/*PROCEDIMENTO UTILIZADO PARA ALTERAR O INDICADOR CONTABIL DE - 1 PARA 0 - NA TABELA GRAZZ.GRZ_LOC_MVTO, 
POIS ESSE INDICADOR É NECESSÁRIO PARA A REALIZAÇÃO DA IMPORTAÇÃO DAS INFORMAÇÕES DE VALORES DE EMPRÉSTIMOS DO ZLOCAÇÕES DAS FILIAIS GERADAS PELA JURIDICA E IMPORTADAS PELA CONTABILIDADE*/


/*MAPEIAS OS DADOS*/

SELECT A.SEQ_MOVIMENTO,
       A.COD_PESSOA,
       B.DES_PESSOA AS DES_PESSOA_ORIGEM,
       A.COD_UNIDADE,
       A.VAL_TOTAL,
       A.VAL_LIQUIDO,
       A.COD_PESS_RECEB,
       A.DTA_VCTO,
       A.DTA_SISTEMA,
       PS.DES_PESSOA AS DES_PESSOA_RECEB,
       LC.COD_PESSOA,
       A.IND_CONTABIL
  FROM GRAZZ.GRZ_LOC_MVTO A
  JOIN GRAZZ.GRZ_PESSOAS B ON B.COD_PESSOA = A.COD_PESSOA
  JOIN GRAZZ.GRZ_PESSOAS PS ON PS.COD_PESSOA = A.COD_PESS_RECEB
  JOIN GRAZZ.GRZ_LOC_LOCADORES LC ON A.COD_PESSOA = LC.COD_PESSOA
 WHERE A.IND_CONTABIL = 0
   AND A.DTA_SISTEMA >= '01/07/2025'
   AND A.COD_UNIDADE = 199
   AND A.COD_PESSOA = 1052;

/*UPDATE PARA ALTERAR O INDICADOR DEIXANDO-O COM O ZERO 0*/

UPDATE GRAZZ.GRZ_LOC_MVTO A
   SET A.IND_CONTABIL = 0
 WHERE A.IND_CONTABIL = 1
   AND A.DTA_SISTEMA >= '01/07/2025'
   AND A.COD_UNIDADE = 199
   AND A.COD_PESSOA = 1052;