/* ======================================================
   == RECRIANDO SQL DO RELATÓRIO DE CONTAGENS DE ITENS ==
   ====================================================== */


WITH
PARAMS AS (
SELECT  TO_DATE('&DATA_INICIO','DD/MM/YYYY') AS DATA_INICIO,
        TO_DATE('&DATA_FIM','DD/MM/YYYY') AS DATA_FIM,
        &UNIDADE AS UNIDADE,
        &TAREFA AS TAREFA
FROM DUAL
       

), 

TAREFAS_HISTORICOS AS (
SELECT A.*
FROM SISLOGWEB.GRZ_CONT_TAREFAS_ITENS_HIST A
CROSS JOIN PARAMS P
WHERE A.COD_USUARIO = 394611
  AND A.DTA_SISTEMA >= P.DATA_INICIO
  AND A.DTA_SISTEMA <  P.DATA_FIM + 1 
  AND A.SEQ_TAREFA = 581001
  AND A.COD_ITEM   = 518589

),

/* =====*/

TAREFAS AS (
SELECT A.*
FROM SISLOGWEB.GRZ_CONT_TAREFAS_ITENS A
CROSS JOIN PARAMS P
WHERE A.COD_USUARIO = 394611
AND A.DTA_ATUALIZADO >= P.DATA_INICIO
AND A.DTA_ATUALIZADO <  P.DATA_FIM + 1
AND A.SEQ_TAREFA = 581001
AND A.COD_ITEM = 518589

),

--SELECT * FROM TAREFAS_HISTORICOS

/* =====*/

TOTAL_TAREFAS AS (
SELECT A.*
FROM SISLOGWEB.GRZ_CONT_TAREFAS A
CROSS JOIN PARAMS P
WHERE A.COD_USUARIO = 394611
  AND A.DTA_SISTEMA >= P.DATA_INICIO
  AND A.DTA_SISTEMA <  P.DATA_FIM + 1

),

DEVOL_DEMONST AS (
/*DEVOLUÇÃO E DEMONSTRAÇÃO*/
SELECT NFI.COD_ITEM AS COD_ITEM,
       SUM(CASE
             WHEN NN.COD_OPERACAO IN (4202, 4203) THEN
              NFI.QTD_MOVIMENTO
             ELSE
              0
           END) AS QTD_DEVOLUCAO,
       SUM(CASE
             WHEN NN.COD_OPERACAO = 340 THEN
              NFI.QTD_MOVIMENTO
             ELSE
              0
           END) AS QTD_SAIDA_DEMO,
       SUM(CASE
             WHEN NN.COD_OPERACAO = 150 THEN
              NFI.QTD_MOVIMENTO
             ELSE
              0
           END) AS QTD_ENTRADA_DEMO
  FROM SISLOGWEB.NFI_NOTAS_ITENS NFI
 INNER JOIN SISLOGWEB.NFI_NOTAS NN ON NN.COD_UNIDADE = NFI.COD_UNIDADE
                                  AND NN.NUM_NOTA = NFI.NUM_NOTA
 PARAMS P
 WHERE NFI.DTA_MOVIMENTO >= P.DATA_INICIO
   AND NFI.DTA_MOVIMENTO < P.DATA_FIM
   AND NFI.COD_ITEM = 518589
   AND NFI.COD_UNIDADE = 581
 GROUP BY NFI.COD_ITEM 
 
)




/*SELEÇÃO FINAL DE RESULTADOS*/

SELECT TH.SEQ_TAREFA,
       TH.COD_ITEM,
       TH.COD_EDITADO,
       TH.DES_ITEM,
       SUM(NVL(TR.QTD_CONTADA), 0) AS QTD_CONTADA,
       TR.COD_USUARIO
FROM TAREFAS_HISTORICOS TH
LEFT JOIN TAREFAS TR ON TR.SEQ_TAREFA = TH.SEQ_TAREFA
                    AND TR.COD_ITEM = TH.COD_ITEM
LEFT JOIN TOTAL_TAREFAS TF ON TF.SEQ = TH.SEQ_TAREFA
