/*SQL - MOVIMENTOS*/
SELECT
    A.COD_UNIDADE,
    A.DTA_MOVIMENTO,
    NVL(MAX(A.VLR_LP), 0) AS VLR_LP
FROM ES_0124_CR_PROJECAO A
WHERE A.DTA_MOVIMENTO >= DATE '2025-11-01'
  AND A.DTA_MOVIMENTO <  DATE '2026-02-01'
  AND A.COD_UNIDADE <> 0
  AND A.COD_GRUPO_LCTO = 57
  AND A.COD_QUEBRA_LCTO = 1
  --AND A.VLR_LP = 0
  AND A.COD_UNIDADE IN (653, 654, 656)
GROUP BY
    A.COD_UNIDADE,
    A.DTA_MOVIMENTO
order by A.DTA_MOVIMENTO