SELECT DISTINCT
       LO.COD_UNIDADE     AS "UNIDADE",
       LO.COD_USUARIO     AS "CÓDIGO USUÁRIO LOGADO",
       FUN.DES_NOME       AS "NOME FUNCIONÁRIO LOGADO",
       LO.HORA_INICIAL    AS "LOGIN INICIAL",
       LO.HORA_FINAL      AS "LOGIN FINAL",
       LO.TEMPO_LOGIN     AS "TEMPO DE LOGIN DO USUÁRIO",
       LO.NUM_EQUIPAMENTO AS "PDV",
       LO.DTA_MOVIMENTO   AS "DATA MOVIMENTO DO LOGIN/ACESSO",
       LIB.COD_ACESSO     AS "CÓDIGO DO ACESSO",
       LI.DES_ACESSO      AS "DESCRIÇÃO DO ACESSO",
       LIB.DTA_MVTO
  FROM GRAZZ.GER_TEMPO_LOGIN LO
  JOIN SISLOGWEB.GRZ_ARH_FUNCIONARIOS FUN
    ON FUN.COD_FUNCIONARIO = LO.COD_USUARIO
  JOIN GRAZZ.GER_MVTO_ACESSOS LIB
     on lib.cod_operador = lo.cod_usuario
    AND LIB.DTA_MVTO = LO.DTA_MOVIMENTO
    and LIB.NUM_EQUIPAMENTO = LO.NUM_EQUIPAMENTO
  JOIN SISLOGWEB.GER_ACESSOS LI
    ON LI.COD_ACESSO = LIB.COD_ACESSO
 WHERE LO.DTA_MOVIMENTO >= DATE '2026-01-01'
   AND LO.DTA_MOVIMENTO <  DATE '2026-03-02'
   AND TRUNC(LIB.DTA_MVTO) >= '01/01/2026'
   AND TRUNC(LIB.DTA_MVTO) <= '01/03/2026'
   AND LIB.COD_OPERADOR <> 376937
   AND LO.COD_UNIDADE = 580
 ORDER BY LO.HORA_INICIAL;