/*RELAÇÃO DE ACESSOS USUÁRIOS*/
SELECT LIB.COD_EMP AS "REDE",
       LIB.COD_UNIDADE "UNIDADE",
       LIB.COD_OPERADOR    AS "PESSOA LOGADA",
       F2.DES_NOME         AS "NOME DA PESSOA LOGADA",
       LIB.DTA_MVTO AS "DATA DO MOVIMENTO",
       LIB.HORA_MVTO AS "HORA DO MOVIMENTO",
       LIB.NUM_EQUIPAMENTO AS "PDV DA OPERAÇÃO",
       LIB.COD_AUTORIZANTE AS "PESSOA AUTORIZANTE",
       FUN.DES_NOME        AS "NOME DA PESSOA AUTORIZANTE",
       FUN.NUM_CPF         AS "CPF DO ATORIZANTE",
       LIB.COD_ACESSO AS "CÓDIGO DO ACESSO",
       LI.DES_ACESSO AS "DESCRIÇÃO DO ACESSO"

  FROM GRAZZ.GER_MVTO_ACESSOS LIB
  JOIN GER_ACESSOS LI
    ON LI.COD_ACESSO = LIB.COD_ACESSO
  JOIN GRZ_ARH_FUNCIONARIOS FUN
    ON FUN.COD_FUNCIONARIO = LIB.COD_AUTORIZANTE
  JOIN GRZ_ARH_FUNCIONARIOS F2
    ON F2.COD_FUNCIONARIO = LIB.COD_OPERADOR
 WHERE LIB.COD_UNIDADE = 580
   AND TRUNC(LIB.DTA_MVTO) >= '01/01/2026'
   AND TRUNC(LIB.DTA_MVTO) <= '01/03/2026'
   AND LIB.COD_OPERADOR <> 376937
 ORDER BY LIB.DTA_MVTO ASC;

/*========================================================*/

SELECT DISTINCT
       LO.COD_UNIDADE     AS "UNIDADE",
       LO.COD_USUARIO     AS "CÓDIGO USUÁRIO LOGADO",
       FUN.DES_NOME       AS "NOME FUNCIONÁRIO LOGADO",
       LO.HORA_INICIAL    AS "LOGIN INICIAL",
       LO.HORA_FINAL      AS "LOGIN FINAL",
       LO.TEMPO_LOGIN     AS "TEMPO DE LOGIN DO USUÁRIO",
       LO.NUM_EQUIPAMENTO AS "PDV",
       LO.DTA_MOVIMENTO   AS "DATA MOVIMENTO DO LOGIN/ACESSO",
       LIB.COD_ACESSO     AS "CÓDIGO DO ACESSO",
       LI.DES_ACESSO      AS "DESCRIÇÃO DO ACESSO",
       LIB.DTA_MVTO
  FROM GRAZZ.GER_TEMPO_LOGIN LO
  JOIN SISLOGWEB.GRZ_ARH_FUNCIONARIOS FUN
    ON FUN.COD_FUNCIONARIO = LO.COD_USUARIO
  JOIN GRAZZ.GER_MVTO_ACESSOS LIB
     on lib.cod_operador = lo.cod_usuario
    AND LIB.DTA_MVTO = LO.DTA_MOVIMENTO
    and LIB.NUM_EQUIPAMENTO = LO.NUM_EQUIPAMENTO
  JOIN SISLOGWEB.GER_ACESSOS LI
    ON LI.COD_ACESSO = LIB.COD_ACESSO
 WHERE LO.DTA_MOVIMENTO >= DATE '2026-01-01'
   AND LO.DTA_MOVIMENTO <  DATE '2026-03-02'
   AND TRUNC(LIB.DTA_MVTO) >= '01/01/2026'
   AND TRUNC(LIB.DTA_MVTO) <= '01/03/2026'
   AND LIB.COD_OPERADOR <> 376937
   AND LO.COD_UNIDADE = 580
 ORDER BY LO.HORA_INICIAL;