SELECT CX.COD_EMP             AS REDE,
       CX.COD_UNIDADE,
       CX.DTA_MVTO,
       CX.DTA_FECHAMENTO,
       CX.DES_HORA_FECHAMENTO AS HORA_FECHAMENTO,
       CX.COD_USUARIO,
       FUN.DES_NOME
  FROM SISLOGWEB.CXS_SALDO_CAIXAS CX
  JOIN SISLOGWEB.GRZ_ARH_FUNCIONARIOS FUN
    ON FUN.COD_FUNCIONARIO = CX.COD_USUARIO
 WHERE CX.DTA_MVTO <> DTA_FECHAMENTO
   AND CX.DTA_MVTO >= '01/01/2026'
 ORDER BY CX.DTA_MVTO ASC, CX.COD_UNIDADE ASC
