/*SQL PARA GERAR REL DE ITENS CANCELADOS
  -- ESSE NOS ÚLTIMOS 6 MESES*/
SELECT A.COD_UNIDADE,
       A.DTA_MOVIMENTO,
       A.HOR_MOVIMENTO,
       A.COD_ESTRUTURADO,
       B.COD_NIV2 AS SETOR,
       A.COD_ITEM,
       C.DES_ITEM,
       A.VLR_TOTAL,
       A.SEQ_CUPOM
  FROM SISLOGWEB.EST_CUPOM_ITENS_CANC A
  JOIN NL.IE_MASCARAS B ON A.COD_ITEM = B.COD_ITEM
  JOIN NL.IE_ITENS C ON A.COD_ITEM = C.COD_ITEM
 WHERE B.COD_NIV2 IN (30, 34, 38)
   AND A.DTA_MOVIMENTO >= ADD_MONTHS(TRUNC(SYSDATE), -6)
   AND A.DTA_MOVIMENTO < TRUNC(SYSDATE) + 1
   AND A.COD_UNIDADE = 360
   AND B.COD_MASCARA = 170;