WITH
DADOS_PREVENTIVA AS (
SELECT LAST_DAY(MES) AS DTA_MOVIMENTO, -- OU TRUNC(MES,'MM') SE PREFERIR 01/MM
       COD_UNIDADE,
       MAX(REGIAO) AS REGIAO, -- COLAPSA PARA UM VALOR POR MÊS
       MAX(REDE) AS REDE, -- IDEM
       VLR_PREV_MES AS VLR_PREVENTIVA,
       SUM(CASE
             WHEN X.VLR_PREV_MES > 0 THEN
              1
             ELSE
              0
           END) OVER(PARTITION BY X.COD_UNIDADE) AS QTD_MESES
  FROM (SELECT TRUNC(A.DTA_MOVIMENTO, 'MM') AS MES,
               A.COD_UNIDADE,
               /* MESMAS REGRAS QUE VOCÊ USOU */
               CASE
                 WHEN TO_CHAR(A.COD_GRUPO_UNI) LIKE '%8%' THEN
                  A.COD_GRUPO_UNI
               END AS REGIAO,
               CASE
                 WHEN TO_CHAR(A.COD_QUEBRA_UNI) NOT LIKE '%8%' THEN
                  A.COD_QUEBRA_UNI
               END AS REDE,
               NVL(A.VLR_PREVENTIVO, 0) AS VLR_PREV_MES
          FROM ES_0124_CR_PROJECAO A
         WHERE A.DTA_MOVIMENTO >= '01/01/2025'
           AND A.DTA_MOVIMENTO <= '31/03/2025' -- INCLUI TODO 31/03
           AND A.COD_QUEBRA_LCTO = 1
           AND A.COD_UNIDADE <> 0
           --AND A.COD_UNIDADE = 592
           ) X
 GROUP BY MES, COD_UNIDADE, VLR_PREV_MES
 ORDER BY COD_UNIDADE, MES

),

CALC_PREVENTIVA AS (
SELECT COD_UNIDADE,
       REGIAO,
       REDE,
       SUM(NVL(VLR_PREVENTIVA, 0)) AS VLR_PREVENTIVA,
       QTD_MESES
FROM DADOS_PREVENTIVA 
GROUP BY COD_UNIDADE, QTD_MESES, REGIAO, REDE

)

SELECT COD_UNIDADE,
       QTD_MESES,
       CASE
         WHEN QTD_MESES > 0 THEN
          TRUNC(VLR_PREVENTIVA / QTD_MESES, 2)
         ELSE
          0
       END AS PREVENTIVA
  FROM CALC_PREVENTIVA
WHERE REGIAO = 8708
AND REDE = 10
ORDER BY COD_UNIDADE