/* =====================================================================================
   ==== VERSÃO DE TESTES = RELATÓRIO DE ÍNDICES DE NÃO CONFORMIDADES DA AUDITORIAS = VERSÃO POR REGIÃO ====
   ===================================================================================== */
--REGIAO
SELECT A.COD_EMP, 
       A.COD_UNIDADE, 
       CASE 
           WHEN A.COD_UNIDADE = 8730 THEN
            'E-COMERCE'
           WHEN A.COD_UNIDADE = 9999 THEN
            'GERAL'
           ELSE
            A.COD_EMP ||' - '|| UPPER(GRZ_UTIL.BUSCA_DES_UNIDADE(A.COD_UNIDADE)) 
       END AS DES_FANTASIA, 
       CASE
           WHEN B.COD_REGIAO IS NOT NULL THEN
            B.COD_REGIAO
           ELSE
            9999
       END AS COD_REGIAO,
       A.INVENT_MAX,
       '&DDATAMES1' || ' - ' || '&DDATAMES3' AS PERIODO,
       
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES1', A.CRES,0))CRES_MES1, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES2', A.CRES,0))CRES_MES2, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES3', A.CRES,0))CRES_MES3,
       
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES1', A.DEVOL,0))DEVOL_MES1, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES2', A.DEVOL,0))DEVOL_MES2, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES3', A.DEVOL,0))DEVOL_MES3,
       
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES1', A.INVENT,0))INVENT_MES1, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES2', A.INVENT,0))INVENT_MES2, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES3', A.INVENT,0))INVENT_MES3, 
       
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES1', A.CUP_CANC,0))CUP_CANC_MES1, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES2', A.CUP_CANC,0))CUP_CANC_MES2, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES3', A.CUP_CANC,0))CUP_CANC_MES3, 
      
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES1', A.ITE_CANC,0))ITE_CANC_MES1, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES2', A.ITE_CANC,0))ITE_CANC_MES2, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES3', A.ITE_CANC,0))ITE_CANC_MES3, 
       
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES1', A.CREDIARIO,0))CREDIARIO_MES1, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES2', A.CREDIARIO,0))CREDIARIO_MES2, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES3', A.CREDIARIO,0))CREDIARIO_MES3, 
      
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES1', A.F4,0))F4_MES1, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES2', A.F4,0))F4_MES2, 
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES3', A.F4,0))F4_MES3, 
             
       SUM(DECODE(TO_CHAR(A.DTA_MOVIMENTO,'DD/MM/YYYY'),'&DDATAMES3', A.RANK,0))RANK, 
       A.TIPO_UNIDADE   
  FROM SISLOGWEB.GRZ_NAO_CONFORMIDADES_INDICES A
  LEFT JOIN V_REGIAO_UNIDADES_AVT B ON A.COD_UNIDADE = B.COD_UNIDADE
 WHERE A.DTA_MOVIMENTO BETWEEN '&DDATAMES1'  AND '&DDATAMES3' 
   --AND A.COD_EMP = &REDE 
   --AND COD_UNIDADE IN (140, 154, 160, 267)
   AND A.IND_REDE = 0 
   --AND COD_REGIAO BETWEEN :SREGINI AND :SREGFIM 
 GROUP BY A.COD_EMP,
          A.COD_UNIDADE, 
          UPPER(GRZ_UTIL.BUSCA_DES_UNIDADE(A.COD_UNIDADE)), 
          B.COD_REGIAO, 
          A.INVENT_MAX, 
          A.TIPO_UNIDADE 
 ORDER BY A.COD_UNIDADE, 
          B.COD_REGIAO, 
          A.TIPO_UNIDADE, 
          RANK DESC;

