/*=== SQL -  RELATÓRIO DE ACESSOS DAS LOJAS ===*/

SELECT DISTINCT A.COD_EMP,
                A.COD_UNIDADE,
                UNI.COD_QUEBRA AS COD_GRUPO,
                GE.DES_NOME DES_UNIDADE,
                A.DTA_MVTO,
                A.COD_OPERADOR,
                A.COD_ACESSO,
                A.COD_AUTORIZANTE,
                A.HORA_MVTO,
                A.COD_NIVEL_ACESSO,
                A.COD_NIVEL_AUTORIZANTE,
                A.NUM_EQUIPAMENTO,
                A.NUM_CUPOM,
                (SELECT B.DES_PESSOA
                   FROM NL.PS_MASCARAS C, NL.PS_PESSOAS B
                  WHERE C.COD_COMPLETO = '0100' || A.COD_OPERADOR
                    AND C.COD_PESSOA = B.COD_PESSOA
                    AND C.COD_MASCARA = 50
                    AND ROWNUM <= 1) AS DES_OPERADOR,
                (SELECT B.DES_PESSOA
                   FROM NL.PS_MASCARAS C, NL.PS_PESSOAS B
                  WHERE C.COD_COMPLETO = '0100' || A.COD_AUTORIZANTE
                    AND C.COD_PESSOA = B.COD_PESSOA
                    AND C.COD_MASCARA = 50
                    AND ROWNUM <= 1) AS DES_AUTORIZANTE,
                DECODE(A.COD_NIVEL_AUTORIZANTE, 99, 1, 0) NIVEL_99, -- SE NÃO MARCAR DESCONSIDERAR TI
                DECODE(A.COD_NIVEL_AUTORIZANTE, 30, 1, 0) NIVEL_30,
                DECODE(A.COD_NIVEL_AUTORIZANTE, 20, 1, 0) NIVEL_20,
                DECODE(A.COD_NIVEL_AUTORIZANTE, 10, 1, 1, 1, 0) NIVEL_10
  FROM SISLOGWEB.GRZ_LOJAS_MVTO_ACESSOS A,
       NL.GE_UNIDADES                   GE,
       NL.GE_GRUPOS_UNIDADES            UNI
 WHERE A.COD_UNIDADE = GE.COD_UNIDADE
   AND UNI.COD_EMP = 1
      --AND UNI.COD_GRUPO = :IGRUPO 
      --AND ((:IREDE = 999 AND A.COD_EMP IN (10,30,40,50,70)) OR (:IREDE <> 999 AND A.COD_EMP = :IREDE)) 
   AND A.COD_UNIDADE BETWEEN 580 AND 580
      --AND A.COD_ACESSO = :SCODACESSO   -- SE ESCOLHER UM CÓDIGO DE ACESSO
   AND A.COD_OPERADOR BETWEEN 387788 AND 394575
      --AND A.NUM_EQUIPAMENTO BETWEEN :IEQUIPAMENTOINI AND :IEQUIPAMENTOFIM 
   AND A.DTA_MVTO BETWEEN '01/01/2026' AND '01/03/2026'
   AND UNI.COD_UNIDADE = A.COD_UNIDADE
--AND A.COD_AUTORIZANTE <> 1    -- SE MARCAR DESCONSIDERAR TI
 ORDER BY A.COD_UNIDADE, A.DTA_MVTO, A.COD_OPERADOR, A.NUM_CUPOM;