CREATE OR REPLACE VIEW PESSOA_FISICA AS
SELECT PESSOA.COD_PESSOA,
       PESSOA.NOME_PESSOA,
       LOGRA.NOME_LOGRA,
       FISICA.COD_MUNIC,
       FISICA.TIPO_LOGRA,
       TIPLOG.NOME_TIP_LOGRA,
       FISICA.COD_LOGRA,
       FISICA.COD_BAIRRO,
       FISICA.APELIDO,
       FISICA.DT_NASC,
       FISICA.DDD_FONE_CEL,
       FISICA.FONE_CEL,
       FISICA.FONE_ALTER,
       FISICA.DOC_UNICO,
       FISICA.SENHA,
       FISICA.REFERENCIA,
       FISICA.NUMERO,
       FISICA.COMPLEMENTO,
       BAIRRO.NOME_BAIRRO,
       MUNICI.NOME_MUNIC,
       FISICA.CEP,
       FISICA.COD_UF,
       FISICA.CPF,
       FISICA.DDD,
       FISICA.FONE,
       FISICA.EMAIL,
       FISICA.EMAIL_ALTER,
       FISICA.FAX,
       FISICA.RAMAL,
       FISICA.SEXO,
       FISICA.IND_CASA_PROPRIA,
       FISICA.IND_RECURSO_FGTS
  FROM LOGRA  LOGRA,
       PESSOA PESSOA,
       FISICA FISICA,
       MUNICI MUNICI,
       BAIRRO BAIRRO,
       TIPLOG TIPLOG
 WHERE (PESSOA.COD_PESSOA = FISICA.COD_PESSOA(+))
   AND (FISICA.COD_UF = LOGRA.COD_UF(+))
   AND (FISICA.COD_MUNIC = LOGRA.COD_MUNIC(+))
   AND (FISICA.COD_LOGRA = LOGRA.COD_LOGRA(+))
   AND (FISICA.COD_UF = MUNICI.COD_UF(+))
   AND (FISICA.COD_MUNIC = MUNICI.COD_MUNIC(+))
   AND (FISICA.COD_UF = BAIRRO.COD_UF(+))
   AND (FISICA.COD_MUNIC = BAIRRO.COD_MUNIC(+))
   AND (FISICA.COD_BAIRRO = BAIRRO.COD_BAIRRO(+))
   AND (FISICA.TIPO_LOGRA = TIPLOG.TIP_LOGRA(+))
   AND (PESSOA.TIPO_PESSOA = 'F')

