CREATE OR REPLACE VIEW V_AFAST_COLAB_AVT AS
SELECT 
    CT.COD_CONTRATO,
    NVL(MAX(CASE
        WHEN TRUNC(SYSDATE) BETWEEN A.DATA_INICIO AND A.DATA_FIM THEN A.COD_CAUSA_AFAST
        ELSE NULL
    END), 0) AS COD_CAUSA_AFAST,
    
    MAX(CASE
        WHEN TRUNC(SYSDATE) BETWEEN A.DATA_INICIO AND A.DATA_FIM THEN B.NOME_CAUSA_AFAST
        ELSE NULL
    END) AS NOME_CAUSA_AFAST,

    MAX(CASE
        WHEN TRUNC(SYSDATE) BETWEEN A.DATA_INICIO AND A.DATA_FIM THEN A.DATA_INICIO
        ELSE NULL
    END) AS DATA_INICIO,

    MAX(CASE
        WHEN TRUNC(SYSDATE) BETWEEN A.DATA_INICIO AND A.DATA_FIM THEN A.DATA_FIM
        ELSE NULL
    END) AS DATA_FIM,

    'DADOS ANTERIORES ==>' AS ESPACO,

    MAX(PREV.COD_CAUSA_AFAST) AS COD_CAUSA_AFAST_ANT,
    MAX(PREV.NOME_CAUSA_AFAST) AS NOME_CAUSA_AFAST_ANT,
    MAX(PREV.DATA_INICIO) AS DATA_INICIO_ANT,
    MAX(PREV.DATA_FIM) AS DATA_FIM_ANT

FROM RHFP0300 CT
LEFT JOIN RHFP0306 A ON CT.COD_CONTRATO = A.COD_CONTRATO
LEFT JOIN RHFP0100 B ON A.COD_CAUSA_AFAST = B.COD_CAUSA_AFAST
LEFT JOIN (
    SELECT P.COD_CONTRATO,
           P.COD_CAUSA_AFAST,
           Q.NOME_CAUSA_AFAST,
           P.DATA_INICIO,
           P.DATA_FIM
      FROM RHFP0306 P
     JOIN RHFP0100 Q ON P.COD_CAUSA_AFAST = Q.COD_CAUSA_AFAST
     WHERE P.DATA_FIM >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1)
       AND P.DATA_INICIO < TRUNC(SYSDATE, 'MM')
) PREV ON CT.COD_CONTRATO = PREV.COD_CONTRATO

GROUP BY CT.COD_CONTRATO;


