CREATE OR REPLACE VIEW V_CONTRATOS_DEMITIDOS_AVT AS
SELECT DISTINCT
       A.COD_CONTRATO,
       B.NOME_PESSOA AS DES_PESSOA,
       E.COD_FUNCAO,
       E.DES_FUNCAO,
       E.DATA_INI_CLH,
       E.DATA_FIM_CLH,
       D.COD_UNIDADE,
       D.DES_UNIDADE,
       D.COD_TIPO,
       D.DES_TIPO,
       D.COD_REDE,
       D.DES_REDE,
       D.EDICAO_ORG_2 AS COD_EMP,
       D.NOME2 AS DES_EMP,
       A.DATA_INICIO AS DATA_ADMISSAO,
       A.DATA_FIM AS DATA_DEMISSAO,
       A.COD_CAUSA_DEMISSAO AS COD_DEMISSAO,
       C.NOME_CAUSA_DEMISSAO AS DES_DEMISSAO
  FROM RHFP0300 A
 INNER JOIN PESSOA_FISICA B ON A.COD_FUNC = B.COD_PESSOA
  LEFT JOIN RHFP0102 C ON A.COD_CAUSA_DEMISSAO = C.COD_CAUSA_DEMISSAO
 INNER JOIN VH_EST_ORG_CONTRATO_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO AND D.DATA_FIM_ORG = '31/12/2999'
 INNER JOIN VH_CARGO_CONTRATO_AVT E ON A.COD_CONTRATO = E.COD_CONTRATO AND E.DATA_FIM_CLH = '31/12/2999'
 WHERE A.DATA_FIM IS NOT NULL
 ORDER BY A.DATA_FIM

