CREATE OR REPLACE VIEW V_DADOS_COLAB_AVT_2 AS
WITH CTE_ORGANOGRAMA AS (
    SELECT ORG.*, VO.COD_REDE, VO.DES_REDE, VO.COD_REGIAO, VO.DES_REGIAO, VO.COD_TIPO, VO.DES_TIPO,
           ROW_NUMBER() OVER (PARTITION BY ORG.COD_CONTRATO ORDER BY ORG.DATA_INICIO DESC) AS RN
    FROM VH_EST_ORG_CONTRATO_AVT ORG
    LEFT JOIN V_ORGANOGRAMAS_AVT VO ON ORG.COD_ORGANOGRAMA = VO.COD_ORGANOGRAMA
    WHERE SYSDATE BETWEEN ORG.DATA_INICIO AND NVL(ORG.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
),
CTE_AFAST AS (
    SELECT AFAST.COD_CONTRATO, AFAST.COD_CAUSA_AFAST, AFAST.NOME_CAUSA_AFAST, 
           AFAST.DATA_INICIO, AFAST.DATA_FIM,
           ROW_NUMBER() OVER (PARTITION BY AFAST.COD_CONTRATO ORDER BY AFAST.DATA_INICIO DESC) AS RN
    FROM V_AFAST_COLAB_AVT AFAST
),
CTE_CARGO_ANTERIOR AS (
    SELECT CC.COD_CONTRATO, CC.COD_CLH_ANT, CC.DES_CLH_ANT, CC.DATA_INICIO_ANT, CC.DATA_FIM_ANT,
           ROW_NUMBER() OVER (PARTITION BY CC.COD_CONTRATO ORDER BY CC.DATA_INICIO_ANT DESC) AS RN
    FROM V_CARGO_CONTRATO_AVT CC
),
CTE_ORGANOGRAMA_ANTERIOR AS (
    SELECT CO.COD_CONTRATO, CO.EDICAO_ORG_ANT, CO.DES_ORGANOGRAMA_ANT, CO.DATA_INICIO_ORG_ANT, CO.DATA_FIM_ORG_ANT,
           ROW_NUMBER() OVER (PARTITION BY CO.COD_CONTRATO ORDER BY CO.DATA_INICIO_ORG_ANT DESC) AS RN
    FROM V_ORGANOGRAMA_CONTRATO_AVT CO
)
SELECT /*DADOS DO CONTRATO*/
    PF.COD_PESSOA,
    CT.COD_CONTRATO,
    CASE
        WHEN CT.DATA_INICIO > SYSDATE THEN NULL
        ELSE INITCAP(PF.NOME_PESSOA)
    END AS DES_PESSOA,
    CT.DATA_INICIO AS DATA_ADMISSAO,
    CT.DATA_FIM AS DATA_DEMISSAO,
    CT.COD_CAUSA_DEMISSAO AS COD_DEMISSAO,
    DEM.NOME_CAUSA_DEMISSAO AS DES_DEMISSAO,
    FUNC.COD_CLH AS COD_FUNCAO,
    FUNC.COD_CLH || ' - ' || FUNC.NOME_CLH AS DES_FUNCAO,
    CT_FUNC.DATA_INICIO AS DATA_INICIO_CLH,
    CT_FUNC.DATA_FIM AS DATA_FIM_CLH,
    CT.COD_VINCULO_EMPREG,
    CT_TUR.COD_TURNO,
    TURNO.NOME_TURNO AS DES_TURNO,
    HR.QTD_HORBAS_MES AS HR_BASE_MES,
    HR.QTD_HORBAS_SEM AS HR_BASE_SEM,
    HR.QTD_HORBAS_DIA AS HR_BASE_DIA,
    HR.DATA_INICIO AS DATA_INICIO_HR,
    HR.DATA_FIM AS DATA_FIM_HR,
    CASE
        WHEN CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < SYSDATE THEN 1
        ELSE 0
    END AS STATUS,
    CASE
        WHEN CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < SYSDATE THEN 'INATIVO'
        WHEN CT.DATA_INICIO <= SYSDATE THEN 'ATIVO'
        WHEN CT.DATA_INICIO > SYSDATE THEN 'ADMISSAO FUTURA'
    END AS DESC_STATUS,
    /*DADOS DO ORGANOGRAMA DO CONTRATO*/
    ORG.COD_ORGANOGRAMA,
    ORG.EDICAO_ORG AS COD_UNIDADE,
    ORG.EDICAO_ORG || ' - ' || ORG.NOME_ORGANOGRAMA AS DES_UNIDADE,
    ORG.DATA_INICIO AS DATA_INICIO_ORG,
    ORG.DATA_FIM AS DATA_FIM_ORG,
    RESP.IND_RESP_UNI AS IND_RESP_UNI,
    ORG.COD_REDE AS COD_REDE_LOCAL,        -- Correção para ORG ao invés de VO
    ORG.DES_REDE AS DES_REDE_LOCAL,        -- Correção para ORG ao invés de VO
    ORG.COD_REGIAO,                        -- Correção para ORG ao invés de VO
    ORG.DES_REGIAO,                        -- Correção para ORG ao invés de VO
    ORG.COD_ORG_1 AS COD_GRUPO_EMP,
    ORG.EDICAO_ORG_1 AS EDICAO_GRUPO_EMP,
    ORG.NOME1 AS DES_GRUPO_EMP,
    ORG.COD_ORG_2 AS COD_EMP,
    ORG.EDICAO_ORG_2 AS EDICAO_EMP,
    ORG.NOME2 AS DES_EMPRESA,
    ORG.COD_ORG_3 AS COD_ORG_FILIAL,
    ORG.EDICAO_ORG_3 AS EDICAO_FILIAL,
    ORG.NOME3 AS DES_FILIAL,
    ORG.COD_ORG_4 AS COD_ORG_DIVISAO,
    ORG.EDICAO_ORG_4 AS EDICAO_DIVISAO,
    ORG.NOME4 AS DES_DIVISAO,
    ORG.COD_ORG_5 AS COD_ORG_DEPART,
    ORG.EDICAO_ORG_5 AS EDICAO_DEPART,
    ORG.NOME5 AS DES_DEPART,
    ORG.COD_ORG_6 AS COD_ORG_SETOR,
    ORG.EDICAO_ORG_6 AS EDICAO_SETOR,
    ORG.NOME6 AS DES_SETOR,
    ORG.COD_ORG_7 AS COD_ORG_SECAO,
    ORG.EDICAO_ORG_7 AS EDICAO_SECAO,
    ORG.NOME7 AS DES_SECAO,
    ORG.COD_ORG_8 AS COD_ORG_UNI,
    ORG.EDICAO_ORG_8 AS EDICAO_UNI,
    ORG.NOME8 AS DES_UNI,
    CASE
        WHEN LOT_CONT.COD_LOTACAO IS NOT NULL THEN LOT_CONT.COD_LOTACAO
        ELSE NULL
    END AS COD_LOTACAO,
    ORG.COD_TIPO,                          -- Correção para ORG ao invés de VO
    ORG.DES_TIPO,                          -- Correção para ORG ao invés de VO
    /*DADOS PESSOAIS DO CONTRATO*/
    FP02.DATA_NASCIMENTO,
    FP02.SEXO,
    FP02.COD_ESTADO_CIVIL AS COD_EST_CIVIL,
    EC.NOME_ESTADO_CIVIL AS DES_EST_CIVIL,
    PF.EMAIL AS DES_EMAIL,
    PF.DDD_FONE_CEL AS COD_DDD,
    PF.FONE_CEL,
    PF.CPF,
    FP02.NRO_IDENTIDADE,
    PJ.NOME_PESSOA || '/' || FP02.COD_UF_IDENTIDADE AS EMISSOR,
    FP02.NRO_PIS_PASEP,
    FP02.COD_NACIONALIDADE,
    NAC.NOME_NACIONALIDADE || '(a)' AS NACIONALIDADE,
    FP02.COD_NACIONALIDADE || ' - ' || NAC.NOME_NACIONALIDADE || '(a)' AS DES_NACIONALIDADE,
    PF.CEP AS COD_CEP,
    PF.TIPO_LOGRA,
    PF.COD_LOGRA,
    PF.NOME_LOGRA AS DES_LOGRA,
    PF.COD_BAIRRO,
    PF.NOME_BAIRRO AS DES_BAIRRO,
    PF.COD_MUNIC AS COD_CIDADE,
    PF.NOME_MUNIC AS DES_CIDADE,
    PF.COD_UF,
    /*DADOS DE AFASTAMENTOS DO CONTRATO*/
    AFAST.COD_CAUSA_AFAST AS COD_AFAST,
    AFAST.NOME_CAUSA_AFAST AS DES_AFAST,
    AFAST.DATA_INICIO AS DATA_INI_AFAST,
    AFAST.DATA_FIM AS DATA_FIM_AFAST,
    CASE
        WHEN CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < SYSDATE THEN 'INATIVO'
        WHEN AFAST.COD_CAUSA_AFAST <> 0 AND AFAST.COD_CAUSA_AFAST <> 4 AND AFAST.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN 'AFASTADO'
        WHEN AFAST.COD_CAUSA_AFAST = 7 THEN 'EM FÉRIAS'
        WHEN AFAST.COD_CAUSA_AFAST IN (3, 6) THEN 'AFASTADO TEMP'
        WHEN AFAST.COD_CAUSA_AFAST = 4 AND AFAST.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN 'PODERÁ RETORNAR'
        ELSE 'EM ATIVIDADE'
    END AS STATUS_AFAST,
    /*DADOS DE CARGO E ORGANOGRAMAS ANTERIORES DO CONTRATO - O ÚLTIMO ANTES DO ATUAL*/
    'DADOS ANTERIORES DO CONTRATO =>' AS ESPACO,
    CC.COD_CLH_ANT AS COD_FUNCAO_ANT,
    CC.DES_CLH_ANT AS DES_FUNCAO_ANT,
    CC.DATA_INICIO_ANT,
    CC.DATA_FIM_ANT,
    CO.EDICAO_ORG_ANT AS COD_UNIDADE_ANT,
    CO.DES_ORGANOGRAMA_ANT AS DES_UNIDADE_ANT,
    CO.DATA_INICIO_ORG_ANT,
    CO.DATA_FIM_ORG_ANT
    
FROM RHFP0300 CT
INNER JOIN RHFP0200 FP02 ON CT.COD_FUNC = FP02.COD_FUNC
LEFT JOIN PESSOA_JURIDICA PJ ON FP02.COD_ORG_IDENTIDADE = PJ.COD_PESSOA
LEFT JOIN RHFP0104 EC ON FP02.COD_ESTADO_CIVIL = EC.COD_ESTADO_CIVIL
LEFT JOIN RHFP0107 NAC ON FP02.COD_NACIONALIDADE = NAC.COD_NACIONALIDADE
INNER JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
INNER JOIN RHFP0340 CT_FUNC ON CT.COD_CONTRATO = CT_FUNC.COD_CONTRATO
                             AND SYSDATE BETWEEN CT_FUNC.DATA_INICIO AND NVL(CT_FUNC.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
 LEFT JOIN RHFP0500 FUNC ON CT_FUNC.COD_CLH = FUNC.COD_CLH
 
-- DADOS DO ORGANOGRAMA DO CONTRATO
INNER JOIN CTE_ORGANOGRAMA ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO AND ORG.RN = 1
LEFT JOIN V_SUPERIOR_IMEDIATO_AVT RESP ON CT.COD_CONTRATO = RESP.COD_CONTRATO
LEFT JOIN CTE_AFAST AFAST ON CT.COD_CONTRATO = AFAST.COD_CONTRATO AND AFAST.RN = 1
LEFT JOIN RHFP0102 DEM ON CT.COD_CAUSA_DEMISSAO = DEM.COD_CAUSA_DEMISSAO

-- DADOS ANTERIORES DO CONTRATO
LEFT JOIN CTE_CARGO_ANTERIOR CC ON CT.COD_CONTRATO = CC.COD_CONTRATO AND CC.RN = 1
LEFT JOIN CTE_ORGANOGRAMA_ANTERIOR CO ON CT.COD_CONTRATO = CO.COD_CONTRATO AND CO.RN = 1

-- DADOS DO TURNO E HORÁRIOS DO CONTRATO
INNER JOIN RHAF1119 CT_TUR ON CT.COD_CONTRATO = CT_TUR.COD_CONTRATO
                             AND SYSDATE BETWEEN CT_TUR.DATA_INICIO AND CT_TUR.DATA_FIM
INNER JOIN RHAF1145 TURNO ON CT_TUR.COD_TURNO = TURNO.COD_TURNO
INNER JOIN V_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
LEFT JOIN RHFP0309 LOT_CONT ON CT.COD_CONTRATO = LOT_CONT.COD_CONTRATO

WHERE (CT.DATA_FIM IS NULL AND SYSDATE BETWEEN CT.DATA_INICIO AND NVL(CT.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
       OR CT.DATA_FIM >= SYSDATE - 365)


ORDER BY STATUS ASC, DATA_ADMISSAO, DESC_STATUS DESC;
