CREATE OR REPLACE VIEW V_DADOS_COLAB_AVT2_ALT AS
SELECT DISTINCT
    CASE
        WHEN CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < TRUNC(SYSDATE) THEN 1
        ELSE 0
    END AS STATUS,
    CASE
        WHEN CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < TRUNC(SYSDATE) THEN 'INATIVO'
        WHEN CT.DATA_INICIO <= TRUNC(SYSDATE) THEN 'ATIVO'
        WHEN CT.DATA_INICIO > TRUNC(SYSDATE) THEN 'ADMISSAO_FUTURA'
    END AS DESC_STATUS,
    PF.COD_PESSOA,
    CT.COD_CONTRATO,
    CASE
        WHEN CT.DATA_INICIO > TRUNC(SYSDATE) THEN NULL
        ELSE INITCAP(PF.NOME_PESSOA)
    END AS DES_PESSOA,
    CT.DATA_INICIO AS DATA_ADMISSAO,
    CT.DATA_FIM AS DATA_DEMISSAO,
    CT.COD_CAUSA_DEMISSAO AS COD_DEMISSAO,
    DEM.NOME_CAUSA_DEMISSAO AS DES_DEMISSAO,
    FUNC.COD_CLH AS COD_FUNCAO,
    FUNC.COD_CLH || ' - ' || FUNC.NOME_CLH AS DES_FUNCAO,
    CT_FUNC.DATA_INICIO AS DATA_INICIO_CLH,
    CT_FUNC.DATA_FIM AS DATA_FIM_CLH,
    CT.COD_VINCULO_EMPREG,
    CT_TUR.COD_TURNO,
    TURNO.NOME_TURNO AS DES_TURNO,
    HR.QTD_HORBAS_MES AS HR_BASE_MES,
    HR.QTD_HORBAS_SEM AS HR_BASE_SEM,
    HR.QTD_HORBAS_DIA AS HR_BASE_DIA,
    HR.DATA_INICIO AS DATA_INICIO_HR,
    HR.DATA_FIM AS DATA_FIM_HR,
    ORG2.EDICAO_NIVEL3 AS COD_SETOR_LOJA,
    ORG2.EDICAO_NIVEL4 AS EDICAO_AREA,
    ORG2.EDICAO_NIVEL5 AS EDICAO_PAI,
    ORG2.COD_ORGANOGRAMA,
    ORG2.EDICAO_ORG AS COD_UNIDADE,
    ORG2.EDICAO_ORG || ' - ' || ORG1.NOME_ORGANOGRAMA AS DES_UNIDADE,
    ORG2.EDICAO_NIVEL4 AS COD_UNIDADE_SUB,
    ORG2.EDICAO_NIVEL5 AS COD_UNIDADE_PAI,
    CT_ORG.DATA_INICIO AS DATA_INICIO_ORG,
    CT_ORG.DATA_FIM AS DATA_FIM_ORG,
    RESP.IND_RESP_UNI AS IND_RESP_UNI,
    CASE
        WHEN ORG2.EDICAO_NIVEL3 = '013' AND ORG2.EDICAO_NIVEL2 = '008' THEN 3
        WHEN ORG2.EDICAO_NIVEL3 = '001' AND ORG2.EDICAO_NIVEL2 = '008' THEN 2
        WHEN ORG2.EDICAO_NIVEL3 = '001' AND ORG2.EDICAO_NIVEL2 = '004' OR
             ORG2.EDICAO_NIVEL3 = '001' AND ORG2.EDICAO_NIVEL2 = '006' OR
             ORG2.EDICAO_NIVEL3 = '002' AND ORG2.EDICAO_NIVEL2 = '128' OR
             ORG2.EDICAO_NIVEL3 = '002' AND ORG2.EDICAO_NIVEL2 = '276' OR
             ORG2.EDICAO_NIVEL3 = '001' AND ORG2.EDICAO_NIVEL2 = '282' THEN 4
        ELSE 1
    END AS COD_TIPO,
    CASE
        WHEN ORG2.EDICAO_NIVEL3 = '013' AND ORG2.EDICAO_NIVEL2 = '008' THEN 'DEPÓSITO'
        WHEN ORG2.EDICAO_NIVEL3 = '001' AND ORG2.EDICAO_NIVEL2 = '008' THEN 'SETOR'
        WHEN ORG2.EDICAO_NIVEL3 = '001' AND ORG2.EDICAO_NIVEL2 = '004' OR
             ORG2.EDICAO_NIVEL3 = '001' AND ORG2.EDICAO_NIVEL2 = '006' OR
             ORG2.EDICAO_NIVEL3 = '002' AND ORG2.EDICAO_NIVEL2 = '128' OR
             ORG2.EDICAO_NIVEL3 = '002' AND ORG2.EDICAO_NIVEL2 = '276' OR
             ORG2.EDICAO_NIVEL3 = '001' AND ORG2.EDICAO_NIVEL2 = '282' THEN 'COLIGADA'
        ELSE 'LOJA'
    END AS DES_TIPO,
    CASE
        WHEN ORG3.EDICAO_NIVEL3 = 1 THEN TO_CHAR(10)
        WHEN ORG3.EDICAO_NIVEL3 = 2 THEN TO_CHAR(50)
        WHEN ORG3.EDICAO_NIVEL3 = 3 THEN TO_CHAR(30)
        WHEN ORG3.EDICAO_NIVEL3 = 4 THEN TO_CHAR(40)
        WHEN ORG3.EDICAO_NIVEL3 = 7 THEN TO_CHAR(70)
        WHEN ORG2.COD_NIVEL3 = 9 THEN TO_CHAR(ORG2.EDICAO_NIVEL3)
        WHEN ORG2.COD_NIVEL3 = 21 THEN TO_CHAR(ORG2.EDICAO_NIVEL3)
        ELSE NULL
    END AS COD_REDE_LOCAL,
    DECODE(CASE
               WHEN ORG3.EDICAO_NIVEL3 = 1 THEN TO_CHAR(10)
               WHEN ORG3.EDICAO_NIVEL3 = 2 THEN TO_CHAR(50)
               WHEN ORG3.EDICAO_NIVEL3 = 3 THEN TO_CHAR(30)
               WHEN ORG3.EDICAO_NIVEL3 = 4 THEN TO_CHAR(40)
               WHEN ORG3.EDICAO_NIVEL3 = 7 THEN TO_CHAR(70)
               WHEN ORG2.COD_NIVEL3 = 9 THEN TO_CHAR(ORG2.EDICAO_NIVEL3)
               WHEN ORG2.COD_NIVEL3 = 21 THEN TO_CHAR(ORG2.EDICAO_NIVEL3)
               ELSE TO_CHAR(0)
           END, 10, 'GRZ', 50, 'TOT', 30, 'PRM', 40, 'FRG', 70, 'GZT', 001, 'ADM', 013, 'CD') AS DES_REDE_LOCAL,
    CASE
        WHEN ORG3.EDICAO_CUSTO_CONT IN ('811', '815', '831', '835', '841', '845', '851', '855', '871') THEN TO_CHAR(ORG2.EDICAO_NIVEL3)
        ELSE NULL
    END AS COD_AREA_COMERCIAL_SUB,
    DECODE(CASE
               WHEN ORG3.EDICAO_CUSTO_CONT IN ('811', '815', '831', '835', '841', '845', '851', '855', '871') THEN TO_CHAR(ORG2.EDICAO_NIVEL3)
               ELSE TO_CHAR(0)
           END, '001', 'ADM', TO_CHAR(0), NULL) AS DES_AREA_COMERCIAL_SUB,
    ORG2.COD_NIVEL2 AS COD_EMP,
    ORG2.EDICAO_NIVEL2 AS EDICAO_EMP,
    CASE
        WHEN ORG2.EDICAO_NIVEL2 = '004' THEN ORG2.EDICAO_NIVEL2 || ' - ' || 'MUNDIART SA'
        WHEN ORG2.EDICAO_NIVEL2 = '006' THEN ORG2.EDICAO_NIVEL2 || ' - ' || 'GRATO AGROPECUARIA LTDA'
        WHEN ORG2.EDICAO_NIVEL2 = '008' THEN ORG2.EDICAO_NIVEL2 || ' - ' || 'GRAZZIOTIN SA'
        WHEN ORG2.EDICAO_NIVEL2 = '128' THEN ORG2.EDICAO_NIVEL2 || ' - ' || 'FLORESTA GRAZZIOTIN LTDA'
        WHEN ORG2.EDICAO_NIVEL2 = '276' THEN ORG2.EDICAO_NIVEL2 || ' - ' || 'CENTRO SHOPPING LTDA'
        WHEN ORG2.EDICAO_NIVEL2 = '282' THEN ORG2.EDICAO_NIVEL2 || ' - ' || 'GRAZZIOTIN FINANCEIRA SA'
        ELSE NULL
    END AS DES_EMPRESA,
    FP02.DATA_NASCIMENTO,
    FP02.SEXO,
    PF.EMAIL AS DES_EMAIL,
    PF.DDD_FONE_CEL AS COD_DDD,
    PF.FONE_CEL,
    PF.CPF,
    FP02.NRO_PIS_PASEP,
    FP02.COD_NACIONALIDADE,
    FP02.COD_NACIONALIDADE || ' - ' || NAC.NOME_NACIONALIDADE AS DES_NACIONALIDADE,
    PF.CEP AS COD_CEP,
    PF.TIPO_LOGRA,
    PF.COD_LOGRA,
    PF.NOME_LOGRA AS DES_LOGRA,
    PF.COD_BAIRRO,
    PF.NOME_BAIRRO AS DES_BAIRRO,
    PF.COD_MUNIC AS COD_CIDADE,
    PF.NOME_MUNIC AS DES_CIDADE,
    PF.COD_UF,
    CASE
        WHEN LOT_CONT.COD_LOTACAO IS NOT NULL THEN LOT_CONT.COD_LOTACAO
        ELSE NULL
    END AS COD_LOTACAO,
    AFAST.COD_CAUSA_AFAST AS COD_AFAST,
    AFAST.NOME_CAUSA_AFAST AS DES_AFAST,
    AFAST.DATA_INICIO AS DATA_INI_AFAST,
    AFAST.DATA_FIM AS DATA_FIM_AFAST,
    CASE
        WHEN (CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < TRUNC(SYSDATE)) THEN 'INATIVO'
        WHEN AFAST.COD_CAUSA_AFAST <> 0 AND AFAST.COD_CAUSA_AFAST <> 4 AND AFAST.DATA_FIM = '31/12/2999' THEN 'AFASTADO'
        WHEN AFAST.COD_CAUSA_AFAST = 7 THEN 'EM FÉRIAS'
        WHEN AFAST.COD_CAUSA_AFAST IN (3, 6) THEN 'AFASTADO TEMP'
        WHEN AFAST.COD_CAUSA_AFAST = 4 AND AFAST.DATA_FIM = '31/12/2999' THEN 'PODERÁ RETORNAR'
        ELSE 'EM ATIVIDADE'
    END AS STATUS_AFAST,
    'DADOS ANTERIORES DO CONTRATO =>' AS ESPACO,
    CC.COD_CLH_ANT AS COD_FUNCAO_ANT,
    CC.DES_CLH_ANT AS DES_FUNCAO_ANT,
    CC.DATA_INICIO_ANT,
    CC.DATA_FIM_ANT,
    CO.EDICAO_ORG_ANT AS COD_UNIDADE_ANT,
    CO.DES_ORGANOGRAMA_ANT AS DES_UNIDADE_ANT,
    CO.DATA_INICIO_ORG_ANT,
    CO.DATA_FIM_ORG_ANT
FROM
    RHFP0300 CT
    INNER JOIN RHFP0200 FP02 ON CT.COD_FUNC = FP02.COD_FUNC
    INNER JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
    LEFT JOIN RHFP0310 CT_ORG ON CT.COD_CONTRATO = CT_ORG.COD_CONTRATO AND TRUNC(SYSDATE) BETWEEN CT_ORG.DATA_INICIO AND '31/12/2999'
    INNER JOIN RHFP0400 ORG1 ON CT_ORG.COD_ORGANOGRAMA = ORG1.COD_ORGANOGRAMA
    INNER JOIN RHFP0401 ORG2 ON ORG1.COD_ORGANOGRAMA = ORG2.COD_ORGANOGRAMA AND TRUNC(SYSDATE) BETWEEN ORG2.DATA_INICIO AND '31/12/2999'
    LEFT JOIN RHFP0402 ORG3 ON ORG1.COD_CUSTO_CONTABIL = ORG3.COD_CUSTO_CONTABIL
    INNER JOIN RHFP0340 CT_FUNC ON CT.COD_CONTRATO = CT_FUNC.COD_CONTRATO AND TRUNC(SYSDATE) BETWEEN CT_FUNC.DATA_INICIO AND '31/12/2999'
    INNER JOIN RHFP0500 FUNC ON CT_FUNC.COD_CLH = FUNC.COD_CLH
    LEFT JOIN RHFP0309 LOT_CONT ON CT.COD_CONTRATO = LOT_CONT.COD_CONTRATO
    INNER JOIN RHAF1119 CT_TUR ON CT.COD_CONTRATO = CT_TUR.COD_CONTRATO AND TRUNC(SYSDATE) BETWEEN CT_TUR.DATA_INICIO AND '31/12/2999'
    INNER JOIN RHAF1145 TURNO ON CT_TUR.COD_TURNO = TURNO.COD_TURNO
    INNER JOIN V_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
    LEFT JOIN V_SUPERIOR_IMEDIATO_AVT RESP ON CT.COD_CONTRATO = RESP.COD_CONTRATO
    LEFT JOIN V_AFAST_COLAB_AVT AFAST ON CT.COD_CONTRATO = AFAST.COD_CONTRATO
    LEFT JOIN RHFP0102 DEM ON CT.COD_CAUSA_DEMISSAO = DEM.COD_CAUSA_DEMISSAO
    LEFT JOIN V_CARGO_CONTRATO_AVT CC ON CT.COD_CONTRATO = CC.COD_CONTRATO
    LEFT JOIN V_ORGANOGRAMA_CONTRATO_AVT CO ON CT.COD_CONTRATO = CO.COD_CONTRATO
    LEFT JOIN RHFP0107 NAC ON FP02.COD_NACIONALIDADE = NAC.COD_NACIONALIDADE
WHERE
    (TRUNC(SYSDATE) BETWEEN CT.DATA_INICIO AND '31/12/2999'
    /*OR CT.DATA_FIM >= TRUNC(SYSDATE) - 200*/)
    AND ORG2.EDICAO_NIVEL2 IN ('004', '006', '008', '128', '276', '282')
ORDER BY
    STATUS ASC,
    DATA_ADMISSAO,
    DESC_STATUS DESC

