CREATE OR REPLACE VIEW V_DADOS_DEPENDE_FUNC_AVT AS
SELECT DADOS_DEP.COD_PESSOA COD_PESSOA_DEPENDENTE,
       DADOS_DEP.CPF CPF_DEPENDENTE,
       NOME_DEP.NOME_PESSOA NOME_DEPENDENTE,
       GRAU_PARENTESCO.NOME_GRAU_PARENTESCO PARENTESCO,
       DADOS_FUNC.COD_PESSOA COD_PESSOA_FUNCIONARIO,
       DADOS_FUNC.CPF CPF_FUNCIONARIO,
       NOME_FUNC.NOME_PESSOA NOME_FUNCIONARIO,
       CONTRATO_FUNCIONARIO.COD_CONTRATO
  FROM FISICA   DADOS_FUNC,
       PESSOA   NOME_FUNC,
       RHFP0202 DEPENDENTE_FUNCIONARIO,
       FISICA   DADOS_DEP,
       PESSOA   NOME_DEP,
       RHFP0106 GRAU_PARENTESCO,
       RHFP0300 CONTRATO_FUNCIONARIO
 WHERE DADOS_FUNC.COD_PESSOA = DEPENDENTE_FUNCIONARIO.COD_FUNC
   AND DEPENDENTE_FUNCIONARIO.COD_PESSOA = DADOS_DEP.COD_PESSOA
   AND GRAU_PARENTESCO.COD_GRAU_PARENTESCO =
       DEPENDENTE_FUNCIONARIO.COD_GRAU_PARENTESCO
   AND CONTRATO_FUNCIONARIO.COD_FUNC = DADOS_FUNC.COD_PESSOA
   AND DADOS_FUNC.COD_PESSOA = NOME_FUNC.COD_PESSOA
   AND DADOS_DEP.COD_PESSOA = NOME_DEP.COD_PESSOA
   AND CONTRATO_FUNCIONARIO.DATA_FIM IS NULL
   AND (DEPENDENTE_FUNCIONARIO.DATA_FIM IS NULL OR
       DEPENDENTE_FUNCIONARIO.DATA_FIM > SYSDATE)

