CREATE OR REPLACE VIEW V_DADOS_BANCOS_AVT AS
SELECT BC.COD_BANCO,
       BC.COD_PESSOA,
       PJ.NOME_PESSOA AS DES_BANCO
FROM BANCO BC
LEFT JOIN PESSOA_JURIDICA PJ ON BC.COD_PESSOA = PJ.COD_PESSOA
ORDER BY BC.COD_BANCO ASC

