CREATE OR REPLACE VIEW V_DADOS_ORGANOGRAMAS_AVT AS
SELECT
    L.COD_ORGANOGRAMA,
    L.COD_UNIDADE,
    L.DES_UNIDADE,
    L.DATA_INICIO,
    L.DATA_FIM,
    L.COD_REDE,
    L.DES_REDE,
    L.COD_REGIAO,
    L.COD_EMP,
    L.DES_EMPRESA,
    TO_CHAR(L.COD_TIPO) AS COD_TIPO,
    L.DES_TIPO,
    L.EDICAO_COMPLETA,
    L.DES_CIDADE,
    L.COD_UF
FROM
    V_DADOS_LOJAS_AVT L

UNION ALL

-- Selecionando dados dos Setores
SELECT
    S.COD_ORGANOGRAMA,
    TO_NUMBER(S.COD_UNIDADE) AS COD_UNIDADE,
    S.DES_UNIDADE,
    S.DATA_INICIO,
    S.DATA_FIM,
    S.COD_REDE,
    S.DES_REDE,
    S.COD_REGIAO,
    TO_NUMBER(S.COD_EMP) AS COD_EMP,
    S.DES_EMPRESA,
    TO_CHAR(S.COD_TIPO) AS COD_TIPO,
    S.DES_TIPO,
    S.EDICAO_COMPLETA,
    S.DES_CIDADE,
    S.COD_UF
FROM
    V_SETORES_ADM_AVT S

