CREATE OR REPLACE VIEW V_DADOS_EMPRESAS_AVT AS
SELECT B.COD_ORGANOGRAMA,
       B.COD_PESSOA,
       B.COD_NIVEL_ORG,
       CASE
         WHEN B.COD_NIVEL_ORG = 2 THEN
          A.EDICAO_NIVEL2 || ' - ' || B.NOME_ORGANOGRAMA
         ELSE
          NULL
       END AS DES_EMPRESA,
       B.CLIENTE
  FROM RHFP0401 A
 INNER JOIN RHFP0400 B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
 WHERE B.COD_NIVEL_ORG = 2
 ORDER BY B.COD_ORGANOGRAMA ASC

