CREATE OR REPLACE VIEW V_EST_ORG_ALTER_AVT AS
SELECT CASE
           WHEN A.DATA_FIM = '31/12/2999' THEN
            0
           ELSE
            1
       END AS STATUS_ORG,
       A.COD_ORGANOGRAMA,
       B.NOME_ORGANOGRAMA,
       A.COD_ORGANOGRAMA || ' - ' || B.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA_A,
       A.EDICAO_ORG || ' - ' || B.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA_B,
       A.DATA_INICIO,
       A.DATA_FIM,
       B.COD_NIVEL_ORG,
       D.NOME_NIVEL_ORG,
       A.COD_ORGANOGRAMA_SUB,
       A.EDICAO_ORG,
       SUBSTR(RHYF0002(B.COD_ORGANOGRAMA, B.COD_NIVEL_ORG, TRUNC(SYSDATE)),
              1,
              80) AS EDICAO,
       PJ1.COD_UF,
       A.COD_NIVEL1 AS COD1,
       A.COD_NIVEL2 AS COD2,
       A.COD_NIVEL3 AS COD3,
       A.COD_NIVEL4 AS COD4,
       A.COD_NIVEL5 AS COD5,
       A.COD_NIVEL6 AS COD6,
       A.COD_NIVEL7 AS COD7,
       A.COD_NIVEL8 AS COD8,
       A.EDICAO_NIVEL1 AS EDI1,
       A.EDICAO_NIVEL2 AS EDI2,
       A.EDICAO_NIVEL3 AS EDI3,
       A.EDICAO_NIVEL4 AS EDI4,
       A.EDICAO_NIVEL5 AS EDI5,
       A.EDICAO_NIVEL6 AS EDI6,
       A.EDICAO_NIVEL7 AS EDI7,
       A.EDICAO_NIVEL8 AS EDI8,
       A.COD_NIVEL1 AS COD_ORG_1,
       A.EDICAO_NIVEL1 AS EDICAO_ORG_1,
       B1.NOME_ORGANOGRAMA AS NOME1,
       A.COD_NIVEL2 AS COD_ORG_2,
       A.EDICAO_NIVEL2 AS EDICAO_ORG_2,
       B2.NOME_ORGANOGRAMA AS NOME2,
       A.COD_NIVEL3 AS COD_ORG_3,
       A.EDICAO_NIVEL3 AS EDICAO_ORG_3,
       B3.NOME_ORGANOGRAMA AS NOME3,
       A.COD_NIVEL4 AS COD_ORG_4,
       A.EDICAO_NIVEL4 AS EDICAO_ORG_4,
       B4.NOME_ORGANOGRAMA AS NOME4,
       A.COD_NIVEL5 AS COD_ORG_5,
       A.EDICAO_NIVEL5 AS EDICAO_ORG_5,
       B5.NOME_ORGANOGRAMA AS NOME5,
       A.COD_NIVEL6 AS COD_ORG_6,
       A.EDICAO_NIVEL6 AS EDICAO_ORG_6,
       B6.NOME_ORGANOGRAMA AS NOME6,
       A.COD_NIVEL7 AS COD_ORG_7,
       A.EDICAO_NIVEL7 AS EDICAO_ORG_7,
       B7.NOME_ORGANOGRAMA AS NOME7,
       A.COD_NIVEL8 AS COD_ORG_8,
       A.EDICAO_NIVEL8 AS EDICAO_ORG_8,
       B8.NOME_ORGANOGRAMA AS NOME8,
       CASE
           WHEN C.EDICAO_NIVEL3 = '1' AND A.EDICAO_ORG NOT IN ('811', '815') THEN
            TO_CHAR(10)
           WHEN C.EDICAO_NIVEL3 = '3' AND A.EDICAO_ORG NOT IN ('831', '835') THEN
            TO_CHAR(30)
           WHEN C.EDICAO_NIVEL3 = '4' AND A.EDICAO_ORG NOT IN ('841', '845') THEN
            TO_CHAR(40)
           WHEN C.EDICAO_NIVEL3 = '2' AND A.EDICAO_ORG NOT IN ('851', '855') THEN
            TO_CHAR(50)
           WHEN C.EDICAO_NIVEL3 = '7' AND A.EDICAO_ORG NOT IN ('871') THEN
            TO_CHAR(70)
           WHEN A.COD_NIVEL3 = 9 THEN
            TO_CHAR(A.EDICAO_NIVEL3)
           WHEN A.COD_NIVEL3 = 21 THEN
            TO_CHAR(A.EDICAO_NIVEL3)
           WHEN A.COD_NIVEL3 = 9 AND A.EDICAO_ORG IN ('811', '815', '831', '835', '841', '845', '851', '855', '871') THEN
            TO_CHAR(A.EDICAO_NIVEL3)
           ELSE
            NULL
       END AS COD_REDE,
       CASE
           WHEN C.EDICAO_NIVEL3 = '1' AND A.EDICAO_ORG NOT IN ('811', '815') THEN
            'GRAZZIOTIN'
           WHEN C.EDICAO_NIVEL3 = '3' AND A.EDICAO_ORG NOT IN ('831', '835') THEN
            'PORMENOS'
           WHEN C.EDICAO_NIVEL3 = '4' AND A.EDICAO_ORG NOT IN ('841', '845') THEN
            'FRANCO GIORGI'
           WHEN C.EDICAO_NIVEL3 = '2' AND A.EDICAO_ORG NOT IN ('851', '855') THEN
            'TOTTAL'
           WHEN C.EDICAO_NIVEL3 = '7' AND A.EDICAO_ORG NOT IN ('871') THEN
            'GZT STORE'
           WHEN A.COD_NIVEL3 = 9 OR A.EDICAO_ORG IN ('811', '815', '831', '835', '841', '845', '851', '855', '871') THEN
            'ADMINISTRAÇÃO'
           WHEN A.COD_NIVEL3 = 21 THEN
            'LOGÍSTICA'
           ELSE
            NULL
       END AS DES_REDE,
       CASE
           WHEN A.COD_NIVEL2 = 8 AND A.COD_NIVEL3 = 9 THEN
            2
           WHEN A.COD_NIVEL2 = 8 AND A.COD_NIVEL3 = 21 THEN
            3
           WHEN A.COD_NIVEL2 <> 8 THEN
            4
           ELSE
            1
       END AS COD_TIPO,
       CASE
           WHEN A.COD_NIVEL2 = 8 AND A.COD_NIVEL3 = 9 THEN
            'SETOR'
           WHEN A.COD_NIVEL2 = 8 AND A.COD_NIVEL3 = 21 THEN
            'DEPÓSITO'
           WHEN A.COD_NIVEL2 <> 8 THEN
            'COLIGADA'
           ELSE
            'LOJA'
       END AS DES_TIPO,
       /*\* INDICADOR SE O ORGANOGRAMA TEM CONTRATOS ATIVOS *\
       CASE
           WHEN E.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
            0
           ELSE
            1
       END AS IND_COLABS_ATIVOS,*/
       0 AS IND_SEL
  FROM RHFP0401 A,
       RHFP0400 B1,
       RHFP0400 B2,
       RHFP0400 B3,
       RHFP0400 B4,
       RHFP0400 B5,
       RHFP0400 B6,
       RHFP0400 B7,
       RHFP0400 B8,
       RHFP0400 B,
       RHFP0402 C,
       RHFP0117 D,
       PESSOA_JURIDICA PJ1
 WHERE A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
   AND A.COD_NIVEL1 = B1.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL2 = B2.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL3 = B3.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL4 = B4.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL5 = B5.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL6 = B6.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL7 = B7.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL8 = B8.COD_ORGANOGRAMA(+)
   AND B.COD_CUSTO_CONTABIL = C.COD_CUSTO_CONTABIL(+)
   AND B.COD_NIVEL_ORG = D.COD_NIVEL_ORG(+)
   AND B.COD_PESSOA = PJ1.COD_PESSOA(+)
   --AND TRUNC(SYSDATE) BETWEEN A.DATA_INICIO AND A.DATA_FIM
 ORDER BY A.COD_ORGANOGRAMA ASC

