CREATE OR REPLACE VIEW V_EXPORTA_TURMAS AS
SELECT A.COD_EVENTO,
       A.COD_TURMA,
       B.COD_CONTRATO,
       C.NOME_PESSOA,
       nvl(B.NOTA_PARTICIPACAO,'0') NOTA_PARTICIPACAO,
       A.DATA_INICIO,
    --   A.DATA_FIM,
    --   B.COD_PESSOA,
       A.NOME_TURMA
    --   E.EDICAO_ORG,
    --   F.NOME_ORGANOGRAMA,
    --   G.EDICAO_NIVEL3
FROM RHDP2142 A
    ,RHDP2144 B
    ,PESSOA   C
    ,RHFP0310 D
    ,RHFP0401 E
    ,RHFP0400 F
    ,RHFP0402 G
    ,RHFP0300 H
       WHERE A.COD_EVENTO IN (45,46,57)--(55,100,101,102,103,104,105,43,57,45,46)
AND A.COD_TURMA = B.COD_TURMA
AND B.COD_PESSOA = C.COD_PESSOA
AND B.COD_CONTRATO = D.COD_CONTRATO
AND B.COD_CONTRATO = H.COD_CONTRATO
AND H.COD_CONTRATO = D.COD_CONTRATO
AND G.COD_CUSTO_CONTABIL = F.COD_CUSTO_CONTABIL
--AND (A.DATA_INICIO <= '01/01/2012' )
--AND (A.DATA_INICIO >= '30/12/2016')
AND G.EDICAO_NIVEL3 IN(1,2,3,4)
AND H.DATA_FIM IS NULL
AND A.DATA_INICIO BETWEEN D.DATA_INICIO AND D.DATA_FIM
AND D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA
AND D.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
AND F.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA
--and A.COD_TURMA = 65527
GROUP BY  A.COD_EVENTO,
       A.COD_TURMA,
       A.NOME_TURMA,
       B.COD_PESSOA,
       B.COD_CONTRATO,
       A.DATA_INICIO,
       B.NOTA_PARTICIPACAO,
       A.DATA_FIM,
       C.NOME_PESSOA,
       E.EDICAO_ORG,
       F.NOME_ORGANOGRAMA,
       G.EDICAO_NIVEL3
order by A.COD_EVENTO, A.COD_TURMA,B.COD_CONTRATO

