CREATE OR REPLACE VIEW V_FUNC_DADOS_AVT AS
SELECT
  RHFP0310.COD_CONTRATO,
  RHFP0310.DATA_INICIO AS DATA_INICIO_ORG,
  RHFP0310.DATA_FIM AS DATA_FIM_ORG,
  RHFP0310.COD_ORGANOGRAMA,
  SUBSTR(RHYF0002(RHFP0310.COD_ORGANOGRAMA, RHFP0400.COD_NIVEL_ORG, TRUNC(SYSDATE)), 1, 80) AS EDICAO_COMPLETA,
  RHFP0400.NOME_ORGANOGRAMA AS DES_ORGANOGRAMA,
  RHFP0400.COD_NIVEL_ORG,
  RHFP0117.NOME_NIVEL_ORG,
  RHFP0400.COD_CUSTO_CONTABIL,
  RHFP0402.CUSTO_CONTABIL AS COD_UNIDADE,
  RHFP0402.CUSTO_CONTABIL || ' - ' || RHFP0402.NOME_CUSTO_CONTABIL AS DES_UNIDADE,
  CASE
    WHEN RHFP0310.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN 0
    ELSE 1
  END AS INDIC_ORG,
  CASE
    WHEN RHFP0310.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN 'ATUAL'
    ELSE NULL
  END AS DESC_INDIC_ORG,
  RHFP0310.COD_MOTIVO,
  RHFP0323.NOME_MOTIVO,
  RHFP0323.COD_TIPO_MOTIVO,
  RHFP0115.NOME_TIPO_MOTIVO,
  RHFP0300.COD_CAUSA_DEMISSAO,
  RHFP0102.NOME_CAUSA_DEMISSAO,
  RHFP0401.DATA_INICIO AS DATA_INICIO_EST,
  RHFP0401.DATA_FIM AS DATA_FIM_EST,
  RHFP0401.COD_ORGANOGRAMA_SUB,
  RHFP0401.EDICAO_ORG,
  RHFP0401.IND_LANCAMENTO,
  ANTERIOR.DATA_INICIO_ORG AS DATA_INICIO_ORG_ANT,
  ANTERIOR.DATA_FIM_ORG AS DATA_FIM_ORG_ANT,
  ANTERIOR.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_ANT,
  ANTERIOR.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA_ANT,
  ANTERIOR.EDICAO_COMPLETA AS EDICAO_COMPLETA_ANT,
  ANTERIOR.COD_NIVEL_ORG AS COD_NIVEL_ORG_ANT,
  ANTERIOR.NOME_NIVEL_ORG AS NOME_NIVEL_ORG_ANT,
  ANTERIOR.COD_CUSTO_CONTABIL AS COD_CUSTO_CONTABIL_ANT,
  ANTERIOR.COD_UNIDADE AS COD_UNIDADE_ANT,
  ANTERIOR.DES_UNIDADE AS DES_UNIDADE_ANT,
  CASE
    WHEN ANTERIOR.DATA_FIM_ORG != TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN 1
    ELSE 0
  END AS INDIC_ORG_ANT,
  CASE
    WHEN ANTERIOR.DATA_FIM_ORG != TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN 'ANTERIOR'
    ELSE NULL
  END AS DESC_INDIC_ORG_ANT,
  ANTERIOR.COD_MOTIVO AS COD_MOTIVO_ANT,
  ANTERIOR.NOME_MOTIVO AS NOME_MOTIVO_ANT,
  ANTERIOR.COD_TIPO_MOTIVO AS COD_TIPO_MOTIVO_ANT,
  ANTERIOR.NOME_TIPO_MOTIVO AS NOME_TIPO_MOTIVO_ANT,
  ANTERIOR.COD_CAUSA_DEMISSAO AS COD_CAUSA_DEMISSAO_ANT,
  ANTERIOR.NOME_CAUSA_DEMISSAO AS DES_CAUSA_DEMISSAO_ANT,
  CASE
    WHEN ORESP.COD_CONTRATO_RESP = RHFP0310.COD_CONTRATO THEN 'S'
    ELSE 'N'
  END AS IND_RESPONSAVEL
FROM
  RHFP0310
  INNER JOIN RHFP0400 ON RHFP0310.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
  LEFT JOIN RHFP0323 ON RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO
  LEFT JOIN RHFP0115 ON RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO
  LEFT JOIN RHFP0300 ON RHFP0300.COD_CONTRATO = RHFP0310.COD_CONTRATO
  LEFT JOIN RHFP0102 ON RHFP0300.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO
  LEFT JOIN RHFP0402 ON RHFP0400.COD_CUSTO_CONTABIL = RHFP0402.COD_CUSTO_CONTABIL
  LEFT JOIN RHFP0401 ON RHFP0400.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA
  LEFT JOIN PESSOA PESSOA_EMPFIL ON RHFP0400.COD_PESSOA = PESSOA_EMPFIL.COD_PESSOA
  LEFT JOIN PESSOA PESSOA_DRT ON RHFP0400.COD_DRT = PESSOA_DRT.COD_PESSOA
  LEFT JOIN RHFP0117 ON RHFP0400.COD_NIVEL_ORG = RHFP0117.COD_NIVEL_ORG
  LEFT JOIN RHFP0397 ORESP ON RHFP0310.COD_ORGANOGRAMA = ORESP.COD_ORGANOGRAMA AND TRUNC(SYSDATE) BETWEEN ORESP.DATA_INICIO AND ORESP.DATA_FIM
  LEFT JOIN (
    SELECT
      INT_RHFP0310.COD_CONTRATO,
      INT_RHFP0310.DATA_INICIO AS DATA_INICIO_ORG,
      INT_RHFP0310.DATA_FIM AS DATA_FIM_ORG,
      INT_RHFP0310.COD_ORGANOGRAMA,
      INT_RHFP0400.NOME_ORGANOGRAMA,
      SUBSTR(RHYF0002(INT_RHFP0310.COD_ORGANOGRAMA, INT_RHFP0400.COD_NIVEL_ORG, INT_RHFP0310.DATA_INICIO), 1, 80) AS EDICAO_COMPLETA,
      INT_RHFP0400.COD_NIVEL_ORG,
      INT_RHFP0117.NOME_NIVEL_ORG,
      INT_RHFP0400.COD_CUSTO_CONTABIL,
      INT_RHFP0402.CUSTO_CONTABIL AS COD_UNIDADE,
      INT_RHFP0402.CUSTO_CONTABIL || ' - ' || INT_RHFP0402.NOME_CUSTO_CONTABIL AS DES_UNIDADE,
      INT_RHFP0310.COD_MOTIVO,
      INT_RHFP0323.NOME_MOTIVO,
      INT_RHFP0323.COD_TIPO_MOTIVO,
      INT_RHFP0115.NOME_TIPO_MOTIVO,
      INT_RHFP0300.COD_CAUSA_DEMISSAO,
      INT_RHFP0102.NOME_CAUSA_DEMISSAO
    FROM
      RHFP0310 INT_RHFP0310
      INNER JOIN RHFP0400 INT_RHFP0400 ON INT_RHFP0310.COD_ORGANOGRAMA = INT_RHFP0400.COD_ORGANOGRAMA
      LEFT JOIN RHFP0323 INT_RHFP0323 ON INT_RHFP0310.COD_MOTIVO = INT_RHFP0323.COD_MOTIVO
      LEFT JOIN RHFP0115 INT_RHFP0115 ON INT_RHFP0323.COD_TIPO_MOTIVO = INT_RHFP0115.COD_TIPO_MOTIVO
      LEFT JOIN RHFP0300 INT_RHFP0300 ON INT_RHFP0300.COD_CONTRATO = INT_RHFP0310.COD_CONTRATO
      LEFT JOIN RHFP0102 INT_RHFP0102 ON INT_RHFP0300.COD_CAUSA_DEMISSAO = INT_RHFP0102.COD_CAUSA_DEMISSAO
      LEFT JOIN RHFP0402 INT_RHFP0402 ON INT_RHFP0400.COD_CUSTO_CONTABIL = INT_RHFP0402.COD_CUSTO_CONTABIL
      LEFT JOIN PESSOA INT_PESSOA_EMPFIL ON INT_RHFP0400.COD_PESSOA = INT_PESSOA_EMPFIL.COD_PESSOA
      LEFT JOIN PESSOA INT_PESSOA_DRT ON INT_RHFP0400.COD_DRT = INT_PESSOA_DRT.COD_PESSOA
      LEFT JOIN RHFP0117 INT_RHFP0117 ON INT_RHFP0400.COD_NIVEL_ORG = INT_RHFP0117.COD_NIVEL_ORG
  ) ANTERIOR ON RHFP0310.COD_CONTRATO = ANTERIOR.COD_CONTRATO AND RHFP0310.DATA_INICIO - 1 = ANTERIOR.DATA_FIM_ORG
WHERE
  TRUNC(SYSDATE) BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM
  AND TRUNC(SYSDATE) BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
ORDER BY
  RHFP0310.COD_CONTRATO ASC
