CREATE OR REPLACE VIEW V_GERENTES_LOJAS_AVT AS
SELECT DISTINCT CLH.COD_CONTRATO,
                PE.NOME_PESSOA,
                CLH.COD_CLH,
                CLH2.NOME_CLH,
                ORG3.COD_ORGANOGRAMA,
                ORG3.EDICAO_ORG AS COD_UNIDADE,
                ORG3.EDICAO_ORG || ' - ' || ORG2.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA,
                CASE
                  WHEN RESP.COD_CONTRATO_RESP IS NULL THEN
                   'N'
                  ELSE
                   'S'
                END AS IND_RESP_UNI
  FROM RHFP0340 CLH
 INNER JOIN RHFP0300 CT ON CLH.COD_CONTRATO = CT.COD_CONTRATO
 INNER JOIN RHFP0306 AF ON AF.COD_CONTRATO = CT.COD_CONTRATO
 INNER JOIN RHFP0500 CLH2 ON CLH2.COD_CLH = CLH.COD_CLH
 INNER JOIN PESSOA PE ON PE.COD_PESSOA = CT.COD_FUNC
 INNER JOIN RHFP0310 ORG ON ORG.COD_CONTRATO = CLH.COD_CONTRATO
 INNER JOIN RHFP0400 ORG2 ON ORG2.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
 INNER JOIN RHFP0401 ORG3 ON ORG3.COD_ORGANOGRAMA = ORG2.COD_ORGANOGRAMA
  LEFT JOIN (SELECT DISTINCT A.COD_CONTRATO_RESP
               FROM RHFP0397 A
              INNER JOIN V_DADOS_LOJAS_AVT B ON A.COD_ORGANOGRAMA =
                                                B.COD_ORGANOGRAMA
              WHERE A.DATA_FIM = '31/12/2999'
                AND SYSDATE BETWEEN A.DATA_INICIO AND A.DATA_FIM) RESP ON CT.COD_CONTRATO =
                                                                          RESP.COD_CONTRATO_RESP
 WHERE CLH.COD_CLH IN
       ('77', '78', '79', '80', '81', '86', '87', '88', '90', '184', '185',
        '186', '188', '189', '190', '192', '294', '318', '304', '191', '197', '89', '92', '93')
   AND SYSDATE BETWEEN CLH.DATA_INICIO AND CLH.DATA_FIM
   AND SYSDATE BETWEEN ORG.DATA_INICIO AND ORG.DATA_FIM
   AND SYSDATE BETWEEN ORG3.DATA_INICIO AND ORG3.DATA_FIM
   AND CT.DATA_FIM IS NULL
   AND NOT EXISTS (SELECT 1
          FROM RHFP0306 AF
         WHERE AF.COD_CONTRATO = CT.COD_CONTRATO
           AND AF.DATA_FIM = '31/12/2999')
 ORDER BY ORG3.EDICAO_ORG ASC;