CREATE OR REPLACE VIEW V_HISTORICO_CONTRATO_AVT AS
WITH CTE_ORGANOGRAMA AS (
     SELECT CTO.COD_CONTRATO,
            CTO.NOME_PESSOA,
            /* ORGANOGRAMA PRINCIPAL DO CONTRATO */
            CTO.COD_EMP,
            CTO.EDICAO_EMP,
            CTO.DES_EMP,
            CTO.COD_UNIDADE,
            CTO.DES_UNIDADE,
            CTO.COD_ORGANOGRAMA,
            CTO.NOME_ORGANOGRAMA,
            CTO.NOME_ORGANOGRAMA_A,
            CTO.COD_NIVEL_ORG,
            CTO.COD_ORGANOGRAMA_SUB,
            CTO.EDICAO,
            CTO.DATA_INI_ORG,
            CTO.DATA_FIM_ORG,
            /* SEQUENCIA DOS NÍVEIS DO ORGANOGRAMA DO CONTRATO */
            CTO.COD_ORG_1,
            CTO.EDICAO_ORG_1,
            CTO.NOME1,
            CTO.COD_ORG_2,
            CTO.EDICAO_ORG_2,
            CTO.NOME2,
            CTO.COD_ORG_3,
            CTO.EDICAO_ORG_3,
            CTO.NOME3,
            CTO.COD_ORG_4,
            CTO.EDICAO_ORG_4,
            CTO.NOME4,
            CTO.COD_ORG_5,
            CTO.EDICAO_ORG_5,
            CTO.NOME5,
            CTO.COD_ORG_6,
            CTO.EDICAO_ORG_6,
            CTO.NOME6,
            CTO.COD_ORG_7,
            CTO.EDICAO_ORG_7,
            CTO.NOME7,
            CTO.COD_ORG_8,
            CTO.EDICAO_ORG_8,
            CTO.NOME8,
            CTO.COD_REDE,
            CTO.DES_REDE,            
            CTO.COD_TIPO,            
            CTO.DES_TIPO,
            --VO.COD_REDE,
            --VO.DES_REDE,
            VO.COD_REGIAO,
            VO.DES_REGIAO,
            ROW_NUMBER() OVER(PARTITION BY CTO.COD_CONTRATO ORDER BY CTO.DATA_INI_ORG DESC) AS RN
       FROM VH_EST_ORG_CONTRATO_AVT CTO
       LEFT JOIN V_ORGANOGRAMAS_AVT VO ON CTO.COD_ORGANOGRAMA =
                                          VO.COD_ORGANOGRAMA
     --WHERE ORG.COD_CONTRATO = 389622
),

CTE_CARGO AS (
     SELECT CC.COD_CONTRATO,
            CC.COD_FUNCAO,
            CC.DES_FUNCAO,
            CC.DATA_INI_FUNCAO,
            CC.DATA_FIM_FUNCAO
     FROM VH_HIST_CARGO_CONTRATO_AVT CC
),

CTE_AFAST AS (
     SELECT AFAST.COD_CONTRATO,
            AFAST.COD_AFAST,
            AFAST.DES_AFAST,
            AFAST.DATA_INI_AFAST,
            AFAST.DATA_FIM_AFAST,
            AFAST.QTD_DIAS_AFAST,
            ROW_NUMBER() OVER(PARTITION BY AFAST.COD_CONTRATO ORDER BY AFAST.DATA_INI_AFAST DESC) AS RN
     FROM VH_AFAST_CONTRATO_AVT AFAST
     --WHERE AFAST.COD_CONTRATO = 389622
)
SELECT
    /* DADOS DO CONTRATO */
    PF.COD_PESSOA,
    CT.COD_CONTRATO,
    INITCAP(PF.NOME_PESSOA) AS DES_PESSOA,
    CT.DATA_INICIO AS DATA_ADMISSAO,
    CT.DATA_FIM AS DATA_DEMISSAO,
    CT.COD_CAUSA_DEMISSAO AS COD_DEMISSAO,
    DEM.NOME_CAUSA_DEMISSAO AS DES_DEMISSAO,

    /* DADOS DA FUNÇÃO */
    FUN.COD_FUNCAO,
    FUN.DES_FUNCAO,
    FUN.DATA_INI_FUNCAO,
    FUN.DATA_FIM_FUNCAO,

    /* DADOS DO ORGANOGRAMA DO CONTRATO */
    ORG.COD_ORGANOGRAMA,
    ORG.COD_UNIDADE,
    ORG.DES_UNIDADE,
    ORG.DATA_INI_ORG,
    ORG.DATA_FIM_ORG,
    ORG.COD_REDE AS COD_REDE_LOCAL,
    ORG.DES_REDE AS DES_REDE_LOCAL,
    ORG.COD_REGIAO,
    ORG.DES_REGIAO,
    ORG.COD_ORG_1 AS COD_GRUPO_EMP,
    ORG.EDICAO_ORG_1 AS EDICAO_GRUPO_EMP,
    ORG.NOME1 AS DES_GRUPO_EMP,
    ORG.COD_EMP,
    ORG.EDICAO_EMP,
    ORG.DES_EMP,
    ORG.COD_ORG_3 AS COD_ORG_FILIAL,
    ORG.EDICAO_ORG_3 AS EDICAO_FILIAL,
    ORG.NOME3 AS DES_FILIAL,
    ORG.COD_ORG_4 AS COD_ORG_DIVISAO,
    ORG.EDICAO_ORG_4 AS EDICAO_DIVISAO,
    ORG.NOME4 AS DES_DIVISAO,
    ORG.COD_ORG_5 AS COD_ORG_DEPART,
    ORG.EDICAO_ORG_5 AS EDICAO_DEPART,
    ORG.NOME5 AS DES_DEPART,
    ORG.COD_ORG_6 AS COD_ORG_SETOR,
    ORG.EDICAO_ORG_6 AS EDICAO_SETOR,
    ORG.NOME6 AS DES_SETOR,
    ORG.COD_ORG_7 AS COD_ORG_SECAO,
    ORG.EDICAO_ORG_7 AS EDICAO_SECAO,
    ORG.NOME7 AS DES_SECAO,
    ORG.COD_ORG_8 AS COD_ORG_UNI,
    ORG.EDICAO_ORG_8 AS EDICAO_UNI,
    ORG.NOME8 AS DES_UNI,
    ORG.COD_TIPO,
    ORG.DES_TIPO,

    /* DADOS DE AFASTAMENTOS */
    AFAST.COD_AFAST,
    AFAST.DES_AFAST,
    AFAST.DATA_INI_AFAST,
    AFAST.DATA_FIM_AFAST,
    AFAST.QTD_DIAS_AFAST

FROM RHFP0300 CT
INNER JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
LEFT JOIN RHFP0102 DEM ON CT.COD_CAUSA_DEMISSAO = DEM.COD_CAUSA_DEMISSAO

-- DADOS DO CARGO DO CONTRATO
LEFT JOIN CTE_CARGO FUN
    ON CT.COD_CONTRATO = FUN.COD_CONTRATO

-- DADOS DO ORGANOGRAMA DO CONTRATO
LEFT JOIN CTE_ORGANOGRAMA ORG
    ON CT.COD_CONTRATO = ORG.COD_CONTRATO

-- DADOS DE AFASTAMENTO
LEFT JOIN CTE_AFAST AFAST
    ON CT.COD_CONTRATO = AFAST.COD_CONTRATO
    AND AFAST.RN = 1

WHERE (
    CT.DATA_FIM IS NULL
    OR SYSDATE BETWEEN CT.DATA_INICIO AND NVL(CT.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
    OR CT.DATA_FIM >= SYSDATE - 500
)
--AND CT.COD_CONTRATO = 389622
ORDER BY CT.COD_CONTRATO, ORG.DATA_INI_ORG, FUN.DATA_INI_FUNCAO


