CREATE OR REPLACE VIEW V_INFO_FILIAL_CONT_AVT AS
SELECT RHFP0310.COD_CONTRATO,
       RHFP0310.DATA_INICIO,
       RHFP0310.DATA_FIM,
       RHFP0310.COD_MOTIVO,
       RHFP0323.NOME_MOTIVO,
       RHFP0401.COD_NIVEL2 AS COD_EMPRESA,
       RHFP0401.COD_NIVEL3 AS COD_FILIAL,
       RHFP0401.COD_NIVEL4,
       RHFP0401.COD_NIVEL5,
       RHFP0401.COD_NIVEL6,
       RHFP0401.COD_NIVEL7,
       RHFP0401.COD_NIVEL8,
       (RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMSEMP_NIVEL4,
       RHFP0401.EDICAO_NIVEL2 AS EDICAO_EMPRESA,
       RHFP0401.EDICAO_NIVEL3 AS EDICAO_FILIAL,
       RHFP0401.EDICAO_NIVEL4,
       RHFP0401.EDICAO_NIVEL5,
       RHFP0401.EDICAO_NIVEL6,
       RHFP0401.EDICAO_NIVEL7,
       RHFP0401.EDICAO_NIVEL8,
       
       PESEMP.COD_PESSOA  AS COD_PESSOA_EMPRESA,
       PESFIL.COD_PESSOA  AS COD_PESSOA_FILIAL,
       PESEMP.NOME_PESSOA AS RAZAO_SOCIAL_EMPRESA,
       PESFIL.NOME_PESSOA AS RAZAO_SOCIAL_FILIAL,
       
       EMP400.NOME_ORGANOGRAMA AS NOME_EMPRESA,
       FIL400.NOME_ORGANOGRAMA AS NOME_FILIAL,
       JURFIL.FANTASIA         AS NOME_FANTASIA_FILIAL,
       N4.NOME_ORGANOGRAMA     AS NOME_NIVEL4,
       N5.NOME_ORGANOGRAMA     AS NOME_NIVEL5,
       N6.NOME_ORGANOGRAMA     AS NOME_NIVEL6,
       N7.NOME_ORGANOGRAMA     AS NOME_NIVEL7,
       N8.NOME_ORGANOGRAMA     AS NOME_NIVEL8,
       LOGEMP.NOME_LOGRA       AS LOGRADOURO_EMPRESA,
       JUREMP.NUMERO           AS NUMERO_EMPRESA,
       JUREMP.COMPLEMENTO      AS COMPLEMENTO_EMPRESA,
       BAIEMP.NOME_BAIRRO      AS BAIRRO_EMPRESA,
       MUNEMP.NOME_MUNIC       AS MUNICIPIO_EMPRESA,
       JUREMP.CEP              AS CEP_EMPRESA,
       JUREMP.COD_UF           AS UF_EMPRESA,
       JUREMP.CGC              AS CGC_EMPRESA,
       JUREMP.TIP_LOGRA        AS TIPO_LOG_EMPRESA,
       
       LOGFIL.NOME_LOGRA  AS LOGRADOURO_FILIAL,
       JURFIL.NUMERO      AS NUMERO_FILIAL,
       JURFIL.COMPLEMENTO AS COMPLEMENTO_FILIAL,
       BAIFIL.NOME_BAIRRO AS BAIRRO_FILIAL,
       MUNFIL.NOME_MUNIC  AS MUNICIPIO_FILIAL,
       JURFIL.CEP         AS CEP_FILIAL,
       JURFIL.COD_UF      AS UF_FILIAL,
       JURFIL.CGC         AS CGC_FILIAL,
       JURFIL.TIP_LOGRA   AS TIPO_LOG_FILIAL,
       JURFIL.DDD         AS DDD_FILIAL,
       JURFIL.FONE        AS FONE_FILIAL

  FROM RHFP0310 RHFP0310,
       RHFP0401 RHFP0401,
       RHFP0400 EMP400,
       RHFP0400 FIL400,
       RHFP0400 N4,
       RHFP0400 N5,
       RHFP0400 N6,
       RHFP0400 N7,
       RHFP0400 N8,
       
       FISICA FISEMP,
       FISICA FISFIL,
       PESSOA PESEMP,
       PESSOA PESFIL,
       PESSOA PESN04,
       PESSOA PESN05,
       PESSOA RESPEMP,
       PESSOA RESPFIL,
       
       LOGRA    LOGEMP,
       JURIDICA JUREMP,
       MUNICI   MUNEMP,
       BAIRRO   BAIEMP,
       
       LOGRA    LOGFIL,
       JURIDICA JURFIL,
       MUNICI   MUNFIL,
       BAIRRO   BAIFIL,
       
       LOGRA    LOGN4,
       JURIDICA JURN4,
       MUNICI   MUNN4,
       BAIRRO   BAIN4,
       
       LOGRA    LOGN5,
       JURIDICA JURN5,
       MUNICI   MUNN5,
       BAIRRO   BAIN5,
       
       RHFP0430 R430EMP,
       RHFP0430 R430FIL,
       
       BANCO   BANEMP,
       AGENCIA AGEEMP,
       BANCO   BANFIL,
       AGENCIA AGEFIL,
       
       PESSOA   PESBANEMP,
       PESSOA   PESBANFIL,
       PESSOA   PESAGEEMP,
       PESSOA   PESAGEFIL,
       RHFP0323 RHFP0323

 WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA
      --AND :DATA_REFERENCIA BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
      --AND :DATA_REFERENCIA BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM
      --AND RHFP0310.COD_CONTRATO = 376606
      
   AND RHFP0401.COD_NIVEL2 = R430EMP.COD_ESTABELECIMENTO(+)
   AND RHFP0401.COD_NIVEL3 = R430FIL.COD_ESTABELECIMENTO(+)
   AND R430EMP.BANCO_DEBITO = BANEMP.COD_BANCO(+)
   AND R430FIL.BANCO_DEBITO = BANFIL.COD_BANCO(+)
   AND R430EMP.BANCO_DEBITO = AGEEMP.COD_BANCO(+)
   AND R430EMP.CODAGE_DEBITO = AGEEMP.COD_AGENCIA(+)
   AND R430FIL.BANCO_DEBITO = AGEFIL.COD_BANCO(+)
   AND R430FIL.CODAGE_DEBITO = AGEFIL.COD_AGENCIA(+)
      
   AND EMP400.COD_PESSOA = PESEMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = PESFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA = PESN04.COD_PESSOA(+)
   AND N5.COD_PESSOA = PESN05.COD_PESSOA(+)
      
   AND R430EMP.COD_RESPONSAVEL = RESPEMP.COD_PESSOA(+)
   AND RESPEMP.COD_PESSOA = FISEMP.COD_PESSOA(+)
   AND R430FIL.COD_RESPONSAVEL = RESPFIL.COD_PESSOA(+)
   AND RESPFIL.COD_PESSOA = FISFIL.COD_PESSOA(+)
      
   AND BANEMP.COD_PESSOA = PESBANEMP.COD_PESSOA(+)
   AND BANFIL.COD_PESSOA = PESBANFIL.COD_PESSOA(+)
   AND AGEEMP.COD_PESSOA = PESAGEEMP.COD_PESSOA(+)
   AND AGEFIL.COD_PESSOA = PESAGEFIL.COD_PESSOA(+)
      
   AND RHFP0401.COD_NIVEL2 = EMP400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL3 = FIL400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL4 = N4.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL5 = N5.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL6 = N6.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL7 = N7.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL8 = N8.COD_ORGANOGRAMA(+)
      
   AND EMP400.COD_PESSOA = JUREMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = JURFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA = JURN4.COD_PESSOA(+)
   AND N5.COD_PESSOA = JURN5.COD_PESSOA(+)
      
   AND JUREMP.COD_LOGRA = LOGEMP.COD_LOGRA(+)
   AND JUREMP.COD_MUNIC = LOGEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF = LOGEMP.COD_UF(+)
   AND JUREMP.COD_MUNIC = MUNEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF = MUNEMP.COD_UF(+)
   AND JUREMP.COD_BAIRRO = BAIEMP.COD_BAIRRO(+)
   AND JUREMP.COD_MUNIC = BAIEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF = BAIEMP.COD_UF(+)
      
   AND JURFIL.COD_LOGRA = LOGFIL.COD_LOGRA(+)
   AND JURFIL.COD_MUNIC = LOGFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF = LOGFIL.COD_UF(+)
   AND JURFIL.COD_MUNIC = MUNFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF = MUNFIL.COD_UF(+)
   AND JURFIL.COD_BAIRRO = BAIFIL.COD_BAIRRO(+)
   AND JURFIL.COD_MUNIC = BAIFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF = BAIFIL.COD_UF(+)
      
   AND JURN4.COD_LOGRA = LOGN4.COD_LOGRA(+)
   AND JURN4.COD_MUNIC = LOGN4.COD_MUNIC(+)
   AND JURN4.COD_UF = LOGN4.COD_UF(+)
   AND JURN4.COD_MUNIC = MUNN4.COD_MUNIC(+)
   AND JURN4.COD_UF = MUNN4.COD_UF(+)
   AND JURN4.COD_BAIRRO = BAIN4.COD_BAIRRO(+)
   AND JURN4.COD_MUNIC = BAIN4.COD_MUNIC(+)
   AND JURN4.COD_UF = BAIN4.COD_UF(+)
      
   AND JURN5.COD_LOGRA = LOGN5.COD_LOGRA(+)
   AND JURN5.COD_MUNIC = LOGN5.COD_MUNIC(+)
   AND JURN5.COD_UF = LOGN5.COD_UF(+)
   AND JURN5.COD_MUNIC = MUNN5.COD_MUNIC(+)
   AND JURN5.COD_UF = MUNN5.COD_UF(+)
   AND JURN5.COD_BAIRRO = BAIN5.COD_BAIRRO(+)
   AND JURN5.COD_MUNIC = BAIN5.COD_MUNIC(+)
   AND JURN5.COD_UF = BAIN5.COD_UF(+)
      
   AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)