CREATE OR REPLACE VIEW V_LOJAS_WEB AS
SELECT FP03.COD_CONTRATO COD_CONTRATO,
       SENHA.DES_SENHA DATA_NASCIMENTO,
       INITCAP(P.NOME_PESSOA) DES_PESSOA,
       SENHA.COD_GRUPO COD_GRUPO_UNIDADE,
       ORG_CUSTO_CTB.CUSTO_CONTABIL COD_UNIDADE,
       ORG_EMP.COD_NIVEL2 COD_EMP,
       FP03.DATA_FIM DTA_DEMISSAO,
       NVL(SENHA.IND_ATUALIZA_GRUPO, 0) IND_ATUALIZA_GRUPO
  FROM RHFP0200    FP02,
       RHFP0300    FP03,
       PESSOA      P,
       MUNICI      MUN,
       FISICA      FIS,
       RHFP0310    CONTR_ORGANOGRAMA,
       RHFP0400    ORGANOGRAMA,
       RHFP0401    ORG_EMP,
       RHFP0402    ORG_CUSTO_CTB,
       RHFP0500    FUNCOES,
       RHFP0340    CONTRFUNC,
       MDL_USUARIO SENHA
 WHERE P.COD_PESSOA = FP02.COD_FUNC
   AND FIS.COD_PESSOA = FP02.COD_FUNC
   AND FP02.COD_FUNC = FP03.COD_FUNC
   AND FP03.COD_CONTRATO = CONTRFUNC.COD_CONTRATO
   AND FUNCOES.COD_CLH = CONTRFUNC.COD_CLH
   AND FP03.COD_CONTRATO = CONTR_ORGANOGRAMA.COD_CONTRATO
   AND FP03.COD_CONTRATO = SENHA.COD_CONTRATO(+)
   AND FIS.COD_MUNIC = MUN.COD_MUNIC
   AND CONTR_ORGANOGRAMA.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
   AND ORGANOGRAMA.COD_ORGANOGRAMA = ORG_EMP.COD_ORGANOGRAMA
   AND ORGANOGRAMA.COD_CUSTO_CONTABIL = ORG_CUSTO_CTB.COD_CUSTO_CONTABIL(+)
   AND CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
   AND ORG_EMP.COD_NIVEL2 IN (4, 8, 282, 276)
   AND ((FP03.DATA_FIM IS NULL) OR (FP03.DATA_FIM >= SYSDATE - 30))
      --AND FP03.COD_CONTRATO = '353671'
   AND CONTRFUNC.DATA_FIM > SYSDATE
--D TO_CHAR(DATA_NASCIMENTO,'DDMMYYYY') = '04121976'