CREATE OR REPLACE VIEW V_OCORRENCIAS_PONTO_AVT AS
WITH OCORRENCIAS AS (
    SELECT B.COD_CONTRATO,
        B.DES_PESSOA,
        B.COD_UNIDADE,
        SUM(DECODE(A.COD_OCORRENCIA, 203, A.NUM_HORAS, 0)) AS "EXTRAS DIURNAS 60% ( GERAL )",
        SUM(DECODE(A.COD_OCORRENCIA, 205, A.NUM_HORAS, 0)) AS "ATRASOS DIURNO ( GERAL )",
        SUM(DECODE(A.COD_OCORRENCIA, 203, A.NUM_HORAS, 0)) - SUM(DECODE(A.COD_OCORRENCIA, 205, A.NUM_HORAS, 0)) AS TOTAL,
        SUM(DECODE(A.COD_OCORRENCIA, 1034, A.NUM_HORAS, 0)) AS BANCO_HORAS,
        LISTAGG(CASE WHEN A.COD_OCORRENCIA = 1034 THEN TO_CHAR(A.DATA_OCORRENCIA, 'DD/MM/YYYY') END, ', ') 
        WITHIN GROUP (ORDER BY A.DATA_OCORRENCIA) AS DATAS_FALTAS
    FROM RHAF1123 A
    INNER JOIN V_DADOS_PESSOA B ON B.COD_CONTRATO = A.COD_CONTRATO
    WHERE A.COD_OCORRENCIA IN (203, 205, 1034)
    GROUP BY B.COD_CONTRATO, B.DES_PESSOA, B.COD_UNIDADE
)
SELECT
    O.COD_CONTRATO,
    O.DES_PESSOA,
    O.COD_UNIDADE,
    CASE
        WHEN O.BANCO_HORAS < 0 THEN '-' || TRUNC(ABS(O.BANCO_HORAS)) || ':' || LPAD(ROUND(MOD(ABS(O.BANCO_HORAS), 1) * 60), 2, '0')
        ELSE TRUNC(O.BANCO_HORAS) || ':' || LPAD(ROUND(MOD(O.BANCO_HORAS, 1) * 60), 2, '0')
    END AS "BCO FALTAS ( GERAL )",
    O.DATAS_FALTAS,
    CASE
        WHEN O.TOTAL < 0 THEN '-' || TRUNC(ABS(O.TOTAL)) || ':' || LPAD(ROUND(MOD(ABS(O.TOTAL), 1) * 60), 2, '0')
        ELSE NULL
    END AS ATRASOS,
    CASE
        WHEN O.TOTAL > 0 THEN TRUNC(O.TOTAL) || ':' || LPAD(ROUND(MOD(O.TOTAL, 1) * 60), 2, '0')
        ELSE NULL
    END AS EXTRAS
FROM
    OCORRENCIAS O
ORDER BY O.DES_PESSOA;
