CREATE OR REPLACE VIEW V_ORGANOGRAMA_CONTRATO_AVT AS
SELECT RHFP0310.COD_CONTRATO,
       RHFP0310.DATA_INICIO AS DATA_INICIO_ORG,
       RHFP0310.DATA_FIM AS DATA_FIM_ORG,
       CASE 
           WHEN RHFP0401.COD_NIVEL2 = 4 THEN 4
           WHEN RHFP0401.COD_NIVEL2 = 6 THEN 6
           WHEN RHFP0401.COD_NIVEL2 = 8 THEN 8
           WHEN RHFP0401.COD_NIVEL2 = 276 THEN 276
           WHEN RHFP0401.COD_NIVEL2 = 282 THEN 282
           WHEN RHFP0401.COD_NIVEL2 = 1629 THEN 1629
           ELSE 
            NULL
       END AS COD_EMP,
       RHFP0310.COD_ORGANOGRAMA,
       RHFP0401.EDICAO_ORG,
       RHFP0401.EDICAO_ORG || ' - ' || RHFP0400.NOME_ORGANOGRAMA AS DES_ORGANOGRAMA,
       SUBSTR(RHYF0002(RHFP0310.COD_ORGANOGRAMA,
                       RHFP0400.COD_NIVEL_ORG,
                       trunc(sysdate)),
              1,
              80) AS EDICAO_ORGANOGRAMA,
       RHFP0400.COD_NIVEL_ORG,
       RHFP0117.NOME_NIVEL_ORG,
       RHFP0400.COD_CUSTO_CONTABIL,
       RHFP0402.NOME_CUSTO_CONTABIL,
       RHFP0402.CUSTO_CONTABIL,
       RHFP0310.COD_MOTIVO,
       RHFP0323.NOME_MOTIVO,
       RHFP0323.COD_TIPO_MOTIVO,
       RHFP0115.NOME_TIPO_MOTIVO,
       RHFP0310.COD_CAUSA_DEMISSAO,
       RHFP0102.NOME_CAUSA_DEMISSAO,
       RHFP0401.DATA_INICIO AS DATA_INICIO_EST,
       RHFP0401.DATA_FIM AS DATA_FIM_EST,
       RHFP0401.COD_ORGANOGRAMA_SUB,
       RHFP0401.IND_LANCAMENTO,
       ANTERIOR.DATA_INICIO_ORG AS DATA_INICIO_ORG_ANT,
       ANTERIOR.DATA_FIM_ORG AS DATA_FIM_ORG_ANT,
       ANTERIOR.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_ANT,
       ANTERIOR.EDI_ORG AS EDICAO_ORG_ANT,
       CASE
           WHEN ANTERIOR.EDI_ORG IS NOT NULL THEN
            ANTERIOR.EDI_ORG || ' - ' || ANTERIOR.NOME_ORGANOGRAMA
           ELSE
            NULL
       END AS DES_ORGANOGRAMA_ANT,
       ANTERIOR.EDICAO_ORGANOGRAMA AS EDICAO_ORGANOGRAMA_ANT,
       ANTERIOR.COD_NIVEL_ORG AS COD_NIVEL_ORG_ANT,
       ANTERIOR.NOME_NIVEL_ORG AS NOME_NIVEL_ORG_ANT,
       ANTERIOR.COD_CUSTO_CONTABIL AS COD_CUSTO_CONTABIL_ANT,
       ANTERIOR.NOME_CUSTO_CONTABIL AS NOME_CUSTO_CONTABIL_ANT,
       ANTERIOR.CUSTO_CONTABIL AS CUSTO_CONTABIL_ANT,
       ANTERIOR.COD_MOTIVO AS COD_MOTIVO_ANT,
       ANTERIOR.NOME_MOTIVO AS NOME_MOTIVO_ANT,
       ANTERIOR.COD_TIPO_MOTIVO AS COD_TIPO_MOTIVO_ANT,
       ANTERIOR.NOME_TIPO_MOTIVO AS NOME_TIPO_MOTIVO_ANT,
       ANTERIOR.COD_CAUSA_DEMISSAO AS COD_CAUSA_DEMISSAO_ANT,
       ANTERIOR.NOME_CAUSA_DEMISSAO AS NOME_CAUSA_DEMISSAO_ANT,
       DECODE(ORESP.COD_CONTRATO_RESP, RHFP0310.COD_CONTRATO, 'S', 'N') AS IND_RESPONSAVEL
  FROM RHFP0310 RHFP0310,
       RHFP0400 RHFP0400,
       RHFP0323 RHFP0323,
       RHFP0115 RHFP0115,
       RHFP0102 RHFP0102,
       RHFP0402 RHFP0402,
       RHFP0401 RHFP0401,
       RHFP0436 RHFP0436,
       RHFP3170 RHFP3170,
       PESSOA PESSOA_DRT,
       PESSOA PESSOA_EMPFIL,
       RHFP0117 RHFP0117,
       RHFP0397 ORESP,
       (SELECT RHFP0310.COD_CONTRATO,
               RHFP0310.DATA_INICIO AS DATA_INICIO_ORG,
               RHFP0310.DATA_FIM AS DATA_FIM_ORG,
               RHFP0401.EDICAO_ORG AS EDI_ORG,
               RHFP0310.COD_ORGANOGRAMA,
               RHFP0400.NOME_ORGANOGRAMA,
               SUBSTR(RHYF0002(RHFP0310.COD_ORGANOGRAMA,
                               RHFP0400.COD_NIVEL_ORG,
                               RHFP0310.DATA_INICIO),
                      1,
                      80) AS EDICAO_ORGANOGRAMA,
               RHFP0400.COD_NIVEL_ORG,
               RHFP0117.NOME_NIVEL_ORG,
               RHFP0400.COD_CUSTO_CONTABIL,
               RHFP0402.NOME_CUSTO_CONTABIL,
               RHFP0402.CUSTO_CONTABIL,
               RHFP0310.COD_MOTIVO,
               RHFP0323.NOME_MOTIVO,
               RHFP0323.COD_TIPO_MOTIVO,
               RHFP0115.NOME_TIPO_MOTIVO,
               RHFP0310.COD_CAUSA_DEMISSAO,
               RHFP0102.NOME_CAUSA_DEMISSAO
          FROM RHFP0310 RHFP0310,
               RHFP0401 RHFP0401,
               RHFP0400 RHFP0400,
               RHFP0323 RHFP0323,
               RHFP0115 RHFP0115,
               RHFP0102 RHFP0102,
               RHFP0402 RHFP0402,
               RHFP0436 RHFP0436,
               RHFP3170 RHFP3170,
               PESSOA   PESSOA_DRT,
               PESSOA   PESSOA_EMPFIL,
               RHFP0117 RHFP0117
         WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
           AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
           AND RHFP0310.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO(+)
           AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
           AND RHFP0400.COD_CUSTO_CONTABIL = RHFP0402.COD_CUSTO_CONTABIL(+)
           AND RHFP0400.COD_PESSOA = PESSOA_EMPFIL.COD_PESSOA(+)
           AND RHFP0400.COD_DRT = PESSOA_DRT.COD_PESSOA(+)
           AND RHFP0400.COD_NIVEL_ORG = RHFP0117.COD_NIVEL_ORG(+)
           AND RHFP0400.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA(+)
           AND RHFP0310.COD_ORGANOGRAMA = RHFP0436.COD_ORGANOGRAMA(+)
           AND RHFP0310.COD_ORGANOGRAMA = RHFP3170.COD_ORGANOGRAMA(+)) ANTERIOR
 WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
   AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
   AND RHFP0310.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO(+)
   AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
   AND RHFP0400.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA(+)
   AND RHFP0400.COD_CUSTO_CONTABIL = RHFP0402.COD_CUSTO_CONTABIL(+)
   AND RHFP0400.COD_PESSOA = PESSOA_EMPFIL.COD_PESSOA(+)
   AND RHFP0400.COD_DRT = PESSOA_DRT.COD_PESSOA(+)
   AND RHFP0400.COD_NIVEL_ORG = RHFP0117.COD_NIVEL_ORG(+)
   AND trunc(sysdate) BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM
   AND RHFP0310.COD_CONTRATO = ANTERIOR.COD_CONTRATO(+)
   AND RHFP0310.DATA_INICIO - 1 = ANTERIOR.DATA_FIM_ORG(+)
   AND trunc(sysdate) BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
   AND RHFP0310.COD_ORGANOGRAMA = RHFP0436.COD_ORGANOGRAMA(+)
   AND RHFP0310.COD_ORGANOGRAMA = RHFP3170.COD_ORGANOGRAMA(+)
   AND RHFP0310.COD_ORGANOGRAMA = ORESP.COD_ORGANOGRAMA(+)
   AND trunc(sysdate) BETWEEN ORESP.DATA_INICIO(+) AND ORESP.DATA_FIM(+)

