CREATE OR REPLACE VIEW V_PROGRAMACAO_FERIAS_AVT AS
SELECT A.COD_CONTRATO,
       C.NOME_PESSOA AS DES_PESSOA,
       A.DATA_PREVISTA_FERIAS,
       A.DIAS_FERIAS_CONCED,
       A.DATA_FERIAS,
       A.DATA_RETORNO,
       A.DIAS_FERIAS_GOZADOS,
       A.DIAS_ABONO_CONCED,
       A.DIAS_ABONO_GOZADOS,
       A.DATA_ABONO,
       A.DATA_FIM_ABONO,
       A.DATA_PAGAMENTO,
       A.COD_MESTRE_EVENTO,
       A.COD_OPERADOR,
       A.DATA_INCLUSAO,
       CASE
           WHEN A.DATA_PREVISTA_FERIAS >= TRUNC(SYSDATE) THEN
            0
           ELSE
            1
       END AS IND_FERIAS
FROM RHFP0327 A
INNER JOIN RHFP0300 B ON A.COD_CONTRATO = B.COD_CONTRATO
INNER JOIN PESSOA_FISICA C ON B.COD_FUNC = C.COD_PESSOA
--WHERE A.DATA_PREVISTA_FERIAS BETWEEN '01/01/2025' AND '28/02/2025'
ORDER BY A.DATA_PREVISTA_FERIAS

