CREATE OR REPLACE VIEW V_UNIDADES_ATIVAS_AVT AS
WITH FILTRO_TELEFONES AS (
    SELECT COD_PESSOA, NUM_FONE AS CELULAR
    FROM NL.PS_TELEFONES@NLGRZ
    WHERE NUM_SEQ = 4
)
SELECT
    GU.COD_EMP,
    PSPES.COD_ATIVIDADE,
    TO_CHAR(PJ.NUM_CGC) NUM_CGC,
    TEL.CELULAR,
    SUBSTR(GU.COD_NIVEL2, 2, 3) AS COD_REDE,
    DECODE(SUBSTR(GU.COD_NIVEL2, 2, 3),
        '10', 'GRAZZIOTIN',
        '30', 'PORMENOS',
        '40', 'FRANCO GIORGI',
        '50', 'TOTTAL',
        '70', 'GZT STORE',
        'UNKNOWN') AS DES_REDE,
    DECODE(SUBSTR(GU.COD_NIVEL2, 2, 3),
        '10', 'GRZ',
        '30', 'PRM',
        '40', 'FRG',
        '50', 'TOT',
        '70', 'GZT',
        'UNK') AS DES_REDE_ABREV,
    MAX(DECODE(GU.COD_UNIDADE,
        1566, 566,
        3566, 566,
        4566, 566,
        5566, 566,
        1580, 580,
        3580, 580,
        4580, 580,
        5580, 580,
        818, 900,
        838, 900,
        848, 900,
        858, 900,
        878, 900,
        GU.COD_UNIDADE)) COD_UNIDADE,
    PSPES.DES_FANTASIA,
    REG.COD_GRUPO AS COD_REGIAO,
    DREG.NOME_REGIAO AS DES_REGIAO,
    G1.COD_UF,
    PSPES.COD_CIDADE
FROM NL.GE_UNIDADES@NLGRZ GU
INNER JOIN NL.PS_PESSOAS@NLGRZ PSPES ON PSPES.COD_PESSOA = GU.COD_UNIDADE
INNER JOIN NL.G1_CIDADES@NLGRZ G1 ON G1.COD_CIDADE = PSPES.COD_CIDADE
INNER JOIN NL.PS_JURIDICAS@NLGRZ PJ ON PJ.COD_PESSOA = GU.COD_UNIDADE
LEFT JOIN FILTRO_TELEFONES TEL ON PSPES.COD_PESSOA = TEL.COD_PESSOA
INNER JOIN NL.GE_GRUPOS_UNIDADES@NLGRZ REG ON PSPES.COD_PESSOA = REG.COD_UNIDADE
INNER JOIN NL.DATALAKE_DIM_REGIAO@NLGRZ DREG ON REG.COD_GRUPO = DREG.COD_REGIAO
WHERE GU.COD_EMP = 1
    AND GU.COD_UNIDADE < 8000
    AND GU.COD_NIVEL2 IN (810, 830, 840, 850, 870, 900)
    AND GU.COD_UNIDADE NOT IN (900)
    AND PSPES.IND_INATIVO = 0
    AND PSPES.DTA_AFASTAMENTO IS NULL
    AND PJ.NUM_CGC NOT IN (0, 92012467000170)
GROUP BY
    GU.COD_EMP,
    PSPES.COD_ATIVIDADE,
    PJ.NUM_CGC,
    SUBSTR(GU.COD_NIVEL2, 2, 3),
    PSPES.DES_FANTASIA,
    G1.COD_UF,
    PSPES.COD_CIDADE,
    TEL.CELULAR,
    REG.COD_GRUPO,
    DREG.NOME_REGIAO
ORDER BY
    COD_UNIDADE ASC

