CREATE OR REPLACE VIEW V_VALOR_HORAS_EXTRAS_AVT AS
WITH HORAS_EXTRAS AS (
  SELECT D.COD_EMP,
         D.COD_UNIDADE,
         D.DES_UNIDADE,
         SUM(CASE
               WHEN A.COD_VD IN
                    (325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 336) THEN
                COALESCE(A.QTDE_VD, 0)
               ELSE
                0
             END) AS QTDE_HORAS_EXTRAS,
         SUM(CASE
               WHEN A.COD_VD IN
                    (325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 336) THEN
                COALESCE(A.VALOR_VD, 0)
               ELSE
                0
             END) AS VLR_HORAS_EXTRAS,
         B.DATA_REFERENCIA,
         B.COD_EVENTO
    FROM RHFP1006 A
   INNER JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
   INNER JOIN RHFP1000 C ON A.COD_VD = C.COD_VD
   INNER JOIN VH_EST_ORG_CONTRATO_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO
   WHERE A.COD_VD IN
         (325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 336)
     AND B.COD_EVENTO IN (1, 8, 17, 19)
   GROUP BY D.COD_EMP,
            D.COD_UNIDADE,
            D.DES_UNIDADE,
            B.DATA_REFERENCIA,
            B.COD_EVENTO
),
REPOUSO_HORAS_EXTRAS AS (
  SELECT D.COD_EMP,
         D.COD_UNIDADE,
         D.DES_UNIDADE,
         SUM(CASE
               WHEN A.COD_VD = 158 THEN
                COALESCE(A.QTDE_VD, 0)
               ELSE
                0
             END) AS QTDE_REP_HORAS_EXTRAS,
         SUM(CASE
               WHEN A.COD_VD = 158 THEN
                COALESCE(A.VALOR_VD, 0)
               ELSE
                0
             END) AS VLR_REP_HORAS_EXTRAS,
         B.DATA_REFERENCIA,
         B.COD_EVENTO
    FROM RHFP1006 A
   INNER JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
   INNER JOIN RHFP1000 C ON A.COD_VD = C.COD_VD
   INNER JOIN VH_EST_ORG_CONTRATO_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO
   WHERE A.COD_VD = 158
     AND B.COD_EVENTO IN (1, 8, 17, 19)
   GROUP BY D.COD_EMP,
            D.COD_UNIDADE,
            D.DES_UNIDADE,
            B.DATA_REFERENCIA,
            B.COD_EVENTO
),
DIFERENCA_HORAS_EXTRAS AS (
  SELECT D.COD_EMP,
         D.COD_UNIDADE,
         D.DES_UNIDADE,
         SUM(CASE
               WHEN A.COD_VD = 189 THEN
                COALESCE(A.QTDE_VD, 0)
               ELSE
                0
             END) AS QTDE_DIF_HORAS_EXTRAS,
         SUM(CASE
               WHEN A.COD_VD = 189 THEN
                COALESCE(A.VALOR_VD, 0)
               ELSE
                0
             END) AS VLR_DIF_HORAS_EXTRAS,
         B.DATA_REFERENCIA,
         B.COD_EVENTO
    FROM RHFP1006 A
   INNER JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
   INNER JOIN RHFP1000 C ON A.COD_VD = C.COD_VD
   INNER JOIN VH_EST_ORG_CONTRATO_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO
   WHERE A.COD_VD = 189
     AND B.COD_EVENTO IN (1, 8, 17, 19)
   GROUP BY D.COD_EMP,
            D.COD_UNIDADE,
            D.DES_UNIDADE,
            B.DATA_REFERENCIA,
            B.COD_EVENTO
),
BONUS_DOMINGO AS (
  SELECT D.COD_EMP,
         D.COD_UNIDADE,
         D.DES_UNIDADE,
         SUM(CASE
               WHEN A.COD_VD = 323 THEN
                COALESCE(A.QTDE_VD, 0)
               ELSE
                0
             END) AS QTDE_BONUS_DOM,
         SUM(CASE
               WHEN A.COD_VD = 323 THEN
                COALESCE(A.VALOR_VD, 0)
               ELSE
                0
             END) AS VLR_BONUS_DOM,
         B.DATA_REFERENCIA,
         B.COD_EVENTO
    FROM RHFP1006 A
   INNER JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
   INNER JOIN RHFP1000 C ON A.COD_VD = C.COD_VD
   INNER JOIN VH_EST_ORG_CONTRATO_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO
   WHERE A.COD_VD = 323
     AND B.COD_EVENTO IN (1, 8, 17, 19)
   GROUP BY D.COD_EMP,
            D.COD_UNIDADE,
            D.DES_UNIDADE,
            B.DATA_REFERENCIA,
            B.COD_EVENTO
)
SELECT A.COD_EMP,
       A.COD_UNIDADE,
       A.DES_UNIDADE,
       COALESCE(A.QTDE_HORAS_EXTRAS, 0) AS QTDE_HORAS_EXTRAS,
       COALESCE(A.VLR_HORAS_EXTRAS, 0) AS VLR_HORAS_EXTRAS,
       COALESCE(B.QTDE_REP_HORAS_EXTRAS, 0) AS QTDE_REP_HORAS_EXTRAS,
       COALESCE(B.VLR_REP_HORAS_EXTRAS, 0) AS VLR_REP_HORAS_EXTRAS,
       COALESCE(C.QTDE_DIF_HORAS_EXTRAS, 0) AS QTDE_DIF_HORAS_EXTRAS,
       COALESCE(C.VLR_DIF_HORAS_EXTRAS, 0) AS VLR_DIF_HORAS_EXTRAS,
       COALESCE(D.QTDE_BONUS_DOM, 0) AS QTDE_BONUS_DOM,
       COALESCE(D.VLR_BONUS_DOM, 0) AS VLR_BONUS_DOM,
       A.DATA_REFERENCIA,
       A.COD_EVENTO
  FROM HORAS_EXTRAS A
  LEFT JOIN REPOUSO_HORAS_EXTRAS B ON A.COD_EMP = B.COD_EMP
                                  AND A.COD_UNIDADE = B.COD_UNIDADE
                                  AND A.DATA_REFERENCIA = B.DATA_REFERENCIA
                                  AND A.COD_EVENTO = B.COD_EVENTO
  LEFT JOIN DIFERENCA_HORAS_EXTRAS C ON A.COD_EMP = C.COD_EMP
                                    AND A.COD_UNIDADE = C.COD_UNIDADE
                                    AND A.DATA_REFERENCIA =
                                        C.DATA_REFERENCIA
                                    AND A.COD_EVENTO = C.COD_EVENTO
  LEFT JOIN BONUS_DOMINGO D ON A.COD_EMP = D.COD_EMP
                           AND A.COD_UNIDADE = D.COD_UNIDADE
                           AND A.DATA_REFERENCIA = D.DATA_REFERENCIA
                           AND A.COD_EVENTO = D.COD_EVENTO;