CREATE OR REPLACE VIEW VH_CONTRATO_COLAB_AVT AS
SELECT B.COD_PESSOA,
       A.COD_CONTRATO,
       B.NOME_PESSOA AS DES_PESSOA,
       A.DATA_INICIO AS DATA_ADMISSAO,
       A.DATA_FIM AS DATA_DEMISSAO,
       A.DATA_AVANCO,
       A.COD_CAUSA_DEMISSAO AS COD_DEMISSAO,
       C.NOME_CAUSA_DEMISSAO AS DES_DEMISSAO,
       CASE
         WHEN A.DATA_FIM IS NOT NULL AND A.DATA_FIM < SYSDATE THEN
          1
         ELSE
          0
       END AS STATUS,
       CASE
         WHEN A.DATA_FIM IS NOT NULL AND A.DATA_FIM < SYSDATE THEN
          'INATIVO'
         WHEN A.DATA_INICIO <= SYSDATE /*OR CT.DATA_FIM = SYSDATE AND TO_CHAR(SYSDATE, 'HH24:MI:SS') = '23:59:59'*/
          THEN
          'ATIVO'
         WHEN A.DATA_INICIO > SYSDATE
         /*AND CT.DATA_AVANCO > SYSDATE*/
          THEN
          'ADMISSAO FUTURA'
       END AS DESC_STATUS
  FROM RHFP0300 A
 INNER JOIN PESSOA_FISICA B ON A.COD_FUNC = B.COD_PESSOA
  LEFT JOIN RHFP0102 C ON A.COD_CAUSA_DEMISSAO = C.COD_CAUSA_DEMISSAO
ORDER BY A.COD_CONTRATO, A.DATA_INICIO

