CREATE OR REPLACE VIEW VH_EST_ORG_CONTRATO_ALTER_AVT AS
SELECT DISTINCT
       B.COD_CONTRATO,
       PF.NOME_PESSOA,
       /*ORGANOGRAMA PRINCIPAL DO CONTRATO*/
       A.COD_ORG_2 AS COD_EMP,
       A.COD_ORGANOGRAMA,
       A.NOME_ORGANOGRAMA,
       A.NOME_ORGANOGRAMA_A,
       A.EDICAO_ORG,
       A.NOME_ORGANOGRAMA_B,
       A.COD_NIVEL_ORG,
       A.COD_ORGANOGRAMA_SUB,
       A.EDICAO,
       B.DATA_INICIO,
       B.DATA_FIM,
       /*SEQUENCIA DOS NÍVEIS DO ORGANOGRAMA DO CONTRATO*/
       A.COD_ORG_1,
       A.EDICAO_ORG_1,
       A.NOME1,
       A.COD_ORG_2,
       A.EDICAO_ORG_2,
       A.NOME2,
       A.COD_ORG_3,
       A.EDICAO_ORG_3,
       A.NOME3,
       A.COD_ORG_4,
       A.EDICAO_ORG_4,
       A.NOME4,
       A.COD_ORG_5,
       A.EDICAO_ORG_5,
       A.NOME5,
       A.COD_ORG_6,
       A.EDICAO_ORG_6,
       A.NOME6,
       A.COD_ORG_7,
       A.EDICAO_ORG_7,
       A.NOME7,
       A.COD_ORG_8,
       A.EDICAO_ORG_8,
       A.NOME8,
       A.DATA_INICIO AS DATA_INI_SUB,
       A.DATA_FIM AS DATA_FIM_SUB,
       CASE
           WHEN A.COD_ORG_2 = 8 AND A.COD_ORG_3 = 9 THEN
            2
           WHEN A.COD_ORG_2 = 8 AND A.COD_ORG_3 = 21 THEN
            3
           WHEN A.COD_ORG_2 <> 8 THEN
            4
           ELSE
            1
       END AS COD_TIPO,
       CASE
           WHEN A.COD_ORG_2 = 8 AND A.COD_ORG_3 = 9 THEN
            'SETOR'
           WHEN A.COD_ORG_2 = 8 AND A.COD_ORG_3 = 21 THEN
            'DEPÓSITO'
           WHEN A.COD_ORG_2 <> 8 THEN
            'COLIGADA'
           ELSE
            'LOJA'
       END AS DES_TIPO
       --ROW_NUMBER() OVER(PARTITION BY B.COD_CONTRATO ORDER BY A.DATA_INICIO DESC) AS RN
FROM V_EST_ORG_ALTER_AVT A
INNER JOIN RHFP0310 B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
INNER JOIN RHFP0300 C ON B.COD_CONTRATO = C.COD_CONTRATO
INNER JOIN PESSOA_FISICA PF ON C.COD_FUNC = PF.COD_PESSOA
ORDER BY B.DATA_INICIO

