/* ==========================================================================================
   ==== SQL PARA RELATÓRIO DE PRODUTIVIDADE ENCIMA DO INVENTÁRIO DE ITENS PARA AUDITORIA ====
   =========================================================================================== */

WITH HRS AS (
  SELECT
    TAF.COD_UNIDADE,
    A.SEQ_TAREFA,
    A.COD_USUARIO,
    TRUNC(A.DTA_ATUALIZADO)           AS DIA,
    TO_CHAR(A.DTA_ATUALIZADO,'HH24')  AS HORA,
    SUM(A.QTD_CONTADA)                AS QTD_HORA
  FROM GRZ_CONT_TAREFAS_ITENS A
  LEFT JOIN GRZ_CONT_TAREFAS TAF
         ON TAF.SEQ = A.SEQ_TAREFA
  WHERE A.DTA_ATUALIZADO >= TO_DATE('&DATA_INICIO','DD/MM/YYYY')
    AND A.DTA_ATUALIZADO <  TO_DATE('&DATA_FIM','DD/MM/YYYY')
    -- AND A.SEQ_TAREFA = 482003
    -- AND TO_CHAR(A.DTA_ATUALIZADO,'HH24') BETWEEN '08' AND '20'
  GROUP BY
    TAF.COD_UNIDADE, A.SEQ_TAREFA, A.COD_USUARIO,
    TRUNC(A.DTA_ATUALIZADO), TO_CHAR(A.DTA_ATUALIZADO,'HH24')
),

APUR AS (
  SELECT H.COD_UNIDADE, H.SEQ_TAREFA,
         MIN(H.DIA) AS D_INI, MAX(H.DIA) AS D_FIM
  FROM HRS H
  GROUP BY H.COD_UNIDADE, H.SEQ_TAREFA
),

/* MÉDIA DO DIA = ITENS DO DIA / HORAS COM PRODUÇÃO NO DIA */
DIA_USR AS (
  SELECT
    H.COD_UNIDADE,
    H.SEQ_TAREFA,
    H.COD_USUARIO,
    H.DIA,
    SUM(H.QTD_HORA)                                                AS IT_DIA_USR,
    SUM(CASE WHEN H.QTD_HORA > 0 THEN 1 ELSE 0 END)                AS HR_ATIVAS_DIA,
    SUM(H.QTD_HORA) / NULLIF(SUM(CASE WHEN H.QTD_HORA > 0 THEN 1 ELSE 0 END),0)
                                                                  AS MED_IT_HR_DIA
  FROM HRS H
  GROUP BY H.COD_UNIDADE, H.SEQ_TAREFA, H.COD_USUARIO, H.DIA
),

RES AS (
  SELECT
    D.COD_UNIDADE, D.SEQ_TAREFA, D.COD_USUARIO,
    AVG(D.MED_IT_HR_DIA)    AS MED_IT_HR_PER,
    MEDIAN(D.MED_IT_HR_DIA) AS MEDN_IT_HR_PER,
    STDDEV(D.MED_IT_HR_DIA) AS VAR_IT_HR_PER,
    COUNT(*)                AS DIAS_PROD
  FROM DIA_USR D
  GROUP BY D.COD_UNIDADE, D.SEQ_TAREFA, D.COD_USUARIO
),

TOT_USR AS (
  SELECT
    H.COD_UNIDADE, H.SEQ_TAREFA, H.COD_USUARIO,
    SUM(H.QTD_HORA) AS TOT_IT_USR
  FROM HRS H
  GROUP BY H.COD_UNIDADE, H.SEQ_TAREFA, H.COD_USUARIO
),

/* POR DIA COM PARTICIPAÇÃO DO USUÁRIO NA UNIDADE */
DIA_DET AS (
  SELECT
    D.COD_UNIDADE, D.SEQ_TAREFA, D.COD_USUARIO, D.DIA,
    D.IT_DIA_USR, D.HR_ATIVAS_DIA, D.MED_IT_HR_DIA,
    SUM(D.IT_DIA_USR) OVER (PARTITION BY D.COD_UNIDADE, D.SEQ_TAREFA, D.DIA) AS IT_DIA_UNI,
    RANK() OVER (PARTITION BY D.COD_UNIDADE, D.SEQ_TAREFA, D.DIA
                 ORDER BY D.MED_IT_HR_DIA DESC) AS POS_DIA_UNI
  FROM DIA_USR D
),

/* POR HORA COM % DA HORA NO DIA E PI DA HORA */
HR_DET AS (
  SELECT
    H.COD_UNIDADE, H.SEQ_TAREFA, H.COD_USUARIO, H.DIA, H.HORA,
    H.QTD_HORA                                         AS IT_HORA,
    D.IT_DIA_USR,
    CASE WHEN D.IT_DIA_USR > 0
         THEN 100 * H.QTD_HORA / D.IT_DIA_USR
         ELSE 0 END                                    AS PCT_HR_DIA,
    CASE
      WHEN NULLIF(MAX(H.QTD_HORA) OVER (PARTITION BY H.COD_UNIDADE,H.SEQ_TAREFA,H.COD_USUARIO,H.DIA),0) IS NOT NULL
      THEN 100 * H.QTD_HORA /
           NULLIF(MAX(H.QTD_HORA) OVER (PARTITION BY H.COD_UNIDADE,H.SEQ_TAREFA,H.COD_USUARIO,H.DIA),0)
      ELSE 0
    END                                               AS PI_HR,
    RANK() OVER (PARTITION BY H.COD_UNIDADE,H.SEQ_TAREFA,H.COD_USUARIO,H.DIA
                 ORDER BY H.QTD_HORA DESC)            AS POS_HR_DIA
  FROM HRS H
  JOIN DIA_USR D
    ON D.COD_UNIDADE = H.COD_UNIDADE
   AND D.SEQ_TAREFA  = H.SEQ_TAREFA
   AND D.COD_USUARIO = H.COD_USUARIO
   AND D.DIA         = H.DIA
),

TOT_GER AS (
  SELECT
    H.COD_UNIDADE, H.SEQ_TAREFA,
    SUM(H.QTD_HORA)               AS TOT_IT_UNI,
    COUNT(DISTINCT H.COD_USUARIO) AS COLAB_ATIVOS,
    COUNT(DISTINCT H.DIA)         AS DIAS_APUR,
    AVG(D.MED_IT_HR_DIA)          AS MED_IT_HR_EQP,
    AVG(R.MED_IT_HR_PER)          AS MED_IT_HR_PER_EQP
  FROM HRS H
  JOIN DIA_USR D
    ON D.COD_UNIDADE = H.COD_UNIDADE
   AND D.SEQ_TAREFA  = H.SEQ_TAREFA
   AND D.COD_USUARIO = H.COD_USUARIO
   AND D.DIA         = H.DIA
  JOIN RES R
    ON R.COD_UNIDADE = H.COD_UNIDADE
   AND R.SEQ_TAREFA  = H.SEQ_TAREFA
   AND R.COD_USUARIO = H.COD_USUARIO
  GROUP BY H.COD_UNIDADE, H.SEQ_TAREFA
)

SELECT
  /* CHAVES + APURAÇÃO */
  H.COD_UNIDADE AS UNIDADE,
  H.SEQ_TAREFA  AS SEQ,
  '&DATA_INICIO' || ' A ' || '&DATA_FIM' AS APURACAO,

  /* GRANULARIDADE (LINHA = HORA) */
  H.DIA, H.HORA, H.COD_USUARIO, F.DES_NOME AS NOME,

  /* A — POR HORA */
  H.IT_HORA                                 AS HORA_ITENS,
  ROUND(H.PCT_HR_DIA,2)                     AS HORA_PCT_DIA_USUARIO,
  ROUND(H.PI_HR,2)                          AS HORA_PI,
  H.POS_HR_DIA                              AS HORA_RANK_DIA_USR,

  /* B — POR DIA */
  D.IT_DIA_USR                              AS DIA_ITENS_USUARIO,
  D.HR_ATIVAS_DIA                           AS DIA_HORAS_ATIVAS,
  ROUND(D.MED_IT_HR_DIA,2)                  AS DIA_MEDIA_ITENS_HORA,
  ROUND(CASE WHEN D.IT_DIA_UNI > 0
             THEN 100*D.IT_DIA_USR/D.IT_DIA_UNI
             ELSE 0 END,2)                  AS DIA_PCT_USR_UNIDADE,
  D.POS_DIA_UNI                             AS DIA_RANK_UNIDADE,

  /* C — PERÍODO (ÍNDICE GERAL DO USUÁRIO) */
  T.TOT_IT_USR                              AS PER_TOT_ITENS_USUARIO,
  ROUND(R.MED_IT_HR_PER,2)                  AS PER_MEDIA_ITENS_HORA,
  ROUND(R.MEDN_IT_HR_PER,2)                 AS PER_MEDIANA_ITENS_HORA,
  ROUND(R.VAR_IT_HR_PER,2)                  AS PER_DESVIO_ITENS_HORA,
  R.DIAS_PROD                               AS PER_DIAS_PROD,
  RANK() OVER (PARTITION BY R.COD_UNIDADE, R.SEQ_TAREFA
               ORDER BY R.MED_IT_HR_PER DESC) AS PER_RANK_UNIDADE,
  RANK() OVER (ORDER BY R.MED_IT_HR_PER DESC)  AS PER_RANK_GERAL,

  /* D — TOTAIS GERAIS */
  TG.TOT_IT_UNI                             AS TOT_ITENS_UNIDADE,
  TG.COLAB_ATIVOS                           AS TOT_COLAB_ATIVOS,
  TG.DIAS_APUR                              AS TOT_DIAS_APUR,
  ROUND(TG.MED_IT_HR_EQP,2)                 AS TOT_MEDIA_ITENS_HORA_EQP,
  ROUND(TG.MED_IT_HR_PER_EQP,2)             AS TOT_MEDIA_IT_HR_PER_EQP

FROM HR_DET H
JOIN DIA_DET D
  ON D.COD_UNIDADE = H.COD_UNIDADE
 AND D.SEQ_TAREFA  = H.SEQ_TAREFA
 AND D.COD_USUARIO = H.COD_USUARIO
 AND D.DIA         = H.DIA
JOIN RES R
  ON R.COD_UNIDADE = H.COD_UNIDADE
 AND R.SEQ_TAREFA  = H.SEQ_TAREFA
 AND R.COD_USUARIO = H.COD_USUARIO
JOIN TOT_USR T
  ON T.COD_UNIDADE = H.COD_UNIDADE
 AND T.SEQ_TAREFA  = H.SEQ_TAREFA
 AND T.COD_USUARIO = H.COD_USUARIO
JOIN TOT_GER TG
  ON TG.COD_UNIDADE = H.COD_UNIDADE
 AND TG.SEQ_TAREFA  = H.SEQ_TAREFA
JOIN APUR AP
  ON AP.COD_UNIDADE = H.COD_UNIDADE
 AND AP.SEQ_TAREFA  = H.SEQ_TAREFA
JOIN GRZ_ARH_FUNCIONARIOS F
  ON F.COD_FUNCIONARIO = H.COD_USUARIO
WHERE F.COD_UNIDADE = 761
ORDER BY H.SEQ_TAREFA, H.DIA, H.HORA, H.COD_UNIDADE, H.COD_USUARIO;