/*
PROCESSO PARA AJUSTAR TAREFAS QUE PUXAM COM UNIDADE 999 
- CASO QUE ACONTECE QUANDO O USUÁRIO REALIZANDO O PROCESSO NÃO PERTENCE A LOJA DA CONFERÊNCIA, NO CASO AUDITORIA
*/

--SELECT DE CONSULTA
SELECT A.SEQ,
       --C.SEQ_TAREFA,
       A.COD_UNIDADE,
       A.COD_UNIDADE_DESTINO,
       A.DTA_SISTEMA,
       A.TOT_CONTADOS,
       DECODE(A.IND_STATUS,
              0,
              'EM ANDAMENTO',
              1,
              'FINALIZADO',
              2,
              'CANCELADO') SITUACAO,
       A.COD_USUARIO,
       B.DES_NOME,
       B.COD_CENTRO_CUSTO AS UNIDADE_LOCAL,
       A.ROWID
  FROM GRZ_CONT_TAREFAS A
 INNER JOIN GRZ_ARH_FUNCIONARIOS B ON B.COD_FUNCIONARIO = A.COD_USUARIO
 --INNER JOIN GRZ_CONT_TAREFAS_ITENS C ON A.SEQ = C.SEQ_TAREFA
 WHERE A.DTA_SISTEMA >= '01/10/2025'
 AND A.COD_UNIDADE IN (159, 307, 529)
 --AND A.SEQ LIKE '999%'
 AND B.COD_CENTRO_CUSTO = 761
ORDER BY A.SEQ, A.COD_UNIDADE


/*
1º TABELA A ATUALIZAR - REFERENCIA SEMPRE PELO SEQ_TAREFA E USUÁRIO
     -- MAS É BOM CONTER UM SUM(QTD_CONTADA) FACILITA O CONFRONTO COM A GRZ_CONT_TAREFAS
*/
     
SELECT * FROM GRZ_CONT_TAREFAS_ITENS_HIST
WHERE DTA_SISTEMA >= '01/10/2025'


/*
2º TABELA A ATUALIZAR - MESMA COISA, REFERENCIA SEMPRE PELO SEQ_TAREFA E USUÁRIO E SUM(QTD_CONTADA)
*/

SELECT * FROM GRZ_CONT_TAREFAS_ITENS
WHERE DTA_SISTEMA >= '01/10/2025'


/*
3º POR ÚLTIMO ATUALIZAR A GRZ_CONT_TAREFAS - LEMBRANDO SEMPRE DE SALVAR A SEQ/SEQ_TAREFA ANTES E O DEPOIS PARA CONFRONTO, 
ASSIM NÃO SE PERDE AS TAREFAS QUE DEVEM SER DE FATO ATUALIZADAS
*/

SELECT * FROM GRZ_CONT_TAREFAS
WHERE DTA_SISTEMA >= '01/10/2025'