WITH
LOJAS AS (
SELECT
  A.COD_ORGANOGRAMA_SUB,
  A.EDICAO_ORG,
  A.COD_ORGANOGRAMA,
  A.NOME_ORGANOGRAMA,
  A.DATA_INICIO,
  A.DATA_FIM,
  A.TIP_LOGRA,
  A.LOGRADOURO,
  A.NUMERO,
  A.COMPLEMENTO,
  A.BAIRRO,
  A.CIDADE,
  A.COD_UF,
  A.CEP,
  A.CNPJ
FROM V_EST_ORG_AVT A
WHERE A.COD_NIVEL_ORG = 3
  AND A.COD_TIPO      = 1
  AND EXISTS (
        SELECT 1
        FROM V_EST_ORG_AVT B
        WHERE B.COD_NIVEL_ORG = 5
          AND B.COD3 = A.COD3
      )
ORDER BY A.COD_TIPO, A.EDICAO_ORG


),

SETOR3 AS (
SELECT
  A.COD_ORGANOGRAMA_SUB,
  A.EDICAO_ORG,
  A.COD_ORGANOGRAMA,
  A.NOME_ORGANOGRAMA,
  A.DATA_INICIO,
  A.DATA_FIM,
  A.TIP_LOGRA,
  A.LOGRADOURO,
  A.NUMERO,
  A.COMPLEMENTO,
  A.BAIRRO,
  A.CIDADE,
  A.COD_UF,
  A.CEP,
  A.CNPJ
FROM V_EST_ORG_AVT A
WHERE A.COD_NIVEL_ORG = 3
  AND A.COD_TIPO IN (2, 3, 4)
  AND EXISTS (
        SELECT 1
        FROM V_EST_ORG_AVT B
        WHERE B.COD_NIVEL_ORG = 5
          AND B.COD3 = A.COD3
      )
ORDER BY A.COD_TIPO, A.EDICAO_ORG

),

SETOR5 AS (
SELECT
  A.COD_ORGANOGRAMA_SUB,
  A.EDICAO_ORG,
  A.COD_ORGANOGRAMA,
  A.NOME_ORGANOGRAMA,
  A.DATA_INICIO,
  A.DATA_FIM,
  A.TIP_LOGRA,
  A.LOGRADOURO,
  A.NUMERO,
  A.COMPLEMENTO,
  A.BAIRRO,
  A.CIDADE,
  A.COD_UF,
  A.CEP,
  A.CNPJ
FROM V_EST_ORG_AVT A
WHERE A.COD_NIVEL_ORG = 5
  AND A.COD_TIPO IN (2, 3, 4)
  AND EXISTS (
        SELECT 1
        FROM V_EST_ORG_AVT B
        WHERE B.COD_NIVEL_ORG = 5
          AND B.COD3 = A.COD3
      )
ORDER BY A.COD_TIPO, A.EDICAO_ORG

),

EMPRESAS AS (
SELECT
  A.COD_ORGANOGRAMA_SUB,
  A.EDICAO_ORG,
  A.COD_ORGANOGRAMA,
  A.NOME_ORGANOGRAMA,
  A.DATA_INICIO,
  A.DATA_FIM,
  A.TIP_LOGRA,
  A.LOGRADOURO,
  A.NUMERO,
  A.COMPLEMENTO,
  A.BAIRRO,
  A.CIDADE,
  A.COD_UF,
  A.CEP,
  A.CNPJ
FROM V_EST_ORG_AVT A
WHERE A.COD_NIVEL_ORG = 2
  --AND A.COD_TIPO      = 1
  /*AND EXISTS (
        SELECT 1
        FROM V_EST_ORG_AVT B
        WHERE B.COD_NIVEL_ORG = 5
          AND B.COD3 = A.COD3
      )*/
ORDER BY A.COD_TIPO, A.EDICAO_ORG

)

SELECT * FROM LOJAS

UNION ALL

SELECT * FROM SETOR3

UNION ALL

SELECT * FROM SETOR5

UNION ALL

SELECT * FROM EMPRESAS