/* DIAGNÓSTICO: Buscar onde estão os Regionais em 2022 */
SELECT DISTINCT
    C.COD_CONTRATO,
    C.DES_PESSOA,
    C.DATA_ADMISSAO,
    C.DATA_DEMISSAO,
    F.DES_FUNCAO,
    O.COD_EMP,
    O.DES_EMP,
    O.COD_UNIDADE,
    O.DES_UNIDADE,
    O.DATA_INI_ORG,
    O.DATA_FIM_ORG
FROM V_DADOS_CONTRATO_AVT C
JOIN VH_CARGO_CONTRATO_AVT F ON F.COD_CONTRATO = C.COD_CONTRATO
JOIN VH_EST_ORG_CONTRATO_AVT O ON O.COD_CONTRATO = C.COD_CONTRATO
WHERE 
    -- Filtra por função que contenha REGIONAL
    UPPER(F.DES_FUNCAO) LIKE '%REGIONAL%'
    -- Filtra para pegar apenas quem estava ativo em 2022
    AND C.DATA_ADMISSAO <= TO_DATE('31/12/2022', 'DD/MM/YYYY')
    AND NVL(C.DATA_DEMISSAO, TO_DATE('31/12/2999', 'DD/MM/YYYY')) >= TO_DATE('01/01/2022', 'DD/MM/YYYY')
    -- Verifica validade do histórico de cargo e unidade em 2022
    AND F.DATA_INI_CLH <= TO_DATE('31/12/2022', 'DD/MM/YYYY') AND NVL(F.DATA_FIM_CLH, TO_DATE('31/12/2999', 'DD/MM/YYYY')) >= TO_DATE('01/01/2022', 'DD/MM/YYYY')
    AND O.DATA_INI_ORG <= TO_DATE('31/12/2022', 'DD/MM/YYYY') AND NVL(O.DATA_FIM_ORG, TO_DATE('31/12/2999', 'DD/MM/YYYY')) >= TO_DATE('01/01/2022', 'DD/MM/YYYY')
ORDER BY C.DES_PESSOA;
