/* Período alvo: 2022 a 2025 */
WITH PARAMS AS (
  SELECT TO_DATE('01/01/2022', 'DD/MM/YYYY') AS D_INI,
         TO_DATE('31/12/2025', 'DD/MM/YYYY') AS D_FIM
  FROM DUAL
),

/* Gera uma linha para cada mês do período, para explodir os contratos */
DATAS_REF AS (
  SELECT /*+ MATERIALIZE */
         ADD_MONTHS(TRUNC(p.D_INI,'MM'), LEVEL-1) AS DTA_INI,
         LAST_DAY(ADD_MONTHS(TRUNC(p.D_INI,'MM'), LEVEL-1)) AS DTA_FIM
  FROM PARAMS p
  CONNECT BY ADD_MONTHS(TRUNC(p.D_INI,'MM'), LEVEL-1) <= TRUNC(p.D_FIM,'MM')
),

/* HISTÓRICO DE CONTRATOS EXPLODIDO POR MÊS */
CONTRATOS AS (
  SELECT /*+ MATERIALIZE */
    DISTINCT
    CT.COD_CONTRATO,
    CT.DES_PESSOA,
    CT.DATA_ADMISSAO,
    CT.DATA_DEMISSAO,
    FN.DES_FUNCAO,
    ORG.COD_UNIDADE,
    ORG.DES_UNIDADE,
    ORG.COD_ORGANOGRAMA, -- Importante para vincular com a estrutura organizacional
    M.DTA_FIM AS MES_REF
  FROM V_DADOS_CONTRATO_AVT    CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON ORG.COD_CONTRATO = CT.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT   FN  ON FN.COD_CONTRATO  = CT.COD_CONTRATO
  CROSS JOIN DATAS_REF M
  WHERE
    CT.DATA_ADMISSAO <= M.DTA_FIM
    AND NVL(CT.DATA_DEMISSAO, TO_DATE('31/12/2999', 'DD/MM/YYYY')) >= M.DTA_INI
    AND ORG.DATA_INI_ORG <= M.DTA_FIM AND NVL(ORG.DATA_FIM_ORG, TO_DATE('31/12/2999', 'DD/MM/YYYY')) >= M.DTA_INI
    AND FN.DATA_INI_CLH  <= M.DTA_FIM AND NVL(FN.DATA_FIM_CLH,  TO_DATE('31/12/2999', 'DD/MM/YYYY')) >= M.DTA_INI
),

/* LOJAS ALVO (CIDADES ESPECÍFICAS) */
LOJAS_ALVO AS (
  SELECT /*+ MATERIALIZE */
    T5.COD_ORGANOGRAMA,
    TO_NUMBER(T5.EDICAO_ORG) AS COD_UNIDADE,
    T5.NOME_ORGANOGRAMA_B    AS DES_UNIDADE,
    T5.EDICAO_ORG, -- Hierarquia organizacional
    T3.CIDADE,
    T3.COD_UF
  FROM V_EST_ORG_AVT T5
  JOIN V_EST_ORG_AVT T3
         ON T3.COD_TIPO = T5.COD_TIPO
        AND T3.COD_NIVEL_ORG = 3
        AND T3.EDICAO_ORG = T5.EDICAO_ORG
  WHERE T5.COD_TIPO = 1
    AND T5.COD_NIVEL_ORG = 5
    AND T3.CIDADE IN ('ALECRIM','CATUIPE','CERRO LARGO','CORONEL BICACO','CRISSIUMAL','CRUZ ALTA',
                      'ENTRE IJUIS','GIRUA','GUARANI DAS MISSOES','HORIZONTINA','IBIRUBA','IJUI',
                      'PANAMBI','PORTO XAVIER','SANTA BARBARA DO SUL','SANTA ROSA','SANTO ANGELO',
                      'SANTO AUGUSTO','SANTO CRISTO','SAO LUIZ GONZAGA','SAO PAULO DAS MISSOES',
                      'TENENTE PORTELA','TRES DE MAIO','TRES PASSOS','TUPANCIRETA','TUPARENDI')
),

/* REGIONAIS: Busca unidades de nível 3 (Regional) que compartilham a mesma EDICAO_ORG das lojas */
UNIDADES_REGIONAIS AS (
  SELECT DISTINCT
    T3.COD_ORGANOGRAMA AS COD_ORG_REGIONAL,
    T3.EDICAO_ORG,
    TO_NUMBER(T3.EDICAO_ORG) AS COD_UNIDADE_REGIONAL
  FROM V_EST_ORG_AVT T3
  WHERE T3.COD_TIPO = 1
    AND T3.COD_NIVEL_ORG = 3 -- Nível Regional
),

/* 1. GERENTES DE LOJA (Direto na unidade da loja) */
GERENTES_LOJA AS (
    SELECT 
        TO_CHAR(C.MES_REF, 'YYYY') AS ANO,
        L.COD_UNIDADE AS COD_LOJA,
        L.DES_UNIDADE AS DES_LOJA,
        L.CIDADE,
        L.EDICAO_ORG,
        C.COD_CONTRATO,
        C.DES_PESSOA,
        C.DATA_ADMISSAO,
        C.DATA_DEMISSAO,
        C.DES_FUNCAO
    FROM CONTRATOS C
    JOIN LOJAS_ALVO L ON L.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
    WHERE UPPER(C.DES_FUNCAO) LIKE '%GERENTE%' 
      AND UPPER(C.DES_FUNCAO) NOT LIKE '%REGIONAL%'
),

/* 2. GERENTES REGIONAIS (Via EDICAO_ORG - mesma hierarquia) */
GERENTES_REGIONAL AS (
    SELECT 
        TO_CHAR(C.MES_REF, 'YYYY') AS ANO,
        L.COD_UNIDADE AS COD_LOJA,
        L.DES_UNIDADE AS DES_LOJA,
        L.CIDADE,
        C.COD_CONTRATO,
        C.DES_PESSOA,
        C.DATA_ADMISSAO,
        C.DATA_DEMISSAO,
        C.DES_FUNCAO
    FROM CONTRATOS C
    JOIN UNIDADES_REGIONAIS UR ON UR.COD_ORG_REGIONAL = C.COD_ORGANOGRAMA
    JOIN LOJAS_ALVO L ON L.EDICAO_ORG = UR.EDICAO_ORG -- Vincula pela hierarquia
    WHERE UPPER(C.DES_FUNCAO) LIKE '%REGIONAL%'
)

/* SELECT FINAL CRUZADO */
SELECT DISTINCT
    COALESCE(GL.ANO, GR.ANO) AS ANO,
    COALESCE(GL.COD_LOJA, GR.COD_LOJA) AS COD_LOJA,
    COALESCE(GL.DES_LOJA, GR.DES_LOJA) AS DES_LOJA,
    COALESCE(GL.CIDADE, GR.CIDADE) AS CIDADE,
    
    -- DADOS DO GERENTE DE LOJA
    GL.COD_CONTRATO AS COD_CONTR_GERENTE,
    GL.DES_PESSOA AS NOME_GERENTE,
    GL.DATA_ADMISSAO AS ADM_GERENTE,
    GL.DATA_DEMISSAO AS DEM_GERENTE,
    GL.DES_FUNCAO AS FUNCAO_GERENTE,
    
    -- DADOS DO REGIONAL
    GR.COD_CONTRATO AS COD_CONTR_REGIONAL,
    GR.DES_PESSOA AS NOME_REGIONAL,
    GR.DATA_ADMISSAO AS ADM_REGIONAL,
    GR.DATA_DEMISSAO AS DEM_REGIONAL,
    GR.DES_FUNCAO AS FUNCAO_REGIONAL

FROM GERENTES_LOJA GL
FULL OUTER JOIN GERENTES_REGIONAL GR
  ON GL.ANO = GR.ANO 
 AND GL.COD_LOJA = GR.COD_LOJA
 
ORDER BY ANO, CIDADE, DES_LOJA;
