/* ===============================================
   == RELATÓRIO DADOS CONTRATOS ALUGUÉIS (Oracle)
   == Mesclar apenas unidades listadas em UNIDADES_AGREGADAS
   =============================================== */

WITH 
BASE_CONTRATOS AS (
  /* BASE APENAS CONTRATOS VIGENTES */
  SELECT A.COD_UNIDADE,
         CASE
           WHEN A.COD_UNIDADE = 630 THEN
            'FOTOVOLTAICAS'
           ELSE
            V.DES_FANTASIA
         END AS DES_UNIDADE,
         V.REDE,
         A.COD_CONTRATO,
         A.IND_INATIVO,
         A.DTA_INICIO,
         A.DTA_TERMINO,
         B.VAL_FIXO,
         B.VAL_ANTIGO_ALUGUEL,
         B.VAL_NOVO_ALUGUEL,
         B.DTA_ALTERACAO,
         B.VAL_DIFERENCA,
         B.DTA_VALIDADE_DIF,
         B.VAL_DESCTO,
         B.DTA_DESCTO_INI,
         B.DTA_DESCTO_FIM
    FROM GRAZZ.GRZ_LOC_CONTRATOS A
    JOIN GRAZZ.GRZ_LOC_CONTR_VALORES B ON B.COD_CONTRATO = A.COD_CONTRATO
    LEFT JOIN SISLOGWEB.V_UNIDADES_ATIVAS V ON V.COD_UNIDADE = A.COD_UNIDADE
   WHERE A.COD_EMPRESA = 1
     AND A.IND_INATIVO = 0
     AND B.IND_INATIVO = 0
     AND B.COD_VALOR = 1
     --AND A.COD_UNIDADE = 53
),


/* APENAS VERIFICA A DATA DE REAJUSTE */
REAJUSTE AS (
  SELECT COD_UNIDADE,
         COD_CONTRATO,
         DTA_ALTERACAO
    FROM BASE_CONTRATOS
   WHERE DTA_ALTERACAO >= TRUNC(SYSDATE)
),


/* LOJAS QUE POSSUEM DESCONTOS */
DESCONTOS AS (
  SELECT COD_UNIDADE,
         COD_CONTRATO,
         VAL_DESCTO,
         DTA_DESCTO_INI,
         DTA_DESCTO_FIM,
         LAST_DAY(ADD_MONTHS(DTA_DESCTO_FIM, -1)) AS DESCONTO_ATE
    FROM BASE_CONTRATOS
   WHERE DTA_DESCTO_FIM >= TRUNC(SYSDATE)
),


/* LOJAS QUE POSSUEM DIFERENÇAS */
DIFERENCAS AS (
  SELECT COD_UNIDADE,
         COD_CONTRATO,
         VAL_DIFERENCA,
         DTA_VALIDADE_DIF AS VALIDADE_DIF        
    FROM BASE_CONTRATOS
   WHERE DTA_VALIDADE_DIF >= TRUNC(SYSDATE)
),


/* LOJAS QUE POSSUEM EMPRÉSTIMOS (por unidade+contrato) */
LOJAS_EMPRESTIMOS AS (
  SELECT A.COD_UNIDADE,
         A.COD_CONTRATO,
         SUM(NVL(A.VLR_ADIANTAMENTO, 0)) AS VLR_EMPRESTIMO,
         NULL AS EMPRESTIMO_ATE
    FROM GRAZZ.GRZ_LOC_MVTO A
    JOIN GRAZZ.GRZ_LOC_ADIANTAMENTOS B ON B.COD_PESSOA = A.COD_PESSOA
                                      AND B.COD_CONTRATO = A.COD_CONTRATO
   /*LÓGICA PARA INFORMAR EM UM ÚNICO CAMPO MES E ANO*/
   WHERE /*A.ANO_REFERENCIA = TO_NUMBER(SUBSTR('&PERIODO', 4, 4))
     AND A.MES_REFERENCIA = TO_NUMBER(SUBSTR('&PERIODO', 1, 2))*/
     
     A.ANO_REFERENCIA = 2025
     AND A.MES_REFERENCIA = 10
     AND A.VLR_ADIANTAMENTO <> 0
     AND A.COD_UNIDADE = 199
   GROUP BY A.COD_UNIDADE, A.COD_CONTRATO
),


/* RETENÇÃO (DEIXAR 284 FIXA POIS É SÓ ELA COM ESSE VALOR; DEIXAR RETENCAO_ATE FIXA, POIS NÃO EXISTE EM TABELA) */
LOJAS_RETENCAO AS (
  SELECT COD_UNIDADE,
         SUM(NVL(VLR_ADIANTAMENTO, 0)) AS VLR_RETENCAO,
         LAST_DAY(TO_DATE('08/2032', 'MM/YYYY')) AS RETENCAO_ATE
    FROM GRAZZ.GRZ_LOC_MVTO
    /*LÓGICA PARA INFORMAR EM UM ÚNICO CAMPO MES E ANO*/
   WHERE /*ANO_REFERENCIA = TO_NUMBER(SUBSTR('&PERIODO', 4, 4))
     AND MES_REFERENCIA = TO_NUMBER(SUBSTR('&PERIODO', 1, 2))*/
   
     ANO_REFERENCIA = 2025
     AND MES_REFERENCIA = 11
     AND VLR_ADIANTAMENTO <> 0
     AND COD_UNIDADE = 284
   GROUP BY COD_UNIDADE
),


/* LISTA FIXA DE UNIDADES QUE DEVEM AGREGAR NUMA ÚNICA LINHA */
UNIDADES_AGREGADAS AS (
  SELECT 22  AS COD_UNIDADE FROM dual UNION ALL
  SELECT 125 AS COD_UNIDADE FROM dual UNION ALL
  SELECT 337 AS COD_UNIDADE FROM dual UNION ALL
  SELECT 356 AS COD_UNIDADE FROM dual
),


/* AGREGAÇÃO: SE A UNIDADE ESTÁ NA LISTA, MESCLA (CHAVE -1); SENÃO, SEPARA POR CONTRATO */
CONTRATOS AS (
  SELECT B.COD_UNIDADE AS UNIDADE,
         
         /* chave de agrupamento condicional */
         CASE
           WHEN UA.COD_UNIDADE IS NOT NULL THEN
            -1
           ELSE
            B.COD_CONTRATO
         END AS CHAVE_GRP,
         
         MAX(B.DES_UNIDADE) AS DES_UNIDADE,
         MAX(B.REDE) AS REDE,
         
         CASE
           WHEN MIN(B.IND_INATIVO) = 0 THEN
            'ATIVO'
           WHEN MAX(B.IND_INATIVO) = 1 THEN
            'INATIVO'
           ELSE
            TO_CHAR(MAX(B.IND_INATIVO))
         END AS DES_SITUACAO,
         
         MIN(B.DTA_INICIO) AS DTA_INICIO,
         MAX(B.DTA_TERMINO) AS DTA_TERMINO,
         MAX(R.DTA_ALTERACAO) AS DTA_ALTERACAO,
         
         SUM(NVL(B.VAL_FIXO, 0)) AS VLR_ALUGUEL_FIXO,
         SUM(NVL(B.VAL_NOVO_ALUGUEL, 0)) AS VLR_NOVO_ALUGUEL,
         SUM(NVL(B.VAL_ANTIGO_ALUGUEL, 0)) AS VLR_ANTIGO_ALUGUEL,
         
         SUM(NVL(F_DIF.VAL_DIFERENCA, 0)) AS VLR_DIFERENCA,
         MAX(F_DIF.VALIDADE_DIF) AS DTA_DIFERENCA,
         
         CASE
           WHEN B.COD_UNIDADE = 284 THEN
            NVL(MAX(F_RET.VLR_RETENCAO), 0)
           ELSE
            SUM(NVL(D.VAL_DESCTO, 0))
         END AS VLR_DESCONTO,
         
         CASE
           WHEN B.COD_UNIDADE = 284 THEN
            MAX(F_RET.RETENCAO_ATE)
           ELSE
            MAX(D.DESCONTO_ATE)
         END AS DESCONTO_ATE,
         
         SUM(NVL(E.VLR_EMPRESTIMO, 0)) AS VLR_EMPRESTIMO,
         MAX(E.EMPRESTIMO_ATE) AS EMPRESTIMO_ATE
  
    FROM BASE_CONTRATOS B
    LEFT JOIN UNIDADES_AGREGADAS UA ON UA.COD_UNIDADE = B.COD_UNIDADE
    LEFT JOIN DESCONTOS D ON D.COD_UNIDADE = B.COD_UNIDADE
                         AND D.COD_CONTRATO = B.COD_CONTRATO
    LEFT JOIN DIFERENCAS F_DIF ON F_DIF.COD_UNIDADE = B.COD_UNIDADE
                              AND F_DIF.COD_CONTRATO = B.COD_CONTRATO
    LEFT JOIN LOJAS_EMPRESTIMOS E ON E.COD_UNIDADE = B.COD_UNIDADE
                                 AND E.COD_CONTRATO = B.COD_CONTRATO
    LEFT JOIN REAJUSTE R ON R.COD_UNIDADE = B.COD_UNIDADE
                        AND R.COD_CONTRATO = B.COD_CONTRATO
    LEFT JOIN LOJAS_RETENCAO F_RET ON F_RET.COD_UNIDADE = B.COD_UNIDADE
  
   GROUP BY B.COD_UNIDADE,
            CASE
              WHEN UA.COD_UNIDADE IS NOT NULL THEN
               -1
              ELSE
               B.COD_CONTRATO
            END,
            CASE
              WHEN B.COD_UNIDADE = 284 THEN
               F_RET.RETENCAO_ATE
            END
)

/* SELECT FINAL */
SELECT CT.UNIDADE,
       /*CASE
         WHEN CT.CHAVE_GRP = -1 THEN
          NULL
         ELSE
          CT.CHAVE_GRP
       END AS COD_CONTRATO,*/
       CT.DES_UNIDADE,
       CT.DTA_INICIO,
       CT.DTA_TERMINO,
       
       TO_CHAR(SUM(CASE
                     WHEN CT.DTA_ALTERACAO IS NOT NULL THEN
                      NVL(CT.VLR_ANTIGO_ALUGUEL, 0)
                     ELSE
                      NVL(NULLIF(CT.VLR_ALUGUEL_FIXO, 0), CT.VLR_NOVO_ALUGUEL)
                   END),
               'FM999G999G990D00') AS VLR_ALUGUEL,
       
       TO_CHAR(SUM(CT.VLR_DIFERENCA), 'FM999G999G990D00') AS DIFERENCA,
       TO_CHAR(CT.DTA_DIFERENCA,
               'fmMonth/yyyy',
               'NLS_DATE_LANGUAGE=Portuguese') AS DTA_DIFERENCA,
       
       TO_CHAR(SUM(CT.VLR_DESCONTO), 'FM999G999G990D00') AS DESCONTO,
       TO_CHAR(CT.DESCONTO_ATE,
               'fmMonth/yyyy',
               'NLS_DATE_LANGUAGE=Portuguese') AS DESCONTO_ATE,
       
       TO_CHAR(SUM(CT.VLR_EMPRESTIMO), 'FM999G999G990D00') AS EMPRESTIMO,
       TO_CHAR(CT.EMPRESTIMO_ATE,
               'fmMonth/yyyy',
               'NLS_DATE_LANGUAGE=Portuguese') AS EMPRESTIMO_ATE,
       
       TO_CHAR(SUM(CASE
                     WHEN CT.DTA_ALTERACAO IS NOT NULL THEN
                      NVL(CT.VLR_ANTIGO_ALUGUEL, 0)
                     ELSE
                      NVL(NULLIF(CT.VLR_ALUGUEL_FIXO, 0), CT.VLR_NOVO_ALUGUEL)
                   END + NVL(CT.VLR_DIFERENCA, 0) - NVL(CT.VLR_DESCONTO, 0) -
                   NVL(CT.VLR_EMPRESTIMO, 0)),
               'FM999G999G990D00') AS SALDO

  FROM CONTRATOS CT
  /*LÓGICA ABAIXO APRESENTA MAIS DINAMISMO - DEIXAR UM DOS CAMPOS EM BRANCO NÃO ANULA O OUTRO
    PODENDO INFORMAR UMA UNIDADE ESPECÍFICA OU DEIXAR EM BRANCO PARA TODAS; MESMO CASO PARA REDE*/
  WHERE (NVL('&UNIDADE','') IS NULL OR ct.UNIDADE = '&UNIDADE')
    AND (NVL('&REDE','') IS NULL OR ct.REDE = '&REDE')
 GROUP BY CT.UNIDADE,
          CT.REDE,
          CASE
            WHEN CT.CHAVE_GRP = -1 THEN
             NULL
            ELSE
             CT.CHAVE_GRP
          END,
          CT.DES_UNIDADE,
          CT.DTA_INICIO,
          CT.DTA_TERMINO,
          CT.DTA_ALTERACAO,
          CT.DTA_DIFERENCA,
          CT.DESCONTO_ATE,
          CT.EMPRESTIMO_ATE
 ORDER BY CT.REDE,
          UNIDADE,
          CASE
            WHEN CT.CHAVE_GRP = -1 THEN
             NULL
            ELSE
             CT.CHAVE_GRP
          END;

         
         
         
         
