CREATE OR REPLACE VIEW V_AFASTAMENTOS_AVT AS
SELECT CT.COD_CONTRATO,
       PF.NOME_PESSOA AS DES_PESSOA,
       NVL(AF.COD_CAUSA_AFAST,0) AS  STATUS_AFASTAMENTO,
       AF.DATA_INICIO AS DATA_INI_AFAST,
       AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       PESSOA_FISICA PF
 WHERE CT.COD_CONTRATO= AF.COD_CONTRATO(+)
   AND CT.COD_FUNC = PF.COD_PESSOA(+)

   --AND '30/04/2025' BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   --AND CT.COD_CONTRATO = 389622


/*SELECT A.COD_CONTRATO,
       A.DATA_INICIO,
       A.DATA_FIM,
       A.COD_CAUSA_AFAST,
       C.NOME_CAUSA_AFAST,
       CASE
         WHEN B.DATA_FIM < TRUNC(SYSDATE) THEN
          1
         ELSE
          0
       END AS STATUS,
       CASE
         WHEN B.DATA_FIM < TRUNC(SYSDATE) THEN
          'INATIVO'
         WHEN B.DATA_INICIO <= TRUNC(SYSDATE) THEN
          'ATIVO'
         ELSE
          'ADMISSAO_FUTURA'
       END AS DESC_STATUS,
       NVL(A.COD_CAUSA_AFAST, 0) AS COD_STATUS_AFAST,
       CASE
         WHEN B.DATA_FIM IS NOT NULL AND B.DATA_FIM < SYSDATE THEN
          'INATIVO'
         WHEN A.COD_CAUSA_AFAST <> 0 AND A.COD_CAUSA_AFAST <> 4 AND
              A.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'AFASTADO'
         WHEN A.COD_CAUSA_AFAST = 7 THEN
          'EM FÉRIAS'
         WHEN A.COD_CAUSA_AFAST IN (3, 6) THEN
          'AFASTADO TEMP'
         WHEN A.COD_CAUSA_AFAST = 4 AND
              A.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'PODERÁ RETORNAR'
         ELSE
          'EM ATIVIDADE'
       END AS STATUS_AFAST
  FROM RHFP0306 A
  FULL OUTER JOIN RHFP0300 B ON B.COD_CONTRATO = A.COD_CONTRATO
  FULL OUTER JOIN RHFP0100 C ON A.COD_CAUSA_AFAST = C.COD_CAUSA_AFAST
WHERE A.COD_CONTRATO = 389622
  AND ('30/04/2025' BETWEEN A.DATA_INICIO AND A.DATA_FIM OR A.DATA_INICIO IS NULL)*/

