CREATE OR REPLACE VIEW V_QUEBRA_DE_CAIXA_AVT AS
WITH TEMPO AS (
    SELECT
        A.COD_USUARIO,
        PS.NOME_PESSOA AS DES_USUARIO,
        NMCLH.NOME_CLH AS NOME_CARGO,
        K.QTD_HORBAS_MES,
        SUM(ROUND(A.TEMPO_LOGIN / 60, 2)) AS TEMPO_LOGIN,        
        DL.COD_UNIDADE,
        DL.DES_UNIDADE
    FROM
        SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ A
    JOIN
        RHFP0340 CARGO ON CARGO.COD_CONTRATO = A.COD_USUARIO AND CARGO.DATA_FIM = '31/12/2999'
    JOIN
        RHFP0307 G ON G.COD_CONTRATO = A.COD_USUARIO AND G.DATA_FIM = '31/12/2999'
    JOIN
        RHFP0321 K ON K.COD_HORAS_BASE = G.COD_HORAS_BASE
    JOIN
        RHFP0500 NMCLH ON NMCLH.COD_CLH = CARGO.COD_CLH
    LEFT JOIN
             RHFP0300 CT ON A.COD_USUARIO = CT.COD_CONTRATO
    LEFT JOIN
             PESSOA PS ON CT.COD_FUNC = PS.COD_PESSOA
    JOIN
        V_DADOS_LOJAS_AVT DL ON A.COD_UNIDADE = DL.COD_UNIDADE
    WHERE
        TO_DATE(SUBSTR(A.HORA_INICIAL, 1, 10), 'DD/MM/YYYY') BETWEEN
            TO_DATE('15/' || TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE), -1), 'MM/YYYY'), 'DD/MM/YYYY')
            AND TO_DATE('15/' || TO_CHAR(TRUNC(SYSDATE), 'MM/YYYY'), 'DD/MM/YYYY')
        AND CARGO.COD_CLH NOT IN (102, 47, 225, 120)
        AND NMCLH.NOME_CLH NOT LIKE '%GERENTE%'
        AND NOT EXISTS (
            SELECT 1
            FROM V_DADOS_PESSOA Y
            WHERE Y.COD_FUNCAO IN (225, 120)
              AND Y.DES_GRUPO LIKE '%FRANCO GIORGI%'
              AND Y.COD_CONTRATO = A.COD_USUARIO
        )
    GROUP BY
        A.COD_USUARIO, PS.NOME_PESSOA, K.QTD_HORBAS_MES, NMCLH.NOME_CLH, DL.COD_UNIDADE, DL.DES_UNIDADE
)

SELECT
    T.COD_USUARIO,
    T.DES_USUARIO,
    T.NOME_CARGO,
    TO_DATE(TO_CHAR(LAST_DAY(SYSDATE), 'DD/MM/YYYY')) AS DATA_REFERENCIA,
    SUM(T.TEMPO_LOGIN) AS TEMPO_LOGIN,
    CT.DATA_FIM,
    T.QTD_HORBAS_MES,
    T.COD_UNIDADE,
    T.DES_UNIDADE
FROM
    TEMPO T
JOIN
    RHFP0300 CT ON CT.COD_CONTRATO = T.COD_USUARIO
WHERE
    NOT EXISTS (
        SELECT 1
        FROM RHFP1004 A
        WHERE A.COD_CONTRATO = T.COD_USUARIO
          AND A.DATA_MOV IN (TO_CHAR(LAST_DAY(SYSDATE), 'DD/MM/YYYY'), CT.DATA_FIM)
          AND A.COD_VD = 838
          AND A.COD_EVENTO IN (1, 17)
    )
GROUP BY
    T.COD_USUARIO, T.DES_USUARIO, CT.DATA_FIM, T.QTD_HORBAS_MES, T.NOME_CARGO, T.COD_UNIDADE, T.DES_UNIDADE

