CREATE OR REPLACE VIEW V_QUEBRA_CAIXA_AVT AS
SELECT PESSOA.EDICAO_NIVEL3,
       PESSOA.NOME_ORGANOGRAMA,
       CARGO.COD_CLH,
       CARGO.NOME_CLH,
       PESSOA.COD_CONTRATO,
       PESSOA.NOME_FUNCIONARIO,
       (TRIM(TO_CHAR(RHYF0118(TEMPO.TEMPO_LOGIN_EM_HORAS), '990,00'))) AS TEMPO_LOGIN_TOT,
       PESSOA.DATA_DEMISSAO
  FROM (SELECT F.COD_USUARIO,
               SUM(ROUND((F.TEMPO_LOGIN / 60), 2)) AS TEMPO_LOGIN_EM_HORAS
          FROM SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ F
         WHERE TO_DATE(SUBSTR(HORA_INICIAL, 1, 10)) >=
               TO_DATE('15/' ||
                       TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE), -1), 'MM/YYYY'),
                       'DD/MM/YYYY')
           AND TO_DATE(SUBSTR(HORA_INICIAL, 1, 10)) <=
               TO_DATE('15/' || TO_CHAR(TRUNC(SYSDATE), 'MM/YYYY')) -- PERÍODO ENTRE DIA 15 DO MES PASSADO AO DIA 15 DO MES ATUAL
         GROUP BY F.COD_USUARIO) TEMPO,
       (SELECT DISTINCT G.EDICAO_NIVEL3,
                        E.NOME_ORGANOGRAMA,
                        B.COD_CONTRATO,
                        A.NOME_PESSOA AS NOME_FUNCIONARIO,
                        H.COD_CLH,
                        B.DATA_FIM AS DATA_DEMISSAO
          FROM PESSOA   A,
               RHFP0300 B,
               RHFP0310 D,
               RHFP0400 E,
               RHFP0401 G,
               RHFP0340 H,
               RHFP0500 J
         WHERE B.COD_FUNC = A.COD_PESSOA
           AND D.COD_CONTRATO = B.COD_CONTRATO
           AND B.COD_CONTRATO = H.COD_CONTRATO
           AND H.COD_CLH = J.COD_CLH
           AND D.DATA_FIM = '31/12/2999'
           AND H.DATA_FIM = '31/12/2999'
           AND E.COD_ORGANOGRAMA = D.COD_ORGANOGRAMA
           AND E.COD_ORGANOGRAMA = G.COD_ORGANOGRAMA
           AND G.EDICAO_NIVEL3 NOT IN ('001', '013')
         ORDER BY G.EDICAO_NIVEL3, B.COD_CONTRATO) PESSOA,
       (SELECT A.COD_CONTRATO, A.COD_CLH, B.NOME_CLH
          FROM RHFP0340 A, RHFP0500 B
         WHERE A.COD_CLH = B.COD_CLH
           AND A.DATA_FIM = '31/12/2999') CARGO
 WHERE TEMPO.COD_USUARIO = PESSOA.COD_CONTRATO
   AND CARGO.COD_CONTRATO = PESSOA.COD_CONTRATO
   AND PESSOA.COD_CLH = CARGO.COD_CLH
      -- AND PESSOA.COD_CONTRATO = 388239
   AND CARGO.NOME_CLH NOT LIKE '%SERVENTE%'
   AND CARGO.NOME_CLH NOT LIKE '%GERENTE%'
   AND CARGO.NOME_CLH NOT LIKE '%APRENDIZ%'
   AND CARGO.NOME_CLH NOT LIKE '%CAIXA GERAL%'
   AND PESSOA.EDICAO_NIVEL3 NOT IN
       (SELECT DISTINCT COD_UNIDADE
          FROM V_DADOS_PESSOA
         WHERE DES_GRUPO LIKE '%FRANCO GIORGI%'
           AND COD_FUNCAO = 120)
 ORDER BY PESSOA.EDICAO_NIVEL3, TEMPO.COD_USUARIO

