CREATE TABLE RHFP0258_BKP1025
AS
SELECT *
FROM RHFP0258
/
CREATE OR REPLACE PROCEDURE ECONSIGFIX(v_origem IN NUMBER, v_proximo IN NUMBER)
AS
  v_ct_ant  NUMBER DEFAULT 0;
  v_conv    NUMBER DEFAULT 0;
BEGIN
  FOR c_cts in 
    (SELECT TB.COD_CONTRATO, TB.COD_CONVENIO, TB.DATA_COMPRA, TB.SEQ
     FROM RHFP0258 TB,
          (SELECT COD_CONTRATO, COD_CONVENIO, SEQUENCIA_PRESTACAO, COUNT(*) AS TOT
           FROM RHFP0258
           WHERE COD_CONVENIO = v_origem
             AND SEQUENCIA_PRESTACAO = 999
           GROUP BY COD_CONTRATO, COD_CONVENIO, SEQUENCIA_PRESTACAO
           HAVING COUNT(*) > 1) REP
     WHERE TB.COD_CONTRATO = REP.COD_CONTRATO
       AND TB.COD_CONVENIO = REP.COD_CONVENIO
       AND TB.SEQUENCIA_PRESTACAO = REP.SEQUENCIA_PRESTACAO
     ORDER BY COD_CONTRATO, DATA_COMPRA) LOOP
     IF (c_cts.COD_CONTRATO <> v_ct_ant) THEN
       v_conv := V_PROXIMO;
     ELSE
       UPDATE RHFP0258
         SET COD_CONVENIO = v_conv
       WHERE COD_CONTRATO = c_cts.COD_CONTRATO
       AND COD_CONVENIO = c_cts.COD_CONVENIO
       AND DATA_COMPRA = c_cts.DATA_COMPRA
       AND SEQ = c_cts.SEQ;
       
       v_conv := v_conv + 1;
     END IF;
     v_ct_ant := c_cts.COD_CONTRATO;
  END LOOP;
  COMMIT;  
END;
/
EXECUTE ECONSIGFIX(2,3)
/
