--SELECT VIEW OFFICIAL V_DADOS_LOJAS_AVT


-----VERSÃO 1 ==================

SELECT
    LOJASATV.COD_PESSOA,
    LOJASATV.COD_ORGANOGRAMA_SUB,
    LOJASATV.COD_ORGANOGRAMA,
    LOJASATV.UNIDADE,
    LOJASATV.NOME_UNIDADE,
    LOJASATV.REDE,
    LOJASATV.DES_REDE,
    LOJASATV.EMAIL,
    LOJASATV.VALOR AS REGIAO,
    LOJASATV.NUM_CGC AS CNPJ,
    LOJASATV.CEP,
    LOJASATV.TIP_LOGRA AS LOGRADOURO,
    LOJASATV.NOME_LOGRA AS NOME_LOGRADOURO,
    LOJASATV.NUMERO,
    LOJASATV.NOME_BAIRRO,
    LOJASATV.NOME_MUNIC AS CIDADE,
    LOJASATV.COD_UF
FROM (
    SELECT
        J.COD_PESSOA,
        A1.COD_ORGANOGRAMA_SUB,
        A2.COD_ORGANOGRAMA,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END UNIDADE,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END || ' - ' || UNI.DES_FANTASIA AS NOME_UNIDADE,
        NVL(UNI.REDE, 0) REDE,
        DECODE(UNI.REDE,
            10,
            'GRAZZIOTIN',
            30,
            'PORMENOS',
            40,
            'FRANCO GIORGI',
            50,
            'TOTTAL',
            70,
            'GZT STORE') DES_REDE,
        J.EMAIL,
        PE.VALOR,
        UNI.NUM_CGC,
        J.CEP,
        L.TIP_LOGRA,
        L.NOME_LOGRA,
        J.NUMERO,
        B.NOME_BAIRRO,
        M.NOME_MUNIC,
        J.COD_UF,
        ROW_NUMBER() OVER (PARTITION BY UNI.COD_UNIDADE ORDER BY
            CASE WHEN A2.COD_NIVEL_ORG = 5 AND A3.COD_NIVEL_CONTABIL = 5 THEN 0 ELSE 1 END
        ) AS RN
    FROM
        SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI,
        RHFP0401 A1,
        RHFP0400 A2,
        RHFP0402 A3,
        RHFP0310 B1,
        JURIDICA J,
        PE0002 PE,
        MUNICI M,
        BAIRRO B,
        LOGRA L
    WHERE
        UNI.COD_UNIDADE = A1.EDICAO_ORG
        AND A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
        AND B1.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND J.CGC = UNI.NUM_CGC
        AND PE.COD_PESSOA = J.COD_PESSOA
        AND M.COD_MUNIC = J.COD_MUNIC
        AND B.COD_BAIRRO = J.COD_BAIRRO
        AND L.COD_LOGRA = J.COD_LOGRA
        AND UNI.COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549, 7549)
        AND PE.VALOR BETWEEN 8701 AND 8719
        AND A2.COD_NIVEL_ORG = 5
        AND A3.COD_NIVEL_CONTABIL = 5
        AND A3.EDICAO_NIVEL5 IS NOT NULL
        AND A1.COD_NIVEL2 <> 282
        AND A1.DATA_FIM = '31/12/2999'
        AND B1.DATA_FIM = '31/12/2999'
        AND (
            (UNI.COD_UNIDADE LIKE '7%' AND B1.DATA_INICIO <= SYSDATE AND (B1.DATA_FIM IS NULL OR B1.DATA_FIM > SYSDATE))
            OR
            (UNI.COD_UNIDADE NOT LIKE '7%')
        )
) LOJASATV
WHERE RN = 1
ORDER BY
    LOJASATV.UNIDADE ASC;




--=====================================================--
--=====================================================--

-----VERSÃO 2 ==================


SELECT
    LOJASATV.COD_PESSOA,
    LOJASATV.COD_ORGANOGRAMA_SUB,
    LOJASATV.COD_ORGANOGRAMA,
    LOJASATV.UNIDADE,
    LOJASATV.NOME_UNIDADE,
    LOJASATV.REDE,
    LOJASATV.DES_REDE,
    LOJASATV.EMAIL,
    LOJASATV.VALOR AS REGIAO,
    LOJASATV.EDICAO_NIVEL1 || '.' || 
    LOJASATV.EDICAO_NIVEL2 || '.' || 
    LOJASATV.EDICAO_NIVEL3 || '.' || 
    LOJASATV.EDICAO_NIVEL4 || '.' || 
    LOJASATV.EDICAO_NIVEL5 AS EDICAO_COMPLETA,
    LOJASATV.NUM_CGC AS CNPJ,
    LOJASATV.CEP,
    LOJASATV.TIP_LOGRA AS LOGRADOURO,
    LOJASATV.NOME_LOGRA AS NOME_LOGRADOURO,
    LOJASATV.NUMERO,
    LOJASATV.NOME_BAIRRO,
    LOJASATV.NOME_MUNIC AS CIDADE,
    LOJASATV.COD_UF
FROM (
    SELECT
        J.COD_PESSOA,
        A1.COD_ORGANOGRAMA_SUB,
        A2.COD_ORGANOGRAMA,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END UNIDADE,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END || ' - ' || UNI.DES_FANTASIA AS NOME_UNIDADE,
        NVL(UNI.REDE, 0) REDE,
        DECODE(UNI.REDE,
            10,
            'GRAZZIOTIN',
            30,
            'PORMENOS',
            40,
            'FRANCO GIORGI',
            50,
            'TOTTAL',
            70,
            'GZT STORE') DES_REDE,
        J.EMAIL,
        PE.VALOR,
        UNI.NUM_CGC,
        J.CEP,
        L.TIP_LOGRA,
        L.NOME_LOGRA,
        J.NUMERO,
        B.NOME_BAIRRO,
        M.NOME_MUNIC,
        J.COD_UF,
        A1.EDICAO_NIVEL1,
        A1.EDICAO_NIVEL2,
        A1.EDICAO_NIVEL3,
        A1.EDICAO_NIVEL4,
        A1.EDICAO_NIVEL5,
        ROW_NUMBER() OVER (PARTITION BY UNI.COD_UNIDADE ORDER BY
            CASE WHEN A2.COD_NIVEL_ORG = 5 AND A3.COD_NIVEL_CONTABIL = 5 THEN 0 ELSE 1 END
        ) AS RN
    FROM
        SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI,
        RHFP0401 A1,
        RHFP0400 A2,
        RHFP0402 A3,
        RHFP0310 B1,
        JURIDICA J,
        PE0002 PE,
        MUNICI M,
        BAIRRO B,
        LOGRA L
    WHERE
        UNI.COD_UNIDADE = A1.EDICAO_ORG
        AND A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
        AND B1.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND J.CGC = UNI.NUM_CGC
        AND PE.COD_PESSOA = J.COD_PESSOA
        AND M.COD_MUNIC = J.COD_MUNIC
        AND B.COD_BAIRRO = J.COD_BAIRRO
        AND L.COD_LOGRA = J.COD_LOGRA
        AND UNI.COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549, 7549)
        AND PE.VALOR BETWEEN 8701 AND 8719
        AND A2.COD_NIVEL_ORG = 5
        AND A3.COD_NIVEL_CONTABIL = 5
        AND A3.EDICAO_NIVEL5 IS NOT NULL
        AND A1.COD_NIVEL2 <> 282
        AND A1.DATA_FIM = '31/12/2999'
        AND B1.DATA_FIM = '31/12/2999'
        AND (
            (UNI.COD_UNIDADE LIKE '7%' AND B1.DATA_INICIO <= SYSDATE AND (B1.DATA_FIM IS NULL OR B1.DATA_FIM > SYSDATE))
            OR
            (UNI.COD_UNIDADE NOT LIKE '7%')
        )
) LOJASATV
WHERE RN = 1
ORDER BY
    LOJASATV.UNIDADE ASC;