--==AJUSTANDO==--  ---==PODE SER O OFICAL==---

WITH CTE AS (
  SELECT
    A.COD_UNIDADE AS UNIDADE,
    A.DES_FANTASIA AS NOME_UNIDADE,
    C.COD_FIADOR AS FIADOR,
    C.DES_FIADOR AS NOME_FIADOR,
    A.REDE,
    D.COD_GRUPO AS GRUPO,
    TO_CHAR(B.DTA_INICIO, 'DD/MM/YYYY') AS DATA_INICIO,
    TO_CHAR(B.DTA_TERMINO, 'DD/MM/YYYY') AS DATA_TERMINO,
    B.IND_INATIVO AS STATUS,
    CASE
        WHEN B.IND_INATIVO = 0 THEN 'ATIVO'
        WHEN B.IND_INATIVO = 1 THEN 'INATIVO'
        ELSE
         NULL
    END AS DES_STATUS,
    COUNT(*) OVER(PARTITION BY A.COD_UNIDADE, B.DTA_TERMINO) AS QTD_CONTRATOS_COM_MESMA_DATA,
    B.DTA_TERMINO
  FROM V_UNIDADES_ATIVAS A
  INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
  INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
  INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
  LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO = E.COD_CONTRATO
  WHERE D.COD_GRUPO = 999
    AND A.COD_UNIDADE BETWEEN 0 AND 9999
    AND B.DTA_TERMINO > SYSDATE
    --AND B.IND_INATIVO = 0                                                          
),
FILTERED_CTE AS (
  SELECT 
    UNIDADE,
    NOME_UNIDADE,
    FIADOR,
    NOME_FIADOR,
    REDE,
    GRUPO,
    TO_DATE(DATA_INICIO, 'DD/MM/YYYY') AS DATA_INICIO,
    TO_DATE(DATA_TERMINO, 'DD/MM/YYYY') AS DATA_TERMINO,
    STATUS,
    DES_STATUS,
    QTD_CONTRATOS_COM_MESMA_DATA
  FROM CTE
  WHERE DTA_TERMINO > SYSDATE 
    OR QTD_CONTRATOS_COM_MESMA_DATA > 1
    OR DTA_TERMINO = TO_DATE('31/12/2999', 'DD/MM/YYYY')
),
TOT_VR_GRAZZIOTIN AS (
  SELECT 'Total Tipo Fiador: VR Grazziotin S/A' AS NOME_UNIDADE, COUNT(*) AS TOTAL
  FROM FILTERED_CTE
  WHERE FIADOR = 1
),
TOT_NENHUM AS (
  SELECT 'Total Tipo Fiador: Nenhum' AS NOME_UNIDADE, COUNT(*) AS TOTAL
  FROM FILTERED_CTE
  WHERE FIADOR = 3
),
TOTAL_GERAL AS (
  SELECT 'Total Geral' AS NOME_UNIDADE, COUNT(*) AS TOTAL
  FROM FILTERED_CTE
)
SELECT UNIDADE, NOME_UNIDADE, TO_CHAR(FIADOR) AS FIADOR, NOME_FIADOR, REDE, TO_CHAR(GRUPO) AS GRUPO, DATA_INICIO, DATA_TERMINO, TO_CHAR(STATUS) AS STATUS, TO_CHAR(DES_STATUS) AS DES_STATUS FROM FILTERED_CTE
UNION ALL
SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL
UNION ALL
SELECT NULL, NOME_UNIDADE, NULL, NULL, NULL, TO_CHAR(TOTAL), NULL, NULL, NULL, NULL FROM TOT_VR_GRAZZIOTIN
UNION ALL
SELECT NULL, NOME_UNIDADE, NULL, NULL, NULL, TO_CHAR(TOTAL), NULL, NULL, NULL, NULL FROM TOT_NENHUM
UNION ALL
SELECT NULL, NOME_UNIDADE, NULL, NULL, NULL, TO_CHAR(TOTAL), NULL, NULL, NULL, NULL FROM TOTAL_GERAL
