LIBERAÇÃO DE ACESSO AOS FORMULÁRIOS

SELECT * FROM GRZ_FORM_LIBERACOES;

INSERT INTO GRZ_FORM_LIBERACOES (COD_REDE, COD_UNIDADE, COD_COLABORADOR, COD_FORM_PORTAL, IND_ATIVO, DTA_CADASTRO, DES_FORM, DES_PESSOA, VER_PDF)
VALUES(999, 999, 390289, 3, 1, '08/08/2022', 'Formulário Aprovação de Ponto', 'TABATA MORAIS LANZARIN', 1);

