
SELECT A.COD_PESSOA, C.NOME_ORGANOGRAMA, A.COD_CAMPO, B.EDICAO_NIVEL3,  B.COD_ORGANOGRAMA, A.VALOR
FROM PE0002 A, RHFP0401 B, RHFP0400 C, JURIDICA JU
WHERE B.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
AND C.COD_PESSOA  = JU.COD_PESSOA 
AND JU.COD_PESSOA  = A.COD_PESSOA 
AND COD_CAMPO = 1 
--AND VALOR = 8701
AND B.COD_ORGANOGRAMA IN (
'1782',
'1784',
'1785'
)
ORDER BY A.VALOR,B.EDICAO_NIVEL3 ASC




-- CONSULTA LOJAS DA REGIÃO

SELECT * FROM PE0002
WHERE COD_CAMPO = 1
AND VALOR = 8711


-- CONSULTAR

SELECT * FROM OPERORG
where cod_operador = 'F378318'
ORDER BY COD_ORGANOGRAMA


-- DELETAR

DELETE FROM OPERORG
where cod_operador = 'F378318'


-- INSERIR 

INSERT INTO OPERORG (COD_OPERADOR, COD_ORGANOGRAMA, IND_ATIVOS)
SELECT 'F378318', A.COD_ORGANOGRAMA , 'N'
FROM RHFP0400 A, PE0002 B 
WHERE A.COD_PESSOA (+) = B.COD_PESSOA 
AND COD_CAMPO = 1
AND VALOR = 8711
ORDER BY A.COD_ORGANOGRAMA