/*COMANDO PARA EXECUTAR CASO ALGUM OPERADOR NÃO POSSUIR PROVILÉGIOS SUFICIENES PARA EXECUTAR ALGUMA OPERAÇÃO CRUD NO SISTEMA

SMPRE EXECUTAR ESSE COMANDO PELO BANCO DE DADOS, CONECTADO AO USUÁRIO SUPGR

--====================--

USUÁRIO DO SUPGR E SENHA

USUÁRIO: SUPGR
SENHA: SUPGR

--=============---*/

GRANT CONNECT,
      RESOURCE,
      UNLIMITED TABLESPACE,
      CREATE USER,
      DROP USER,
      ALTER USER,
      CREATE ANY SYNONYM,
      DROP ANY SYNONYM,
      CREATE ANY VIEW,
      DROP ANY VIEW,
      CREATE ANY TRIGGER,
      DROP ANY TRIGGER
TO "F379135" WITH ADMIN OPTION