/* === COMANDOS PARA IDENTIFICAR INTEGRIDADES E/OU ERROS EM VIEWS


-- Verificar erros específicos da view
SELECT * FROM ALL_ERRORS WHERE NAME = 'V_RESP_ORGANOGRAMAS_AVT' AND TYPE = 'VIEW';

-- Obter o código da view
SELECT TEXT FROM ALL_VIEWS WHERE VIEW_NAME = 'V_RESP_ORGANOGRAMAS_AVT';

-- Compilar a view
ALTER VIEW GRZ_FOLHA.V_RESP_ORGANOGRAMAS_AVT COMPILE;

-- Verificar dependências da view
SELECT * FROM USER_DEPENDENCIES WHERE NAME = 'V_RESP_ORGANOGRAMAS_AVT';

-- Recompilar views subjacentes
ALTER VIEW V_DADOS_LOJAS_AVT COMPILE;
ALTER VIEW V_SETORES_ADM_AVT COMPILE;

-- Verificar colunas nas views subjacentes
DESCRIBE V_DADOS_LOJAS_AVT;
DESCRIBE V_SETORES_ADM_AVT;

-- Recompilar a view após correção
ALTER VIEW GRZ_FOLHA.V_RESP_ORGANOGRAMAS_AVT COMPILE;

-- Obter o código da view V_RESP_ORGANOGRAMAS_AVT
SELECT TEXT FROM ALL_VIEWS WHERE VIEW_NAME = 'V_RESP_ORGANOGRAMAS_AVT';

-- Verificar todas as views que estão inválidas
SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE = 'VIEW' AND STATUS = 'INVALID';

-- Verificar erros específicos da view V_RESP_ORGANOGRAMAS_AVT
SELECT * FROM ALL_ERRORS WHERE NAME = 'V_RESP_ORGANOGRAMAS_AVT' AND TYPE = 'VIEW';
