--COMANDO PARA DERRUBAR SESSÃO DE USUÁRIOS DE UM SISTEMA, 
  --COM BASE NA BASE DE DADOS EM QUE ESTIVER LOGADO REFENRENTE AO SISTEMA QUE DESEJA DERRUBAR A SESSÃO DOS USUÁRIOS, 
  --NESSE CASO O SISTEMA DA FOLHA


SELECT s.sid, s.serial#, s.username
FROM v$session s
WHERE s.username = 'DELTA';

ALTER SYSTEM KILL SESSION 'sid, serial#';