
--=====COMANDOS SQL PARA INSERIR NOVOS ARQUIVOS E SEUS PARAMETROS NA TABELA RHFP3001



SELECT * FROM RHFP3001
WHERE COD_ARQUIVO IN (5073, 5074)



SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       1 AS TIPO_REGISTRO,
       0 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       2 AS TIPO_REGISTRO,
       1 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       3 AS TIPO_REGISTRO,
       2 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       5 AS TIPO_REGISTRO,
       4 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       6 AS TIPO_REGISTRO,
       5 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       71 AS TIPO_REGISTRO,
       0 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       491 AS CAMPO_QUEBRA,
       1 AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

--====

UNION ALL

--====

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       1 AS TIPO_REGISTRO,
       0 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       2 AS TIPO_REGISTRO,
       1 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       3 AS TIPO_REGISTRO,
       2 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       5 AS TIPO_REGISTRO,
       4 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       6 AS TIPO_REGISTRO,
       5 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       71 AS TIPO_REGISTRO,
       0 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       491 AS CAMPO_QUEBRA,
       1 AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001


--INSERTS PARA O NOVO ARQUIVO TABELA RHFP3001


INSERT INTO RHFP3001 (COD_ARQUIVO, TIPO_REGISTRO, SEQUENCIA, TAMANHO, SELECAO, ORIGEM, DICIONARIO, CAMPO_QUEBRA, NIVEL_QUEBRA, QTD_LINHAS)
SELECT DISTINCT COD_ARQUIVO, TIPO_REGISTRO, SEQUENCIA, TAMANHO, SELECAO, ORIGEM, DICIONARIO, CAMPO_QUEBRA, NIVEL_QUEBRA, QTD_LINHAS FROM (
    SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       1 AS TIPO_REGISTRO,
       0 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       2 AS TIPO_REGISTRO,
       1 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       3 AS TIPO_REGISTRO,
       2 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       5 AS TIPO_REGISTRO,
       4 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       6 AS TIPO_REGISTRO,
       5 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       71 AS TIPO_REGISTRO,
       0 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       491 AS CAMPO_QUEBRA,
       1 AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

--====

UNION ALL

--====

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       1 AS TIPO_REGISTRO,
       0 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       2 AS TIPO_REGISTRO,
       1 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       3 AS TIPO_REGISTRO,
       2 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       5 AS TIPO_REGISTRO,
       4 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       6 AS TIPO_REGISTRO,
       5 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       NULL AS CAMPO_QUEBRA,
       NULL AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       71 AS TIPO_REGISTRO,
       0 AS SEQUENCIA,
       165 AS TAMANHO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       491 AS CAMPO_QUEBRA,
       1 AS NIVEL_QUEBRA,
       NULL AS QTD_LINHAS
FROM RHFP3001
);