--====CTE OFICIAL PARA RETORNAR HORAS EXTRAS, ATRASOS E FALTAS DO CONTRATO===---



WITH OCORRENCIAS AS (
    SELECT B.COD_CONTRATO,
        B.DES_PESSOA,
        COD_UNIDADE,
        SUM(CASE WHEN COD_OCORRENCIA IN (203, 209) THEN NUM_HORAS ELSE 0 END) AS "EXTRAS DIURNAS ( GERAL )",  -- Incluindo múltiplos códigos para extras
        SUM(DECODE(COD_OCORRENCIA, 205, NUM_HORAS, 0)) AS "ATRASOS DIURNO ( GERAL )",
        SUM(CASE WHEN COD_OCORRENCIA IN (203, 209) THEN NUM_HORAS ELSE 0 END) - SUM(DECODE(COD_OCORRENCIA, 205, NUM_HORAS, 0)) AS TOTAL,
        SUM(DECODE(COD_OCORRENCIA, 1034, NUM_HORAS, 0)) AS BANCO_HORAS,
        LISTAGG(CASE WHEN COD_OCORRENCIA = 1034 THEN TO_CHAR(A.DATA_OCORRENCIA, 'DD/MM/YYYY') END, ', ') 
        WITHIN GROUP (ORDER BY A.DATA_OCORRENCIA) AS DATAS_FALTAS
    FROM RHAF1123 A
    INNER JOIN V_DADOS_PESSOA B ON B.COD_CONTRATO = A.COD_CONTRATO
    WHERE A.COD_OCORRENCIA IN (203, 205, 209, 1034)
    AND B.COD_UNIDADE IN ('769')
    AND A.DATA_OCORRENCIA BETWEEN  TO_DATE('01/05/2024', 'DD/MM/YYYY') AND  TO_DATE('29/05/2024', 'DD/MM/YYYY')
    GROUP BY B.COD_CONTRATO, B.DES_PESSOA, B.COD_UNIDADE
)
SELECT
    COD_CONTRATO,
    DES_PESSOA,
    COD_UNIDADE,
    CASE
        WHEN BANCO_HORAS < 0 THEN '-' || TRUNC(ABS(BANCO_HORAS)) || ':' || LPAD(ROUND(MOD(ABS(BANCO_HORAS), 1) * 60), 2, '0')
        ELSE TRUNC(BANCO_HORAS) || ':' || LPAD(ROUND(MOD(BANCO_HORAS, 1) * 60), 2, '0')
    END AS "BCO FALTAS ( GERAL )",
    DATAS_FALTAS,
    /*CASE
        WHEN TOTAL < 0 THEN '-' || TRUNC(ABS(TOTAL)) || ':' || LPAD(ROUND(MOD(ABS(TOTAL), 1) * 60), 2, '0')
        ELSE TRUNC(TOTAL) || ':' || LPAD(ROUND(MOD(TOTAL, 1) * 60), 2, '0')
    END AS COMPENSAR,*/
    CASE
        WHEN TOTAL < 0 THEN '-' || TRUNC(ABS(TOTAL)) || ':' || LPAD(ROUND(MOD(ABS(TOTAL), 1) * 60), 2, '0')
        ELSE NULL
    END AS ATRASOS,
    CASE
        WHEN TOTAL > 0 THEN TRUNC(TOTAL) || ':' || LPAD(ROUND(MOD(TOTAL, 1) * 60), 2, '0')
        ELSE NULL
    END AS EXTRAS
    
FROM
    OCORRENCIAS
GROUP BY COD_CONTRATO,
         DES_PESSOA,
         COD_UNIDADE,
         TOTAL,
         BANCO_HORAS,
         "ATRASOS DIURNO ( GERAL )",
         "EXTRAS DIURNAS ( GERAL )",
         DATAS_FALTAS
ORDER BY DES_PESSOA;



