SELECT P.TABLE_NAME, 'É PAI DE ' REL, C.TABLE_NAME
FROM USER_CONSTRAINTS P
JOIN USER_CONSTRAINTS C ON C.R_CONSTRAINT_NAME = P.CONSTRAINT_NAME
AND C.R_OWNER = P.OWNER
WHERE UPPER(P.TABLE_NAME) = UPPER('RHFP0509')
UNION ALL
SELECT C.TABLE_NAME, 'É FILHO DE ' REL, P.TABLE_NAME
FROM USER_CONSTRAINTS P
JOIN USER_CONSTRAINTS C ON C.R_CONSTRAINT_NAME = P.CONSTRAINT_NAME
AND C.R_OWNER = P.OWNER
WHERE UPPER(C.TABLE_NAME) = UPPER('MY_TABLE_NAME');

