SELECT 
    TO_CHAR(CURRENT_DATE, 'DD/MM/YYYY') AS dateShort,
    REPLACE(TO_CHAR(CURRENT_DATE, 'FMDay, DD FMMonth YYYY'), '  ', '') AS dateLong,
    TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS') AS time,
    TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI') AS timeHourMin
FROM DUAL;