GRANT CONNECT, RESOURCE, ALTER USER, CREATE ANY SYNONYM, CREATE ANY VIEW, DROP ANY VIEW, CREATE ANY TRIGGER, DROP ANY TRIGGER TO GRZ_FOLHA WITH ADMIN OPTION;

GRANT SELECT ON SYS.DBA_CONS_COLUMNS TO GRZ_FOLHA WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_CONSTRAINTS TO GRZ_FOLHA WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_TAB_COLUMNS TO GRZ_FOLHA WITH GRANT OPTION;

GRANT SELECT ON SYS.V_$SESSION TO GRZ_FOLHA WITH GRANT OPTION;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, CREATE USER, DROP USER, ALTER USER, CREATE ANY SYNONYM, DROP ANY SYNONYM, CREATE ANY VIEW, DROP ANY VIEW, CREATE ANY TRIGGER, DROP ANY TRIGGER TO SUPGR WITH ADMIN OPTION;

GRANT SELECT ON SYS.DBA_CONS_COLUMNS TO SUPGR WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_CONSTRAINTS TO SUPGR WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_TAB_COLUMNS TO SUPGR WITH GRANT OPTION;

GRANT SELECT ON SYS.V_$SESSION TO SUPGR WITH GRANT OPTION;

