--====MAPEAMENTO DE COLABORADORES DEMITIDOS QUE RECEBEM PLR====----

SELECT NULL AS COD_CONTRATO,
       NULL AS DES_PESSOA,
       NULL AS DES_FUNCAO,
       '==RECEBEM PROPORCIONAL AOS MESES TRABALHADOS==' AS DES_UNIDADE,
       NULL AS DATA_ADMISSAO,
       NULL AS DATA_DEMISSAO,
       NULL AS CAUSA_DEMISSAO,
       NULL AS ULTIMO_SALARIO
  FROM DUAL

UNION ALL

SELECT A.COD_CONTRATO,
       A.DES_PESSOA,
       A.DES_FUNCAO,
       A.DES_UNIDADE,
       A.DATA_ADMISSAO,
       A.DATA_DEMISSAO,
       A.COD_DEMISSAO || ' - ' || A.DES_DEMISSAO AS CAUSA_DEMISSAO,
       (SELECT TO_CHAR(MAX(B.VALOR_VD), 'FM999G999G990D00')
          FROM RHFP1006 B
          LEFT JOIN RHFP1005 C ON B.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
          LEFT JOIN RHFP1003 D ON B.COD_MESTRE_EVENTO = D.COD_MESTRE_EVENTO
         WHERE B.COD_CONTRATO = A.COD_CONTRATO
           AND B.COD_MESTRE_EVENTO IN
               (15623, 15683, 15757, 15837, 15911, 15987, 16052, 16130, 16198,
                16268, 16329, 16413)
           AND B.COD_VD = 1700
           AND D.DATA_REFERENCIA <= A.DATA_DEMISSAO FETCH FIRST 1 ROW ONLY) AS ULTIMO_SALARIO

  FROM V_DADOS_COLAB_AVT A
 WHERE A.STATUS = 1
   AND A.COD_EMP = '008'
   AND A.DATA_DEMISSAO BETWEEN '01/01/2023' AND '31/12/2023'
   AND A.DATA_ADMISSAO <= '01/07/2023'
   AND A.COD_CONTRATO NOT IN (6970)
   AND A.COD_DEMISSAO NOT IN (10, 13, 14, 21)
   AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
   AND A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%'

UNION ALL

  SELECT NULL AS COD_CONTRATO,
         NULL AS DES_PESSOA,
         NULL AS DES_FUNCAO,
         NULL AS DES_UNIDADE,
         NULL AS DATA_ADMISSAO,
         NULL AS DATA_DEMISSAO,
         NULL AS CAUSA_DEMISSAO,
         NULL AS ULTIMO_SALARIO
    FROM DUAL
  
  UNION ALL
  
  SELECT NULL AS COD_CONTRATO,
         NULL AS DES_PESSOA,
         NULL AS DES_FUNCAO,
         '==RECEBEM INTEGRAL AO ANO TODO==' AS DES_UNIDADE,
         NULL AS DATA_ADMISSAO,
         NULL AS DATA_DEMISSAO,
         NULL AS CAUSA_DEMISSAO,
         NULL AS ULTIMO_SALARIO
    FROM DUAL
  
  UNION ALL
  
  SELECT A.COD_CONTRATO,
         A.DES_PESSOA,
         A.DES_FUNCAO,
         A.DES_UNIDADE,
         A.DATA_ADMISSAO,
         A.DATA_DEMISSAO,
         A.COD_DEMISSAO || ' - ' || A.DES_DEMISSAO AS CAUSA_DEMISSAO,
         (SELECT TO_CHAR(MAX(B.VALOR_VD), 'FM999G999G990D00')
            FROM RHFP1006 B
            LEFT JOIN RHFP1005 C ON B.COD_MESTRE_EVENTO =
                                    C.COD_MESTRE_EVENTO
            LEFT JOIN RHFP1003 D ON B.COD_MESTRE_EVENTO =
                                    D.COD_MESTRE_EVENTO
           WHERE B.COD_CONTRATO = A.COD_CONTRATO
             AND B.COD_MESTRE_EVENTO IN
                 (15623, 15683, 15757, 15837, 15911, 15987, 16052, 16130,
                  16198, 16268, 16329, 16413)
             AND B.COD_VD = 1700
             AND D.DATA_REFERENCIA <= A.DATA_DEMISSAO FETCH FIRST 1 ROW ONLY) AS ULTIMO_SALARIO
  
    FROM V_DADOS_COLAB_AVT A
   WHERE A.STATUS = 1
     AND A.COD_EMP = '008'
     AND A.DATA_DEMISSAO >= '01/01/2024'   
     AND A.DATA_DEMISSAO <= SYSDATE
     AND A.DATA_ADMISSAO <= '01/07/2023'
     AND A.COD_CONTRATO NOT IN (6970)
     AND A.COD_DEMISSAO NOT IN (10, 13, 14, 21)
     AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
     AND A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%';