SET TERMOUT ON HEADING ON FEEDBACK ON VERIFY ON LINESIZE 2000
accept FILE prompt "ARQUIVO: "
accept TABLENAME prompt "NOME DA TABELA: "
accept OWNER prompt "NOME DO USUARIO PROPRIETARIO DA TABELA: "
accept PASSWORD_ORIG prompt "SENHA DO USUARIO PROPRIETARIO DA TABELA: " HIDE
accept HOST_STRING prompt "HOST_STRING: "
SET TERMOUT OFF HEADING OFF FEEDBACK OFF VERIFY OFF
SPOOL &&FILE

SELECT 'PROMPT CONECTANDO ...' || CHR(10) || 'CONNECT &&OWNER'||'/'||'&&PASSWORD_ORIG'||'@'||'&&HOST_STRING'
FROM DUAL;
SELECT 'PROMPT CRIANDO SINONIMOS...'
FROM DUAL;

SELECT DISTINCT 'CREATE SYNONYM "' || OWNER || '".' || '&&TABLENAME FOR &&OWNER'||'.'||'&&TABLENAME;'
FROM DBA_SYNONYMS
WHERE upper(TABLE_OWNER) = upper('&&OWNER')
and upper(OWNER) <> upper('&&OWNER')
and upper(OWNER) <> 'ORDSYS'
and upper(OWNER) <> 'SYS'
and upper(OWNER) <> 'SYSTEM'
and upper(OWNER) <> 'DBSNMP'
and upper(OWNER) <> 'PUBLIC';

SELECT 'PROMPT CONCEDENDO PRIVILEGIOS ...'
FROM DUAL;

SELECT DISTINCT 'GRANT ALL ON &&OWNER' || '.' || '&&TABLENAME TO "' || OWNER || '" WITH GRANT OPTION;'
FROM DBA_SYNONYMS
WHERE upper(TABLE_OWNER) = upper('&&OWNER')
and upper(OWNER) <> upper('&&OWNER')
and upper(OWNER) <> 'ORDSYS'
and upper(OWNER) <> 'SYS'
and upper(OWNER) <> 'SYSTEM'
and upper(OWNER) <> 'DBSNMP'
and upper(OWNER) <> 'PUBLIC';
SPOOL OFF
SET TERMOUT ON HEADING ON FEEDBACK ON VERIFY ON
@&&FILE
