PARA UTILIZAÇÃO DO E-MAIL PRINCIPAL VERIFICAR O SEGUINTE NA TABELA DIRETIVA:

 

SE NÃO EXISTIR A DIRETIVA/LINHA 8

INSERT INTO DIRETIVA (COD_DIRETIVA, NOME_DIRETIVA, VALOR_DIRETIVA)

VALUES (8, 'E-MAIL PARA ASSINATURAS DIGITAIS E ELETRONICAS DA PESSOA FISICA', 'PRINCIPAL');

 

OU

 

SE JÁ EXISTE A DIRETIVA/LINHA 8

UPDATE DIRETIVA

  SET VALOR_DIRETIVA = 'PRINCIPAL'

WHERE COD_DIRETIVA = 8; 