CREATE OR REPLACE PROCEDURE ATU_SUP_IMEDIATO_REGIONAL AS
BEGIN
  --ATUALIZA SUPERIOR IMEDIATO DOS REGIONAIS

  DECLARE
    
     CURSOR C1 IS
       SELECT OP.COD_OPERADOR
       FROM V_DADOS_PESSOA VDP,
            RHFP0300       CT,
            OPERADOR       OP
       WHERE CT.COD_CONTRATO = VDP.COD_CONTRATO
         AND OP.COD_PESSOA = CT.COD_FUNC
         AND VDP.COD_FUNCAO = 325; -- regionais
     r1 C1%ROWTYPE;
  
    --CURSOR DAS LOJAS RESPONSAVEIS POR CADA REGIONAL
    CURSOR C2 IS
      SELECT OP.COD_OPERADOR, ORG.COD_ORGANOGRAMA
        FROM V_DADOS_PESSOA VDP,
             PE0002         PE,
             RHFP0300       CT,
             OPERADOR       OP,
             RHFP0400       ORG
       WHERE PE.VALOR = VDP.cod_grupo_unidade
         AND CT.COD_CONTRATO = VDP.COD_CONTRATO
         AND OP.COD_PESSOA = CT.COD_FUNC
         AND ORG.COD_PESSOA = PE.COD_PESSOA
         AND COD_FUNCAO = 325 -- regionais
         AND PE.COD_CAMPO = 1
      -- AND PE.VALOR = '8701'
      -- AND VDP.COD_CONTRATO = 378992
       ORDER BY OP.COD_OPERADOR, ORG.COD_ORGANOGRAMA;
    r2 C2%ROWTYPE;
    
  BEGIN
    
    FOR R1 IN C1 LOOP
        DELETE FROM OPERORG WHERE COD_OPERADOR = r1.COD_OPERADOR; --SÓ IRÁ DELETAR TODOS OS REGISTROS SOMENTE UMA UNICA VEZ
        INSERT INTO OPERORG (COD_OPERADOR, COD_ORGANOGRAMA, IND_ATIVOS) VALUES (r1.COD_OPERADOR, 1777, 'N'); --INSERE O ORGANOGRAMA DOS REGIONAIS (PARA AUTOAVALIAÇÃO)
        COMMIT;
    END LOOP;
    
    FOR R2 IN C2 LOOP
      INSERT INTO OPERORG (COD_OPERADOR, COD_ORGANOGRAMA, IND_ATIVOS) VALUES (r2.COD_OPERADOR, r2.COD_ORGANOGRAMA, 'N');
      COMMIT;
    END LOOP;
  END;

END ATU_SUP_IMEDIATO_REGIONAL; 