CREATE OR REPLACE PROCEDURE NL.GRZ_FOLHA_ATUALIZA_EMAIL
IS
BEGIN

DECLARE

 CURSOR C1 IS
		SELECT FOLHA.COD_CONTRATO
		     , FOLHA.COD_PESSOA
		     , FOLHA.CPF
		     , FOLHA.COD_UNIDADE AS FILIAL
		     , NVL(PSPES.DES_EMAIL, FOLHA.DES_EMAIL) EMAIL
		FROM V_DADOS_PESSOA@GRZFOLHA FOLHA, PS_PESSOAS PSPES, FISICA@GRZFOLHA FISICA
		WHERE PSPES.COD_PESSOA = FOLHA.COD_UNIDADE
		   AND FOLHA.COD_UNIDADE NOT IN ('900', '001')
		   AND FOLHA.DES_FUNCAO LIKE '%GERENTE%'
		   AND FISICA.COD_PESSOA = FOLHA.COD_PESSOA
	    -- AND FISICA.COD_PESSOA IN (3294, 83344,89693,93108, 77992, 25435)   -- TESTE COM GERENTES
		   AND FOLHA.COD_GRUPO IN ('1','2','3','4','7'); -- 1 GRAZZIOTIN, 2 TOTTAL, 3 PORMENOS, 4 FRANCO GIORGI, 7 GZT
 r1   C1%ROWTYPE;

BEGIN

    FOR R1 IN C1 LOOP

  		UPDATE FISICA@GRZFOLHA
		  SET EMAIL = r1.EMAIL
	  	WHERE CPF = r1.CPF
		  AND COD_PESSOA = r1.COD_PESSOA;

    END LOOP;
 COMMIT;
END;

END GRZ_FOLHA_ATUALIZA_EMAIL;
