/*PROCESSO DE ATUALIZAR NRO_RECIBO E STATUS DE EVENTOS DO ESOCIAL QUE FORAM MAS DERAM ERRO NO RETORNO DO E-SOCIAL*/

--outra versão
SELECT a.*, rowid--COD_EVENTO  
FROM RHES0110 a
WHERE a.COD_ROTINA = 1461
AND a.COD_EVENTO IN (18098, 18099, 18100)
AND a.NRO_RECIBO IS NULL
ORDER BY a.COD_EVENTO


SELECT COD_EVENTO  
FROM RHES0110
WHERE COD_ROTINA = 1449
AND TAB_EVENTO = 'S-1210'
AND NRO_RECIBO IS NULL
ORDER BY COD_EVENTO


SELECT * FROM RHES1210
WHERE COD_ROTINA = 1449

UPDATE RHES0110 A
SET 
    A.COD_SITUACAO = 3,
    A.COD_RESPOSTA = 201,
    A.DESCRICAO_RESPOSTA = 'SUCESSO',
    A.NRO_RECIBO = (
        SELECT B.NRO_RECIBO
        FROM RHES0110_TB B
        WHERE B.COD_EVENTO = A.COD_EVENTO
    ),
    A.IND_ASSINADO = 'S'
WHERE A.COD_ROTINA = 1449
  AND EXISTS (
      SELECT 1
      FROM RHES0110_TB B
      WHERE B.COD_EVENTO = A.COD_EVENTO
  );
