--==PROCESSO PARA INSERIR LOJAS COM PREJUÍZO NAS VARIAVEIS LIVRES==--

SELECT * FROM RHFP1026 WHERE COD_VL = 15

/*INSERT DE EXEMPLO.
  OBS: COLUNA - COD_ARGUMENTO - DEVE SEGUIR UM SEQUENCIAL NUMÉRICO AO INSEIR*/
INSERT INTO RHFP1026 (COD_VL, COD_ARGUMENTO, VALOR_VL, ARGUMENTO_1, ARGUMENTO_2, ARGUMENTO_3) VALUES (15, 1, 1.00, '040', NULL, NULL);