/*REL GERENTES COM FÉRIAS PROGRAMADAS*/

SELECT COD_CONTRATO,
       DES_PESSOA,
       DES_FUNCAO,
       DES_UNIDADE,
       DES_REDE_LOCAL,
       DATA_INI_AFAST,
       DATA_FIM_AFAST
FROM V_DADOS_COLAB_AVT
WHERE STATUS = 0
AND (COD_TIPO = :TIPO OR :TIPO = 0)
AND (COD_UNIDADE = :FILIAL OR :FILIAL = 0)
AND (COD_REDE_LOCAL = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
AND DATA_INI_AFAST >= :DATA_INICIO
AND DATA_FIM_AFAST <= :DATA_FIM
AND COD_AFAST = 7