/*ROTINA DE INATIVAÇÃO DE OPERADORES DO DATASYS*/

CREATE OR REPLACE PROCEDURE INATIVA_OPERADORES AS
BEGIN
  UPDATE OPERADOR OP
  SET IND_INATIVO = 'S',
      DATA_INATIVACAO = SYSDATE
  WHERE OP.COD_PESSOA IS NOT NULL
    AND NVL(OP.IND_INATIVO,'N') <> 'S'
    AND EXISTS
         (SELECT CT1.COD_FUNC
          FROM RHFP0300 CT1
          WHERE CT1.COD_FUNC = OP.COD_PESSOA)
    AND NOT EXISTS
         (SELECT CT2.COD_FUNC
          FROM RHFP0300 CT2
          WHERE CT2.COD_FUNC = OP.COD_PESSOA
            AND (CT2.DATA_FIM IS NULL OR CT2.DATA_FIM >= TRUNC(SYSDATE,'DD')));
END;
