 SELECT CASE
            WHEN DISTINCT(COD_RELAT_GR) = '%RE0350D%' THEN
             ''
 FROM RHWF0405
 WHERE (COD_RELAT_GR LIKE '%RE0350D%' OR
        COD_RELAT_GR LIKE '%RE0050%' OR
        COD_RELAT_GR LIKE '%DECLRACA%')