SELECT LC.COD_CLASSE_CONT,
LC.COD_LANCAMENTO,
       LC.COD_CONTA_CONTABIL,
       CT.NOME_CONTA_CONTABIL,
       LC.TIPO_LANCAMENTO,
       LC.COD_SELECAO,
       LC.COD_CONTRAPARTIDA,
       LC.COD_HISTORICO,
       HI.HISTORICO_COMP,
       TOT.COD_TOTAL,
       TT.COD_VD,
       VD.NOME_VD
        FROM RHFP0403 CT, RHFP0404 LC,RHFP0415 HI, RHFP0405 TOT, RHFP0446 TT, RHFP1000 VD
WHERE CT.COD_CONTA_CONTABIL = LC.COD_CONTA_CONTABIL
  AND LC.COD_HISTORICO = HI.COD_HISTORICO
  AND LC.COD_CONTA_CONTABIL = HI.COD_CONTA_CONTABIL
  AND LC.COD_LANCAMENTO = TOT.COD_LANCAMENTO
  AND TOT.COD_TOTAL = TT.COD_TOTAL
  AND TT.COD_VD = VD.COD_VD
  AND LC.COD_CLASSE_CONT IN (1,2,3,4,5)
      ORDER BY LC.COD_LANCAMENTO

