SELECT PF.COD_PESSOA, 
       PF.NOME_PESSOA, 
       PF.DT_NASC, 
       TO_CHAR(PF.CPF) AS CPF, 
       A.NRO_IDENTIDADE
  FROM RHFP0200 A, PESSOA_FISICA PF
 WHERE A.COD_FUNC = PF.COD_PESSOA
   AND A.COD_FUNC = 120072;