--==SELECT RELATÓRIO PARA RELACIONAR TODOS OS COLABORADORES COM CARGO GERENCIAL DE TODAS AS EMPRESAS==--



SELECT COD_CONTRATO,
       COD_CONTRATO || ' - ' || DES_PESSOA AS COLABORADOR,
       COD_FUNCAO,
       DES_FUNCAO,
       DATA_ADMISSAO,
       EDICAO_EMP,
       'Empresa' || ' - ' || DES_EMPRESA AS EMPRESA,
       COD_UNIDADE,
       'Filial/Setor' || ' - ' || DES_UNIDADE AS LOCAL,
       COD_AFAST,
       DES_AFAST,
       CASE
          WHEN DATA_INI_AFAST IS NOT NULL AND DATA_FIM_AFAST IS NOT NULL THEN
           'De ' || DATA_INI_AFAST   || ' até ' ||   DATA_FIM_AFAST
          ELSE
           'Em Atividade'
       END AS AFASTAMENTO      
FROM V_DADOS_COLAB_AVT
WHERE STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND (DES_FUNCAO LIKE '%AUDITOR%' OR
     DES_FUNCAO LIKE '%COMPRADOR%' OR
     DES_FUNCAO LIKE '%GERENTE%' OR
     DES_FUNCAO LIKE '%SUPERVISOR%' OR
     DES_FUNCAO LIKE '%DIRETOR%')
ORDER BY EDICAO_EMP ASC, COD_UNIDADE ASC, DES_PESSOA DESC