SELECT CT.COD_CONTRATO
FROM RHFP0306 CA,
     RHFP0312 CS,
     RHFP0300 CT
WHERE CT.COD_CONTRATO = SEL.COD_CONTRATO
  AND CT.DATA_INICIO <= :DATA_REFERENCIA
  AND (CT.DATA_FIM IS NULL OR (CT.DATA_FIM IS NOT NULL AND :DATA_REFERENCIA <= CT.DATA_FIM))
  AND CT.COD_CONTRATO <> 4
  AND CA.COD_CONTRATO(+) = CT.COD_CONTRATO
  AND :DATA_REFERENCIA BETWEEN CA.DATA_INICIO(+) AND CA.DATA_FIM(+)
  AND NVL(CA.COD_CAUSA_AFAST,0) IN (0,6,7)
  AND CS.COD_CONTRATO = CT.COD_CONTRATO
  AND :DATA_REFERENCIA BETWEEN CS.DATA_INICIO AND CS.DATA_FIM
  AND CS.COD_SINDICATO in (4,99)