SELECT DISTINCT C.EDICAO_NIVEL3,
                D.NOME_ORGANOGRAMA,
                COUNT(DISTINCT A.COD_CONTRATO) AS QTD_CONTRATOS,
                G.COD_CUSTO_N3,
                H.COD_EXAME,
                I.NOME_EXAME,
                COUNT(DISTINCT H.COD_CLASSE_EXAME) AS QTD_CLASSE_EXAME,
                J.NOME_CLASSE_EXAME AS NATUREZA,
                COUNT(H.DATA_EXAME) AS REALIZADOS
  FROM RHFP0310 A,
       RHFP0300 B,
       RHFP0401 C,
       RHFP0400 D,
       RHFP0340 F,
       RHFP0402 G,
       RHMS0220 H,
       RHMS0150 I,
       RHMS0340 J
 WHERE B.COD_CONTRATO = A.COD_CONTRATO
      --AND C.EDICAO_NIVEL3 BETWEEN '004' AND '7999'
   AND (B.DATA_FIM > SYSDATE OR B.DATA_FIM IS NULL)
   AND (A.DATA_FIM > SYSDATE OR A.DATA_FIM IS NULL)
   AND (F.DATA_FIM > SYSDATE OR F.DATA_FIM IS NULL)
   --AND B.COD_CONTRATO = J.COD_CONTRATO(+)
   --AND J.DATA_INICIO(+) <= SYSDATE
   --AND J.DATA_FIM(+) >= SYSDATE
   AND G.COD_CUSTO_N3 = '1200'
   AND C.COD_ORGANOGRAMA = A.COD_ORGANOGRAMA
   AND D.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
   AND D.COD_CUSTO_CONTABIL = G.COD_CUSTO_CONTABIL
   AND A.COD_CONTRATO = H.COD_CONTRATO
   AND H.COD_EXAME = I.COD_EXAME
   AND H.COD_CLASSE_EXAME = J.COD_CLASSE_EXAME
   AND F.COD_CONTRATO = B.COD_CONTRATO
 GROUP BY C.EDICAO_NIVEL3,
          D.NOME_ORGANOGRAMA,
          G.COD_CUSTO_N3,
          H.COD_EXAME,
          I.NOME_EXAME,
          H.COD_CLASSE_EXAME,
          J.NOME_CLASSE_EXAME
 ORDER BY 1 ASC





SELECT DISTINCT C.EDICAO_NIVEL3,
                D.NOME_ORGANOGRAMA,
                COUNT(DISTINCT A.COD_CONTRATO) AS QTD_CONTRATOS,
                G.COD_CUSTO_N3,
                H.COD_EXAME,
                I.NOME_EXAME,
                COUNT(H.COD_CLASSE_EXAME) AS QTD_CLASSE_EXAME,
                J.NOME_CLASSE_EXAME AS NATUREZA,
                COUNT(H.DATA_EXAME) AS REALIZADOS
  FROM RHFP0310 A,
       RHFP0300 B,
       RHFP0401 C,
       RHFP0400 D,
       RHFP0340 F,
       RHFP0402 G,
       RHMS0220 H,
       RHMS0150 I,
       RHMS0340 J
 WHERE B.COD_CONTRATO = A.COD_CONTRATO
   AND (B.DATA_FIM > SYSDATE OR B.DATA_FIM IS NULL)
   AND (A.DATA_FIM > SYSDATE OR A.DATA_FIM IS NULL)
   AND (F.DATA_FIM > SYSDATE OR F.DATA_FIM IS NULL)
   AND H.DATA_EXAME >= '01/01/2022'
   AND H.DATA_EXAME <= '31/12/2022'
   AND A.DATA_FIM = '31/12/2999'
   AND G.COD_CUSTO_N3 = '1200'
   AND C.COD_ORGANOGRAMA = A.COD_ORGANOGRAMA
   AND D.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
   AND D.COD_CUSTO_CONTABIL = G.COD_CUSTO_CONTABIL
   AND A.COD_CONTRATO = H.COD_CONTRATO
   AND H.COD_EXAME = I.COD_EXAME
   AND H.COD_CLASSE_EXAME = J.COD_CLASSE_EXAME
   AND F.COD_CONTRATO = B.COD_CONTRATO
 GROUP BY C.EDICAO_NIVEL3,
          D.NOME_ORGANOGRAMA,
          G.COD_CUSTO_N3,
          H.COD_EXAME,
          I.NOME_EXAME,
          H.COD_CLASSE_EXAME,
          J.NOME_CLASSE_EXAME,
          H.DATA_EXAME
 ORDER BY 1 ASC
 
SELECT * FROM RHMS0340

SELECT DISTINCT C.EDICAO_NIVEL3,
                D.NOME_ORGANOGRAMA,
                COUNT(DISTINCT A.COD_CONTRATO) AS QTD_CONTRATOS,
                COUNT(DISTINCT F.COD_EXAME) QTD_EXAMES
                --, COUNT(DISTINCT H.COD_CLASSE_EXAME) QTD_CLASSES
                 (SELECT G.NOME_EXAME, H.NOME_CLASSE_EXAME
                    FROM RHMS0220 F, RHMS0150 G, RHMS0340 H
                   WHERE G.COD_EXAME = F.COD_EXAME
                     AND H.COD_CLASSE_EXAME = F.COD_CLASSE_EXAME) AS EXAMES
  FROM RHFP0310 A,
       RHFP0300 B,
       RHFP0401 C,
       RHFP0400 D,
       RHFP0402 E,
       RHMS0220 F,
       RHMS0150 G,
       RHMS0340 H
 WHERE B.COD_CONTRATO = A.COD_CONTRATO
   AND F.COD_CONTRATO = B.COD_CONTRATO
      --AND  B.COD_FUNC = G.COD_FUNC
   AND C.EDICAO_NIVEL3 BETWEEN '004' AND '7999'
   AND (B.DATA_FIM > SYSDATE OR B.DATA_FIM IS NULL)
   AND (A.DATA_FIM > SYSDATE OR A.DATA_FIM IS NULL)
   AND F.DATA_EXAME >= '01/01/2022'
   AND F.DATA_EXAME <= '31/12/2022'
   AND C.COD_ORGANOGRAMA = A.COD_ORGANOGRAMA
   AND C.COD_ORGANOGRAMA = D.COD_ORGANOGRAMA
   AND E.COD_CUSTO_CONTABIL = D.COD_CUSTO_CONTABIL
   AND F.COD_CONTRATO = B.COD_CONTRATO
 GROUP BY C.EDICAO_NIVEL3, D.NOME_ORGANOGRAMA, H.COD_CLASSE_EXAME
 ORDER BY 1 ASC

SELECT G.COD_EXAME, G.NOME_EXAME
  FROM RHMS0150 G;

 
SELECT H.COD_CLASSE_EXAME, H.NOME_CLASSE_EXAME
  FROM RHMS0340 H;
