SELECT R200.COD_REQUISICAO,
       R200.NOME_REQUISICAO,
       R200.COD_ORGANOGRAMA,
       R400.NOME_ORGANOGRAMA,
       R400.COD_NIVEL_ORG,
       R200.COD_CLH,
       R500.NOME_CLH,
       TRUNC(R200.DATA_EMISSAO) AS DATA_EMISSAO,
       (SELECT NVL(MAX(COD_PROCESSO_REQ), 0)
          FROM RHWF0010) AS IND_SOLICITA_APROVACAO,
       (SELECT NVL(MAX(COD_PROCESSO), 0)
          FROM RHFP0323
         WHERE COD_MOTIVO = R200.COD_MOTIVO) AS COD_PROC_MOTIVO,
       NVL((SELECT COD_REQUISICAO AS COD_REQUISICAO
              FROM RHWF0250
             WHERE COD_REQUISICAO = R200.COD_REQUISICAO
             GROUP BY COD_REQUISICAO), 0) AS INDICADOR,
       NVL((SELECT SITUACAO AS SITUACAO
              FROM RHWF0250
             WHERE COD_REQUISICAO = R200.COD_REQUISICAO
             GROUP BY SITUACAO), NULL) AS SITUACAO
  FROM RHRS0200 R200,
       RHFP0400 R400,
       RHFP0500 R500
 WHERE R400.COD_ORGANOGRAMA = R200.COD_ORGANOGRAMA
   AND R500.COD_CLH(+) = R200.COD_CLH
   AND R200.COD_OPERADOR = 'F338702'
 ORDER BY R200.COD_REQUISICAO DESC