-- SELECT PARA PUXAR RELAÇÃO DE PERFIS DOS COLABORADORES QUE UTILIZAM O SISTEMA

SELECT C.COD_CONTRATO AS CONTRATO
     , B.COD_OPERADOR AS OPERADOR
     , A.NOME_PERFIL
     , A.COD_PERFIL AS PERFIL
     , UPPER (C.DES_PESSOA) AS NOME_COLABORADOR
     , C.NOME_ORGANOGRAMA AS ORGANOGRAMA
     , C.COD_UNIDADE AS UNIDADE
     , C.DES_GRUPO AS NOME_GRUPO
     , B.IND_INATIVO AS INATIVAÇÃO
     , B.TIPO
FROM RHUS0010 A
   , OPERADOR B
   , V_DADOS_PESSOA C
WHERE A.COD_PERFIL = B.COD_PERFIL
AND B.COD_PESSOA = C.COD_PESSOA
ORDER BY A.COD_PERFIL ASC;