SELECT OP.COD_OPERADOR, ORG.COD_ORGANOGRAMA
FROM V_DADOS_PESSOA VDP, PE0002 PE, RHFP0300 CT, OPERADOR OP, RHFP0400 ORG
WHERE PE.VALOR = VDP.cod_grupo_unidade
AND CT.COD_CONTRATO = VDP.COD_CONTRATO
AND OP.COD_PESSOA = CT.COD_FUNC
AND ORG.COD_PESSOA = PE.COD_PESSOA
AND COD_FUNCAO = 325 -- regionais
AND PE.COD_CAMPO = 1
--AND PE.VALOR = '8701'
--AND VDP.COD_CONTRATO = 378992;


este é o select correto  13031980