/*SQL PARA INSERIR UMA NOVA NACIONALIDADE*/

SELECT * FROM RHFP0107

INSERT INTO RHFP0107(COD_NACIONALIDADE, NOME_NACIONALIDADE, COD_OUTRO_SIST, COD_ESOCIAL, COD_XML_DEST)
       VALUES(145, 'Camaronês', NULL, 145, 50)


/*SOMENTE ATUALIZADO PARA SEGUIR O PADRÃO*/    
UPDATE RHFP0107
SET COD_NACIONALIDADE = 63
WHERE COD_NACIONALIDADE = 145