SELECT A.COD_OPERADOR,
       C.NOME_PESSOA,
       SUBSTR(RHYF0205(A.SENHA), 1, 30) AS SENHA,
       B.DATA_CRIACAO,
       TO_DATE(B.DATA_CRIACAO, 'DD/MM/YY') + 70 AS DTA_VENCIMENTO,
       A.BLOQUEADO
  FROM OPERADOR A
  JOIN PESSOA C ON A.COD_PESSOA = C.COD_PESSOA
  JOIN OPSENHA B ON B.COD_OPERADOR = A.COD_OPERADOR
  JOIN (SELECT COD_OPERADOR, MAX(DATA_CRIACAO) AS MAX_DATA
          FROM OPSENHA
         GROUP BY COD_OPERADOR) B1 ON B.COD_OPERADOR = B1.COD_OPERADOR
                                  AND B.DATA_CRIACAO = B1.MAX_DATA
 WHERE A.COD_OPERADOR = 'F385887'