/*NOVO TURNOVER GERENCIAL- SQL OFICIAL DO RELATÓRIO GERENCIAL

SEL0065 = REL0065

*/


WITH
MONTHS AS (
/*VERSÃO PARA USAR NO PL/SQL*/
/*SELECT ADD_MONTHS(TO_DATE('01/07/2025', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
       LAST_DAY(ADD_MONTHS(TO_DATE('01/07/2025', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END,

       TO_CHAR(ADD_MONTHS(TO_DATE('01/07/2025', 'DD/MM/YYYY'), LEVEL - 1),
               'MM/YYYY') AS MES_ANO,
       INITCAP(TRIM(TO_CHAR(ADD_MONTHS(TO_DATE('01/07/2025', 'DD/MM/YYYY'),
                                       LEVEL - 1),
                            'Month'))) || '/' ||
       TO_CHAR(ADD_MONTHS(TO_DATE('01/07/2025', 'DD/MM/YYYY'), LEVEL - 1),
               'YYYY') AS MES_ANO_EXTENSO
  FROM DUAL
CONNECT BY LEVEL <=
           MONTHS_BETWEEN(TO_DATE('31/07/2025', 'DD/MM/YYYY'),
                          TO_DATE('01/07/2025', 'DD/MM/YYYY')) + 1*/



/*OFICIAL*/
SELECT :DATA_INICIO AS MONTH_START,
       LAST_DAY(:DATA_FIM) AS MONTH_END,

       --ex: 07/2025  (se for um único mês)  ou  07/2025 - 08/2025 (se cruzar mês)
       CASE
         WHEN TRUNC(:DATA_INICIO, 'MM') = TRUNC(:DATA_FIM, 'MM') THEN
          TO_CHAR(:DATA_INICIO, 'MM/YYYY')
         ELSE
          TO_CHAR(:DATA_INICIO, 'MM/YYYY') || ' - ' ||
          TO_CHAR(:DATA_FIM, 'MM/YYYY')
       END AS MES_ANO,

       --ex: Julho/2025  (único mês)  ou  Julho/2025 - Agosto/2025 (intervalo)
       CASE
         WHEN TRUNC(:DATA_INICIO, 'MM') = TRUNC(:DATA_FIM, 'MM') THEN
          INITCAP(TO_CHAR(:DATA_INICIO,
                          'FMMonth',
                          'NLS_DATE_LANGUAGE=Portuguese')) || '/' ||
          TO_CHAR(:DATA_INICIO, 'YYYY')
         ELSE
          INITCAP(TO_CHAR(:DATA_INICIO,
                          'FMMonth',
                          'NLS_DATE_LANGUAGE=Portuguese')) || '/' ||
          TO_CHAR(:DATA_INICIO, 'YYYY') || ' - ' ||
          INITCAP(TO_CHAR(:DATA_FIM,
                          'FMMonth',
                          'NLS_DATE_LANGUAGE=Portuguese')) || '/' ||
          TO_CHAR(:DATA_FIM, 'YYYY')
       END AS MES_ANO_EXTENSO

  FROM DUAL

),


CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.SEXO,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
  FROM V_DADOS_CONTRATO_AVT    CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_HIST_HORAS_COLAB_AVT HR,
       VH_CARGO_CONTRATO_AVT   FN
 WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
   AND CT.COD_CONTRATO = HR.COD_CONTRATO
   AND CT.COD_CONTRATO = FN.COD_CONTRATO
   AND (CT.DATA_ADMISSAO <= :DATA_FIM)
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= :DATA_INICIO)
   /*AND (CT.DATA_ADMISSAO <= TO_DATE('31/07/2025','DD/MM/YYYY'))
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= TO_DATE('01/07/2025','DD/MM/YYYY'))*/
   /*AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= '01/07/2025')*/
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :DATA_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
   AND ORG.COD_EMP = 8
   --AND ORG.COD_TIPO = 1
   AND ORG.EDICAO_ORG_4 IS NOT NULL
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   --AND ORG.COD_UNIDADE = 004
 ORDER BY CT.COD_CONTRATO
),

STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_ORGANOGRAMA,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST,
       AF.DATA_INICIO AS DATA_INI_AFAST,
       AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND ((:DATA_FIM BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= :DATA_FIM AND CT.DATA_FIM IS NULL))
   AND :DATA_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   AND ORG.COD_EMP = 8
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   --AND ORG.COD_TIPO = 1
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608) --657 essa ainda irá inaugurar em agosto
),

/*uso para testes*/
/*SELECT A.*
FROM CONTRATOS A

SELECT DISTINCT COD_CONTRATO FROM V_DADOS_COLAB_AVT
WHERE (DATA_DEMISSAO IS NULL OR
       DATA_DEMISSAO >= :DATA_FIM)
AND COD_EMP = 8
AND COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
ORDER BY COD_CONTRATO*/


EFETIVO_INICIAL_UNI AS (
    SELECT CTR.COD_ORGANOGRAMA,
           CTR.COD_UNIDADE,
           CTR.COD_REDE,
           CTR.COD_EMP,
           CTR.COD_TIPO,
           M.MONTH_START,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
      FROM CONTRATOS CTR
     CROSS JOIN MONTHS M
     WHERE ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')

     GROUP BY CTR.COD_ORGANOGRAMA,
              CTR.COD_UNIDADE,
              CTR.COD_REDE,
              CTR.COD_EMP,
              M.MONTH_START,
              CTR.COD_TIPO
),
EFETIVO_FINAL_UNI AS (
    SELECT CTR.COD_ORGANOGRAMA,
           CTR.COD_UNIDADE,
           CTR.COD_REDE,
           CTR.COD_EMP,
           CTR.COD_TIPO,
           M.MONTH_END,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
      FROM CONTRATOS CTR
     CROSS JOIN MONTHS M
     WHERE LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
     GROUP BY CTR.COD_ORGANOGRAMA,
              CTR.COD_UNIDADE,
              CTR.COD_REDE,
              CTR.COD_EMP,
              M.MONTH_END,
              CTR.COD_TIPO
),


DATAMETRICS_UNI AS (
SELECT A.COD_ORGANOGRAMA,
       A.COD_UNIDADE,
       A.DES_UNIDADE,
       A.COD_REDE,
       A.COD_EMP,
       A.COD_TIPO,
       M.MONTH_START,
       M.MONTH_END,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN
                A.COD_CONTRATO
             END) AS ATIVOS_ATUAIS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO <= M.MONTH_END AND
                   (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN
                A.COD_CONTRATO
             END) AS ATIVOS_PERIODO,

       COUNT(DISTINCT CASE
               WHEN B.DATA_INI_AFAST <= M.MONTH_END AND
                   (B.DATA_FIM_AFAST IS NULL OR B.DATA_FIM_AFAST >= M.MONTH_START) AND
                    /*B.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND*/
                    B.STATUS_AFAST <> 7 THEN
                A.COD_CONTRATO
             END) AS AFAST_PERIODO,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS ADMITIDOS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS DEMITIDOS

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
 CROSS JOIN MONTHS M
 WHERE (UPPER(A.DES_FUNCAO) LIKE '%GERENTE%' OR
        UPPER(A.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
        UPPER(A.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY A.COD_ORGANOGRAMA,
          A.COD_UNIDADE,
          A.DES_UNIDADE,
          A.COD_REDE,
          A.COD_EMP,
          A.COD_TIPO,
          M.MONTH_START,
          M.MONTH_END
),

TURNOVER_UNI AS (
SELECT A.COD_ORGANOGRAMA,
       A.COD_UNIDADE,
       A.DES_UNIDADE,
       A.COD_REDE,
       A.DES_REDE,
       A.COD_EMP,
       A.COD_TIPO,
       DM.ATIVOS_ATUAIS,
       DM.ATIVOS_PERIODO,
       DM.AFAST_PERIODO,
       DM.ADMITIDOS,
       DM.DEMITIDOS,
       EI.EFETIVO_INICIAL,
       EF.EFETIVO_FINAL,
       (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DM.DEMITIDOS * 100) /
                ((EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER
  FROM (SELECT DISTINCT COD_ORGANOGRAMA,
                        COD_UNIDADE,
                        DES_UNIDADE,
                        COD_REDE,
                        DES_REDE,
                        COD_EMP,
                        COD_TIPO
          FROM CONTRATOS) A
   LEFT JOIN EFETIVO_INICIAL_UNI EI ON A.COD_ORGANOGRAMA =
                                      EI.COD_ORGANOGRAMA
   LEFT JOIN EFETIVO_FINAL_UNI EF ON A.COD_ORGANOGRAMA = EF.COD_ORGANOGRAMA
  INNER JOIN DATAMETRICS_UNI DM ON A.COD_ORGANOGRAMA = DM.COD_ORGANOGRAMA
                               AND (NVL(DM.ATIVOS_PERIODO, 0) > 0 OR
                                    NVL(DM.ADMITIDOS, 0) > 0 OR
                                    NVL(DM.DEMITIDOS, 0) > 0 OR
                                    NVL(DM.ATIVOS_ATUAIS, 0) > 0 -- opcional, se quiser exigir “ativo hoje”
                                   )
  WHERE (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (A.COD_REDE = :REDE OR :REDE = 0)
    AND (A.COD_TIPO = :TIPO OR :TIPO = 0)

),


/*================================*/

/*RELAÇÃO POR REDES*/

EFETIVO_INICIAL_RD AS (
    SELECT CTR.COD_REDE,
           CTR.COD_EMP,
           CTR.COD_TIPO,
           M.MONTH_START,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
      FROM CONTRATOS CTR
     CROSS JOIN MONTHS M
     WHERE CTR.COD_TIPO = 1
       AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
     GROUP BY CTR.COD_REDE,
              CTR.COD_EMP,
              M.MONTH_START,
              CTR.COD_TIPO
),
EFETIVO_FINAL_RD AS (
    SELECT CTR.COD_REDE,
           CTR.COD_EMP,
           CTR.COD_TIPO,
           M.MONTH_END,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
      FROM CONTRATOS CTR
     CROSS JOIN MONTHS M
     WHERE CTR.COD_TIPO = 1
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
     GROUP BY CTR.COD_REDE,
              CTR.COD_EMP,
              M.MONTH_END,
              CTR.COD_TIPO
),


DATAMETRICS_RD AS (
SELECT A.COD_REDE,
       A.COD_EMP,
       A.COD_TIPO,
       M.MONTH_START,
       M.MONTH_END,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN
                A.COD_CONTRATO
             END) AS ATIVOS_ATUAIS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO <= M.MONTH_END AND
                   (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN
                A.COD_CONTRATO
             END) AS ATIVOS_PERIODO,

       COUNT(DISTINCT CASE
               WHEN B.DATA_INI_AFAST <= M.MONTH_END AND
                   (B.DATA_FIM_AFAST IS NULL OR B.DATA_FIM_AFAST >= M.MONTH_START) AND
                    /*B.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND*/
                    B.STATUS_AFAST <> 7 THEN
                A.COD_CONTRATO
             END) AS AFAST_PERIODO,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS ADMITIDOS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS DEMITIDOS

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
 CROSS JOIN MONTHS M
 WHERE A.COD_TIPO = 1
   AND (UPPER(A.DES_FUNCAO) LIKE '%GERENTE%' OR
        UPPER(A.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
        UPPER(A.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY A.COD_REDE,
          A.COD_EMP,
          A.COD_TIPO,
          M.MONTH_START,
          M.MONTH_END
),

TURNOVER_RD AS (
SELECT A.COD_REDE AS REDE,
       A.DES_REDE,
       A.COD_EMP,
       A.COD_TIPO AS TIPO,
       DM.ATIVOS_ATUAIS,
       DM.ATIVOS_PERIODO,
       DM.AFAST_PERIODO,
       DM.ADMITIDOS,
       DM.DEMITIDOS,
       EI.EFETIVO_INICIAL,
       EF.EFETIVO_FINAL,
       (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DM.DEMITIDOS * 100) /
                ((EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER
  FROM (SELECT DISTINCT COD_REDE,
                        DES_REDE,
                        COD_EMP,
                        COD_TIPO
          FROM CONTRATOS
          WHERE COD_TIPO = 1) A
  LEFT JOIN EFETIVO_INICIAL_RD EI
         ON A.COD_REDE = EI.COD_REDE AND A.COD_TIPO = EI.COD_TIPO AND A.COD_EMP = EI.COD_EMP
  LEFT JOIN EFETIVO_FINAL_RD EF
         ON A.COD_REDE = EF.COD_REDE AND A.COD_TIPO = EF.COD_TIPO AND A.COD_EMP = EF.COD_EMP
  LEFT JOIN DATAMETRICS_RD DM
         ON A.COD_REDE = DM.COD_REDE AND A.COD_TIPO = DM.COD_TIPO AND A.COD_EMP = DM.COD_EMP
  /*WHERE (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (A.COD_REDE = :REDE OR :REDE = 0)
    AND (A.COD_TIPO = :TIPO OR :TIPO = 0)*/

),


/*================================*/

/*RELAÇÃO GERAL DAS LOJAS*/

EFETIVO_INICIAL_LJ AS (
    SELECT CTR.COD_TIPO,
           M.MONTH_START,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
      FROM CONTRATOS CTR
     CROSS JOIN MONTHS M
     WHERE CTR.COD_TIPO = 1
       AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
     GROUP BY CTR.COD_TIPO,
              M.MONTH_START

),
EFETIVO_FINAL_LJ AS (
    SELECT CTR.COD_TIPO,
           M.MONTH_END,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
      FROM CONTRATOS CTR
     CROSS JOIN MONTHS M
     WHERE CTR.COD_TIPO = 1
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
     GROUP BY CTR.COD_TIPO,
              M.MONTH_END

),


DATAMETRICS_LJ AS (
SELECT A.COD_TIPO,
       M.MONTH_START,
       M.MONTH_END,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN
                A.COD_CONTRATO
             END) AS ATIVOS_ATUAIS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO <= M.MONTH_END AND
                   (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN
                A.COD_CONTRATO
             END) AS ATIVOS_PERIODO,

       COUNT(DISTINCT CASE
               WHEN B.DATA_INI_AFAST <= M.MONTH_END AND
                   (B.DATA_FIM_AFAST IS NULL OR B.DATA_FIM_AFAST >= M.MONTH_START) AND
                    /*B.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND*/
                    B.STATUS_AFAST <> 7 THEN
                A.COD_CONTRATO
             END) AS AFAST_PERIODO,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS ADMITIDOS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS DEMITIDOS

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
 CROSS JOIN MONTHS M
 WHERE A.COD_TIPO = 1
  AND (UPPER(A.DES_FUNCAO) LIKE '%GERENTE%' OR
        UPPER(A.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
        UPPER(A.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY A.COD_TIPO,
          M.MONTH_START,
          M.MONTH_END
),

TURNOVER_LJ AS (
SELECT A.COD_TIPO AS TIPO,
       A.DES_TIPO,
       DM.ATIVOS_ATUAIS,
       DM.ATIVOS_PERIODO,
       DM.AFAST_PERIODO,
       DM.ADMITIDOS,
       DM.DEMITIDOS,
       EI.EFETIVO_INICIAL,
       EF.EFETIVO_FINAL,
       (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DM.DEMITIDOS * 100) /
                ((EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER

  FROM (SELECT DISTINCT COD_TIPO,
                        DES_TIPO
          FROM CONTRATOS
          WHERE COD_TIPO = 1) A
  LEFT JOIN EFETIVO_INICIAL_LJ EI
         ON A.COD_TIPO = EI.COD_TIPO
  LEFT JOIN EFETIVO_FINAL_LJ EF
         ON A.COD_TIPO = EF.COD_TIPO
  LEFT JOIN DATAMETRICS_LJ DM
         ON A.COD_TIPO = DM.COD_TIPO
  /*WHERE A.COD_TIPO = 1
    AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (A.COD_REDE = :REDE OR :REDE = 0)
    AND (A.COD_TIPO = :TIPO OR :TIPO = 0)*/


),


/*================================*/

/*RELAÇÃO POR ADM/CD*/

EFETIVO_INICIAL_AC AS (
SELECT CTR.COD_REDE,
       CTR.COD_EMP,
       CTR.COD_TIPO,
       M.MONTH_START,
       COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
  FROM CONTRATOS CTR
 CROSS JOIN MONTHS M
 WHERE CTR.COD_TIPO IN (2, 3)
   AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
       CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
   AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
       CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
   AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
       UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
       UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY CTR.COD_REDE, CTR.COD_EMP, M.MONTH_START, CTR.COD_TIPO

),

EFETIVO_FINAL_AC AS (
SELECT CTR.COD_REDE,
       CTR.COD_EMP,
       CTR.COD_TIPO,
       M.MONTH_END,
       COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
  FROM CONTRATOS CTR
 CROSS JOIN MONTHS M
 WHERE CTR.COD_TIPO IN (2, 3)
   AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
       CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
   AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
       CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
   AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
       UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
       UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY CTR.COD_REDE, CTR.COD_EMP, M.MONTH_END, CTR.COD_TIPO

),


DATAMETRICS_AC AS (
SELECT A.COD_REDE,
       A.COD_EMP,
       A.COD_TIPO,
       M.MONTH_START,
       M.MONTH_END,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN
                A.COD_CONTRATO
             END) AS ATIVOS_ATUAIS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO <= M.MONTH_END AND
                    (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN
                A.COD_CONTRATO
             END) AS ATIVOS_PERIODO,

       COUNT(DISTINCT CASE
               WHEN B.DATA_INI_AFAST <= M.MONTH_END AND
                    (B.DATA_FIM_AFAST IS NULL OR B.DATA_FIM_AFAST >= M.MONTH_START) AND
                    /*B.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND*/
                    B.STATUS_AFAST <> 7 THEN
                A.COD_CONTRATO
             END) AS AFAST_PERIODO,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS ADMITIDOS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS DEMITIDOS

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
 CROSS JOIN MONTHS M
 WHERE A.COD_TIPO IN (2, 3)
   AND (UPPER(A.DES_FUNCAO) LIKE '%GERENTE%' OR
       UPPER(A.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
       UPPER(A.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY A.COD_REDE, A.COD_EMP, A.COD_TIPO, M.MONTH_START, M.MONTH_END

),

TURNOVER_AC AS (
SELECT A.COD_REDE AS REDE,
       A.DES_REDE,
       A.COD_EMP,
       A.COD_TIPO AS TIPO,
       DM.ATIVOS_ATUAIS,
       DM.ATIVOS_PERIODO,
       DM.AFAST_PERIODO,
       DM.ADMITIDOS,
       DM.DEMITIDOS,
       EI.EFETIVO_INICIAL,
       EF.EFETIVO_FINAL,
       (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DM.DEMITIDOS * 100) /
                ((EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER
  FROM (SELECT DISTINCT COD_REDE, DES_REDE, COD_EMP, COD_TIPO
          FROM CONTRATOS
         WHERE COD_TIPO IN (2, 3)) A
  LEFT JOIN EFETIVO_INICIAL_AC EI ON A.COD_REDE = EI.COD_REDE
                                 AND A.COD_TIPO = EI.COD_TIPO
                                 AND A.COD_EMP = EI.COD_EMP
  LEFT JOIN EFETIVO_FINAL_AC EF ON A.COD_REDE = EF.COD_REDE
                               AND A.COD_TIPO = EF.COD_TIPO
                               AND A.COD_EMP = EF.COD_EMP
  LEFT JOIN DATAMETRICS_AC DM ON A.COD_REDE = DM.COD_REDE
                             AND A.COD_TIPO = DM.COD_TIPO
                             AND A.COD_EMP = DM.COD_EMP
  /*WHERE (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (A.COD_REDE = :REDE OR :REDE = 0)
    AND (A.COD_TIPO = :TIPO OR :TIPO = 0)*/

),


/*================================*/

/*RELAÇÃO GERAL CENTRO ADMINISTRATIVO (ADM+CD)*/

EFETIVO_INICIAL_CA AS (
SELECT CTR.COD_EMP,
       M.MONTH_START,
       COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
  FROM CONTRATOS CTR
 CROSS JOIN MONTHS M
 WHERE CTR.COD_TIPO IN (2, 3)
   AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
       CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
   AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
       CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
   AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
       UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
       UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY CTR.COD_EMP, M.MONTH_START

),

EFETIVO_FINAL_CA AS (
SELECT CTR.COD_EMP,
       M.MONTH_END,
       COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
  FROM CONTRATOS CTR
 CROSS JOIN MONTHS M
 WHERE CTR.COD_TIPO IN (2, 3)
   AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
       CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
   AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
       CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
   AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
       UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
       UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY CTR.COD_EMP, M.MONTH_END

),


DATAMETRICS_CA AS (
SELECT A.COD_EMP,
       M.MONTH_START,
       M.MONTH_END,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN
                A.COD_CONTRATO
             END) AS ATIVOS_ATUAIS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO <= M.MONTH_END AND
                    (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN
                A.COD_CONTRATO
             END) AS ATIVOS_PERIODO,

       COUNT(DISTINCT CASE
               WHEN B.DATA_INI_AFAST <= M.MONTH_END AND
                    (B.DATA_FIM_AFAST IS NULL OR B.DATA_FIM_AFAST >= M.MONTH_START) AND
                    /*B.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND*/
                    B.STATUS_AFAST <> 7 THEN
                A.COD_CONTRATO
             END) AS AFAST_PERIODO,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS ADMITIDOS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS DEMITIDOS

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
 CROSS JOIN MONTHS M
 WHERE A.COD_TIPO IN (2, 3)
   AND (UPPER(A.DES_FUNCAO) LIKE '%GERENTE%' OR
       UPPER(A.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
       UPPER(A.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY A.COD_EMP, M.MONTH_START, M.MONTH_END

),

TURNOVER_CA AS (
SELECT A.COD_EMP,
       '2 E 3' AS TIPO,
       'ADM E CD' DES_TIPO,
       DM.ATIVOS_ATUAIS,
       DM.ATIVOS_PERIODO,
       DM.AFAST_PERIODO,
       DM.ADMITIDOS,
       DM.DEMITIDOS,
       EI.EFETIVO_INICIAL,
       EF.EFETIVO_FINAL,
       (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DM.DEMITIDOS * 100) /
                ((EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER

  FROM (SELECT DISTINCT COD_EMP FROM CONTRATOS WHERE COD_TIPO IN (2, 3)) A
  LEFT JOIN EFETIVO_INICIAL_CA EI ON A.COD_EMP = EI.COD_EMP
  LEFT JOIN EFETIVO_FINAL_CA EF ON A.COD_EMP = EF.COD_EMP
  LEFT JOIN DATAMETRICS_CA DM ON A.COD_EMP = DM.COD_EMP
  --WHERE A.COD_TIPO IN (2,3)
    /*AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (A.COD_REDE = :REDE OR :REDE = 0)
    AND (A.COD_TIPO = :TIPO OR :TIPO = 0)*/

),


/*================================*/

/*RELAÇÃO GERAL DA COMPANHIA*/

EFETIVO_INICIAL_EMP AS (
    SELECT CTR.COD_EMP,
           M.MONTH_START,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
      FROM CONTRATOS CTR
     CROSS JOIN MONTHS M
     WHERE ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
     GROUP BY CTR.COD_EMP,
              M.MONTH_START

),
EFETIVO_FINAL_EMP AS (
    SELECT CTR.COD_EMP,
           M.MONTH_END,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
      FROM CONTRATOS CTR
     CROSS JOIN MONTHS M
     WHERE LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')
     GROUP BY CTR.COD_EMP,
              M.MONTH_END

),


DATAMETRICS_EMP AS (
SELECT A.COD_EMP,
       M.MONTH_START,
       M.MONTH_END,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN
                A.COD_CONTRATO
             END) AS ATIVOS_ATUAIS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO <= M.MONTH_END AND
                   (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN
                A.COD_CONTRATO
             END) AS ATIVOS_PERIODO,

       COUNT(DISTINCT CASE
               WHEN B.DATA_INI_AFAST <= M.MONTH_END AND
                   (B.DATA_FIM_AFAST IS NULL OR B.DATA_FIM_AFAST >= M.MONTH_START) AND
                    /*B.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND*/
                    B.STATUS_AFAST <> 7 THEN
                A.COD_CONTRATO
             END) AS AFAST_PERIODO,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS ADMITIDOS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                A.COD_CONTRATO
             END) AS DEMITIDOS

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
 CROSS JOIN MONTHS M
 WHERE (UPPER(A.DES_FUNCAO) LIKE '%GERENTE%' OR
        UPPER(A.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
        UPPER(A.DES_FUNCAO) LIKE '%DIRETOR%')
 GROUP BY A.COD_EMP,
          M.MONTH_START,
          M.MONTH_END
),

TURNOVER_EMP AS (
SELECT A.COD_EMP,
       A.DES_EMP,
       DM.ATIVOS_ATUAIS,
       DM.ATIVOS_PERIODO,
       DM.AFAST_PERIODO,
       DM.ADMITIDOS,
       DM.DEMITIDOS,
       EI.EFETIVO_INICIAL,
       EF.EFETIVO_FINAL,
       (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DM.DEMITIDOS * 100) /
                ((EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER

  FROM (SELECT DISTINCT COD_EMP,
                        DES_EMP
          FROM CONTRATOS) A
  LEFT JOIN EFETIVO_INICIAL_EMP EI
         ON A.COD_EMP = EI.COD_EMP
  LEFT JOIN EFETIVO_FINAL_EMP EF
         ON A.COD_EMP = EF.COD_EMP
  LEFT JOIN DATAMETRICS_EMP DM
         ON A.COD_EMP = DM.COD_EMP
  /*WHERE (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (A.COD_REDE = :REDE OR :REDE = 0)
    AND (A.COD_TIPO = :TIPO OR :TIPO = 0)*/


),


/*============================*/

TURNOVER_UNIDADE AS (
  SELECT ROW_NUMBER() OVER(ORDER BY COD_TIPO, COD_REDE, COD_UNIDADE, COD_ORGANOGRAMA, COD_EMP) AS RN,
         T.*
    FROM TURNOVER_UNI T

),

TURNOVER_REDE AS (
  SELECT ROW_NUMBER() OVER(ORDER BY TIPO, REDE, DES_REDE) AS RN, R.*
    FROM TURNOVER_RD R
),

TURNOVER_LOJA AS (
  SELECT ROW_NUMBER() OVER(ORDER BY TIPO, DES_TIPO) AS RN, J.*
    FROM TURNOVER_LJ J
),

TURNOVER_ADM_CD AS (
  SELECT ROW_NUMBER() OVER(ORDER BY TIPO, REDE, DES_REDE) AS RN, A.*
    FROM TURNOVER_AC A
),

TURNOVER_ADM_E_CD AS (
  SELECT ROW_NUMBER() OVER(ORDER BY TIPO, DES_TIPO) AS RN, C.*
    FROM TURNOVER_CA C
),

TURNOVER_EMPRESA AS (
  SELECT ROW_NUMBER() OVER(ORDER BY COD_EMP, DES_EMP) AS RN, E.*
    FROM TURNOVER_EMP E
),

PERIODO AS (
  SELECT MIN(MONTH_START) AS INI, MAX(MONTH_END) AS FIM FROM MONTHS
)


/*SELECT FINAL COM TODOS OS INDICADORES*/
SELECT --LOJAS/SETORES
       U.COD_ORGANOGRAMA,
       U.COD_TIPO,
       U.COD_UNIDADE,
       U.DES_UNIDADE,
       U.DES_REDE AS DES_REDE_UNI,
       'Ref: ' || P.INI || ' - ' || P.FIM AS REFERENCIA,

       --NVL(PFM.TOT_COLAB, 0) AS COLABORADORES,
       U.ATIVOS_ATUAIS,
       U.ATIVOS_PERIODO,
       U.AFAST_PERIODO,
       U.ADMITIDOS,
       U.DEMITIDOS,
       U.EFETIVO_INICIAL,
       U.EFETIVO_FINAL,
       U.EFETIVO_MEDIO,

       ROUND(U.TURNOVER, 2) AS "%_TURNOVER",

       --REDES
       R.REDE,
       R.DES_REDE,
       R.ATIVOS_ATUAIS AS ATV_ATUAIS_RD,
       R.ATIVOS_PERIODO AS ATV_PERIODO_RD,
       R.AFAST_PERIODO AS AFAST_PERIODO_RD,
       R.ADMITIDOS AS ADMITIDOS_RD,
       R.DEMITIDOS AS DEMITIDOS_RD,
       R.EFETIVO_INICIAL AS EFTV_INICIAL_RD,
       R.EFETIVO_FINAL AS EFTV_FINAL_RD,
       R.EFETIVO_MEDIO AS EFTV_MEDIO_RD,

       ROUND(R.TURNOVER, 2) AS "%_TURNOVER_RD",

       --GERAL LOJAS
       L.TIPO,
       L.DES_TIPO,
       L.ATIVOS_ATUAIS AS ATV_ATUAIS_LJ,
       L.ATIVOS_PERIODO AS ATV_PERIODO_LJ,
       L.AFAST_PERIODO AS AFAST_PERIODO_LJ,
       L.ADMITIDOS AS ADMITIDOS_LJ,
       L.DEMITIDOS AS DEMITIDOS_LJ,
       L.EFETIVO_INICIAL AS EFTV_INICIAL_LJ,
       L.EFETIVO_FINAL AS EFTV_FINAL_LJ,
       L.EFETIVO_MEDIO AS EFTV_MEDIO_LJ,

       ROUND(L.TURNOVER, 2) AS "%_TURNOVER_LJ",

       --ADM E CD
       A.REDE AS SETOR,
       A.DES_REDE AS DES_SETOR,
       A.ATIVOS_ATUAIS AS ATV_ATUAIS_AC,
       A.ATIVOS_PERIODO AS ATV_PERIODO_AC,
       A.AFAST_PERIODO AS AFAST_PERIODO_AC,
       A.ADMITIDOS AS ADMITIDOS_AC,
       A.DEMITIDOS AS DEMITIDOS_AC,
       A.EFETIVO_INICIAL AS EFTV_INICIAL_AC,
       A.EFETIVO_FINAL AS EFTV_FINAL_AC,
       A.EFETIVO_MEDIO AS EFTV_MEDIO_AC,

       ROUND(A.TURNOVER, 2) AS "%_TURNOVER_AC",

       --ADM + CD
       C.TIPO AS TIPO_AD,
       C.DES_TIPO AS DES_TIPO_AD,
       C.ATIVOS_ATUAIS AS ATV_ATUAIS_AD,
       C.ATIVOS_PERIODO AS ATV_PERIODO_AD,
       C.AFAST_PERIODO AS AFAST_PERIODO_AD,
       C.ADMITIDOS AS ADMITIDOS_AD,
       C.DEMITIDOS AS DEMITIDOS_AD,
       C.EFETIVO_INICIAL AS EFTV_INICIAL_AD,
       C.EFETIVO_FINAL AS EFTV_FINAL_AD,
       C.EFETIVO_MEDIO AS EFTV_MEDIO_AD,

       ROUND(C.TURNOVER, 2) AS "%_TURNOVER_AD",

       --GERAL DA COMPANHIA
       E.COD_EMP,
       E.DES_EMP,
       E.ATIVOS_ATUAIS AS ATV_ATUAIS_EMP,
       E.ATIVOS_PERIODO AS ATV_PERIODO_EMP,
       E.AFAST_PERIODO AS AFAST_PERIODO_EMP,
       E.ADMITIDOS AS ADMITIDOS_EMP,
       E.DEMITIDOS AS DEMITIDOS_EMP,
       E.EFETIVO_INICIAL AS EFTV_INICIAL_EMP,
       E.EFETIVO_FINAL AS EFTV_FINAL_EMP,
       E.EFETIVO_MEDIO AS EFTV_MEDIO_EMP,

       ROUND(E.TURNOVER, 2) AS "%_TURNOVER_EMP",

       'De ' || :DATA_INICIO || ' até ' || :DATA_FIM AS PERIODO,

       'TIPO: ' || :TIPO || ' | ' || 'UNIDADE: ' || :UNIDADE ||
       ' | ' || 'REDE: ' || :REDE AS PARAMETROS

  FROM TURNOVER_UNIDADE U
  FULL OUTER JOIN TURNOVER_REDE     R ON U.RN = R.RN
  FULL OUTER JOIN TURNOVER_LOJA     L ON COALESCE(U.RN, R.RN) = L.RN
  FULL OUTER JOIN TURNOVER_ADM_CD   A ON COALESCE(U.RN, R.RN, L.RN) = A.RN
  FULL OUTER JOIN TURNOVER_ADM_E_CD C ON COALESCE(U.RN, R.RN, L.RN, A.RN) = C.RN
  FULL OUTER JOIN TURNOVER_EMPRESA  E ON COALESCE(U.RN, R.RN, L.RN, A.RN, C.RN) = E.RN
  CROSS JOIN PERIODO P

ORDER BY COALESCE(U.RN, R.RN, L.RN, A.RN, C.RN, E.RN)

