SELECT S.DATA_SOLICITACAO,
       MV.COD_SOLICITACAO,
       MV.COD_CONTRATO,
       MV.DATA_VIGENCIA,
       MV.JUSTIFICATIVA,
       MV.IND_CARGO,
       MV.COD_CARGO,
       R500.NOME_CLH,
       MV.IND_HORARIO,
       MV.HORARIO AS NOME_TURNO,
       MV.HORARIO,
       MV.IND_SALARIO,
       MV.VALOR_SALARIO,
       MV.PERC_SALARIO,
       MV.IND_CH,
       MV.COD_HORAS_BASE,
       MV.IND_ORGANOGRAMA,
       MV.COD_ORGANOGRAMA,
       R400.NOME_ORGANOGRAMA,
       MV.IND_AUXILIO_DESL,
       MV.IND_AUXILIO_ACESSO,
       MV.IND_ESPECIALIDADE,
       MV.IND_GRATIFICACAO,
       MV.IND_INSALUBRIDADE,
       MV.IND_PERICULOSIDADE,
       MV.IND_QUEBRA_CAIXA,
       MV.IND_RESP_TECNICA,
       MV.OUTRAS_VERBAS,
       MV.IND_TIPO_ALT,
       MV.COD_MOTIVO,
       PS.NOME_PESSOA,
       (SELECT NVL(MAX(COD_PROCESSO_MOV), 0)
           FROM RHWF0010) AS IND_SOLICITA_APROVACAO,
       NVL((SELECT COD_MOVIMENTACAO AS COD_REQUISICAO
               FROM RHWF0250
               WHERE COD_MOVIMENTACAO = MV.COD_SOLICITACAO
               GROUP BY COD_MOVIMENTACAO), 0) AS INDICADOR,
       NVL((SELECT SITUACAO AS SITUACAO
               FROM RHWF0250
               WHERE COD_MOVIMENTACAO = MV.COD_SOLICITACAO
               GROUP BY SITUACAO), NULL) AS SITUACAO
  FROM RHWF0312 MV,
       RHWF0310 S,
       RHFP0300 CT,
       PESSOA PS,
       RHFP0400 R400,
       RHFP0500 R500
 WHERE S.COD_SOLICITACAO = MV.COD_SOLICITACAO
   AND MV.COD_CONTRATO = CT.COD_CONTRATO
   AND CT.COD_FUNC = PS.COD_PESSOA
   AND S.COD_CONTRATO = 340774
   AND S.TIPO_SOLICITACAO = 'M'
   AND R400.COD_ORGANOGRAMA(+) = MV.COD_ORGANOGRAMA
   AND R500.COD_CLH(+) = MV.COD_CARGO
 ORDER BY DATA_SOLICITACAO DESC