SELECT DISTINCT A.COD_CONTRATO
      ,A.DATA
      ,DECODE(A.COD_SEQ_HORARIO,
 1,'MANHÃ'
,2,'TARDE') AS MANHA_OU_TARDE
      ,A.HORA_ENT AS HORA_ENTRADA
      ,DECODE(A.ORIGEM_ENT,
 'e','NÃO ALTERADO'
,'i','ALTERADO') AS IND_ALTERACAO_ENT
      ,A.HORA_SAI AS HORA_SAIDA
      ,DECODE(A.ORIGEM_SAI,
 'e','NÃO ALTERADO'
,'i','ALTERADO') AS IND_ALTERACAO_SAI
FROM RHAF1118 A, V_DADOS_PESSOA B, RHFP0401 C
where A.COD_CONTRATO = B.COD_CONTRATO
AND C.EDICAO_NIVEL3 = B.COD_UNIDADE

and A.data between :DATA_REFERENCIA_1 and :DATA_REFERENCIA_2
AND A.DATA <= :DATA_REFERENCIA
and (A.ORIGEM_ENT = 'i' OR A.ORIGEM_SAI = 'i')
ORDER BY A.COD_CONTRATO
