--SELECT 1

SELECT B.COD_CONTRATO,
       CASE
         WHEN B.DATA_INICIO IS NOT NULL THEN
          B.DATA_INICIO
         ELSE
          TO_DATE('01/09/2023', 'DD/MM/YYYY')
       END AS DATA_INICIO,
       CASE
         WHEN B.DATA_FIM IS NOT NULL THEN
          B.DATA_FIM
         ELSE
          TO_DATE('31/12/2999', 'DD/MM/YYYY')
       END AS DATA_FIM,
       B.COD_LOTACAO,
       CASE
         WHEN B.IND_TITULAR IS NOT NULL THEN
          B.IND_TITULAR
         ELSE
          'N'
       END AS IND_TITULAR,
       CASE
         WHEN B.COD_MOTIVO IS NOT NULL THEN
          B.COD_MOTIVO
         ELSE
          414
       END AS COD_MOTIVO
  FROM RHFP0509 A
  LEFT JOIN RHFP0309 B ON A.COD_LOTACAO = B.COD_LOTACAO
  LEFT JOIN RHFP0510 C ON A.COD_LOTACAO = C.COD_LOTACAO
          
          
--SELECT 2
         
SELECT VDC.COD_CONTRATO AS COD_CONTRATO_1,
       LT1.COD_LOTACAO AS COD_LOTACAO_2,
       LT1.COD_ORGANOGRAMA,
       VDC.COD_ORGANOGRAMA,
       VDC.COD_UNIDADE
  FROM V_DADOS_COLAB_AVT VDC
  LEFT JOIN RHFP0510 LT1 ON VDC.COD_ORGANOGRAMA = LT1.COD_ORGANOGRAMA
                        AND LT1.COD_CLH = VDC.COD_FUNCAO
 WHERE VDC.COD_EMP = '008'
   AND VDC.STATUS = 0
   AND VDC.STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND VDC.TIPO = 'LOJA'
   AND (VDC.COD_FUNCAO = 68 OR
       VDC.COD_FUNCAO IN
       (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) OR
       VDC.COD_FUNCAO IN (121, 305, 122) OR VDC.COD_FUNCAO = 206 OR
       VDC.COD_FUNCAO = 120 OR VDC.COD_FUNCAO = 102 OR VDC.COD_FUNCAO = 74)
 ORDER BY LT1.COD_LOTACAO
 
 
SELECT COD_CONTRATO, DES_PESSOA, DATA_ADMISSAO, DATA_DEMISSAO, COD_ORGANOGRAMA, COD_UNIDADE, DES_UNIDADE
  FROM V_DADOS_COLAB_AVT
 WHERE COD_EMP = '008'
   AND STATUS = 0
   AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND TIPO = 'LOJA'
   --AND COD_CONTRATO = 376606
   AND (COD_FUNCAO = 68 OR
       COD_FUNCAO IN
       (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) OR
       COD_FUNCAO IN (121, 305, 122) OR COD_FUNCAO = 206 OR
       COD_FUNCAO = 120 OR COD_FUNCAO = 102 OR COD_FUNCAO = 74)   
 ORDER BY COD_CONTRATO ASC;



--====SELECT OFICIAL PARA MAPEAR OS CONTRATOS DE CADA LOTAÇÃO=====----

SELECT VDC.COD_CONTRATO,
       LT.COD_LOTACAO,
       LT.COD_ORGANOGRAMA,
       VDC.COD_ORGANOGRAMA,
       VDC.COD_UNIDADE
  FROM V_DADOS_COLAB_AVT VDC
  LEFT JOIN RHFP0510 LT ON VDC.COD_ORGANOGRAMA = LT.COD_ORGANOGRAMA
                       AND LT.COD_CLH = VDC.COD_FUNCAO
 WHERE VDC.COD_EMP = '008'
   AND VDC.STATUS = 0
   AND VDC.STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND VDC.TIPO = 'LOJA'
   AND (VDC.COD_FUNCAO = 68 OR
       VDC.COD_FUNCAO IN
       (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) OR
       VDC.COD_FUNCAO IN (121, 305, 122) OR VDC.COD_FUNCAO = 206 OR
       VDC.COD_FUNCAO = 120 OR VDC.COD_FUNCAO = 102 OR VDC.COD_FUNCAO = 74)
 ORDER BY LT.COD_LOTACAO;


--VERSÃO 2====


SELECT VDC.COD_CONTRATO,
       LT.COD_LOTACAO,
       LT.COD_ORGANOGRAMA,
       VDC.COD_ORGANOGRAMA,
       VDC.COD_UNIDADE
  FROM V_DADOS_COLAB_AVT VDC
  LEFT JOIN RHFP0510 LT ON VDC.COD_ORGANOGRAMA = LT.COD_ORGANOGRAMA
                       AND LT.COD_CLH = VDC.COD_FUNCAO
 WHERE VDC.COD_EMP = '008'
   AND VDC.STATUS = 0
   AND VDC.STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND VDC.TIPO = 'LOJA'
   AND (VDC.COD_FUNCAO = 68 OR
       VDC.COD_FUNCAO IN
       (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) OR
       VDC.COD_FUNCAO IN (121, 305, 122) OR VDC.COD_FUNCAO = 206 OR
       VDC.COD_FUNCAO = 120 OR VDC.COD_FUNCAO = 102 OR VDC.COD_FUNCAO = 74)
 ORDER BY LT.COD_LOTACAO;
 
 
