CREATE OR REPLACE VIEW V_DADOS_ORGANOGRAMAS_AVT AS
SELECT
    L.COD_ORGANOGRAMA AS COD_ORGANOGRAMA,
    L.UNIDADE,
    L.NOME_UNIDADE AS NOME_UNIDADE,
    L.REDE AS COD_REDE_LOCAL,
    L.DES_REDE AS DES_REDE_SETOR,
    L.EMPRESA,
    'LOJA' AS TIPO,
    L.EDICAO_COMPLETA
FROM
    V_DADOS_LOJAS_AVT L

UNION ALL

-- Selecionando dados dos Setores
SELECT
    S.COD_ORGANOGRAMA AS COD_ORGANOGRAMA,
    S.SETOR,
    S.NOME_SETOR AS NOME_UNIDADE,
    S.EDICAO_NIVEL3 AS COD_REDE_LOCAL,
    S.DESC_SETOR AS DES_REDE_SETOR,
    S.EDICAO_NIVEL2 AS EMPRESA,
    CASE
        WHEN S.SETOR = 900 THEN 'DEPÓSITO'
        ELSE 'SETOR'
    END AS TIPO,
    S.EDICAO_COMPLETA
FROM
    V_SETORES_ADM_AVT S

