--SQL PARA ATUALIZAR COD_LOTACAO DA TABELA RHRS0200 PARA PODER DELETAR UMA LOTAÇÃO NA TABELA RHFP0509



SELECT COD_LOTACAO FROM RHRS0200
WHERE COD_LOTACAO IS NOT NULL;

DELETE 
FROM RHFP0509
WHERE COD_LOTACAO IN (1,923)

UPDATE RHRS0200
SET COD_LOTACAO = NULL
WHERE COD_LOTACAO IN (1,923)