SELECT CR.COD_ORGANOGRAMA,       
       CR.COD_CLASSE_CONT,       
       CR.COD_CUSTO_CONTABIL,       
       CR.COD_LANCAMENTO,       
       CR.CONTA_CONTABIL AS CONTA_CREDITO,       
       DB.CONTA_CONTABIL AS CONTA_DEBITO,
       TO_CHAR(SUM(CR.VALOR_LANCAMENTO), 'FM999G999G999D90') AS VALOR_CREDITO,
       TO_CHAR(SUM(DB.VALOR_LANCAMENTO), 'FM999G999G999D90') AS VALOR_DEBITO,      
       LC.COD_HISTORICO,       
       HI.HISTORICO_COMP,       
       CC.EDICAO_NIVEL5 AS EDICAO_NIVEL5_CC,       
       CC.EDICAO_NIVEL3 AS EDICAO_NIVEL3_CC,       
       CD.EDICAO_NIVEL5 AS EDICAO_NIVEL5_CD,       
       CD.EDICAO_NIVEL3 AS EDICAO_NIVEL3_CD
  FROM RHFP0402 CC,       
       RHFP0402 CD,       
       RHFP0404 LC,       
       RHFP0415 HI,       
       (SELECT *
          FROM RHFP0408        
         WHERE TIPO_LANCAMENTO = 'C') CR,       
       (SELECT *
          FROM RHFP0408        
         WHERE TIPO_LANCAMENTO = 'D') DB
 WHERE CR.COD_ORGANOGRAMA = DB.COD_ORGANOGRAMA      
   AND CR.COD_CLASSE_CONT = DB.COD_CLASSE_CONT      
   AND CR.COD_CUSTO_CONTABIL = DB.COD_CUSTO_CONTABIL      
   AND CR.COD_LANCAMENTO = DB.COD_LANCAMENTO      
   AND DB.COD_CUSTO_CONTABIL = CD.COD_CUSTO_CONTABIL      
   AND CR.COD_LANCAMENTO = LC.COD_LANCAMENTO      
   AND CR.COD_CUSTO_DESTINO = CC.COD_CUSTO_CONTABIL      
   AND (CR.COD_CONTA_CONTABIL = LC.COD_CONTA_CONTABIL       
       OR CR.COD_CONTA_CONTABIL = LC.COD_CONTRAPARTIDA       
       OR CR.COD_CONTA_CONTABIL = LC.COD_CONTA_NEGATIVA)      
   AND LC.COD_CONTA_CONTABIL = HI.COD_CONTA_CONTABIL(+)      
   AND LC.COD_HISTORICO = HI.COD_HISTORICO(+)
   AND CC.EDICAO_NIVEL5 = '900'
 GROUP BY CR.COD_ORGANOGRAMA,       
       CR.COD_CLASSE_CONT,       
       CR.COD_CUSTO_CONTABIL,       
       CR.COD_LANCAMENTO,       
       CR.CONTA_CONTABIL,  
       DB.CONTA_CONTABIL,
       LC.COD_HISTORICO,       
       HI.HISTORICO_COMP,       
       CC.EDICAO_NIVEL5, 
       CC.EDICAO_NIVEL3,   
       CD.EDICAO_NIVEL5,      
       CD.EDICAO_NIVEL3
       