VIEW V_STATUS_COLAB_AVT

CREATE OR REPLACE VIEW V_STATUS_COLAB_AVT AS 
SELECT COD_CONTRATO, 
       NOME_PESSOA, 
       DATA_INICIO,
       DATA_FIM,
       STATUS,
       CASE 
           WHEN STATUS = 0 AND DATA_INICIO <= TRUNC(SYSDATE) THEN 'ATIVO'
           WHEN STATUS = 0 AND DATA_INICIO > TRUNC(SYSDATE) THEN 'ADMISSAO_FUTURA'
           ELSE 'INATIVO' 
       END AS DESCRICAO_STATUS
FROM (
    SELECT RHFP0300.COD_CONTRATO, PF.NOME_PESSOA, RHFP0300.DATA_INICIO, RHFP0300.DATA_FIM, 0 AS STATUS
      FROM RHFP0300 
      JOIN PESSOA_FISICA PF ON RHFP0300.COD_FUNC = PF.COD_PESSOA
     WHERE (RHFP0300.DATA_FIM IS NULL OR RHFP0300.DATA_FIM >= TRUNC(SYSDATE))
       AND (RHFP0300.DATA_INICIO <= TRUNC(SYSDATE))
    UNION ALL
    SELECT RHFP0300.COD_CONTRATO, PF.NOME_PESSOA, RHFP0300.DATA_INICIO, RHFP0300.DATA_FIM, 1 AS STATUS
      FROM RHFP0300 
      JOIN PESSOA_FISICA PF ON RHFP0300.COD_FUNC = PF.COD_PESSOA
     WHERE (RHFP0300.DATA_FIM IS NOT NULL AND RHFP0300.DATA_FIM < TRUNC(SYSDATE))
       AND (RHFP0300.DATA_INICIO <= TRUNC(SYSDATE))
    UNION ALL
    SELECT RHFP0300.COD_CONTRATO, NULL AS NOME_PESSOA, RHFP0300.DATA_INICIO, RHFP0300.DATA_FIM, 0 AS STATUS
      FROM RHFP0300 
     WHERE (RHFP0300.DATA_INICIO > TRUNC(SYSDATE))
) T;