--SQL PARA ATUALIZAR AS REGIOES DAS LOJAS NA TBL PE0002

MERGE INTO PE0002 PE
USING V_DADOS_LOJAS_AVT VDL
ON (PE.COD_PESSOA = VDL.COD_PESSOA AND PE.COD_CAMPO = 1)
WHEN MATCHED THEN
  UPDATE SET PE.VALOR = VDL.COD_REGIAO;