SELECT A.COD_CONTRATO, A.DATA_INICIO, A.DATA_FIM,
       B.DATA_INICIO AS AFAST_INICIO, B.DATA_FIM AS AFAST_FIM,
       C.DATA_FERIAS, C.DATA_RETORNO,
       D.NUM_HORAS
       
FROM RHFP0300 A JOIN RHFP0306 B ON
       A.COD_CONTRATO = B.COD_CONTRATO JOIN RHFP0327 C ON
       B.COD_CONTRATO = C.COD_CONTRATO JOIN RHAF1123 D ON
       C.COD_CONTRATO = D.COD_CONTRATO

       
WHERE extract(YEAR from B.DATA_INICIO) = 2022