--SQL ORGANOGRAMA ATUAL DOS COLABORADORES DE TODO O GRUPO

SELECT DISTINCT A.COD_CONTRATO,
                A.NOME_PESSOA,
                C.COD_NIVEL2 AS EMPRESA,
                CASE
                  WHEN C.COD_NIVEL2 = 4 THEN
                   'MUNDIART SA'
                  WHEN C.COD_NIVEL2 = 6 THEN
                   'GRATO AGROPECUARIA LTDA GRATO'
                  WHEN C.COD_NIVEL2 = 8 THEN
                   'GRAZZIOTIN S A'
                  WHEN C.COD_NIVEL2 = 276 THEN
                   'CENTRO SHOPPING EMP E PARTIC LTDA ADM'
                  WHEN C.COD_NIVEL2 = 282 THEN
                   'GRAZZIOTIN FINANCEIRA SA CREDITO FINANCIAMENTO E I'
                  WHEN C.COD_NIVEL2 = 1629 THEN
                   'FLORESTA GRAZZIOTIN LTDA'
                  ELSE
                   'OUTRO'
                END AS DES_EMPRESA,
                B.COD_ORGANOGRAMA,
                C.EDICAO_ORG,
                C.EDICAO_ORG || ' - ' || D.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA,
                B.DATA_INICIO,
                B.DATA_FIM
  FROM V_STATUS_COLAB_AVT A, RHFP0310 B, RHFP0401 C, RHFP0400 D
 WHERE A.COD_CONTRATO = B.COD_CONTRATO
   AND C.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
   AND D.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
   AND B.DATA_FIM = '31/12/2999'
   AND C.DATA_FIM = '31/12/2999'
   AND A.STATUS = 0
   --AND A.DESC_STATUS <> 'ADMISSAO_FUTURA'
 ORDER BY C.COD_NIVEL2, C.EDICAO_ORG ASC;


--=========================================================--



--TESTANDO VERSÃO COM DATA DE REFERÊNCIA

SELECT A.COD_CONTRATO,
       A.NOME_PESSOA,
       C.COD_NIVEL2 AS EMPRESA,
       CASE
         WHEN C.COD_NIVEL2 = 4 THEN 'MUNDIART SA'
         WHEN C.COD_NIVEL2 = 6 THEN 'GRATO AGROPECUARIA LTDA GRATO'
         WHEN C.COD_NIVEL2 = 8 THEN 'GRAZZIOTIN S A'
         WHEN C.COD_NIVEL2 = 276 THEN 'CENTRO SHOPPING EMP E PARTIC LTDA ADM'
         WHEN C.COD_NIVEL2 = 282 THEN 'GRAZZIOTIN FINANCEIRA SA CREDITO FINANCIAMENTO E I'
         WHEN C.COD_NIVEL2 = 1629 THEN 'FLORESTA GRAZZIOTIN LTDA'
         ELSE 'OUTRO'
       END AS DES_EMPRESA,
       B.COD_ORGANOGRAMA,
       C.EDICAO_ORG,
       C.EDICAO_ORG || ' - ' || D.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA,
       B.DATA_INICIO,
       B.DATA_FIM
FROM V_STATUS_COLAB_AVT A 
JOIN RHFP0310 B ON A.COD_CONTRATO = B.COD_CONTRATO
JOIN RHFP0401 C ON C.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
JOIN RHFP0400 D ON D.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
WHERE A.STATUS = 0
AND '30/09/2023' BETWEEN B.DATA_INICIO AND B.DATA_FIM
AND '30/09/2023' BETWEEN C.DATA_INICIO AND C.DATA_FIM
ORDER BY C.COD_NIVEL2, C.EDICAO_ORG ASC;