/*SQL DA VIEW  - V_VALOR_HORAS_EXTRAS_AVT ORIGINAL = BACKUP*/

SELECT B.COD_ORGANOGRAMA AS COD_EMP,
       E.EDICAO_ORG AS COD_UNIDADE,
       F.NOME_ORGANOGRAMA AS DES_UNIDADE,

       /*VALOR REFERENTE AS HORAS EXTRAS*/
       SUM(CASE
             WHEN A.COD_VD IN
                  (158, 189, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 336) THEN
              COALESCE(A.QTDE_VD, 0)
             ELSE
              0
           END) AS QTDE_HORAS_EXTRAS,
       SUM(CASE
             WHEN A.COD_VD IN
                  (158, 189, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 336) THEN
              COALESCE(A.VALOR_VD, 0)
             ELSE
              0
           END) AS VLR_HORAS_EXTRAS,

       /*REPOUSO HORAS EXTRAS - VD 158*/

       /*BONUS REFERENTE AOS DOMINGOS*/
       SUM(CASE
             WHEN A.COD_VD = 323 THEN
              COALESCE(A.QTDE_VD, 0)
             ELSE
              0
           END) AS QTDE_BONUS_DOM,
       SUM(CASE
             WHEN A.COD_VD = 323 THEN
              COALESCE(A.VALOR_VD, 0)
             ELSE
              0
           END) AS VLR_BONUS_DOM,

       B.DATA_REFERENCIA,
       B.COD_EVENTO
  FROM RHFP1006 A
 INNER JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
 INNER JOIN RHFP1000 C ON A.COD_VD = C.COD_VD
 INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO
  LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA
  LEFT JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
 WHERE A.COD_VD IN
       (158, 189, 323, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 336)
   AND B.COD_EVENTO IN (1, 8)
   AND B.COD_ORGANOGRAMA = 8
 --AND E.EDICAO_ORG = 7390
 --AND B.DATA_REFERENCIA BETWEEN '01/06/2025' AND '30/06/2025'
 GROUP BY E.EDICAO_ORG, F.NOME_ORGANOGRAMA, B.DATA_REFERENCIA, B.COD_EVENTO, B.COD_ORGANOGRAMA
 ORDER BY E.EDICAO_ORG, B.DATA_REFERENCIA