--FUNÇÃO GERENTE

SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO,
       CASE
         WHEN COD_FUNCAO IN (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) THEN
         'LOT' || ' ' || DES_UNIDADE || ' - GERENTE'
         ELSE
         NULL
       END AS LOTACAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%GERENTE%'
ORDER BY COD_UNIDADE ASC


--===

--FUNÇÃO ORIENTADOR DE VENDA

SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO,
       CASE
         WHEN COD_FUNCAO IN (121, 305, 122) THEN
         'LOT' || ' ' || DES_UNIDADE || ' - ORIENT. DE VENDA'
         ELSE
         NULL
       END AS LOTACAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%ORIENTADOR DE VENDA%'
ORDER BY COD_UNIDADE ASC


--========


--FUNÇÃO AUXILIAR DE LOJA (POR MENOS)

SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO,
       CASE
         WHEN COD_FUNCAO = 206 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - AUXI. LOJA'
         ELSE
         NULL
       END AS LOTACAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%AUXILIAR DE LOJA%'
ORDER BY COD_UNIDADE ASC


--========


--FUNÇÃO VENDEDOR MODA MASCULINA

SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO,
       CASE
         WHEN COD_FUNCAO = 120 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - VEND. MODA MASC.'
         ELSE
         NULL
       END AS LOTACAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%VENDEDOR MODA MASCULINA%'
ORDER BY COD_UNIDADE ASC



--========


--FUNÇÃO CAIXA GERAL

SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO,
       CASE
         WHEN COD_FUNCAO = 102 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - CAIXA GERAL'
         ELSE
         NULL
       END AS LOTACAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%CAIXA GERAL%'
ORDER BY COD_UNIDADE ASC


--========


--FUNÇÃO APRENDIZ

SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO,
       CASE
         WHEN COD_FUNCAO = 74 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - APRENDIZ'
         ELSE
         NULL
       END AS LOTACAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%APRENDIZ%'
ORDER BY COD_UNIDADE ASC


--========


--FUNÇÃO SERVENTE

SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO,
       CASE
         WHEN COD_FUNCAO = 68 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - SERVENTE'
         ELSE
         NULL
       END AS LOTACAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%SERVENTE%'
ORDER BY COD_UNIDADE ASC
 
 
 
 
 
 
 
 
 
 
--===============================


--TODAS AS FUNÇÕES DOS COLABORADORES DE LOJA

SELECT COD_UNIDADE,
       DES_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
--AND COD_FUNCAO NOT IN (204)
AND COD_FUNCAO = 102
--AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
--AND DES_FUNCAO LIKE '%ORIENTADOR DE VENDA%'
ORDER BY COD_UNIDADE ASC


--===

SELECT DISTINCT 
       COD_FUNCAO,
       DES_FUNCAO
  FROM V_DADOS_COLAB_AVT
 WHERE STATUS = 0
   --AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND COD_EMP = '008'
   AND TIPO = 'LOJA'
   AND COD_FUNCAO NOT IN (204)
   AND DES_FUNCAO NOT LIKE '%GERENTE%'
ORDER BY COD_FUNCAO ASC


--==================================









--MAPEAR AS FUNÇÕES DE ORIENTADOR DE VENDA

----FUNÇÕES E AS PESSOAS E  SUAS LOJAS

SELECT COD_UNIDADE,
       DES_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%ORIENTADOR DE VENDA%'
ORDER BY COD_UNIDADE ASC


--SÓ OS CÓDIGOS DAS FUNÇÕES

SELECT DISTINCT 
       COD_FUNCAO
  FROM V_DADOS_COLAB_AVT
 WHERE STATUS = 0
   AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND COD_EMP = '008'
   AND TIPO = 'LOJA'
   --AND COD_FUNCAO NOT IN (204)
   AND DES_FUNCAO LIKE '%ORIENTADOR DE VENDA%'

 
 
 
 
--==============================






--MAPEAR AS LOJAS COM 2 GERENTES

SELECT COD_UNIDADE,
       COUNT(*) AS NUMERO_DE_GERENTES
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
  AND TIPO = 'LOJA'
  AND STATUS = 0
  AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
  AND COD_FUNCAO IN (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318)
GROUP BY COD_UNIDADE
HAVING COUNT(*) >= 2
ORDER BY COD_UNIDADE ASC;

--====

SELECT COD_UNIDADE,
       DES_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO 
FROM V_DADOS_COLAB_AVT
WHERE COD_UNIDADE IN (025, 566, 580, 7046, 7093)
AND DES_FUNCAO LIKE '%GERENTE%'
AND COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
 