SELECT B.COD_CONTRATO,
       E.EDICAO_ORG,
       G.CUSTO_CONTABIL,
       PF.NOME_PESSOA,
       B.DATA_INICIO,
       B.DATA_FIM,
       A.DATA_NASCIMENTO,
       'GRAZZIOTIN' AS DES_EMPRESA,
       D.COD_CLH,
       H.COD_TURNO,
       HOR.QTD_HORBAS_MES,
       A.NRO_CTPS,
       A.NRO_SERIE_CTPS,
       J.COD_CAUSA_AFAST,
       J.DATA_INICIO,
       J.DATA_FIM,
       PF.CPF,
       TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DTA_SISTEMA,
       '2230' AS LOTE,
       '045999999999' AS CPF_GESTOR,
       CASE
          WHEN K.NOME_CLH LIKE '%GERENTE%' OR
               K.NOME_CLH LIKE '%SUPERVISOR%' OR
               K.NOME_CLH LIKE '%DIRETOR%' THEN 
           1
          ELSE
           0
       END AS IN_GESTOR
  FROM RHFP0200 A
 INNER JOIN RHFP0300 B ON A.COD_FUNC = B.COD_FUNC
 INNER JOIN RHFP0310 C ON B.COD_CONTRATO = C.COD_CONTRATO
 INNER JOIN RHFP0340 D ON B.COD_CONTRATO = D.COD_CONTRATO
 INNER JOIN RHFP0401 E ON C.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA
 INNER JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
 INNER JOIN RHFP0402 G ON F.COD_CUSTO_CONTABIL = G.COD_CUSTO_CONTABIL
 INNER JOIN PESSOA_FISICA PF ON A.COD_FUNC = PF.COD_PESSOA
 INNER JOIN RHAF1119 H ON B.COD_CONTRATO = H.COD_CONTRATO
 INNER JOIN V_HORAS_COLAB_AVT HOR ON B.COD_CONTRATO = HOR.COD_CONTRATO
 INNER JOIN RHFP0306 J ON B.COD_CONTRATO = J.COD_CONTRATO
 INNER JOIN RHFP0500 K ON D.COD_CLH = K.COD_CLH
WHERE C.DATA_FIM = '31/12/2999'
AND D.DATA_FIM = '31/12/2999'
AND E.DATA_FIM = '31/12/2999'
AND H.DATA_FIM = '31/12/2999'



SELECT * FROM RHAF1119

SELECT * FROM V_DADOS_PESSOA

SELECT * FROM V_HORAS_COLAB_AVT