SELECT * FROM NL.NE_NOTAS --TBL RAIZ
WHERE NUM_NOTA = 51698990;

--NL.AI_NE_NOTAS TABELA "TEMP" QUE SERVE COMO PONTE PARA AS RAIZ
SELECT * FROM NL.AI_NE_NOTAS

--====================================================--

SELECT * FROM NL.NE_ITENS --TBL RAIZ
WHERE NUM_SEQ = 13742574;

--NL.AI_NE_ITENS TABELA "TEMP" QUE SERVE COMO PONTE PARA AS RAIZ
SELECT * FROM NL.AI_NE_ITENS

--====================================================--

SELECT * FROM NL.CE_DIARIOS --TBL RAIZ
WHERE NUM_SEQ = 13742574;


--NL.AI_CE_DIARIOS TABELA "TEMP" QUE SERVE COMO PONTE PARA AS RAIZ
SELECT * FROM NL.AI_CE_DIARIOS

--====================================================--

SELECT * FROM NL.CP_TITULOS --TBL RAIZ
WHERE NUM_TITULO = 51698990

--NL.AI_CP_TITULOS TABELA "TEMP" QUE SERVE COMO PONTE PARA AS RAIZ
SELECT * FROM NL.AI_CP_TITULOS

--====================================================--

SELECT * FROM NL.CP_HISTORICOS --TBL RAIZ
WHERE NUM_TITULO = 51698990

--NL.AI_CP_TITULOS TABELA "TEMP" QUE SERVE COMO PONTE PARA AS RAIZ
SELECT * FROM NL.AI_CP_HISTORICOS 