--SELECT PARA ALTERAR O TIPO DE JORNADA DO E-SOCIAL, PARA ENVIO DO E-SOCIAL 

SELECT * FROM RHAF1145
WHERE COD_TURNO = 1

SELECT * FROM RHAF1145
ORDER BY 1 ASC

--UPDATE PARA ALTERAR DE 4 PARA 1 A COLUNA TIPO_JORNADA_ESOCIAL (POIS O TIPO 1 NÃO EXISTE MAIS NO SISTEMA)


UPDATE RHAF1145
SET TIPO_JORNADA_ESOCIAL = 1
WHERE COD_TURNO = 1