SET TERMOUT ON HEADING ON FEEDBACK ON VERIFY ON LINESIZE 2000
accept FILE prompt "ARQUIVO: "
accept USERNAME prompt "NOME DO NOVO USUARIO: "
accept PASSWORD prompt "SENHA DO NOVO USUARIO: " HIDE
accept OWNER prompt "NOME DO USUARIO ORIGEM: "
accept PASSWORD_ORIG prompt "SENHA DO USUARIO ORIGEM: " HIDE
accept PASSWORD_SYS prompt "SENHA DO USUARIO SYS: " HIDE
accept HOST_STRING prompt "HOST_STRING: "
accept DEFAULT_TABLESPACE prompt "DEFAULT TABLESPACE: "
accept TEMPORARY_TABLESPACE prompt "TEMPORARY TABLESPACE: "
accept RM_COMMAND prompt "COMANDO PARA DELECAO: "
SET TERMOUT OFF HEADING OFF FEEDBACK OFF VERIFY OFF
SPOOL &&FILE
SELECT 'PROMPT CONECTANDO ...' || CHR(10) || 'CONNECT SYS'||'/'||'&&PASSWORD_SYS'||'@'||'&&HOST_STRING'||' AS SYSDBA'
FROM DUAL;
SELECT 'PROMPT CRIANDO USUARIO...'
FROM DUAL;
SELECT 'CREATE USER &&USERNAME IDENTIFIED BY &&PASSWORD DEFAULT TABLESPACE &&DEFAULT_TABLESPACE TEMPORARY TABLESPACE &&TEMPORARY_TABLESPACE;'
FROM DUAL;
SELECT 'PROMPT GRANTS...'
FROM DUAL;
SELECT 'GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO &&USERNAME ;'
FROM DUAL;
SELECT 'PROMPT CONECTANDO ...' || CHR(10) || 'CONNECT &&OWNER'||'/'||'&&PASSWORD_ORIG'||'@'||'&&HOST_STRING'
FROM DUAL;
SELECT 'PROMPT CONCEDENDO PRIVILEGIOS ...'
FROM DUAL;
SELECT 'GRANT SELECT ON '||OBJECT_NAME||' TO &&USERNAME WITH GRANT OPTION;'
FROM ALL_OBJECTS 
WHERE UPPER(OWNER) = UPPER('&&OWNER')
AND OBJECT_TYPE NOT IN ('PACKAGE BODY','INDEX','LIBRARY','TYPE','TYPE BODY','TRIGGER','FUNCTION','PACKAGE','PROCEDURE', 'SEQUENCE');
SELECT 'GRANT EXECUTE ON '||OBJECT_NAME||' TO &&USERNAME WITH GRANT OPTION;'
FROM ALL_OBJECTS 
WHERE UPPER(OWNER) = UPPER('&&OWNER')
AND OBJECT_TYPE IN ('FUNCTION','PACKAGE','PROCEDURE');
SELECT 'PROMPT CRIANDO SINONIMOS...'
FROM DUAL;
SELECT 'CREATE SYNONYM &&USERNAME'||'.'||OBJECT_NAME||' FOR &&OWNER'||'.'||OBJECT_NAME||';'
FROM ALL_OBJECTS 
WHERE upper(OWNER) = upper('&&OWNER') 
AND OBJECT_TYPE NOT IN ('PACKAGE BODY','INDEX','LIBRARY','TYPE','TYPE BODY','SEQUENCE');
SPOOL OFF
SET TERMOUT ON HEADING ON FEEDBACK ON VERIFY ON
@&&FILE
host &&RM_COMMAND &&FILE
