/*VARIÁVEL OFICIAL PARA USAR ENTRADA DE DADOS NO PL/SQL - SELECT COM DATA DE EXEMPLO*/
SELECT
    TO_CHAR(TO_DATE('&DATA_INICIO','DD/MM/YYYY'),'DD/MM/YYYY') AS DATA_INICIO,
    TO_CHAR(TO_DATE('&DATA_FIM','DD/MM/YYYY'),'DD/MM/YYYY') AS DATA_FIM,
    TO_CHAR(TO_DATE('&DATA_INICIO','DD/MM/YYYY'),'DD/MM/YYYY')
    || ' - ' ||
    TO_CHAR(TO_DATE('&DATA_FIM','DD/MM/YYYY'),'DD/MM/YYYY') AS REFERENCIA
FROM dual


/*VARIÁVEL QUE O PL/SQL ACEITA COM ENTRADA DE DADOS = & 

EXEMPLO:
 &UNIDADE OU &TIPO OU &REDE...

*/