SELECT A.COD_OPERADOR, B.NOME_PESSOA, SUBSTR(RHYF0205(A.SENHA),1,30) AS SENHA 
FROM OPERADOR A, PESSOA B 
WHERE A.COD_OPERADOR = 'F387692'
AND A.COD_PESSOA = B.COD_PESSOA


--SQL ALTERNATIVO

SELECT DISTINCT A.COD_OPERADOR,
       B.NOME_PESSOA,
       SUBSTR(RHYF0205(A.SENHA),1,30) AS SENHA,
       C.TROCAR_SENHA
FROM OPERADOR A, PESSOA B, OPSENHA C
WHERE A.COD_PESSOA = B.COD_PESSOA
AND C.COD_OPERADOR = A.COD_OPERADOR
AND A.COD_OPERADOR = 'TESTE123'