--VERSÃO ALTERNATIVA PARA OS DADOS APENAS DE GERENTES

--CREATE OR REPLACE VIEW V_DADOS_PESSOA_GERENTES AS
SELECT FP03.COD_CONTRATO COD_CONTRATO
      ,INITCAP(P.COD_PESSOA) COD_PESSOA
      ,INITCAP(P.NOME_PESSOA) DES_PESSOA
      ,INITCAP(SUBSTR(P.NOME_PESSOA,1,INSTR(P.NOME_PESSOA,' ')-1)) DES_NOME
      ,INITCAP(SUBSTR(P.NOME_PESSOA,INSTR(P.NOME_PESSOA,' ')+1,50)) DES_SOBRENOME
      ,FUNCOES.COD_CLH COD_FUNCAO
      ,FUNCOES.NOME_CLH DES_FUNCAO
      ,TO_CHAR(FP02.DATA_NASCIMENTO,'DDMMYYYY') DATA_NASCIMENTO_OLD
      ,SENHA.DES_SENHA DATA_NASCIMENTO
      ,INITCAP(MUN.NOME_MUNIC) DES_MUNIC
      ,DECODE(FIS.COD_UF,'RS','BR','SC','BR','PR','BR') DES_PAIS
      ,FP03.COD_CONTRATO||'@GRAZZIOTIN.COM.BR' DES_EMAIL
      ,ORGANOGRAMA.NOME_ORGANOGRAMA
      ,INITCAP(ORG_CUSTO_CTB.NOME_CUSTO_CONTABIL) NOME_CUSTO_CONTABIL
      ,ORG_CUSTO_CTB.CUSTO_CONTABIL COD_UNIDADE
      ,NVL(ORG_CUSTO_CTB.EDICAO_NIVEL3,0) COD_GRUPO
      ,DECODE(ORG_CUSTO_CTB.EDICAO_NIVEL3,1,'GRAZZIOTIN',2,'TOTTAL',3,'PORMENOS',4,'FRANCO GIORGI',276,'GZT STORE') DES_GRUPO
      ,ORG_EMP.COD_NIVEL2 COD_EMP
      ,SENHA.COD_GRUPO COD_GRUPO_UNIDADE
      ,FP03.DATA_FIM DTA_DEMISSAO
      ,FP03.DATA_INICIO DTA_ADMISSAO
      ,FIS.CPF
      ,FP02.NRO_PIS_PASEP
      --,DECODE(NVL(RESPONSAVEL_LOJA.COD_CONTRATO,0),0,0,1) RESPONSAVEL_LOJA
FROM RHFP0200 FP02
   , RHFP0300 FP03
   , PESSOA P
   , MUNICI MUN
   , FISICA FIS
   , RHFP0310 CONTR_ORGANOGRAMA
   , RHFP0400 ORGANOGRAMA
   , RHFP0401 ORG_EMP
   , RHFP0402 ORG_CUSTO_CTB
   , RHFP0500 FUNCOES
   , RHFP0340 CONTRFUNC
   , MDL_USUARIO SENHA
   --, RHFP0396 RESPONSAVEL_LOJA
WHERE P.COD_PESSOA = FP02.COD_FUNC
AND FIS.COD_PESSOA = FP02.COD_FUNC
AND FP02.COD_FUNC = FP03.COD_FUNC
AND FP03.COD_CONTRATO = CONTRFUNC.COD_CONTRATO
AND FUNCOES.COD_CLH = CONTRFUNC.COD_CLH
AND FP03.COD_CONTRATO = CONTR_ORGANOGRAMA.COD_CONTRATO
AND FP03.COD_CONTRATO = SENHA.COD_CONTRATO(+)
AND FIS.COD_MUNIC = MUN.COD_MUNIC
AND CONTR_ORGANOGRAMA.COD_ORGANOGRAMA= ORGANOGRAMA.COD_ORGANOGRAMA
AND ORGANOGRAMA.COD_ORGANOGRAMA = ORG_EMP.COD_ORGANOGRAMA
AND ORGANOGRAMA.COD_CUSTO_CONTABIL = ORG_CUSTO_CTB.COD_CUSTO_CONTABIL(+)
AND CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
AND ORG_EMP.COD_NIVEL2 IN (4,8,282,276)
AND FP03.DATA_FIM IS NULL
--AND FP03.COD_CONTRATO = '353671'
AND CONTRFUNC.DATA_FIM > SYSDATE
--D TO_CHAR(DATA_NASCIMENTO,'DDMMYYYY') = '04121976'
AND ORG_EMP.DATA_INICIO <= TRUNC(SYSDATE)
AND ORG_EMP.DATA_FIM > TRUNC(SYSDATE)
--AND FP03.COD_CONTRATO = RESPONSAVEL_LOJA.COD_CONTRATO(+)
--AND RESPONSAVEL_LOJA.DATA_INICIO(+) <= SYSDATE
--AND RESPONSAVEL_LOJA.DATA_FIM(+) >= SYSDATE

