CREATE OR REPLACE VIEW FUNCIONARIOS AS
SELECT CON_CON.COD_CONTRATO
,CON_EMP.COD_FILIAL
,CON_EMP.NOME_FILIAL
,CON_EMP.EDICAO_FILIAL
,CON_STACON.STATUS_CONTRATO
,CON_EMP.MUNICIPIO_FILIAL
,CON_ORG.NOME_ORGANOGRAMA
,CON_FUN.NOME_FUNCIONARIO
,CON_CUSTO.EDICAO_NIVEL3
,CON_FUN.DATA_NASCIMENTO
,CON_STAAFA.STATUS_AFASTAMENTO
,CON_STAAFA.DATA_INICIO AS DTA_INICIO_AFAST
,CON_STAAFA.DATA_FIM AS DTA_FIM_AFAST
,CON_EMP.EDICAO_NIVEL6
,CON_CON.DATA_AVANCO
,CON_CLH.COD_CLH
,CON_TURNOS.COD_TURNO
,CON_FUN.NRO_CTPS
,CON_FUN.NRO_SERIE_CTPS
,CON_FUN.COD_UF_CTPS
,CON_USU_HOR.CONT_ALFA1
,CON_USU_HOR.CONT_ALFA2
,CON_USU_HOR.CONT_ALFA3
,CON_USU_HOR.CONT_ALFA4
,CON_USU_HOR.COD_CAMPO1
,CON_USU_HOR.COD_CAMPO2
,CON_USU_HOR.COD_CAMPO3
,CON_USU_HOR.COD_CAMPO4
,CON_CON.DATA_FIM
,CON_HORBAS.QTD_HORBAS_MES
,CON_RES.DATA_RESCISAO
,CON_EMP.EDICAO_NIVEL5
,CON_FER_PER.DATA_FERIAS
,CON_FER_PER.DATA_FIM_FERIAS
,CON_FUN.CPF
,CON_FUN.IND_DEFICIENCIA
From RHFP0300 RHFP0300
,  (
SELECT
Rhfp0300.COD_CONTRATO,
Rhfp0200.COD_FUNC,
Rhfp0200.COD_GRAU_INSTRUCAO,
Rhfp0200.COD_ESTADO_CIVIL,
Rhfp0200.COD_NACIONALIDADE,
Rhfp0200.COD_PESSOA_PARENTE,
Rhfp0200.COD_PESSOA_PAI,
Rhfp0200.COD_NACION_PAI,
Rhfp0200.COD_PESSOA_MAE,
Rhfp0200.COD_NACION_MAE,
Rhfp0200.COD_PESSOA_CONJUGE,
Rhfp0200.COD_NACION_CONJUGE,
Rhfp0200.DATA_NASCIMENTO,
TRUNC(MONTHS_BETWEEN(SYSDATE,Rhfp0200.DATA_NASCIMENTO) / 12) AS IDADE,
TO_CHAR(Rhfp0200.DATA_NASCIMENTO,'DD') AS DIA_NASCIMENTO,
TO_CHAR(Rhfp0200.DATA_NASCIMENTO,'MM') AS MES_NASCIMENTO,
TO_CHAR(Rhfp0200.DATA_NASCIMENTO,'YYYY') AS ANO_NASCIMENTO,
Rhfp0200.SEXO,
Rhfp0200.COD_MUNIC_NASCIMENTO,
Rhfp0200.COD_UF_NASCIMENTO,
Rhfp0200.NRO_PIS_PASEP,
Rhfp0200.DATA_PIS_PASEP,
Rhfp0200.NRO_CONT_INDIVIDUAL,
Rhfp0200.DATA_CONT_INDIVIDUAL,
Rhfp0200.NRO_CTPS,
Rhfp0200.NRO_SERIE_CTPS,
Rhfp0200.DATA_EXP_CTPS,
Rhfp0200.COD_UF_CTPS,
Rhfp0200.NRO_TITULO,
Rhfp0200.NRO_ZONA_TITULO,
Rhfp0200.NRO_SECAO_TITULO,
Rhfp0200.DATA_EMISSAO_TITULO,
Rhfp0200.COD_UF_TITULO,
Rhfp0200.COD_MUN_TITULO,
Rhfp0200.NRO_HABILITACAO,
Rhfp0200.NRO_PRONTUARIO_HAB,
Rhfp0200.DATA_EMISSAO_HAB,
Rhfp0200.COD_CATEGORIA_HAB,
Rhfp0200.DATA_VALIDADE_HAB,
Rhfp0200.NRO_IDENTIDADE,
Rhfp0200.COD_ORG_IDENTIDADE,
Rhfp0200.DATA_EMI_IDENTIDADE,
Rhfp0200.COD_UF_IDENTIDADE,
Rhfp0200.NRO_RESERVISTA,
Rhfp0200.SERVICO_MILITAR,
Rhfp0200.NRO_PASSAPORTE,
Rhfp0200.DATA_EMI_PASSAPORTE,
Rhfp0200.DATA_VAL_PASSAPORTE,
Rhfp0200.ORGAO_EMISSOR_PASSAP,
Rhfp0200.COD_CONSELHO,
Rhfp0200.COD_ESCOLA,
Rhfp0200.DATA_DIPLOMACAO,
Rhfp0200.DATA_VALIDADE,
Rhfp0200.NRO_REGISTRO,
Rhfp0200.NRO_LIVRO,
Rhfp0200.NRO_FOLHA,
Rhfp0200.NRO_DOCUMENTO_01,
Rhfp0200.NRO_DOCUMENTO_02,
Rhfp0200.DATA_CASAMENTO,
Rhfp0200.DATA_APOSENTADORIA,
Rhfp0200.COD_TIPO_APOSENT,
Rhfp0145.NOME_TIPO_APOSENT,
Rhfp0200.NRO_BENEFICIO_INSS,
Rhfp0200.COD_RACA_COR,
Rhfp0200.CANDIDATO,
Rhfp0200.IND_DEFICIENCIA,
Rhfp0200.COD_DEFICIENCIA,
Rhfp0132.NOME_DEFICIENCIA,
Pessoa_1.NOME_PESSOA AS NOME_FUNCIONARIO,
Pessoa_2.NOME_PESSOA AS NOME_PARENTE,
Pessoa_3.NOME_PESSOA AS NOME_PAI,
Pessoa_4.NOME_PESSOA AS NOME_MAE,
Pessoa_5.NOME_PESSOA AS NOME_CONJUGE,
Pessoa_6.NOME_PESSOA AS NOME_ORGAO_IDENTIDADE,
Rhfp0104.NOME_ESTADO_CIVIL,
Rhfp0105.NOME_GRAU_INSTRUCAO,
Rhfp0105.NOME_RESUMIDO,
Rhfp0107_1.NOME_NACIONALIDADE AS NOME_NACIONALIDADE,
Rhfp0107_2.NOME_NACIONALIDADE AS NOME_NACIONALIDADE_PAI,
Rhfp0107_3.NOME_NACIONALIDADE AS NOME_NACIONALIDADE_MAE,
Rhfp0107_4.NOME_NACIONALIDADE AS NOME_NACIONALIDADE_CONJUGE,
Uf_1.NOME_UF AS NOME_UF_NASCIMENTO,
Munici_1.NOME_MUNIC AS NOME_MUNIC_NASCIMENTO,
Uf_2.NOME_UF AS NOME_UF_CTPS,
Uf_3.NOME_UF AS NOME_UF_TITULO,
Munici_1.NOME_MUNIC AS NOME_MUNIC_TITULO,
Uf_4.NOME_UF AS NOME_UF_IDENTIDADE,
Rhfp0130.NOME_RACA_COR,
Rhfp0200.COD_TITULACAO,
Rhfp0139.NOME_TITULACAO,
FISICA.CPF,
Pessoa_7.NOME_PESSOA AS NOME_CONSELHO_REGIONAL,
Pessoa_8.NOME_PESSOA AS NOME_ENTIDADE_ENSINO,
NVL(DEPS.NRO_DEPENDENTES,0) AS NRO_DEPENDENTES,
FISCONJ.DT_NASC AS DATA_NASC_CONJUGE,
FISCONJ.SEXO AS SEXO_CONJUGE,
FISICA.MATRICULA_NASC,
FISICA.COD_DNV,
FISICA.NRO_CARTAO_SUS,
FISICA.TIPO_SANGUE,
FISICA.FATOR_RH
FROM RHFP0200 Rhfp0200,
     RHFP0300 Rhfp0300,
     PESSOA Pessoa_1,
     PESSOA Pessoa_2,
     PESSOA Pessoa_3,
     PESSOA Pessoa_4,
     PESSOA Pessoa_5,
     PESSOA Pessoa_6,
     PESSOA Pessoa_7,
     PESSOA Pessoa_8,
     RHFP0104 Rhfp0104,
     RHFP0105 Rhfp0105,
     RHFP0107 Rhfp0107_1,
     RHFP0107 Rhfp0107_2,
     RHFP0107 Rhfp0107_3,
     RHFP0107 Rhfp0107_4,
     MUNICI Munici_1,
     UF Uf_1,
     UF Uf_2,
     UF Uf_3,
     MUNICI Munici_3,
     UF Uf_4,
     RHFP0130 Rhfp0130,
     FISICA Fisica,
     FISICA FISCONJ,
     Rhfp0132 Rhfp0132,
     Rhfp0139 Rhfp0139,
     Rhfp0145 Rhfp0145,
     (SELECT COD_FUNC,
             COUNT(*) AS NRO_DEPENDENTES
        FROM RHFP0202
       WHERE trunc(sysdate) BETWEEN RHFP0202.DATA_INICIO AND RHFP0202.DATA_FIM
       GROUP BY COD_FUNC
     ) DEPS
 WHERE (Rhfp0200.COD_FUNC = Rhfp0300.COD_FUNC)
       AND  (Rhfp0200.COD_FUNC             = Pessoa_1.COD_PESSOA(+))
       AND  (Rhfp0200.COD_PESSOA_PARENTE   = Pessoa_2.COD_PESSOA(+))
       AND  (Rhfp0200.COD_PESSOA_PAI       = Pessoa_3.COD_PESSOA(+))
       AND  (Rhfp0200.COD_PESSOA_MAE       = Pessoa_4.COD_PESSOA(+))
       AND  (Rhfp0200.COD_PESSOA_CONJUGE   = Pessoa_5.COD_PESSOA(+))
       AND  (Rhfp0200.COD_ORG_IDENTIDADE   = Pessoa_6.COD_PESSOA(+))
       AND  (Rhfp0200.COD_ESTADO_CIVIL     = Rhfp0104.COD_ESTADO_CIVIL(+))
       AND  (Rhfp0200.COD_GRAU_INSTRUCAO   = Rhfp0105.COD_GRAU_INSTRUCAO(+))
       AND  (Rhfp0200.COD_NACIONALIDADE    = Rhfp0107_1.COD_NACIONALIDADE(+))
       AND  (Rhfp0200.COD_NACION_PAI       = Rhfp0107_2.COD_NACIONALIDADE(+))
       AND  (Rhfp0200.COD_NACION_MAE       = Rhfp0107_3.COD_NACIONALIDADE(+))
       AND  (Rhfp0200.COD_NACION_CONJUGE   = Rhfp0107_4.COD_NACIONALIDADE(+))
       AND  (Rhfp0200.COD_UF_NASCIMENTO    = Munici_1.COD_UF(+))
       AND  (Rhfp0200.COD_MUNIC_NASCIMENTO = Munici_1.COD_MUNIC(+))
       AND  (Rhfp0200.COD_UF_NASCIMENTO    = Uf_1.COD_UF(+))
       AND  (Rhfp0200.COD_UF_CTPS          = Uf_2.COD_UF(+))
       AND  (Rhfp0200.COD_UF_TITULO        = Uf_3.COD_UF(+))
       AND  (Rhfp0200.COD_UF_TITULO        = Munici_3.COD_UF(+))
       AND  (Rhfp0200.COD_MUN_TITULO       = Munici_3.COD_MUNIC(+))
       AND  (Rhfp0200.COD_UF_IDENTIDADE    = Uf_4.COD_UF(+))
       AND  (Rhfp0200.COD_RACA_COR         = Rhfp0130.COD_RACA_COR(+))
       AND  (Rhfp0200.COD_FUNC             = Fisica.COD_PESSOA(+))
       AND  (Rhfp0200.COD_DEFICIENCIA      = Rhfp0132.COD_DEFICIENCIA(+))
       AND  (Rhfp0200.COD_TITULACAO        = Rhfp0139.COD_TITULACAO(+))
       AND  (Rhfp0200.COD_CONSELHO         = Pessoa_7.COD_PESSOA(+))
       AND  (Rhfp0200.COD_ESCOLA           = Pessoa_8.COD_PESSOA(+))
       AND  (Rhfp0200.COD_FUNC             = DEPS.COD_FUNC(+))
       AND  (Rhfp0200.COD_PESSOA_CONJUGE   = FISCONJ.COD_PESSOA(+))
       AND  (Rhfp0200.COD_TIPO_APOSENT     = Rhfp0145.COD_TIPO_APOSENT(+))
 ) CON_FUN
,(
SELECT RHAF1119.COD_CONTRATO,
       RHAF1119.DATA_INICIO,
       RHAF1119.COD_TURNO,
       RHAF1119.DATA_FIM,
       RHAF1119.COD_MOTIVO,
       RHAF1119.COD_SEQ_JORNADA,
       RHAF1119.TIPO_TURNO,
       RHFP0323.NOME_MOTIVO,
       RHFP0323.COD_TIPO_MOTIVO,
       RHFP0115.NOME_TIPO_MOTIVO,
       RHAF1145.NOME_TURNO,
       RHAF1145.COD_CLASSE_TURNO,
       RHAF1145.IND_REGIME_ESCALA,
       RHAF1103.NOME_CLASSE_TURNO,
        RHAF1145.HORARIO_1_ENT,
        RHAF1145.HORARIO_1_SAI,
        RHAF1145.HORARIO_2_ENT,
        RHAF1145.HORARIO_2_SAI,
        RHAF1145.HORARIO_3_ENT,
        RHAF1145.HORARIO_3_SAI,
        RHAF1145.HORARIO_4_ENT,
        RHAF1145.HORARIO_4_SAI
  FROM RHAF1119 RHAF1119,
       RHFP0323 RHFP0323,
       RHFP0115 RHFP0115,
       RHAF1145 RHAF1145,
       RHAF1103 RHAF1103
 WHERE RHAF1119.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
   AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
   AND RHAF1119.COD_TURNO = RHAF1145.COD_TURNO(+)
   AND RHAF1145.COD_CLASSE_TURNO = RHAF1103.COD_CLASSE_TURNO(+)
   AND trunc(sysdate) BETWEEN RHAF1119.DATA_INICIO AND RHAF1119.DATA_FIM
 ) CON_TURNOS
,(
SELECT
  RHFP0340.COD_CONTRATO,
  RHFP0340.DATA_INICIO,
  RHFP0340.DATA_FIM,
  RHFP0340.COD_CLH,
  RHFP0500.NOME_CLH,
  RHFP0500.COD_CBO,
  RHFP0500.COD_CBO_2002,
  RHFP0500.SEQUENCIA_CBO_2002,
  RHFP0500.EDICAO_CLH,
  RHFP0103.NOME_CBO,
  RHFP0137.NOME_CBO_2002,
  RHFP0340.COD_MOTIVO,
  RHFP0323.NOME_MOTIVO,
  RHFP0323.COD_TIPO_MOTIVO,
  RHFP0115.NOME_TIPO_MOTIVO,
  RHFP0340.COD_FUN_CARGO,
  RHFP0514.NOME_FUN_CARGO,
  RHFP0500.COD_GRUPO_OCUP,
  RHFP0609.NOME_GRUPO_OCUP,
  ROUND((MONTHS_BETWEEN(DECODE(RHFP0340.DATA_FIM,TO_DATE('31/12/2999'),DECODE(RHFP0300.DATA_FIM,NULL,trunc(sysdate),RHFP0300.DATA_FIM),RHFP0340.DATA_FIM),RHFP0340.DATA_INICIO) /12),2) AS ANOS_CARGO_BASE10,
   TRUNC(MONTHS_BETWEEN(DECODE(RHFP0340.DATA_FIM,TO_DATE('31/12/2999'),DECODE(RHFP0300.DATA_FIM,NULL,trunc(sysdate),RHFP0300.DATA_FIM),RHFP0340.DATA_FIM),RHFP0340.DATA_INICIO)/12) AS ANOS_CARGO,
   ROUND(MONTHS_BETWEEN(DECODE(RHFP0340.DATA_FIM,TO_DATE('31/12/2999'),DECODE(RHFP0300.DATA_FIM,NULL,trunc(sysdate),RHFP0300.DATA_FIM),RHFP0340.DATA_FIM),RHFP0340.DATA_INICIO)) AS MESES_CARGO
FROM
  RHFP0300 RHFP0300,
  RHFP0340 RHFP0340,
  RHFP0323 RHFP0323,
  RHFP0115 RHFP0115,
  RHFP0500 RHFP0500,
  RHFP0103 RHFP0103,
  RHFP0137 RHFP0137,
  RHFP0514 RHFP0514,
  RHFP0609 RHFP0609
WHERE RHFP0340.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
  AND RHFP0500.COD_GRUPO_OCUP = RHFP0609.COD_GRUPO_OCUP(+)
  AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
  AND RHFP0340.COD_CLH = RHFP0500.COD_CLH(+)
  AND RHFP0500.COD_CBO = RHFP0103.COD_CBO(+)
  AND RHFP0500.COD_CBO_2002 = RHFP0137.COD_CBO_2002(+)
  AND RHFP0500.SEQUENCIA_CBO_2002 = RHFP0137.SEQUENCIA(+)
  AND RHFP0340.COD_FUN_CARGO = RHFP0514.COD_FUN_CARGO(+)
  AND RHFP0340.COD_CONTRATO = RHFP0300.COD_CONTRATO
  AND trunc(sysdate) BETWEEN RHFP0340.DATA_INICIO AND RHFP0340.DATA_FIM
 ) CON_CLH
,(
SELECT
  RHFP0300.COD_CONTRATO,
  RHFP0300.COD_FUNC,
  RHFP0300.DATA_INICIO,
  RHFP0300.DATA_FIM,
  RHFP0300.COD_CAUSA_DEMISSAO,
  RHFP0102.NOME_CAUSA_DEMISSAO,
  RHFP0102.COD_CAGED AS COD_CAGED_DEMISSAO,
  RHFP0102.COD_SAQUE,
  RHFP0300.COD_CLASSE_CONTRATO,
  RHFP0239.NOME_CLASSE_CONTRATO,
  RHFP0300.COD_VINCULO_EMPREG,
  RHFP0110.NOME_VINCULO_EMPREG,
  RHFP0300.COD_TIPO_ADMISSAO,
  RHFP0114.NOME_TIPO_ADMISSAO,
  RHFP0114.COD_CAGED AS COD_CAGED_ADMISSAO,
  RHFP0300.COD_OPC_PGTO,
  RHFP0112.NOME_OPCAO_PGTO,
  RHFP0300.COD_FORMA_PGTO,
  RHFP0111.NOME_FORMA_PGTO,
  RHFP0300.COD_BCO_PGTO,
  BANCO_PGTO.COD_FEBRABAN AS COD_FEBRABAN_PGTO,
  PESSOA_BCO_PGTO.NOME_PESSOA AS NOME_BCO_PGTO,
  RHFP0300.COD_AGE_PGTO,
  AGENCIA_PGTO.DIGITO AS DIGITO_AGENCIA_PGTO,
  PESSOA_AGE_PGTO.NOME_PESSOA AS NOME_AGE_PGTO,
  RHFP0300.NRO_CONTA_PGTO,
  trim(substr(trim(RHFP0300.nro_conta_pgto),1,length(trim(RHFP0300.nro_conta_pgto))-1)) as nro_conta_pagamento,
  trim(substr(trim(RHFP0300.nro_conta_pgto),length(trim(RHFP0300.nro_conta_pgto)),1)) as digito_conta_pagamento,
  RHFP0300.DATA_OPCAO_FGTS,
  RHFP0300.COD_BCO_FGTD,
  BANCO_FGTS.COD_FEBRABAN AS COD_FEBRABAN_FGTS,
  PESSOA_BCO_FGTS.NOME_PESSOA AS NOME_BCO_FGTS,
  RHFP0300.COD_AGE_FGTS,
  PESSOA_AGE_FGTS.NOME_PESSOA AS NOME_AGE_FGTS,
  RHFP0300.NRO_CONTA_FGTS,
  RHFP0300.COD_TIPO_CONTRATO,
  RHFP0116.NOME_TIPO_CONTRATO,
  RHFP0116.DURACAO_CONTRATO,
  RHFP0116.ATUALIZA_AUTOMATICO,
  RHFP0116.NOVO_TIPO_CONTRATO,
  RHFP0300.MAO_OBRA,
  RHFP0300.COD_SITUACAO,
  RHFP0113.NOME_SITUACAO,
  RHFP0300.COD_CATEGORIA_TRAB,
  RHFP0128.NOME_CATEGORIA_TRAB,
  RHFP0300.COD_CLASSE_CONTRIB,
  RHFP0804.VALOR_CONTRIBUICAO,
  RHFP0300.IND_VINCULO_MULT,
  RHFP0300.IND_AGENTES_NOCIVOS,
  RHFP0300.IND_CONT_PREV,
  RHFP0300.DATA_AVANCO,
  trunc(sysdate) AS DATA_REFERENCIA,
  TO_NUMBER(TO_CHAR(RHFP0300.DATA_AVANCO,'DD'),'99') AS DIA_AVANCO,
  TO_NUMBER(TO_CHAR(RHFP0300.DATA_AVANCO,'MM'),'99') AS MES_AVANCO,
  TO_NUMBER(TO_CHAR(RHFP0300.DATA_AVANCO,'YYYY'),'9999') AS ANO_AVANCO,
  TO_NUMBER(TO_CHAR(RHFP0300.DATA_INICIO,'DD'),'99') AS DIA_ADMISSAO,
  TO_NUMBER(TO_CHAR(RHFP0300.DATA_INICIO,'MM'),'99') AS MES_ADMISSAO,
  TO_NUMBER(TO_CHAR(RHFP0300.DATA_INICIO,'YYYY'),'9999') AS ANO_ADMISSAO,
  0 AS CHECK_UNIBANCO,
  RHAF1112.IND_ESPELHO,
  RHAF1112.IND_FREQUENCIA,
  RHAF1112.IND_HORARIO_AUTO,
  RHAF1112.IND_OCORRENCIAS,
  RHAF1112.IND_REFEITORIO,
  RHCS0196.DATA_ADESAO,
  RHCS0196.IND_ADERIU,
  RHCS0196.NRO_PROTOCOLO,
  RHFP0300.DATA_REINTEGRACAO
FROM PESSOA PESSOA_BCO_PGTO,
     PESSOA PESSOA_AGE_PGTO,
     PESSOA PESSOA_BCO_FGTS,
     PESSOA PESSOA_AGE_FGTS,
     RHFP0300 RHFP0300,
     BANCO BANCO_PGTO,
     AGENCIA AGENCIA_PGTO,
     BANCO BANCO_FGTS,
     AGENCIA AGENCIA_FGTS,
     RHFP0102 RHFP0102,
     RHFP0239 RHFP0239,
     RHFP0110 RHFP0110,
     RHFP0114 RHFP0114,
     RHFP0112 RHFP0112,
     RHFP0111 RHFP0111,
     RHFP0116 RHFP0116,
     RHFP0113 RHFP0113,
     RHFP0128 RHFP0128,
     RHFP0804 RHFP0804,
     RHAF1112 RHAF1112,
     RHCS0196 RHCS0196
WHERE     RHFP0300.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO(+)
      AND RHFP0300.COD_CLASSE_CONTRATO = RHFP0239.COD_CLASSE_CONTRATO(+)
      AND RHFP0300.COD_VINCULO_EMPREG = RHFP0110.COD_VINCULO_EMPREG(+)
      AND RHFP0300.COD_TIPO_ADMISSAO = RHFP0114.COD_TIPO_ADMISSAO(+)
      AND RHFP0300.COD_OPC_PGTO = RHFP0112.COD_OPCAO_PGTO(+)
      AND RHFP0300.COD_FORMA_PGTO = RHFP0111.COD_FORMA_PGTO(+)
      AND RHFP0300.COD_BCO_PGTO = BANCO_PGTO.COD_BANCO(+)
      AND BANCO_PGTO.COD_PESSOA = PESSOA_BCO_PGTO.COD_PESSOA(+)
      AND RHFP0300.COD_BCO_PGTO = AGENCIA_PGTO.COD_BANCO(+)
      AND RHFP0300.COD_AGE_PGTO = AGENCIA_PGTO.COD_AGENCIA(+)
      AND AGENCIA_PGTO.COD_PESSOA = PESSOA_AGE_PGTO.COD_PESSOA(+)
      AND RHFP0300.COD_BCO_FGTD = BANCO_FGTS.COD_BANCO(+)
      AND BANCO_FGTS.COD_PESSOA = PESSOA_BCO_FGTS.COD_PESSOA(+)
      AND RHFP0300.COD_BCO_FGTD = AGENCIA_FGTS.COD_BANCO(+)
      AND RHFP0300.COD_AGE_FGTS = AGENCIA_FGTS.COD_AGENCIA(+)
      AND AGENCIA_FGTS.COD_PESSOA = PESSOA_AGE_FGTS.COD_PESSOA(+)
      AND RHFP0300.COD_TIPO_CONTRATO = RHFP0116.COD_TIPO_CONTRATO(+)
      AND RHFP0300.COD_SITUACAO = RHFP0113.COD_SITUACAO(+)
      AND RHFP0300.COD_CATEGORIA_TRAB = RHFP0128.COD_CATEGORIA_TRAB(+)
      AND RHFP0300.COD_CLASSE_CONTRIB = RHFP0804.COD_CLASSE_CONTRIB(+)
      AND RHFP0300.COD_CONTRATO = RHAF1112.COD_CONTRATO(+)
      AND trunc(sysdate) BETWEEN RHAF1112.DATA_INICIO(+) AND RHAF1112.DATA_FIM(+)
      AND RHFP0300.COD_CONTRATO = RHCS0196.COD_CONTRATO(+)
 ) CON_CON
,(
SELECT RHFP0307.COD_CONTRATO,
       RHFP0307.DATA_INICIO,
       RHFP0307.DATA_FIM,
       RHFP0307.COD_HORAS_BASE,
       RHFP0321.QTD_HORBAS_MES,
	 RHFP0321.QTD_HORBAS_SEM,
	 RHFP0321.QTD_HORBAS_DIA,
	 RHFP0307.COD_MOTIVO,
	 RHFP0323.NOME_MOTIVO,
	 RHFP0323.COD_TIPO_MOTIVO,
	 RHFP0115.NOME_TIPO_MOTIVO,
       ANTERIOR.DATA_INICIO AS DATA_INICIO_ANTERIOR,
       ANTERIOR.DATA_FIM AS DATA_FIM_ANTERIOR,
       ANTERIOR.COD_HORAS_BASE AS COD_HORAS_BASE_ANTERIOR,
       ANTERIOR.QTD_HORBAS_MES AS QTD_HORBAS_MES_ANTERIOR,
    	 ANTERIOR.QTD_HORBAS_SEM AS QTD_HORBAS_SEM_ANTERIOR,
       ANTERIOR.QTD_HORBAS_DIA AS QTD_HORBAS_DIA_ANTERIOR,
	 ANTERIOR.COD_MOTIVO AS COD_MOTIVO_ANTERIOR,
	 ANTERIOR.NOME_MOTIVO AS NOME_MOTIVO_ANTERIOR,
	 ANTERIOR.COD_TIPO_MOTIVO AS COD_TIPO_MOTIVO_ANTERIOR,
	 ANTERIOR.NOME_TIPO_MOTIVO AS NOME_TIPO_MOTIVO_ANTERIOR
  FROM RHFP0321 RHFP0321,
       RHFP0307 RHFP0307,
       RHFP0323 RHFP0323,
       RHFP0115 RHFP0115,
       ( SELECT RHFP0307.COD_CONTRATO,
                RHFP0307.DATA_INICIO,
                RHFP0307.DATA_FIM,
                RHFP0307.COD_HORAS_BASE,
                RHFP0321.QTD_HORBAS_MES,
                RHFP0321.QTD_HORBAS_SEM,
                RHFP0321.QTD_HORBAS_DIA,
	          RHFP0307.COD_MOTIVO,
	          RHFP0323.NOME_MOTIVO,
	          RHFP0323.COD_TIPO_MOTIVO,
	          RHFP0115.NOME_TIPO_MOTIVO
           FROM RHFP0321 RHFP0321,
                RHFP0307 RHFP0307,
                RHFP0323 RHFP0323,
                RHFP0115 RHFP0115
          WHERE RHFP0307.COD_HORAS_BASE = RHFP0321.COD_HORAS_BASE(+)
            AND RHFP0307.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
            AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
       ) ANTERIOR
 WHERE trunc(sysdate) BETWEEN RHFP0307.DATA_INICIO AND RHFP0307.DATA_FIM
   AND RHFP0307.COD_HORAS_BASE = RHFP0321.COD_HORAS_BASE(+)
   AND RHFP0307.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
   AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
   AND RHFP0307.COD_CONTRATO = ANTERIOR.COD_CONTRATO(+)
   AND RHFP0307.DATA_INICIO - 1 = ANTERIOR.DATA_FIM(+)
 ) CON_HORBAS
,(
SELECT
 RHFP0310.COD_CONTRATO,
 RHFP0310.DATA_INICIO AS DATA_INICIO_ORG,
 RHFP0310.DATA_FIM AS DATA_FIM_ORG,
 RHFP0310.COD_ORGANOGRAMA,
 SUBSTR(RHYF0002(RHFP0310.COD_ORGANOGRAMA,RHFP0400.COD_NIVEL_ORG,trunc(sysdate)),1,80) AS EDICAO_ORGANOGRAMA,
 RHFP0400.NOME_ORGANOGRAMA,
 RHFP0400.COD_NIVEL_ORG,
 RHFP0117.NOME_NIVEL_ORG,
 RHFP0400.COD_PESSOA AS COD_EMPFIL,
 PESSOA_EMPFIL.NOME_PESSOA AS NOME_EMPRESA_FILIAL,
 RHFP0400.CLIENTE,
 RHFP0400.COD_DRT,
 PESSOA_DRT.NOME_PESSOA AS NOME_DRT,
 RHFP0400.ULTIMA_FICHA_REG,
 RHFP0400.COD_CUSTO_CONTABIL,
 RHFP0402.NOME_CUSTO_CONTABIL,
 RHFP0402.CUSTO_CONTABIL,
 RHFP0310.COD_MOTIVO,
 RHFP0323.NOME_MOTIVO,
 RHFP0323.COD_TIPO_MOTIVO,
 RHFP0115.NOME_TIPO_MOTIVO,
 RHFP0310.COD_CAUSA_DEMISSAO,
 RHFP0102.NOME_CAUSA_DEMISSAO,
 RHFP0401.DATA_INICIO AS DATA_INICIO_EST,
 RHFP0401.DATA_FIM AS DATA_FIM_EST,
 RHFP0401.COD_ORGANOGRAMA_SUB,
 RHFP0401.EDICAO_ORG,
 RHFP0401.IND_LANCAMENTO,
 RHFP0436.CCUST_RH,
 RHFP3170.LOTACAO_SIAPE,
 ANTERIOR.DATA_INICIO_ORG AS DATA_INICIO_ORG_ANT,
 ANTERIOR.DATA_FIM_ORG AS DATA_FIM_ORG_ANT,
 ANTERIOR.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_ANT,
 ANTERIOR.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA_ANT,
 ANTERIOR.EDICAO_ORGANOGRAMA AS EDICAO_ORGANOGRAMA_ANT,
 ANTERIOR.COD_NIVEL_ORG AS COD_NIVEL_ORG_ANT,
 ANTERIOR.NOME_NIVEL_ORG AS NOME_NIVEL_ORG_ANT,
 ANTERIOR.COD_EMPFIL AS COD_EMPFIL_ANT,
 ANTERIOR.NOME_EMPRESA_FILIAL AS NOME_EMPRESA_FILIAL_ANT,
 ANTERIOR.CLIENTE AS CLIENTE_ANT,
 ANTERIOR.COD_DRT AS COD_DRT_ANT,
 ANTERIOR.NOME_DRT AS NOME_DRT_ANT,
 ANTERIOR.ULTIMA_FICHA_REG AS ULTIMA_FICHA_REF_ANT,
 ANTERIOR.COD_CUSTO_CONTABIL AS COD_CUSTO_CONTABIL_ANT,
 ANTERIOR.NOME_CUSTO_CONTABIL AS NOME_CUSTO_CONTABIL_ANT,
 ANTERIOR.CUSTO_CONTABIL AS CUSTO_CONTABIL_ANT,
 ANTERIOR.COD_MOTIVO AS COD_MOTIVO_ANT,
 ANTERIOR.NOME_MOTIVO AS NOME_MOTIVO_ANT,
 ANTERIOR.COD_TIPO_MOTIVO AS COD_TIPO_MOTIVO_ANT,
 ANTERIOR.NOME_TIPO_MOTIVO AS NOME_TIPO_MOTIVO_ANT,
 ANTERIOR.COD_CAUSA_DEMISSAO AS COD_CAUSA_DEMISSAO_ANT,
 ANTERIOR.NOME_CAUSA_DEMISSAO AS NOME_CAUSA_DEMISSAO_ANT,
 ANTERIOR.CCUST_RH AS CCUST_RH_ANT,
 ANTERIOR.LOTACAO_SIAPE AS LOTACAO_SIAPE_ANT,
 DECODE(ORESP.COD_CONTRATO_RESP, RHFP0310.COD_CONTRATO, 'S', 'N') AS IND_RESPONSAVEL
FROM
  RHFP0310 RHFP0310,
  RHFP0400 RHFP0400,
  RHFP0323 RHFP0323,
  RHFP0115 RHFP0115,
  RHFP0102 RHFP0102,
  RHFP0402 RHFP0402,
  RHFP0401 RHFP0401,
  RHFP0436 RHFP0436,
  RHFP3170 RHFP3170,
  PESSOA PESSOA_DRT,
  PESSOA PESSOA_EMPFIL,
  RHFP0117 RHFP0117,
  RHFP0397 ORESP,
  (SELECT RHFP0310.COD_CONTRATO,
          RHFP0310.DATA_INICIO AS DATA_INICIO_ORG,
          RHFP0310.DATA_FIM AS DATA_FIM_ORG,
          RHFP0310.COD_ORGANOGRAMA,
          RHFP0400.NOME_ORGANOGRAMA,
          SUBSTR(RHYF0002(RHFP0310.COD_ORGANOGRAMA,RHFP0400.COD_NIVEL_ORG,RHFP0310.DATA_INICIO),1,80) AS EDICAO_ORGANOGRAMA,
          RHFP0400.COD_NIVEL_ORG,
          RHFP0117.NOME_NIVEL_ORG,
          RHFP0400.COD_PESSOA AS COD_EMPFIL,
          PESSOA_EMPFIL.NOME_PESSOA AS NOME_EMPRESA_FILIAL,
          RHFP0400.CLIENTE,
          RHFP0400.COD_DRT,
          PESSOA_DRT.NOME_PESSOA AS NOME_DRT,
          RHFP0400.ULTIMA_FICHA_REG,
          RHFP0400.COD_CUSTO_CONTABIL,
          RHFP0402.NOME_CUSTO_CONTABIL,
          RHFP0402.CUSTO_CONTABIL,
          RHFP0310.COD_MOTIVO,
          RHFP0323.NOME_MOTIVO,
          RHFP0323.COD_TIPO_MOTIVO,
          RHFP0115.NOME_TIPO_MOTIVO,
          RHFP0310.COD_CAUSA_DEMISSAO,
          RHFP0102.NOME_CAUSA_DEMISSAO,
          RHFP0436.CCUST_RH,
          RHFP3170.LOTACAO_SIAPE
     FROM RHFP0310 RHFP0310,
          RHFP0400 RHFP0400,
          RHFP0323 RHFP0323,
          RHFP0115 RHFP0115,
          RHFP0102 RHFP0102,
          RHFP0402 RHFP0402,
          RHFP0436 RHFP0436,
          RHFP3170 RHFP3170,
          PESSOA PESSOA_DRT,
          PESSOA PESSOA_EMPFIL,
          RHFP0117 RHFP0117
    WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
      AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
      AND RHFP0310.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO(+)
      AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
      AND RHFP0400.COD_CUSTO_CONTABIL = RHFP0402.COD_CUSTO_CONTABIL(+)
      AND RHFP0400.COD_PESSOA = PESSOA_EMPFIL.COD_PESSOA(+)
      AND RHFP0400.COD_DRT = PESSOA_DRT.COD_PESSOA(+)
      AND RHFP0400.COD_NIVEL_ORG = RHFP0117.COD_NIVEL_ORG(+)
      AND RHFP0310.COD_ORGANOGRAMA = RHFP0436.COD_ORGANOGRAMA(+)
      AND RHFP0310.COD_ORGANOGRAMA = RHFP3170.COD_ORGANOGRAMA(+)
     ) ANTERIOR
WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
      AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
      AND RHFP0310.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO(+)
      AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
      AND RHFP0400.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA(+)
      AND RHFP0400.COD_CUSTO_CONTABIL = RHFP0402.COD_CUSTO_CONTABIL(+)
      AND RHFP0400.COD_PESSOA = PESSOA_EMPFIL.COD_PESSOA(+)
      AND RHFP0400.COD_DRT = PESSOA_DRT.COD_PESSOA(+)
      AND RHFP0400.COD_NIVEL_ORG = RHFP0117.COD_NIVEL_ORG(+)
      AND trunc(sysdate) BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM
      AND RHFP0310.COD_CONTRATO = ANTERIOR.COD_CONTRATO(+)
      AND RHFP0310.DATA_INICIO - 1 = ANTERIOR.DATA_FIM_ORG(+)
      AND trunc(sysdate) BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
      AND RHFP0310.COD_ORGANOGRAMA = RHFP0436.COD_ORGANOGRAMA(+)
      AND RHFP0310.COD_ORGANOGRAMA = RHFP3170.COD_ORGANOGRAMA(+)
      AND RHFP0310.COD_ORGANOGRAMA = ORESP.COD_ORGANOGRAMA(+)
      AND trunc(sysdate) BETWEEN ORESP.DATA_INICIO(+) AND ORESP.DATA_FIM(+)
 ) CON_ORG
,(
SELECT RHFP0300.COD_CONTRATO,
       NVL(RHFP0306.COD_CAUSA_AFAST,0) AS  STATUS_AFASTAMENTO,
       RHFP0306.DATA_INICIO,
       RHFP0306.DATA_FIM
  FROM RHFP0306 RHFP0306,
       RHFP0300 RHFP0300
 WHERE RHFP0300.COD_CONTRATO = RHFP0306.COD_CONTRATO(+)
   AND trunc(sysdate) BETWEEN RHFP0306.DATA_INICIO(+) AND RHFP0306.DATA_FIM(+)
 ) CON_STAAFA
,(
SELECT CAMPOS.*
FROM (
SELECT CTR.COD_CONTRATO,
       CTR.DATA_INICIO,
     CTR.DATA_FIM,
     CTR.COD_CUSTO_CONTABIL,
       RHFP0402.CUSTO_CONTABIL,
     RHFP0402.NOME_CUSTO_CONTABIL,
     RHFP0402.COD_CUSTO_N1,
     RHFP0402.COD_CUSTO_N2,
     RHFP0402.COD_CUSTO_N3,
     RHFP0402.COD_CUSTO_N4,
     RHFP0402.COD_CUSTO_N5,
     RHFP0402.COD_CUSTO_N6,
     RHFP0402.COD_CUSTO_N7,
       RHFP0402.COD_CUSTO_N8,
     RHFP0402.COD_CUSTO_SUB,
       CS.NOME_CUSTO_CONTABIL AS NOME_CUSTO_SUB,
     RHFP0402.COD_NIVEL_CONTABIL,
     RHFP0402.EDICAO_CUSTO_CONT,
     RHFP0402.EDICAO_NIVEL1,
     RHFP0402.EDICAO_NIVEL2,
     RHFP0402.EDICAO_NIVEL3,
     RHFP0402.EDICAO_NIVEL4,
     RHFP0402.EDICAO_NIVEL5,
     RHFP0402.EDICAO_NIVEL6,
     RHFP0402.EDICAO_NIVEL7,
     RHFP0402.EDICAO_NIVEL8,
       SUBSTR(RHYF0034(RHFP0402.COD_CUSTO_CONTABIL,1,'E'),1,120) AS EDICAO_COMPOSTA_NIVEL1,
       SUBSTR(RHYF0034(RHFP0402.COD_CUSTO_CONTABIL,2,'E'),1,120) AS EDICAO_COMPOSTA_NIVEL2,
       SUBSTR(RHYF0034(RHFP0402.COD_CUSTO_CONTABIL,3,'E'),1,120) AS EDICAO_COMPOSTA_NIVEL3,
       SUBSTR(RHYF0034(RHFP0402.COD_CUSTO_CONTABIL,4,'E'),1,120) AS EDICAO_COMPOSTA_NIVEL4,
       SUBSTR(RHYF0034(RHFP0402.COD_CUSTO_CONTABIL,5,'E'),1,120) AS EDICAO_COMPOSTA_NIVEL5,
       SUBSTR(RHYF0034(RHFP0402.COD_CUSTO_CONTABIL,6,'E'),1,120) AS EDICAO_COMPOSTA_NIVEL6,
       SUBSTR(RHYF0034(RHFP0402.COD_CUSTO_CONTABIL,7,'E'),1,120) AS EDICAO_COMPOSTA_NIVEL7,
       SUBSTR(RHYF0034(RHFP0402.COD_CUSTO_CONTABIL,8,'E'),1,120) AS EDICAO_COMPOSTA_NIVEL8
  FROM RHFP0402 RHFP0402,
       RHFP0402 CS,
       (SELECT RHFP0310.COD_CONTRATO,
              RHFP0400.COD_CUSTO_CONTABIL,
             RHFP0310.DATA_INICIO,
           RHFP0310.DATA_FIM
          FROM RHFP0310 RHFP0310,
               RHFP0400 RHFP0400
         WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
           AND trunc(sysdate) BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM
           AND RHFP0310.COD_CONTRATO NOT IN (SELECT RHFP0313.COD_CONTRATO
                                               FROM RHFP0313 RHFP0313
                                              WHERE trunc(sysdate) BETWEEN RHFP0313.DATA_INICIO AND RHFP0313.DATA_FIM
                                               AND RHFP0313.COD_CONTRATO = RHFP0310.COD_CONTRATO)
         UNION ALL
        SELECT RHFP0313.COD_CONTRATO,
               RHFP0313.COD_CUSTO_CONTABIL,
               RHFP0313.DATA_INICIO,
           RHFP0313.DATA_FIM
          FROM RHFP0313 RHFP0313
         WHERE trunc(sysdate) BETWEEN RHFP0313.DATA_INICIO AND RHFP0313.DATA_FIM
       ) CTR
 WHERE RHFP0402.COD_CUSTO_CONTABIL = CTR.COD_CUSTO_CONTABIL
   AND RHFP0402.COD_CUSTO_SUB = CS.COD_CUSTO_CONTABIL(+)
) CAMPOS
WHERE 1=1
 ) CON_CUSTO
,(
SELECT STACON.COD_CONTRATO,
       STACON.STATUS AS STATUS_CONTRATO
  FROM (SELECT COD_CONTRATO,
               0 AS STATUS
          FROM  RHFP0300 RHFP0300
         WHERE (RHFP0300.DATA_FIM IS NULL  OR RHFP0300.DATA_FIM >= trunc(sysdate))
           AND (RHFP0300.DATA_INICIO <= trunc(sysdate))
         UNION ALL
        SELECT COD_CONTRATO,
               1 AS STATUS
          FROM  RHFP0300 RHFP0300
         WHERE (RHFP0300.DATA_FIM IS NOT NULL AND RHFP0300.DATA_FIM < trunc(sysdate))
           AND (RHFP0300.DATA_INICIO <= trunc(sysdate))
         UNION ALL
        SELECT COD_CONTRATO,
               1 AS STATUS
          FROM  RHFP0300 RHFP0300
         WHERE (RHFP0300.DATA_INICIO > trunc(sysdate))
       ) STACON
 ) CON_STACON
,(
SELECT
   CON.COD_CONTRATO,
   CAMPO1.COD_CAMPO AS COD_CAMPO1,
   CAMPO1.CONT_NUMERICO AS CONT_NUMERICO1,
   CAMPO1.CONT_DATA AS CONT_DATA1,
   CAMPO1.CONT_ALFA AS CONT_ALFA1,
   CAMPO1.COD_ITEM AS COD_ITEM1,
   CAMPO1.CONT_TEXTO AS CONT_TEXTO1,
   CAMPO1.NOME_CAMPO AS NOME_CAMPO1,
   CAMPO1.COD_CLASSE_USU AS COD_CLASSE_USU1,
   CAMPO1.TIPO_CAMPO AS TIPO_CAMPO1,
   CAMPO1.TAMANHO AS TAMANHO1,
   CAMPO1.MENSAGEM AS MENSAGEM1,
   CAMPO1.NOME_ITEM AS NOME_ITEM1,
   CAMPO1.NOME_CLASSE_USU AS NOME_CLASSE_USU1,

   CAMPO2.COD_CAMPO AS COD_CAMPO2,
   CAMPO2.CONT_NUMERICO AS CONT_NUMERICO2,
   CAMPO2.CONT_DATA AS CONT_DATA2,
   CAMPO2.CONT_ALFA AS CONT_ALFA2,
   CAMPO2.COD_ITEM AS COD_ITEM2,
   CAMPO2.CONT_TEXTO AS CONT_TEXTO2,
   CAMPO2.NOME_CAMPO AS NOME_CAMPO2,
   CAMPO2.COD_CLASSE_USU AS COD_CLASSE_USU2,
   CAMPO2.TIPO_CAMPO AS TIPO_CAMPO2,
   CAMPO2.TAMANHO AS TAMANHO2,
   CAMPO2.MENSAGEM AS MENSAGEM2,
   CAMPO2.NOME_ITEM AS NOME_ITEM2,
   CAMPO2.NOME_CLASSE_USU AS NOME_CLASSE_USU2,

   CAMPO3.COD_CAMPO AS COD_CAMPO3,
   CAMPO3.CONT_NUMERICO AS CONT_NUMERICO3,
   CAMPO3.CONT_DATA AS CONT_DATA3,
   CAMPO3.CONT_ALFA AS CONT_ALFA3,
   CAMPO3.COD_ITEM AS COD_ITEM3,
   CAMPO3.CONT_TEXTO AS CONT_TEXTO3,
   CAMPO3.NOME_CAMPO AS NOME_CAMPO3,
   CAMPO3.COD_CLASSE_USU AS COD_CLASSE_USU3,
   CAMPO3.TIPO_CAMPO AS TIPO_CAMPO3,
   CAMPO3.TAMANHO AS TAMANHO3,
   CAMPO3.MENSAGEM AS MENSAGEM3,
   CAMPO3.NOME_ITEM AS NOME_ITEM3,
   CAMPO3.NOME_CLASSE_USU AS NOME_CLASSE_USU3,

   CAMPO4.COD_CAMPO AS COD_CAMPO4,
   CAMPO4.CONT_NUMERICO AS CONT_NUMERICO4,
   CAMPO4.CONT_DATA AS CONT_DATA4,
   CAMPO4.CONT_ALFA AS CONT_ALFA4,
   CAMPO4.COD_ITEM AS COD_ITEM4,
   CAMPO4.CONT_TEXTO AS CONT_TEXTO4,
   CAMPO4.NOME_CAMPO AS NOME_CAMPO4,
   CAMPO4.COD_CLASSE_USU AS COD_CLASSE_USU4,
   CAMPO4.TIPO_CAMPO AS TIPO_CAMPO4,
   CAMPO4.TAMANHO AS TAMANHO4,
   CAMPO4.MENSAGEM AS MENSAGEM4,
   CAMPO4.NOME_ITEM AS NOME_ITEM4,
   CAMPO4.NOME_CLASSE_USU AS NOME_CLASSE_USU4,

   CAMPO5.COD_CAMPO AS COD_CAMPO5,
   CAMPO5.CONT_NUMERICO AS CONT_NUMERICO5,
   CAMPO5.CONT_DATA AS CONT_DATA5,
   CAMPO5.CONT_ALFA AS CONT_ALFA5,
   CAMPO5.COD_ITEM AS COD_ITEM5,
   CAMPO5.CONT_TEXTO AS CONT_TEXTO5,
   CAMPO5.NOME_CAMPO AS NOME_CAMPO5,
   CAMPO5.COD_CLASSE_USU AS COD_CLASSE_USU5,
   CAMPO5.TIPO_CAMPO AS TIPO_CAMPO5,
   CAMPO5.TAMANHO AS TAMANHO5,
   CAMPO5.MENSAGEM AS MENSAGEM5,
   CAMPO5.NOME_ITEM AS NOME_ITEM5,
   CAMPO5.NOME_CLASSE_USU AS NOME_CLASSE_USU5,

   CAMPO6.COD_CAMPO AS COD_CAMPO6,
   CAMPO6.CONT_NUMERICO AS CONT_NUMERICO6,
   CAMPO6.CONT_DATA AS CONT_DATA6,
   CAMPO6.CONT_ALFA AS CONT_ALFA6,
   CAMPO6.COD_ITEM AS COD_ITEM6,
   CAMPO6.CONT_TEXTO AS CONT_TEXTO6,
   CAMPO6.NOME_CAMPO AS NOME_CAMPO6,
   CAMPO6.COD_CLASSE_USU AS COD_CLASSE_USU6,
   CAMPO6.TIPO_CAMPO AS TIPO_CAMPO6,
   CAMPO6.TAMANHO AS TAMANHO6,
   CAMPO6.MENSAGEM AS MENSAGEM6,
   CAMPO6.NOME_ITEM AS NOME_ITEM6,
   CAMPO6.NOME_CLASSE_USU AS NOME_CLASSE_USU6,

   CAMPO7.COD_CAMPO AS COD_CAMPO7,
   CAMPO7.CONT_NUMERICO AS CONT_NUMERICO7,
   CAMPO7.CONT_DATA AS CONT_DATA7,
   CAMPO7.CONT_ALFA AS CONT_ALFA7,
   CAMPO7.COD_ITEM AS COD_ITEM7,
   CAMPO7.CONT_TEXTO AS CONT_TEXTO7,
   CAMPO7.NOME_CAMPO AS NOME_CAMPO7,
   CAMPO7.COD_CLASSE_USU AS COD_CLASSE_USU7,
   CAMPO7.TIPO_CAMPO AS TIPO_CAMPO7,
   CAMPO7.TAMANHO AS TAMANHO7,
   CAMPO7.MENSAGEM AS MENSAGEM7,
   CAMPO7.NOME_ITEM AS NOME_ITEM7,
   CAMPO7.NOME_CLASSE_USU AS NOME_CLASSE_USU7,

   CAMPO8.COD_CAMPO AS COD_CAMPO8,
   CAMPO8.CONT_NUMERICO AS CONT_NUMERICO8,
   CAMPO8.CONT_DATA AS CONT_DATA8,
   CAMPO8.CONT_ALFA AS CONT_ALFA8,
   CAMPO8.COD_ITEM AS COD_ITEM8,
   CAMPO8.CONT_TEXTO AS CONT_TEXTO8,
   CAMPO8.NOME_CAMPO AS NOME_CAMPO8,
   CAMPO8.COD_CLASSE_USU AS COD_CLASSE_USU8,
   CAMPO8.TIPO_CAMPO AS TIPO_CAMPO8,
   CAMPO8.TAMANHO AS TAMANHO8,
   CAMPO8.MENSAGEM AS MENSAGEM8,
   CAMPO8.NOME_ITEM AS NOME_ITEM8,
   CAMPO8.NOME_CLASSE_USU AS NOME_CLASSE_USU8,

   CAMPO9.COD_CAMPO AS COD_CAMPO9,
   CAMPO9.CONT_NUMERICO AS CONT_NUMERICO9,
   CAMPO9.CONT_DATA AS CONT_DATA9,
   CAMPO9.CONT_ALFA AS CONT_ALFA9,
   CAMPO9.COD_ITEM AS COD_ITEM9,
   CAMPO9.CONT_TEXTO AS CONT_TEXTO9,
   CAMPO9.NOME_CAMPO AS NOME_CAMPO9,
   CAMPO9.COD_CLASSE_USU AS COD_CLASSE_USU9,
   CAMPO9.TIPO_CAMPO AS TIPO_CAMPO9,
   CAMPO9.TAMANHO AS TAMANHO9,
   CAMPO9.MENSAGEM AS MENSAGEM9,
   CAMPO9.NOME_ITEM AS NOME_ITEM9,
   CAMPO9.NOME_CLASSE_USU AS NOME_CLASSE_USU9,

   CAMPO10.COD_CAMPO AS COD_CAMPO10,
   CAMPO10.CONT_NUMERICO AS CONT_NUMERICO10,
   CAMPO10.CONT_DATA AS CONT_DATA10,
   CAMPO10.CONT_ALFA AS CONT_ALFA10,
   CAMPO10.COD_ITEM AS COD_ITEM10,
   CAMPO10.CONT_TEXTO AS CONT_TEXTO10,
   CAMPO10.NOME_CAMPO AS NOME_CAMPO10,
   CAMPO10.COD_CLASSE_USU AS COD_CLASSE_USU10,
   CAMPO10.TIPO_CAMPO AS TIPO_CAMPO10,
   CAMPO10.TAMANHO AS TAMANHO10,
   CAMPO10.MENSAGEM AS MENSAGEM10,
   CAMPO10.NOME_ITEM AS NOME_ITEM10,
   CAMPO10.NOME_CLASSE_USU AS NOME_CLASSE_USU10

  FROM
      (SELECT COD_CONTRATO
         FROM RHFP0308
         GROUP BY COD_CONTRATO
      ) CON,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 5
      ) CAMPO1,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 6
      ) CAMPO2,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 7
      ) CAMPO3,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 8
      ) CAMPO4,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 0
      ) CAMPO5,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 0
      ) CAMPO6,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 0
      ) CAMPO7,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 0
      ) CAMPO8,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 0
      ) CAMPO9,
      (SELECT RHFP0308.COD_CONTRATO,
              RHFP0308.COD_CAMPO,
              RHFP0308.CONT_NUMERICO,
              RHFP0308.CONT_DATA,
              RHFP0308.CONT_ALFA,
              RHFP0308.COD_ITEM,
              RHFP0308.CONT_TEXTO,
              RHFP0337.NOME_CAMPO,
              RHFP0337.COD_CLASSE_USU,
              RHFP0337.TIPO_CAMPO,
              RHFP0337.TAMANHO,
              RHFP0337.MENSAGEM,
              RHFP0338.NOME_ITEM,
              RHFP0336.NOME_CLASSE_USU
         FROM RHFP0308 RHFP0308,
              RHFP0337 RHFP0337,
              RHFP0338 RHFP0338,
              RHFP0336 RHFP0336
        WHERE RHFP0308.COD_CAMPO = RHFP0337.COD_CAMPO(+)
          AND RHFP0308.COD_CAMPO = RHFP0338.COD_CAMPO(+)
          AND RHFP0308.COD_ITEM  = RHFP0338.COD_ITEM(+)
          AND RHFP0337.COD_CLASSE_USU =
RHFP0336.COD_CLASSE_USU(+)
          AND RHFP0308.COD_CAMPO = 0
      ) CAMPO10
  WHERE CON.COD_CONTRATO = CAMPO1.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO2.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO3.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO4.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO5.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO6.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO7.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO8.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO9.COD_CONTRATO(+)
    AND CON.COD_CONTRATO = CAMPO10.COD_CONTRATO(+)
 ) CON_USU_HOR
,(
SELECT DISTINCT
  RHFP0350.COD_CONTRATO,
  RHFP0350.DATA_RESCISAO,
  RHFP0350.DATA_AVISO_PREVIO,
  RHFP0350.DATA_PAGAMENTO,
  RHFP0350.COD_CAUSA_DEMISSAO,
  RHFP0350.SITUACAO,
  RHFP0350.PARCELAMENTO,
  RHFP0350.NRO_PROGRAMACAO,
  RHFP0350.TIPO_PROGRAMACAO,
  RHFP0350.AVISO_INDENIZADO,
  RHFP0350.DIAS_AVISO_PREVIO,
  DECODE(DECODE(RHFP0350.IND_REC_GRRF,'S',1,0) +
         DECODE(TRUNC(RHFP0350.DATA_RESCISAO,'MONTH'),TRUNC(ADD_MONTHS(trunc(sysdate),1),'MONTH'),1,0),
         2, 'S','N') AS IND_REC_GRRF,
  RHFP0351.DATA_COMPLEMENTO AS DATA_RESCISAO_COMPLEMENTAR,
  RHFP0351.DATA_PAGAMENTO   AS DATA_PAGAMENTO_COMPLEMENTAR,
  RHFP0351.SITUACAO         AS SITUACAO_COMPLEMENTAR,
  RHFP0351.COD_MOTIVO_COMPL AS COD_MOTIVO_COMPLEMENTAR,
  RHFP0351.PARCELAMENTO     AS PARCELAMENTO_COMPLEMENTAR,
  RHFP0351.TIPO_PROGRAMACAO AS TIPO_PROGRAMACAO_COMPLEMENTAR,
  RHFP0351.NRO_PROGRAMACAO  AS NRO_PROGRAMACAO_COMPLEMENTAR,
  RHFP0102.NOME_CAUSA_DEMISSAO,
  RHFP0356.NOME_MOTIVO_COMPL AS NOME_MOTIVO_COMPLEMENTAR,
  PARCRESC.NRO_PARCELA,
  PARCRESC.VALOR_PARCELA,
  PARCCOMP.NRO_PARCELA       AS NRO_PARCELA_COMPLEMENTAR,
  PARCCOMP.VALOR_PARCELA     AS VALOR_PARCELA_COMPLEMENTAR
  FROM
    RHFP0300 RHFP0300,
    RHFP0350 RHFP0350,
    RHFP0351 RHFP0351,
    RHFP0102 RHFP0102,
    RHFP0356 RHFP0356,
    (SELECT RHFP0352.COD_CONTRATO,
            RHFP0352.DATA_RESCISAO,
            RHFP0352.NRO_PARCELA,
            RHFP0352.VALOR_PARCELA
       FROM RHFP0352 RHFP0352
      WHERE RHFP0352.DATA_COMPLEMENTO IS NULL) PARCRESC,
    (SELECT RHFP0352.COD_CONTRATO,
            RHFP0352.DATA_RESCISAO,
            RHFP0352.DATA_COMPLEMENTO,
            RHFP0352.NRO_PARCELA,
            RHFP0352.VALOR_PARCELA
       FROM RHFP0352 RHFP0352
      WHERE RHFP0352.DATA_COMPLEMENTO IS NOT NULL) PARCCOMP
  WHERE RHFP0300.COD_CONTRATO  = RHFP0350.COD_CONTRATO
        AND RHFP0350.COD_CONTRATO  = RHFP0351.COD_CONTRATO(+)
        AND RHFP0350.DATA_RESCISAO  = RHFP0351.DATA_RESCISAO(+)
        AND RHFP0350.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO
        AND RHFP0351.COD_MOTIVO_COMPL = RHFP0356.COD_MOTIVO_COMPL(+)
        AND RHFP0350.COD_CONTRATO     = PARCRESC.COD_CONTRATO(+)
        AND RHFP0350.DATA_RESCISAO    = PARCRESC.DATA_RESCISAO(+)
        AND RHFP0351.COD_CONTRATO     = PARCCOMP.COD_CONTRATO(+)
        AND RHFP0351.DATA_RESCISAO    = PARCCOMP.DATA_RESCISAO(+)
        AND RHFP0351.DATA_COMPLEMENTO = PARCCOMP.DATA_COMPLEMENTO(+)
 ) CON_RES
,(
SELECT
   RHFP0327.COD_CONTRATO,
   RHFP0327.DATA_PREVISTA_FERIAS,
   RHFP0327.DIAS_FERIAS_CONCED,
   RHFP0327.DIAS_ABONO_CONCED,
   RHFP0327.DIAS_LICENCA,
   RHFP0327.PER13SAL,
   RHFP0327.DIAS_FERIAS_GOZADOS,
   RHFP0327.DIAS_ABONO_GOZADOS,
   RHFP0327.DATA_FERIAS,
   (RHFP0327.DATA_RETORNO - 1) AS DATA_FIM_FERIAS,
   RHFP0327.DATA_RETORNO,
   RHFP0327.DATA_ABONO,
   RHFP0327.DATA_FIM_ABONO,
   RHFP0327.DATA_PAGAMENTO,
   RHFP0327.FALTAS_DESCONTADAS,
   RHFP0327.ADIANTAMENTO,
   RHFP0327.TIPO_FERIAS,
   RHFP0327.AVISO_IMPRESSO,
   RHFP0327.RECIBO_IMPRESSO,
   RHFP0327.DESCONTA_FALTA,
   RHFP0327.APROPRIACAO,
   RHFP0327.SITUACAO_PROGRAMACAO,
   RHFP0327.NRO_PROGRAMACAO,
   RHFP0328.DATA_INICIO_PERIODO,
   RHFP0328.DIAS_FERIAS     AS DIAS_FERIAS_PERIODO,
   RHFP0328.DIAS_ABONO      AS DIAS_ABONO_PERIODO,
   RHFP0328.FALTA_FERIAS    AS FALTA_FERIAS_PERIODO,
   RHFP0328.FALTA_ABONO     AS FALTA_ABONO_PERIODO,
   RHFP0328.TOTAL_FALTAS    AS TOTAL_FALTAS_PERIODO,
   RHFP0328.NRO_PROGRAMACAO AS NRO_PROGRAMACAO_PERIODO,
   RHFP0328.TIPO_PERIODO,
   RHFP0325.DATA_FIM_PERIODO,
   RHFP0325.DATA_ENCERRAMENTO AS DATA_ENCERRAMENTO_PERIODO,
   RHFP0325.DATA_INCLUSAO AS DATA_INCLUSAO_PERIODO,
   RHFP0325.DIAS_PERIODO
   FROM
        RHFP0300 RHFP0300,
        RHFP0327 RHFP0327,
        RHFP0328 RHFP0328,
        RHFP0325 RHFP0325
   WHERE  RHFP0300.COD_CONTRATO = RHFP0327.COD_CONTRATO
          AND RHFP0327.COD_CONTRATO = RHFP0328.COD_CONTRATO
          AND RHFP0327.DATA_PREVISTA_FERIAS = RHFP0328.DATA_PREVISTA_FERIAS
          AND RHFP0328.DATA_INICIO_PERIODO = RHFP0325.DATA_INICIO_PERIODO
          AND RHFP0328.COD_CONTRATO = RHFP0325.COD_CONTRATO
          AND RHFP0327.DATA_PREVISTA_FERIAS BETWEEN trunc(sysdate - 30) AND trunc(sysdate)
 ) CON_FER_PER
,(
SELECT
        RHFP0310.COD_CONTRATO,
        RHFP0310.DATA_INICIO,
        RHFP0310.DATA_FIM,
        RHFP0310.COD_MOTIVO,
        RHFP0323.NOME_MOTIVO,
        RHFP0401.COD_NIVEL2 AS COD_EMPRESA,
        RHFP0401.COD_NIVEL3 AS COD_FILIAL,
        RHFP0401.COD_NIVEL4,
        RHFP0401.COD_NIVEL5,
        RHFP0401.COD_NIVEL6,
        RHFP0401.COD_NIVEL7,
        RHFP0401.COD_NIVEL8,
       (RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMSEMP_NIVEL4,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5) AS EDICAO_COMSEMP_NIVEL5,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6) AS EDICAO_COMSEMP_NIVEL6,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7) AS EDICAO_COMSEMP_NIVEL7,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7||'.'||RHFP0401.EDICAO_NIVEL8) AS EDICAO_COMSEMP_NIVEL8,
        RHFP0401.EDICAO_NIVEL2 AS EDICAO_COMPOSTA_EMPRESA,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3) AS EDICAO_COMPOSTA_FILIAL,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMPOSTA_NIVEL4,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5) AS EDICAO_COMPOSTA_NIVEL5,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6) AS EDICAO_COMPOSTA_NIVEL6,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7) AS EDICAO_COMPOSTA_NIVEL7,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7||'.'||RHFP0401.EDICAO_NIVEL8) AS EDICAO_COMPOSTA_NIVEL8,
        RHFP0401.EDICAO_NIVEL2 AS EDICAO_EMPRESA,
        RHFP0401.EDICAO_NIVEL3 AS EDICAO_FILIAL,
        RHFP0401.EDICAO_NIVEL4,
        RHFP0401.EDICAO_NIVEL5,
        RHFP0401.EDICAO_NIVEL6,
        RHFP0401.EDICAO_NIVEL7,
        RHFP0401.EDICAO_NIVEL8,

        PESEMP.COD_PESSOA   AS COD_PESSOA_EMPRESA,
        PESFIL.COD_PESSOA   AS COD_PESSOA_FILIAL,
        PESN04.COD_PESSOA   AS COD_PESSOA_NIVEL4,
        PESN05.COD_PESSOA   AS COD_PESSOA_NIVEL5,
        PESEMP.NOME_PESSOA  AS RAZAO_SOCIAL_EMPRESA,
        PESFIL.NOME_PESSOA  AS RAZAO_SOCIAL_FILIAL,
        PESN04.NOME_PESSOA  AS RAZAO_SOCIAL_NIVEL4,
        PESN05.NOME_PESSOA  AS RAZAO_SOCIAL_NIVEL5,

        RESPEMP.COD_PESSOA AS COD_RESP_EMPRESA,
        RESPEMP.NOME_PESSOA AS NOME_RESP_EMPRESA,
        RESPFIL.COD_PESSOA AS COD_RESP_FILIAL,
        RESPFIL.NOME_PESSOA AS NOME_RESP_FILIAL,

        EMP400.NOME_ORGANOGRAMA  AS NOME_EMPRESA,
        FIL400.NOME_ORGANOGRAMA  AS NOME_FILIAL,
        JURFIL.FANTASIA          AS NOME_FANTASIA_FILIAL,
        N4.NOME_ORGANOGRAMA      AS NOME_NIVEL4,
        N5.NOME_ORGANOGRAMA      AS NOME_NIVEL5,
        N6.NOME_ORGANOGRAMA      AS NOME_NIVEL6,
        N7.NOME_ORGANOGRAMA      AS NOME_NIVEL7,
        N8.NOME_ORGANOGRAMA      AS NOME_NIVEL8,
        LOGEMP.NOME_LOGRA     AS LOGRADOURO_EMPRESA,
        JUREMP.NUMERO         AS NUMERO_EMPRESA,
        JUREMP.COMPLEMENTO    AS COMPLEMENTO_EMPRESA,
        BAIEMP.NOME_BAIRRO    AS BAIRRO_EMPRESA,
        MUNEMP.NOME_MUNIC     AS MUNICIPIO_EMPRESA,
        JUREMP.CEP            AS CEP_EMPRESA,
        JUREMP.COD_UF         AS UF_EMPRESA,
        JUREMP.CGC            AS CGC_EMPRESA,
        JUREMP.TIP_LOGRA      AS TIPO_LOG_EMPRESA,

        LOGFIL.NOME_LOGRA     AS LOGRADOURO_FILIAL,
        JURFIL.NUMERO         AS NUMERO_FILIAL,
        JURFIL.COMPLEMENTO    AS COMPLEMENTO_FILIAL,
        BAIFIL.NOME_BAIRRO    AS BAIRRO_FILIAL,
        MUNFIL.NOME_MUNIC     AS MUNICIPIO_FILIAL,
        JURFIL.CEP            AS CEP_FILIAL,
        JURFIL.COD_UF         AS UF_FILIAL,
        JURFIL.CGC            AS CGC_FILIAL,
        JURFIL.TIP_LOGRA      AS TIPO_LOG_FILIAL,
        JURFIL.DDD            AS DDD_FILIAL,
        JURFIL.FONE           AS FONE_FILIAL,

       LOGN4.NOME_LOGRA       AS LOGRADOURO_NIVEL4,
       JURN4.NUMERO           AS NUMERO_NIVEL4,
       JURN4.COMPLEMENTO      AS COMPLEMENTO_NIVEL4,
       BAIN4.NOME_BAIRRO      AS BAIRRO_NIVEL4,
       MUNN4.NOME_MUNIC       AS MUNICIPIO_NIVEL4,
       JURN4.CEP              AS CEP_NIVEL4,
       JURN4.COD_UF           AS UF_NIVEL4,
       JURN4.CGC              AS CGC_NIVEL4,
       JURN4.TIP_LOGRA        AS TIPO_LOG_NIVEL4,

       LOGN5.NOME_LOGRA       AS LOGRADOURO_NIVEL5,
       JURN5.NUMERO           AS NUMERO_NIVEL5,
       JURN5.COMPLEMENTO      AS COMPLEMENTO_NIVEL5,
       BAIN5.NOME_BAIRRO      AS BAIRRO_NIVEL5,
       MUNN5.NOME_MUNIC       AS MUNICIPIO_NIVEL5,
       JURN5.CEP              AS CEP_NIVEL5,
       JURN5.COD_UF           AS UF_NIVEL5,
       JURN5.CGC              AS CGC_NIVEL5,
       JURN5.TIP_LOGRA        AS TIPO_LOG_NIVEL5,

       R430EMP.BANCO_DEBITO   AS ESTEMP_BANCO_DEBITO,
       R430EMP.CODAGE_DEBITO  AS ESTEMP_CODAGE_DEBITO,
       R430EMP.DIGAGE_DEBITO  AS ESTEMP_DIGAGE_DEBITO,
       R430EMP.CONTA_DEBITO   AS ESTEMP_CONTA_DEBITO,
       R430EMP.TIPO_INSCRICAO AS ESTEMP_TIPO_INSCRICAO,
       R430EMP.CPF            AS ESTEMP_CPF,
       R430EMP.COD_CEI        AS ESTEMP_COD_CEI,
       JUREMP.CGC             AS ESTEMP_CNPJ,
       SUBSTR(JUREMP.CGC,9,6) AS ESTEMP_COMP_CNPJ,

       R430FIL.BANCO_DEBITO   AS ESTFIL_BANCO_DEBITO,
       R430FIL.CODAGE_DEBITO  AS ESTFIL_CODAGE_DEBITO,
       R430FIL.DIGAGE_DEBITO  AS ESTFIL_DIGAGE_DEBITO,
       R430FIL.CONTA_DEBITO   AS ESTFIL_CONTA_DEBITO,
       R430FIL.TIPO_INSCRICAO AS ESTFIL_TIPO_INSCRICAO,
       R430FIL.CPF            AS ESTFIL_CPF,
       R430FIL.COD_CEI        AS ESTFIL_COD_CEI,
       JURFIL.CGC             AS ESTFIL_CNPJ,
       SUBSTR(JURFIL.CGC,9,6) AS ESTFIL_COMP_CNPJ,


       PESBANEMP.NOME_PESSOA AS ESTEMP_NOME_BANCO_DEBITO,
       PESBANFIL.NOME_PESSOA AS ESTFIL_NOME_BANCO_DEBITO,
       PESAGEEMP.NOME_PESSOA AS ESTEMP_NOME_AGENCIA_DEBITO,
       PESAGEFIL.NOME_PESSOA AS ESTFIL_NOME_AGENCIA_DEBITO,

       ANTERIOR.COD_EMPRESA                        AS ANT_COD_EMPRESA,
       ANTERIOR.DATA_INICIO                        AS ANT_DATA_INICIO,
       ANTERIOR.DATA_FIM                           AS ANT_DATA_FIM,
       ANTERIOR.COD_MOTIVO                         AS ANT_COD_MOTIVO,
       ANTERIOR.NOME_MOTIVO                        AS ANT_NOME_MOTIVO,
       ANTERIOR.COD_FILIAL                         AS ANT_COD_FILIAL,
       ANTERIOR.COD_NIVEL4                         AS ANT_COD_NIVEL4,
       ANTERIOR.COD_NIVEL5                         AS ANT_COD_NIVEL5,
       ANTERIOR.COD_NIVEL6                         AS ANT_COD_NIVEL6,
       ANTERIOR.COD_NIVEL7                         AS ANT_COD_NIVEL7,
       ANTERIOR.COD_NIVEL8                         AS ANT_COD_NIVEL8,
       ANTERIOR.EDICAO_COMSEMP_NIVEL4              AS ANT_EDICAO_COMSEMP_NIVEL4,
       ANTERIOR.EDICAO_COMSEMP_NIVEL5              AS ANT_EDICAO_COMSEMP_NIVEL5,
       ANTERIOR.EDICAO_COMSEMP_NIVEL6              AS ANT_EDICAO_COMSEMP_NIVEL6,
       ANTERIOR.EDICAO_COMSEMP_NIVEL7              AS ANT_EDICAO_COMSEMP_NIVEL7,
       ANTERIOR.EDICAO_COMSEMP_NIVEL8              AS ANT_EDICAO_COMSEMP_NIVEL8,
       ANTERIOR.EDICAO_COMPOSTA_EMPRESA            AS ANT_EDICAO_COMPOSTA_EMPRESA,
       ANTERIOR.EDICAO_COMPOSTA_FILIAL             AS ANT_EDICAO_COMPOSTA_FILIAL,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL4             AS ANT_EDICAO_COMPOSTA_NIVEL4,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL5             AS ANT_EDICAO_COMPOSTA_NIVEL5,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL6             AS ANT_EDICAO_COMPOSTA_NIVEL6,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL7             AS ANT_EDICAO_COMPOSTA_NIVEL7,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL8             AS ANT_EDICAO_COMPOSTA_NIVEL8,
       ANTERIOR.EDICAO_EMPRESA                     AS ANT_EDICAO_EMPRESA,
       ANTERIOR.EDICAO_FILIAL                      AS ANT_EDICAO_FILIAL,
       ANTERIOR.EDICAO_NIVEL4                      AS ANT_EDICAO_NIVEL4,
       ANTERIOR.EDICAO_NIVEL5                      AS ANT_EDICAO_NIVEL5,
       ANTERIOR.EDICAO_NIVEL6                      AS ANT_EDICAO_NIVEL6,
       ANTERIOR.EDICAO_NIVEL7                      AS ANT_EDICAO_NIVEL7,
       ANTERIOR.EDICAO_NIVEL8                      AS ANT_EDICAO_NIVEL8,

       ANTERIOR.COD_PESSOA_EMPRESA                 AS ANT_COD_PESSOA_EMPRESA,
       ANTERIOR.COD_PESSOA_FILIAL                  AS ANT_COD_PESSOA_FILIAL,
       ANTERIOR.COD_PESSOA_NIVEL4                  AS ANT_COD_PESSOA_NIVEL4,
       ANTERIOR.COD_PESSOA_NIVEL5                  AS ANT_COD_PESSOA_NIVEL5,

       ANTERIOR.RAZAO_SOCIAL_EMPRESA               AS ANT_RAZAO_SOCIAL_EMPRESA,
       ANTERIOR.RAZAO_SOCIAL_FILIAL                AS ANT_RAZAO_SOCIAL_FILIAL,
       ANTERIOR.RAZAO_SOCIAL_NIVEL4                AS ANT_RAZAO_SOVIAL_NIVEL4,
       ANTERIOR.RAZAO_SOCIAL_NIVEL5                AS ANT_RAZAO_SOVIAL_NIVEL5,

       ANTERIOR.COD_RESP_EMPRESA                   AS ANT_COD_RESP_EMPRESA,
       ANTERIOR.NOME_RESP_EMPRESA                  AS ANT_NOME_RESP_EMPRESA,
       ANTERIOR.COD_RESP_FILIAL                    AS ANT_COD_RESP_FILIAL,
       ANTERIOR.NOME_RESP_FILIAL                   AS ANT_NOME_RESP_FILIAL,

       ANTERIOR.NOME_EMPRESA                       AS ANT_NOME_EMPRESA,
       ANTERIOR.NOME_FILIAL                        AS ANT_NOME_FILIAL,
       ANTERIOR.NOME_NIVEL4                        AS ANT_NOME_NIVEL4,
       ANTERIOR.NOME_NIVEL5                        AS ANT_NOME_NIVEL5,
       ANTERIOR.NOME_NIVEL6                        AS ANT_NOME_NIVEL6,
       ANTERIOR.NOME_NIVEL7                        AS ANT_NOME_NIVEL7,
       ANTERIOR.NOME_NIVEL8                        AS ANT_NOME_NIVEL8,

       ANTERIOR.LOGRADOURO_EMPRESA                 AS ANT_LOGRADOURO_EMPRESA,
       ANTERIOR.NUMERO_EMPRESA                     AS ANT_NUMERO_EMPRESA,
       ANTERIOR.COMPLEMENTO_EMPRESA                AS ANT_COMPLEMENTO_EMPRESA,
       ANTERIOR.BAIRRO_EMPRESA                     AS ANT_BAIRRO_EMPRESA,
       ANTERIOR.MUNICIPIO_EMPRESA                  AS ANT_MUNICIPIO_EMPRESA,
       ANTERIOR.CEP_EMPRESA                        AS ANT_CEP_EMPRESA,
       ANTERIOR.UF_EMPRESA                         AS ANT_UF_EMPRESA,
       ANTERIOR.CGC_EMPRESA                        AS ANT_CGC_EMPRESA,
       ANTERIOR.TIPO_LOG_EMPRESA                   AS ANT_TIPO_LOG_EMPRESA,

       ANTERIOR.LOGRADOURO_FILIAL                  AS ANT_LOGRADOURO_FILIAL,
       ANTERIOR.NUMERO_FILIAL                      AS ANT_NUMERO_FILIAL,
       ANTERIOR.COMPLEMENTO_FILIAL                 AS ANT_COMPLEMENTO_FILIAL,
       ANTERIOR.BAIRRO_FILIAL                      AS ANT_BAIRRO_FILIAL,
       ANTERIOR.MUNICIPIO_FILIAL                   AS ANT_MUNICIPIO_FILIAL,
       ANTERIOR.CEP_FILIAL                         AS ANT_CEP_FILIAL,
       ANTERIOR.UF_FILIAL                          AS ANT_UF_FILIAL,
       ANTERIOR.CGC_FILIAL                         AS ANT_CGC_FILIAL,
       ANTERIOR.TIPO_LOG_FILIAL                    AS ANT_TIPO_LOG_FILIAL,

       ANTERIOR.LOGRADOURO_NIVEL4                  AS ANT_LOGRADOURO_NIVEL4,
       ANTERIOR.NUMERO_NIVEL4                      AS ANT_NUMERO_NIVEL4,
       ANTERIOR.COMPLEMENTO_NIVEL4                 AS ANT_COMPLEMENTO_NIVEL4,
       ANTERIOR.BAIRRO_NIVEL4                      AS ANT_BAIRRO_NIVEL4,
       ANTERIOR.MUNICIPIO_NIVEL4                   AS ANT_MUNICIPIO_NIVEL4,
       ANTERIOR.CEP_NIVEL4                         AS ANT_CEP_NIVEL4,
       ANTERIOR.UF_NIVEL4                          AS ANT_UF_NIVEL4,
       ANTERIOR.CGC_NIVEL4                         AS ANT_CGC_NIVEL4,
       ANTERIOR.TIPO_LOG_NIVEL4                    AS ANT_TIPO_LOG_NIVEL4,

       ANTERIOR.LOGRADOURO_NIVEL5                  AS ANT_LOGRADOURO_NIVEL5,
       ANTERIOR.NUMERO_NIVEL5                      AS ANT_NUMERO_NIVEL5,
       ANTERIOR.COMPLEMENTO_NIVEL5                 AS ANT_COMPLEMENTO_NIVEL5,
       ANTERIOR.BAIRRO_NIVEL5                      AS ANT_BAIRRO_NIVEL5,
       ANTERIOR.MUNICIPIO_NIVEL5                   AS ANT_MUNICIPIO_NIVEL5,
       ANTERIOR.CEP_NIVEL5                         AS ANT_CEP_NIVEL5,
       ANTERIOR.UF_NIVEL5                          AS ANT_UF_NIVEL5,
       ANTERIOR.CGC_NIVEL5                         AS ANT_CGC_NIVEL5,
       ANTERIOR.TIPO_LOG_NIVEL5                    AS ANT_TIPO_LOG_NIVEL5,

       ANTERIOR.ESTEMP_BANCO_DEBITO                AS ANT_ESTEMP_BANCO_DEBITO,
       ANTERIOR.ESTEMP_CODAGE_DEBITO               AS ANT_ESTEMP_CODAGE_DEBITO,
       ANTERIOR.ESTEMP_DIGAGE_DEBITO               AS ANT_ESTEMP_DIGAGE_DEBITO,
       ANTERIOR.ESTEMP_CONTA_DEBITO                AS ANT_ESTEMP_CONTA_DEBITO,
       ANTERIOR.ESTEMP_TIPO_INSCRICAO              AS ANT_ESTEMP_TIPO_INSCRICAO,
       ANTERIOR.ESTEMP_CPF                         AS ANT_ESTEMP_CPF,
       ANTERIOR.ESTEMP_COD_CEI                     AS ANT_ESTEMP_COD_CEI,
       ANTERIOR.ESTEMP_CNPJ                        AS ANT_ESTEMP_CNPJ,

       ANTERIOR.ESTFIL_BANCO_DEBITO                AS ANT_ESTFIL_BANCO_DEBITO,
       ANTERIOR.ESTFIL_CODAGE_DEBITO               AS ANT_ESTFIL_CODAGE_DEBITO,
       ANTERIOR.ESTFIL_DIGAGE_DEBITO               AS ANT_ESTFIL_DIGAGE_DEBITO,
       ANTERIOR.ESTFIL_CONTA_DEBITO                AS ANT_ESTFIL_CONTA_DEBITO,
       ANTERIOR.ESTFIL_TIPO_INSCRICAO              AS ANT_ESTFIL_TIPO_INSCRICAO,
       ANTERIOR.ESTFIL_CPF                         AS ANT_ESTFIL_CPF,
       ANTERIOR.ESTFIL_COD_CEI                     AS ANT_ESTFIL_COD_CEI,
       ANTERIOR.ESTFIL_CNPJ                        AS ANT_ESTFIL_CNPJ,

       ANTERIOR.ESTEMP_NOME_BANCO_DEBITO           AS ANT_ESTEMP_NOME_BANCO_DEBITO,
       ANTERIOR.ESTFIL_NOME_BANCO_DEBITO           AS ANT_ESTFIL_NOME_BANCO_DEBITO,
       ANTERIOR.ESTEMP_NOME_AGENCIA_DEBITO         AS ANT_ESTEMP_NOME_AGENCIA_DEBITO,
       ANTERIOR.ESTFIL_NOME_AGENCIA_DEBITO         AS ANT_ESTFIL_NOME_AGENCIA_DEBITO


  FROM RHFP0310 RHFP0310,
       RHFP0401 RHFP0401,
       RHFP0400 EMP400,
       RHFP0400 FIL400,
       RHFP0400 N4,
       RHFP0400 N5,
       RHFP0400 N6,
       RHFP0400 N7,
       RHFP0400 N8,

       PESSOA PESEMP,
       PESSOA PESFIL,
       PESSOA PESN04,
       PESSOA PESN05,
       PESSOA RESPEMP,
       PESSOA RESPFIL,

       LOGRA    LOGEMP,
       JURIDICA JUREMP,
       MUNICI   MUNEMP,
       BAIRRO   BAIEMP,

       LOGRA    LOGFIL,
       JURIDICA JURFIL,
       MUNICI   MUNFIL,
       BAIRRO   BAIFIL,

       LOGRA    LOGN4,
       JURIDICA JURN4,
       MUNICI   MUNN4,
       BAIRRO   BAIN4,

       LOGRA    LOGN5,
       JURIDICA JURN5,
       MUNICI   MUNN5,
       BAIRRO   BAIN5,

       RHFP0430 R430EMP,
       RHFP0430 R430FIL,

       BANCO BANEMP,
       AGENCIA AGEEMP,
       BANCO BANFIL,
       AGENCIA AGEFIL,

       PESSOA PESBANEMP,
       PESSOA PESBANFIL,
       PESSOA PESAGEEMP,
       PESSOA PESAGEFIL,
       RHFP0323 RHFP0323,
(
SELECT
       RHFP0310.COD_CONTRATO,
       RHFP0310.DATA_INICIO,
       RHFP0310.DATA_FIM,
       RHFP0310.COD_MOTIVO,
       RHFP0323.NOME_MOTIVO,
       RHFP0401.COD_NIVEL2 AS COD_EMPRESA,
        RHFP0401.COD_NIVEL3 AS COD_FILIAL,
        RHFP0401.COD_NIVEL4,
        RHFP0401.COD_NIVEL5,
        RHFP0401.COD_NIVEL6,
        RHFP0401.COD_NIVEL7,
        RHFP0401.COD_NIVEL8,
       (RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMSEMP_NIVEL4,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5) AS EDICAO_COMSEMP_NIVEL5,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6) AS EDICAO_COMSEMP_NIVEL6,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7) AS EDICAO_COMSEMP_NIVEL7,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7||'.'||RHFP0401.EDICAO_NIVEL8) AS EDICAO_COMSEMP_NIVEL8,
       RHFP0401.EDICAO_NIVEL2 AS EDICAO_COMPOSTA_EMPRESA,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3) AS EDICAO_COMPOSTA_FILIAL,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMPOSTA_NIVEL4,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5) AS EDICAO_COMPOSTA_NIVEL5,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6) AS EDICAO_COMPOSTA_NIVEL6,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7) AS EDICAO_COMPOSTA_NIVEL7,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7||'.'||RHFP0401.EDICAO_NIVEL8) AS EDICAO_COMPOSTA_NIVEL8,
       RHFP0401.EDICAO_NIVEL2 AS EDICAO_EMPRESA,
        RHFP0401.EDICAO_NIVEL3 AS EDICAO_FILIAL,
        RHFP0401.EDICAO_NIVEL4,
        RHFP0401.EDICAO_NIVEL5,
        RHFP0401.EDICAO_NIVEL6,
        RHFP0401.EDICAO_NIVEL7,
        RHFP0401.EDICAO_NIVEL8,

       PESEMP.COD_PESSOA   AS COD_PESSOA_EMPRESA,
       PESFIL.COD_PESSOA   AS COD_PESSOA_FILIAL,
       PESN04.COD_PESSOA   AS COD_PESSOA_NIVEL4,
       PESN05.COD_PESSOA   AS COD_PESSOA_NIVEL5,
       PESEMP.NOME_PESSOA  AS RAZAO_SOCIAL_EMPRESA,
       PESFIL.NOME_PESSOA  AS RAZAO_SOCIAL_FILIAL,
       PESN04.NOME_PESSOA  AS RAZAO_SOCIAL_NIVEL4,
       PESN05.NOME_PESSOA  AS RAZAO_SOCIAL_NIVEL5,

       EMP400.NOME_ORGANOGRAMA  AS NOME_EMPRESA,
       FIL400.NOME_ORGANOGRAMA  AS NOME_FILIAL,
       N4.NOME_ORGANOGRAMA      AS NOME_NIVEL4,
       N5.NOME_ORGANOGRAMA      AS NOME_NIVEL5,
       N6.NOME_ORGANOGRAMA      AS NOME_NIVEL6,
       N7.NOME_ORGANOGRAMA      AS NOME_NIVEL7,
       N8.NOME_ORGANOGRAMA      AS NOME_NIVEL8,

       RESPEMP.COD_PESSOA AS COD_RESP_EMPRESA,
       RESPEMP.NOME_PESSOA AS NOME_RESP_EMPRESA,
       RESPFIL.COD_PESSOA AS COD_RESP_FILIAL,
       RESPFIL.NOME_PESSOA AS NOME_RESP_FILIAL,

       LOGEMP.NOME_LOGRA     AS LOGRADOURO_EMPRESA,
       JUREMP.NUMERO         AS NUMERO_EMPRESA,
       JUREMP.COMPLEMENTO    AS COMPLEMENTO_EMPRESA,
       BAIEMP.NOME_BAIRRO    AS BAIRRO_EMPRESA,
       MUNEMP.NOME_MUNIC     AS MUNICIPIO_EMPRESA,
       JUREMP.CEP            AS CEP_EMPRESA,
       JUREMP.COD_UF         AS UF_EMPRESA,
       JUREMP.CGC            AS CGC_EMPRESA,
       JUREMP.TIP_LOGRA      AS TIPO_LOG_EMPRESA,

       LOGFIL.NOME_LOGRA     AS LOGRADOURO_FILIAL,
       JURFIL.NUMERO         AS NUMERO_FILIAL,
       JURFIL.COMPLEMENTO    AS COMPLEMENTO_FILIAL,
       BAIFIL.NOME_BAIRRO    AS BAIRRO_FILIAL,
       MUNFIL.NOME_MUNIC     AS MUNICIPIO_FILIAL,
       JURFIL.CEP            AS CEP_FILIAL,
       JURFIL.COD_UF         AS UF_FILIAL,
       JURFIL.CGC            AS CGC_FILIAL,
       JURFIL.TIP_LOGRA      AS TIPO_LOG_FILIAL,

       LOGN4.NOME_LOGRA     AS LOGRADOURO_NIVEL4,
       JURN4.NUMERO         AS NUMERO_NIVEL4,
       JURN4.COMPLEMENTO    AS COMPLEMENTO_NIVEL4,
       BAIN4.NOME_BAIRRO    AS BAIRRO_NIVEL4,
       MUNN4.NOME_MUNIC     AS MUNICIPIO_NIVEL4,
       JURN4.CEP            AS CEP_NIVEL4,
       JURN4.COD_UF         AS UF_NIVEL4,
       JURN4.CGC            AS CGC_NIVEL4,
       JURN4.TIP_LOGRA      AS TIPO_LOG_NIVEL4,

       LOGN5.NOME_LOGRA     AS LOGRADOURO_NIVEL5,
       JURN5.NUMERO         AS NUMERO_NIVEL5,
       JURN5.COMPLEMENTO    AS COMPLEMENTO_NIVEL5,
       BAIN5.NOME_BAIRRO    AS BAIRRO_NIVEL5,
       MUNN5.NOME_MUNIC     AS MUNICIPIO_NIVEL5,
       JURN5.CEP            AS CEP_NIVEL5,
       JURN5.COD_UF         AS UF_NIVEL5,
       JURN5.CGC            AS CGC_NIVEL5,
       JURN5.TIP_LOGRA      AS TIPO_LOG_NIVEL5,

       R430EMP.BANCO_DEBITO   AS ESTEMP_BANCO_DEBITO,
       R430EMP.CODAGE_DEBITO  AS ESTEMP_CODAGE_DEBITO,
       R430EMP.DIGAGE_DEBITO  AS ESTEMP_DIGAGE_DEBITO,
       R430EMP.CONTA_DEBITO   AS ESTEMP_CONTA_DEBITO,
       R430EMP.TIPO_INSCRICAO AS ESTEMP_TIPO_INSCRICAO,
       R430EMP.CPF            AS ESTEMP_CPF,
       R430EMP.COD_CEI        AS ESTEMP_COD_CEI,
       JUREMP.CGC             AS ESTEMP_CNPJ,

       R430FIL.BANCO_DEBITO   AS ESTFIL_BANCO_DEBITO,
       R430FIL.CODAGE_DEBITO  AS ESTFIL_CODAGE_DEBITO,
       R430FIL.DIGAGE_DEBITO  AS ESTFIL_DIGAGE_DEBITO,
       R430FIL.CONTA_DEBITO   AS ESTFIL_CONTA_DEBITO,
       R430FIL.TIPO_INSCRICAO AS ESTFIL_TIPO_INSCRICAO,
       R430FIL.CPF            AS ESTFIL_CPF,
       R430FIL.COD_CEI        AS ESTFIL_COD_CEI,
       JURFIL.CGC             AS ESTFIL_CNPJ,

       PESBANEMP.NOME_PESSOA AS ESTEMP_NOME_BANCO_DEBITO,
       PESBANFIL.NOME_PESSOA AS ESTFIL_NOME_BANCO_DEBITO,
       PESAGEEMP.NOME_PESSOA AS ESTEMP_NOME_AGENCIA_DEBITO,
       PESAGEFIL.NOME_PESSOA AS ESTFIL_NOME_AGENCIA_DEBITO

  FROM RHFP0310 RHFP0310,
       RHFP0401 RHFP0401,

       RHFP0400 EMP400,
       RHFP0400 FIL400,
       RHFP0400 N4,
       RHFP0400 N5,
       RHFP0400 N6,
       RHFP0400 N7,
       RHFP0400 N8,

       LOGRA    LOGEMP,
       JURIDICA JUREMP,
       MUNICI   MUNEMP,
       BAIRRO   BAIEMP,

       LOGRA    LOGFIL,
       JURIDICA JURFIL,
       MUNICI   MUNFIL,
       BAIRRO   BAIFIL,

       LOGRA    LOGN4,
       JURIDICA JURN4,
       MUNICI   MUNN4,
       BAIRRO   BAIN4,

       LOGRA    LOGN5,
       JURIDICA JURN5,
       MUNICI   MUNN5,
       BAIRRO   BAIN5,

       RHFP0430 R430EMP,
       RHFP0430 R430FIL,

       BANCO BANEMP,
       AGENCIA AGEEMP,
       BANCO BANFIL,
       AGENCIA AGEFIL,

       PESSOA PESBANEMP,
       PESSOA PESBANFIL,
       PESSOA PESAGEEMP,
       PESSOA PESAGEFIL,

       PESSOA PESEMP,
       PESSOA PESFIL,
       PESSOA PESN04,
       PESSOA PESN05,
       PESSOA RESPEMP,
       PESSOA RESPFIL,

       RHFP0323 RHFP0323

 WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA
   AND RHFP0310.DATA_INICIO BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
   AND RHFP0401.COD_NIVEL2 = R430EMP.COD_ESTABELECIMENTO(+)
   AND RHFP0401.COD_NIVEL3 = R430FIL.COD_ESTABELECIMENTO(+)

   AND R430EMP.BANCO_DEBITO = BANEMP.COD_BANCO(+)
   AND R430FIL.BANCO_DEBITO = BANFIL.COD_BANCO(+)
   AND R430EMP.BANCO_DEBITO = AGEEMP.COD_BANCO(+)
   AND R430EMP.CODAGE_DEBITO = AGEEMP.COD_AGENCIA(+)
   AND R430FIL.BANCO_DEBITO = AGEFIL.COD_BANCO(+)
   AND R430FIL.CODAGE_DEBITO = AGEFIL.COD_AGENCIA(+)

   AND R430EMP.COD_RESPONSAVEL = RESPEMP.COD_PESSOA(+)
   AND R430FIL.COD_RESPONSAVEL = RESPFIL.COD_PESSOA(+)

   AND BANEMP.COD_PESSOA = PESBANEMP.COD_PESSOA(+)
   AND BANFIL.COD_PESSOA = PESBANFIL.COD_PESSOA(+)
   AND AGEEMP.COD_PESSOA = PESAGEEMP.COD_PESSOA(+)
   AND AGEFIL.COD_PESSOA = PESAGEFIL.COD_PESSOA(+)

   AND RHFP0401.COD_NIVEL2 = EMP400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL3 = FIL400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL4 = N4.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL5 = N5.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL6 = N6.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL7 = N7.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL8 = N8.COD_ORGANOGRAMA(+)

   AND EMP400.COD_PESSOA = PESEMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = PESFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA     = PESN04.COD_PESSOA(+)
   AND N5.COD_PESSOA     = PESN05.COD_PESSOA(+)

   AND EMP400.COD_PESSOA = JUREMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = JURFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA     = JURN4.COD_PESSOA(+)
   AND N5.COD_PESSOA     = JURN5.COD_PESSOA(+)

   AND JUREMP.COD_LOGRA = LOGEMP.COD_LOGRA(+)
   AND JUREMP.COD_MUNIC = LOGEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF    = LOGEMP.COD_UF(+)
   AND JUREMP.COD_MUNIC = MUNEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF    = MUNEMP.COD_UF(+)
   AND JUREMP.COD_BAIRRO = BAIEMP.COD_BAIRRO(+)
   AND JUREMP.COD_MUNIC  = BAIEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF     = BAIEMP.COD_UF(+)

   AND JURFIL.COD_LOGRA = LOGFIL.COD_LOGRA(+)
   AND JURFIL.COD_MUNIC = LOGFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF    = LOGFIL.COD_UF(+)
   AND JURFIL.COD_MUNIC = MUNFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF    = MUNFIL.COD_UF(+)
   AND JURFIL.COD_BAIRRO = BAIFIL.COD_BAIRRO(+)
   AND JURFIL.COD_MUNIC  = BAIFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF     = BAIFIL.COD_UF(+)

   AND JURN4.COD_LOGRA  = LOGN4.COD_LOGRA(+)
   AND JURN4.COD_MUNIC  = LOGN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = LOGN4.COD_UF(+)
   AND JURN4.COD_MUNIC  = MUNN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = MUNN4.COD_UF(+)
   AND JURN4.COD_BAIRRO = BAIN4.COD_BAIRRO(+)
   AND JURN4.COD_MUNIC  = BAIN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = BAIN4.COD_UF(+)

   AND JURN5.COD_LOGRA  = LOGN5.COD_LOGRA(+)
   AND JURN5.COD_MUNIC  = LOGN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = LOGN5.COD_UF(+)
   AND JURN5.COD_MUNIC  = MUNN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = MUNN5.COD_UF(+)
   AND JURN5.COD_BAIRRO = BAIN5.COD_BAIRRO(+)
   AND JURN5.COD_MUNIC  = BAIN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = BAIN5.COD_UF(+)

   AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
) ANTERIOR

 WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA
   AND trunc(sysdate) BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
   AND trunc(sysdate) BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM

   AND RHFP0401.COD_NIVEL2 = R430EMP.COD_ESTABELECIMENTO(+)
   AND RHFP0401.COD_NIVEL3 = R430FIL.COD_ESTABELECIMENTO(+)
   AND R430EMP.BANCO_DEBITO = BANEMP.COD_BANCO(+)
   AND R430FIL.BANCO_DEBITO = BANFIL.COD_BANCO(+)
   AND R430EMP.BANCO_DEBITO = AGEEMP.COD_BANCO(+)
   AND R430EMP.CODAGE_DEBITO = AGEEMP.COD_AGENCIA(+)
   AND R430FIL.BANCO_DEBITO = AGEFIL.COD_BANCO(+)
   AND R430FIL.CODAGE_DEBITO = AGEFIL.COD_AGENCIA(+)

   AND EMP400.COD_PESSOA = PESEMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = PESFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA     = PESN04.COD_PESSOA(+)
   AND N5.COD_PESSOA     = PESN05.COD_PESSOA(+)

   AND R430EMP.COD_RESPONSAVEL = RESPEMP.COD_PESSOA(+)
   AND R430FIL.COD_RESPONSAVEL = RESPFIL.COD_PESSOA(+)

   AND BANEMP.COD_PESSOA = PESBANEMP.COD_PESSOA(+)
   AND BANFIL.COD_PESSOA = PESBANFIL.COD_PESSOA(+)
   AND AGEEMP.COD_PESSOA = PESAGEEMP.COD_PESSOA(+)
   AND AGEFIL.COD_PESSOA = PESAGEFIL.COD_PESSOA(+)

   AND RHFP0401.COD_NIVEL2 = EMP400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL3 = FIL400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL4 = N4.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL5 = N5.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL6 = N6.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL7 = N7.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL8 = N8.COD_ORGANOGRAMA(+)

   AND EMP400.COD_PESSOA = JUREMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = JURFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA = JURN4.COD_PESSOA(+)
   AND N5.COD_PESSOA = JURN5.COD_PESSOA(+)

   AND JUREMP.COD_LOGRA = LOGEMP.COD_LOGRA(+)
   AND JUREMP.COD_MUNIC = LOGEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF    = LOGEMP.COD_UF(+)
   AND JUREMP.COD_MUNIC = MUNEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF    = MUNEMP.COD_UF(+)
   AND JUREMP.COD_BAIRRO = BAIEMP.COD_BAIRRO(+)
   AND JUREMP.COD_MUNIC  = BAIEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF     = BAIEMP.COD_UF(+)

   AND JURFIL.COD_LOGRA = LOGFIL.COD_LOGRA(+)
   AND JURFIL.COD_MUNIC = LOGFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF    = LOGFIL.COD_UF(+)
   AND JURFIL.COD_MUNIC = MUNFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF    = MUNFIL.COD_UF(+)
   AND JURFIL.COD_BAIRRO = BAIFIL.COD_BAIRRO(+)
   AND JURFIL.COD_MUNIC  = BAIFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF     = BAIFIL.COD_UF(+)

   AND JURN4.COD_LOGRA  = LOGN4.COD_LOGRA(+)
   AND JURN4.COD_MUNIC  = LOGN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = LOGN4.COD_UF(+)
   AND JURN4.COD_MUNIC  = MUNN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = MUNN4.COD_UF(+)
   AND JURN4.COD_BAIRRO = BAIN4.COD_BAIRRO(+)
   AND JURN4.COD_MUNIC  = BAIN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = BAIN4.COD_UF(+)

   AND JURN5.COD_LOGRA  = LOGN5.COD_LOGRA(+)
   AND JURN5.COD_MUNIC  = LOGN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = LOGN5.COD_UF(+)
   AND JURN5.COD_MUNIC  = MUNN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = MUNN5.COD_UF(+)
   AND JURN5.COD_BAIRRO = BAIN5.COD_BAIRRO(+)
   AND JURN5.COD_MUNIC  = BAIN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = BAIN5.COD_UF(+)

   AND RHFP0310.COD_CONTRATO = ANTERIOR.COD_CONTRATO(+)
   AND RHFP0310.DATA_INICIO -1 = ANTERIOR.DATA_FIM(+)
   AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
 ) CON_EMP
Where RHFP0300.COD_CONTRATO = CON_RES.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_TURNOS.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_EMP.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_HORBAS.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_FER_PER.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_ORG.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_USU_HOR.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_STACON.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_CON.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_FUN.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_CLH.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_STAAFA.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_CUSTO.COD_CONTRATO(+)
 AND (
 CON_CON.COD_CONTRATO NOT IN (100000,100022,366951,366960,373486,319724,299634,299618,364908,365467,364916,365475,374159,373907,373460,364932)
 OR CON_CON.DATA_FIM >=  TO_DATE('01/01/2002','DD/MM/YYYY')
 AND CON_CON.COD_CONTRATO NOT IN (364908,365467,364916,365475,374159,373907,364924,364932,373460,376409)
 AND CON_STACON.STATUS_CONTRATO = 0
 )
AND ( RHFP0300.COD_CONTRATO IN (SELECT COD_CONTRATO FROM RHFP0300 WHERE COD_CONTRATO > 00000) )
Order by CON_EMP.EDICAO_FILIAL ASC
 , CON_CON.COD_CONTRATO ASC

