/*VIEW CRIADA PARA SER DINÂMICA ONDE RETORNA TODA A ESTRUTURA DO ORGANOGRAMA DA EMPRESA COM BASE NA DATA ATUAL*/
CREATE OR REPLACE VIEW V_EST_ORG_AVT AS
SELECT A.COD_ORGANOGRAMA,
       B.NOME_ORGANOGRAMA,       
       A.COD_ORGANOGRAMA || ' - ' || B.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA_A,
       A.EDICAO_ORG || ' - ' || B.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA_B,
       A.COD_ORGANOGRAMA_SUB,
       A.EDICAO_ORG,
       SUBSTR(RHYF0002(B.COD_ORGANOGRAMA, B.COD_NIVEL_ORG, TRUNC(SYSDATE)),1,80) AS EDICAO,
       A.EDICAO_NIVEL1 AS EDI1,
       A.EDICAO_NIVEL2 AS EDI2,
       A.EDICAO_NIVEL3 AS EDI3,
       A.EDICAO_NIVEL4 AS EDI4,
       A.EDICAO_NIVEL5 AS EDI5,
       A.EDICAO_NIVEL6 AS EDI6,
       A.EDICAO_NIVEL7 AS EDI7,
       A.EDICAO_NIVEL8 AS EDI8,
       A.COD_NIVEL1 AS COD1,
       A.COD_NIVEL2 AS COD2,
       A.COD_NIVEL3 AS COD3,
       A.COD_NIVEL4 AS COD4,
       A.COD_NIVEL5 AS COD5,
       A.COD_NIVEL6 AS COD6,
       A.COD_NIVEL7 AS COD7,
       A.COD_NIVEL8 AS COD8,
       B1.NOME_ORGANOGRAMA AS NOME1,
       B2.NOME_ORGANOGRAMA AS NOME2,
       B3.NOME_ORGANOGRAMA AS NOME3,
       B4.NOME_ORGANOGRAMA AS NOME4,
       B5.NOME_ORGANOGRAMA AS NOME5,
       B6.NOME_ORGANOGRAMA AS NOME6,
       B7.NOME_ORGANOGRAMA AS NOME7,
       B8.NOME_ORGANOGRAMA AS NOME8,
       0 AS IND_SEL
FROM RHFP0401 A,
     RHFP0400 B1,
     RHFP0400 B2,
     RHFP0400 B3,
     RHFP0400 B4,
     RHFP0400 B5,
     RHFP0400 B6,
     RHFP0400 B7,
     RHFP0400 B8,
     RHFP0400 B
 WHERE A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
   AND A.COD_NIVEL1 = B1.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL2 = B2.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL3 = B3.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL4 = B4.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL5 = B5.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL6 = B6.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL7 = B7.COD_ORGANOGRAMA(+)
   AND A.COD_NIVEL8 = B8.COD_ORGANOGRAMA(+)
   AND TRUNC(SYSDATE) BETWEEN A.DATA_INICIO AND A.DATA_FIM
 ORDER BY A.COD_ORGANOGRAMA ASC;