/*VIEW V_COLABORADORES DO TIAGO ORIGINAL*/


CREATE OR REPLACE VIEW V_COLABORADORES AS
SELECT 
    RHFP0300.COD_CONTRATO COD_FUNCIONARIO,
    ORG_EMP.EDICAO_ORG COD_CENTRO_CUSTO,
    INITCAP(P.NOME_PESSOA) DES_NOME,
    TO_CHAR(RHFP0300.DATA_INICIO, 'DD/MM/YYYY') DTA_ADMISSAO,
    TO_CHAR(RHFP0300.DATA_FIM, 'DD/MM/YYYY') DTA_DEMISSAO,
    TO_CHAR(RHFP0200.DATA_NASCIMENTO, 'DD/MM/YYYY') DATA_NASCIMENTO,
    CONTR_ORGANOGRAMA.COD_ORGANOGRAMA, 
    CONTR_ORGANOGRAMA.COD_NIVEL2 COD_EMPRESA,
    CASE
        WHEN CONTR_ORGANOGRAMA.COD_NIVEL2 = 8 THEN 'GRAZZIOTIN'
        WHEN CONTR_ORGANOGRAMA.COD_NIVEL2 = 4 THEN 'MUNDIART'
        WHEN CONTR_ORGANOGRAMA.COD_NIVEL2 = 276 THEN 'CENTRO SHOPPING'
        WHEN CONTR_ORGANOGRAMA.COD_NIVEL2 = 280 THEN 'CAULESPAR'
        WHEN CONTR_ORGANOGRAMA.COD_NIVEL2 = 282 THEN 'FINANCIADORA'
        WHEN CONTR_ORGANOGRAMA.COD_NIVEL2 = 2 THEN 'VR'
        WHEN CONTR_ORGANOGRAMA.COD_NIVEL2 = 6 THEN 'GRATO'
        ELSE 'GRAZZIOTIN'
    END DES_EMPRESA,
    FUNCOES.COD_CLH COD_FUNCAO,
    TURNO.COD_TURNO,
    TRIM(TO_CHAR(HORAS2.QTD_HORBAS_MES, '999')) QTD_CH_MENSAL,
    TRIM(RHFP0200.NRO_CTPS) NUM_CART_TRAB,
    TRIM(RHFP0200.NRO_SERIE_CTPS) NUM_SERIE_CART_TRAB,
    NVL(AFASTAMENTO.COD_CAUSA_AFAST, 0) COD_AFASTAMENTO,
    AFASTAMENTO.DATA_INICIO DATA_AFASTAMENTO_INI,
    AFASTAMENTO.DATA_FIM DATA_AFASTAMENTO_FIM,
    TRIM(FIS.CPF) CPF,
    FIS.sexo,
    FUNCOES.NOME_CLH CARGO, 
    INITCAP(MUN.NOME_MUNIC) DES_MUNIC,
    CASE
        WHEN FUNCOES.COD_CLH = 325 THEN RHFP0300.COD_CONTRATO || '@grupograzziotin.com.br'
        ELSE RHFP0300.COD_CONTRATO || '@grazziotin.com.br'
    END EMAIL,
    CASE
        WHEN ((UPPER(FUNCOES.NOME_CLH) LIKE '%GERENTE%') OR
              (UPPER(FUNCOES.NOME_CLH) LIKE '%SUPERVISOR%') OR
              (UPPER(FUNCOES.NOME_CLH) LIKE '%DIRETOR%')) THEN 1
        ELSE 0
    END IND_GESTOR,
    OH.CODNIV_1,
    OH.CODNIV_2,
    OH.CODNIV_3,
    OH.CODNIV_4,
    OH.CODNIV_5,
    OH.CODNIV_6,
    OH.CODNIV_7,
    OH.CODNIV_8
FROM RHFP0300
INNER JOIN RHFP0200 ON RHFP0200.COD_FUNC = RHFP0300.COD_FUNC
INNER JOIN PESSOA P ON P.COD_PESSOA = RHFP0200.COD_FUNC
INNER JOIN FISICA FIS ON FIS.COD_PESSOA = RHFP0200.COD_FUNC
INNER JOIN MUNICI MUN ON MUN.COD_MUNIC = FIS.COD_MUNIC
LEFT JOIN RHFP0310 CONTR_ORGANOGRAMA ON RHFP0300.COD_CONTRATO = CONTR_ORGANOGRAMA.COD_CONTRATO
    AND TRUNC(SYSDATE) BETWEEN CONTR_ORGANOGRAMA.DATA_INICIO AND NVL(CONTR_ORGANOGRAMA.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
LEFT JOIN RHFP0400 ORGANOGRAMA ON CONTR_ORGANOGRAMA.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
LEFT JOIN RHFP0401 ORG_EMP ON ORGANOGRAMA.COD_ORGANOGRAMA = ORG_EMP.COD_ORGANOGRAMA
    AND TRUNC(SYSDATE) BETWEEN ORG_EMP.DATA_INICIO AND NVL(ORG_EMP.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
LEFT JOIN RHFP0340 CONTRFUNC ON RHFP0300.COD_CONTRATO = CONTRFUNC.COD_CONTRATO
    AND TRUNC(SYSDATE) BETWEEN CONTRFUNC.DATA_INICIO AND NVL(CONTRFUNC.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
LEFT JOIN RHFP0500 FUNCOES ON FUNCOES.COD_CLH = CONTRFUNC.COD_CLH
LEFT JOIN RHAF1119 TURNO ON RHFP0300.COD_CONTRATO = TURNO.COD_CONTRATO
    AND TRUNC(SYSDATE) BETWEEN TURNO.DATA_INICIO AND TURNO.DATA_FIM
LEFT JOIN RHFP0307 HORAS ON RHFP0300.COD_CONTRATO = HORAS.COD_CONTRATO
    AND TRUNC(SYSDATE) BETWEEN HORAS.DATA_INICIO AND HORAS.DATA_FIM
LEFT JOIN RHFP0321 HORAS2 ON HORAS.COD_HORAS_BASE = HORAS2.COD_HORAS_BASE
LEFT JOIN RHFP0402 ORG_CUSTO_CTB ON ORGANOGRAMA.COD_CUSTO_CONTABIL = ORG_CUSTO_CTB.COD_CUSTO_CONTABIL
LEFT JOIN RHFP0306 AFASTAMENTO ON RHFP0300.COD_CONTRATO = AFASTAMENTO.COD_CONTRATO
    AND TRUNC(SYSDATE) BETWEEN AFASTAMENTO.DATA_INICIO AND AFASTAMENTO.DATA_FIM
LEFT JOIN TABLE(CAST(GET_ORG_HIERARCHY(CONTR_ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA.COD_NIVEL_ORG) AS ORG_HIERARCHY_TABLE)) OH ON 1 = 1
WHERE RHFP0200.NRO_SERIE_CTPS IS NOT NULL
  AND RHFP0200.NRO_CTPS IS NOT NULL
  AND FIS.CPF IS NOT NULL
  AND (RHFP0300.DATA_FIM IS NULL
       AND TRUNC(SYSDATE) BETWEEN RHFP0300.DATA_INICIO AND NVL(RHFP0300.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
       OR RHFP0300.DATA_FIM >= TRUNC(SYSDATE) - 15)
ORDER BY NVL2(ORG_CUSTO_CTB.CUSTO_CONTABIL, ORG_EMP.EDICAO_ORG, '001')