--VIEW V_LOJAS_ATIVAS --TESTANDO


--A PRINCIPIRO PRIMEIRAS TABELAS PARA USAR NA VIEW

SELECT * FROM JURIDICA
SELECT * FROM RHFP0400;
SELECT * FROM RHFP0401;
SELECT * FROM RHFP0402;
SELECT * FROM RHFP0310;
SELECT * FROM RHFP0300;
SELECT * FROM RHFP0306;

--=======================================--

--SELECT TEST1

SELECT B.EDICAO_NIVEL3 AS FILIAL,
       F.NOME_ORGANOGRAMA,
       NVL(G.EDICAO_NIVEL3, 0) COD_GRUPO,
       NVL(DECODE(G.EDICAO_NIVEL3,1,'GRAZZIOTIN',2,'TOTTAL',3,'PORMENOS',4,'FRANCO GIORGI',7,'GZT STORE'), 'N/A') DES_GRUPO,
       DECODE(D.COD_SEQ_JORNADA,
              1,'DOMINGO',
              2,'SEGUNDA',
              3,'TERÇA',
              4,'QUARTA',
              5,'QUINTA',
              6,'SEXTA',
              7,'SABADO') AS DIA,
       D.COD_SEQ_JORNADA,
       E.HORA_ENT,
       E.HORA_SAI,
       E.COD_SEQ_HORARIO,
       A.DATA_INICIO,
       A.DATA_FIM
FROM RHAF1149 A
JOIN RHFP0401 B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
JOIN RHAF1145 C ON A.COD_TURNO = C.COD_TURNO
JOIN RHAF1120 D ON A.COD_TURNO = D.COD_TURNO
JOIN RHAF1117 E ON E.COD_HORARIO = D.COD_HORARIO_1
JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
LEFT JOIN RHFP0402 G ON G.COD_CUSTO_CONTABIL = F.COD_CUSTO_CONTABIL
WHERE B.COD_ORGANOGRAMA_SUB = 8
AND E.COD_SEQ_HORARIO = 1
AND A.DATA_INICIO <= TRUNC(SYSDATE)
AND A.DATA_FIM >= TRUNC(SYSDATE)
ORDER BY B.EDICAO_NIVEL3, D.COD_SEQ_JORNADA


--==============================================--

--SELECT TEST2

SELECT A1.COD_ORGANOGRAMA,
       A1.EDICAO_ORG,
       A2.NOME_ORGANOGRAMA,
       NVL(A3.EDICAO_NIVEL3, 0) COD_GRUPO,
       NVL(DECODE(A3.EDICAO_NIVEL3,
                  1,
                  'GRAZZIOTIN',
                  2,
                  'TOTTAL',
                  3,
                  'PORMENOS',
                  4,
                  'FRANCO GIORGI',
                  7,
                  'GZT STORE',
                  8,
                  'ADMINISTRAÇÃO'),
           'N/A') DES_GRUPO,
       J1.CGC
  FROM RHFP0401 A1, RHFP0400 A2, RHFP0402 A3, JURIDICA J1, RHFP0310 B1, RHFP0300 B2, RHFP0306 B3
 WHERE A1.COD_ORGANOGRAMA = A2.COD_ORGANOGRAMA
   AND A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
   AND J1.COD_PESSOA = A2.COD_PESSOA
   AND B1.COD_ORGANOGRAMA = A2.COD_ORGANOGRAMA
   AND B2.COD_CONTRATO = B1.COD_CONTRATO
   --AND B1.COD_CONTRATO = B3.COD_CONTRATO
   AND A1.DATA_FIM = '31/12/2999'
   AND A1.COD_NIVEL2 = 8
   AND A1.EDICAO_NIVEL3 NOT IN ('001', '013')
   AND A3.EDICAO_NIVEL3 NOT IN ('5')
   AND B1.DATA_FIM = '31/12/2999'
   AND B2.DATA_FIM IS NULL
   --AND A1.EDICAO_ORG = 025
   --AND B3.COD_CAUSA_AFAST = 0
ORDER BY A1.EDICAO_ORG ASC


--==================================================--

--SELECT TEST3

SELECT J.COD_PESSOA, A1.COD_PESSOA, A1.NOME_ORGANOGRAMA, A2.EDICAO_ORG
FROM JURIDICA J, RHFP0400 A1, RHFP0401 A2, RHFP0402 A3
WHERE J.COD_PESSOA = A1.COD_PESSOA
AND A1.COD_ORGANOGRAMA = A2.COD_ORGANOGRAMA
AND A3.COD_CUSTO_CONTABIL = A1.COD_CUSTO_CONTABIL
AND A2.COD_ORGANOGRAMA_SUB = 8
AND A2.DATA_FIM = '31/12/2999'

