/*VIEW OFICIAL DE TODA A ESTRUTURA DO ORGANOGRAMA.
         SOMENTE ORGANOGRAMAS VIGENTES*/
        
        
SELECT ORG2.COD_NIVEL1,
       ORG2.COD_NIVEL2,
       ORG2.COD_NIVEL3,
       ORG2.COD_NIVEL4,
       ORG2.COD_NIVEL5,
       ORG2.COD_NIVEL6,
       ORG2.EDICAO_NIVEL1,
       ORG2.EDICAO_NIVEL2,
       ORG2.EDICAO_NIVEL3,
       ORG2.EDICAO_NIVEL4,
       ORG2.EDICAO_NIVEL5,
       ORG2.EDICAO_NIVEL6,
       ORG1.NOME_ORGANOGRAMA AS DES_ORGANOGRAMA       
FROM RHFP0400 ORG1
INNER JOIN RHFP0401 ORG2 ON ORG1.COD_ORGANOGRAMA = ORG2.COD_ORGANOGRAMA
INNER JOIN RHFP0402 ORG3 ON ORG1.COD_CUSTO_CONTABIL = ORG3.COD_CUSTO_CONTABIL
INNER JOIN RHFP0310 CT_ORG ON ORG1.COD_ORGANOGRAMA = CT_ORG.COD_ORGANOGRAMA
 LEFT JOIN NL.GE_GRUPOS_UNIDADES@NLGRZ GRUPO ON TO_NUMBER(ORG2.EDICAO_ORG) = GRUPO.COD_UNIDADE



--SELECT EXEMPLO
 
 
SELECT DISTINCT
       A.COD_UNIDADE,
       B.EDICAO_ORG, -- Mantém a coluna original no resultado
       B.COD_ORGANOGRAMA
FROM NL.GE_GRUPOS_UNIDADES@NLGRZ A 
INNER JOIN RHFP0401 B ON A.COD_UNIDADE = TO_NUMBER(B.EDICAO_ORG)
WHERE REGEXP_LIKE(B.EDICAO_ORG, '^\d+$') -- Garante que apenas números sejam convertidos
  AND B.EDICAO_ORG = '004'
  AND B.COD_ORGANOGRAMA = 12