CREATE OR REPLACE VIEW PESSOA_JURIDICA AS
SELECT JU.COD_PESSOA,
       P.NOME_PESSOA,
       JU.TIP_LOGRA,
       TIPLOG.NOME_TIP_LOGRA,
       LOGRA.COD_LOGRA,
       LOGRA.NOME_LOGRA,
       JU.NUMERO,
       JU.COMPLEMENTO,
       BA.COD_BAIRRO,
       BA.NOME_BAIRRO,
       IB.COD_IBGE,
       JU.COD_MUNIC,       
       MU.NOME_MUNIC,
       IB.NOME_MUNIC AS NOME_MUNIC_IBGE,       
       JU.REFERENCIA,       
       JU.CEP,
       JU.COD_UF,
       JU.CGC,
       JU.INSC_MUNIC,
       JU.INSC_EST,
       JU.COD_ATIV,
       JU.COD_NATURE,
       JU.CNAE2,
       JU.ESTABELECIMENTO,
       JU.CATEGORIA,
       JU.DDD,
       JU.FONE,
       JU.RAMAL,
       JU.EMAIL,
       JU.FANTASIA,
       JU.FAX,
       JU.FONE_ALTER,
       MU.COD_MUN_FED
FROM LOGRA LOGRA,
     TIPLOG TIPLOG,
     BAIRRO BA,
     MUNICI MU,
     PESSOA P,
     MUNIBGE IB,
     JURIDICA JU
WHERE P.COD_PESSOA = JU.COD_PESSOA
  AND P.TIPO_PESSOA = 'J'
  AND MU.COD_UF (+) = JU.COD_UF
  AND MU.COD_MUNIC(+) = JU.COD_MUNIC
  AND IB.COD_MUNIC(+) = MU.COD_MUNIC
  AND BA.COD_UF(+) = JU.COD_UF
  AND BA.COD_MUNIC(+) = JU.COD_MUNIC
  AND BA.COD_BAIRRO(+) = JU.COD_BAIRRO
  AND TIPLOG.TIP_LOGRA(+) = JU.TIP_LOGRA
  AND LOGRA.COD_UF(+) = JU.COD_UF
  AND LOGRA.COD_MUNIC(+) = JU.COD_MUNIC
  AND LOGRA.COD_LOGRA(+) = JU.COD_LOGRA;
