CREATE OR REPLACE VIEW V_DADOS_PESSOA_ALTER_AVT AS
SELECT /*DADOS DO CONTRATO*/
       DISTINCT
       FP03.COD_CONTRATO AS COD_CONTRATO,
       INITCAP(P.COD_PESSOA) AS COD_PESSOA,
       INITCAP(P.NOME_PESSOA) AS DES_PESSOA,
       INITCAP(SUBSTR(P.NOME_PESSOA, 1, INSTR(P.NOME_PESSOA, ' ') - 1)) AS DES_NOME,
       INITCAP(SUBSTR(P.NOME_PESSOA, INSTR(P.NOME_PESSOA, ' ') + 1, 50)) AS DES_SOBRENOME,
       FUNCOES.COD_CLH AS COD_FUNCAO,
       FUNCOES.NOME_CLH AS DES_FUNCAO,
       CONTRFUNC.DATA_INICIO AS DATA_INI_FUNCAO,
       CONTRFUNC.DATA_FIM AS DATA_FIM_FUNCAO,
       TO_CHAR(FP02.DATA_NASCIMENTO, 'ddmmyyyy') AS DATA_NASCIMENTO_OLD,
       SENHA.DES_SENHA AS DATA_NASCIMENTO,
       INITCAP(MUN.NOME_MUNIC) AS DES_MUNIC,
       DECODE(FIS.COD_UF, 'RS', 'BR', 'SC', 'BR', 'PR', 'BR') AS DES_PAIS,
       CASE
          WHEN FUNCOES.COD_CLH = 325 THEN
            FP03.COD_CONTRATO || '@grupograzziotin.com.br'
          WHEN ORG.EDICAO_ORG_3 = '001' THEN
            FP03.COD_CONTRATO || '@grazziotin.com.br'
          ELSE
           FIS.EMAIL
       END AS DES_EMAIL,
       FP03.DATA_INICIO AS DATA_ADMISSAO,
       FP03.DATA_FIM AS DATA_DEMISSAO,
       FP03.COD_CAUSA_DEMISSAO AS COD_DEMISSAO,
       DEM.NOME_CAUSA_DEMISSAO AS DES_DEMISSAO,
       FIS.CPF,
       FP02.NRO_PIS_PASEP,

       /*TIPO DO ORGANOGRAMA*/
       ORG.COD_TIPO,
       ORG.DES_TIPO,

       /*DADOS DO ORGANOGRAMA DO CONTRATO*/
       ORG.COD_ORGANOGRAMA,
       ORG.COD_UNIDADE,
       ORG.DES_UNIDADE,
       ORG.DATA_INI_ORG,
       ORG.DATA_FIM_ORG,
       ORG.COD_REDE AS COD_REDE_LOCAL,
       ORG.DES_REDE AS DES_REDE_LOCAL,

       SENHA.COD_GRUPO AS COD_GRUPO_UNIDADE,

       ----NÍVEIS DO ORGANOGRAMA DO CONTRATO
       ORG.COD_ORG_1    AS COD_GRUPO_EMP,
       ORG.EDICAO_ORG_1 AS EDICAO_GRUPO_EMP,
       ORG.NOME1        AS DES_GRUPO_EMP,
       --===
       ORG.COD_ORG_2    AS COD_EMP,
       ORG.EDICAO_ORG_2 AS EDICAO_EMP,
       ORG.NOME2        AS DES_EMPRESA,
       --===
       ORG.COD_ORG_3    AS COD_ORG_FILIAL,
       ORG.EDICAO_ORG_3 AS EDICAO_FILIAL,
       ORG.NOME3        AS DES_FILIAL,
       --===
       ORG.COD_ORG_4    AS COD_ORG_DIVISAO,
       ORG.EDICAO_ORG_4 AS EDICAO_DIVISAO,
       ORG.NOME4        AS DES_DIVISAO,
       --===
       ORG.COD_ORG_5    AS COD_ORG_DEPART,
       ORG.EDICAO_ORG_5 AS EDICAO_DEPART,
       ORG.NOME5        AS DES_DEPART,
       --===
       ORG.COD_ORG_6    AS COD_ORG_SETOR,
       ORG.EDICAO_ORG_6 AS EDICAO_SETOR,
       ORG.NOME6        AS DES_SETOR,
       --===
       ORG.COD_ORG_7    AS COD_ORG_SECAO,
       ORG.EDICAO_ORG_7 AS EDICAO_SECAO,
       ORG.NOME7        AS DES_SECAO,
       --===
       ORG.COD_ORG_8    AS COD_ORG_UNI,
       ORG.EDICAO_ORG_8 AS EDICAO_UNI,
       ORG.NOME8        AS DES_UNI

  FROM RHFP0200 FP02
 INNER JOIN RHFP0300 FP03 ON FP03.COD_FUNC = FP02.COD_FUNC
  LEFT JOIN RHFP0102 DEM ON FP03.COD_CAUSA_DEMISSAO = DEM.COD_CAUSA_DEMISSAO
 INNER JOIN PESSOA P ON P.COD_PESSOA = FP02.COD_FUNC
 INNER JOIN FISICA FIS ON FIS.COD_PESSOA = FP02.COD_FUNC
 INNER JOIN MUNICI MUN ON MUN.COD_MUNIC = FIS.COD_MUNIC
 INNER JOIN VH_EST_ORG_CONTRATO_AVT ORG ON FP03.COD_CONTRATO = ORG.COD_CONTRATO /*AND ORG.DATA_FIM_ORG = '31/12/2999'*/
  --LEFT JOIN V_ORGANOGRAMAS_AVT VO ON ORG.COD_ORGANOGRAMA = VO.COD_ORGANOGRAMA
 INNER JOIN RHFP0340 CONTRFUNC ON CONTRFUNC.COD_CONTRATO = FP03.COD_CONTRATO /*AND TRUNC(SYSDATE) BETWEEN CONTRFUNC.DATA_INICIO
                                                                             AND NVL(CONTRFUNC.DATA_FIM, '31/12/2999')*/
 INNER JOIN RHFP0500 FUNCOES ON FUNCOES.COD_CLH = CONTRFUNC.COD_CLH
  LEFT JOIN MDL_USUARIO SENHA ON SENHA.COD_CONTRATO = FP03.COD_CONTRATO


 WHERE (FP03.DATA_FIM IS NULL AND TRUNC(SYSDATE) BETWEEN FP03.DATA_INICIO AND
       NVL(FP03.DATA_FIM, '31/12/2999') OR
       FP03.DATA_FIM >= TRUNC(SYSDATE) - 1300)
