CREATE OR REPLACE VIEW V_HIST_CONTRATO_AVT AS
SELECT
    'CARGO' AS TIPO_HISTORICO,
    CT.COD_CONTRATO,
    PF.NOME_PESSOA,
    CT.DATA_INICIO AS DATA_ADMISSAO,
    CT.DATA_FIM AS DATA_DEMISSAO,
    CASE
        WHEN CT.DATA_FIM IS NULL THEN
         0
        ELSE
         1
    END AS STATUS,
    CASE
        WHEN CT.DATA_FIM IS NULL THEN
         'ATIVO'
        ELSE
         'INATIVO'
    END AS DES_STATUS,
    CARGO.COD_FUNCAO,
    CARGO.DES_FUNCAO,
    CARGO.DATA_INI_CLH AS DATA_INI_FUNCAO,
    CARGO.DATA_FIM_CLH AS DATA_FIM_FUNCAO,
    NULL AS COD_EMP,
    NULL AS EDICAO_EMP,
    NULL AS DES_EMP,
    NULL AS COD_UNIDADE,
    NULL AS DES_UNIDADE,
    NULL AS DATA_INI_ORG,
    NULL AS DATA_FIM_ORG,
    NULL AS COD_REDE,
    NULL AS DES_REDE,
    NULL AS COD_TIPO,
    NULL AS DES_TIPO,
    NULL AS HR_BASE_MES,
    NULL AS HR_BASE_SEM,
    NULL AS HR_BASE_DIA,
    NULL AS DATA_INI_HR,
    NULL AS DATA_FIM_HR,
    NULL AS COD_MOTIVO,
    NULL AS DES_MOTIVO,
    NULL AS COD_AFAST,
    NULL AS DES_AFAST,
    NULL AS DATA_INI_AFAST,
    NULL AS DATA_FIM_AFAST,
    NULL AS QTD_DIAS_AFAST,
    NULL AS COD_STATUS_AFAST,
    NULL AS STATUS_AFAST,
    CARGO.DATA_INI_CLH AS VALID_FROM,
    CARGO.DATA_FIM_CLH AS VALID_TO
FROM RHFP0300 CT
JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
JOIN VH_CARGO_CONTRATO_AVT CARGO ON CT.COD_CONTRATO = CARGO.COD_CONTRATO
--WHERE CT.COD_CONTRATO = 389622

UNION ALL

-- Histórico de ORGANOGRAMA
SELECT
   'ORGANOGRAMA' AS TIPO_HISTORICO,
    CT.COD_CONTRATO,
    PF.NOME_PESSOA,
    CT.DATA_INICIO,
    CT.DATA_FIM,
    CASE
        WHEN CT.DATA_FIM IS NULL THEN
         0
        ELSE
         1
    END AS STATUS,
    CASE
        WHEN CT.DATA_FIM IS NULL THEN
         'ATIVO'
        ELSE
         'INATIVO'
    END AS DES_STATUS,
    NULL,
    NULL,
    NULL,
    NULL,
    ORG.COD_EMP,
    ORG.EDICAO_EMP,
    ORG.DES_EMP,
    ORG.COD_UNIDADE,
    ORG.DES_UNIDADE,
    ORG.DATA_INI_ORG,
    ORG.DATA_FIM_ORG,
    ORG.COD_REDE,
    ORG.DES_REDE,
    ORG.COD_TIPO,
    ORG.DES_TIPO,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    ORG.DATA_INI_ORG AS VALID_FROM,
    ORG.DATA_FIM_ORG AS VALID_TO
FROM RHFP0300 CT
JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
JOIN VH_EST_ORG_CONTRATO_AVT ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO
--WHERE CT.COD_CONTRATO = 389622

UNION ALL

-- Histórico de HORAS
SELECT
   'HORAS' AS TIPO_HISTORICO,
    CT.COD_CONTRATO,
    PF.NOME_PESSOA,
    CT.DATA_INICIO,
    CT.DATA_FIM,
    CASE
        WHEN CT.DATA_FIM IS NULL THEN
         0
        ELSE
         1
    END AS STATUS,
    CASE
        WHEN CT.DATA_FIM IS NULL THEN
         'ATIVO'
        ELSE
         'INATIVO'
    END AS DES_STATUS,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    HORAS.HR_BASE_MES,
    HORAS.HR_BASE_SEM,
    HORAS.HR_BASE_DIA,
    HORAS.DATA_INI_HR AS VALID_FROM,
    HORAS.DATA_FIM_HR AS VALID_TO,
    HORAS.COD_MOTIVO,
    HORAS.DES_MOTIVO,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    HORAS.DATA_INI_HR AS VALID_FROM,
    HORAS.DATA_FIM_HR AS VALID_TO
FROM RHFP0300 CT
JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
JOIN VH_HIST_HORAS_COLAB_AVT HORAS ON CT.COD_CONTRATO = HORAS.COD_CONTRATO
--WHERE CT.COD_CONTRATO = 389622

UNION ALL

-- Histórico de AFASTAMENTOS
SELECT
   'AFASTAMENTO' AS TIPO_HISTORICO,
    CT.COD_CONTRATO,
    PF.NOME_PESSOA,
    CT.DATA_INICIO,
    CT.DATA_FIM,
    CASE
        WHEN CT.DATA_FIM IS NULL THEN
         0
        ELSE
         1
    END AS STATUS,
    CASE
        WHEN CT.DATA_FIM IS NULL THEN
         'ATIVO'
        ELSE
         'INATIVO'
    END AS DES_STATUS,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    AFAST.COD_AFAST,
    AFAST.DES_AFAST,
    AFAST.DATA_INI_AFAST AS VALID_FROM,
    AFAST.DATA_FIM_AFAST AS VALID_TO,
    AFAST.QTD_DIAS_AFAST,
    AFAST.COD_STATUS_AFAST,
    AFAST.STATUS_AFAST,
    AFAST.DATA_INI_AFAST AS VALID_FROM,
    AFAST.DATA_FIM_AFAST AS VALID_TO
FROM RHFP0300 CT
JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
JOIN VH_AFAST_CONTRATO_AVT AFAST ON CT.COD_CONTRATO = AFAST.COD_CONTRATO
--WHERE CT.COD_CONTRATO = 389622

