CREATE OR REPLACE VIEW VH_COLAB_PESSOA_AVT AS
SELECT B.COD_PESSOA,
       A.COD_CONTRATO,
       B.NOME_PESSOA AS DES_PESSOA,
       A.DATA_INICIO AS DATA_ADMISSAO,
       A.DATA_FIM AS DATA_DEMISSAO,
       A.DATA_AVANCO,
       A.COD_CAUSA_DEMISSAO AS COD_DEMISSAO,
       D.NOME_CAUSA_DEMISSAO AS DES_DEMISSAO,
       C.DATA_NASCIMENTO,
       TRUNC(MONTHS_BETWEEN(SYSDATE, C.DATA_NASCIMENTO) / 12) AS IDADE,
       C.SEXO,
       C.COD_ESTADO_CIVIL AS COD_EST_CIVIL,
       F.NOME_ESTADO_CIVIL AS DES_EST_CIVIL,
       C.IND_DEFICIENCIA,
       C.COD_DEFICIENCIA,
       H.NOME_DEFICIENCIA AS DES_DEFICIENCIA,
       B.EMAIL AS DES_EMAIL,
       B.DDD_FONE_CEL AS COD_DDD,
       B.FONE_CEL,
       B.CPF,
       C.NRO_IDENTIDADE,
       E.NOME_PESSOA || '/' || C.COD_UF_IDENTIDADE AS EMISSOR,
       C.NRO_PIS_PASEP,
       C.COD_NACIONALIDADE,
       G.NOME_NACIONALIDADE || '(a)' AS NACIONALIDADE,
       C.COD_NACIONALIDADE || ' - ' || G.NOME_NACIONALIDADE || '(a)' AS DES_NACIONALIDADE,
       B.CEP AS COD_CEP,
       B.TIPO_LOGRA,
       B.COD_LOGRA,
       B.NOME_LOGRA AS DES_LOGRA,
       B.COD_BAIRRO,
       B.NOME_BAIRRO AS DES_BAIRRO,
       B.COD_MUNIC AS COD_CIDADE,
       B.NOME_MUNIC AS DES_CIDADE,
       B.COD_UF,
       CASE
         WHEN A.DATA_FIM IS NOT NULL AND A.DATA_FIM < SYSDATE THEN
          1
         ELSE
          0
       END AS STATUS,
       CASE
         WHEN A.DATA_FIM IS NOT NULL AND A.DATA_FIM < SYSDATE THEN
          'INATIVO'
         WHEN A.DATA_INICIO <= SYSDATE /*OR CT.DATA_FIM = SYSDATE AND TO_CHAR(SYSDATE, 'HH24:MI:SS') = '23:59:59'*/
          THEN
          'ATIVO'
         WHEN A.DATA_INICIO > SYSDATE
         /*AND CT.DATA_AVANCO > SYSDATE*/
          THEN
          'ADMISSAO FUTURA'
       END AS DESC_STATUS,
       /*DADOS DE AFASTAMENTOS DO CONTRATO*/
       AFAST.COD_CAUSA_AFAST AS COD_AFAST,
       CASE
         WHEN AFAST.COD_CAUSA_AFAST IS NOT NULL THEN
          AFAST.COD_CAUSA_AFAST || ' - ' || AFAST.NOME_CAUSA_AFAST
         ELSE
          NULL
       END AS DES_AFAST,
       AFAST.DATA_INICIO AS DATA_INI_AFAST,
       AFAST.DATA_FIM AS DATA_FIM_AFAST,
       NVL(AFAST.COD_CAUSA_AFAST, 0) AS COD_STATUS_AFAST,
       CASE
         WHEN A.DATA_FIM IS NOT NULL AND A.DATA_FIM < SYSDATE THEN
          'INATIVO'
         WHEN AFAST.COD_CAUSA_AFAST <> 0 AND AFAST.COD_CAUSA_AFAST <> 4 AND
              AFAST.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'AFASTADO'
         WHEN AFAST.COD_CAUSA_AFAST = 7 THEN
          'EM FÉRIAS'
         WHEN AFAST.COD_CAUSA_AFAST IN (3, 6) THEN
          'AFASTADO TEMP'
         WHEN AFAST.COD_CAUSA_AFAST = 4 AND
              AFAST.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'PODERÁ RETORNAR'
         ELSE
          'EM ATIVIDADE'
       END AS STATUS_AFAST
  FROM RHFP0300 A
 INNER JOIN PESSOA_FISICA B ON A.COD_FUNC = B.COD_PESSOA
 INNER JOIN RHFP0200 C ON A.COD_FUNC = C.COD_FUNC
  LEFT JOIN RHFP0102 D ON A.COD_CAUSA_DEMISSAO = D.COD_CAUSA_DEMISSAO
  LEFT JOIN PESSOA_JURIDICA E ON C.COD_ORG_IDENTIDADE = E.COD_PESSOA
  LEFT JOIN RHFP0104 F ON C.COD_ESTADO_CIVIL = F.COD_ESTADO_CIVIL
  LEFT JOIN RHFP0107 G ON C.COD_NACIONALIDADE = G.COD_NACIONALIDADE
  LEFT JOIN RHFP0132 H ON C.COD_DEFICIENCIA = H.COD_DEFICIENCIA
  LEFT JOIN V_AFAST_COLAB_AVT AFAST ON A.COD_CONTRATO = AFAST.COD_CONTRATO
 --WHERE A.COD_CONTRATO = 389622
 ORDER BY A.COD_CONTRATO, A.DATA_INICIO

