CREATE OR REPLACE VIEW VH_HIST_SINDICATOS_CONT_AVT AS
SELECT DISTINCT
       A.COD_CONTRATO,
       A.COD_SINDICATO,
       PJ.NOME_PESSOA AS DES_SINDICATO,
       A.IND_CONT_SINDICAL,
       A.IND_MENS_SINDICATO,
       A.DATA_INICIO,
       A.DATA_FIM
FROM RHFP0312 A
INNER JOIN RHFP0329 B ON A.COD_SINDICATO = B.COD_SINDICATO
LEFT JOIN PESSOA_JURIDICA PJ ON B.COD_PESSOA = PJ.COD_PESSOA

