--SELECT * FROM RHFP0309 = LOTAÇÕES DO CONTRATO;
--SELECT * FROM RHFP0509 = LOTAÇÕES;
--SELECT * FROM RHFP0510 = ESPECIFICAÇÃO DA LOTAÇÃO;


SELECT * FROM RHFP0396
WHERE DATA_FIM = '31/12/2999'

SELECT A.COD_LOTACAO,
       A.NOME_LOTACAO,
       B.DATA_INICIO,
       B.DATA_FIM,
       B.COD_ORGANOGRAMA,
       B.COD_CLH,
       B.NUM_VAGAS,
       B.NUM_HORAS,
       B.COD_MOTIVO
  FROM RHFP0509 A, RHFP0510 B
 WHERE A.COD_LOTACAO = B.COD_LOTACAO

SELECT * FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')


SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       COUNT(CASE
               WHEN COD_FUNCAO IN
                    (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) THEN
                COD_CONTRATO
               ELSE
                NULL
             END) AS NUM_GERENTES,
       DES_FUNCAO,
       CASE
         WHEN A.COD_FUNCAO IN (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) THEN
         'LOT' || ' ' || DES_UNIDADE || ' - GERENTE'
         ELSE
         NULL
       END AS LOTACAO,
       IND_
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND TIPO = 'LOJA'
AND STATUS = 0
AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
AND DES_FUNCAO LIKE '%GERENTE%'
GROUP BY COD_UNIDADE,
         DES_UNIDADE,
         COD_CONTRATO,
         DES_PESSOA,
         COD_FUNCAO,
         DES_FUNCAO
ORDER BY COD_UNIDADE ASC

--SQL PARA CONTAR A QUANTIDADE DE COLABORADORES POR FUNÇÃO PARA AS LOTAÇÕES

SELECT COD_UNIDADE,
       DES_UNIDADE,
       COD_ORGANOGRAMA,
       COUNT(CASE
               WHEN COD_FUNCAO = 68 THEN
                COD_CONTRATO
               ELSE
                NULL
             END) AS NUM_SERVENTES,
       COUNT(CASE
               WHEN COD_FUNCAO IN
                    (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) THEN
                COD_CONTRATO
               ELSE
                NULL
             END) AS NUM_GERENTES,
       COUNT(CASE
               WHEN COD_FUNCAO IN (121, 305, 122) THEN
                COD_CONTRATO
               ELSE
                NULL
             END) AS NUM_ORIENT_VENDA,
       COUNT(CASE
               WHEN COD_FUNCAO = 206 THEN
                COD_CONTRATO
               ELSE
                NULL
             END) AS NUM_AUXI_LOJA,
       COUNT(CASE
               WHEN COD_FUNCAO = 120 THEN
                COD_CONTRATO
               ELSE
                NULL
             END) AS NUM_VEND_MODA_MASC,
       COUNT(CASE
               WHEN COD_FUNCAO = 102 THEN
                COD_CONTRATO
               ELSE
                NULL
             END) AS NUM_CAIXA_GERAL,
       COUNT(CASE
               WHEN COD_FUNCAO = 74 THEN
                COD_CONTRATO
               ELSE
                NULL
             END) AS NUM_APRENDIZ,
       MAX(CASE
             WHEN COD_FUNCAO = 68 THEN
              HR_BASE_MES
             ELSE
              NULL
           END) AS HORAS_BASE_SERVENTE
  FROM V_DADOS_COLAB_AVT VDC, RHFP0510 LOT1, RHFP0509 LOT2
 WHERE COD_EMP = '008'
   AND STATUS = 0
   AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND TIPO = 'LOJA'
   AND (COD_FUNCAO = 68 OR
       COD_FUNCAO IN
       (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) OR
       COD_FUNCAO IN (121, 305, 122) OR COD_FUNCAO = 206 OR
       COD_FUNCAO = 120 OR COD_FUNCAO = 102 OR COD_FUNCAO = 74)
   AND COD_UNIDADE NOT IN (004, 014, 016, 019)
 GROUP BY COD_UNIDADE, DES_UNIDADE, COD_ORGANOGRAMA
 ORDER BY COD_UNIDADE ASC;


--SQLs PRINCIPAL PARA COMEÇAR A CRIAÇÃO DAS LOTAÇÕES 


--TODAS AS FUNÇÕES

SELECT COD_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       COD_FUNCAO,
       DES_FUNCAO,
       CASE
         WHEN COD_FUNCAO IN (77, 78, 79, 80, 81, 86, 87, 88, 89, 90, 184, 185, 186, 188, 189, 190, 192, 294, 318) THEN
         'LOT' || ' ' || DES_UNIDADE || ' - GERENTE'
         ELSE
         NULL
       END AS LOT_GERENTE,
       CASE
         WHEN COD_FUNCAO IN (121, 305, 122) THEN
         'LOT' || ' ' || DES_UNIDADE || ' - ORIENT. DE VENDA'
         ELSE
         NULL
       END AS LOT_ORIENT_VENDA,
       CASE
         WHEN COD_FUNCAO = 206 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - AUXI. LOJA'
         ELSE
         NULL
       END AS LOT_AUXI_LOJA,
       CASE
         WHEN COD_FUNCAO = 120 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - VEND. MODA MASC.'
         ELSE
         NULL
       END AS LOT_VEND_MODA_MASC,
       CASE
         WHEN COD_FUNCAO = 102 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - CAIXA GERAL'
         ELSE
         NULL
       END AS LOT_CAIXA_GERAL,
       CASE
         WHEN COD_FUNCAO = 74 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - APRENDIZ'
         ELSE
         NULL
       END AS LOT_APRENDIZ,
       CASE
         WHEN COD_FUNCAO = 68 THEN
         'LOT' || ' ' || DES_UNIDADE || ' - SERVENTE'
         ELSE
         NULL
       END AS LOT_SERVENTE
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
  AND TIPO = 'LOJA'
  AND STATUS = 0
  AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
  AND (
    DES_FUNCAO LIKE '%GERENTE%'
    OR DES_FUNCAO LIKE '%ORIENTADOR DE VENDA%'
    OR DES_FUNCAO LIKE '%AUXILIAR DE LOJA%'
    OR DES_FUNCAO LIKE '%VENDEDOR MODA MASCULINA%'
    OR DES_FUNCAO LIKE '%CAIXA GERAL%'
    OR DES_FUNCAO LIKE '%APRENDIZ%'
    OR DES_FUNCAO LIKE '%SERVENTE%'
  )
ORDER BY COD_UNIDADE ASC;

--SQL ALTER PARA MAPEAR AS LOTAÇÕES DE CADA LOJA

SELECT
  MIN(COD_UNIDADE) AS COD_LOTACAO,
  'LOT' || ' ' || DES_UNIDADE || ' - ' || NOME_FUNCAO AS NOME_LOTACAO,
  CASE WHEN NOME_FUNCAO = 'SERVENTE' THEN 'H' ELSE 'V' END AS TIPO_LOTACAO,
  CASE WHEN NOME_FUNCAO = 'APRENDIZ' THEN 4 ELSE 1 END AS COD_TIPO_VAGA,
  TO_CHAR(MIN(COD_UNIDADE)) AS EDICAO_QL
FROM (
  SELECT
    COD_UNIDADE,
    DES_UNIDADE,
    CASE
      WHEN DES_FUNCAO LIKE '%GERENTE%' THEN 'GERENTE'
      WHEN DES_FUNCAO LIKE '%ORIENTADOR DE VENDA%' THEN 'ORIENT. DE VENDA'
      WHEN DES_FUNCAO LIKE '%AUXILIAR DE LOJA%' THEN 'AUXI. LOJA'
      WHEN DES_FUNCAO LIKE '%VENDEDOR MODA MASCULINA%' THEN 'VEND. MODA MASC.'
      WHEN DES_FUNCAO LIKE '%CAIXA GERAL%' THEN 'CAIXA GERAL'
      WHEN DES_FUNCAO LIKE '%APRENDIZ%' THEN 'APRENDIZ'
      WHEN DES_FUNCAO LIKE '%SERVENTE%' THEN 'SERVENTE'
      ELSE NULL -- Não atribuímos 'OUTRO' aqui para evitar criar lotações desnecessárias
    END AS NOME_FUNCAO
  FROM V_DADOS_COLAB_AVT
  WHERE COD_EMP = '008'
    AND TIPO = 'LOJA'
    AND STATUS = 0
    AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
    AND COD_UNIDADE NOT IN (4, 14, 16, 19)
    --AND COD_UNIDADE = 023
  GROUP BY COD_UNIDADE, DES_UNIDADE, DES_FUNCAO
  HAVING (DES_FUNCAO NOT LIKE '%GERENTE%' OR COD_UNIDADE NOT IN (25, 566, 580, 7046, 7093))
     OR (DES_FUNCAO LIKE '%GERENTE%' AND COD_UNIDADE IN (25, 566, 580, 7046, 7093) AND COUNT(*) = 1)
)
WHERE NOME_FUNCAO IS NOT NULL -- Isto exclui as funções que não correspondem aos padrões
GROUP BY DES_UNIDADE, NOME_FUNCAO
ORDER BY MIN(COD_UNIDADE) ASC;


--=====================--

