/*ABAIXO SCRIPTS USADOS PARA O PROCESSO DE CÁLCULO DO AUMENTO SALARIAL.
SCRIPTS NECESSÁRIOS PARA QUE OS VALORES ENTREM DE FORMA CORRETA, COM BASE NOS VALORES INTEGRADOS AO VD 905.

ESSES SCRIPTS SÓ DEVEM SER EXECUTADOS APÓS O RH EXECUTAR O CÁLCULO DO EVENTO 22 - AUMENTO SALARIAL, 
E AI, O RESPONSÁVEL NA TI, EXECUTA OS SCRIPTS NA ORDEM CORRETA, EXECUTANDO OS SCRIPT EMPRESA POR EMPRESA, PARA NÃO OCORRER RISCOS,
AI COM ISSO FEITO, REPASSA NOVAMENTE AO RH A CONFIRMAÇÃO DA EXECUÇÃO, PARA QUE ENTÃO, O RH POSSA GERAR O EVENTO 1 - MENSAL,
PARA QUE OS VALORES DO AUMENTO ENFIM ENTREM EM FOLHA

 > PRIMEIRO SQL A EXECUTAR = INSERT (OBSERVAÇÃO QUANTO A EXECUÇÃO JUNTO AO SCRIPT)
 > SEGUNDO SQL A EXECUTAR = UPDATE (OBSERVAÇÃO QUANTO A EXECUÇÃO JUNTO AO SCRIPT)
 
OBS_1: ANTECIPAÇÃO SALARIAL NÃO É AUMENTO, É OUTRO PROCEDIMENTO REALIZADO COM BASE NA LESGISLAÇÃO
       AUMENTO SALARIAL É O PERCENTUAL GERADO PELA PRÓPRIA EMPRESA, PORÉM, INTEGRADO AO MESMO VD DA ANTECIPAÇÃO >VD 905<
     
OBS_2: SEMPRE TER CUIDADO AO REALIZAR QUALQUER ALTERAÇÃO NOS SCRIPTS, POIS ISSO PODE AFETAR SERIAMENTE OS CÁLCULOS NA FOLHA.
       RECOMENDA-SE SEMPRE EXECUTAR PRIMEIRO EM BASE DE TESTE(SE A MESMA ESTIVER ATUALIZADA COM DADOS ATUAIS) ANTES DE EXECUTAR EM PRODUÇÃO*/

---===============================================================---
---===============================================================---

--==========PRIMEIRO A EXECUTAR INSERT=========--


/*PRIMEIRO SE EXECUTA O INSERT, POIS ELE IRÁ INSERIR PARA TODOS OS COLABORADORES QUE NÃO RECEBEM ANTECIPAÇÃO SALARIAL,
O VALOR CORRESPONDENTE AO EVENTO 22, O VALOR DO AUMENTO PARA OS CONTRATOS QUE AINDA NÃO O POSSUEM.
SENDO ASSIM, APÓS SER EXECUTADO O EVENTO 22 PELO RH, A TI EXECUTA PRIMEIRAMENTE ESSE SCRIPT, 
PARA ETÃO INSERIR ESSE VALOR AOS CONTRATOS PARA FINS DO CÁLCULO MENSAL.*/



INSERT INTO RHFP1004
  (SELECT 1 AS COD_EVENTO,
          CC.COD_CONTRATO,
          CC.DATA_REFERENCIA,
          905 AS COD_VD,
          CC.TIPO_INF_VD,
          99 AS PRESTACAO_VD,
          CC.QTDE_VD,
          NVL(TRIM((CC.VALOR_VD + (SELECT FF.VALOR_VD
                                     FROM RHFP1004 FF
                                    WHERE FF.COD_EVENTO = 1
                                      AND FF.COD_CONTRATO = CC.COD_CONTRATO
                                      AND FF.DATA_MOV = CC.DATA_REFERENCIA
                                      AND FF.COD_VD = 905))),
              CC.VALOR_VD) AS VALOR_VD,
          1 AS COD_ORIGEM_MOV,
          CC.COD_MESTRE_EVENTO,
          CC.DATA_REFERENCIA,
          'Aumento Salarial (Evento 22) - Mestre 17287' AS OBSERVACAO,
          NULL
     FROM RHFP1005 CC
    WHERE CC.COD_EVENTO = 22
      AND CC.DATA_REFERENCIA = TO_DATE('28/02/2025', 'DD/MM/YYYY') /*SEMPRE LEMBRAR DE ALTERAR A DATA DE REFERÊNCIA ANTES DA EXECUÇÃO*/
      AND CC.COD_VD = 1090
         --AND CC.COD_CONTRATO = 389622 /*FILTRO PARA FINS DE TESTES, ANTES DA GERAÇÃO GERAL*/
      AND CC.COD_CONTRATO NOT IN
          (SELECT FF.COD_CONTRATO
             FROM RHFP1004 FF
            WHERE FF.COD_EVENTO = 1
              AND FF.COD_CONTRATO = CC.COD_CONTRATO
              AND FF.DATA_MOV = CC.DATA_REFERENCIA
              AND FF.COD_VD = 905)
      AND CC.COD_CONTRATO IN (SELECT ORG.COD_CONTRATO
                                FROM RHFP0310 ORG
                               WHERE CC.COD_CONTRATO = ORG.COD_CONTRATO
                                    --AND ORG.COD_CONTRATO IN (389622, 388070, 390837) /*FILTRO PARA FINS DE TESTES, ANTES DA GERAÇÃO GERAL*/
                                 AND ORG.DATA_FIM = '31/12/2999'
                                 AND ORG.COD_NIVEL2 = 8) /*INSERIR SOMENTE A EMPRESA 8 (DEMAIS EMPRESAS: 4, 276, 1629)*/
   );




--===========



-----SELECT PARA CONFERENCIA APÓS INSERÇÃO

SELECT DISTINCT
       A.COD_CONTRATO,
       PF.NOME_PESSOA,
       A.COD_EVENTO,
       A.DATA_MOV,
       A.COD_VD,
       A.PRESTACAO_VD,
       A.VALOR_VD,
       A.COD_ORIGEM_MOV,
       A.COD_MESTRE_EVENTO,
       A.DATA_DIGITACAO,
       A.OBSERVACAO,       
       CASE
          WHEN C.COD_NIVEL2 = 4 THEN
           C.COD_NIVEL2 || ' - ' || 'MUNDIART S/A'
          WHEN C.COD_NIVEL2 = 8 THEN
           C.COD_NIVEL2 || ' - ' || 'GRAZZIOTIN S/A'
          WHEN C.COD_NIVEL2 = 276 THEN
           C.COD_NIVEL2 || ' - ' || 'CENTRO SHOPPING LTDA'
          WHEN C.COD_NIVEL2 = 1629 THEN
           C.COD_NIVEL2 || ' - ' || 'FLORESTA GRAZZIOTIN LTDA'
          ELSE
           NULL
       END AS EMPRESA,
       C.COD_ORGANOGRAMA,
       E.EDICAO_ORG || ' - ' || D.NOME_ORGANOGRAMA
FROM RHFP1004 A
LEFT JOIN RHFP0300 B ON A.COD_CONTRATO = B.COD_CONTRATO
LEFT JOIN RHFP0310 C ON A.COD_CONTRATO = C.COD_CONTRATO
LEFT JOIN RHFP0400 D ON C.COD_ORGANOGRAMA = D.COD_ORGANOGRAMA
LEFT JOIN RHFP0401 E ON E.COD_ORGANOGRAMA = D.COD_ORGANOGRAMA
LEFT JOIN PESSOA_FISICA PF ON B.COD_FUNC = PF.COD_PESSOA
WHERE A.COD_VD = 905
AND A.PRESTACAO_VD = 99
AND A.COD_EVENTO = 1
AND A.DATA_MOV = TO_DATE('28/02/2025', 'DD/MM/YYYY') /*SEMPRE LEMBRAR DE ALTERAR A DATA DE REFERÊNCIA ANTES DA EXECUÇÃO*/
AND B.DATA_FIM IS NULL
AND C.DATA_FIM = '31/12/2999'
AND C.COD_NIVEL2 = 8
--AND A.COD_CONTRATO IN (389622, 388070, 390837) /*CONTRATOS USADOS PARA FINS DE TESTES*/



------------------------------------------------------------------------------------------------------


--SEGUNDO A EXECUTAR UPDATE

/*UPDATE DEVE SER EXECUTADO APÓS O INSERT, 
POIS O PROCEDIMENTO DELE É APENAS ATUALIZAR O VALOR DE AUMENETO, 
PARA OS COLABORADORES QUE RECEBEM ANTECIPAÇÃO SALARIAL, 
AQUELE VALOR QUE ENTRA MENSALMENTE PARA DETERMINADOS COLABORADORES COM BASE EM CONVENÇÕES COLETIVAS*/

SELECT * FROM RHFP1004


UPDATE RHFP1004 MOV
   SET MOV.VALOR_VD = (SELECT NVL(K.VALOR_VD +
                                  (SELECT FF.VALOR_VD
                                     FROM RHFP1004 FF
                                    WHERE FF.COD_EVENTO = 1
                                      AND FF.COD_CONTRATO = K.COD_CONTRATO
                                      AND FF.DATA_MOV = K.DATA_REFERENCIA
                                      AND FF.COD_VD = 905
                                      AND FF.COD_ORIGEM_MOV <> 1),
                                  K.VALOR_VD) AS VALOR_VD
                         FROM RHFP1005 K
                        WHERE K.COD_EVENTO = 22
                          AND K.DATA_REFERENCIA =
                              TO_DATE('28/02/2025', 'DD/MM/YYYY') /*SEMPRE LEMBRAR DE ALTERAR A DATA DE REFERÊNCIA ANTES DA EXECUÇÃO*/
                          AND K.COD_CONTRATO = MOV.COD_CONTRATO
                          AND K.COD_VD = 1090),
       OBSERVACAO   = 'Aumento Salarial (Evento 22) - Mestre 17287'
 WHERE MOV.COD_EVENTO = 1
   AND MOV.DATA_MOV = TO_DATE('28/02/2025', 'DD/MM/YYYY') /*SEMPRE LEMBRAR DE ALTERAR A DATA DE REFERÊNCIA ANTES DA EXECUÇÃO*/
   AND MOV.COD_VD = 905
   AND MOV.COD_ORIGEM_MOV <> 1
      --AND MOV.COD_CONTRATO = 394553  /*FILTRO PARA FINS DE TESTES, ANTES DA GERAÇÃO GERAL*/
   AND MOV.COD_CONTRATO IN
       (SELECT COD_CONTRATO
          FROM RHFP1005
         WHERE COD_EVENTO = 22
           AND DATA_REFERENCIA = TO_DATE('28/02/2025', 'DD/MM/YYYY') /*SEMPRE LEMBRAR DE ALTERAR A DATA DE REFERÊNCIA ANTES DA EXECUÇÃO*/
           AND COD_CONTRATO = MOV.COD_CONTRATO
           AND COD_VD = 1090)
   AND EXISTS
 (SELECT 1
          FROM RHFP1004 FF
         WHERE FF.COD_EVENTO = 1
           AND FF.COD_CONTRATO = MOV.COD_CONTRATO
           AND FF.DATA_MOV = MOV.DATA_MOV
           AND FF.COD_VD = 905
           AND FF.COD_ORIGEM_MOV <> 1)
   AND MOV.COD_CONTRATO IN (SELECT ORG.COD_CONTRATO
                              FROM RHFP0310 ORG
                             WHERE MOV.COD_CONTRATO = ORG.COD_CONTRATO
                                  --AND ORG.COD_CONTRATO = 256897  /*FILTRO PARA FINS DE TESTES, ANTES DA GERAÇÃO GERAL*/
                               AND ORG.DATA_FIM = '31/12/2999'
                               AND ORG.COD_NIVEL2 = 8) /*INSERIR SOMENTE A EMPRESA 8 (DEMAIS EMPRESAS: 4, 276, 1629)*/
							   
							   
					
					
--==========


					
					
-----SELECT PARA CONFERÊNCIA APÓS ATUALIZAÇÃO

SELECT DISTINCT
       A.COD_CONTRATO,
       PF.NOME_PESSOA,
       A.COD_EVENTO,
       A.DATA_MOV,
       A.COD_VD,
       A.PRESTACAO_VD,
       A.VALOR_VD,
       A.COD_ORIGEM_MOV,
       A.COD_MESTRE_EVENTO,
       A.DATA_DIGITACAO,
       A.OBSERVACAO,       
       CASE
          WHEN C.COD_NIVEL2 = 4 THEN
           C.COD_NIVEL2 || ' - ' || 'MUNDIART S/A'
          WHEN C.COD_NIVEL2 = 8 THEN
           C.COD_NIVEL2 || ' - ' || 'GRAZZIOTIN S/A'
          WHEN C.COD_NIVEL2 = 276 THEN
           C.COD_NIVEL2 || ' - ' || 'CENTRO SHOPPING LTDA'
          WHEN C.COD_NIVEL2 = 1629 THEN
           C.COD_NIVEL2 || ' - ' || 'FLORESTA GRAZZIOTIN LTDA'
          ELSE
           NULL
       END AS EMPRESA,
       C.COD_ORGANOGRAMA,
       E.EDICAO_ORG || ' - ' || D.NOME_ORGANOGRAMA       
FROM RHFP1004 A
LEFT JOIN RHFP0300 B ON A.COD_CONTRATO = B.COD_CONTRATO
LEFT JOIN RHFP0310 C ON A.COD_CONTRATO = C.COD_CONTRATO
LEFT JOIN RHFP0400 D ON C.COD_ORGANOGRAMA = D.COD_ORGANOGRAMA
LEFT JOIN RHFP0401 E ON E.COD_ORGANOGRAMA = D.COD_ORGANOGRAMA
LEFT JOIN PESSOA_FISICA PF ON B.COD_FUNC = PF.COD_PESSOA
WHERE A.COD_VD = 905
AND A.PRESTACAO_VD = 99
AND A.COD_EVENTO = 1
AND A.DATA_MOV = TO_DATE('28/02/2025', 'DD/MM/YYYY') /*SEMPRE LEMBRAR DE ALTERAR A DATA DE REFERÊNCIA ANTES DA EXECUÇÃO*/
AND C.DATA_FIM = '31/12/2999'
AND B.DATA_FIM IS NULL
AND C.COD_NIVEL2 = 8
--and A.COD_CONTRATO = 256897