--SCRIPT PARA CONSULTAR TAREFAS DO USUÁRIO DO WORKFLOW E DELETAR UMA TAREFA INCORRETA.

SELECT TU.COD_EXEC_PROC,
       TU.DATA_INICIO,
       TU.DATA_CONCLUSAO_PREV,
       TU.DATA_CONCLUSAO_EFET,
       TU.COD_CONTRATO,
       VDP.DES_PESSOA, 
       TU.COMENTARIOS
  FROM RHWF0255 TU, V_DADOS_PESSOA VDP
 WHERE TU.COD_CONTRATO = VDP.COD_CONTRATO
   AND TU.COD_EXEC_PROC = 3227;
   

--===========================--
   
DELETE
FROM RHWF0255
WHERE COD_EXEC_PROC = 3227;



--======================================--