/*select carga de colaboradores para PAYTRACK*/

WITH RANDOM_CHARACTERS AS (
    SELECT
        DBMS_RANDOM.STRING('U', 1) AS UPPERCASE_CHAR,      -- 1 uppercase letter
        DBMS_RANDOM.STRING('L', 1) AS LOWERCASE_CHAR,      -- 1 lowercase letter
        CHR(TRUNC(DBMS_RANDOM.VALUE(48, 58))) AS DIGIT_CHAR, -- 1 digit (ASCII 48 to 57)
        SUBSTR('!@#$%*&', TRUNC(DBMS_RANDOM.VALUE(1, 8)), 1) AS SPECIAL_CHAR1, -- 1 special character from specified set
        SUBSTR('!@#$%*&', TRUNC(DBMS_RANDOM.VALUE(1, 8)), 1) AS SPECIAL_CHAR2, -- another special character from specified set
        DBMS_RANDOM.STRING('A', 6) AS MIXED_CHARS          -- 5 random alphanumeric characters
    FROM dual
)
SELECT 
    DES_PESSOA,
    SEXO,
    CPF,
    DES_EMAIL,
    DATA_NASCIMENTO,
    CPF AS COD_INTEGRACAO,
    'S' AS ATIVO,
    COD_CONTRATO AS USUARIO,
    UPPERCASE_CHAR || LOWERCASE_CHAR || DIGIT_CHAR || SPECIAL_CHAR1 || SPECIAL_CHAR2 || MIXED_CHARS AS SENHA_ALEATORIA,
    '92.012.467/0001-70' AS CNPJ_EMPRESA,
    CASE 
        WHEN DES_FUNCAO LIKE '%DIRETOR%' THEN 
         EDICAO_AREA 
        ELSE
        EDICAO_PAI 
    END AS COD_CENTRO_CUSTO,
    (SELECT 
        CASE
            WHEN ORG2.EDICAO_NIVEL5 IS NOT NULL OR ORG2.EDICAO_NIVEL4 IS NOT NULL THEN ORG1.NOME_ORGANOGRAMA
            ELSE NULL
        END AS RESULTADO
    FROM RHFP0401 ORG2
    INNER JOIN RHFP0400 ORG1 ON ORG2.COD_ORGANOGRAMA = ORG1.COD_ORGANOGRAMA
    WHERE ORG2.EDICAO_NIVEL5 = V_DADOS_COLAB_AVT.EDICAO_PAI
    AND ORG2.EDICAO_NIVEL4 = V_DADOS_COLAB_AVT.EDICAO_AREA
    AND ROWNUM = 1) AS DESC_CENTRO_CUSTO
FROM V_DADOS_COLAB_AVT
CROSS JOIN RANDOM_CHARACTERS
WHERE STATUS = 0
AND (
    DES_FUNCAO LIKE '%DIRETOR%' OR
    DES_FUNCAO LIKE '%SUPERVISOR%' OR
    DES_FUNCAO LIKE '%GERENTE%' OR
    DES_FUNCAO LIKE '%REGIONAIS%'
)
AND COD_TIPO = 2
AND COD_CONTRATO NOT IN (388733);