SELECT A.COD_CONTRATO
       , B.NOME_PESSOA
       , C.NOME_ORGANOGRAMA
       , E.DATA_INICIO
       , E.DATA_FIM
       , F.COD_CID_10
       , F.NOME_CID_10
       , (E.DATA_FIM - E.DATA_INICIO + 1) AS DIAS_AFAST
FROM  RHFP0300 A
     , PESSOA B
     , RHFP0400 C
     , RHFP0310 D
     , RHFP0306 E
     , RHMS0180 F
     , RHFP0401 G
WHERE A.COD_FUNC = B.COD_PESSOA
AND A.COD_CONTRATO = D.COD_CONTRATO
AND C.COD_ORGANOGRAMA = D.COD_ORGANOGRAMA
AND A.COD_CONTRATO = E.COD_CONTRATO
AND E.COD_CID_10 = F.COD_CID_10
AND D.DATA_FIM = '31/12/2999'
AND E.DATA_INICIO >= :DATA_FIM
AND E.DATA_INICIO >= :DATA_INICIO
AND G.COD_NIVEL2 = :ORGANOGRAMA
ORDER BY B.NOME_PESSOA ASC
--AND A.COD_CONTRATO = 387692
--AND (A.DATA_FIM IS NULL OR A.DATA_FIM > TRUNC(SYSDATE))
-- TRÁS SOMENTE CONTRATOS ATIVOS