/* SQL - RELATÓRIO DE RENDIMENTOS GERENCIAL DO ANO DE 2025, CONTENDO TODOS OS TRIBUTOS BRUTO POR COLABORADOR*/

/* CAMPOS DO RELATÓRIO
CONTRATO, 
NOME,
FUNÇÃO,
UNIDADE,
VALORES,
COMPETÊNCIA

*/


WITH
PARAMS AS (
  SELECT TO_DATE('&DATA_INICIO','DD/MM/YYYY') AS D_INI,
         TO_DATE('&DATA_FIM'   ,'DD/MM/YYYY') AS D_FIM
  FROM DUAL
  
  /*SELECT :DATA_INICIO AS D_INI,
         :DATA_FIM AS D_FIM
  FROM DUAL*/
  
),
DATAS_REF AS (
  SELECT ADD_MONTHS(p.D_INI, LEVEL-1)                          AS DTA_INI,
         LAST_DAY(ADD_MONTHS(p.D_INI, LEVEL-1))                AS DTA_FIM,
         TO_CHAR(ADD_MONTHS(p.D_INI, LEVEL-1),'MM/YYYY')       AS MES_ANO
  FROM PARAMS p
  CONNECT BY LEVEL <= MONTHS_BETWEEN(p.D_FIM, p.D_INI) + 1
),



CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.SEXO,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
 CROSS JOIN DATAS_REF M
 CROSS JOIN PARAMS P
 WHERE -- CONTRATOS ATIVOS EM QUALQUER DIA DO MÊS
 CT.DATA_ADMISSAO <= M.DTA_FIM
 AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31') >= M.DTA_INI
/*VERSÕES ALTERNATIVAS DE FILTRAR POR DATA
(('31/03/2025' BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= '31/03/2025' AND CT.DATA_DEMISSAO IS NULL))
AND (CT.DATA_ADMISSAO <= TO_DATE('31/07/2025','DD/MM/YYYY'))
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= TO_DATE('01/07/2025','DD/MM/YYYY'))
AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= '01/07/2025')*/

 AND P.D_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
 AND P.D_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
 AND P.D_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
 AND ORG.COD_EMP = 8
 --AND ORG.COD_TIPO = 1
 AND ORG.EDICAO_ORG_4 IS NOT NULL
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
--AND ORG.COD_UNIDADE = 004
 ORDER BY CT.COD_CONTRATO
),

/*MAPEIA TODOS OS COLABORADORES MAS TAMBÉM COM INFO DE AFASTAMENTO*/
STATUS_AFASTADOS AS (
SELECT DISTINCT ORG.COD_EMP,
                CT.COD_CONTRATO,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFAST,
                AF.DATA_INICIO AS DATA_INI_AFAST,
                AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306                AF,
       RHFP0300                CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT   FN,
       DATAS_REF               M,
       PARAMS                  P
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND CT.DATA_INICIO <= M.DTA_FIM
   AND NVL(CT.DATA_FIM, DATE '2999-12-31') >= M.DTA_INI
      /* AND (CT.DATA_INICIO <= '31/03/2025')
         AND (CT.DATA_INICIO IS NULL OR CT.DATA_FIM >= '01/01/2025')*/
   AND P.D_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND P.D_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND P.D_FIM BETWEEN AF.DATA_INICIO(+) AND
       NVL(AF.DATA_FIM(+), DATE '2999-12-31')
   AND ORG.COD_EMP = 8
   --AND ORG.COD_TIPO = 1
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)

),


VALORES AS (
  SELECT A.COD_CONTRATO, SUM(A.VALOR_VD) AS TOTAL_VALOR
    FROM RHFP1006 A
    JOIN RHFP1003 B
      ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
   CROSS JOIN PARAMS P
   WHERE A.COD_VD = 1001
     AND B.DATA_REFERENCIA >= P.D_INI
     AND B.DATA_REFERENCIA < P.D_FIM + 1
   GROUP BY A.COD_CONTRATO
   
)


SELECT CT.COD_CONTRATO,
       CT.DES_PESSOA,
       CT.DATA_ADMISSAO,
       CT.DATA_DEMISSAO,
       CT.DES_FUNCAO,
       CT.DES_UNIDADE,
       AF.STATUS_AFAST,
       AF.DATA_INI_AFAST,
       AF.DATA_FIM_AFAST,
       TO_CHAR(VL.TOTAL_VALOR, 'FM999G999G990D00') AS RENDIMENTOS       
FROM CONTRATOS CT
JOIN VALORES VL ON CT.COD_CONTRATO = VL.COD_CONTRATO
LEFT JOIN STATUS_AFASTADOS AF ON CT.COD_CONTRATO = AF.COD_CONTRATO
WHERE (CT.DES_FUNCAO LIKE '%GERENTE%'
    OR CT.DES_FUNCAO LIKE '%COMPRADOR%'
    OR CT.DES_FUNCAO LIKE '%SUPERVISOR%'
    OR CT.DES_FUNCAO LIKE '%DIRETOR%')
  AND CT.DES_FUNCAO NOT LIKE '%ASSESOR%'
  --AND VL.TOTAL_VALOR = 0
--AND CT.COD_CONTRATO = 272019
ORDER BY CT.DES_UNIDADE, CT.COD_CONTRATO