---SELECTs PARA CRIAÇÃO DA VIEW === V_LOJAS_ATIVAS


--SELECT PEGANDO OS DADOS DA VIEW DA BASE DO SISLOGWEB

SELECT COD_UNIDADE, 
       DES_FANTASIA, 
       NVL(REDE, 0) REDE,
       DECODE(REDE, 10,'GRAZZIOTIN', 30,'PORMENOS', 40,'FRANCO GIORGI', 50,'TOTTAL', 70,'GZT STORE') DES_REDE,
       NUM_CGC
FROM SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ
WHERE COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549)
ORDER BY COD_UNIDADE ASC

--==============--

--SELECT OFICIAL PARA A CRIAÇÃO DA VIEW === V_LOJAS_ATIVAS


SELECT A2.COD_ORGANOGRAMA,
       A2.COD_PESSOA,
       A1.COD_ORGANOGRAMA_SUB,
       CASE
         WHEN UNI.REDE IN (10, 30, 40, 50) THEN
          LPAD(UNI.COD_UNIDADE, 3, '0')
         WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
          LPAD(UNI.COD_UNIDADE, 3, '0')
         WHEN UNI.REDE = 70 THEN
          LPAD(UNI.COD_UNIDADE, 4, '0')
       END UNIDADE,
       UNI.DES_FANTASIA AS NOME_UNIDADE,
       NVL(UNI.REDE, 0) REDE,
       DECODE(UNI.REDE,
              10,
              'GRAZZIOTIN',
              30,
              'PORMENOS',
              40,
              'FRANCO GIORGI',
              50,
              'TOTTAL',
              70,
              'GZT STORE') DES_REDE,
       UNI.NUM_CGC
       --SUBSTR(A1.EDICAO_ORG, 1, 11)
  FROM SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI, RHFP0401 A1, RHFP0400 A2
 WHERE UNI.COD_UNIDADE = A1.EDICAO_ORG
   AND A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
   AND UNI.COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549, 7549)
   AND A1.COD_ORGANOGRAMA_SUB = 8
 ORDER BY UNI.COD_UNIDADE ASC



--==VERSÃO EM EDIÇÃO=====================--


SELECT
    LOJASATV.COD_ORGANOGRAMA,
    LOJASATV.COD_PESSOA,
    LOJASATV.COD_ORGANOGRAMA_SUB,
    LOJASATV.UNIDADE,
    LOJASATV.NOME_UNIDADE,
    LOJASATV.REDE,
    LOJASATV.DES_REDE,
    LOJASATV.NUM_CGC,
    LOJASATV.EMAIL
FROM (
    SELECT
        A2.COD_ORGANOGRAMA,
        J.COD_PESSOA,
        A1.COD_ORGANOGRAMA_SUB,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END UNIDADE,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END || ' - ' || UNI.DES_FANTASIA AS NOME_UNIDADE,
        NVL(UNI.REDE, 0) REDE,
        DECODE(UNI.REDE,
            10,
            'GRAZZIOTIN',
            30,
            'PORMENOS',
            40,
            'FRANCO GIORGI',
            50,
            'TOTTAL',
            70,
            'GZT STORE') DES_REDE,
        UNI.NUM_CGC,
        J.EMAIL,
        ROW_NUMBER() OVER (PARTITION BY UNI.COD_UNIDADE ORDER BY
            CASE WHEN A2.COD_NIVEL_ORG = 5 AND A3.COD_NIVEL_CONTABIL = 5 THEN 0 ELSE 1 END
        ) AS RN
    FROM
        SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI,
        RHFP0401 A1,
        RHFP0400 A2,
        RHFP0402 A3,
        RHFP0310 B1,
        PESSOA_JURIDICA J
    WHERE
        UNI.COD_UNIDADE = A1.EDICAO_ORG
        AND A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
        AND B1.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND J.CGC = UNI.NUM_CGC
        AND UNI.COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549, 7549)
        AND A2.COD_NIVEL_ORG = 5
        AND A3.COD_NIVEL_CONTABIL = 5
        AND A3.EDICAO_NIVEL5 IS NOT NULL
        AND A2.COD_CUSTO_CONTABIL IS NOT NULL
        AND A1.COD_NIVEL2 <> 282
        AND A1.DATA_FIM = '31/12/2999'
        AND B1.DATA_FIM = '31/12/2999'
        --AND UNI.DES_FANTASIA LIKE '%GZT %'
) LOJASATV
WHERE RN = 1
ORDER BY
    LOJASATV.UNIDADE ASC



 

--===========================--

--TESTANDO...


SELECT * FROM PESSOA_JURIDICA
WHERE NOME_PESSOA LIKE '%569%'


SELECT
    LOJASATV.COD_ORGANOGRAMA,
    LOJASATV.COD_PESSOA,
    LOJASATV.COD_ORGANOGRAMA_SUB,
    LOJASATV.UNIDADE,
    LOJASATV.NOME_UNIDADE,
    LOJASATV.REDE,
    LOJASATV.DES_REDE,
    LOJASATV.NUM_CGC,
    LOJASATV.EMAIL
FROM (
    SELECT
        A2.COD_ORGANOGRAMA,
        J.COD_PESSOA,
        A1.COD_ORGANOGRAMA_SUB,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END UNIDADE,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END || ' - ' || UNI.DES_FANTASIA AS NOME_UNIDADE,
        NVL(UNI.REDE, 0) REDE,
        DECODE(UNI.REDE,
            10,
            'GRAZZIOTIN',
            30,
            'PORMENOS',
            40,
            'FRANCO GIORGI',
            50,
            'TOTTAL',
            70,
            'GZT STORE') DES_REDE,
        UNI.NUM_CGC,
        J.EMAIL,
        ROW_NUMBER() OVER (PARTITION BY UNI.COD_UNIDADE ORDER BY
            CASE WHEN A2.COD_NIVEL_ORG = 5 AND A3.COD_NIVEL_CONTABIL = 5 THEN 0 ELSE 1 END
        ) AS RN
    FROM
        SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI,
        RHFP0401 A1,
        RHFP0400 A2,
        RHFP0402 A3,
        RHFP0310 B1,
        PESSOA_JURIDICA J
    WHERE
        UNI.COD_UNIDADE = A1.EDICAO_ORG
        AND A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
        AND B1.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND J.CGC = UNI.NUM_CGC
        AND UNI.COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549, 7549)
        AND A2.COD_NIVEL_ORG = 5
        AND A3.COD_NIVEL_CONTABIL = 5
        AND A3.EDICAO_NIVEL5 IS NOT NULL
        AND A1.COD_NIVEL2 <> 282
        AND A1.DATA_FIM = '31/12/2999'
        AND B1.DATA_FIM = '31/12/2999'
) LOJASATV
WHERE RN = 1
ORDER BY
    LOJASATV.UNIDADE ASC
    
    
    
    
--===============================--



SELECT
    LOJASATV.COD_ORGANOGRAMA,
    LOJASATV.COD_PESSOA,
    LOJASATV.COD_ORGANOGRAMA_SUB,
    LOJASATV.UNIDADE,
    LOJASATV.NOME_UNIDADE,
    LOJASATV.REDE,
    LOJASATV.DES_REDE,
    LOJASATV.NUM_CGC,
    LOJASATV.EMAIL
FROM (
    SELECT
        A2.COD_ORGANOGRAMA,
        J.COD_PESSOA,
        A1.COD_ORGANOGRAMA_SUB,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END UNIDADE,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END || ' - ' || UNI.DES_FANTASIA AS NOME_UNIDADE,
        NVL(UNI.REDE, 0) REDE,
        DECODE(UNI.REDE,
            10,
            'GRAZZIOTIN',
            30,
            'PORMENOS',
            40,
            'FRANCO GIORGI',
            50,
            'TOTTAL',
            70,
            'GZT STORE') DES_REDE,
        UNI.NUM_CGC,
        J.EMAIL,
        ROW_NUMBER() OVER (PARTITION BY UNI.COD_UNIDADE ORDER BY
            CASE WHEN A2.COD_NIVEL_ORG = 5 AND A3.COD_NIVEL_CONTABIL = 5 THEN 0 ELSE 1 END
        ) AS RN
    FROM
        SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI,
        RHFP0401 A1,
        RHFP0400 A2,
        RHFP0402 A3,
        RHFP0310 B1,
        PESSOA_JURIDICA J
    WHERE
        UNI.COD_UNIDADE = A1.EDICAO_ORG
        AND A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
        AND B1.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND J.CGC = UNI.NUM_CGC
        AND UNI.COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549, 7549)
        AND A2.COD_NIVEL_ORG = 5
        AND A3.COD_NIVEL_CONTABIL = 5
        AND A3.EDICAO_NIVEL5 IS NOT NULL
        AND A1.COD_NIVEL2 <> 282
        AND A1.DATA_FIM = '31/12/2999'
        AND B1.DATA_FIM = '31/12/2999'
        AND (
            (UNI.COD_UNIDADE LIKE '7%' AND B1.DATA_INICIO <= SYSDATE AND (B1.DATA_FIM IS NULL OR B1.DATA_FIM > SYSDATE))
            OR
            (UNI.COD_UNIDADE NOT LIKE '7%')
        )
) LOJASATV
WHERE RN = 1
ORDER BY
    LOJASATV.UNIDADE ASC

    
    
    
    

    
    
    
    
WITH Duplicates AS (
    SELECT
        CALCULATED.COD_ORGANOGRAMA,
        CALCULATED.COD_PESSOA,
        CALCULATED.COD_ORGANOGRAMA_SUB,
        CALCULATED.UNIDADE,
        CALCULATED.NOME_UNIDADE,
        CALCULATED.REDE,
        CALCULATED.DES_REDE,
        CALCULATED.NUM_CGC,
        CALCULATED.EMAIL,
        COUNT(*) OVER (PARTITION BY CALCULATED.UNIDADE) AS DUPLICATE_COUNT
    FROM (
        SELECT
            A2.COD_ORGANOGRAMA,
            J.COD_PESSOA,
            A1.COD_ORGANOGRAMA_SUB,
            CASE
                WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                    LPAD(UNI.COD_UNIDADE, 3, '0')
                WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                    LPAD(UNI.COD_UNIDADE, 3, '0')
                WHEN UNI.REDE = 70 THEN
                    LPAD(UNI.COD_UNIDADE, 4, '0')
            END UNIDADE,
            CASE
                WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                    LPAD(UNI.COD_UNIDADE, 3, '0')
                WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                    LPAD(UNI.COD_UNIDADE, 3, '0')
                WHEN UNI.REDE = 70 THEN
                    LPAD(UNI.COD_UNIDADE, 4, '0')
            END || ' - ' || UNI.DES_FANTASIA AS NOME_UNIDADE,
            NVL(UNI.REDE, 0) REDE,
            DECODE(UNI.REDE,
                10,
                'GRAZZIOTIN',
                30,
                'PORMENOS',
                40,
                'FRANCO GIORGI',
                50,
                'TOTTAL',
                70,
                'GZT STORE') DES_REDE,
            UNI.NUM_CGC,
            J.EMAIL,
            ROW_NUMBER() OVER (PARTITION BY UNI.COD_UNIDADE ORDER BY
                CASE WHEN A2.COD_NIVEL_ORG = 5 AND A3.COD_NIVEL_CONTABIL = 5 THEN 0 ELSE 1 END
            ) AS RN
        FROM
            SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI,
            RHFP0401 A1,
            RHFP0400 A2,
            RHFP0402 A3,
            RHFP0310 B1,
            JURIDICA J
        WHERE
            UNI.COD_UNIDADE = A1.EDICAO_ORG
            AND A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
            AND A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
            AND B1.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
            AND J.CGC = UNI.NUM_CGC
            AND UNI.COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549, 7549)
            AND A2.COD_NIVEL_ORG = 5
            AND A3.COD_NIVEL_CONTABIL = 5
            AND A3.EDICAO_NIVEL5 IS NOT NULL
            AND A1.COD_NIVEL2 <> 282
            AND A1.DATA_FIM = '31/12/2999'
            AND B1.DATA_FIM = '31/12/2999'
    ) CALCULATED
    WHERE RN = 1
)
SELECT *
FROM Duplicates
WHERE DUPLICATE_COUNT > 1
ORDER BY UNIDADE ASC

   


SELECT * FROM RHFP0401
WHERE EDICAO_ORG = 549
ORDER BY EDICAO_ORG

--====--

SELECT * FROM SELORG_FPRE0021A


SELECT A.COD_ORGANOGRAMA, A.NOME_ORGANOGRAMA_E, A.EDICAO
  FROM SELORG_FPRE0021A A, RHFP0310 B, V_DADOS_PESSOA C, RHFP0401 D
 WHERE A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
   AND C.COD_CONTRATO = B.COD_CONTRATO
   AND D.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
   AND D.DATA_FIM = '31/12/2999'
   AND B.DATA_FIM = '31/12/2999'
   AND SUBSTR(A.EDICAO, 1, 11) NOT IN
       ('001.008.001', '001.008.013', '001.006.001', '001.006',
        '001.004.001', '001.004', '001.002.001', '001.002', '001.008', 
'001',
        '001.282.001', '001.276.002')
 GROUP BY A.COD_ORGANOGRAMA, A.NOME_ORGANOGRAMA_E, A.EDICAO
 ORDER BY A.EDICAO ASC