---=========SQL PARA RELATÓRIO DO RESUMO DA FOLHA --AJUSTANDO========--

SELECT A.COD_EVENTO,
       D.NOME_EVENTO,
       A.COD_VD, 
       B.NOME_VD,
       TO_CHAR(SUM(NVL(A.VALOR_VD, 0)), 'FM999G999G990D00') AS "TOTAIS_1005",
       --TO_CHAR(SUM(NVL(E.VALOR_VD, 0)), 'FM999G999G990D00') AS "TOTAIS_1006",
       A.COD_MESTRE_EVENTO,
       C.NOME_MESTRE_EVENTO,
       '01/04/2024' AS "DE",
       '30/04/2024' AS "ATE",
       C.DATA_REFERENCIA
FROM RHFP1005 A,
     RHFP1000 B,
     RHFP1003 C,
     RHFP1002 D
     --RHFP1006 E
WHERE A.COD_VD = B.COD_VD
  AND A.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
  AND A.COD_EVENTO = D.COD_EVENTO
  AND A.COD_MESTRE_EVENTO IN (SELECT COD_MESTRE_EVENTO
                               FROM RHFP1003
                              WHERE TO_DATE(DATA_REFERENCIA) BETWEEN
                                    '01/04/2024' AND '30/04/2024'
                                   --'01/10/2022' AND '31/10/2022'
                                AND COD_ORGANOGRAMA = 8
                                AND COD_EVENTO = 1)
  --AND A.COD_MESTRE_EVENTO = E.COD_MESTRE_EVENTO
GROUP BY A.COD_EVENTO,
         D.NOME_EVENTO,
         A.COD_VD, 
         B.NOME_VD,
         A.COD_MESTRE_EVENTO,
         C.NOME_MESTRE_EVENTO,
         C.DATA_REFERENCIA
ORDER BY A.COD_VD ASC;

SELECT * FROM RHFP1006