/*PROCESSO PARA ALTERAR CÓDIGO DE CANDIDATO DE 1 PARA 0 - A PRINCÍPIO, 
  ESSA É A CAUSA PARA OS CASOS DE COLABOADORES QUE REALIZARAM FICHA ATRAVÉS DO TRABALHE CONOSO, 
  E RESPONSÁVEL POR OCASIONAR O PROBLEMA DE INDICAR DEFICIENCIA PARA A PESSOA MESMO NÃO EXISTINDO*/
  
SELECT A.*, ROWID FROM RHFP0200 A
WHERE A.COD_FUNC = 4312948

--COLUNA CANDIDATO DE 1 PARA 0 --RESILVE O PROBLEMA DE CONTINUAÇÃO DE CADASTRO DE PESSOA FÍSICA NO SISTEMA