CREATE OR REPLACE VIEW V_RESP_ORGANOGRAMAS_AVT AS
--MAPEIAS OS RESPONSÁVEIS PELOS ORGANOGRAMAS, INCOMPLETO POIS HÁ LOCAIS SEM GERENTE/RESPONSÁVEL
SELECT DISTINCT RESP.COD_CONTRATO_RESP,
                PE.NOME_PESSOA,
                RESP.COD_ORGANOGRAMA_RESP,
                ORG.COD_ORGANOGRAMA,
                ORG.UNIDADE,
                ORG.NOME_UNIDADE,
                ORG.COD_REDE_LOCAL,
                ORG.DES_REDE_SETOR
  FROM RHFP0397 RESP
  JOIN V_DADOS_ORGANOGRAMAS_AVT ORG ON RESP.COD_ORGANOGRAMA =
                                       ORG.COD_ORGANOGRAMA
  JOIN RHFP0300 CT ON CT.COD_CONTRATO = RESP.COD_CONTRATO_RESP
  JOIN PESSOA PE ON PE.COD_PESSOA = CT.COD_FUNC
  JOIN OPERORG OP ON OP.COD_ORGANOGRAMA = RESP.COD_ORGANOGRAMA
 WHERE RESP.DATA_FIM = '31/12/2999'
 ORDER BY LPAD(ORG.UNIDADE, 4, '0') ASC;