---TABELA CENTRO DE CUSTO DOS GESTORES CENTRO DE CUSTOS POR NIVEIS

CREATE TABLE GRZ_GESTORES_GRUPO (
COD_CONTRATO NUMBER(8),
DES_GESTOR VARCHAR2(200),
CPF VARCHAR2(15),
COD_FUNCAO NUMBER(5),
DES_FUNCAO VARCHAR2(150),
COD_UNIDADE NUMBER(6),
DES_UNIDADE VARCHAR2(200),
TIPO_LOCAL VARCHAR2(50),
COD_UNIDADE_SUB VARCHAR2(10),
PRIMARY KEY (COD_CONTRATO, COD_UNIDADE)
);