--SELECT PARA CONSULATAR BEM AO CERTO A TABELA E O COD_MESTRE_EVENTO

SELECT * FROM RHFP1003
WHERE COD_MESTRE_EVENTO = 14996

------

--UPDATE PARA ALTERAR O CAMPO 'SITUAÇÃO' NO FORMS, E PRA ISSO DEVE-SE ALTERAR A COLUNA SITUACAO_PROCESSO
--QUE PROVAVELMENTE ESTARÁ COMO 'C' - CALCULADO, COM ISSO DEVE SER ALTERADO PARA 'I' - INCORPORADO

UPDATE RHFP1003
SET SITUACAO_PROCESSO = 'I'
WHERE COD_MESTRE_EVENTO = 14996 