SELECT ORG.COD_UNIDADE,
       ORG.DES_UNIDADE,
       A.COD_CONTRATO,
       CT.DES_PESSOA,
       CT.DATA_ADMISSAO,
       CT.DATA_DEMISSAO,
       FN.DES_FUNCAO,
       HR.HR_BASE_MES,
       HR.HR_BASE_SEM,
       HR.HR_BASE_DIA,
       --A.COD_VD,
       MAX(CASE
             WHEN A.COD_VD = 838 THEN
              A.QTDE_VD
             ELSE
              NULL
           END) AS HORAS_OPERACAO,
       TO_CHAR(SUM(CASE
              WHEN A.COD_VD IN (37,38) THEN
               NVL(A.VALOR_VD, 0)
              ELSE
               0
            END), 'FM999G999G990D00') AS VALOR_OCX,
       /*COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 220 THEN A.COD_CONTRATO END) AS QTD_220,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 200 THEN A.COD_CONTRATO END) AS QTD_200,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 195 THEN A.COD_CONTRATO END) AS QTD_195,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 180 THEN A.COD_CONTRATO END) AS QTD_180,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 165 THEN A.COD_CONTRATO END) AS QTD_165,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 160 THEN A.COD_CONTRATO END) AS QTD_160,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 150 THEN A.COD_CONTRATO END) AS QTD_150,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 140 THEN A.COD_CONTRATO END) AS QTD_140,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 125 THEN A.COD_CONTRATO END) AS QTD_125,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 120 THEN A.COD_CONTRATO END) AS QTD_120,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 110 THEN A.COD_CONTRATO END) AS QTD_110,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 105 THEN A.COD_CONTRATO END) AS QTD_105,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 100 THEN A.COD_CONTRATO END) AS QTD_100,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 80  THEN A.COD_CONTRATO END) AS QTD_80,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 60  THEN A.COD_CONTRATO END) AS QTD_60,
       COUNT(DISTINCT CASE WHEN HR.HR_BASE_MES = 40  THEN A.COD_CONTRATO END) AS QTD_40,*/
       COUNT(DISTINCT A.COD_CONTRATO) AS QTD_COLAB_QCX,
       --B.DATA_REFERENCIA,
       CASE
           WHEN :HORAS_MES = 0
           THEN 'Geral (todas as cargas horárias)'
           ELSE
            'Carga horária: ' || TO_CHAR(:HORAS_MES)
       END AS INFO_CARGA,

       :DATA_INICIO || ' à ' || :DATA_FIM AS PERIODO_INFO
  FROM RHFP1006 A
 INNER JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
  LEFT JOIN RHFP1000 C ON A.COD_VD = C.COD_VD
 INNER JOIN V_DADOS_CONTRATO_AVT CT ON A.COD_CONTRATO = CT.COD_CONTRATO
 INNER JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
  LEFT JOIN VH_HIST_HORAS_COLAB_AVT HR ON A.COD_CONTRATO = HR.COD_CONTRATO
  LEFT JOIN VH_CARGO_CONTRATO_AVT FN ON A.COD_CONTRATO = FN.COD_CONTRATO
 WHERE B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND (B.DATA_REFERENCIA BETWEEN CT.DATA_ADMISSAO AND
       NVL(CT.DATA_DEMISSAO, TRUNC(SYSDATE)))
   AND B.DATA_REFERENCIA BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND B.DATA_REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND B.DATA_REFERENCIA BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
   AND B.COD_EVENTO = 1
   AND A.COD_VD IN (38, 37, 838)
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (HR.HR_BASE_MES = :HORAS_MES OR :HORAS_MES = 0)
 GROUP BY A.COD_CONTRATO,
          CT.DES_PESSOA,
          CT.DATA_ADMISSAO,
          CT.DATA_DEMISSAO,
          FN.DES_FUNCAO,
          HR.HR_BASE_MES,
          HR.HR_BASE_SEM,
          HR.HR_BASE_DIA,
          ORG.COD_UNIDADE,
          ORG.DES_UNIDADE,
          --A.COD_VD,
          B.DATA_REFERENCIA
 ORDER BY ORG.COD_UNIDADE, B.DATA_REFERENCIA


