WITH
-- Subconsulta para obter a quantidade total de contratos por unidade
Total_Contratos_Unidade AS (
    SELECT
        D.COD_UNIDADE,
        D.COD_ORGANOGRAMA,
        COUNT(DISTINCT D.COD_CONTRATO) AS QTDE_TOTAL_CONTRATOS
    FROM V_DADOS_PESSOA_ALTER_AVT D
    LEFT JOIN RHFP1006 A ON A.COD_CONTRATO = D.COD_CONTRATO
    WHERE D.COD_EMP = '008'
    GROUP BY D.COD_UNIDADE, D.COD_ORGANOGRAMA, D.COD_REDE_LOCAL
),

-- Subconsulta para obter a quantidade de contratos com absenteísmo por unidade
Contratos_Absenteismo_Unidade AS (
    SELECT
        D.COD_UNIDADE,
        D.COD_ORGANOGRAMA,
        B.DATA_REFERENCIA,
        COUNT(DISTINCT A.COD_CONTRATO) AS QTDE_CONTRATOS_ABS,
        SUM(CASE WHEN A.COD_VD IN (631, 632, 831, 832) THEN A.QTDE_VD ELSE 0 END) AS TOTAL_FALTAS_UNID,
        SUM(CASE WHEN A.COD_VD = 897 THEN A.QTDE_VD ELSE 0 END) AS TOTAL_ATESTADOS_UNID
    FROM RHFP1006 A
    LEFT JOIN V_DADOS_PESSOA_ALTER_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO
    INNER JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    WHERE D.COD_EMP = '008'
        AND B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
        AND A.COD_VD IN (631, 632, 831, 832, 897)
    GROUP BY D.COD_UNIDADE, D.COD_ORGANOGRAMA, D.COD_REDE_LOCAL, B.DATA_REFERENCIA
)

-- Consulta final para unidades
SELECT
    D.COD_ORGANOGRAMA,
    D.COD_UNIDADE,
    D.DES_UNIDADE,
    D.COD_REDE_LOCAL,
    MAX(D.DES_REDE_LOCAL) AS DES_REDE_LOCAL,
    B.DATA_REFERENCIA,
    CASE
       WHEN EXTRACT(DAY FROM B.DATA_REFERENCIA) IN (30, 31) THEN NULL
       WHEN EXTRACT(MONTH FROM B.DATA_REFERENCIA) = 2 AND
          ((MOD(EXTRACT(YEAR FROM B.DATA_REFERENCIA), 4) = 0 AND MOD(EXTRACT(YEAR FROM B.DATA_REFERENCIA), 100) != 0) OR
           (MOD(EXTRACT(YEAR FROM B.DATA_REFERENCIA), 400) = 0)) AND EXTRACT(DAY FROM B.DATA_REFERENCIA) = 29 THEN NULL
       WHEN EXTRACT(MONTH FROM B.DATA_REFERENCIA) = 2 AND EXTRACT(DAY FROM B.DATA_REFERENCIA) = 28 THEN NULL
       ELSE B.DATA_REFERENCIA
    END AS DATA_REFERENCIA_VERIFICADA,
    INITCAP(TRIM(TO_CHAR(B.DATA_REFERENCIA, 'MONTH'))) || '/' || TO_CHAR(B.DATA_REFERENCIA, 'YYYY') AS REFERENCIA,
    MAX(TU.QTDE_TOTAL_CONTRATOS) AS QTDE_CONTR_UNID,
    MAX(CAU.QTDE_CONTRATOS_ABS) AS QTDE_ABS_UNID,
    TO_CHAR(MAX(CAU.TOTAL_FALTAS_UNID), 'FM999G999G990D00') AS FALTAS_UNID,
    TO_CHAR(MAX(CAU.TOTAL_ATESTADOS_UNID), 'FM999G999G990D00') AS ATESTADOS_UNID,
    'Período informado: ' || TO_CHAR(:DATA_INICIO, 'DD/MM/YYYY') || ' à ' || TO_CHAR(:DATA_FIM, 'DD/MM/YYYY') AS PERIODO
FROM
    V_DADOS_PESSOA_ALTER_AVT D
    LEFT JOIN RHFP1006 A ON A.COD_CONTRATO = D.COD_CONTRATO
    LEFT JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    LEFT JOIN Total_Contratos_Unidade TU ON D.COD_UNIDADE = TU.COD_UNIDADE AND D.COD_ORGANOGRAMA = TU.COD_ORGANOGRAMA
    LEFT JOIN Contratos_Absenteismo_Unidade CAU ON D.COD_UNIDADE = CAU.COD_UNIDADE AND D.COD_ORGANOGRAMA = CAU.COD_ORGANOGRAMA AND B.DATA_REFERENCIA = CAU.DATA_REFERENCIA
WHERE B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
    AND A.COD_VD IN (631, 632, 831, 832, 897)
    AND D.COD_EMP = '008'
GROUP BY D.COD_UNIDADE,
         D.DES_UNIDADE,
         D.COD_REDE_LOCAL,
         D.COD_ORGANOGRAMA,
         B.DATA_REFERENCIA
ORDER BY D.COD_UNIDADE, D.COD_ORGANOGRAMA, B.DATA_REFERENCIA
