WITH
/* BLOCO PARA ENTRADA DE PARÂMETROS (DINÂMICO POR PERÍODO) */
PARAMS AS (

/*VERSÃO PARA USAR NO PL/SQL*/
  /*SELECT TO_DATE('&DATA_INICIO', 'DD/MM/YYYY') AS DATA_INICIO,
       TO_DATE('&DATA_FIM', 'DD/MM/YYYY') AS DATA_FIM
  FROM DUAL*/

/* SELECT --:REFERENCIA AS REFERENCIA
         TO_DATE('&REFERENCIA', 'DD/MM/YYYY') AS REFERENCIA
  FROM DUAL*/


/*VERSÃO PARA USAR NO SAPINHO E DENTRO DA FOLHA*/
SELECT :DATA_INICIO AS DATA_INICIO,
       :DATA_FIM AS DATA_FIM
FROM DUAL

),

CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.SEXO,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
 CROSS JOIN PARAMS P
 WHERE CT.DATA_ADMISSAO <= P.DATA_FIM
  AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31') >= P.DATA_INICIO

/* CT.DATA_ADMISSAO <= P.DATA_INICIO
 AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31') >= P.DATA_FIM*/
 --AND P.REFERENCIA BETWEEN CT.DATA_ADMISSAO AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31')
/*VERSÕES ALTERNATIVAS DE FILTRAR POR DATA
(('31/03/2025' BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= '31/03/2025' AND CT.DATA_DEMISSAO IS NULL))
AND (CT.DATA_ADMISSAO <= TO_DATE('31/07/2025','DD/MM/YYYY'))
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= TO_DATE('01/07/2025','DD/MM/YYYY'))
AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= '01/07/2025')*/

  AND P.DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
  AND P.DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
  AND P.DATA_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR

  /*AND ORG.DATA_INI_ORG <= P.DATA_FIM AND ORG.DATA_FIM_ORG >= P.DATA_INICIO
  AND FN.DATA_INI_CLH  <= P.DATA_FIM AND FN.DATA_FIM_CLH  >= P.DATA_INICIO
  AND HR.DATA_INI_HR   <= P.DATA_FIM AND HR.DATA_FIM_HR   >= P.DATA_INICIO*/

  --AND (ORG.COD_EMP = &EMPRESA OR &EMPRESA = 0)
  --AND (ORG.COD_EMP = :EMPRESA OR :EMPRESA = 0)
 --AND ORG.COD_TIPO = 1
  AND ORG.EDICAO_ORG_4 IS NOT NULL
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
--AND ORG.COD_UNIDADE = 004
 ORDER BY CT.COD_CONTRATO

),

MOVIMENTACOES AS (
SELECT A.COD_SOLICITACAO,
       C.COD_CONTRATO AS SOLICITANTE,
       I.NOME_PESSOA AS DES_SOLICITANTE,
       DECODE(c.TIPO_SOLICITACAO, 'M', 'Movimentação', 'D', 'Demissional') AS TIPO_SOLICITACAO,
       C.DATA_SOLICITACAO,
       A.COD_CONTRATO AS CONTRATO_MOVIMENTADO,
       A.HORARIO AS HORA_SOLICITACAO,
       y.DATA_CONCLUSAO_EFET,
       y.COD_EXEC_PROC,
       A.JUSTIFICATIVA
  FROM RHWF0312 A, RHWF0310 C, RHWF0250 Y, RHFP0300 R, PESSOA I, PARAMS P
 WHERE C.COD_SOLICITACAO = A.COD_SOLICITACAO
   AND A.IND_HORARIO = 'S'
   AND Y.COD_MOVIMENTACAO = C.COD_SOLICITACAO
   AND R.COD_CONTRATO = C.COD_CONTRATO
   AND R.COD_FUNC = I.COD_PESSOA
   AND C.DATA_SOLICITACAO BETWEEN P.DATA_INICIO AND P.DATA_FIM
 ORDER BY A.COD_SOLICITACAO, A.COD_CONTRATO

)

SELECT A.COD_SOLICITACAO,
       A.SOLICITANTE,
       A.DES_SOLICITANTE,
       A.COD_SOLICITACAO,
       A.DATA_SOLICITACAO,
       A.HORA_SOLICITACAO,
       A.TIPO_SOLICITACAO,
       A.CONTRATO_MOVIMENTADO,
       B.DES_PESSOA AS PESSOA_MOVIMENTADO,
       B.COD_FILIAL || ' - ' || B.DES_FILIAL AS FILIAL,
       B.COD_UNIDADE,
       B.DES_UNIDADE,
       A.DATA_CONCLUSAO_EFET,
       A.COD_EXEC_PROC,
       A.JUSTIFICATIVA
FROM MOVIMENTACOES A
JOIN CONTRATOS B ON A.CONTRATO_MOVIMENTADO = B.COD_CONTRATO
WHERE (B.COD_EMP = :EMPRESA OR :EMPRESA = 0)--(B.COD_EMP = &EMPRESA OR &EMPRESA = 0)
  AND (B.COD_TIPO = :TIPO OR :TIPO = 0)--AND (B.COD_TIPO = &TIPO OR &TIPO = 0)
  AND (B.COD_REDE = :REDE OR :REDE = 0)--AND (B.COD_REDE = &REDE OR &REDE = 0)
  AND (B.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)--AND (B.COD_UNIDADE = &UNIDADE OR &UNIDADE = 0)
ORDER BY A.DATA_SOLICITACAO, A.SOLICITANTE;
