WITH BASE_DADOS AS (
    SELECT
        A.COD_CID_10,
        B.NOME_CID_10,
        A.DATA_INICIO,
        C.COD_TIPO,
        C.COD_REDE,
        C.DES_REDE,
        C.COD_EMP
    FROM RHFP0306 A
    LEFT JOIN RHFP0310 ORG
        ON A.COD_CONTRATO = ORG.COD_CONTRATO AND :DATA_FIM BETWEEN ORG.DATA_INICIO AND ORG.DATA_FIM
    LEFT JOIN VH_EST_ORG_CONTRATO_AVT C
        ON ORG.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
    LEFT JOIN RHMS0180 B
        ON A.COD_CID_10 = B.COD_CID_10
    WHERE A.COD_CID_10 IS NOT NULL
      AND A.DATA_INICIO BETWEEN :DATA_INICIO AND :DATA_FIM
      AND (C.COD_TIPO = :TIPO OR :TIPO = 0)
      --AND (C.COD_UNIDADE = :FILIAL OR :FILIAL = 0)
      AND (C.COD_REDE = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
      AND C.COD_EMP = 8
      AND (:COD_UNIDADE = '0' OR C.COD_UNIDADE IN (SELECT * FROM TABLE(SPLIT_CONTRACTS(:COD_UNIDADE))))
),

RESUMO_POR_LETRA_MES AS (
    SELECT
        COD_TIPO,
        COD_REDE,
        DES_REDE,
        SUBSTR(COD_CID_10, 1, 1) AS LETRA_CID,
        TO_CHAR(DATA_INICIO, 'MM/YYYY') AS MES_ANO,
        INITCAP(TRIM(TO_CHAR(DATA_INICIO, 'Month', 'NLS_DATE_LANGUAGE=PORTUGUESE'))) || '/' || TO_CHAR(DATA_INICIO, 'YYYY') AS MES_ANO_EXTENSO,
        COUNT(DISTINCT COD_CID_10 || '-' || COD_REDE) AS TOTAL_POR_LETRA,
        'De ' || :DATA_INICIO || ' até ' || :DATA_FIM AS REFERENCIA
    FROM BASE_DADOS
    GROUP BY
        COD_TIPO,
        COD_REDE,
        DES_REDE,
        SUBSTR(COD_CID_10, 1, 1),
        TO_CHAR(DATA_INICIO, 'MM/YYYY'),
        TO_CHAR(DATA_INICIO, 'Month', 'NLS_DATE_LANGUAGE=PORTUGUESE'),
        TO_CHAR(DATA_INICIO, 'YYYY')
),

CID_MENSAL AS (
    SELECT
        COD_TIPO,
        COD_REDE,
        DES_REDE,
        COD_CID_10 AS COD_CID,
        NOME_CID_10 AS DES_CID,
        SUBSTR(COD_CID_10, 1, 1) AS LETRA_CID,
        TO_CHAR(DATA_INICIO, 'MM/YYYY') AS MES_ANO,
        INITCAP(TRIM(TO_CHAR(DATA_INICIO, 'Month', 'NLS_DATE_LANGUAGE=PORTUGUESE'))) || '/' || TO_CHAR(DATA_INICIO, 'YYYY') AS MES_ANO_EXTENSO,
        COUNT(DISTINCT COD_CID_10) AS QTD_CID,
        'De ' || :DATA_INICIO || ' até ' || :DATA_FIM AS REFERENCIA
    FROM BASE_DADOS
    GROUP BY
        COD_TIPO,
        COD_CID_10,
        NOME_CID_10,
        COD_REDE,
        DES_REDE,
        SUBSTR(COD_CID_10, 1, 1),
        TO_CHAR(DATA_INICIO, 'MM/YYYY'),
        TO_CHAR(DATA_INICIO, 'Month', 'NLS_DATE_LANGUAGE=PORTUGUESE'),
        TO_CHAR(DATA_INICIO, 'YYYY')
),

TOTAIS_GERAIS AS (
    SELECT
        SUM(CASE WHEN COD_TIPO = 1 THEN 1 ELSE 0 END) AS TOT_TIPO_1,
        SUM(CASE WHEN COD_TIPO = 2 THEN 1 ELSE 0 END) AS TOT_TIPO_2,
        SUM(CASE WHEN COD_TIPO = 3 THEN 1 ELSE 0 END) AS TOT_TIPO_3,

        SUM(CASE WHEN COD_REDE = '10' THEN 1 ELSE 0 END) AS TOT_GRZ,
        SUM(CASE WHEN COD_REDE = '30' THEN 1 ELSE 0 END) AS TOT_PORMENOS,
        SUM(CASE WHEN COD_REDE = '40' THEN 1 ELSE 0 END) AS TOT_FRANCO,
        SUM(CASE WHEN COD_REDE = '70' THEN 1 ELSE 0 END) AS TOT_TOTAL,
        SUM(CASE WHEN COD_REDE = '50' THEN 1 ELSE 0 END) AS TOT_GZT
    FROM (
        SELECT DISTINCT COD_CID_10, COD_TIPO, COD_REDE FROM BASE_DADOS
    )
)

SELECT DISTINCT
    A.MES_ANO,
    A.MES_ANO_EXTENSO,
    A.COD_TIPO,
    CASE
        WHEN A.COD_TIPO = 1 THEN
         'RELAÇÃO LOJAS'
        WHEN A.COD_TIPO = 2 THEN
         'RELAÇÃO ADMINISTRAÇÃO'
        WHEN A.COD_TIPO = 3 THEN
         'RELAÇÃO LOGÍSTICA'
        ELSE
         NULL
    END AS DES_TIPO,
    A.COD_REDE,
    A.DES_REDE,
    A.LETRA_CID,
    A.TOTAL_POR_LETRA,
    ' ..... ' AS ESPACO,
    B.COD_CID,
    B.DES_CID,
    'TOTAIS =>' AS TOTAIS,
    TG.TOT_TIPO_1 AS TOT_LOJAS,
    TG.TOT_TIPO_2 AS TOT_ADM,
    TG.TOT_TIPO_3 AS TOT_CD,
    TG.TOT_GRZ,
    TG.TOT_PORMENOS,
    TG.TOT_FRANCO,
    TG.TOT_TOTAL,
    TG.TOT_GZT,
    A.REFERENCIA
FROM RESUMO_POR_LETRA_MES A
LEFT JOIN CID_MENSAL B
  ON A.COD_TIPO = B.COD_TIPO
 AND A.COD_REDE = B.COD_REDE
 AND A.MES_ANO = B.MES_ANO
 AND A.LETRA_CID = B.LETRA_CID
LEFT JOIN TOTAIS_GERAIS TG ON 1 = 1
ORDER BY A.MES_ANO, A.COD_TIPO, A.COD_REDE, A.LETRA_CID, B.COD_CID

