WITH
CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                CT.COD_VINCULO_EMPREG,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.DES_DEFICIENCIA,
                CT.SEXO,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
 FROM V_DADOS_CONTRATO_AVT    CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_HIST_HORAS_COLAB_AVT HR,
       VH_CARGO_CONTRATO_AVT   FN
 WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
   AND CT.COD_CONTRATO = HR.COD_CONTRATO
   AND CT.COD_CONTRATO = FN.COD_CONTRATO
   /*AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= TO_DATE('01/07/2025', 'DD/MM/YYYY')) --VESÃO ALTERNATIVA, PARA RETORNAR ATÉ QUEM JÁ FOI DEMITIDO ATÉ A DATA_DEMISSAO*/
   /*AND (('24/07/2025' BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= '24/07/2025' AND CT.DATA_DEMISSAO IS NULL))*/ -- VERSÃO GERAL
   AND CT.DATA_ADMISSAO BETWEEN :ADMISSAO_INICIO AND :ADMISSAO_FIM
   AND :ADMISSAO_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND :ADMISSAO_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :ADMISSAO_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
   AND ORG.COD_EMP = 8
   --AND ORG.COD_TIPO = 1
   AND ORG.EDICAO_ORG_4 IS NOT NULL
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   --AND ORG.COD_UNIDADE = 004
   --AND CT.COD_CONTRATO IN (397318, 397330)
 ORDER BY CT.COD_CONTRATO

),

STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_ORGANOGRAMA,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST,
       AF.DATA_INICIO AS DATA_INI_AFAST,
       AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND ((:ADMISSAO_FIM BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= :ADMISSAO_FIM AND CT.DATA_FIM IS NULL))
   AND :ADMISSAO_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :ADMISSAO_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND :ADMISSAO_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   AND ORG.COD_EMP = 8
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   --AND ORG.COD_TIPO = 1
),


EXPERIENCIA AS (
SELECT A.COD_CONTRATO,
       A.DATA_INICIO AS DATA_INI_CONT,
       A.DATA_FIM AS DATA_FIM_CONT,
       E.DATA_INICIO AS DATA_ADMISSAO,
       E.DATA_FIM AS DATA_DEMISSAO,
       TO_NUMBER(TO_CHAR(A.DATA_INICIO, 'DD')) AS DIA_INICIO,
       TO_NUMBER(TO_CHAR(A.DATA_INICIO, 'MM')) AS MES_INICIO,
       TO_NUMBER(TO_CHAR(A.DATA_INICIO, 'YYYY')) AS ANO_INICIO,
       TO_NUMBER(TO_CHAR(A.DATA_FIM, 'DD')) AS DIA_FIM,
       TO_NUMBER(TO_CHAR(A.DATA_FIM, 'MM')) AS MES_FIM,
       TO_NUMBER(TO_CHAR(A.DATA_FIM, 'YYYY')) AS ANO_FIM,
       TO_NUMBER(TRUNC(A.DATA_FIM - A.DATA_INICIO) + 1) || ' dias' AS DIAS_CONTRATO,
       A.COD_TP_CONTRATO,
       A.IND_ENCERRADO,
       B.DATA_AVALIACAO,
       --RHFP0305.IND_AVALIACAO,
       C.NOME_TP_CONTRATO,
       C.COD_TIPO_CONTRATO,
       D.NOME_TIPO_CONTRATO,
       C.NUM_DIAS,
       C.IND_AVALIACOES
  FROM RHFP0304 A,
       RHFP0305 B,
       RHFP0314 C,
       RHFP0116 D,
       RHFP0300 E
 WHERE A.DATA_FIM BETWEEN :TERMINO_INICIO AND :TERMINO_FIM
   AND B.COD_CONTRATO(+) = A.COD_CONTRATO
   AND B.DATA_INICIO(+) = A.DATA_INICIO
   AND A.COD_TP_CONTRATO = C.COD_TP_CONTRATO
   AND C.COD_TIPO_CONTRATO = D.COD_TIPO_CONTRATO
   AND A.COD_CONTRATO = E.COD_CONTRATO

),

QTD_CONTRATOS AS (
SELECT COD_EMP,
       COUNT(CASE
                 WHEN DATA_DEMISSAO IS NOT NULL THEN
                  COD_CONTRATO
                 ELSE
                  NULL
             END) AS QTD_DEMITIDOS,
        COUNT(CASE
                 WHEN DATA_DEMISSAO IS NULL THEN
                  COD_CONTRATO
                 ELSE
                  NULL
             END) AS QTD_ADMITIDOS,
             
        COUNT(DISTINCT COD_CONTRATO) AS QTD_TOT_CONTRATOS
FROM CONTRATOS
GROUP BY COD_EMP
)


SELECT CT.COD_CONTRATO,
       CT.COD_CONTRATO || ' - ' || CT.DES_PESSOA AS COLABORADOR,
       CT.DATA_ADMISSAO AS ADMISSAO,
       CT.DATA_DEMISSAO AS DEMISSAO,
       CT.COD_VINCULO_EMPREG,
       CT.DES_FUNCAO,
       CT.HR_BASE_MES,
       CT.IND_DEFICIENCIA,
       CT.DES_DEFICIENCIA,
       CT.SEXO,
       CT.EDICAO_EMP,
       CT.DES_EMP,
       CT.COD_REDE,
       CT.DES_REDE,
       CT.COD_UNIDADE,
       CT.DES_UNIDADE,
       EX.DATA_INI_CONT,
       EX.DATA_FIM_CONT,
       EX.DIAS_CONTRATO,
       EX.IND_ENCERRADO,
       EX.DATA_AVALIACAO,
       EX.COD_TIPO_CONTRATO,
       EX.NOME_TIPO_CONTRATO,
       EX.IND_AVALIACOES,
       QC.QTD_DEMITIDOS,
       QC.QTD_ADMITIDOS,
       QC.QTD_TOT_CONTRATOS,

       :ADMISSAO_INICIO || ' - ' || :ADMISSAO_FIM AS PERIODO_ADMISSAO,
       :TERMINO_INICIO || ' - ' || :TERMINO_FIM AS PERIODO_CONTRATO,
       'TIPO: ' || :TIPO || ' | ' || 'UNIDADE: ' || :UNIDADE ||
       ' | ' || 'REDE: ' || :REDE AS PARAMETROS

  FROM CONTRATOS CT
  LEFT JOIN STATUS_AFASTADOS AF ON CT.COD_CONTRATO = AF.COD_CONTRATO
  JOIN EXPERIENCIA EX ON CT.COD_CONTRATO = EX.COD_CONTRATO
  LEFT JOIN QTD_CONTRATOS QC ON CT.COD_EMP = QC.COD_EMP
  WHERE (CT.COD_TIPO = :TIPO OR :TIPO = 0)
    AND (CT.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (CT.COD_REDE = :REDE OR :REDE = 0)
  ORDER BY EX.DATA_FIM_CONT, CT.COD_UNIDADE
