WITH Rescisao_Valores AS (
    SELECT
        TO_CHAR(B.DATA_INI_MOV, 'MM/YYYY') AS MES_ANO,


        -- Valor total de rescisão
        SUM(TO_NUMBER(A.VALOR_VD)) AS VLR_TOT_RESCISAO,

        -- Valor de rescisão específico para cada causa de demissão
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 10 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_10,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 11 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_11,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 12 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_12,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 13 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_13,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 14 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_14,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 21 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_21,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 33 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_33

    FROM
        RHFP1006 A
    INNER JOIN
        RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
     LEFT JOIN RHFP0300 C ON A.COD_CONTRATO = C.COD_CONTRATO AND C.DATA_FIM IS NOT NULL
     LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON C.COD_CONTRATO = ORG.COD_CONTRATO AND ORG.DATA_FIM_ORG = '31/12/2999'
    WHERE
        B.DATA_INI_MOV >= TRUNC(TO_DATE(:MES_ANO_INICIO, 'MM/YYYY'), 'MM') -- Primeiro dia do mês inicial
        AND B.DATA_INI_MOV <= LAST_DAY(TO_DATE(:MES_ANO_FIM, 'MM/YYYY'))  -- Último dia do mês final
        AND B.COD_EVENTO = 17
        AND A.COD_VD = 1003
        --AND B.COD_ORGANOGRAMA IN (8, 276, 282, 1629)
        AND (B.COD_ORGANOGRAMA = :EMPRESA OR :EMPRESA = 0)
        AND (ORG.COD_TIPO = :TIPO OR :TIPO = 0)
        AND (ORG.COD_UNIDADE = :FILIAL OR :FILIAL = 0)
        AND (ORG.COD_REDE = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
    GROUP BY
        TO_CHAR(B.DATA_INI_MOV, 'MM/YYYY')
),

Demissoes_Causas AS (
    SELECT
        TO_CHAR(TO_DATE(DATA_RESCISAO, 'MM/YYYY'), 'MM/YYYY') AS MES_ANO,

        -- Contagem das demissões por causa
        SUM(DEMISSAO_COD_10) AS DEMISSAO_COD_10,
        SUM(DEMISSAO_COD_11) AS DEMISSAO_COD_11,
        SUM(DEMISSAO_COD_12) AS DEMISSAO_COD_12,
        SUM(DEMISSAO_COD_13) AS DEMISSAO_COD_13,
        SUM(DEMISSAO_COD_14) AS DEMISSAO_COD_14,
        SUM(DEMISSAO_COD_21) AS DEMISSAO_COD_21,
        SUM(DEMISSAO_COD_33) AS DEMISSAO_COD_33,

        -- Total de demissões para o mês
        SUM(TOTAL_DEMISSOES) AS TOTAL_DEMISSOES
    FROM
        V_QTDE_DEMISSOES_AVT
    WHERE
        TO_DATE(DATA_RESCISAO, 'MM/YYYY') BETWEEN TRUNC(TO_DATE(:MES_ANO_INICIO, 'MM/YYYY'), 'MM')
    AND LAST_DAY(TO_DATE(:MES_ANO_FIM, 'MM/YYYY'))
    AND (COD_EMP = :EMPRESA OR :EMPRESA = 0)
    AND (COD_TIPO = :TIPO OR :TIPO = 0)
    AND (COD_UNIDADE = :FILIAL OR :FILIAL = 0)
    AND (COD_REDE = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
    GROUP BY
        TO_CHAR(TO_DATE(DATA_RESCISAO, 'MM/YYYY'), 'MM/YYYY')
),

Totais AS (
    SELECT
        -- Total geral de valor de rescisão
        SUM(R.VLR_TOT_RESCISAO) AS TOTAL_VLR_TOT_RESCISAO,

        -- Totais gerais para quantidade, valor e percentuais de cada causa de demissão
        SUM(D.DEMISSAO_COD_10) AS TOTAL_DEMISSAO_COD_10,
        SUM(R.VLR_RESCISAO_COD_10) AS TOTAL_VLR_RESCISAO_COD_10,
        ROUND(SUM(R.VLR_RESCISAO_COD_10) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_10,

        SUM(D.DEMISSAO_COD_11) AS TOTAL_DEMISSAO_COD_11,
        SUM(R.VLR_RESCISAO_COD_11) AS TOTAL_VLR_RESCISAO_COD_11,
        ROUND(SUM(R.VLR_RESCISAO_COD_11) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_11,

        SUM(D.DEMISSAO_COD_12) AS TOTAL_DEMISSAO_COD_12,
        SUM(R.VLR_RESCISAO_COD_12) AS TOTAL_VLR_RESCISAO_COD_12,
        ROUND(SUM(R.VLR_RESCISAO_COD_12) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_12,

        SUM(D.DEMISSAO_COD_13) AS TOTAL_DEMISSAO_COD_13,
        SUM(R.VLR_RESCISAO_COD_13) AS TOTAL_VLR_RESCISAO_COD_13,
        ROUND(SUM(R.VLR_RESCISAO_COD_13) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_13,

        SUM(D.DEMISSAO_COD_14) AS TOTAL_DEMISSAO_COD_14,
        SUM(R.VLR_RESCISAO_COD_14) AS TOTAL_VLR_RESCISAO_COD_14,
        ROUND(SUM(R.VLR_RESCISAO_COD_14) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_14,

        SUM(D.DEMISSAO_COD_21) AS TOTAL_DEMISSAO_COD_21,
        SUM(R.VLR_RESCISAO_COD_21) AS TOTAL_VLR_RESCISAO_COD_21,
        ROUND(SUM(R.VLR_RESCISAO_COD_21) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_21,

        SUM(D.DEMISSAO_COD_33) AS TOTAL_DEMISSAO_COD_33,
        SUM(R.VLR_RESCISAO_COD_33) AS TOTAL_VLR_RESCISAO_COD_33,
        ROUND(SUM(R.VLR_RESCISAO_COD_33) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_33,

        -- Total de demissões geral e cálculo do percentual total dos totais gerais
        SUM(D.TOTAL_DEMISSOES) AS TOTAL_TOT_DEMISSOES,
        ROUND(
              CASE
                  WHEN (SUM(R.VLR_RESCISAO_COD_10) + SUM(R.VLR_RESCISAO_COD_11) + SUM(R.VLR_RESCISAO_COD_12) +
                        SUM(R.VLR_RESCISAO_COD_13) + SUM(R.VLR_RESCISAO_COD_14) + SUM(R.VLR_RESCISAO_COD_21) +
                        SUM(R.VLR_RESCISAO_COD_33)) * 100.0 / SUM(R.VLR_TOT_RESCISAO) - TRUNC((SUM(R.VLR_RESCISAO_COD_10) + SUM(R.VLR_RESCISAO_COD_11) + SUM(R.VLR_RESCISAO_COD_12) +
                        SUM(R.VLR_RESCISAO_COD_13) + SUM(R.VLR_RESCISAO_COD_14) + SUM(R.VLR_RESCISAO_COD_21) +
                        SUM(R.VLR_RESCISAO_COD_33)) * 100.0 / SUM(R.VLR_TOT_RESCISAO)) >= 0.50
                      THEN TRUNC((SUM(R.VLR_RESCISAO_COD_10) + SUM(R.VLR_RESCISAO_COD_11) + SUM(R.VLR_RESCISAO_COD_12) +
                        SUM(R.VLR_RESCISAO_COD_13) + SUM(R.VLR_RESCISAO_COD_14) + SUM(R.VLR_RESCISAO_COD_21) +
                        SUM(R.VLR_RESCISAO_COD_33)) * 100.0 / SUM(R.VLR_TOT_RESCISAO)) + 1
                  ELSE TRUNC((SUM(R.VLR_RESCISAO_COD_10) + SUM(R.VLR_RESCISAO_COD_11) + SUM(R.VLR_RESCISAO_COD_12) +
                        SUM(R.VLR_RESCISAO_COD_13) + SUM(R.VLR_RESCISAO_COD_14) + SUM(R.VLR_RESCISAO_COD_21) +
                        SUM(R.VLR_RESCISAO_COD_33)) * 100.0 / SUM(R.VLR_TOT_RESCISAO))
              END, 2
          ) AS TOTAL_PERCENTUAL_GERAL

    FROM
        Rescisao_Valores R
    LEFT JOIN
        Demissoes_Causas D ON R.MES_ANO = D.MES_ANO
)

SELECT
    R.MES_ANO,
    TO_CHAR(R.VLR_TOT_RESCISAO, 'FM999G999G990D00') AS VLR_TOT_RESC,

    D.DEMISSAO_COD_10,
    TO_CHAR(R.VLR_RESCISAO_COD_10, 'FM999G999G990D00') AS VLR_RESC_COD_10,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_10 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_10,

    D.DEMISSAO_COD_11,
    TO_CHAR(R.VLR_RESCISAO_COD_11, 'FM999G999G990D00') AS VLR_RESC_COD_11,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_11 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_11,

    D.DEMISSAO_COD_12,
    TO_CHAR(R.VLR_RESCISAO_COD_12, 'FM999G999G990D00') AS VLR_RESC_COD_12,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_12 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_12,

    D.DEMISSAO_COD_13,
    TO_CHAR(R.VLR_RESCISAO_COD_13, 'FM999G999G990D00') AS VLR_RESC_COD_13,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_13 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_13,

    D.DEMISSAO_COD_14,
    TO_CHAR(R.VLR_RESCISAO_COD_14, 'FM999G999G990D00') AS VLR_RESC_COD_14,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_14 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_14,

    D.DEMISSAO_COD_21,
    TO_CHAR(R.VLR_RESCISAO_COD_21, 'FM999G999G990D00') AS VLR_RESC_COD_21,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_21 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_21,

    D.DEMISSAO_COD_33,
    TO_CHAR(R.VLR_RESCISAO_COD_33, 'FM999G999G990D00') AS VLR_RESC_COD_33,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_33 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_33,

    D.TOTAL_DEMISSOES,

    -- Coluna de Percentual Total para cada mês
    TO_CHAR(
            CASE
                WHEN ROUND((R.VLR_RESCISAO_COD_10 + R.VLR_RESCISAO_COD_11 + R.VLR_RESCISAO_COD_12 +
                            R.VLR_RESCISAO_COD_13 + R.VLR_RESCISAO_COD_14 + R.VLR_RESCISAO_COD_21 +
                            R.VLR_RESCISAO_COD_33) * 100.0 / R.VLR_TOT_RESCISAO, 2) >= 99.50
                THEN 100.00
                ELSE FLOOR((R.VLR_RESCISAO_COD_10 + R.VLR_RESCISAO_COD_11 + R.VLR_RESCISAO_COD_12 +
                            R.VLR_RESCISAO_COD_13 + R.VLR_RESCISAO_COD_14 + R.VLR_RESCISAO_COD_21 +
                            R.VLR_RESCISAO_COD_33) * 100.0 / R.VLR_TOT_RESCISAO)
            END, 'FM990.00'
        ) || '%' AS PERCENTUAL_TOTAL,

    -- Totais em colunas
    TO_CHAR(T.TOTAL_VLR_TOT_RESCISAO, 'FM999G999G990D00') AS TOTAL_VLR_TOT_RESC,
    T.TOTAL_DEMISSAO_COD_10 AS TOTAL_DEMISSAO_COD_10,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_10, 'FM999G999G990D00') AS TOTAL_VLR_RESC_COD_10,
    TO_CHAR(T.TOTAL_PERC_COD_10, 'FM990.00') || '%' AS TOT_PERC_COD_10,

    T.TOTAL_DEMISSAO_COD_11 AS TOTAL_DEMISSAO_COD_11,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_11, 'FM999G999G990D00') AS TOTAL_VLR_RESC_COD_11,
    TO_CHAR(T.TOTAL_PERC_COD_11, 'FM990.00') || '%' AS TOT_PERC_COD_11,

    T.TOTAL_DEMISSAO_COD_12 AS TOTAL_DEMISSAO_COD_12,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_12, 'FM999G999G990D00') AS TOTAL_VLR_RESC_COD_12,
    TO_CHAR(T.TOTAL_PERC_COD_12, 'FM990.00') || '%' AS TOT_PERC_COD_12,

    T.TOTAL_DEMISSAO_COD_13 AS TOTAL_DEMISSAO_COD_13,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_13, 'FM999G999G990D00') AS TOTAL_VLR_RESC_COD_13,
    TO_CHAR(T.TOTAL_PERC_COD_13, 'FM990.00') || '%' AS TOT_PERC_COD_13,

    T.TOTAL_DEMISSAO_COD_14 AS TOTAL_DEMISSAO_COD_14,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_14, 'FM999G999G990D00') AS TOTAL_VLR_RESC_COD_14,
    TO_CHAR(T.TOTAL_PERC_COD_14, 'FM990.00') || '%' AS TOT_PERC_COD_14,

    T.TOTAL_DEMISSAO_COD_21 AS TOTAL_DEMISSAO_COD_21,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_21, 'FM999G999G990D00') AS TOTAL_VLR_RESC_COD_21,
    TO_CHAR(T.TOTAL_PERC_COD_21, 'FM990.00') || '%' AS TOT_PERC_COD_21,

    T.TOTAL_DEMISSAO_COD_33 AS TOTAL_DEMISSAO_COD_33,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_33, 'FM999G999G990D00') AS TOTAL_VLR_RESC_COD_33,
    TO_CHAR(T.TOTAL_PERC_COD_33, 'FM990.00') || '%' AS TOT_PERC_COD_33,

    T.TOTAL_TOT_DEMISSOES AS TOTAL_TOT_DEMISSOES,

    -- Novo campo: percentual total para os totais gerais
    TO_CHAR(T.TOTAL_PERCENTUAL_GERAL, 'FM990.00') || '%' AS TOTAL_PERC_GERAL,

    'Período Informado de: ' || :MES_ANO_INICIO || ' à ' || :MES_ANO_FIM AS PERIODO_INFORMADO


FROM
    Rescisao_Valores R
LEFT JOIN
    Demissoes_Causas D ON R.MES_ANO = D.MES_ANO
CROSS JOIN
    Totais T
ORDER BY
    R.MES_ANO

