WITH
CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.HR_BASE_SEM,
                HR.HR_BASE_DIA,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.SEXO,
                CT.IDADE,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
  FROM V_DADOS_CONTRATO_AVT    CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_HIST_HORAS_COLAB_AVT HR,
       VH_CARGO_CONTRATO_AVT   FN
 WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
   AND CT.COD_CONTRATO = HR.COD_CONTRATO
   AND CT.COD_CONTRATO = FN.COD_CONTRATO
   /*AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= TO_DATE('01/07/2025', 'DD/MM/YYYY')) --VESÃO ALTERNATIVA, PARA RETORNAR ATÉ QUEM JÁ FOI DEMITIDO ATÉ A DATA_DEMISSAO*/
   AND ((SYSDATE BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= SYSDATE AND CT.DATA_DEMISSAO IS NULL))
   --AND CT.DATA_ADMISSAO BETWEEN TO_DATE('01/07/2025', 'DD/MM/YYYY') AND TO_DATE('28/07/2025', 'DD/MM/YYYY')
   AND SYSDATE BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND SYSDATE BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND SYSDATE BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
   AND ORG.COD_EMP = 8
   --AND ORG.COD_TIPO = 1
   AND ORG.EDICAO_ORG_4 IS NOT NULL
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608)
   --AND ORG.COD_UNIDADE = 004
 ORDER BY CT.COD_CONTRATO
),

STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_ORGANOGRAMA,
       ORG.COD_UNIDADE,
       AF.COD_CAUSA_AFAST AS COD_AFAST,
       AFN.NOME_CAUSA_AFAST AS DES_AFAST,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST,
       CASE
         WHEN CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < SYSDATE THEN
          'INATIVO'
         WHEN AF.COD_CAUSA_AFAST <> 0 AND AF.COD_CAUSA_AFAST <> 4 AND
              AF.COD_CAUSA_AFAST <> 21 AND AF.COD_CAUSA_AFAST <> 60 AND
              AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'AFASTADO'
         WHEN AF.COD_CAUSA_AFAST IN (21, 60) THEN
          'ATIVO, SEM RETORNO'
         WHEN AF.COD_CAUSA_AFAST = 7 THEN
          'EM FÉRIAS'
         WHEN AF.COD_CAUSA_AFAST IN (3, 6) THEN
          'AFASTADO TEMP'
         WHEN AF.COD_CAUSA_AFAST = 4 AND
              AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'PODERÁ RETORNAR'
         ELSE
          'EM ATIVIDADE'
       END AS DES_STATUS_AFAST,
       AF.DATA_INICIO AS DATA_INI_AFAST,
       AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN,
       RHFP0100 AFN
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND AF.COD_CAUSA_AFAST = AFN.COD_CAUSA_AFAST(+)
   AND ((SYSDATE BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= SYSDATE AND CT.DATA_FIM IS NULL))
   AND SYSDATE BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND SYSDATE BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND SYSDATE BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   AND ORG.COD_EMP = 8
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608)
   --AND ORG.COD_TIPO = 1
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608) --657 essa ainda irá inaugurar em agosto
),

SALARIO_ATUAL AS (
    SELECT T2.COD_CONTRATO,
           T2.DATA_INICIO AS DT_INI_SAL_ATUAL,
           T2.DATA_FIM AS DT_FIM_SAL_ATUAL,
           T2.VALOR_SALARIO AS SAL_ATUAL,
           ROW_NUMBER() OVER (PARTITION BY T2.COD_CONTRATO ORDER BY T2.DATA_INICIO DESC) AS RN
    FROM RHFP0608 T2
    WHERE TRUNC(SYSDATE) BETWEEN T2.DATA_INICIO AND T2.DATA_FIM
    --AND T2.COD_CONTRATO = 297305
),

DISSIDIO_ATUAL AS (
    SELECT *
    FROM (
        SELECT M.COD_CONTRATO,
               M.DATA_MOV AS DT_DISS_MOV_ATUAL,
               M.VALOR_VD AS VLR_DISSIDIO,
               ROW_NUMBER() OVER (PARTITION BY M.COD_CONTRATO ORDER BY M.DATA_MOV DESC) AS RN
        FROM RHFP1004 M, RHFP0608 T
        WHERE M.COD_CONTRATO = T.COD_CONTRATO
        AND M.COD_VD = 905
        AND TRUNC(SYSDATE) BETWEEN T.DATA_INICIO AND T.DATA_FIM
        --AND M.COD_CONTRATO = 297305
    ) SUB
    WHERE RN = 1
),


GRATIFICACAO_ATUAL AS (
    SELECT *
    FROM (
        SELECT M.COD_CONTRATO,
               M.DATA_MOV AS DT_MOV_ATUAL,
               M.VALOR_VD AS VLR_GRATIFICACAO,
               ROW_NUMBER() OVER (PARTITION BY M.COD_CONTRATO ORDER BY M.DATA_MOV DESC) AS RN
        FROM RHFP1004 M, RHFP0608 T
        WHERE M.COD_CONTRATO = T.COD_CONTRATO
        AND M.COD_VD = 935
        AND TRUNC(SYSDATE) BETWEEN T.DATA_INICIO AND T.DATA_FIM
        --AND M.COD_CONTRATO = 297305
    ) SUB
    WHERE RN = 1
)


/*SALARIO_ATUAL AS (
SELECT COD_CONTRATO,
       VALOR_VD
FROM RHFP1005 A
JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
WHERE B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
AND A.COD_VD = 910

)*/

SELECT 1 AS ORDENACAO,
   NULL AS COD_CONTRATO,
   'RELAÇÃO SALÁRIOS GERENTES DAS LOJAS' || ' | ' || 'Referência: ' || SYSDATE AS DES_PESSOA,
   NULL AS IDADE,
   NULL AS DATA_ADMISSAO,
   NULL AS DATA_DEMISSAO,
   NULL AS DES_FUNCAO,
   NULL AS SALARIO,
   NULL AS DISSIDIO,
   NULL AS GRATIFICACAO,
   NULL AS TOTAL,
   NULL AS HR_BASE_MES,
   NULL AS HR_BASE_SEM,
   NULL AS HR_BASE_DIA,
   NULL AS DES_UNIDADE,
   NULL AS COD_REDE,
   NULL AS STATUS_AFAST,
   NULL AS DES_STATUS_AFAST
FROM DUAL

UNION ALL

SELECT 2 AS ORDENACAO,
       A.COD_CONTRATO,
       A.DES_PESSOA,
       A.IDADE,
       A.DATA_ADMISSAO,
       A.DATA_DEMISSAO,
       A.DES_FUNCAO,
       TO_CHAR(C.SAL_ATUAL, 'FM999G999G990D00') AS SALARIO,
       TO_CHAR(D.VLR_DISSIDIO, 'FM999G999G990D00') AS DISSIDIO,
       TO_CHAR(E.VLR_GRATIFICACAO, 'FM999G999G990D00') AS GRATIFICACAO,
       TO_CHAR(
               C.SAL_ATUAL + D.VLR_DISSIDIO + E.VLR_GRATIFICACAO,
       'FM999G999G990D00'
       ) AS TOTAL,
       A.HR_BASE_MES,
       A.HR_BASE_SEM,
       A.HR_BASE_DIA,
       A.DES_UNIDADE,
       A.COD_REDE,
       CASE
           WHEN B.COD_AFAST IS NOT NULL THEN
            B.COD_AFAST
           ELSE
            B.STATUS_AFAST
       END AS STATUS_AFAST,
       CASE
           WHEN B.COD_AFAST IS NOT NULL THEN
            B.DES_AFAST
           ELSE
            B.DES_STATUS_AFAST
       END AS DES_STATUS_AFAST
FROM CONTRATOS A
LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
LEFT JOIN SALARIO_ATUAL C ON A.COD_CONTRATO = C.COD_CONTRATO
LEFT JOIN DISSIDIO_ATUAL D ON A.COD_CONTRATO = D.COD_CONTRATO
LEFT JOIN GRATIFICACAO_ATUAL E ON A.COD_CONTRATO = E.COD_CONTRATO
WHERE A.DES_FUNCAO LIKE 'GERENTE%'
AND A.STATUS = 0
AND (B.STATUS_AFAST = 0 OR STATUS_AFAST = 4)
AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
AND (A.COD_TIPO = :TIPO OR :TIPO = 0)
AND (A.COD_REDE = :REDE OR :REDE = 0)
--ORDER BY A.IDADE DESC, A.DES_UNIDADE


UNION ALL

SELECT
   3 AS ORDENACAO,
   NULL AS COD_CONTRATO,
   'TOTAL GERAL DA RELAÇÃO' AS DES_PESSOA,
   NULL AS IDADE,
   NULL AS DATA_ADMISSAO,
   NULL AS DATA_DEMISSAO,
   NULL AS DES_FUNCAO,
   TO_CHAR(SUM(C.SAL_ATUAL), 'FM999G999G990D00') AS SALARIO,
   TO_CHAR(SUM(D.VLR_DISSIDIO), 'FM999G999G990D00') AS DISSIDIO,
   TO_CHAR(SUM(E.VLR_GRATIFICACAO), 'FM999G999G990D00') AS GRATIFICACAO,
   TO_CHAR(
           SUM(C.SAL_ATUAL)
         + SUM(D.VLR_DISSIDIO)
         + SUM(E.VLR_GRATIFICACAO),
   'FM999G999G990D00'
   ) AS TOTAL,
   NULL AS HR_BASE_MES,
   NULL AS HR_BASE_SEM,
   NULL AS HR_BASE_DIA,
   NULL AS DES_UNIDADE,
   NULL AS COD_REDE,
   NULL AS STATUS_AFAST,
   NULL AS DES_STATUS_AFAST
FROM CONTRATOS A
LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
LEFT JOIN SALARIO_ATUAL C ON A.COD_CONTRATO = C.COD_CONTRATO
LEFT JOIN DISSIDIO_ATUAL D ON A.COD_CONTRATO = D.COD_CONTRATO
LEFT JOIN GRATIFICACAO_ATUAL E ON A.COD_CONTRATO = E.COD_CONTRATO
WHERE A.DES_FUNCAO LIKE 'GERENTE%'
AND A.STATUS = 0
AND (B.STATUS_AFAST = 0 OR STATUS_AFAST = 4)
AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
AND (A.COD_TIPO = :TIPO OR :TIPO = 0)
AND (A.COD_REDE = :REDE OR :REDE = 0)

ORDER BY ORDENACAO, DES_UNIDADE, IDADE DESC NULLS LAST


