--======SELECT ORIGINAL=====--

SELECT DISTINCT A.COD_UNIDADE,
                A.DES_FANTASIA,
                C.COD_FIADOR,
                C.DES_FIADOR,
                A.REDE,
                D.COD_GRUPO,
                TO_CHAR(B.DTA_INICIO, 'DD /MM/YYYY') AS DTA_INICIO,
                TO_CHAR(B.DTA_TERMINO, 'DD /MM/YYYY') AS DTA_TERMINO,
                B.IND_INATIVO
  FROM V_UNIDADES_ATIVAS A
 INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
 INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
 INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
  LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO =
                                                     E.COD_CONTRATO
 WHERE D.COD_GRUPO = 999
   AND A.COD_UNIDADE BETWEEN 0 AND 9999
   AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
   AND B.IND_INATIVO = 0
--AND C.COD_FIADOR = 3
 ORDER BY A.REDE, A.COD_UNIDADE




--======CTE COM OS TOTALIZADORES=====--

WITH CTE AS (
  SELECT DISTINCT 
    A.COD_UNIDADE AS UNIDADE,
    A.DES_FANTASIA AS NOME_UNIDADE,
    C.COD_FIADOR AS FIADOR,
    C.DES_FIADOR AS NOME_FIADOR,
    A.REDE,
    D.COD_GRUPO AS GRUPO,
    TO_CHAR(B.DTA_INICIO, 'DD/MM/YYYY') AS DATA_INICIO,
    TO_CHAR(B.DTA_TERMINO, 'DD/MM/YYYY') AS DATA_TERMINO,
    B.IND_INATIVO AS STATUS
  FROM V_UNIDADES_ATIVAS A
  INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
  INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
  INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
  LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO = E.COD_CONTRATO
  WHERE D.COD_GRUPO = 999
    AND A.COD_UNIDADE BETWEEN 0 AND 9999
    AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
    AND B.IND_INATIVO = 0
    ORDER BY A.REDE, A.COD_UNIDADE
),
TOT_VR_GRAZZIOTIN AS (
  SELECT 'Total Tipo Fiador: VR Grazziotin S/A' AS NOME_UNIDADE, COUNT(*) AS TOTAL
  FROM CTE
  WHERE FIADOR = 1
),
TOT_NENHUM AS (
  SELECT 'Total Tipo Fiador: Nenhum' AS NOME_UNIDADE, COUNT(*) AS TOTAL
  FROM CTE
  WHERE FIADOR = 3
),
TOTAL_GERAL AS (
  SELECT 'Total Geral' AS NOME_UNIDADE, COUNT(*) AS TOTAL
  FROM CTE
)
SELECT UNIDADE, NOME_UNIDADE, TO_CHAR(FIADOR) AS FIADOR, NOME_FIADOR, REDE, TO_CHAR(GRUPO) AS GRUPO, DATA_INICIO, DATA_TERMINO, TO_CHAR(STATUS) AS STATUS FROM CTE
UNION ALL
SELECT NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL FROM DUAL
UNION ALL
SELECT NULL, NOME_UNIDADE, NULL, NULL, NULL, NULL, NULL, NULL, TO_CHAR(TOTAL) FROM TOT_VR_GRAZZIOTIN
UNION ALL
SELECT NULL, NOME_UNIDADE, NULL, NULL, NULL, NULL, NULL, NULL, TO_CHAR(TOTAL) FROM TOT_NENHUM
UNION ALL
SELECT NULL, NOME_UNIDADE, NULL, NULL, NULL, NULL, NULL, NULL, TO_CHAR(TOTAL) FROM TOTAL_GERAL;


