--INSERTS TABELA RHFP0399 ÁREAS QUADRO E LOTAÇÕES - GZT

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(566, 'GZT PORTO ALEGRE CS', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(580, 'GZT SANTA ROSA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7002, 'GZT CACHOEIRINHA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7005, 'GZT CARAZINHO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7007, 'GZT CRUZ ALTA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7008, 'GZT PALMEIRA DAS M', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7009, 'GZT IJUI', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7020, 'GZT FREDERICO WES', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7022, 'GZT CANOAS', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7024, 'GZT TRES PASSOS', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7032, 'GZT GUAPORE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7037, 'GZT SAO BORJA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7038, 'GZT BAGE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7041, 'GZT ESTEIO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7044, 'GZT PASSO FUNDO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7046, 'GZT RIO GRANDE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7047, 'GZT LAGES', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7051, 'GZT GIRUA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7059, 'GZT CACHOEIRA DO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7065, 'GZT PAROBE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7066, 'GZT CONCORDIA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7083, 'GZT SANTA MARIA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7092, 'GZT VACARIA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7093, 'GZT SAO LEOPOLDO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7099, 'GZT LAGES', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7108, 'GZT SANTIAGO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7133, 'GZT CURITIBANOS', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7138, 'GZT RIO GRANDE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7140, 'GZT UNIAO DA VITOR', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7145, 'GZT URUGUAIANA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7173, 'GZT POA PROTASIO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7183, 'GZT ALEGRETE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7193, 'GZT DOM PEDRITO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7233, 'GZT URUGUAIANA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7244, 'GZT SOLEDADE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7268, 'GZT SANTA CRUZ DO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7314, 'GZT TRES DE MAIO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7353, 'GZT PRUDENTOPOLIS', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7386, 'GZT IGREJINHA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7390, 'GZT VIAMAO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7405, 'GZT ITAQUI', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7406, 'GZT SAO FRANCISCO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7412, 'GZT SCHARLAU', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7415, 'GZT CACAPAVA DO SU', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7430, 'GZT LIVRAMENTO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7437, 'GZT SAO LUIZ GONZA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7438, 'GZT IBIRUBA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7442, 'GZT FAXINAL DO SOT', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7446, 'GZT JULIO DE CASTI', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7461, 'GZT VENANCIO AIRES', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7478, 'GZT TUPANCIRETA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7485, 'GZT CACADOR', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7491, 'GZT LAJEADO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7493, 'GZT PF PETROPOLIS', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7500, 'GZT CAXIAS DO SUL', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7536, 'GZT GETULIO VARGA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7540, 'GZT SOLEDADE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7541, 'GZT ROSARIO DO SUL', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7543, 'GZT GARIBALDI', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7548, 'GZT PANAMBI', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7563, 'GZT SAO SEBASTIAO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7569, 'GZT FRAIBURGO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7570, 'GZT MARAVILHA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7577, 'GZT PINHAO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7582, 'GZT SANTA MARIA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7586, 'GZT RESTINGA SECA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7587, 'GZT ARROIO DO TIGR', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7588, 'GZT PORTO UNIAO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7589, 'GZT NOVO HAMBURGO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7591, 'GZT ESTRELA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7592, 'GZT PASSO FUNDO', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7594, 'GZT SANTA MARIA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7597, 'GZT CAXIAS DO SUL', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7598, 'GZT GUARAPUAVA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7599, 'GZT PONTA GROSSA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7601, 'GZT SANTA MARIA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7602, 'GZT NAO ME TOQUE', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7608, 'GZT LAGES', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7609, 'GZT PONTA GROSSA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7612, 'GZT LAGOA VERMELHA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7614, 'GZT CONCORDIA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7620, 'GZT SAO GABRIEL', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7628, 'GZT JOACABA', 5);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(7629, 'GZT ITAJAI', 5);
