INSERT INTO RHMS0220 (COD_PESSOA, COD_SEQ_EXAME, ORIGEM_INFORMACAO,	COD_EXAME, DATA_EXAME, DATA_REFERENCIA, SITUACAO_EXAME, COD_LABORATORIO, IND_RESULTADO,	RESULTADO, IND_OCUPACIONAL, COD_CLASSE_EXAME, DATA_AGENDAMENTO,	IND_REFERENCIA,	IND_PPP,	COD_CONTRATO, COD_EQUIP_EXAME, TEMPO_REPOUSO, DATA_INI_REAL, DATA_FIM_REAL, HORA_INI_REAL, HORA_FIM_REAL, AGH_SOE_SEQ, AGH_SEQP, RESULTADO_TEXTO, AGH_CON_NUMERO, COD_OPERADOR,	COD_MEDICO,	COD_PROC_DIAGNOSTICO, DATA_ORIGEM, IND_REC_TOXICO, SERIE_TOXICO, NUMERO_TOXICO, IND_PROGRAMACAO)
              VALUES (120315, 1,	1,	1,	'06/01/2023',	'06/01/2023',	2,	42558,	1,	NULL,	NULL,	1,	'06/01/2023',	'S',	'S',	393317,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'F389266',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'S')



INSERT INTO RHMS0220 (COD_PESSOA, COD_SEQ_EXAME, ORIGEM_INFORMACAO,	COD_EXAME, DATA_EXAME, DATA_REFERENCIA, SITUACAO_EXAME, COD_LABORATORIO, IND_RESULTADO,	RESULTADO, IND_OCUPACIONAL, COD_CLASSE_EXAME, DATA_AGENDAMENTO,	IND_REFERENCIA,	IND_PPP,	COD_CONTRATO, COD_EQUIP_EXAME, TEMPO_REPOUSO, DATA_INI_REAL, DATA_FIM_REAL, HORA_INI_REAL, HORA_FIM_REAL, AGH_SOE_SEQ, AGH_SEQP, RESULTADO_TEXTO, AGH_CON_NUMERO, COD_OPERADOR,	COD_MEDICO,	COD_PROC_DIAGNOSTICO, DATA_ORIGEM, IND_REC_TOXICO, SERIE_TOXICO, NUMERO_TOXICO, IND_PROGRAMACAO)
              VALUES (122732, 1,	1,	1,	'06/01/2023',	'06/01/2023',	2,	42558,	1,	NULL,	NULL,	1,	'06/01/2023',	'S',	'S',	393318,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'F389266',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'S')



INSERT INTO RHMS0220 (COD_PESSOA, COD_SEQ_EXAME, ORIGEM_INFORMACAO,	COD_EXAME, DATA_EXAME, DATA_REFERENCIA, SITUACAO_EXAME, COD_LABORATORIO, IND_RESULTADO,	RESULTADO, IND_OCUPACIONAL, COD_CLASSE_EXAME, DATA_AGENDAMENTO,	IND_REFERENCIA,	IND_PPP,	COD_CONTRATO, COD_EQUIP_EXAME, TEMPO_REPOUSO, DATA_INI_REAL, DATA_FIM_REAL, HORA_INI_REAL, HORA_FIM_REAL, AGH_SOE_SEQ, AGH_SEQP, RESULTADO_TEXTO, AGH_CON_NUMERO, COD_OPERADOR,	COD_MEDICO,	COD_PROC_DIAGNOSTICO, DATA_ORIGEM, IND_REC_TOXICO, SERIE_TOXICO, NUMERO_TOXICO, IND_PROGRAMACAO)
              VALUES (122637, 1,	1,	1,	'06/01/2023',	'06/01/2023',	2,	42558,	1,	NULL,	NULL,	1,	'06/01/2023',	'S',	'S',	393316,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'F389266',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'S')


INSERT INTO RHMS0220 (COD_PESSOA, COD_SEQ_EXAME, ORIGEM_INFORMACAO,	COD_EXAME, DATA_EXAME, DATA_REFERENCIA, SITUACAO_EXAME, COD_LABORATORIO, IND_RESULTADO,	RESULTADO, IND_OCUPACIONAL, COD_CLASSE_EXAME, DATA_AGENDAMENTO,	IND_REFERENCIA,	IND_PPP,	COD_CONTRATO, COD_EQUIP_EXAME, TEMPO_REPOUSO, DATA_INI_REAL, DATA_FIM_REAL, HORA_INI_REAL, HORA_FIM_REAL, AGH_SOE_SEQ, AGH_SEQP, RESULTADO_TEXTO, AGH_CON_NUMERO, COD_OPERADOR,	COD_MEDICO,	COD_PROC_DIAGNOSTICO, DATA_ORIGEM, IND_REC_TOXICO, SERIE_TOXICO, NUMERO_TOXICO, IND_PROGRAMACAO)
              VALUES (122633, 1,	1,	1,	'06/01/2023',	'06/01/2023',	2,	42558,	1,	NULL,	NULL,	1,	'06/01/2023',	'S',	'S',	393315,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'F389266',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'S')

