--INSERTS TABELA RHFP0399 ÁREAS QUADRO E LOTAÇÕES - FRANCO GIORGI

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(158, 'FRG PASSO FUNDO', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(190, 'FRG SAO BORJA', 2, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(198, 'FRG BAGE', 4, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(202, 'FRG SANTO ANGELO', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(224, 'FRG PONTA GROSSA', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(228, 'FRG STA. LIVRAMENTO', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(252, 'FRG IJUI', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(254, 'FRG PELOTAS,' 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(266, 'FRG LAGES', 2, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(269, 'FRG ALEGRETE', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(277, 'FRG GUARAPUAVA', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(278, 'FRG URUGUAIANA', 4, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(283, 'FRG CRUZ ALTA', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(285, 'FRG STA. CRUZ DO SUL', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(287, 'FRG SANTA MARIA II', 4, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(290, 'FRG RIO GRANDE', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(291, 'FRG CACHOEIRA DO SUL', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(413, 'FRG SAO LEOPOLDO II',	3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(421, 'FRG SANTA MARIA III', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(526, 'FRG SANTA MARIA IV', 3, 3);

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(607, 'FRG PONTA GROSSA', 3, 3);
