SELECT * FROM COMPRA; 
SELECT * FROM JOGO;
SELECT * FROM CLIENTE;
SELECT * FROM CIDADE;
SELECT * FROM FUNCIONARIO;
SELECT * FROM CATEGORIA;
SELECT * FROM ITENS;


--SELECTS TBL JOGO---------------------------------------------------------------------------

SELECT MAX(PRECOJOGO), MIN(PRECOJOGO), AVG(PRECOJOGO),
SUM(PRECOJOGO), COUNT(*)
FROM JOGO;

SELECT CATEGORIA.CODCATEGORIA, DESCRCATEGORIA, MAX(PRECOJOGO), MIN(PRECOJOGO),
AVG(PRECOJOGO),
SUM(PRECOJOGO), COUNT(*)
FROM JOGO JOIN CATEGORIA ON JOGO.CODCATEGORIA = CATEGORIA.CODCATEGORIA
GROUP BY CATEGORIA.CODCATEGORIA, DESCRCATEGORIA;

SELECT MIN(PRECOJOGO)
FROM JOGO;

SELECT MAX(PRECOJOGO)
FROM JOGO;



--SELECTS TBL CLIENTES-------------------------------------------------------------------------

SELECT COUNT(*)
FROM CLIENTE JOIN CIDADE ON CLIENTE.CODCIDADE =
CIDADE.CODCIDADE
WHERE NOMECIDADE = 'Passo Fundo';


--1: Faça uma consulta para listar o numero da compra, a data da compra e o nome do cliente que realizou a compra entre os meses de junho a agosto de 2022

SELECT A.NUMCOMPRA, A.DATACOMPRA, B.NOMECLIENTE
FROM COMPRA A JOIN CLIENTE B ON A.CODCLIENTE = B.CODCLIENTE
WHERE A.DATACOMPRA BETWEEN '01/06/2022' AND '31/08/2022'

--2: Faça uma consulta para listar o nome do jogo, nome do cliente das cidades de Passo fundo e São Paulo

SELECT A.NOMEJOGO, D.NOMECLIENTE, E.NOMECIDADE
FROM JOGO A JOIN ITENS B ON A.CODJOGO = B.CODJOGO
            JOIN COMPRA C ON B.NUMCOMPRA = C.NUMCOMPRA
            JOIN CLIENTE D ON C.CODCLIENTE = D.CODCLIENTE
            JOIN CIDADE E ON D.CODCIDADE = E.CODCIDADE
WHERE E.NOMECIDADE IN ('Passo Fundo', 'São Paulo');


--3: Faça uma consulta para listar quantos jogadores, o nickname, a data de nascimento, a cidade e o jogo de todos os jogadores que moram no Rio de Janeiro

SELECT A.NOMEJOGO, D.NOMECLIENTE, E.NOMECIDADE, SUM(B.QTDVENDA)
FROM JOGO A JOIN ITENS B ON A.CODJOGO = B.CODJOGO
            JOIN COMPRA C ON B.NUMCOMPRA = C.NUMCOMPRA
            JOIN CLIENTE D ON C.CODCLIENTE = D.CODCLIENTE
            JOIN CIDADE E ON D.CODCIDADE = E.CODCIDADE
WHERE E.NOMECIDADE IN ('Passo Fundo', 'São Paulo')
GROUP BY A.NOMEJOGO, D.NOMECLIENTE, E.NOMECIDADE;

--4: CRIAR UMA VISÃO QUE MOSTRE O VALOR DOS JOGOS ACIMA DE 80

CREATE VIEW GAMER AS
SELECT A.CODCLIENTE, A.NOMECLIENTE, B.NUMCOMPRA, C.CODJOGO, D.NOMEJOGO, D.PRECOJOGO
FROM CLIENTE A JOIN COMPRA B ON A.CODCLIENTE = B.CODCLIENTE
               JOIN ITENS C ON C.NUMCOMPRA = B.NUMCOMPRA
               JOIN JOGO D ON D.CODJOGO = C.CODJOGO
WHERE D.PRECOJOGO > 80.00

SELECT * FROM GAMER

DROP VIEW GAMER



