/*SQL -  REL TEMPO DE EMPRESA COLABORADORES*/

SELECT STATUS,
       COD_CONTRATO || ' - ' || DES_PESSOA AS COLABORADOR,
       DATA_ADMISSAO,
       DATA_AVANCO,
       DES_FUNCAO,
       COD_UNIDADE,
       DES_UNIDADE,
       COD_REDE_LOCAL,
       DES_REDE_LOCAL,

       -- Tempo de empresa individual
       TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO) / 12) AS ANOS_EMPRESA,
       TRUNC(MOD(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO), 12)) AS MESES_EMPRESA,

       -- Média real por unidade (exata)
       ROUND(
           SUM(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO)) OVER (PARTITION BY DES_UNIDADE) /
           COUNT(*) OVER (PARTITION BY DES_UNIDADE) / 12,
           1
       ) AS MEDIA_ANOS_UNIDADE,
       COUNT(*) OVER (PARTITION BY DES_UNIDADE) AS TOTAL_COLAB_UNIDADE,

       -- Média real por rede (exata)
       ROUND(
           SUM(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO)) OVER (PARTITION BY COD_REDE_LOCAL) /
           COUNT(*) OVER (PARTITION BY COD_REDE_LOCAL) / 12,
           1
       ) AS MEDIA_ANOS_REDE,
       COUNT(*) OVER (PARTITION BY COD_REDE_LOCAL) AS TOTAL_COLAB_REDE,

       -- Média real para empresa (exata)
       ROUND(
           SUM(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO)) OVER () /
           COUNT(*) OVER () / 12,
           1
       ) AS MEDIA_ANOS_EMPRESA,
       COUNT(*) OVER () AS TOTAL_COLAB_EMPRESA,

       DES_AFAST,
       CASE 
          WHEN DATA_INI_AFAST IS NOT NULL AND DATA_FIM_AFAST IS NOT NULL THEN 
           TO_CHAR(DATA_INI_AFAST, 'DD/MM/YYYY') || ' à ' || TO_CHAR(DATA_FIM_AFAST, 'DD/MM/YYYY')
          WHEN DATA_INI_AFAST IS NOT NULL THEN 
           TO_CHAR(DATA_INI_AFAST, 'DD/MM/YYYY')
          WHEN DATA_FIM_AFAST IS NOT NULL THEN 
           TO_CHAR(DATA_FIM_AFAST, 'DD/MM/YYYY')
          ELSE NULL
       END AS DT_AFAST,
       STATUS_AFAST

FROM V_DADOS_COLAB_AVT
WHERE STATUS = 0
  AND COD_EMP = 8
  AND (COD_TIPO = :TIPO OR :TIPO = 0)
  AND (COD_UNIDADE = :FILIAL OR :FILIAL = 0)
  AND (COD_REDE_LOCAL = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
ORDER BY COD_TIPO ASC, COD_UNIDADE ASC, ANOS_EMPRESA DESC, DATA_AVANCO ASC




/*ORIGINAL*/
/*SELECT STATUS,
       COD_CONTRATO || ' - ' || DES_PESSOA AS COLABORADOR,
       DATA_ADMISSAO,
       DATA_AVANCO,
       DES_FUNCAO,
       COD_UNIDADE,
       DES_UNIDADE,
       DES_REDE_LOCAL,
       TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO) / 12) AS ANOS_EMPRESA,
       TRUNC(MOD(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO), 12)) AS MESES_EMPRESA,
       DES_AFAST,
       DATA_INI_AFAST,
       DATA_FIM_AFAST,
       STATUS_AFAST
FROM V_DADOS_COLAB_AVT
WHERE STATUS = 0
  AND COD_EMP = 8
  AND (COD_TIPO = :TIPO OR :TIPO = 0)
  AND (COD_UNIDADE = :FILIAL OR :FILIAL = 0)
  AND (COD_REDE_LOCAL = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
ORDER BY COD_UNIDADE ASC, ANOS_EMPRESA  DESC, DATA_AVANCO ASC*/
