--==========================================================================================================--
--==========================================================================================================--
--==========================================================================================================--

/*SQLs ESPELHOS DO RESUMO DA FOLHA DE PAGAMENTO, POR FILIAL E GERAL DA EMPRESA*/

--==========================================================================================================--
--==========================================================================================================--
--==========================================================================================================--

/*======OFICIAL POR FILIAL======*/

--==V = SEM PARAMETROS --EXECUÇÃO GERAL

WITH
  Base_V AS (
    SELECT       
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      '01/06/2024 - 30/06/2024' AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER(PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY A.COD_VD) AS RN
    FROM 
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND TO_DATE('30/06/2024', 'DD/MM/YYYY') BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE 
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN TO_DATE('01/06/2024', 'DD/MM/YYYY') AND TO_DATE('30/06/2024', 'DD/MM/YYYY')
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND B.TIPO_VD = 'V'
      AND A.COD_VD NOT IN (292, 4033)
      AND A.VALOR_VD <> 0
    GROUP BY 
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Base_D AS (
    SELECT 
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE 
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      '01/06/2024 - 30/06/2024' AS REFERENCIA,
      CASE
        WHEN A.COD_VD = 1003 THEN 1004
        ELSE A.COD_VD
      END AS COD_VD,
      CASE
        WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões'
        ELSE B.NOME_VD
      END AS NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER (PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND TO_DATE('30/06/2024', 'DD/MM/YYYY') BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN TO_DATE('01/06/2024', 'DD/MM/YYYY') AND TO_DATE('30/06/2024', 'DD/MM/YYYY')
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND (
        B.TIPO_VD = 'D' 
        OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19))  -- Ajuste aqui para considerar apenas os eventos 17 e 19 para VD 1003
      )
      AND A.VALOR_VD <> 0
    GROUP BY
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END,
      CASE WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões' ELSE B.NOME_VD END
  ),
  Base_O AS (
    SELECT 
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      '01/06/2024 - 30/06/2024' AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER(PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY A.COD_VD) AS RN
    FROM 
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND TO_DATE('30/06/2024', 'DD/MM/YYYY') BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE 
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN TO_DATE('01/06/2024', 'DD/MM/YYYY') AND TO_DATE('30/06/2024', 'DD/MM/YYYY')
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND A.COD_VD IN (12, 885, 908, 910, 912, 914, 915, 916, 924, 925, 926, 927, 1004, 1063, 1064, 1067, 1068, 1231, 1232, 1233, 1234, 1456, 1457, 1458, 1459, 1461, 1462, 1463, 1464, 1910, 1924, 1934, 1935, 1941, 2222, 2232, 2601, 2602, 2605, 2611, 2612, 2615, 2616, 2617, 2701, 2705, 2706, 2711, 2712, 2713, 2714, 2715, 2716, 2717)
      AND A.VALOR_VD <> 0
    GROUP BY 
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Totais AS (
    SELECT  
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      '01/06/2024 - 30/06/2024' AS REFERENCIA,
      SUM(CASE WHEN B.TIPO_VD = 'V' THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_V,
      SUM(CASE WHEN B.TIPO_VD = 'D' OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19)) THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_D,
      SUM(CASE WHEN B.TIPO_VD = 'V' THEN NVL(A.VALOR_VD, 0) ELSE 0 END) - SUM(CASE WHEN B.TIPO_VD = 'D' OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19)) THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_LIQUIDO
    FROM 
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND TO_DATE('30/06/2024', 'DD/MM/YYYY') BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE 
      A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN '01/06/2024' AND '30/06/2024'
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      --AND F.COD_NIVEL_ORG = 5 --OR E.EDICAO_ORG IN ('815', '835', '845', '855'))
      AND E.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,322,326,327,328,329,330,331,335,349,399,939,1740,2147,2148,2149,2150,2151)
      AND E.COD_ORGANOGRAMA_SUB NOT IN (344)
      AND A.VALOR_VD <> 0
      AND A.COD_VD NOT IN (292, 4033)
    GROUP BY 
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END
  ),
  Combined_Base AS (
    SELECT 
      COALESCE(V.EDICAO_ORG_REP, D.EDICAO_ORG_REP, O.EDICAO_ORG_REP) AS EDICAO_ORG_REP,
      COALESCE(V.EDICAO_ORG, D.EDICAO_ORG, O.EDICAO_ORG) AS EDICAO_ORG,
      COALESCE(V.NOME_ORGANOGRAMA, D.NOME_ORGANOGRAMA, O.NOME_ORGANOGRAMA) AS NOME_ORGANOGRAMA,
      COALESCE(V.REFERENCIA, D.REFERENCIA, O.REFERENCIA) AS REFERENCIA,
      V.COD_VD AS COD_VD_V,
      V.NOME_VD AS NOME_VD_V,
      TO_CHAR(V.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_V,
      D.COD_VD AS COD_VD_D,
      D.NOME_VD AS NOME_VD_D,
      TO_CHAR(D.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_D,
      O.COD_VD AS COD_VD_O,
      O.NOME_VD AS NOME_VD_O,
      TO_CHAR(O.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_O,
      COALESCE(V.RN, D.RN, O.RN) AS RN,
      DENSE_RANK() OVER(PARTITION BY COALESCE(V.EDICAO_ORG, D.EDICAO_ORG, O.EDICAO_ORG) ORDER BY COALESCE(CASE WHEN V.COD_VD = 1003 THEN 1004 ELSE V.COD_VD END, CASE WHEN D.COD_VD = 1003 THEN 1004 ELSE D.COD_VD END, O.COD_VD)) AS DR
    FROM 
      Base_V V
      FULL OUTER JOIN Base_D D ON V.EDICAO_ORG = D.EDICAO_ORG AND V.RN = D.RN
      FULL OUTER JOIN Base_O O ON COALESCE(V.EDICAO_ORG, D.EDICAO_ORG) = O.EDICAO_ORG AND COALESCE(V.RN, D.RN) = O.RN
  ),
  Headers AS (
    SELECT 
      EDICAO_ORG_REP,
      EDICAO_ORG,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      'VENCIMENTOS' AS HEADER_V,
      'DESCONTOS' AS HEADER_D,
      'OUTROS' AS HEADER_O,
      0 AS RN
    FROM 
      (SELECT DISTINCT EDICAO_ORG_REP, EDICAO_ORG, NOME_ORGANOGRAMA, REFERENCIA FROM Combined_Base)
  ),
  Totals AS (
    SELECT 
      EDICAO_ORG_REP,
      EDICAO_ORG, 
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      'TOTAL VENCIMENTOS' AS NOME_VD_V,
      TO_CHAR(T.TOTAL_V, 'FM999G999G990D00') AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      'TOTAL DESCONTOS' AS NOME_VD_D,
      TO_CHAR(T.TOTAL_D, 'FM999G999G990D00') AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      'TOTAL LÍQUIDO' AS NOME_VD_O,
      TO_CHAR(T.TOTAL_LIQUIDO, 'FM999G999G990D00') AS TOTAL_MES_O,
      NULL AS RN,
      2 AS ORDER_COL
    FROM 
      Totais T
    WHERE T.TOTAL_V <> 0 OR T.TOTAL_D <> 0 OR T.TOTAL_LIQUIDO <> 0
  ),
  Grand_Totals AS (
    SELECT 
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      'TOTAL GERAL VENCIMENTOS' AS NOME_VD_V,
      TO_CHAR(SUM(T.TOTAL_V), 'FM999G999G990D00') AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      'TOTAL GERAL DESCONTOS' AS NOME_VD_D,
      TO_CHAR(SUM(T.TOTAL_D), 'FM999G999G990D00') AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      'TOTAL GERAL LÍQUIDO' AS NOME_VD_O,
      TO_CHAR(SUM(T.TOTAL_LIQUIDO), 'FM999G999G990D00') AS TOTAL_MES_O,
      NULL AS RN,
      3 AS ORDER_COL
    FROM 
      Totais T
  ),
  Blank_Lines AS (
    SELECT 
      DISTINCT 
      EDICAO_ORG_REP,
      EDICAO_ORG,      
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      4 AS ORDER_COL
    FROM 
      Headers
  ),
  Final_Result AS (
    SELECT
      H.EDICAO_ORG_REP, 
      H.EDICAO_ORG,
      H.NOME_ORGANOGRAMA,
      H.REFERENCIA,
      NULL AS COD_VD_V,
      H.HEADER_V AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      H.HEADER_D AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      H.HEADER_O AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      H.RN,
      0 AS ORDER_COL
    FROM 
      Headers H
    UNION ALL
    SELECT
      EDICAO_ORG_REP, 
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      RN,
      1 AS ORDER_COL
    FROM 
      Combined_Base
    UNION ALL
    SELECT 
      EDICAO_ORG_REP, 
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      NULL AS COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      NULL AS COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      NULL AS RN,
      ORDER_COL
    FROM 
      Totals
    UNION ALL
    SELECT
      NULL AS EDICAO_ORG_REP, 
      'TOTAL GERAL' AS EDICAO_ORG,
      'TOTAL GERAL' AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      'TOTAL GERAL VENCIMENTOS' AS NOME_VD_V,
      TO_CHAR(SUM(TOTAL_V), 'FM999G999G990D00') AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      'TOTAL GERAL DESCONTOS' AS NOME_VD_D,
      TO_CHAR(SUM(TOTAL_D), 'FM999G999G990D00') AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      'TOTAL GERAL LÍQUIDO' AS NOME_VD_O,
      TO_CHAR(SUM(TOTAL_LIQUIDO), 'FM999G999G990D00') AS TOTAL_MES_O,
      NULL AS RN,
      3 AS ORDER_COL
    FROM 
      Totais
    UNION ALL
    SELECT
      EDICAO_ORG_REP, 
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      4 AS ORDER_COL
    FROM 
      Blank_Lines
  )
SELECT 
  EDICAO_ORG,
  NOME_ORGANOGRAMA,
  REFERENCIA,
  COD_VD_V,
  NOME_VD_V,
  TOTAL_MES_V,
  COD_VD_D,
  NOME_VD_D,
  TOTAL_MES_D,
  COD_VD_O,
  NOME_VD_O,
  TOTAL_MES_O
FROM 
  Final_Result
ORDER BY 
  EDICAO_ORG_REP ASC, -- Usando a coluna de repetição para ordenação
  ORDER_COL ASC,
  RN ASC;

  







--====VERSÃO COM PARAMÊTROS INFORMADOS NA GERAÇÃO====--
/*PARA O EXCEL*/

WITH
  Base_V AS (
    SELECT
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER(PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY A.COD_VD) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND B.TIPO_VD = 'V'
      AND A.COD_VD NOT IN (292, 4033)
      AND A.VALOR_VD <> 0
    GROUP BY
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Base_D AS (
    SELECT
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      CASE
        WHEN A.COD_VD = 1003 THEN 1004
        ELSE A.COD_VD
      END AS COD_VD,
      CASE
        WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões'
        ELSE B.NOME_VD
      END AS NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER (PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND (
        B.TIPO_VD = 'D'
        OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19))  -- Ajuste aqui para considerar apenas os eventos 17 e 19 para VD 1003
      )
      AND A.VALOR_VD <> 0
    GROUP BY
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END,
      CASE WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões' ELSE B.NOME_VD END
  ),
  Base_O AS (
    SELECT
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER(PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY A.COD_VD) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND A.COD_VD IN (12, 885, 908, 910, 912, 914, 915, 916, 924, 925, 926, 927, 1004, 1063, 1064, 1067, 1068, 1231, 1232, 1233, 1234, 1456, 1457, 1458, 1459, 1461, 1462, 1463, 1464, 1910, 1924, 1934, 1935, 1941, 2222, 2232, 2601, 2602, 2605, 2611, 2612, 2615, 2616, 2617, 2701, 2705, 2706, 2711, 2712, 2713, 2714, 2715, 2716, 2717)
      AND A.VALOR_VD <> 0
    GROUP BY
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Totais AS (
SELECT
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      SUM(CASE WHEN B.TIPO_VD = 'V' THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_V,
      SUM(CASE WHEN B.TIPO_VD = 'D' OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19)) THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_D,
      SUM(CASE WHEN B.TIPO_VD = 'V' THEN NVL(A.VALOR_VD, 0) ELSE 0 END) - SUM(CASE WHEN B.TIPO_VD = 'D' OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19)) THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_LIQUIDO
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      --AND F.COD_NIVEL_ORG = 5 --OR E.EDICAO_ORG IN ('815', '835', '845', '855'))
      AND E.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,322,326,327,328,329,330,331,335,349,399,939,1740,2147,2148,2149,2150,2151)
      AND E.COD_ORGANOGRAMA_SUB NOT IN (344)
      AND A.VALOR_VD <> 0
      AND A.COD_VD NOT IN (292, 4033)
    GROUP BY
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END
  ),
  Combined_Base AS (
    SELECT
      COALESCE(V.EDICAO_ORG_REP, D.EDICAO_ORG_REP, O.EDICAO_ORG_REP) AS EDICAO_ORG_REP,
      COALESCE(V.EDICAO_ORG, D.EDICAO_ORG, O.EDICAO_ORG) AS EDICAO_ORG,
      COALESCE(V.NOME_ORGANOGRAMA, D.NOME_ORGANOGRAMA, O.NOME_ORGANOGRAMA) AS NOME_ORGANOGRAMA,
      COALESCE(V.REFERENCIA, D.REFERENCIA, O.REFERENCIA) AS REFERENCIA,
      V.COD_VD AS COD_VD_V,
      V.NOME_VD AS NOME_VD_V,
      TO_CHAR(V.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_V,
      D.COD_VD AS COD_VD_D,
      D.NOME_VD AS NOME_VD_D,
      TO_CHAR(D.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_D,
      O.COD_VD AS COD_VD_O,
      O.NOME_VD AS NOME_VD_O,
      TO_CHAR(O.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_O,
      COALESCE(V.RN, D.RN, O.RN) AS RN,
      DENSE_RANK() OVER(PARTITION BY COALESCE(V.EDICAO_ORG, D.EDICAO_ORG, O.EDICAO_ORG)
      ORDER BY COALESCE(CASE WHEN V.COD_VD = 1003 THEN 1004 ELSE V.COD_VD END, CASE WHEN D.COD_VD = 1003 THEN 1004 ELSE D.COD_VD END, O.COD_VD)) AS DR
    FROM
      Base_V V
      FULL OUTER JOIN Base_D D ON V.EDICAO_ORG = D.EDICAO_ORG AND V.RN = D.RN
      FULL OUTER JOIN Base_O O ON COALESCE(V.EDICAO_ORG, D.EDICAO_ORG) = O.EDICAO_ORG AND COALESCE(V.RN, D.RN) = O.RN
  ),
  Headers AS (
    SELECT
      EDICAO_ORG_REP,
      EDICAO_ORG,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      'VENCIMENTOS' AS HEADER_V,
      'DESCONTOS' AS HEADER_D,
      'OUTROS' AS HEADER_O,
      0 AS RN
    FROM
      (SELECT DISTINCT EDICAO_ORG_REP, EDICAO_ORG, NOME_ORGANOGRAMA, REFERENCIA FROM Combined_Base)
  ),
  Totals AS (
    SELECT
      EDICAO_ORG_REP,
      EDICAO_ORG,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      'TOTAL VENCIMENTOS' AS NOME_VD_V,
      TO_CHAR(T.TOTAL_V, 'FM999G999G990D00') AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      'TOTAL DESCONTOS' AS NOME_VD_D,
      TO_CHAR(T.TOTAL_D, 'FM999G999G990D00') AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      'TOTAL LÍQUIDO' AS NOME_VD_O,
      TO_CHAR(T.TOTAL_LIQUIDO, 'FM999G999G990D00') AS TOTAL_MES_O,
      NULL AS RN,
      2 AS ORDER_COL
    FROM
      Totais T
    WHERE T.TOTAL_V <> 0 OR T.TOTAL_D <> 0 OR T.TOTAL_LIQUIDO <> 0
  ),
  Grand_Totals AS (
    SELECT
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      'TOTAL GERAL VENCIMENTOS' AS NOME_VD_V,
      TO_CHAR(SUM(T.TOTAL_V), 'FM999G999G990D00') AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      'TOTAL GERAL DESCONTOS' AS NOME_VD_D,
      TO_CHAR(SUM(T.TOTAL_D), 'FM999G999G990D00') AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      'TOTAL GERAL LÍQUIDO' AS NOME_VD_O,
      TO_CHAR(SUM(T.TOTAL_LIQUIDO), 'FM999G999G990D00') AS TOTAL_MES_O,
      NULL AS RN,
      3 AS ORDER_COL
    FROM
      Totais T
  ),
  Blank_Lines AS (
    SELECT
      DISTINCT
      EDICAO_ORG_REP,
      EDICAO_ORG,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      4 AS ORDER_COL
    FROM
      Headers
  ),
  Final_Result AS (
    SELECT
      H.EDICAO_ORG_REP,
      H.EDICAO_ORG,
      H.NOME_ORGANOGRAMA,
      H.REFERENCIA,
      NULL AS COD_VD_V,
      H.HEADER_V AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      H.HEADER_D AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      H.HEADER_O AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      H.RN,
      0 AS ORDER_COL
    FROM
      Headers H
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      RN,
      1 AS ORDER_COL
    FROM
      Combined_Base
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      NULL AS COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      NULL AS COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      NULL AS RN,
      ORDER_COL
    FROM
      Totals
    UNION ALL
    SELECT
      NULL AS EDICAO_ORG_REP,
      'TOTAL GERAL' AS EDICAO_ORG,
      'TOTAL GERAL' AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      'TOTAL GERAL VENCIMENTOS' AS NOME_VD_V,
      TO_CHAR(SUM(TOTAL_V), 'FM999G999G990D00') AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      'TOTAL GERAL DESCONTOS' AS NOME_VD_D,
      TO_CHAR(SUM(TOTAL_D), 'FM999G999G990D00') AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      'TOTAL GERAL LÍQUIDO' AS NOME_VD_O,
      TO_CHAR(SUM(TOTAL_LIQUIDO), 'FM999G999G990D00') AS TOTAL_MES_O,
      NULL AS RN,
      3 AS ORDER_COL
    FROM
      Totais
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      4 AS ORDER_COL
    FROM
      Blank_Lines
  )
SELECT
  EDICAO_ORG,
  NOME_ORGANOGRAMA,
  REFERENCIA,
  COD_VD_V,
  NOME_VD_V,
  TOTAL_MES_V,
  COD_VD_D,
  NOME_VD_D,
  TOTAL_MES_D,
  COD_VD_O,
  NOME_VD_O,
  TOTAL_MES_O
FROM
  Final_Result
ORDER BY
  EDICAO_ORG_REP ASC, -- Usando a coluna de repetição para ordenação
  ORDER_COL ASC,
  RN ASC





--=================



--=====================================================--
/*========VERSÃO PARA O GERADOR DE RELATÓRIOS=========*/
--=====================================================--


WITH
  Base_V AS (
    SELECT
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER(PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY A.COD_VD) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND B.TIPO_VD = 'V'
      AND A.COD_VD NOT IN (292, 4033)
      AND A.VALOR_VD <> 0
    GROUP BY
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Base_D AS (
    SELECT
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      CASE
        WHEN A.COD_VD = 1003 THEN 1004
        ELSE A.COD_VD
      END AS COD_VD,
      CASE
        WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões'
        ELSE B.NOME_VD
      END AS NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER (PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND (
        B.TIPO_VD = 'D'
        OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19))  -- Ajuste aqui para considerar apenas os eventos 17 e 19 para VD 1003
      )
      AND A.VALOR_VD <> 0
    GROUP BY
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END,
      CASE WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões' ELSE B.NOME_VD END
  ),
  Base_O AS (
    SELECT
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER(PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY A.COD_VD) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND A.COD_VD IN (12, 885, 908, 910, 912, 914, 915, 916, 924, 925, 926, 927, 1004, 1063, 1064, 1067, 1068, 1231, 1232, 1233, 1234, 1456, 1457, 1458, 1459, 1461, 1462, 1463, 1464, 1910, 1924, 1934, 1935, 1941, 2222, 2232, 2601, 2602, 2605, 2611, 2612, 2615, 2616, 2617, 2701, 2705, 2706, 2711, 2712, 2713, 2714, 2715, 2716, 2717)
      AND A.VALOR_VD <> 0
    GROUP BY
      E.EDICAO_ORG,
      F.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Totais AS (
       SELECT
      E.EDICAO_ORG AS EDICAO_ORG_REP,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      SUM(CASE WHEN B.TIPO_VD = 'V' THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_V,
      SUM(CASE WHEN B.TIPO_VD = 'D' OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19)) THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_D,
      SUM(CASE WHEN B.TIPO_VD = 'V' THEN NVL(A.VALOR_VD, 0) ELSE 0 END) - SUM(CASE WHEN B.TIPO_VD = 'D' OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19)) THEN NVL(A.VALOR_VD, 0) ELSE 0 END) AS TOTAL_LIQUIDO
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
      LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = CASE WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5 ELSE E.COD_NIVEL4 END
    WHERE
      A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      --AND F.COD_NIVEL_ORG = 5 --OR E.EDICAO_ORG IN ('815', '835', '845', '855'))
      AND E.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,322,326,327,328,329,330,331,335,349,399,939,1740,2147,2148,2149,2150,2151)
      AND E.COD_ORGANOGRAMA_SUB NOT IN (344)
      AND A.VALOR_VD <> 0
      AND A.COD_VD NOT IN (292, 4033)
    GROUP BY
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END

  ),
  Combined_Base AS (
    SELECT
      COALESCE(V.EDICAO_ORG_REP, D.EDICAO_ORG_REP, O.EDICAO_ORG_REP) AS EDICAO_ORG_REP,
      COALESCE(V.EDICAO_ORG, D.EDICAO_ORG, O.EDICAO_ORG) AS EDICAO_ORG,
      COALESCE(V.NOME_ORGANOGRAMA, D.NOME_ORGANOGRAMA, O.NOME_ORGANOGRAMA) AS NOME_ORGANOGRAMA,
      COALESCE(V.REFERENCIA, D.REFERENCIA, O.REFERENCIA) AS REFERENCIA,
      V.COD_VD AS COD_VD_V,
      V.NOME_VD AS NOME_VD_V,
      TO_CHAR(V.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_V,
      D.COD_VD AS COD_VD_D,
      D.NOME_VD AS NOME_VD_D,
      TO_CHAR(D.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_D,
      O.COD_VD AS COD_VD_O,
      O.NOME_VD AS NOME_VD_O,
      TO_CHAR(O.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_O,
      COALESCE(V.RN, D.RN, O.RN) AS RN,
      DENSE_RANK() OVER (PARTITION BY COALESCE(V.EDICAO_ORG, D.EDICAO_ORG, O.EDICAO_ORG) ORDER BY COALESCE(V.RN, D.RN, O.RN)) AS DR
    FROM
      Base_V V
      FULL OUTER JOIN Base_D D ON V.EDICAO_ORG = D.EDICAO_ORG AND V.RN = D.RN
      FULL OUTER JOIN Base_O O ON COALESCE(V.EDICAO_ORG, D.EDICAO_ORG) = O.EDICAO_ORG AND COALESCE(V.RN, D.RN) = O.RN
  ),
  Headers AS (
    SELECT
      EDICAO_ORG_REP,
      EDICAO_ORG,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      'VENCIMENTOS' AS HEADER_V,
      'DESCONTOS' AS HEADER_D,
      'OUTROS' AS HEADER_O,
      0 AS RN
    FROM
      (SELECT DISTINCT EDICAO_ORG_REP, EDICAO_ORG, NOME_ORGANOGRAMA, REFERENCIA FROM Combined_Base)
  ),
  Totals AS (
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      2 AS ORDER_COL,
      TO_CHAR(T.TOTAL_V, 'FM999G999G990D00') AS TOTAL_V,
      TO_CHAR(T.TOTAL_D, 'FM999G999G990D00') AS TOTAL_D,
      TO_CHAR(T.TOTAL_LIQUIDO, 'FM999G999G990D00') AS TOTAL_LIQUIDO
    FROM
      Totais T
  ),
  Blank_Lines AS (
    SELECT
      DISTINCT
      EDICAO_ORG_REP,
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      3 AS ORDER_COL,
      NULL AS TOTAL_V,
      NULL AS TOTAL_D,
      NULL AS TOTAL_LIQUIDO
    FROM
      Headers
  ),
  Final_Result AS (
    SELECT
      H.EDICAO_ORG_REP,
      H.EDICAO_ORG,
      H.NOME_ORGANOGRAMA,
      H.REFERENCIA,
      NULL AS COD_VD_V,
      H.HEADER_V AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      H.HEADER_D AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      H.HEADER_O AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      H.RN,
      0 AS ORDER_COL,
      NULL AS TOTAL_V,
      NULL AS TOTAL_D,
      NULL AS TOTAL_LIQUIDO
    FROM
      Headers H
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      RN,
      1 AS ORDER_COL,
      NULL AS TOTAL_V,
      NULL AS TOTAL_D,
      NULL AS TOTAL_LIQUIDO
    FROM
      Combined_Base
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      2 AS ORDER_COL,
      TOTAL_V,
      TOTAL_D,
      TOTAL_LIQUIDO
    FROM
      Totals
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_ORG,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      ORDER_COL,
      NULL AS TOTAL_V,
      NULL AS TOTAL_D,
      NULL AS TOTAL_LIQUIDO
    FROM
      Blank_Lines
  )
SELECT
  -- Lista de colunas sem a coluna EDICAO_ORG_REP
  EDICAO_ORG,
  NOME_ORGANOGRAMA,
  REFERENCIA,
  COD_VD_V,
  NOME_VD_V,
  TOTAL_MES_V,
  COD_VD_D,
  NOME_VD_D,
  TOTAL_MES_D,
  COD_VD_O,
  NOME_VD_O,
  TOTAL_MES_O,
  TOTAL_V,
  TOTAL_D,
  TOTAL_LIQUIDO
FROM
  Final_Result
ORDER BY
  EDICAO_ORG_REP ASC, -- Usando a coluna de repetição para ordenação
  ORDER_COL ASC,
  RN ASC




  
--============================================================================================================--
--============================================================================================================--
--============================================================================================================--




/*==========OFICIAL GERAL DA EMPRESA==========*/


--==V = SEM PARAMETROS --EXECUÇÃO GERAL

WITH
Base_V AS (
       SELECT 
          E.EDICAO_NIVEL2 AS EDICAO_ORG_REP,
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
          '01/06/2024 - 30/06/2024' AS REFERENCIA,
          A.COD_VD,
          B.NOME_VD,
          SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
          ROW_NUMBER() OVER (PARTITION BY E.EDICAO_NIVEL2 ORDER BY A.COD_VD) AS RN
        FROM 
          RHFP1006 A
          INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
          INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND '30/06/2024' BETWEEN D.DATA_INICIO AND D.DATA_FIM
          INNER JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, '31/12/2999')
          INNER JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
           LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG 
        WHERE 
          COD_MESTRE_EVENTO IN (
            SELECT COD_MESTRE_EVENTO
            FROM RHFP1003
            WHERE TO_DATE(DATA_REFERENCIA) BETWEEN '01/06/2024' AND '30/06/2024'
              AND COD_ORGANOGRAMA = 8
              AND COD_EVENTO IN (1, 17, 19, 26)
          )
          AND E.EDICAO_NIVEL2 = '008'      
          AND NV.COD_NIVEL_ORG = 2
          AND NV.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,
                                         322,326,327,328,329,330,331,335,349,399,939,
                                         1740, 2147,2148,2149,2150,2151)
          AND NV.COD_ORGANOGRAMA_SUB NOT IN (344)
          AND B.TIPO_VD = 'V'
          AND A.COD_VD NOT IN (292,4033)
          AND A.VALOR_VD <> 0
        GROUP BY 
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
          A.COD_VD,
          B.NOME_VD
  ),
  Base_D AS (
      SELECT
          E.EDICAO_NIVEL2 AS EDICAO_ORG_REP,
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
            '01/06/2024 - 30/06/2024' AS REFERENCIA,
            CASE
              WHEN A.COD_VD = 1003 THEN 1004
              ELSE A.COD_VD
            END AS COD_VD,
            CASE
              WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões'
              ELSE B.NOME_VD
            END AS NOME_VD,
            SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
            ROW_NUMBER() OVER (PARTITION BY TO_NUMBER(E.EDICAO_NIVEL2) ORDER BY CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END) AS RN
          FROM
            RHFP1006 A
            INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
            LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
            INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND TO_DATE('30/06/2024', 'DD/MM/YYYY') BETWEEN D.DATA_INICIO AND D.DATA_FIM
            LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
            LEFT JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
            LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG 
          WHERE
            A.COD_MESTRE_EVENTO IN (
              SELECT COD_MESTRE_EVENTO
              FROM RHFP1003
              WHERE TO_DATE(DATA_REFERENCIA) BETWEEN TO_DATE('01/06/2024', 'DD/MM/YYYY') AND TO_DATE('30/06/2024', 'DD/MM/YYYY')
                AND COD_ORGANOGRAMA = 8
                AND COD_EVENTO IN (1, 17, 19, 26)
            )

            AND E.EDICAO_NIVEL2 = '008'
            AND NV.COD_NIVEL_ORG = 2
            AND (
              B.TIPO_VD = 'D' 
              OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19))  -- Ajuste aqui para considerar apenas os eventos 17 e 19 para VD 1003
            )
            AND A.VALOR_VD <> 0
          GROUP BY
            E.EDICAO_NIVEL2,
            NV.NOME_ORGANOGRAMA,
            A.COD_VD,
            B.NOME_VD,
            CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END,
            CASE WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões' ELSE B.NOME_VD END      
  ),
  Base_O AS (
       SELECT 
     
      E.EDICAO_NIVEL2 AS EDICAO_ORG_REP, -- Duplicando a coluna para uso interno
      E.EDICAO_NIVEL2,
      NV.NOME_ORGANOGRAMA,
      '01/06/2024 - 30/06/2024' AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER (PARTITION BY E.EDICAO_NIVEL2 ORDER BY A.COD_VD) AS RN
    FROM 
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND '30/06/2024' BETWEEN D.DATA_INICIO AND D.DATA_FIM
      INNER JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, '31/12/2999')
      INNER JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
       LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG 
    WHERE 
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN '01/06/2024' AND '30/06/2024'
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'      
      AND NV.COD_NIVEL_ORG = 2
      AND NV.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,
                                     322,326,327,328,329,330,331,335,349,399,939,
                                     1740, 2147,2148,2149,2150,2151)
      AND NV.COD_ORGANOGRAMA_SUB NOT IN (344)
      AND A.COD_VD IN (12, 885, 908, 910, 912, 914, 915, 916, 924, 925, 926, 
                       927,1063, 1064, 1067, 1068, 1231, 1232, 1233, 1234,
                       1456, 1457, 1458, 1459, 1461, 1462, 1463, 1464,
                       1910, 1924, 1934, 1935, 1941, 2222, 2232, 2601,
                       2602, 2605, 2611, 2612, 2615, 2616, 2617, 2701,
                       2705, 2706, 2711, 2712, 2713, 2714, 2715, 2716, 2717)
      AND A.COD_VD NOT IN (292,4033)
      AND A.VALOR_VD <> 0

    GROUP BY 
      E.EDICAO_NIVEL2,
      NV.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Totais AS (
    SELECT
      V.EDICAO_NIVEL2 AS EDICAO_ORG_REP, 
      V.EDICAO_NIVEL2,
      V.NOME_ORGANOGRAMA,
      V.REFERENCIA,
      V.TOTAL_V,
      D.TOTAL_D,
      V.TOTAL_V - D.TOTAL_D AS TOTAL_LIQUIDO
    FROM 
      (SELECT EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA, SUM(TOTAL_MES) AS TOTAL_V
       FROM Base_V
       GROUP BY EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA) V
    LEFT JOIN 
      (SELECT EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA, SUM(TOTAL_MES) AS TOTAL_D
       FROM Base_D
       GROUP BY EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA) D
    ON V.EDICAO_NIVEL2 = D.EDICAO_NIVEL2
  ),
  Combined_Base AS (
    SELECT 
      COALESCE(V.EDICAO_ORG_REP, D.EDICAO_ORG_REP, O.EDICAO_ORG_REP) AS EDICAO_ORG_REP,
      COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2, O.EDICAO_NIVEL2) AS EDICAO_EMP,      
      COALESCE(V.NOME_ORGANOGRAMA, D.NOME_ORGANOGRAMA, O.NOME_ORGANOGRAMA) AS NOME_ORGANOGRAMA,
      COALESCE(V.REFERENCIA, D.REFERENCIA, O.REFERENCIA) AS REFERENCIA,
      V.COD_VD AS COD_VD_V,
      V.NOME_VD AS NOME_VD_V,
      TO_CHAR(V.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_V,
      D.COD_VD AS COD_VD_D,
      D.NOME_VD AS NOME_VD_D,
      TO_CHAR(D.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_D,
      O.COD_VD AS COD_VD_O,
      O.NOME_VD AS NOME_VD_O,
      TO_CHAR(O.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_O,
      COALESCE(V.RN, D.RN, O.RN) AS RN,
      DENSE_RANK() OVER (PARTITION BY COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2, O.EDICAO_NIVEL2) ORDER BY COALESCE(V.RN, D.RN, O.RN)) AS DR
    FROM 
      Base_V V
      FULL OUTER JOIN Base_D D ON V.EDICAO_NIVEL2 = D.EDICAO_NIVEL2 AND V.RN = D.RN
      FULL OUTER JOIN Base_O O ON COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2) = O.EDICAO_NIVEL2 AND COALESCE(V.RN, D.RN) = O.RN
  ),
  Headers AS (
    SELECT 
      EDICAO_ORG_REP,
      EDICAO_EMP, 
      NOME_ORGANOGRAMA,
      REFERENCIA,
      'VENCIMENTOS' AS HEADER_V,
      'DESCONTOS' AS HEADER_D,
      'OUTROS' AS HEADER_O,
      0 AS RN
    FROM
      (SELECT DISTINCT EDICAO_ORG_REP, EDICAO_EMP, NOME_ORGANOGRAMA, REFERENCIA FROM Combined_Base)
  ),
  Totals AS (
    SELECT 
      EDICAO_ORG_REP,
      EDICAO_NIVEL2, 
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      'TOTAL VENCIMENTOS' AS NOME_VD_V,
      TO_CHAR(T.TOTAL_V, 'FM999G999G990D00') AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      'TOTAL DESCONTOS' AS NOME_VD_D,
      TO_CHAR(T.TOTAL_D, 'FM999G999G990D00') AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      'TOTAL LÍQUIDO' AS NOME_VD_O,
      TO_CHAR(T.TOTAL_LIQUIDO, 'FM999G999G990D00') AS TOTAL_MES_O,
      NULL AS RN,
      2 AS ORDER_COL
    FROM 
      Totais T
  ),
  Blank_Lines AS (
    SELECT 
      DISTINCT 
      EDICAO_ORG_REP,
      EDICAO_EMP,      
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      3 AS ORDER_COL
    FROM 
      Headers
  ),
  Final_Result AS (
    SELECT
      H.EDICAO_ORG_REP, 
      H.EDICAO_EMP,
      H.NOME_ORGANOGRAMA,
      H.REFERENCIA,
      NULL AS COD_VD_V,
      H.HEADER_V AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      H.HEADER_D AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      H.HEADER_O AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      H.RN,
      0 AS ORDER_COL
    FROM 
      Headers H
    UNION ALL
    SELECT
      EDICAO_ORG_REP, 
      NULL AS EDICAO_EMP,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      RN,
      1 AS ORDER_COL
    FROM 
      Combined_Base
    UNION ALL
    SELECT 
      EDICAO_ORG_REP, 
      NULL AS EDICAO_EMP,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      NULL AS COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      NULL AS COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      NULL AS RN,
      ORDER_COL
    FROM 
      Totals
    UNION ALL
    SELECT
      EDICAO_ORG_REP, 
      NULL AS EDICAO_EMP,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      ORDER_COL
    FROM 
      Blank_Lines
  )
SELECT 
  -- Lista de colunas sem a coluna EDICAO_ORG_REP
  EDICAO_EMP,
  NOME_ORGANOGRAMA,
  REFERENCIA,
  COD_VD_V,
  NOME_VD_V,
  TOTAL_MES_V,
  COD_VD_D,
  NOME_VD_D,
  TOTAL_MES_D,
  COD_VD_O,
  NOME_VD_O,
  TOTAL_MES_O
  --RN,
  --ORDER_COL
FROM 
  Final_Result
ORDER BY 
  EDICAO_ORG_REP ASC, -- Usando a coluna de repetição para ordenação
  ORDER_COL ASC,
  RN ASC;





--====VERSÃO COM PARAMÊTROS INFORMADOS NA GERAÇÃO====--
/*PARA O EXCEL*/

WITH
Base_V AS (
       SELECT
          E.EDICAO_NIVEL2 AS EDICAO_ORG_REP,
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
          :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
          A.COD_VD,
          B.NOME_VD,
          SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
          ROW_NUMBER() OVER (PARTITION BY E.EDICAO_NIVEL2 ORDER BY A.COD_VD) AS RN
        FROM
          RHFP1006 A
          INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
          INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
          INNER JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, '31/12/2999')
          INNER JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
           LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG
        WHERE
          COD_MESTRE_EVENTO IN (
            SELECT COD_MESTRE_EVENTO
            FROM RHFP1003
            WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
              AND COD_ORGANOGRAMA = 8
              AND COD_EVENTO IN (1, 17, 19, 26)
          )
          AND E.EDICAO_NIVEL2 = '008'
          AND NV.COD_NIVEL_ORG = 2
          AND NV.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,
                                         322,326,327,328,329,330,331,335,349,399,939,
                                         1740, 2147,2148,2149,2150,2151)
          AND NV.COD_ORGANOGRAMA_SUB NOT IN (344)
          AND B.TIPO_VD = 'V'
          AND A.COD_VD NOT IN (292,4033)
          AND A.VALOR_VD <> 0
        GROUP BY
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
          A.COD_VD,
          B.NOME_VD
  ),
  Base_D AS (
      SELECT
          E.EDICAO_NIVEL2 AS EDICAO_ORG_REP,
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
            :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
            CASE
              WHEN A.COD_VD = 1003 THEN 1004
              ELSE A.COD_VD
            END AS COD_VD,
            CASE
              WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões'
              ELSE B.NOME_VD
            END AS NOME_VD,
            SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
            ROW_NUMBER() OVER (PARTITION BY TO_NUMBER(E.EDICAO_NIVEL2) ORDER BY CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END) AS RN
          FROM
            RHFP1006 A
            INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
            LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
            INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
            LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
            LEFT JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
            LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG
          WHERE
            A.COD_MESTRE_EVENTO IN (
              SELECT COD_MESTRE_EVENTO
              FROM RHFP1003
              WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
                AND COD_ORGANOGRAMA = 8
                AND COD_EVENTO IN (1, 17, 19, 26)
            )

            AND E.EDICAO_NIVEL2 = '008'
            AND NV.COD_NIVEL_ORG = 2
            AND (
              B.TIPO_VD = 'D'
              OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19))  -- Ajuste aqui para considerar apenas os eventos 17 e 19 para VD 1003
            )
            AND A.VALOR_VD <> 0
          GROUP BY
            E.EDICAO_NIVEL2,
            NV.NOME_ORGANOGRAMA,
            A.COD_VD,
            B.NOME_VD,
            CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END,
            CASE WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões' ELSE B.NOME_VD END
  ),
  Base_O AS (
       SELECT

      E.EDICAO_NIVEL2 AS EDICAO_ORG_REP, -- Duplicando a coluna para uso interno
      E.EDICAO_NIVEL2,
      NV.NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER (PARTITION BY E.EDICAO_NIVEL2 ORDER BY A.COD_VD) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      INNER JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, '31/12/2999')
      INNER JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
       LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG
    WHERE
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND NV.COD_NIVEL_ORG = 2
      AND NV.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,
                                     322,326,327,328,329,330,331,335,349,399,939,
                                     1740, 2147,2148,2149,2150,2151)
      AND NV.COD_ORGANOGRAMA_SUB NOT IN (344)
      AND A.COD_VD IN (12, 885, 908, 910, 912, 914, 915, 916, 924, 925, 926,
                       927,1063, 1064, 1067, 1068, 1231, 1232, 1233, 1234,
                       1456, 1457, 1458, 1459, 1461, 1462, 1463, 1464,
                       1910, 1924, 1934, 1935, 1941, 2222, 2232, 2601,
                       2602, 2605, 2611, 2612, 2615, 2616, 2617, 2701,
                       2705, 2706, 2711, 2712, 2713, 2714, 2715, 2716, 2717)
      AND A.COD_VD NOT IN (292,4033)
      AND A.VALOR_VD <> 0

    GROUP BY
      E.EDICAO_NIVEL2,
      NV.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Totais AS (
    SELECT
      V.EDICAO_NIVEL2 AS EDICAO_ORG_REP,
      V.EDICAO_NIVEL2,
      V.NOME_ORGANOGRAMA,
      V.REFERENCIA,
      V.TOTAL_V,
      D.TOTAL_D,
      V.TOTAL_V - D.TOTAL_D AS TOTAL_LIQUIDO
    FROM
      (SELECT EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA, SUM(TOTAL_MES) AS TOTAL_V
       FROM Base_V
       GROUP BY EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA) V
    LEFT JOIN
      (SELECT EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA, SUM(TOTAL_MES) AS TOTAL_D
       FROM Base_D
       GROUP BY EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA) D
    ON V.EDICAO_NIVEL2 = D.EDICAO_NIVEL2
  ),
  Combined_Base AS (
    SELECT
      COALESCE(V.EDICAO_ORG_REP, D.EDICAO_ORG_REP, O.EDICAO_ORG_REP) AS EDICAO_ORG_REP,
      COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2, O.EDICAO_NIVEL2) AS EDICAO_EMP,
      COALESCE(V.NOME_ORGANOGRAMA, D.NOME_ORGANOGRAMA, O.NOME_ORGANOGRAMA) AS NOME_ORGANOGRAMA,
      COALESCE(V.REFERENCIA, D.REFERENCIA, O.REFERENCIA) AS REFERENCIA,
      V.COD_VD AS COD_VD_V,
      V.NOME_VD AS NOME_VD_V,
      TO_CHAR(V.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_V,
      D.COD_VD AS COD_VD_D,
      D.NOME_VD AS NOME_VD_D,
      TO_CHAR(D.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_D,
      O.COD_VD AS COD_VD_O,
      O.NOME_VD AS NOME_VD_O,
      TO_CHAR(O.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_O,
      COALESCE(V.RN, D.RN, O.RN) AS RN,
      DENSE_RANK() OVER (PARTITION BY COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2, O.EDICAO_NIVEL2) ORDER BY COALESCE(V.RN, D.RN, O.RN)) AS DR
    FROM
      Base_V V
      FULL OUTER JOIN Base_D D ON V.EDICAO_NIVEL2 = D.EDICAO_NIVEL2 AND V.RN = D.RN
      FULL OUTER JOIN Base_O O ON COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2) = O.EDICAO_NIVEL2 AND COALESCE(V.RN, D.RN) = O.RN
  ),
  Headers AS (
    SELECT
      EDICAO_ORG_REP,
      EDICAO_EMP,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      'VENCIMENTOS' AS HEADER_V,
      'DESCONTOS' AS HEADER_D,
      'OUTROS' AS HEADER_O,
      0 AS RN
    FROM
      (SELECT DISTINCT EDICAO_ORG_REP, EDICAO_EMP, NOME_ORGANOGRAMA, REFERENCIA FROM Combined_Base)
  ),
  Totals AS (
    SELECT
      EDICAO_ORG_REP,
      EDICAO_NIVEL2,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      'TOTAL VENCIMENTOS' AS NOME_VD_V,
      TO_CHAR(T.TOTAL_V, 'FM999G999G990D00') AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      'TOTAL DESCONTOS' AS NOME_VD_D,
      TO_CHAR(T.TOTAL_D, 'FM999G999G990D00') AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      'TOTAL LÍQUIDO' AS NOME_VD_O,
      TO_CHAR(T.TOTAL_LIQUIDO, 'FM999G999G990D00') AS TOTAL_MES_O,
      NULL AS RN,
      2 AS ORDER_COL
    FROM
      Totais T
  ),
  Blank_Lines AS (
    SELECT
      DISTINCT
      EDICAO_ORG_REP,
      EDICAO_EMP,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      3 AS ORDER_COL
    FROM
      Headers
  ),
  Final_Result AS (
    SELECT
      H.EDICAO_ORG_REP,
      H.EDICAO_EMP,
      H.NOME_ORGANOGRAMA,
      H.REFERENCIA,
      NULL AS COD_VD_V,
      H.HEADER_V AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      H.HEADER_D AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      H.HEADER_O AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      H.RN,
      0 AS ORDER_COL
    FROM
      Headers H
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_EMP,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      RN,
      1 AS ORDER_COL
    FROM
      Combined_Base
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_EMP,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      NULL AS COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      NULL AS COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      NULL AS RN,
      ORDER_COL
    FROM
      Totals
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_EMP,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      ORDER_COL
    FROM
      Blank_Lines
  )
SELECT
  -- Lista de colunas sem a coluna EDICAO_ORG_REP
  EDICAO_EMP,
  NOME_ORGANOGRAMA,
  REFERENCIA,
  COD_VD_V,
  NOME_VD_V,
  TOTAL_MES_V,
  COD_VD_D,
  NOME_VD_D,
  TOTAL_MES_D,
  COD_VD_O,
  NOME_VD_O,
  TOTAL_MES_O
  --RN,
  --ORDER_COL
FROM
  Final_Result
ORDER BY
  EDICAO_ORG_REP ASC, -- Usando a coluna de repetição para ordenação
  ORDER_COL ASC,
  RN ASC


--========================


/*====VERSÃO PARA O GERADOR DE RELATÓRIOS====*/
/*VERSÃO COM SELEÇÃO*/

WITH
Base_V AS (
       SELECT
          E.EDICAO_NIVEL2 AS EDICAO_ORG_REP,
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
          :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
          A.COD_VD,
          B.NOME_VD,
          SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
          ROW_NUMBER() OVER (PARTITION BY E.EDICAO_NIVEL2 ORDER BY A.COD_VD) AS RN
        FROM
          RHFP1006 A
          INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
          INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
          INNER JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, '31/12/2999')
          INNER JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
           LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG
        WHERE
          COD_MESTRE_EVENTO IN (
            SELECT COD_MESTRE_EVENTO
            FROM RHFP1003
            WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
              AND COD_ORGANOGRAMA = 8
              AND COD_EVENTO IN (1, 17, 19, 26)
          )
          AND E.EDICAO_NIVEL2 = '008'
          AND NV.COD_NIVEL_ORG = 2
          AND NV.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,
                                         322,326,327,328,329,330,331,335,349,399,939,
                                         1740, 2147,2148,2149,2150,2151)
          AND NV.COD_ORGANOGRAMA_SUB NOT IN (344)
          AND B.TIPO_VD = 'V'
          AND A.COD_VD NOT IN (292,4033)
          AND A.VALOR_VD <> 0
        GROUP BY
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
          A.COD_VD,
          B.NOME_VD
  ),
  Base_D AS (
      SELECT
          E.EDICAO_NIVEL2 AS EDICAO_ORG_REP,
          E.EDICAO_NIVEL2,
          NV.NOME_ORGANOGRAMA,
            :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
            CASE
              WHEN A.COD_VD = 1003 THEN 1004
              ELSE A.COD_VD
            END AS COD_VD,
            CASE
              WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões'
              ELSE B.NOME_VD
            END AS NOME_VD,
            SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
            ROW_NUMBER() OVER (PARTITION BY TO_NUMBER(E.EDICAO_NIVEL2) ORDER BY CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END) AS RN
          FROM
            RHFP1006 A
            INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
            LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
            INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
            LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
            LEFT JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
            LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG
          WHERE
            A.COD_MESTRE_EVENTO IN (
              SELECT COD_MESTRE_EVENTO
              FROM RHFP1003
              WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
                AND COD_ORGANOGRAMA = 8
                AND COD_EVENTO IN (1, 17, 19, 26)
            )

            AND E.EDICAO_NIVEL2 = '008'
            AND NV.COD_NIVEL_ORG = 2
            AND (
              B.TIPO_VD = 'D'
              OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19))  -- Ajuste aqui para considerar apenas os eventos 17 e 19 para VD 1003
            )
            AND A.VALOR_VD <> 0
          GROUP BY
            E.EDICAO_NIVEL2,
            NV.NOME_ORGANOGRAMA,
            A.COD_VD,
            B.NOME_VD,
            CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END,
            CASE WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões' ELSE B.NOME_VD END
  ),
  Base_O AS (
       SELECT

      E.EDICAO_NIVEL2 AS EDICAO_ORG_REP, -- Duplicando a coluna para uso interno
      E.EDICAO_NIVEL2,
      NV.NOME_ORGANOGRAMA,
      :DATA_INICIO || ' - ' || :DATA_FIM AS REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER (PARTITION BY E.EDICAO_NIVEL2 ORDER BY A.COD_VD) AS RN
    FROM
      RHFP1006 A
      INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
      INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO AND :DATA_FIM BETWEEN D.DATA_INICIO AND D.DATA_FIM
      INNER JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, '31/12/2999')
      INNER JOIN RHFP0400 F ON E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
       LEFT JOIN V_ORGANOGRAMAS_NIVEIS NV ON E.EDICAO_NIVEL2 = NV.EDICAO_ORG
    WHERE
      COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN :DATA_INICIO AND :DATA_FIM
          AND COD_ORGANOGRAMA = 8
          AND COD_EVENTO IN (1, 17, 19, 26)
      )
      AND E.EDICAO_NIVEL2 = '008'
      AND NV.COD_NIVEL_ORG = 2
      AND NV.COD_ORGANOGRAMA NOT IN (293,301,302,304,305,309,313,315,316,318,320,
                                     322,326,327,328,329,330,331,335,349,399,939,
                                     1740, 2147,2148,2149,2150,2151)
      AND NV.COD_ORGANOGRAMA_SUB NOT IN (344)
      AND A.COD_VD IN (12, 885, 908, 910, 912, 914, 915, 916, 924, 925, 926,
                       927,1063, 1064, 1067, 1068, 1231, 1232, 1233, 1234,
                       1456, 1457, 1458, 1459, 1461, 1462, 1463, 1464,
                       1910, 1924, 1934, 1935, 1941, 2222, 2232, 2601,
                       2602, 2605, 2611, 2612, 2615, 2616, 2617, 2701,
                       2705, 2706, 2711, 2712, 2713, 2714, 2715, 2716, 2717)
      AND A.COD_VD NOT IN (292,4033)
      AND A.VALOR_VD <> 0

    GROUP BY
      E.EDICAO_NIVEL2,
      NV.NOME_ORGANOGRAMA,
      A.COD_VD,
      B.NOME_VD
  ),
  Totais AS (
    SELECT
      V.EDICAO_NIVEL2 AS EDICAO_ORG_REP,
      V.EDICAO_NIVEL2,
      V.NOME_ORGANOGRAMA,
      V.REFERENCIA,
      V.TOTAL_V,
      D.TOTAL_D,
      V.TOTAL_V - D.TOTAL_D AS TOTAL_LIQUIDO
    FROM
      (SELECT EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA, SUM(TOTAL_MES) AS TOTAL_V
       FROM Base_V
       GROUP BY EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA) V
    LEFT JOIN
      (SELECT EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA, SUM(TOTAL_MES) AS TOTAL_D
       FROM Base_D
       GROUP BY EDICAO_NIVEL2, NOME_ORGANOGRAMA, REFERENCIA) D
    ON V.EDICAO_NIVEL2 = D.EDICAO_NIVEL2
  ),
  Combined_Base AS (
    SELECT
      COALESCE(V.EDICAO_ORG_REP, D.EDICAO_ORG_REP, O.EDICAO_ORG_REP) AS EDICAO_ORG_REP,
      COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2, O.EDICAO_NIVEL2) AS EDICAO_EMP,
      COALESCE(V.NOME_ORGANOGRAMA, D.NOME_ORGANOGRAMA, O.NOME_ORGANOGRAMA) AS NOME_ORGANOGRAMA,
      COALESCE(V.REFERENCIA, D.REFERENCIA, O.REFERENCIA) AS REFERENCIA,
      V.COD_VD AS COD_VD_V,
      V.NOME_VD AS NOME_VD_V,
      TO_CHAR(V.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_V,
      D.COD_VD AS COD_VD_D,
      D.NOME_VD AS NOME_VD_D,
      TO_CHAR(D.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_D,
      O.COD_VD AS COD_VD_O,
      O.NOME_VD AS NOME_VD_O,
      TO_CHAR(O.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_O,
      COALESCE(V.RN, D.RN, O.RN) AS RN,
      DENSE_RANK() OVER (PARTITION BY COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2, O.EDICAO_NIVEL2) ORDER BY COALESCE(V.RN, D.RN, O.RN)) AS DR
    FROM
      Base_V V
      FULL OUTER JOIN Base_D D ON V.EDICAO_NIVEL2 = D.EDICAO_NIVEL2 AND V.RN = D.RN
      FULL OUTER JOIN Base_O O ON COALESCE(V.EDICAO_NIVEL2, D.EDICAO_NIVEL2) = O.EDICAO_NIVEL2 AND COALESCE(V.RN, D.RN) = O.RN
  ),
  Headers AS (
    SELECT
      EDICAO_ORG_REP,
      EDICAO_EMP,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS HEADER_V,
      NULL AS HEADER_D,
      NULL AS HEADER_O,
      3 AS RN
    FROM
      (SELECT DISTINCT EDICAO_ORG_REP, EDICAO_EMP, NOME_ORGANOGRAMA, REFERENCIA FROM Combined_Base)
  ),
  Totals AS (
    SELECT
      EDICAO_ORG_REP,
      EDICAO_NIVEL2 AS EDICAO_EMP,
      NOME_ORGANOGRAMA,
      REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      2 AS ORDER_COL,
      TO_CHAR(T.TOTAL_V, 'FM999G999G990D00') AS TOTAL_V,
      TO_CHAR(T.TOTAL_D, 'FM999G999G990D00') AS TOTAL_D,
      TO_CHAR(T.TOTAL_LIQUIDO, 'FM999G999G990D00') AS TOTAL_LIQUIDO
    FROM
      Totais T
  ),
  Final_Result AS (
    SELECT
      H.EDICAO_ORG_REP,
      H.EDICAO_EMP,
      H.NOME_ORGANOGRAMA,
      H.REFERENCIA,
      NULL AS COD_VD_V,
      H.HEADER_V AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      H.HEADER_D AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      H.HEADER_O AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      H.RN,
      0 AS ORDER_COL,
      (SELECT 'Total de Vencimentos:  ' || TO_CHAR(TOTAL_V, 'FM999G999G990D00')
       FROM Totais) AS TOTAL_V,
      (SELECT 'Total de Descontos:  ' || TO_CHAR(TOTAL_D, 'FM999G999G990D00')
       FROM Totais) TOTAL_D,
      (SELECT 'Total de Líquido:  ' || TO_CHAR(TOTAL_LIQUIDO, 'FM999G999G990D00')
       FROM Totais) TOTAL_LIQUIDO
    FROM
      Headers H
    UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_EMP,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      COD_VD_V,
      NOME_VD_V,
      TOTAL_MES_V,
      COD_VD_D,
      NOME_VD_D,
      TOTAL_MES_D,
      COD_VD_O,
      NOME_VD_O,
      TOTAL_MES_O,
      RN,
      1 AS ORDER_COL,
      NULL AS TOTAL_V,
      NULL AS TOTAL_D,
      NULL AS TOTAL_LIQUIDO
    FROM
      Combined_Base
    /*UNION ALL
    SELECT
      EDICAO_ORG_REP,
      NULL AS EDICAO_EMP,
      NULL AS NOME_ORGANOGRAMA,
      NULL AS REFERENCIA,
      NULL AS COD_VD_V,
      NULL AS NOME_VD_V,
      NULL AS TOTAL_MES_V,
      NULL AS COD_VD_D,
      NULL AS NOME_VD_D,
      NULL AS TOTAL_MES_D,
      NULL AS COD_VD_O,
      NULL AS NOME_VD_O,
      NULL AS TOTAL_MES_O,
      NULL AS RN,
      1 AS ORDER_COL,
      TOTAL_V,
      TOTAL_D,
      TOTAL_LIQUIDO
    FROM
      Totals*/
  )
SELECT
  -- Lista de colunas sem a coluna EDICAO_ORG_REP
  EDICAO_EMP,
  NOME_ORGANOGRAMA,
  REFERENCIA,
  COD_VD_V,
  NOME_VD_V,
  TOTAL_MES_V,
  COD_VD_D,
  NOME_VD_D,
  TOTAL_MES_D,
  COD_VD_O,
  NOME_VD_O,
  TOTAL_MES_O,
  TOTAL_V,
  TOTAL_D,
  TOTAL_LIQUIDO
FROM
  Final_Result
ORDER BY
  EDICAO_ORG_REP ASC, -- Usando a coluna de repetição para ordenação
  ORDER_COL ASC,
  RN ASC

