--SQL PARA MAPEAR OS ANIVERSARIANTES DA TI

SELECT 
    COD_CONTRATO, 
    DES_PESSOA, 
    DATA_NASCIMENTO, 
    COD_UNIDADE,
    CASE 
        WHEN EXTRACT(MONTH FROM DATA_NASCIMENTO) < EXTRACT(MONTH FROM SYSDATE) OR
             (EXTRACT(MONTH FROM DATA_NASCIMENTO) = EXTRACT(MONTH FROM SYSDATE) AND 
              EXTRACT(DAY FROM DATA_NASCIMENTO) < EXTRACT(DAY FROM SYSDATE)) THEN 
            TO_DATE(EXTRACT(DAY FROM DATA_NASCIMENTO) || '/' || 
                    EXTRACT(MONTH FROM DATA_NASCIMENTO) || '/' || 
                    (EXTRACT(YEAR FROM SYSDATE)+1), 'DD/MM/YYYY')
        ELSE 
            TO_DATE(EXTRACT(DAY FROM DATA_NASCIMENTO) || '/' || 
                    EXTRACT(MONTH FROM DATA_NASCIMENTO) || '/' || 
                    EXTRACT(YEAR FROM SYSDATE), 'DD/MM/YYYY')
    END AS PROXIMO_ANIVERSARIO
FROM 
    V_DADOS_COLAB_AVT
WHERE 
    COD_UNIDADE IN (740, 768, 769) AND STATUS = 0
ORDER BY 
    PROXIMO_ANIVERSARIO ASC;
