--======TABELA DAS AVALIAÇÕES REALIZADAS=====--
--MAPEAMNETO PARA SABER SE HÁ QUEM NÃO SE APLICA NAS AVALIAÇÕES

--FILTRO SOMENTE COLABORADORES GERAL--

SELECT * FROM GRZ_AVALIACAO_REALIZADAS
WHERE DATA_ADMISSAO > '01/07/2023'
AND DES_FUNCAO NOT LIKE '%APRENDIZ%'
AND DES_FUNCAO NOT LIKE '%ESTAGIARIO%'
AND (DES_FUNCAO NOT LIKE '%GERENTE LOJA%' OR DES_FUNCAO NOT LIKE '%GERENTE DE LOJA%')


--FILTRO SOMENTE POR CARGOS QUE NÃO RECEBEM--

SELECT * FROM GRZ_AVALIACAO_REALIZADAS
WHERE DES_FUNCAO LIKE '%APRENDIZ%'
OR DES_FUNCAO LIKE '%ESTAGIARIO%'


--FILTRO DE GERENTES QUE NÃO SE APLICAM AS AVALIAÇÕES


SELECT A.COD_CONTRATO, A.NOME_PESSOA, A.DES_FUNCAO, B.DATA_INICIO_CLH, A.DATA_ADMISSAO, B.COD_UNIDADE, A.DES_UNIDADE, A.NUM_MEDIA 
FROM GRZ_AVALIACAO_REALIZADAS A
INNER JOIN V_DADOS_COLAB_AVT B ON A.COD_CONTRATO = B.COD_CONTRATO
WHERE (A.DES_FUNCAO LIKE '%GERENTE LOJA%' OR A.DES_FUNCAO LIKE '%GERENTE DE LOJA%')



SELECT * FROM V_DADOS_COLAB_AVT




--======TABELA DAS AVALIAÇÕES NÃO REALIZADAS=====--
--MAPEAMNETO PARA SABER SE HÁ QUEM SE APLICA NAS AVALIAÇÕES


SELECT * FROM GRZ_AVALIACAO_NAO_REALIZADAS