---===SQL PARA ATUALIZAR NOMES DAS CONTAS CONTÁBEIS


SELECT A.*, ROWID
FROM RHFP0403 A
WHERE (A.COD_CONTA_CONTABIL LIKE '%341%'
OR A.COD_CONTA_CONTABIL LIKE '%342%')


UPDATE RHFP0403
SET NOME_CONTA_CONTABIL = CASE
    WHEN SUBSTR(COD_CONTA_CONTABIL, 1, 3) = '341' THEN NOME_CONTA_CONTABIL || ' - LOJAS'
    WHEN SUBSTR(COD_CONTA_CONTABIL, 1, 3) = '342' THEN NOME_CONTA_CONTABIL || ' - ADM'
END
WHERE SUBSTR(COD_CONTA_CONTABIL, 1, 3) = '341'
OR SUBSTR(COD_CONTA_CONTABIL, 1, 3) = '342';


--===TABELA DE BACKUP DAS CONTAS COM NOMES ORIGINAIS ORIGINAIS

RHFP0403_BKP 