/*SQL PARA MAPEAR COLABORADORES QUE NÃO FORAM INTEGRADOS NO NL COM A MÁSCARA 50*/

SELECT *
  FROM V_DADOS_PESSOA A
 WHERE A.COD_EMP = 8
   AND A.DTA_ADMISSAO >= '01/01/2024'
   AND A.DTA_DEMISSAO IS NULL
   AND NOT EXISTS (SELECT 1
          FROM NL.PS_MASCARAS@NLGRZ B
         WHERE B.COD_COMPLETO = '0100' || A.COD_CONTRATO
           AND B.COD_MASCARA = 50);