SELECT B.COD_CONTRATO,b.NOME_FUNCIONARIO, B.EDICAO_FILIAL, B.NOME_FILIAL, B.EDICAO_NIVEL5, B.NOME_ORGANOGRAMA,  A.COD_CONTRATO, A.COD_PERFIL, C.NOME_PERFIL, D.DES_FUNCAO
FROM RHCS0300 A, FUNCIONARIOS B, RHCS0230 C,V_DADOS_PESSOA D 
WHERE A.COD_CONTRATO (+) = B.COD_CONTRATO 
AND B.STATUS_CONTRATO = 0
AND C.COD_PERFIL (+) = A.COD_PERFIL
AND D.COD_CONTRATO (+) = B.COD_CONTRATO
and d.cod_funcao in (102,120,121,122,123,204,206,264,305)
ORDER BY D.COD_EMP, B.NOME_ORGANOGRAMA, A.COD_PERFIL ASC

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT b.NOME_FUNCIONARIO, B.EDICAO_FILIAL, B.NOME_FILIAL, B.EDICAO_NIVEL5, B.NOME_ORGANOGRAMA, B.COD_CONTRATO, A.COD_CONTRATO, A.COD_PERFIL, E.COD_PERFIL AS cod_perfil_1,C.NOME_PERFIL,  D.DES_FUNCAO,  D.COD_EMP
FROM RHCS0300 A, FUNCIONARIOS B, RHCS0230 C,V_DADOS_PESSOA D , RHCS0310 E
WHERE A.COD_CONTRATO (+) = B.COD_CONTRATO 
AND B.STATUS_CONTRATO = 0
AND C.COD_PERFIL (+) = A.COD_PERFIL
AND D.COD_CONTRATO (+) = B.COD_CONTRATO
AND E.COD_CONTRATO (+) = B.COD_CONTRATO
AND E.DATA_AVALIACAO = (SELECT MAX(J.DATA_AVALIACAO)AS DATA_AVALIACAO FROM RHCS0310 J WHERE E.COD_CONTRATO = J.COD_CONTRATO)
AND d.cod_funcao not in (74)
--AND NOME_FILIAL = 'GZT COMERCIO E IMPORTACAO SA'
ORDER BY D.COD_EMP, B.NOME_ORGANOGRAMA, A.COD_PERFIL ASC