---MAP DE DADOS DOS REPs (relógios ponto) PARA ANTIRION REALIZAR A INSTALAÇÃO DO INTEGRADOR

SELECT DISTINCT
       A.CODIGO_FILIAL,
       A.DESCRICAO,
       CASE
           WHEN A.CODIGO_FILIAL = B.EDICAO_FILIAL AND B.COD_EMP NOT IN (4, 282, 1629) THEN
             B.DES_FILIAL
           WHEN A.CODIGO_FILIAL = B.COD_EMP THEN
             B.DES_EMPRESA
           ELSE
            NULL
       END AS DES_LOCAL,
       A.SERIAL,
       A.IP 
FROM REP_LOJAS_BASE A
JOIN V_DADOS_COLAB_AVT B
  ON A.CODIGO_FILIAL = B.EDICAO_FILIAL
  OR A.CODIGO_FILIAL = B.COD_EMP
WHERE B.STATUS = 0
AND b.COD_EMP IN (4, 8, 282, 1629)

SELECT * FROM V_DADOS_LOJAS_AVT

SELECT * FROM V_DADOS_COLAB_AVT


SELECT A.*, ROWID
FROM REP_LOJAS_BASE  A


SELECT DISTINCT(TABLE_NAME) 
FROM ALL_TAB_COLUMNS 
WHERE UPPER (TABLE_NAME) LIKE '%RHAF%'
AND COLUMN_NAME LIKE '%COLETOR%'




SELECT * FROM RHAF0016
WHERE COD_CONTRATO = 389622
AND DATA >= SYSDATE

SELECT * FROM RHAF1130
WHERE COD_COLETOR = 2