/*SQLs FIADORES SISLOGWEB*/


SELECT DISTINCT A.COD_UNIDADE,
                A.DES_FANTASIA,
                C.COD_FIADOR,
                C.DES_FIADOR,
                A.REDE,
                D.COD_GRUPO,
                TO_CHAR(B.DTA_INICIO, 'DD /MM/YYYY') AS DTA_INICIO,
                TO_CHAR(B.DTA_TERMINO, 'DD /MM/YYYY') AS DTA_TERMINO,
                B.IND_INATIVO
  FROM V_UNIDADES_ATIVAS A
 INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
 INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
 INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
  LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO =
                                                     E.COD_CONTRATO
 WHERE D.COD_GRUPO = 999
   AND A.COD_UNIDADE BETWEEN 0 AND 9999
   AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
   AND B.IND_INATIVO = 0
   --AND C.COD_FIADOR = 3
 ORDER BY A.REDE, A.COD_UNIDADE
 
 
 
 
--===OFICIAL==--
select DISTINCT ( 
SELECT 'DETALHE' AS TIPO,
       A.COD_UNIDADE,
       A.DES_FANTASIA,
       C.COD_FIADOR,
       C.DES_FIADOR,
       A.REDE,
       D.COD_GRUPO,
       TO_CHAR(B.DTA_INICIO, 'DD/MM/YYYY') AS DTA_INICIO,
       TO_CHAR(B.DTA_TERMINO, 'DD/MM/YYYY') AS DTA_TERMINO,
       B.IND_INATIVO,
       NULL AS TOTAL
FROM V_UNIDADES_ATIVAS A
INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO = E.COD_CONTRATO
WHERE D.COD_GRUPO = 999
  AND A.COD_UNIDADE BETWEEN 0 AND 9999
  AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
  AND B.IND_INATIVO = 0

UNION ALL

SELECT 'Total VR Grazziotin S/A' AS TIPO,
       NULL AS COD_UNIDADE,
       NULL AS DES_FANTASIA,
       NULL AS COD_FIADOR,
       NULL AS DES_FIADOR,
       NULL AS REDE,
       NULL AS COD_GRUPO,
       NULL AS DTA_INICIO,
       NULL AS DTA_TERMINO,
       NULL AS IND_INATIVO,
       COUNT(DISTINCT A.COD_UNIDADE) AS TOTAL -- Usando DISTINCT
FROM V_UNIDADES_ATIVAS A
INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO = E.COD_CONTRATO
WHERE D.COD_GRUPO = 999
  AND A.COD_UNIDADE BETWEEN 0 AND 9999
  AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
  AND B.IND_INATIVO = 0
  AND C.COD_FIADOR = 1

UNION ALL


SELECT 'TOTAL NENHUM' AS TIPO,
       NULL AS COD_UNIDADE,
       NULL AS DES_FANTASIA,
       NULL AS COD_FIADOR,
       NULL AS DES_FIADOR,
       NULL AS REDE,
       NULL AS COD_GRUPO,
       NULL AS DTA_INICIO,
       NULL AS DTA_TERMINO,
       NULL AS IND_INATIVO,
       COUNT(DISTINCT A.COD_UNIDADE) AS TOTAL 
FROM V_UNIDADES_ATIVAS A
INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO = E.COD_CONTRATO
WHERE D.COD_GRUPO = 999
  AND A.COD_UNIDADE BETWEEN 0 AND 9999
  AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
  AND B.IND_INATIVO = 0
  AND C.COD_FIADOR = 3

UNION ALL

SELECT 'TOTAL GERAL' AS TIPO,
       NULL AS COD_UNIDADE,
       NULL AS DES_FANTASIA,
       NULL AS COD_FIADOR,
       NULL AS DES_FIADOR,
       NULL AS REDE,
       NULL AS COD_GRUPO,
       NULL AS DTA_INICIO,
       NULL AS DTA_TERMINO,
       NULL AS IND_INATIVO,
       COUNT(DISTINCT A.COD_UNIDADE) AS TOTAL 
FROM V_UNIDADES_ATIVAS A
 INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
 INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
 INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
  LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO =
                                                     E.COD_CONTRATO
 WHERE D.COD_GRUPO = 999
   AND A.COD_UNIDADE BETWEEN 0 AND 9999
   AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
  AND B.IND_INATIVO = 0
  AND C.COD_FIADOR IN (1, 3)

ORDER BY REDE, COD_UNIDADE)
FROM DUAL;








SELECT 'DETALHE' AS TIPO,
       A.COD_UNIDADE,
       A.DES_FANTASIA,
       C.COD_FIADOR,
       C.DES_FIADOR,
       A.REDE,
       D.COD_GRUPO,
       TO_CHAR(B.DTA_INICIO, 'DD/MM/YYYY') AS DTA_INICIO,
       TO_CHAR(B.DTA_TERMINO, 'DD/MM/YYYY') AS DTA_TERMINO,
       B.IND_INATIVO,
       NULL AS TOTAL
FROM V_UNIDADES_ATIVAS A
INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO = E.COD_CONTRATO
WHERE D.COD_GRUPO = 999
  AND A.COD_UNIDADE BETWEEN 0 AND 9999
  AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
  AND B.IND_INATIVO = 0

UNION ALL

SELECT 'Total VR Grazziotin S/A' AS TIPO,
       NULL AS COD_UNIDADE,
       NULL AS DES_FANTASIA,
       NULL AS COD_FIADOR,
       NULL AS DES_FIADOR,
       NULL AS REDE,
       NULL AS COD_GRUPO,
       NULL AS DTA_INICIO,
       NULL AS DTA_TERMINO,
       NULL AS IND_INATIVO,
       COUNT(DISTINCT A.COD_UNIDADE) AS TOTAL -- Usando DISTINCT
FROM V_UNIDADES_ATIVAS A
INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO = E.COD_CONTRATO
WHERE D.COD_GRUPO = 999
  AND A.COD_UNIDADE BETWEEN 0 AND 9999
  AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
  AND B.IND_INATIVO = 0
  AND C.COD_FIADOR = 1

UNION ALL


SELECT 'TOTAL NENHUM' AS TIPO,
       NULL AS COD_UNIDADE,
       NULL AS DES_FANTASIA,
       NULL AS COD_FIADOR,
       NULL AS DES_FIADOR,
       NULL AS REDE,
       NULL AS COD_GRUPO,
       NULL AS DTA_INICIO,
       NULL AS DTA_TERMINO,
       NULL AS IND_INATIVO,
       COUNT(DISTINCT A.COD_UNIDADE) AS TOTAL 
FROM V_UNIDADES_ATIVAS A
INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO = E.COD_CONTRATO
WHERE D.COD_GRUPO = 999
  AND A.COD_UNIDADE BETWEEN 0 AND 9999
  AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
  AND B.IND_INATIVO = 0
  AND C.COD_FIADOR = 3

UNION ALL

SELECT 'TOTAL GERAL' AS TIPO,
       NULL AS COD_UNIDADE,
       NULL AS DES_FANTASIA,
       NULL AS COD_FIADOR,
       NULL AS DES_FIADOR,
       NULL AS REDE,
       NULL AS COD_GRUPO,
       NULL AS DTA_INICIO,
       NULL AS DTA_TERMINO,
       (SELECT DISTINCT (A.COD_UNIDADE)                
  FROM V_UNIDADES_ATIVAS A
 INNER JOIN GRAZZ.GRZ_LOC_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE
 INNER JOIN GRAZZ.GRZ_FIADORES C ON B.COD_FIADOR = C.COD_FIADOR
 INNER JOIN NL.GE_GRUPOS_UNIDADES D ON A.COD_UNIDADE = D.COD_UNIDADE
  LEFT JOIN GRAZZ.GRZ_LOC_CONTRATOS_PRORROGACAO E ON B.COD_CONTRATO =
                                                     E.COD_CONTRATO
 WHERE D.COD_GRUPO = 999
   AND A.COD_UNIDADE BETWEEN 0 AND 9999
   AND (B.DTA_TERMINO > SYSDATE OR E.DTA_FIM_PRORR < SYSDATE)
   AND B.IND_INATIVO = 0
   --AND C.COD_FIADOR = 3
       ) AS IND_INATIVO
FROM DUAL

-- Finalmente, aplique a ordenação:
ORDER BY REDE, COD_UNIDADE;
