--TABELA QUE ARMAZENA OS DADOS DAS ÁREAS DO ADM, GESTOR E SUAS EQUIPES

SELECT * FROM GRZ_EQUIPES_SETORES

CREATE TABLE GRZ_EQUIPES_SETORES (
COD_CONTRATO NUMBER(6),
DES_PESSOA VARCHAR2(250),
CPF VARCHAR2(18),
COD_FUNCAO NUMBER(5),
DES_FUNCAO VARCHAR2(150),
COD_ORGANOGRAMA NUMBER(5),
COD_UNIDADE NUMBER(5),
DES_UNIDADE VARCHAR2(180),
CPF_GESTOR VARCHAR2(18),
COD_UNIDADE_SUB NUMBER(5),
DES_UNIDADE_SUB VARCHAR2(180),
PRIMARY KEY (COD_CONTRATO, COD_UNIDADE, COD_UNIDADE_SUB)
);
