-- Create table
create table GRZ_KPI_AVALIACAO_PLR_TB
(
  cod_unidade          NUMBER,
  des_unidade          VARCHAR2(200),
  rede                 NUMBER,
  regiao               NUMBER,
  vlr_orcado_vendas    NUMBER(18,2),
  vlr_realizado        NUMBER(18,2),
  vlr_venda_liquida    NUMBER(18,2),
  vlr_lucro            NUMBER(18,2),
  lucratividade        NUMBER(18,2),
  vlr_margem_orc       NUMBER(18,2),
  vlr_margem_real      NUMBER(18,2),
  margem               NUMBER(18,2),
  vlr_falta_inventario NUMBER(18,2),
  inventario           NUMBER(18,2),
  vlr_preventiva       NUMBER(18,2),
  qtd_meses_prev       NUMBER,
  preventiva           NUMBER(18,2),
  vlr_custo_perm       NUMBER(18,2),
  vlr_estoque_ant_perm NUMBER(18,2),
  vlr_medio_emp_perm   NUMBER(18,2),
  vlr_estmedio_perm    NUMBER(18,2),
  permanencia          NUMBER,
  vlr_custo_folha      NUMBER(18,2),
  folha                NUMBER(18,2),
  vlr_vale_trans       NUMBER(18,2),
  vt                   NUMBER(18,2),
  vlr_venda_loja       NUMBER(18,2),
  vlr_vda_domingo      NUMBER(18,2),
  total_hrs            NUMBER,
  produtividade        NUMBER,
  efetivo_inicial      NUMBER,
  efetivo_final        NUMBER,
  efetivo_medio        NUMBER(18,2),
  turnover             NUMBER(18,2),
  ativos_periodo       NUMBER,
  admitidos            NUMBER,
  demitidos            NUMBER,
  dta_ini              DATE,
  dta_fim              DATE,
  qtd_meses_ref        NUMBER
)