WITH CTE_CONTRATOS_UNIDADE AS (
    SELECT 
        A.COD_UNIDADE,
        A.DES_UNIDADE,
        COUNT(A.COD_CONTRATO) AS QTDE_TOTAL_CONTRATOS -- Contagem total de contratos por unidade
    FROM V_DADOS_COLAB_AVT A
    WHERE A.STATUS = 0      
      AND A.STATUS_AFAST IN ('EM ATIVIDADE', 'EM FÉRIAS', 'AFASTADO TEMP')
      AND A.DES_UNIDADE NOT LIKE '%CENTRAL FINANCEIRA%'
      AND (A.COD_TIPO = :TIPO OR :TIPO = 0)
      --AND (A.COD_UNIDADE = :FILIAL OR :FILIAL = 0)
      AND (:FILIAL = '0' OR
           A.COD_UNIDADE IN
          (SELECT * FROM TABLE(SPLIT_CONTRACTS(:FILIAL))))
      AND A.COD_EMP = 8
    GROUP BY A.COD_UNIDADE, A.DES_UNIDADE
)
SELECT 
    A.COD_SINDICATO,
    A.DES_SINDICATO,
    A.DES_PESSOA,
    A.DES_FUNCAO,
    A.DATA_ADMISSAO,
    A.COD_UNIDADE,
    A.DES_UNIDADE,
    B.DES_CIDADE || '/' || B.COD_UF AS CIDADE,
    B.NUM_CNPJ,
    CTE.QTDE_TOTAL_CONTRATOS -- Soma total de contratos por unidade
FROM V_DADOS_COLAB_AVT A
LEFT JOIN V_ORGANOGRAMAS_AVT B ON A.COD_UNIDADE = B.COD_UNIDADE
LEFT JOIN CTE_CONTRATOS_UNIDADE CTE ON A.COD_UNIDADE = CTE.COD_UNIDADE -- Vincula a CTE com a tabela principal
WHERE A.STATUS = 0  
  AND A.STATUS_AFAST IN ('EM ATIVIDADE', 'EM FÉRIAS', 'AFASTADO TEMP')
  AND A.DES_UNIDADE NOT LIKE '%CENTRAL FINANCEIRA%'
  AND (A.COD_TIPO = :TIPO OR :TIPO = 0)
  --AND (A.COD_UNIDADE = :FILIAL OR :FILIAL = 0)
  AND (:FILIAL = '0' OR
        A.COD_UNIDADE IN
       (SELECT * FROM TABLE(SPLIT_CONTRACTS(:FILIAL))))
  AND A.COD_EMP = 8
ORDER BY A.COD_UNIDADE, A.DES_PESSOA
