/*REL DADOS COLABORADORE - RETORNAR O SALÁRIO BRUTO TBM*/

WITH
CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.SEXO,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.NOME_ORGANOGRAMA,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
  --CROSS JOIN DATAS_REF M

 WHERE CT.STATUS = 0 -- CONTRATOS ATIVOS EM QUALQUER DIA DO MÊS
 /*CT.DATA_ADMISSAO <= M.DTA_FIM
 AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31') >= M.DTA_INI*/
/*VERSÕES ALTERNATIVAS DE FILTRAR POR DATA
(('31/03/2025' BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= '31/03/2025' AND CT.DATA_DEMISSAO IS NULL))
AND (CT.DATA_ADMISSAO <= TO_DATE('31/07/2025','DD/MM/YYYY'))
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= TO_DATE('01/07/2025','DD/MM/YYYY'))
AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= '01/07/2025')*/

 AND SYSDATE BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
 AND SYSDATE BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
 AND SYSDATE BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
 AND ORG.COD_EMP = 8
 --AND ORG.COD_TIPO = 1
 AND ORG.EDICAO_ORG_4 IS NOT NULL
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
--AND ORG.COD_UNIDADE = 004
 ORDER BY CT.COD_CONTRATO
),


/*MAPEIA TODOS OS COLABORADORES MAS TAMBÉM COM INFO DE AFASTAMENTO*/
STATUS_AFASTADOS AS (
SELECT DISTINCT ORG.COD_EMP,
                CT.COD_CONTRATO,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFAST,
                AFC.NOME_CAUSA_AFAST AS DES_AFAST,
                AF.DATA_INICIO AS DATA_INI_AFAST,
                AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306                AF,
       RHFP0300                CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT   FN,
       RHFP0100 AFC
       --DATAS_REF               M,
       --PARAMS                  P
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND AF.COD_CAUSA_AFAST = AFC.COD_CAUSA_AFAST(+)
   AND CT.DATA_FIM IS NULL
   /*AND CT.DATA_INICIO <= M.DTA_FIM
   AND NVL(CT.DATA_FIM, DATE '2999-12-31') >= M.DTA_INI*/
      /* AND (CT.DATA_INICIO <= '31/03/2025')
         AND (CT.DATA_INICIO IS NULL OR CT.DATA_FIM >= '01/01/2025')*/
   AND SYSDATE BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND SYSDATE BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND SYSDATE BETWEEN AF.DATA_INICIO(+) AND
       NVL(AF.DATA_FIM(+), DATE '2999-12-31')
   AND ORG.COD_EMP = 8
   --AND ORG.COD_TIPO = 1
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)

),

SALARIO_BRUTO AS (
SELECT COD_CONTRATO,
       VALOR_SALARIO,
       DATA_INICIO,
       DATA_FIM
FROM RHFP0608
WHERE DATA_FIM = '31/12/2999'
--AND COD_CONTRATO = 389622

),

VENCIMENTOS AS (               -- detalhe por contrato+evento (se quiser manter)
  SELECT A.COD_CONTRATO, B.COD_EVENTO, SUM(A.VALOR_VD) AS VLR
    FROM RHFP1006 A
    JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
   WHERE A.COD_VD = 1001
     AND B.DATA_REFERENCIA BETWEEN DATE '2025-09-01' AND DATE
   '2025-09-30'
   GROUP BY A.COD_CONTRATO, B.COD_EVENTO
),
VENCIMENTOS_TOT AS (           -- 1 linha por contrato
  SELECT COD_CONTRATO, SUM(VLR) AS VENC_TOTAL
    FROM VENCIMENTOS
   GROUP BY COD_CONTRATO
),
VDS_SOLICITADOS AS (           -- detalhe por contrato+evento (se quiser manter)
  SELECT A.COD_CONTRATO, B.COD_EVENTO, SUM(A.VALOR_VD) AS VLR
    FROM RHFP1006 A
    JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
   WHERE A.COD_VD IN
         (1, 2, 3, 5, 6, 7, 8, 10, 28, 37, 38, 184, 185, 188, 285)
     AND B.DATA_REFERENCIA BETWEEN DATE '2025-09-01' AND DATE
   '2025-09-30'
   GROUP BY A.COD_CONTRATO, B.COD_EVENTO
),
VDS_SOLICITADOS_TOT AS (       -- 1 linha por contrato
  SELECT COD_CONTRATO, SUM(VLR) AS VDS_TOTAL
    FROM VDS_SOLICITADOS
   GROUP BY COD_CONTRATO
),
AFAST_ATUAL AS (               -- 1 linha por contrato (evita fan-out por afastamentos)
  SELECT COD_CONTRATO,
         MAX(DES_AFAST) KEEP(DENSE_RANK LAST ORDER BY DATA_INI_AFAST) AS DES_AFAST
    FROM STATUS_AFASTADOS
   GROUP BY COD_CONTRATO
),
DADOS AS (
SELECT 0 AS ORDEM,
       NULL COD_TIPO,
       NULL COD_UNIDADE,
       NULL DES_UNIDADE,
       NULL COD_CONTRATO,
       ' DADOS DE COLABORADORES - SOMENTE ATIVOS ' DES_PESSOA,
       NULL DATA_ADMISSAO,
       NULL CARGA_HORARIA,
       NULL SALARIO_BRUTO,
       NULL VENCIMENTOS,
       NULL VDS_SOLICITADOS,
       NULL AFASTAMENTO
  FROM DUAL
UNION ALL
SELECT 1 AS ORDEM,
       A.COD_TIPO,
       A.COD_UNIDADE,
       A.NOME_ORGANOGRAMA AS DES_UNIDADE,
       A.COD_CONTRATO,
       A.DES_PESSOA,
       A.DATA_ADMISSAO,
       A.HR_BASE_MES AS CARGA_HORARIA,
       B.VALOR_SALARIO AS SALARIO_BRUTO,
       VC.VENC_TOTAL AS VENCIMENTOS,
       VD.VDS_TOTAL AS VDS_SOLICITADOS,
       AF.DES_AFAST AS AFASTAMENTO
  FROM CONTRATOS A
  LEFT JOIN SALARIO_BRUTO B ON B.COD_CONTRATO = A.COD_CONTRATO
  LEFT JOIN VENCIMENTOS_TOT VC ON VC.COD_CONTRATO = A.COD_CONTRATO
  LEFT JOIN VDS_SOLICITADOS_TOT VD ON VD.COD_CONTRATO = A.COD_CONTRATO
  LEFT JOIN AFAST_ATUAL AF ON AF.COD_CONTRATO = A.COD_CONTRATO)
  SELECT COD_UNIDADE,
         DES_UNIDADE,
         COD_CONTRATO,
         DES_PESSOA,
         DATA_ADMISSAO,
         CARGA_HORARIA,
         CASE
           WHEN ORDEM = 0 THEN
            NULL
           ELSE
            TO_CHAR(NVL(SALARIO_BRUTO, 0),
                    'FM999G999G990D00')
         END AS SALARIO_CONTRATO,
         CASE
           WHEN ORDEM = 0 THEN
            NULL
           ELSE
            TO_CHAR(NVL(VENCIMENTOS, 0),
                    'FM999G999G990D00')
         END AS VENCIMENTOS_FOLHA,
         CASE
           WHEN ORDEM = 0 THEN
            NULL
           ELSE
            TO_CHAR(NVL(VDS_SOLICITADOS, 0),
                    'FM999G999G990D00')
         END AS VDS_SOLICITADOS,
         AFASTAMENTO,
         SYSDATE AS DTA_SISTEMA
    FROM DADOS
   ORDER BY ORDEM, COD_TIPO, COD_UNIDADE
 
