WITH FUNCOES AS (
    SELECT COD_REGIAO,
           DES_REGIAO,
           COD_FUNCAO,
           DES_FUNCAO,
           COUNT(DISTINCT COD_CONTRATO) AS QTDE_CONTRATOS_FUNCAO
      FROM V_DADOS_COLAB_AVT
     WHERE STATUS = 0
       AND COD_TIPO = 1
       AND STATUS_AFAST IN ('EM ATIVIDADE', 'EM FÉRIAS', 'AFASTADO TEMP')
     GROUP BY COD_REGIAO, DES_REGIAO, COD_FUNCAO, DES_FUNCAO
),

QTDE_CONTRATOS_REGIAO AS (
    SELECT COD_REGIAO,
           DES_REGIAO,
           COUNT(DISTINCT COD_CONTRATO) AS QTDE_CONTRATOS_REGIAO
      FROM V_DADOS_COLAB_AVT
     WHERE STATUS = 0
       AND COD_TIPO = 1
       AND STATUS_AFAST IN ('EM ATIVIDADE', 'EM FÉRIAS', 'AFASTADO TEMP')
     GROUP BY COD_REGIAO, DES_REGIAO
),

COM_LOTACOES AS (
    SELECT A.COD_REGIAO,
           A.DES_REGIAO,
           A.COD_FUNCAO,
           A.DES_FUNCAO,
           A.COD_LOTACAO,
           A.DES_LOTACAO,       
           CASE 
               WHEN B.COD_TIPO_VAGA <> 7 THEN B.NUM_VAGAS
               WHEN A.COD_FUNCAO = 68 AND B.COD_TIPO_VAGA = 7 THEN COUNT(B.NUM_HORAS)
               ELSE 0
           END AS PREVISTO,
           COUNT(DISTINCT A.COD_CONTRATO) AS REALIZADO -- QTDE DE CONTRATOS COM LOTAÇÃO
      FROM V_DADOS_COLAB_AVT A
      LEFT JOIN RHFP0510 B 
             ON A.COD_LOTACAO = B.COD_LOTACAO
     WHERE A.STATUS = 0
       AND A.COD_TIPO = 1
       AND A.STATUS_AFAST IN ('EM ATIVIDADE', 'EM FÉRIAS', 'AFASTADO TEMP')
       AND A.COD_LOTACAO IS NOT NULL
     GROUP BY A.COD_REGIAO, 
              A.DES_REGIAO, 
              A.COD_FUNCAO, 
              A.DES_FUNCAO, 
              A.COD_LOTACAO, 
              A.DES_LOTACAO, 
              B.COD_TIPO_VAGA, 
              B.NUM_VAGAS, 
              B.NUM_HORAS
),

CONT_SEM_LOTACOES AS (
    SELECT COD_REGIAO,
           DES_REGIAO,
           LISTAGG(COD_CONTRATO || ' - ' || PRIMEIRO_NOME, '; ') 
           WITHIN GROUP (ORDER BY COD_CONTRATO) AS COLABORADOR,
           COUNT(DISTINCT COD_CONTRATO) AS QTDE_CONTRATOS_SEM_LOTACAO
    FROM V_DADOS_COLAB_AVT
    WHERE STATUS = 0
      AND COD_TIPO = 1
      AND STATUS_AFAST IN ('EM ATIVIDADE', 'EM FÉRIAS', 'AFASTADO TEMP')
      AND COD_LOTACAO IS NULL
    GROUP BY COD_REGIAO, DES_REGIAO
)

SELECT DISTINCT
       FC.COD_REGIAO,
       FC.DES_REGIAO,
       FC.DES_FUNCAO,
       LT1.COD_LOTACAO,
       LT1.DES_LOTACAO,       
       COALESCE(QCR.QTDE_CONTRATOS_REGIAO, NULL) AS QTDE_CONTRATOS_REGIAO,
       COALESCE(FC.QTDE_CONTRATOS_FUNCAO, NULL) AS QTDE_CONTRATOS_FUNCAO,
       COALESCE(LT1.PREVISTO, NULL) AS PREVISTO,
       COALESCE(LT1.REALIZADO, NULL) AS REALIZADO,
       '    ' AS ESPACO,
       COALESCE(LTC.QTDE_CONTRATOS_SEM_LOTACAO, NULL) AS QTDE_CONTRATOS_SEM_LOTACAO,
       LTC.COLABORADOR
FROM FUNCOES FC
LEFT JOIN COM_LOTACOES LT1 
       ON FC.COD_REGIAO = LT1.COD_REGIAO 
      AND FC.DES_FUNCAO = LT1.DES_FUNCAO
LEFT JOIN QTDE_CONTRATOS_REGIAO QCR 
       ON FC.COD_REGIAO = QCR.COD_REGIAO
LEFT JOIN CONT_SEM_LOTACOES LTC
       ON FC.COD_REGIAO = LTC.COD_REGIAO                                  
ORDER BY FC.COD_REGIAO, FC.DES_FUNCAO
