SELECT DISTINCT
       A.COD_CONTRATO || ' - ' || A.DES_PESSOA AS COLABORADOR,
       A.DATA_ADMISSAO,
       A.DATA_DEMISSAO,
       A.DES_UNIDADE,
       A.DES_DIVISAO,
       -- Cálculo do tempo de empresa formatado como 'X anos, Y meses e Z dias'
       TRUNC(MONTHS_BETWEEN(SYSDATE, A.DATA_ADMISSAO) / 12) || ' anos, ' ||
       MOD(TRUNC(MONTHS_BETWEEN(SYSDATE, A.DATA_ADMISSAO)), 12) ||
       ' meses e ' ||
       TRUNC(SYSDATE -
             ADD_MONTHS(A.DATA_ADMISSAO,
                        TRUNC(MONTHS_BETWEEN(SYSDATE, A.DATA_ADMISSAO)))) ||
       ' dias' AS TEMPO_EMPRESA,
       A.DES_FUNCAO,
       TO_CHAR(B.VALOR_SALARIO, 'FM999G999G999D90') AS SALARIO,
       MAX(
    CASE
      WHEN C.COD_EVENTO = 1
       AND C.COD_VD    = 935
       AND C.DATA_MOV >= TRUNC(SYSDATE)
      THEN TO_CHAR(C.VALOR_VD, 'FM999G999G999D90')
    END
  ) AS GRATIFICACAO
  FROM V_DADOS_COLAB_AVT A
 INNER JOIN RHFP0608 B ON A.COD_CONTRATO = B.COD_CONTRATO
                       AND B.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY')
  LEFT JOIN RHFP1004 C ON A.COD_CONTRATO = C.COD_CONTRATO
                       AND C.DATA_MOV >= TRUNC(SYSDATE)
 WHERE A.STATUS = 0
   --AND A.EDICAO_DIVISAO = '750'
   AND A.COD_TIPO IN (2,3)
 GROUP BY
  A.COD_CONTRATO || ' - ' || A.DES_PESSOA,
  A.DATA_ADMISSAO,
  A.DATA_DEMISSAO,
  A.DES_UNIDADE,
  A.DES_DIVISAO,
  A.DES_FUNCAO,
  B.VALOR_SALARIO
 ORDER BY A.DES_UNIDADE, A.DES_DIVISAO, COLABORADOR
