SELECT DISTINCT 
    DES_UNIDADE, 
    DES_FUNCAO
FROM V_DADOS_COLAB_AVT
WHERE COD_EMP = '008'
AND STATUS = 0
AND COD_TIPO = 2

UNION ALL

SELECT DISTINCT
    DES_UNIDADE, 
    DES_FUNCAO
FROM V_DADOS_COLAB_AVT 
WHERE COD_EMP = '008'
AND STATUS = 0
AND COD_TIPO = 3

ORDER BY DES_UNIDADE, DES_FUNCAO;
