WITH SALARIO AS (
    SELECT *
    FROM (
        SELECT
            T.COD_CONTRATO,
            CASE WHEN T.COD_MOTIVO = 27 THEN TO_CHAR(T.DATA_INICIO, 'DD/MM/YYYY') END AS DTA_INI_SAL_PROMOCAO,
            CASE WHEN T.COD_MOTIVO = 27 THEN TO_CHAR(T.DATA_FIM, 'DD/MM/YYYY') END AS DTA_FIM_SAL_PROMOCAO,
            CASE WHEN T.COD_MOTIVO = 27 THEN T.VALOR_SALARIO ELSE 0 END AS SAL_PROMOCAO,

            CASE WHEN T.COD_MOTIVO = 31 THEN TO_CHAR(T.DATA_INICIO, 'DD/MM/YYYY') END AS DTA_INI_SAL_ESPONTANEO,
            CASE WHEN T.COD_MOTIVO = 31 THEN TO_CHAR(T.DATA_FIM, 'DD/MM/YYYY') END AS DTA_FIM_SAL_ESPONTANEO,
            CASE WHEN T.COD_MOTIVO = 31 THEN T.VALOR_SALARIO ELSE 0 END AS SAL_ESPONTANEO,

            (SELECT T2.VALOR_SALARIO
             FROM RHFP0608 T2
             WHERE T2.COD_CONTRATO = T.COD_CONTRATO
               AND TRUNC(SYSDATE) BETWEEN T2.DATA_INICIO AND T2.DATA_FIM
             ORDER BY T2.DATA_INICIO DESC
             FETCH FIRST 1 ROW ONLY) AS SALARIO_ATUAL,

            (SELECT TO_CHAR(T2.DATA_INICIO, 'DD/MM/YYYY')
             FROM RHFP0608 T2
             WHERE T2.COD_CONTRATO = T.COD_CONTRATO
               AND TRUNC(SYSDATE) BETWEEN T2.DATA_INICIO AND T2.DATA_FIM
             ORDER BY T2.DATA_INICIO DESC
             FETCH FIRST 1 ROW ONLY) AS DT_INI_SAL_ATUAL,

            (SELECT TO_CHAR(T2.DATA_FIM, 'DD/MM/YYYY')
             FROM RHFP0608 T2
             WHERE T2.COD_CONTRATO = T.COD_CONTRATO
               AND TRUNC(SYSDATE) BETWEEN T2.DATA_INICIO AND T2.DATA_FIM
             ORDER BY T2.DATA_INICIO DESC
             FETCH FIRST 1 ROW ONLY) AS DT_FIM_SAL_ATUAL,

            ROW_NUMBER() OVER (PARTITION BY T.COD_CONTRATO ORDER BY T.DATA_INICIO DESC) AS RN
        FROM RHFP0608 T
        WHERE T.COD_MOTIVO IN (27, 31)
    )
    WHERE RN = 1
),

GRATIFICACAO AS (
    SELECT *
    FROM (
        SELECT
            M.COD_CONTRATO,
            CASE WHEN T.COD_MOTIVO = 27 THEN TO_CHAR(M.DATA_MOV, 'DD/MM/YYYY') END AS DTA_GRAT_PROMOCAO,
            CASE WHEN T.COD_MOTIVO = 27 THEN M.VALOR_VD ELSE 0 END AS GRAT_PROMOCAO,

            CASE WHEN T.COD_MOTIVO = 31 THEN TO_CHAR(M.DATA_MOV, 'DD/MM/YYYY') END AS DTA_GRAT_ESPONTANEO,
            CASE WHEN T.COD_MOTIVO = 31 THEN M.VALOR_VD ELSE 0 END AS GRAT_ESPONTANEO,

            ROW_NUMBER() OVER (PARTITION BY M.COD_CONTRATO ORDER BY M.DATA_MOV DESC) AS RN
        FROM RHFP1004 M
        JOIN RHFP0608 T ON M.COD_CONTRATO = T.COD_CONTRATO
                       AND M.DATA_MOV BETWEEN T.DATA_INICIO AND T.DATA_FIM
        WHERE M.COD_VD = 935
          AND T.COD_MOTIVO IN (27, 31)
    )
    WHERE RN = 1
),

CONTRATOS AS (
    SELECT DISTINCT
        COD_CONTRATO,
        DES_PESSOA,
        DES_FUNCAO,
        DATA_ADMISSAO,
        DES_UNIDADE,
        EDICAO_DIVISAO,
        DES_DIVISAO
    FROM V_DADOS_COLAB_AVT
    WHERE STATUS = 0
      AND COD_TIPO = 2
      AND COD_EMP = 8
      AND (
           DES_FUNCAO LIKE '%COMPRADOR%'
        OR DES_FUNCAO LIKE '%GERENTE%'
        OR DES_FUNCAO LIKE '%SUPERVISOR%'
        OR DES_FUNCAO LIKE '%DIRETOR%'
      )
      AND DES_FUNCAO NOT LIKE '%ASSESSOR DE DIRETORIA%'
)

SELECT
    A.COD_CONTRATO || ' - ' || A.DES_PESSOA AS COLABORADOR,
    A.DES_FUNCAO,
    A.DATA_ADMISSAO,
    A.DES_UNIDADE,
    A.EDICAO_DIVISAO,
    A.DES_DIVISAO,

    TO_CHAR(B.SAL_PROMOCAO, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS SALARIO_PROMOCAO,
    CASE
        WHEN B.DTA_INI_SAL_PROMOCAO IS NOT NULL AND B.DTA_FIM_SAL_PROMOCAO IS NOT NULL
        THEN 'De ' || B.DTA_INI_SAL_PROMOCAO || ' até ' || B.DTA_FIM_SAL_PROMOCAO
    END AS PERIODO_PROMOCAO,

    TO_CHAR(C.GRAT_PROMOCAO, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS GRAT_PROMOCAO,
    TO_CHAR(NVL(B.SAL_PROMOCAO, 0) + NVL(C.GRAT_PROMOCAO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS VLR_TOT_REMUNERACAO_PRO,

    TO_CHAR(B.SAL_ESPONTANEO, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS SALARIO_ESPONTANEO,
    CASE
        WHEN B.DTA_INI_SAL_ESPONTANEO IS NOT NULL AND B.DTA_FIM_SAL_ESPONTANEO IS NOT NULL
        THEN 'De ' || B.DTA_INI_SAL_ESPONTANEO || ' até ' || B.DTA_FIM_SAL_ESPONTANEO
    END AS PERIODO_ESPONTANEO,

    TO_CHAR(C.GRAT_ESPONTANEO, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS GRAT_ESPONTANEO,
    TO_CHAR(NVL(B.SAL_ESPONTANEO, 0) + NVL(C.GRAT_ESPONTANEO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS VLR_TOT_REMUNERACAO_ESP,

    TO_CHAR(B.SALARIO_ATUAL, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS SALARIO_ATUAL,
    CASE
        WHEN B.DT_INI_SAL_ATUAL IS NOT NULL AND B.DT_FIM_SAL_ATUAL IS NOT NULL
        THEN 'De ' || B.DT_INI_SAL_ATUAL || ' até ' || B.DT_FIM_SAL_ATUAL
    END AS PERIODO_ATUAL,

    TO_CHAR(NVL(B.SALARIO_ATUAL, 0) + NVL(C.GRAT_PROMOCAO, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS = '',.''') AS VLR_TOT_REMUNERACAO_ATUAL,

    COUNT(*) OVER (PARTITION BY A.EDICAO_DIVISAO) AS QTD_POR_EDICAO,
    COUNT(*) OVER () AS QTD_TOT_CONTRATOS

FROM CONTRATOS A
LEFT JOIN SALARIO B ON A.COD_CONTRATO = B.COD_CONTRATO
LEFT JOIN GRATIFICACAO C ON A.COD_CONTRATO = C.COD_CONTRATO
ORDER BY A.EDICAO_DIVISAO, A.DES_UNIDADE, A.COD_CONTRATO
