WITH
CONTRATOS AS (
  SELECT DISTINCT CT.STATUS,
                  CT.COD_CONTRATO,
                  CT.DES_PESSOA,
                  CT.DATA_ADMISSAO,
                  CT.DATA_DEMISSAO,
                  /*-- Tempo de empresa individual
                  TRUNC(MONTHS_BETWEEN(:DATA_FIM, CT.DATA_AVANCO) / 12) ||
                  ' ano(s)' || ' e ' ||
                  TRUNC(MOD(MONTHS_BETWEEN(:DATA_FIM, CT.DATA_AVANCO), 12)) ||
                  ' mês(es)' AS TEMPO_EMPRESA,*/
                  CT.DATA_NASCIMENTO,
                  CT.IDADE,
                  FN.COD_FUNCAO,
                  FN.DES_FUNCAO,
                  HR.HR_BASE_MES,
                  CT.IND_DEFICIENCIA,
                  CT.SEXO,
                  ORG.COD_EMP,
                  ORG.EDICAO_EMP,
                  ORG.DES_EMP,
                  ORG.COD_ORGANOGRAMA,
                  ORG.COD_UNIDADE,
                  ORG.DES_UNIDADE,
                  ORG.NOME_ORGANOGRAMA,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_3
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME3
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_4
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_DIVISAO,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME4
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_DIVISAO,
                  ORG.EDICAO,
                  ORG.COD_REDE,
                  ORG.DES_REDE,
                  ORG.COD_TIPO,
                  ORG.DES_TIPO
   FROM V_DADOS_CONTRATO_AVT CT,
         VH_EST_ORG_CONTRATO_AVT ORG,
         VH_HIST_HORAS_COLAB_AVT HR,
         VH_CARGO_CONTRATO_AVT FN
   WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
     AND CT.COD_CONTRATO = HR.COD_CONTRATO
     AND CT.COD_CONTRATO = FN.COD_CONTRATO
     AND ((:REFERENCIA BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
          (CT.DATA_ADMISSAO <= :REFERENCIA AND CT.DATA_DEMISSAO IS NULL))
     AND :REFERENCIA BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
     AND :REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
     AND :REFERENCIA BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
     AND ORG.COD_EMP = 8
    /* AND (ORG.COD_TIPO = :TIPO OR :TIPO = 0)
     AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
     AND (ORG.COD_REDE = :REDE OR :REDE = 0)*/
     AND ORG.EDICAO_ORG_4 IS NOT NULL
   ORDER BY ORG.COD_TIPO, ORG.COD_REDE, ORG.COD_UNIDADE, CT.COD_CONTRATO
),


STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST,
       NA.NOME_CAUSA_AFAST AS DES_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN,
       RHFP0100 NA
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND AF.COD_CAUSA_AFAST = NA.COD_CAUSA_AFAST(+)
   AND ((:REFERENCIA BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= :REFERENCIA AND CT.DATA_FIM IS NULL))
   AND :REFERENCIA BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :REFERENCIA BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND :REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   /*AND (ORG.COD_TIPO = :TIPO OR :TIPO = 0)
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)*/
   --AND (ORG.COD_EMP = :EMPRESA OR :EMPRESA = 0)
   AND ORG.COD_EMP = 8
),



DEPENDENTES AS (
SELECT RHFP0300.COD_CONTRATO,
       RHFP0202.COD_FUNC,
       RHFP0202.COD_PESSOA AS COD_DEPEN,
       PESSOA.NOME_PESSOA AS DES_DEPEN,
       REGEXP_REPLACE(
                      LPAD(FISICA.CPF, 11, '0'), 
                           '(\d{3})(\d{3})(\d{3})(\d{2})', 
                           '\1.\2.\3-\4'
       ) AS CPF_DEPEN,
       --FISICA.CPF AS CPF_DEPEN,
       RHFP0202.DATA_INICIO,
       RHFP0202.DATA_FIM,
       RHFP0202.COD_GRAU_PARENTESCO AS COD_PARENT,
       RHFP0106.NOME_GRAU_PARENTESCO AS GRAU_PARENT,
       RHFP0202.COD_NACIONALIDADE,
       RHFP0107.NOME_NACIONALIDADE,
       RHFP0105.NOME_RESUMIDO,
       RHFP0202.SEXO AS SEXO_PARENT,
       RHFP0202.COD_ESTADO_CIVIL,
       RHFP0104.NOME_ESTADO_CIVIL,
       RHFP0202.TIPO_DEPENDENTE,
       RHFP0109.NOME_TIPO_DEPENDENTE,
       RHFP0202.IRF,
       RHFP0202.SAL_FAMILIA,
       RHFP0202.DATA_NASCIMENTO AS DT_NASC_DEPEN,
       TRUNC(MONTHS_BETWEEN(:REFERENCIA, RHFP0202.DATA_NASCIMENTO) / 12) AS IDADE_DEPEN
  FROM FISICA   FISICA,
       PESSOA   PESSOA,
       RHFP0300 RHFP0300,
       RHFP0202 RHFP0202,
       RHFP0106 RHFP0106,
       RHFP0107 RHFP0107,
       RHFP0105 RHFP0105,
       RHFP0104 RHFP0104,
       RHFP0109 RHFP0109,
       MUNICI   MUNICI,
       UF       UF
 WHERE RHFP0202.COD_FUNC = RHFP0300.COD_FUNC
   AND RHFP0202.COD_PESSOA = PESSOA.COD_PESSOA
   AND RHFP0202.COD_GRAU_PARENTESCO = RHFP0106.COD_GRAU_PARENTESCO(+)
   AND RHFP0202.COD_NACIONALIDADE = RHFP0107.COD_NACIONALIDADE(+)
   AND RHFP0202.COD_GRAU_INSTRUCAO = RHFP0105.COD_GRAU_INSTRUCAO(+)
   AND RHFP0202.COD_ESTADO_CIVIL = RHFP0104.COD_ESTADO_CIVIL(+)
   AND RHFP0202.TIPO_DEPENDENTE = RHFP0109.COD_TIPO_DEPENDENTE(+)
   AND RHFP0202.COD_UF_NASCIMENTO = UF.COD_UF(+)
   AND RHFP0202.COD_UF_NASCIMENTO = MUNICI.COD_UF(+)
   AND RHFP0202.COD_MUNIC_NASCIMENTO = MUNICI.COD_MUNIC(+)
   AND PESSOA.COD_PESSOA = FISICA.COD_PESSOA(+)
   AND :REFERENCIA BETWEEN RHFP0202.DATA_INICIO AND RHFP0202.DATA_FIM
   AND RHFP0202.COD_GRAU_PARENTESCO = 1

),

DEP_COM_RN AS (
  SELECT
    D.*,
    ROW_NUMBER() OVER (
      PARTITION BY D.COD_CONTRATO
      ORDER BY D.DT_NASC_DEPEN, D.DES_DEPEN
    ) AS RN
  FROM DEPENDENTES D
  WHERE D.IRF = 'S'
)

SELECT
  CT.COD_CONTRATO,
  CT.DES_PESSOA,
  CT.DES_FUNCAO,
  CT.COD_UNIDADE,
  CT.DES_UNIDADE,

  /* DEPENDENTE 1 */
  MAX(CASE WHEN DRN.RN = 1 THEN DRN.DES_DEPEN     END) AS DES_DEPEN_1,
  MAX(CASE WHEN DRN.RN = 1 THEN DRN.CPF_DEPEN     END) AS CPF_DEPEN_1,
  MAX(CASE WHEN drn.rn = 1 THEN TO_CHAR(drn.DT_NASC_DEPEN,'DD/MM/YYYY') END) AS DT_NASC_DEPEN_1,
  MAX(CASE WHEN DRN.RN = 1 THEN DRN.GRAU_PARENT   END) AS GRAU_PARENT_1,

  /* DEPENDENTE 2 */
  MAX(CASE WHEN DRN.RN = 2 THEN DRN.DES_DEPEN     END) AS DES_DEPEN_2,
  MAX(CASE WHEN DRN.RN = 2 THEN DRN.CPF_DEPEN     END) AS CPF_DEPEN_2,
  MAX(CASE WHEN drn.rn = 2 THEN TO_CHAR(drn.DT_NASC_DEPEN,'DD/MM/YYYY') END) AS DT_NASC_DEPEN_2,
  MAX(CASE WHEN DRN.RN = 2 THEN DRN.GRAU_PARENT   END) AS GRAU_PARENT_2,

  /* DEPENDENTE 3 */
  MAX(CASE WHEN DRN.RN = 3 THEN DRN.DES_DEPEN     END) AS DES_DEPEN_3,
  MAX(CASE WHEN DRN.RN = 3 THEN DRN.CPF_DEPEN     END) AS CPF_DEPEN_3,
  MAX(CASE WHEN drn.rn = 3 THEN TO_CHAR(drn.DT_NASC_DEPEN,'DD/MM/YYYY') END) AS DT_NASC_DEPEN_3,
  MAX(CASE WHEN DRN.RN = 3 THEN DRN.GRAU_PARENT   END) AS GRAU_PARENT_3,

  /* DEPENDENTE 4 */
  MAX(CASE WHEN DRN.RN = 4 THEN DRN.DES_DEPEN     END) AS DES_DEPEN_4,
  MAX(CASE WHEN DRN.RN = 4 THEN DRN.CPF_DEPEN     END) AS CPF_DEPEN_4,
  MAX(CASE WHEN drn.rn = 4 THEN TO_CHAR(drn.DT_NASC_DEPEN,'DD/MM/YYYY') END) AS DT_NASC_DEPEN_4,
  MAX(CASE WHEN DRN.RN = 4 THEN DRN.GRAU_PARENT   END) AS GRAU_PARENT_4,

  /* DEPENDENTE 5 */
  MAX(CASE WHEN DRN.RN = 5 THEN DRN.DES_DEPEN     END) AS DES_DEPEN_5,
  MAX(CASE WHEN DRN.RN = 5 THEN DRN.CPF_DEPEN     END) AS CPF_DEPEN_5,
  MAX(CASE WHEN drn.rn = 5 THEN TO_CHAR(drn.DT_NASC_DEPEN,'DD/MM/YYYY') END) AS DT_NASC_DEPEN_5,
  MAX(CASE WHEN DRN.RN = 5 THEN DRN.GRAU_PARENT   END) AS GRAU_PARENT_5,

  /* DEPENDENTE 6 */
  MAX(CASE WHEN DRN.RN = 6 THEN DRN.DES_DEPEN     END) AS DES_DEPEN_6,
  MAX(CASE WHEN DRN.RN = 6 THEN DRN.CPF_DEPEN     END) AS CPF_DEPEN_6,
  MAX(CASE WHEN drn.rn = 6 THEN TO_CHAR(drn.DT_NASC_DEPEN,'DD/MM/YYYY') END) AS DT_NASC_DEPEN_6,
  MAX(CASE WHEN DRN.RN = 6 THEN DRN.GRAU_PARENT   END) AS GRAU_PARENT_6,

  /* DEPENDENTE 7 */
  MAX(CASE WHEN DRN.RN = 7 THEN DRN.DES_DEPEN     END) AS DES_DEPEN_7,
  MAX(CASE WHEN DRN.RN = 7 THEN DRN.CPF_DEPEN     END) AS CPF_DEPEN_7,
  MAX(CASE WHEN drn.rn = 7 THEN TO_CHAR(drn.DT_NASC_DEPEN,'DD/MM/YYYY') END) AS DT_NASC_DEPEN_7,
  MAX(CASE WHEN DRN.RN = 7 THEN DRN.GRAU_PARENT   END) AS GRAU_PARENT_7,

  /* DEPENDENTE 8 */
  MAX(CASE WHEN DRN.RN = 8 THEN DRN.DES_DEPEN     END) AS DES_DEPEN_8,
  MAX(CASE WHEN DRN.RN = 8 THEN DRN.CPF_DEPEN     END) AS CPF_DEPEN_8,
  MAX(CASE WHEN drn.rn = 8 THEN TO_CHAR(drn.DT_NASC_DEPEN,'DD/MM/YYYY') END) AS DT_NASC_DEPEN_8,
  MAX(CASE WHEN DRN.RN = 8 THEN DRN.GRAU_PARENT   END) AS GRAU_PARENT_8,       
  
  (
  TO_CHAR(:EMISSAO_DOC,'DD') || ' de ' ||
  LOWER(TO_CHAR(:EMISSAO_DOC,'fmMonth','NLS_DATE_LANGUAGE=PORTUGUESE')) ||
  ' de ' ||
  TO_CHAR(:EMISSAO_DOC,'YYYY')
  ) AS EMISSAO

FROM CONTRATOS CT
LEFT JOIN DEP_COM_RN DRN
  ON DRN.COD_CONTRATO = CT.COD_CONTRATO 
WHERE (CT.COD_CONTRATO = :CONTRATO OR :CONTRATO = 0)
AND (CT.COD_TIPO = :TIPO OR :TIPO = 0)
AND (CT.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
AND (CT.COD_REDE = :REDE OR :REDE = 0)
GROUP BY
  CT.COD_CONTRATO, CT.DES_PESSOA, CT.DES_FUNCAO,
  CT.COD_UNIDADE, CT.DES_UNIDADE, :EMISSAO_DOC
ORDER BY CT.COD_CONTRATO



