SELECT COD_CONTRATO || ' - ' || DES_PESSOA AS COLABORADOR,
       DES_FUNCAO,
       DES_UNIDADE,
       DES_REDE_LOCAL,
       DATA_INI_AFAST,
       DATA_FIM_AFAST,
       'De ' || DATA_FERIAS || ' até ' || DATA_RETORNO AS PERIODO_FERIAS
FROM V_DADOS_COLAB_AVT
WHERE STATUS = 0
AND (COD_TIPO = :TIPO OR :TIPO = 0)
AND (COD_UNIDADE = :FILIAL OR :FILIAL = 0)
AND (COD_REDE_LOCAL = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
AND (DATA_PREVISTA_FERIAS BETWEEN :DATA_INICIO AND :DATA_FIM)
AND (DES_FUNCAO LIKE '%COMPRADOR%'
OR DES_FUNCAO LIKE '%GERENTE%'
OR DES_FUNCAO LIKE '%SUPERVISOR%'
OR DES_FUNCAO LIKE '%DIRETOR%')
AND DES_FUNCAO NOT LIKE '%ACESSOR DE DIRETORIA%'
