SELECT
    COD_CONTRATO || ' - ' || DES_PESSOA AS COLABORADOR,
    DES_FUNCAO,
    DATA_ADMISSAO,
    DES_UNIDADE,
    COUNT(COD_CONTRATO) OVER (PARTITION BY DES_UNIDADE) AS
QTDE_CONTRATOS
FROM
    V_DADOS_COLAB_AVT
WHERE
    --COD_TIPO IN (2, 3)
    STATUS = 0
    AND COD_EMP = :EMPRESA
    AND (COD_TIPO = :TIPO OR :TIPO = 0)
    AND COD_UNIDADE NOT IN (705, 707)
    AND COD_FUNCAO NOT IN (74, 75, 310, 409)
    AND DATA_ADMISSAO <= '31/10/2024'
    AND STATUS_AFAST IN ('EM ATIVIDADE', 'EM FÉRIAS', 'AFASTADO TEMP')
ORDER BY
    DES_UNIDADE
