WITH
UNIDADE AS (
    SELECT COD_ORGANOGRAMA,
           EDICAO_ORG AS COD_UNIDADE,
           NOME_ORGANOGRAMA_B AS DES_UNIDADE,
           COD_REDE,
           DES_REDE,
           COD_TIPO,
           DES_TIPO
    FROM V_EST_ORG_AVT
),


OPERADOR_DADOS AS (
    SELECT COD_OPERADOR, COD_PESSOA, COD_CONTRATO, DES_PESSOA
    FROM (
        SELECT OP.COD_OPERADOR,
               OP.COD_PESSOA,
               CT.COD_CONTRATO,
               PF.NOME_PESSOA AS DES_PESSOA,
               ROW_NUMBER() OVER (PARTITION BY OP.COD_OPERADOR ORDER BY CT.DATA_INICIO DESC) AS RN
        FROM OPERADOR OP
        LEFT JOIN RHFP0300 CT ON OP.COD_PESSOA = CT.COD_FUNC
        LEFT JOIN PESSOA_FISICA PF ON OP.COD_PESSOA = PF.COD_PESSOA
        WHERE CT.DATA_FIM IS NULL
    )
    WHERE RN = 1
),


ULTIMA_SITUACAO AS (
    SELECT COD_REQUISICAO,
           COD_SITUACAO_REQ,
           DATA_INICIO,
           ROW_NUMBER() OVER (PARTITION BY COD_REQUISICAO ORDER BY DATA_INICIO DESC) AS RN
    FROM RHRS0315
),

REQUISICAO AS (
    SELECT A.COD_ORGANOGRAMA,
           A.COD_LOTACAO,
           G.NOME_LOTACAO AS DES_LOTACAO,
           A.COD_OPERADOR,
           A.COD_REQUISICAO AS COD_REQ,
           A.NOME_REQUISICAO AS DES_REQ,
           A.DATA_EMISSAO AS EMISSAO,
           A.QTDE_SOLICITADA,
           A.QTDE_ATENDIDA,
           A.COD_CLH AS COD_FUNCAO,
           D.NOME_CLH AS DES_FUNCAO,
           A.COD_TIPO_VAGA AS TIPO_VAGA,
           E.NOME_TIPO_VAGA AS DES_VAGA,
           F.NOME_MOTIVO AS DES_MOTIVO,
           A.MOTIVO_TEXTUAL AS OBSERVACAO,
           A.ANOS_EXPERIENCIA,
           A.MESES_EXPERIENCIA,
           A.COM_EXPERIENCIA AS "EXPERIENCIA?",
           A.COM_REQUISITOS_CLH AS "FUNCAO?",
           A.COM_REQUISITOS_RP AS "RP?",
           CASE
               WHEN A.COD_CONTRATO_SUBST IS NOT NULL THEN 'S'
               ELSE 'N'
           END AS "SUBSTITUICAO?",
           A.COD_CONTRATO_SUBST,
           A.DATA_SUBSTITUICAO,
           A.DATA_ADMISSAO,
           A.HORARIO,
           B.COD_SITUACAO_REQ AS SITUACAO,
           CASE
               WHEN C.NOME_SITUACAO_REQ IS NULL THEN
                'NÃO INFORMADO'
               ELSE
                C.NOME_SITUACAO_REQ
           END AS DES_SITUACAO
    FROM RHRS0200 A
    LEFT JOIN ULTIMA_SITUACAO B ON A.COD_REQUISICAO = B.COD_REQUISICAO AND B.RN = 1
    LEFT JOIN RHRS0314 C ON B.COD_SITUACAO_REQ = C.COD_SITUACAO_REQ
    LEFT JOIN RHFP0500 D ON A.COD_CLH = D.COD_CLH
    LEFT JOIN RHRS0313 E ON A.COD_TIPO_VAGA = E.COD_TIPO_VAGA
    LEFT JOIN RHFP0323 F ON A.COD_MOTIVO = F.COD_MOTIVO
    LEFT JOIN RHFP0509 G ON A.COD_LOTACAO = G.COD_LOTACAO
    WHERE A.DATA_EMISSAO BETWEEN :DATA_INICIO_REQ AND :DATA_FIM_REQ
     /*BETWEEN TO_DATE('01/01/2025', 'DD/MM/YYYY') AND TO_DATE('31/08/2025', 'DD/MM/YYYY')*/
)


SELECT DISTINCT
    REQ.COD_ORGANOGRAMA,
    UNI.COD_UNIDADE,
    UNI.DES_UNIDADE,
    UNI.DES_REDE,
    REQ.COD_LOTACAO,
    REQ.DES_LOTACAO,
    REQ.COD_OPERADOR,
    OPE.DES_PESSOA,
    REQ.COD_REQ,
    REQ.DES_REQ,
    REQ.EMISSAO AS DATA_REQUISICAO,
    REQ.QTDE_SOLICITADA,
    REQ.QTDE_ATENDIDA,
    REQ.COD_FUNCAO,
    REQ.DES_FUNCAO,
    REQ.TIPO_VAGA,
    REQ.DES_VAGA,
    UPPER(REQ.DES_MOTIVO) AS DES_MOTIVO,
    REQ.OBSERVACAO,
    REQ.ANOS_EXPERIENCIA,
    REQ.MESES_EXPERIENCIA,
    REQ."EXPERIENCIA?",
    REQ."FUNCAO?",
    REQ."RP?",
    REQ."SUBSTITUICAO?",
    REQ.COD_CONTRATO_SUBST,
    REQ.DATA_SUBSTITUICAO,
    REQ.DATA_ADMISSAO,
    REQ.HORARIO,
    REQ.SITUACAO,
    UPPER(REQ.DES_SITUACAO) AS DES_SITUACAO,
    
    'De ' || :DATA_INICIO_REQ || ' até ' || :DATA_FIM_REQ AS PERIODO,

    'TIPO: ' || :TIPO || ' | ' || 'UNIDADE: ' || :UNIDADE ||
    ' | ' || 'REDE: ' || :REDE AS PARAMETROS

    
FROM REQUISICAO REQ
LEFT JOIN UNIDADE UNI ON REQ.COD_ORGANOGRAMA = UNI.COD_ORGANOGRAMA
LEFT JOIN OPERADOR_DADOS OPE ON REQ.COD_OPERADOR = OPE.COD_OPERADOR
WHERE (UNI.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
AND (UNI.COD_REDE = :REDE OR :REDE = 0)
AND (UNI.COD_TIPO = :TIPO OR :TIPO = 0)
AND (REQ.SITUACAO = :SITUACAO OR :SITUACAO = 0)
ORDER BY UNI.COD_UNIDADE
