WITH DistinctPedidos AS (
    SELECT 
        DISTINCT A.MATRICULA,
        A.CESTA_NATAL,
        CASE 
            WHEN B.DES_UNIDADE LIKE '%CENTRAL FINANCEIRA%' THEN '001 - FINANCEIRA'
            ELSE B.DES_UNIDADE
        END AS DES_UNIDADE_NORMALIZADA,
        B.COD_REDE_LOCAL,
        B.DES_REDE_LOCAL
    FROM 
        TEMP_PEDIDOS_SWILE A
    LEFT JOIN 
        V_DADOS_COLAB_AVT B ON A.MATRICULA = B.COD_CONTRATO
)
SELECT 
    DES_UNIDADE_NORMALIZADA,
    COUNT(MATRICULA) AS QTDE_CONTRATOS,
    COD_REDE_LOCAL,
    DES_REDE_LOCAL,
    TO_CHAR(SUM(CESTA_NATAL), 'FM999G999G990D00') AS VLR_CESTA,
    TO_CHAR(
        CASE 
            WHEN DES_REDE_LOCAL IS NULL OR DES_REDE_LOCAL = '' THEN SUM(CESTA_NATAL)
            ELSE SUM(SUM(CESTA_NATAL)) OVER (PARTITION BY DES_REDE_LOCAL)
        END,
        'FM999G999G990D00'
    ) AS TOTAL_REDE_CESTA
FROM 
    DistinctPedidos
GROUP BY 
    DES_UNIDADE_NORMALIZADA,
    COD_REDE_LOCAL,
    DES_REDE_LOCAL
ORDER BY 
    COD_REDE_LOCAL, 
    DES_UNIDADE_NORMALIZADA
