WITH
PARAMS AS (
    SELECT TO_DATE(:REFERENCIA, 'DD/MM/YYYY') AS REFERENCIA
    FROM DUAL
),

CONTRATOS AS (
    SELECT DISTINCT
           CT.STATUS,
           CT.COD_CONTRATO,
           CT.DES_PESSOA,
           CT.DATA_NASCIMENTO,
           CT.DATA_ADMISSAO,
           CT.DATA_DEMISSAO,
           CT.COD_VINCULO_EMPREG,
           FN.COD_FUNCAO,
           FN.DES_FUNCAO,
           FN.DATA_INI_CLH,
           FN.DATA_FIM_CLH,
           HR.HR_BASE_MES,
           HR.DATA_INI_HR,
           HR.DATA_FIM_HR,
           CT.IND_DEFICIENCIA,
           CT.SEXO,
           ORG.COD_EMP,
           ORG.EDICAO_EMP,
           ORG.DES_EMP,
           ORG.COD_ORGANOGRAMA,
           ORG.COD_UNIDADE,
           ORG.DES_UNIDADE,
           ORG.DATA_INI_ORG,
           ORG.DATA_FIM_ORG,
           CASE
             WHEN ORG.COD_TIPO = 2 THEN ORG.EDICAO_ORG_3
             WHEN ORG.COD_TIPO = 3 THEN ORG.EDICAO_ORG_3
             ELSE ORG.COD_UNIDADE
           END AS COD_FILIAL,
           CASE
             WHEN ORG.COD_TIPO = 2 THEN ORG.NOME3
             WHEN ORG.COD_TIPO = 3 THEN ORG.NOME3
             ELSE ORG.DES_UNIDADE
           END AS DES_FILIAL,
           CASE
             WHEN ORG.COD_TIPO = 2 THEN ORG.EDICAO_ORG_4
             WHEN ORG.COD_TIPO = 3 THEN ORG.EDICAO_ORG_4
             ELSE ORG.COD_UNIDADE
           END AS COD_DIVISAO,
           CASE
             WHEN ORG.COD_TIPO = 2 THEN ORG.NOME4
             WHEN ORG.COD_TIPO = 3 THEN ORG.NOME4
             ELSE ORG.DES_UNIDADE
           END AS DES_DIVISAO,
           ORG.COD_REDE,
           ORG.DES_REDE,
           ORG.COD_TIPO,
           ORG.DES_TIPO
      FROM V_DADOS_CONTRATO_AVT    CT,
           VH_EST_ORG_CONTRATO_AVT ORG,
           VH_HIST_HORAS_COLAB_AVT HR,
           VH_CARGO_CONTRATO_AVT   FN,
           PARAMS                  P
     WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
       AND CT.COD_CONTRATO = HR.COD_CONTRATO
       AND CT.COD_CONTRATO = FN.COD_CONTRATO
       AND (
             (P.REFERENCIA BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO)
             OR (CT.DATA_ADMISSAO <= P.REFERENCIA AND CT.DATA_DEMISSAO IS NULL)
           )
       AND P.REFERENCIA BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
       AND P.REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
       AND P.REFERENCIA BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
       AND ORG.COD_EMP = 8
       AND ORG.EDICAO_ORG_4 IS NOT NULL
),

STATUS_AFASTADOS AS (
    SELECT DISTINCT
           ORG.COD_EMP,
           CT.COD_CONTRATO,
           FN.DES_FUNCAO,
           ORG.COD_ORGANOGRAMA,
           ORG.COD_UNIDADE,
           AF.COD_CAUSA_AFAST AS COD_AFAST,
           AFN.NOME_CAUSA_AFAST AS DES_AFAST,
           NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFAST,
           CASE
             WHEN CT.DATA_FIM IS NOT NULL
              AND CT.DATA_FIM < SYSDATE THEN
                'INATIVO'
             WHEN AF.COD_CAUSA_AFAST <> 0
              AND AF.COD_CAUSA_AFAST <> 4
              AND AF.COD_CAUSA_AFAST <> 21
              AND AF.COD_CAUSA_AFAST <> 60
              AND AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
                'AFASTADO'
             WHEN AF.COD_CAUSA_AFAST IN (21, 60) THEN
                'ATIVO, SEM RETORNO'
             WHEN AF.COD_CAUSA_AFAST = 7 THEN
                'EM FÉRIAS'
             WHEN AF.COD_CAUSA_AFAST IN (3, 6) THEN
                'AFASTADO TEMP'
             WHEN AF.COD_CAUSA_AFAST = 4
              AND AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
                'PODERÁ RETORNAR'
             ELSE
                'EM ATIVIDADE'
           END AS DES_STATUS_AFAST,
           AF.DATA_INICIO AS DATA_INI_AFAST,
           AF.DATA_FIM AS DATA_FIM_AFAST
      FROM RHFP0306                AF,
           RHFP0300                CT,
           VH_EST_ORG_CONTRATO_AVT ORG,
           VH_CARGO_CONTRATO_AVT   FN,
           RHFP0100                AFN,
           PARAMS                  P
     WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
       AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
       AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
       AND AF.COD_CAUSA_AFAST = AFN.COD_CAUSA_AFAST(+)
       AND (
             (P.REFERENCIA BETWEEN CT.DATA_INICIO AND CT.DATA_FIM)
             OR (CT.DATA_INICIO <= P.REFERENCIA AND CT.DATA_FIM IS NULL)
           )
       AND P.REFERENCIA BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
       AND P.REFERENCIA BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
       AND P.REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
       AND ORG.COD_EMP = 8
),

QUANTIDADES AS (
    SELECT
        CT.COD_ORGANOGRAMA,

        COUNT(DISTINCT CT.COD_CONTRATO) AS QTD_COLABORADORES,

        COUNT(DISTINCT CASE
            WHEN UPPER(CT.DES_FUNCAO) LIKE '%TEMPORARIO%'
            THEN CT.COD_CONTRATO
        END) AS QTD_TEMPORARIOS,

        COUNT(DISTINCT CASE
            WHEN UPPER(CT.DES_FUNCAO) LIKE '%APRENDIZ%'
            THEN CT.COD_CONTRATO
        END) AS QTD_APRENDIZ,

        COUNT(DISTINCT CASE
            WHEN UPPER(CT.DES_FUNCAO) LIKE '%ESTAGIARIO%'
            THEN CT.COD_CONTRATO
        END) AS QTD_ESTAGIARIO,

        COUNT(DISTINCT CASE
            WHEN AF.DES_STATUS_AFAST IN (
                'AFASTADO',
                'AFASTADO TEMP',
                'EM FÉRIAS',
                'ATIVO, SEM RETORNO',
                'PODERÁ RETORNAR'
            )
            THEN CT.COD_CONTRATO
        END) AS QTD_AFASTADOS

    FROM CONTRATOS CT
    LEFT JOIN STATUS_AFASTADOS AF
           ON CT.COD_CONTRATO = AF.COD_CONTRATO
          AND CT.COD_ORGANOGRAMA = AF.COD_ORGANOGRAMA
    GROUP BY CT.COD_ORGANOGRAMA
),

QUANTIDADES_EMPRESA AS (
    SELECT
        CT.COD_EMP,

        COUNT(DISTINCT CT.COD_CONTRATO) AS TOT_EMP_QTD_COLABORADORES,

        COUNT(DISTINCT CASE
            WHEN UPPER(CT.DES_FUNCAO) LIKE '%TEMPORARIO%'
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_TEMPORARIOS,

        COUNT(DISTINCT CASE
            WHEN UPPER(CT.DES_FUNCAO) LIKE '%APRENDIZ%'
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_APRENDIZ,

        COUNT(DISTINCT CASE
            WHEN UPPER(CT.DES_FUNCAO) LIKE '%ESTAGIARIO%'
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_ESTAGIARIO,

        COUNT(DISTINCT CASE
            WHEN AF.DES_STATUS_AFAST IN (
                'AFASTADO',
                'AFASTADO TEMP',
                'EM FÉRIAS',
                'ATIVO, SEM RETORNO',
                'PODERÁ RETORNAR'
            )
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_AFASTADOS,

        COUNT(DISTINCT CASE
            WHEN AF.DES_STATUS_AFAST = 'EM ATIVIDADE'
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_EM_ATIVIDADE,

        COUNT(DISTINCT CASE
            WHEN AF.DES_STATUS_AFAST = 'EM FÉRIAS'
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_FERIAS,

        COUNT(DISTINCT CASE
            WHEN AF.DES_STATUS_AFAST = 'AFASTADO TEMP'
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_AFASTADO_TEMP,

        COUNT(DISTINCT CASE
            WHEN AF.DES_STATUS_AFAST = 'ATIVO, SEM RETORNO'
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_ATIVO_SEM_RETORNO,

        COUNT(DISTINCT CASE
            WHEN AF.DES_STATUS_AFAST = 'PODERÁ RETORNAR'
            THEN CT.COD_CONTRATO
        END) AS TOT_EMP_QTD_PODERA_RETORNAR

    FROM CONTRATOS CT
    LEFT JOIN STATUS_AFASTADOS AF
           ON AF.COD_CONTRATO = CT.COD_CONTRATO
    GROUP BY CT.COD_EMP
)

SELECT
    AF.DES_STATUS_AFAST,
    CT.*,
    AF.DES_AFAST,
    QTD.QTD_COLABORADORES,
    QTD.QTD_TEMPORARIOS,
    QTD.QTD_APRENDIZ,
    QTD.QTD_ESTAGIARIO,
    QTD.QTD_AFASTADOS,
    QE.TOT_EMP_QTD_COLABORADORES,
    QE.TOT_EMP_QTD_TEMPORARIOS,
    QE.TOT_EMP_QTD_APRENDIZ,
    QE.TOT_EMP_QTD_ESTAGIARIO,
    QE.TOT_EMP_QTD_AFASTADOS
FROM CONTRATOS CT
LEFT JOIN STATUS_AFASTADOS AF
       ON CT.COD_CONTRATO = AF.COD_CONTRATO
      AND CT.COD_ORGANOGRAMA = AF.COD_ORGANOGRAMA
LEFT JOIN QUANTIDADES QTD
       ON CT.COD_ORGANOGRAMA = QTD.COD_ORGANOGRAMA
LEFT JOIN QUANTIDADES_EMPRESA QE
       ON QE.COD_EMP = CT.COD_EMP
WHERE (CT.COD_TIPO = :TIPO OR :TIPO = 0)
  AND (CT.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
  AND (CT.COD_REDE = :REDE OR :REDE = 0)
ORDER BY CT.COD_UNIDADE, CT.COD_CONTRATO