SELECT A.COD_CONTRATO || ' - ' || A.DES_PESSOA AS COLAB,
       B.HORARIO_1_ENT,
       B.HORARIO_1_SAI,
       B.HORARIO_2_ENT,
       B.HORARIO_2_SAI,
       B.HORARIO_3_ENT,
       B.HORARIO_3_SAI,
       B.HORARIO_4_ENT,
       B.HORARIO_4_SAI,
       A.EDICAO_DIVISAO || ' - ' || A.DES_DIVISAO AS DIVISAO,
       A.DES_UNIDADE
FROM V_DADOS_COLAB_AVT A
INNER JOIN RHAF1145 B ON A.COD_TURNO = B.COD_TURNO
WHERE A.STATUS = 0
AND A.COD_TIPO IN (2, 3)
--AND A.COD_CONTRATO = 389622
ORDER BY A.EDICAO_DIVISAO
