/*=== v2.OFICIAL - RELATÓRIO ANÁLISE QUANTITATIVA ORGANIZACIONAL - EQUIDADE (Y x Y-1) ===*/ 

WITH
PARAMS_BASE AS (
/*modo padrão com data direta*/
/*SELECT    
    DATE '2025-12-31'                 AS DT_REF_ATUAL, 
    ADD_MONTHS(DATE '2025-12-31',-12) AS DT_REF_ANT,
    '8, 282, 1629' AS COD_EMP,
    '8, 282, 1629' AS COD_ORGANOGRAMA
  FROM DUAL*/

/*modo PL/SQL com entrada de data*/
/*SELECT
  TO_DATE('&REFERENCIA','DD/MM/YYYY')                  AS DT_REF_ATUAL,
  ADD_MONTHS(TO_DATE('&REFERENCIA','DD/MM/YYYY'),-12)  AS DT_REF_ANT,
  '8, 282, 1629' AS COD_EMP,
  '8, 282, 1629' AS COD_ORGANOGRAMA
FROM DUAL*/

/*modo pra usar em outros SGBS ou pelo sistema da folha*/
SELECT :REFERENCIA AS DT_REF_ATUAL,
       ADD_MONTHS(:REFERENCIA, -12) AS DT_REF_ANT,
       '8, 282, 1629' AS COD_EMP,
       '8, 282, 1629' AS COD_ORGANOGRAMA
  FROM DUAL


),

EMP_LIST AS (
  SELECT 8 AS COD_EMP,
         8 AS COD_ORGANOGRAMA 
  FROM DUAL
  UNION ALL 
  SELECT 282 AS COD_EMP,
         282 AS COD_ORGANOGRAMA
  FROM DUAL
  UNION ALL 
  SELECT 1629 AS COD_EMP,
         1629 AS COD_ORGANOGRAMA
  FROM DUAL
),

ANOS AS (
  SELECT
    EXTRACT(YEAR FROM DT_REF_ANT)   AS ANO_Y1,
    EXTRACT(YEAR FROM DT_REF_ATUAL) AS ANO_Y
  FROM PARAMS_BASE
),

PARAMS AS (
  SELECT 'Y-1' AS PERIODO,
         EXTRACT(YEAR FROM b.DT_REF_ANT) AS ANO,
         b.DT_REF_ANT AS DT_REF
    FROM PARAMS_BASE b
  UNION ALL
  SELECT 'Y' AS PERIODO,
         EXTRACT(YEAR FROM b.DT_REF_ATUAL) AS ANO,
         b.DT_REF_ATUAL AS DT_REF
    FROM PARAMS_BASE b
),

PARAMS_PLR AS (
  SELECT
    PERIODO,
    ANO,
    LAST_DAY(TO_DATE('01/04/' || ANO, 'DD/MM/YYYY')) AS DT_REF_PLR
  FROM PARAMS
),

/* ==== Chaves classificatórias ==== */
NIVEIS AS (
  SELECT 1 ORDEM,  'CONSELHO_ADM'   NIVEL_KEY, 'CONSELHO ADMINISTRATIVO'  NIVEL_DESC FROM DUAL UNION ALL
  SELECT 2,        'CONSELHO_FISC'  ,          'CONSELHO FISCAL'                    FROM DUAL UNION ALL
  SELECT 3,        'DIR_ESTAT_VAR'  ,          'DIRETORIA ESTATUTÁRIA VAREJO'       FROM DUAL UNION ALL
  SELECT 4,        'DIR_ESTAT_FIN'  ,          'DIRETORIA ESTATUTÁRIA FINANCEIRA'   FROM DUAL UNION ALL
  SELECT 5,        'DIRETORIA_ADJ'  ,          'DIRETORIA ADJUNTA'                  FROM DUAL UNION ALL
  SELECT 6,        'GER_SUP'        ,          'GERÊNCIA/SUPERVISÃO'                FROM DUAL UNION ALL
  SELECT 7,        'COLAB'          ,          'COLABORADORES'                      FROM DUAL UNION ALL
/*SELECT 7,        'ESPECIAL'       ,          'ESPECIALISTAS'                      FROM DUAL UNION ALL
  SELECT 8,        'ADMIN'          ,          'ADMINISTRATIVO'                     FROM DUAL UNION ALL
  SELECT 9,        'OPER'           ,          'OPERACIONAL'                        FROM DUAL UNION ALL*/
  SELECT 8,         'APRENDIZ'       ,          'APRENDIZ'                           FROM DUAL UNION ALL
  SELECT 9,         'ESTAGIARIO'     ,          'ESTAGIÁRIO'                         FROM DUAL
),


/* =============================================
   ======= QUADRO I -  MAPEAMENTO GERAL ========
   ============================================= */

/* ========= Base contratos (para os 2 anos) ========= */
/*backup*/
/*CONTRATOS AS (
  SELECT DISTINCT
         p.PERIODO,
         p.ANO,
         ct.COD_CONTRATO,
         ct.SEXO,
         fn.DES_FUNCAO
    FROM PARAMS p
    JOIN V_DADOS_CONTRATO_AVT ct
      ON 1=1
    JOIN VH_EST_ORG_CONTRATO_AVT org
      ON org.COD_CONTRATO = ct.COD_CONTRATO
    JOIN VH_HIST_HORAS_COLAB_AVT hr
      ON hr.COD_CONTRATO = ct.COD_CONTRATO
    JOIN VH_CARGO_CONTRATO_AVT fn
      ON fn.COD_CONTRATO = ct.COD_CONTRATO
   WHERE ((p.DT_REF BETWEEN ct.DATA_ADMISSAO AND ct.DATA_DEMISSAO)
       OR (ct.DATA_ADMISSAO <= p.DT_REF AND ct.DATA_DEMISSAO IS NULL))
     AND p.DT_REF BETWEEN org.DATA_INI_ORG AND org.DATA_FIM_ORG
     AND p.DT_REF BETWEEN org.DATA_INICIO  AND org.DATA_FIM
     AND p.DT_REF BETWEEN hr.DATA_INI_HR   AND hr.DATA_FIM_HR
     AND p.DT_REF BETWEEN fn.DATA_INI_CLH  AND fn.DATA_FIM_CLH
     AND org.COD_EMP IN (SELECT COD_EMP FROM EMP_LIST)
     AND org.EDICAO_ORG_4 IS NOT NULL
),*/

CT_BASE AS (
  SELECT
    p.PERIODO,
    p.ANO,
    p.DT_REF,
    ct.COD_CONTRATO,
    ct.SEXO,
    ROW_NUMBER() OVER (
      PARTITION BY p.PERIODO, p.ANO, ct.COD_CONTRATO
      ORDER BY NVL(ct.DATA_DEMISSAO, DATE '9999-12-31') DESC,
               ct.DATA_ADMISSAO DESC
    ) AS RN
  FROM PARAMS p
  JOIN V_DADOS_CONTRATO_AVT ct
    ON 1=1
  WHERE p.DT_REF BETWEEN ct.DATA_ADMISSAO
                     AND NVL(ct.DATA_DEMISSAO, DATE '9999-12-31')
),

CONTRATOS_BASE AS (
  SELECT
    PERIODO,
    ANO,
    DT_REF,
    COD_CONTRATO,
    SEXO
  FROM CT_BASE
  WHERE RN = 1
),

ORG_1 AS (
  SELECT *
  FROM (
    SELECT
      b.PERIODO,
      b.ANO,
      b.COD_CONTRATO,
      org.COD_EMP,
      org.EDICAO_ORG_4,
      ROW_NUMBER() OVER (
        PARTITION BY b.PERIODO, b.ANO, b.COD_CONTRATO
        ORDER BY org.DATA_INICIO DESC, org.DATA_INI_ORG DESC, org.COD_EMP DESC
      ) AS RN
    FROM CONTRATOS_BASE b
    JOIN VH_EST_ORG_CONTRATO_AVT org
      ON org.COD_CONTRATO = b.COD_CONTRATO
     AND b.DT_REF BETWEEN org.DATA_INI_ORG AND org.DATA_FIM_ORG
     AND b.DT_REF BETWEEN org.DATA_INICIO  AND org.DATA_FIM
  )
  WHERE RN = 1
),

HR_1 AS (
  SELECT *
  FROM (
    SELECT
      b.PERIODO,
      b.ANO,
      b.COD_CONTRATO,
      ROW_NUMBER() OVER (
        PARTITION BY b.PERIODO, b.ANO, b.COD_CONTRATO
        ORDER BY hr.DATA_INI_HR DESC, hr.DATA_FIM_HR DESC
      ) AS RN
    FROM CONTRATOS_BASE b
    JOIN VH_HIST_HORAS_COLAB_AVT hr
      ON hr.COD_CONTRATO = b.COD_CONTRATO
     AND b.DT_REF BETWEEN hr.DATA_INI_HR AND hr.DATA_FIM_HR
  )
  WHERE RN = 1
),

FN_1 AS (
  SELECT *
  FROM (
    SELECT
      b.PERIODO,
      b.ANO,
      b.COD_CONTRATO,
      fn.DES_FUNCAO,
      ROW_NUMBER() OVER (
        PARTITION BY b.PERIODO, b.ANO, b.COD_CONTRATO
        ORDER BY fn.DATA_INI_CLH DESC, fn.DATA_FIM_CLH DESC
      ) AS RN
    FROM CONTRATOS_BASE b
    JOIN VH_CARGO_CONTRATO_AVT fn
      ON fn.COD_CONTRATO = b.COD_CONTRATO
     AND b.DT_REF BETWEEN fn.DATA_INI_CLH AND fn.DATA_FIM_CLH
  )
  WHERE RN = 1
),

CONTRATOS AS (
  SELECT
    b.PERIODO,
    b.ANO,
    b.COD_CONTRATO,
    b.SEXO,
    f.DES_FUNCAO
  FROM CONTRATOS_BASE b
  JOIN ORG_1 o
    ON o.PERIODO = b.PERIODO
   AND o.ANO = b.ANO
   AND o.COD_CONTRATO = b.COD_CONTRATO
  JOIN HR_1 h
    ON h.PERIODO = b.PERIODO
   AND h.ANO = b.ANO
   AND h.COD_CONTRATO = b.COD_CONTRATO
  JOIN FN_1 f
    ON f.PERIODO = b.PERIODO
   AND f.ANO = b.ANO
   AND f.COD_CONTRATO = b.COD_CONTRATO
  WHERE o.COD_EMP IN (SELECT COD_EMP FROM EMP_LIST)
    AND o.EDICAO_ORG_4 IS NOT NULL
),


BASE AS (
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    CASE
      WHEN UPPER(SEXO) LIKE 'F%' THEN 'F'
      WHEN UPPER(SEXO) LIKE 'M%' THEN 'M'
      ELSE 'N'
    END AS SEXO,
    UPPER(TRANSLATE(TRIM(DES_FUNCAO),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüç',
      'AAAAAEEEEIIIIOOOOOUUUUCaaaaaeeeeiiiiooooouuuuc')) AS DES_NORM
  FROM CONTRATOS
),

/* ========= Classificação (para os 2 anos) ========= */
CLASSIF AS (
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    SEXO,
    CASE
      /* 1) Aprendiz / Estágio */
      WHEN DES_NORM LIKE '%APRENDIZ%'   THEN 'APRENDIZ'
      WHEN DES_NORM LIKE 'ESTAGIARIO%'  THEN 'ESTAGIARIO'

      /* 2) Conselho */
      WHEN DES_NORM LIKE 'CONSELHO ADMINISTRACAO%' AND COD_CONTRATO IN (299685, 375780) THEN 'CONSELHO_ADM'
      WHEN DES_NORM LIKE 'CONSELHO FISCAL%' OR DES_NORM LIKE 'CONSELHEIRO FISCAL%' THEN 'CONSELHO_FISC'
      WHEN DES_NORM LIKE 'CONSELHO%' OR DES_NORM LIKE 'CONSELHEIRO%' THEN 'CONSELHO_ADM'

      /* 3) Diretoria estatutária varejo*/
      WHEN COD_CONTRATO IN (299685, 375780, 386492) THEN 'DIR_ESTAT_VAR'
        
     /* 4) Diretoria estatutária financeira*/
      WHEN COD_CONTRATO IN (377540, 379244, 386731) THEN 'DIR_ESTAT_FIN'

      /* 5) Diretoria */
      WHEN DES_NORM LIKE 'DIRETOR%' AND COD_CONTRATO NOT IN (299685, 375780, 386492, 377540, 379244, 386731) THEN 'DIRETORIA_ADJ'

      /* 6) Gerência/Supervisão */
      WHEN (DES_NORM LIKE 'GERENTE%' OR DES_NORM LIKE 'SUPERVISOR%' OR
            DES_NORM LIKE 'COMPRADOR%' OR DES_NORM LIKE 'ENCARREGAD%') AND DES_NORM NOT LIKE '%TRAINEE%' THEN 'GER_SUP'
            
      /* 7) Colaboradores */    
      WHEN (DES_NORM LIKE 'ANALISTA%' OR DES_NORM LIKE 'PROGRAMADOR%' OR
            DES_NORM LIKE 'DESENVOLVEDOR%' OR DES_NORM LIKE 'AUDITOR%' OR
            DES_NORM LIKE 'INSTRUTOR%' OR DES_NORM LIKE 'TECNIC%' OR DES_NORM LIKE 'ENFERMAGEM%' OR
            DES_NORM LIKE 'COORDENADOR%' OR DES_NORM LIKE 'ESPECIALISTA%' OR
            DES_NORM LIKE 'LIDER TECH%' OR DES_NORM LIKE 'CHEFE%' OR
            DES_NORM LIKE 'CONTROLLER%' OR DES_NORM LIKE 'MEDICO%' OR
            DES_NORM LIKE 'CAIXA GERAL%') THEN 'COLAB'
      WHEN DES_NORM LIKE 'ASSESSOR%' THEN 'COLAB'
      WHEN (DES_NORM LIKE '%ADMINISTRAT%' OR DES_NORM LIKE '%ESCRITORIO%' OR DES_NORM LIKE '%PESSOAL%' OR
            DES_NORM LIKE '%CONTABIL%' OR DES_NORM LIKE '%FINANCEIR%' OR DES_NORM LIKE '%CREDITO%' OR
            DES_NORM LIKE '%COBRANCA%' OR DES_NORM LIKE '%JURIDIC%' OR DES_NORM LIKE '%MARKETING%' OR
            DES_NORM LIKE '%E-COMMERCE%' OR DES_NORM LIKE '%COMUNICACAO%' OR
            DES_NORM LIKE '%SERVICE DESK%' OR DES_NORM LIKE '%INFRAESTRUTUR%' OR
            DES_NORM LIKE 'ARQUIVISTA%' OR DES_NORM LIKE 'DIGITADOR%' OR
            DES_NORM LIKE 'TELEFONISTA%' OR DES_NORM LIKE 'PREPARADOR DE DADOS%' OR
            DES_NORM LIKE 'AGENTE ADMINISTRATIVO%') THEN 'COLAB'
      WHEN (DES_NORM LIKE 'AUXILIAR DE ESCRITORIO%' OR DES_NORM LIKE 'AUXILIAR DE PESSOAL%' OR
            DES_NORM LIKE 'AUXILIAR DE CONTABILIDADE%' OR DES_NORM LIKE 'AUXILIAR DE COMPRAS%' OR
            DES_NORM LIKE 'ASSISTENTE ADMINISTRATIVO%' OR DES_NORM LIKE 'ASSISTENTE CONTABIL%' OR DES_NORM LIKE 'ASSISTENTE DE MARKETING%' OR
            DES_NORM LIKE 'ASSISTENTE FISCAL%' OR DES_NORM LIKE 'ASSISTENTE FINANCEIRO%' OR 
            DES_NORM LIKE '%TRAINEE' OR DES_NORM LIKE 'PROGRAMADOR TRAINEE%' OR DES_NORM LIKE 'COMPRADOR TRAINEE%') THEN 'COLAB'
      WHEN (DES_NORM LIKE '%AUXILIAR%' OR DES_NORM LIKE '%LOJA%' OR DES_NORM LIKE 'VENDEDOR%' OR DES_NORM LIKE 'VEND.%' OR
            DES_NORM LIKE '%VENDAS%' OR DES_NORM LIKE '%DISTRIBUICAO%' OR
            DES_NORM LIKE '%ALMOXARIF%' OR DES_NORM LIKE '%SERVICOS GERAIS%' OR
            DES_NORM LIKE '%MANUTENCAO%' OR DES_NORM LIKE '%EMPILHADEIR%' OR
            DES_NORM LIKE '%OPERADOR%' OR DES_NORM LIKE '%ESTOQUE%' OR DES_NORM LIKE '%REPOSITOR%' OR DES_NORM LIKE '%NEGOCIO%' OR
            DES_NORM LIKE '%CONFERENTE%' OR DES_NORM LIKE '%EMPACOTAD%' OR
            DES_NORM LIKE '%SEGURANCA%' OR DES_NORM LIKE 'PORTEIRO%' OR
            DES_NORM LIKE 'SERVENTE%' OR DES_NORM LIKE 'CASEIRO%' OR
            DES_NORM LIKE 'JARDINEIRO%' OR DES_NORM LIKE 'GOVERNANTA%' OR
            DES_NORM LIKE '%ORIENTADOR DE VENDA%' OR DES_NORM LIKE '%EXTRACAO%' OR DES_NORM LIKE '%TRABALHADOR%') THEN 'COLAB' 

      /* 7) Especialistas */ --backup
      /*WHEN (DES_NORM LIKE 'ANALISTA%' OR DES_NORM LIKE 'PROGRAMADOR%' OR
            DES_NORM LIKE 'DESENVOLVEDOR%' OR DES_NORM LIKE 'AUDITOR%' OR
            DES_NORM LIKE 'INSTRUTOR%' OR DES_NORM LIKE 'TECNIC%' OR DES_NORM LIKE 'ENFERMAGEM%' OR
            DES_NORM LIKE 'COORDENADOR%' OR DES_NORM LIKE 'ESPECIALISTA%' OR
            DES_NORM LIKE 'LIDER TECH%' OR DES_NORM LIKE 'CHEFE%' OR
            DES_NORM LIKE 'CONTROLLER%' OR DES_NORM LIKE 'MEDICO%' OR
            DES_NORM LIKE 'CAIXA GERAL%') AND DES_NORM NOT LIKE '%TRAINEE%' THEN 'ESPECIAL'*/
 

      /* 7) Administrativo (override assessor) */ --BACKUP
    /*WHEN DES_NORM LIKE 'ASSESSOR%' THEN 'ADMIN'
      WHEN (DES_NORM LIKE '%ADMINISTRAT%' OR DES_NORM LIKE '%ESCRITORIO%' OR DES_NORM LIKE '%PESSOAL%' OR
            DES_NORM LIKE '%CONTABIL%' OR DES_NORM LIKE '%FINANCEIR%' OR DES_NORM LIKE '%CREDITO%' OR
            DES_NORM LIKE '%COBRANCA%' OR DES_NORM LIKE '%JURIDIC%' OR DES_NORM LIKE '%MARKETING%' OR
            DES_NORM LIKE '%E-COMMERCE%' OR DES_NORM LIKE '%COMUNICACAO%' OR
            DES_NORM LIKE '%SERVICE DESK%' OR DES_NORM LIKE '%INFRAESTRUTUR%' OR
            DES_NORM LIKE 'ARQUIVISTA%' OR DES_NORM LIKE 'DIGITADOR%' OR
            DES_NORM LIKE 'TELEFONISTA%' OR DES_NORM LIKE 'PREPARADOR DE DADOS%' OR
            DES_NORM LIKE 'AGENTE ADMINISTRATIVO%') THEN 'ADMIN'
      WHEN (DES_NORM LIKE 'AUXILIAR DE ESCRITORIO%' OR DES_NORM LIKE 'AUXILIAR DE PESSOAL%' OR
            DES_NORM LIKE 'AUXILIAR DE CONTABILIDADE%' OR DES_NORM LIKE 'AUXILIAR DE COMPRAS%' OR
            DES_NORM LIKE 'ASSISTENTE ADMINISTRATIVO%' OR DES_NORM LIKE 'ASSISTENTE CONTABIL%' OR DES_NORM LIKE 'ASSISTENTE DE MARKETING%' OR
            DES_NORM LIKE 'ASSISTENTE FISCAL%' OR DES_NORM LIKE 'ASSISTENTE FINANCEIRO%' OR 
            DES_NORM LIKE '%TRAINEE' OR DES_NORM LIKE 'PROGRAMADOR TRAINEE%' OR DES_NORM LIKE 'COMPRADOR TRAINEE%') THEN 'ADMIN'*/

      /* 9) Operacional */ --BACKUP
      /*WHEN (DES_NORM LIKE '%AUXILIAR%' OR DES_NORM LIKE '%LOJA%' OR DES_NORM LIKE 'VENDEDOR%' OR DES_NORM LIKE 'VEND.%' OR
            DES_NORM LIKE '%VENDAS%' OR DES_NORM LIKE '%DISTRIBUICAO%' OR
            DES_NORM LIKE '%ALMOXARIF%' OR DES_NORM LIKE '%SERVICOS GERAIS%' OR
            DES_NORM LIKE '%MANUTENCAO%' OR DES_NORM LIKE '%EMPILHADEIR%' OR
            DES_NORM LIKE '%OPERADOR%' OR DES_NORM LIKE '%ESTOQUE%' OR DES_NORM LIKE '%REPOSITOR%' OR DES_NORM LIKE '%NEGOCIO%' OR
            DES_NORM LIKE '%CONFERENTE%' OR DES_NORM LIKE '%EMPACOTAD%' OR
            DES_NORM LIKE '%SEGURANCA%' OR DES_NORM LIKE 'PORTEIRO%' OR
            DES_NORM LIKE 'SERVENTE%' OR DES_NORM LIKE 'CASEIRO%' OR
            DES_NORM LIKE 'JARDINEIRO%' OR DES_NORM LIKE 'GOVERNANTA%' OR
            DES_NORM LIKE '%ORIENTADOR DE VENDA%' OR DES_NORM LIKE '%EXTRACAO%' OR DES_NORM LIKE '%TRABALHADOR%') AND
            DES_NORM NOT LIKE 'CAIXA GERAL%' THEN 'OPER'*/
            
      ELSE 'COLAB'
    END AS NIVEL_KEY
  FROM BASE
),

CLASSIF_B12 AS (
  /* base normal */
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    SEXO,
    NIVEL_KEY
  FROM CLASSIF

  UNION ALL

  /* duplicação controlada: mesmos contratos também no conselho */
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    SEXO,
    'CONSELHO_ADM' AS NIVEL_KEY
  FROM CLASSIF
  WHERE COD_CONTRATO IN (299685, 375780)
    AND NIVEL_KEY IN ('DIR_ESTAT_VAR', 'DIR_ESTAT_FIN')
),


/* =======================================================
   ======== BLOCO I (Y e Y-1) - Quantidades Gerais ======= */
   
AGG_I AS (
  SELECT
    PERIODO, ANO, NIVEL_KEY,
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN SEXO='F' THEN 1 ELSE 0 END) AS FEM_QTDE,
    SUM(CASE WHEN SEXO='M' THEN 1 ELSE 0 END) AS MASC_QTDE
  FROM CLASSIF_B12
  GROUP BY PERIODO, ANO, NIVEL_KEY
),

GRID_I AS (
  SELECT
    p.PERIODO, p.ANO,
    n.ORDEM, n.NIVEL_KEY, n.NIVEL_DESC,
    NVL(a.FEM_QTDE,0) AS FEM_QTDE,
    ROUND(100*NVL(a.FEM_QTDE,0)/NULLIF(NVL(a.TOTAL,0),0),0) AS FEM_PCT,
    NVL(a.MASC_QTDE,0) AS MASC_QTDE,
    ROUND(100*NVL(a.MASC_QTDE,0)/NULLIF(NVL(a.TOTAL,0),0),0) AS MASC_PCT,
    NVL(a.TOTAL,0) AS TOTAL
  FROM PARAMS p
  CROSS JOIN NIVEIS n
  LEFT JOIN AGG_I a
    ON a.PERIODO=p.PERIODO AND a.ANO=p.ANO AND a.NIVEL_KEY=n.NIVEL_KEY
),

TOTAIS_I AS (
  SELECT
    PERIODO,
    ANO,
    COUNT(CASE WHEN SEXO='F' THEN 1 END) AS TOT_FEM_QTDE,
    
    ROUND(100 * COUNT(CASE WHEN SEXO='F' THEN 1 END) /
          NULLIF(COUNT(*),0),0) AS TOT_FEM_PCT,

    COUNT(CASE WHEN SEXO='M' THEN 1 END) AS TOT_MASC_QTDE,
    ROUND(100 * COUNT(CASE WHEN SEXO='M' THEN 1 END) /
          NULLIF(COUNT(*),0),0) AS TOT_MASC_PCT,

    COUNT(*) AS TOT_GERAL_QTDE,

    ROUND(100 * (
      COUNT(CASE WHEN SEXO='F' THEN 1 END) +
      COUNT(CASE WHEN SEXO='M' THEN 1 END)
    ) / NULLIF(COUNT(*),0),0) AS TOT_GERAL_PCT

  FROM CLASSIF
  WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
  GROUP BY PERIODO, ANO
),


/* ======================================================================= 
   ========= BLOCO II (3 grupos) para Y e Y-1 - Apenas Executivo ========= */

BLOCO2_BASE AS (
  SELECT * FROM GRID_I
   WHERE NIVEL_KEY IN ('CONSELHO_ADM','CONSELHO_FISC','DIR_ESTAT_VAR', 'DIR_ESTAT_FIN')
),

BLOCO2_TOTAIS AS (
  SELECT
    PERIODO,
    ANO,
    SUM(CASE WHEN SEXO = 'F' THEN 1 ELSE 0 END) AS B2_TOT_FEM_QTDE,
    ROUND(100 * SUM(CASE WHEN SEXO = 'F' THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 0) AS B2_TOT_FEM_PCT,
    SUM(CASE WHEN SEXO = 'M' THEN 1 ELSE 0 END) AS B2_TOT_MASC_QTDE,
    ROUND(100 * SUM(CASE WHEN SEXO = 'M' THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 0) AS B2_TOT_MASC_PCT,
    COUNT(*) AS B2_TOT_GERAL_QTDE,
    ROUND(100 * (
      SUM(CASE WHEN SEXO = 'F' THEN 1 ELSE 0 END) +
      SUM(CASE WHEN SEXO = 'M' THEN 1 ELSE 0 END)
    ) / NULLIF(COUNT(*),0), 0) AS B2_TOT_GERAL_PCT
  FROM CLASSIF
  WHERE NIVEL_KEY IN ('CONSELHO_ADM','CONSELHO_FISC','DIR_ESTAT_VAR','DIR_ESTAT_FIN')
    AND NIVEL_KEY <> 'DIR_ESTAT_FIN'
  GROUP BY PERIODO, ANO
),

BLOCO2_LINHAS AS (
  SELECT PERIODO, ANO, 1 AS B2_TARGET_ORDEM,
         NIVEL_DESC AS B2_NIVEL,
         FEM_QTDE AS B2_FEM_QTDE, FEM_PCT AS B2_FEM_PCT,
         MASC_QTDE AS B2_MASC_QTDE, MASC_PCT AS B2_MASC_PCT,
         TOTAL AS B2_TOTAL
    FROM BLOCO2_BASE WHERE NIVEL_KEY='CONSELHO_ADM'
  UNION ALL
  SELECT PERIODO, ANO, 2, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE WHERE NIVEL_KEY='CONSELHO_FISC'
  UNION ALL
  SELECT PERIODO, ANO, 3, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE WHERE NIVEL_KEY='DIR_ESTAT_VAR'
  UNION ALL
  SELECT PERIODO, ANO, 4, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE WHERE NIVEL_KEY='DIR_ESTAT_FIN'
),

/* =======================================================================================
   ========= BLOCO III (para Y e Y-1) - Remuneração Fixa, Eventual e/ou Variável ========= */
REMUN_1001 AS (
  SELECT
    p.PERIODO,
    p.ANO,
    a.COD_CONTRATO,
    SUM(a.VALOR_VD) AS VALOR_1001
  FROM PARAMS p
  CROSS JOIN EMP_LIST p1
  JOIN RHFP1003 b
    ON b.DATA_REFERENCIA = p.DT_REF
   AND b.COD_ORGANOGRAMA = p1.COD_ORGANOGRAMA
  JOIN RHFP1006 a
    ON a.COD_MESTRE_EVENTO = b.COD_MESTRE_EVENTO
  WHERE b.COD_EVENTO = 1
    AND a.COD_VD = 1001
  GROUP BY p.PERIODO, p.ANO, a.COD_CONTRATO
),

/*Por hora não será usado, mas fica aqui pra criar outra versão*/
/*REMUN_219 AS (
  SELECT
    p.PERIODO,
    p.ANO,
    a.COD_CONTRATO,
    SUM(a.VALOR_VD) AS VALOR_219
  FROM PARAMS_PLR p
  CROSS JOIN EMP_LIST p1
  JOIN RHFP1003 b
    ON b.DATA_REFERENCIA = p.DT_REF_PLR
   AND b.COD_ORGANOGRAMA = p1.COD_ORGANOGRAMA
  JOIN RHFP1006 a
    ON a.COD_MESTRE_EVENTO = b.COD_MESTRE_EVENTO
  WHERE b.COD_EVENTO = 9
    AND a.COD_VD = 219
  GROUP BY
    p.PERIODO,
    p.ANO,
    a.COD_CONTRATO
),*/

REMUN_FX_CONTRATO AS (
  SELECT
    x.PERIODO,
    x.ANO,
    x.COD_CONTRATO,
    SUM(x.VALOR) AS REMUN_FIXA
  FROM (
    SELECT PERIODO, ANO, COD_CONTRATO, VALOR_1001 AS VALOR
    FROM REMUN_1001

    /*UNION ALL

    SELECT PERIODO, ANO, COD_CONTRATO, VALOR_219 AS VALOR
    FROM REMUN_219*/
  ) x
  GROUP BY x.PERIODO, x.ANO, x.COD_CONTRATO
),

BLOCO3_BASE AS (
  SELECT
    cl.PERIODO,
    cl.ANO,
    cl.NIVEL_KEY,
    cl.SEXO,
    NVL(rf.REMUN_FIXA,0) AS REMUN_FIXA
  FROM CLASSIF cl
  LEFT JOIN REMUN_FX_CONTRATO rf
    ON rf.PERIODO = cl.PERIODO
   AND rf.ANO     = cl.ANO
   AND rf.COD_CONTRATO = cl.COD_CONTRATO
),

BLOCO3_AGG AS (
  SELECT
    PERIODO,
    ANO,
    NIVEL_KEY,
    SUM(CASE WHEN SEXO='F' THEN 1 ELSE 0 END) AS FEM_QTDE,
    SUM(CASE WHEN SEXO='M' THEN 1 ELSE 0 END) AS MASC_QTDE,
    SUM(CASE WHEN SEXO = 'F' THEN REMUN_FIXA ELSE 0 END) AS FEM_VAL,
    SUM(CASE WHEN SEXO = 'M' THEN REMUN_FIXA ELSE 0 END) AS MASC_VAL,
    SUM(REMUN_FIXA) AS TOTAL_VAL
  FROM BLOCO3_BASE
  GROUP BY PERIODO, ANO, NIVEL_KEY
),

BLOCO3_GRID AS (
  SELECT
    PERIODO,
    ANO,
    NIVEL_KEY,
    FEM_QTDE,
    FEM_VAL,
    MASC_QTDE,
    MASC_VAL,
    (NVL(FEM_QTDE,0) + NVL(MASC_QTDE,0)) AS TOTAL_QTDE,
    TOTAL_VAL,
    ROUND(100 * FEM_VAL  / NULLIF(TOTAL_VAL,0), 2) AS B3_FEM_PCT,
    ROUND(100 * MASC_VAL / NULLIF(TOTAL_VAL,0), 2) AS B3_MASC_PCT
  FROM BLOCO3_AGG
),

/*BLOCO3_TOTAIS AS (
  SELECT
    r.PERIODO,
    r.ANO,
    r.B3_TOT_FEM_QTD,
    r.B3_TOT_FEM_VAL,
    r.B3_TOT_MASC_QTD,
    r.B3_TOT_MASC_VAL,
    r.B3_TOT_GERAL_VAL,
    q.B3_TOT_FEM_QTDE,
    q.B3_TOT_MASC_QTDE,
    q.B3_TOT_GERAL_QTDE
  FROM (
    SELECT
      PERIODO,
      ANO,
      SUM(FEM_QTDE)  AS B3_TOT_FEM_QTD,
      SUM(FEM_VAL)   AS B3_TOT_FEM_VAL,
      SUM(MASC_QTDE) AS B3_TOT_MASC_QTD,
      SUM(MASC_VAL)  AS B3_TOT_MASC_VAL,
      SUM(TOTAL_VAL) AS B3_TOT_GERAL_VAL
    FROM BLOCO3_AGG
    WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
    GROUP BY PERIODO, ANO
  ) r
  JOIN (
    SELECT
      PERIODO,
      ANO,
      SUM(CASE WHEN SEXO = 'F' THEN 1 ELSE 0 END) AS B3_TOT_FEM_QTDE,
      SUM(CASE WHEN SEXO = 'M' THEN 1 ELSE 0 END) AS B3_TOT_MASC_QTDE,
      COUNT(*) AS B3_TOT_GERAL_QTDE
    FROM CLASSIF
    WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
    GROUP BY PERIODO, ANO
  ) q
    ON q.PERIODO = r.PERIODO
   AND q.ANO     = r.ANO
),*/

BLOCO3_TOTAIS AS (
  SELECT
    PERIODO,
    ANO,
    SUM(FEM_QTDE)  AS B3_TOT_FEM_QTDE,
    SUM(MASC_QTDE) AS B3_TOT_MASC_QTDE,
    SUM(FEM_QTDE) + SUM(MASC_QTDE) AS B3_TOT_GERAL_QTDE,
    SUM(FEM_VAL)   AS B3_TOT_FEM_VAL,
    SUM(MASC_VAL)  AS B3_TOT_MASC_VAL,
    SUM(TOTAL_VAL) AS B3_TOT_GERAL_VAL
  FROM BLOCO3_AGG
  WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
  GROUP BY PERIODO, ANO
),



/* =============================================================
   ======= QUADRO II -  MAPEAMENTO DE SOMENTE ADMITIDOS ========
   ============================================================= */

/* ========= Base contratos (admitidos no ano do período) ========= */
/*backup*/
/*CONTRATOS_ADM AS (
  SELECT DISTINCT
         p.PERIODO,
         p.ANO,
         ct.COD_CONTRATO,
         ct.SEXO,
         fn.DES_FUNCAO
    FROM PARAMS p
    JOIN V_DADOS_CONTRATO_AVT ct
      ON 1=1
    JOIN VH_EST_ORG_CONTRATO_AVT org
      ON org.COD_CONTRATO = ct.COD_CONTRATO
    JOIN VH_HIST_HORAS_COLAB_AVT hr
      ON hr.COD_CONTRATO = ct.COD_CONTRATO
    JOIN VH_CARGO_CONTRATO_AVT fn
      ON fn.COD_CONTRATO = ct.COD_CONTRATO
   WHERE ct.DATA_ADMISSAO >= TRUNC(p.DT_REF, 'YYYY')
     AND ct.DATA_ADMISSAO <  ADD_MONTHS(TRUNC(p.DT_REF, 'YYYY'), 12)
     AND p.DT_REF BETWEEN org.DATA_INI_ORG AND org.DATA_FIM_ORG
     AND p.DT_REF BETWEEN org.DATA_INICIO  AND org.DATA_FIM
     AND p.DT_REF BETWEEN hr.DATA_INI_HR   AND hr.DATA_FIM_HR
     AND p.DT_REF BETWEEN fn.DATA_INI_CLH  AND fn.DATA_FIM_CLH
     AND org.COD_EMP IN (SELECT COD_EMP FROM EMP_LIST)
     AND org.EDICAO_ORG_4 IS NOT NULL
),*/

CT_ADM_BASE AS (
  SELECT
    p.PERIODO,
    p.ANO,
    p.DT_REF,
    ct.COD_PESSOA,
    ct.COD_CONTRATO,
    ct.SEXO,
    TRUNC(ct.DATA_ADMISSAO) AS DATA_ADMISSAO,
    LEAST(NVL(ct.DATA_DEMISSAO, p.DT_REF), p.DT_REF) AS DT_CORTE,
    ROW_NUMBER() OVER (
      PARTITION BY p.PERIODO, p.ANO, ct.COD_CONTRATO
      ORDER BY NVL(ct.DATA_DEMISSAO, DATE '9999-12-31') DESC,
               ct.DATA_ADMISSAO DESC
    ) AS RN_CONTRATO
  FROM PARAMS p
  JOIN V_DADOS_CONTRATO_AVT ct
    ON 1=1
  WHERE ct.DATA_ADMISSAO >= TRUNC(p.DT_REF, 'YYYY')
    AND ct.DATA_ADMISSAO <  ADD_MONTHS(TRUNC(p.DT_REF, 'YYYY'), 12)
),

CONTRATOS_ADM_BASE AS (
  SELECT
    PERIODO,
    ANO,
    DT_REF,
    COD_PESSOA,
    COD_CONTRATO,
    SEXO,
    DATA_ADMISSAO,
    DT_CORTE
  FROM CT_ADM_BASE
  WHERE RN_CONTRATO = 1
),

ORG_ADM_1 AS (
  SELECT *
  FROM (
    SELECT
      b.PERIODO,
      b.ANO,
      b.COD_CONTRATO,
      org.COD_EMP,
      org.EDICAO_ORG_4,
      ROW_NUMBER() OVER (
        PARTITION BY b.PERIODO, b.ANO, b.COD_CONTRATO
        ORDER BY org.DATA_INICIO DESC, org.DATA_INI_ORG DESC, org.COD_EMP DESC
      ) AS RN
    FROM CONTRATOS_ADM_BASE b
    JOIN VH_EST_ORG_CONTRATO_AVT org
      ON org.COD_CONTRATO = b.COD_CONTRATO
     AND b.DT_CORTE BETWEEN org.DATA_INI_ORG AND org.DATA_FIM_ORG
     AND b.DT_CORTE BETWEEN org.DATA_INICIO  AND org.DATA_FIM
  )
  WHERE RN = 1
),

HR_ADM_1 AS (
  SELECT *
  FROM (
    SELECT
      b.PERIODO,
      b.ANO,
      b.COD_CONTRATO,
      ROW_NUMBER() OVER (
        PARTITION BY b.PERIODO, b.ANO, b.COD_CONTRATO
        ORDER BY hr.DATA_INI_HR DESC, hr.DATA_FIM_HR DESC
      ) AS RN
    FROM CONTRATOS_ADM_BASE b
    JOIN VH_HIST_HORAS_COLAB_AVT hr
      ON hr.COD_CONTRATO = b.COD_CONTRATO
     AND b.DT_CORTE BETWEEN hr.DATA_INI_HR AND hr.DATA_FIM_HR
  )
  WHERE RN = 1
),

FN_ADM_1 AS (
  SELECT *
  FROM (
    SELECT
      b.PERIODO,
      b.ANO,
      b.COD_CONTRATO,
      fn.DES_FUNCAO,
      ROW_NUMBER() OVER (
        PARTITION BY b.PERIODO, b.ANO, b.COD_CONTRATO
        ORDER BY fn.DATA_INI_CLH DESC,
                 NVL(fn.DATA_FIM_CLH, DATE '9999-12-31') DESC
      ) AS RN
    FROM CONTRATOS_ADM_BASE b
    JOIN VH_CARGO_CONTRATO_AVT fn
      ON fn.COD_CONTRATO = b.COD_CONTRATO
     AND b.DATA_ADMISSAO BETWEEN fn.DATA_INI_CLH
                             AND NVL(fn.DATA_FIM_CLH, DATE '9999-12-31')
  )
  WHERE RN = 1
),

CONTRATOS_ADM AS (
  SELECT DISTINCT
    b.PERIODO,
    b.ANO,
    b.COD_PESSOA,
    b.COD_CONTRATO,
    b.SEXO,
    f.DES_FUNCAO
  FROM CONTRATOS_ADM_BASE b
  JOIN ORG_ADM_1 o
    ON o.PERIODO = b.PERIODO
   AND o.ANO = b.ANO
   AND o.COD_CONTRATO = b.COD_CONTRATO
  JOIN HR_ADM_1 h
    ON h.PERIODO = b.PERIODO
   AND h.ANO = b.ANO
   AND h.COD_CONTRATO = b.COD_CONTRATO
  JOIN FN_ADM_1 f
    ON f.PERIODO = b.PERIODO
   AND f.ANO = b.ANO
   AND f.COD_CONTRATO = b.COD_CONTRATO
  WHERE o.COD_EMP IN (SELECT COD_EMP FROM EMP_LIST)
    AND o.EDICAO_ORG_4 IS NOT NULL
),


BASE_ADM AS (
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    CASE
      WHEN UPPER(SEXO) LIKE 'F%' THEN 'F'
      WHEN UPPER(SEXO) LIKE 'M%' THEN 'M'
      ELSE 'N'
    END AS SEXO,
    UPPER(TRANSLATE(TRIM(DES_FUNCAO),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüç',
      'AAAAAEEEEIIIIOOOOOUUUUCaaaaaeeeeiiiiooooouuuuc')) AS DES_NORM
  FROM CONTRATOS_ADM
),

CLASSIF_ADM AS (
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    SEXO,
    CASE
      /* 1) Aprendiz / Estágio */
      WHEN DES_NORM LIKE '%APRENDIZ%'   THEN 'APRENDIZ'
      WHEN DES_NORM LIKE 'ESTAGIARIO%'  THEN 'ESTAGIARIO'

      /* 2) Conselho */
      WHEN DES_NORM LIKE 'CONSELHO ADMINISTRACAO%' AND COD_CONTRATO IN (299685, 375780) THEN 'CONSELHO_ADM'
      WHEN DES_NORM LIKE 'CONSELHO FISCAL%' OR DES_NORM LIKE 'CONSELHEIRO FISCAL%' THEN 'CONSELHO_FISC'
      WHEN DES_NORM LIKE 'CONSELHO%' OR DES_NORM LIKE 'CONSELHEIRO%' THEN 'CONSELHO_ADM'

      /* 3) Diretoria estatutária varejo*/
      WHEN COD_CONTRATO IN (299685, 375780, 386492) THEN 'DIR_ESTAT_VAR'
        
     /* 4) Diretoria estatutária financeira*/
      WHEN COD_CONTRATO IN (377540, 379244, 386731) THEN 'DIR_ESTAT_FIN'

      /* 5) Diretoria */
      WHEN DES_NORM LIKE 'DIRETOR%' AND COD_CONTRATO NOT IN (299685, 375780, 386492, 377540, 379244, 386731) THEN 'DIRETORIA_ADJ'

      /* 6) Gerência/Supervisão */
      WHEN (DES_NORM LIKE 'GERENTE%' OR DES_NORM LIKE 'SUPERVISOR%' OR
            DES_NORM LIKE 'COMPRADOR%' OR DES_NORM LIKE 'ENCARREGAD%') AND DES_NORM NOT LIKE '%TRAINEE%' THEN 'GER_SUP'
            
      /* 7) Colaboradores */    
      WHEN (DES_NORM LIKE 'ANALISTA%' OR DES_NORM LIKE 'PROGRAMADOR%' OR
            DES_NORM LIKE 'DESENVOLVEDOR%' OR DES_NORM LIKE 'AUDITOR%' OR
            DES_NORM LIKE 'INSTRUTOR%' OR DES_NORM LIKE 'TECNIC%' OR DES_NORM LIKE 'ENFERMAGEM%' OR
            DES_NORM LIKE 'COORDENADOR%' OR DES_NORM LIKE 'ESPECIALISTA%' OR
            DES_NORM LIKE 'LIDER TECH%' OR DES_NORM LIKE 'CHEFE%' OR
            DES_NORM LIKE 'CONTROLLER%' OR DES_NORM LIKE 'MEDICO%' OR
            DES_NORM LIKE 'CAIXA GERAL%') THEN 'COLAB'
      WHEN DES_NORM LIKE 'ASSESSOR%' THEN 'COLAB'
      WHEN (DES_NORM LIKE '%ADMINISTRAT%' OR DES_NORM LIKE '%ESCRITORIO%' OR DES_NORM LIKE '%PESSOAL%' OR
            DES_NORM LIKE '%CONTABIL%' OR DES_NORM LIKE '%FINANCEIR%' OR DES_NORM LIKE '%CREDITO%' OR
            DES_NORM LIKE '%COBRANCA%' OR DES_NORM LIKE '%JURIDIC%' OR DES_NORM LIKE '%MARKETING%' OR
            DES_NORM LIKE '%E-COMMERCE%' OR DES_NORM LIKE '%COMUNICACAO%' OR
            DES_NORM LIKE '%SERVICE DESK%' OR DES_NORM LIKE '%INFRAESTRUTUR%' OR
            DES_NORM LIKE 'ARQUIVISTA%' OR DES_NORM LIKE 'DIGITADOR%' OR
            DES_NORM LIKE 'TELEFONISTA%' OR DES_NORM LIKE 'PREPARADOR DE DADOS%' OR
            DES_NORM LIKE 'AGENTE ADMINISTRATIVO%') THEN 'COLAB'
      WHEN (DES_NORM LIKE 'AUXILIAR DE ESCRITORIO%' OR DES_NORM LIKE 'AUXILIAR DE PESSOAL%' OR
            DES_NORM LIKE 'AUXILIAR DE CONTABILIDADE%' OR DES_NORM LIKE 'AUXILIAR DE COMPRAS%' OR
            DES_NORM LIKE 'ASSISTENTE ADMINISTRATIVO%' OR DES_NORM LIKE 'ASSISTENTE CONTABIL%' OR DES_NORM LIKE 'ASSISTENTE DE MARKETING%' OR
            DES_NORM LIKE 'ASSISTENTE FISCAL%' OR DES_NORM LIKE 'ASSISTENTE FINANCEIRO%' OR 
            DES_NORM LIKE '%TRAINEE' OR DES_NORM LIKE 'PROGRAMADOR TRAINEE%' OR DES_NORM LIKE 'COMPRADOR TRAINEE%') THEN 'COLAB'
      WHEN (DES_NORM LIKE '%AUXILIAR%' OR DES_NORM LIKE '%LOJA%' OR DES_NORM LIKE 'VENDEDOR%' OR DES_NORM LIKE 'VEND.%' OR
            DES_NORM LIKE '%VENDAS%' OR DES_NORM LIKE '%DISTRIBUICAO%' OR
            DES_NORM LIKE '%ALMOXARIF%' OR DES_NORM LIKE '%SERVICOS GERAIS%' OR
            DES_NORM LIKE '%MANUTENCAO%' OR DES_NORM LIKE '%EMPILHADEIR%' OR
            DES_NORM LIKE '%OPERADOR%' OR DES_NORM LIKE '%ESTOQUE%' OR DES_NORM LIKE '%REPOSITOR%' OR DES_NORM LIKE '%NEGOCIO%' OR
            DES_NORM LIKE '%CONFERENTE%' OR DES_NORM LIKE '%EMPACOTAD%' OR
            DES_NORM LIKE '%SEGURANCA%' OR DES_NORM LIKE 'PORTEIRO%' OR
            DES_NORM LIKE 'SERVENTE%' OR DES_NORM LIKE 'CASEIRO%' OR
            DES_NORM LIKE 'JARDINEIRO%' OR DES_NORM LIKE 'GOVERNANTA%' OR
            DES_NORM LIKE '%ORIENTADOR DE VENDA%' OR DES_NORM LIKE '%EXTRACAO%' OR DES_NORM LIKE '%TRABALHADOR%') THEN 'COLAB' 

      /* 7) Especialistas */ --backup
      /*WHEN (DES_NORM LIKE 'ANALISTA%' OR DES_NORM LIKE 'PROGRAMADOR%' OR
            DES_NORM LIKE 'DESENVOLVEDOR%' OR DES_NORM LIKE 'AUDITOR%' OR
            DES_NORM LIKE 'INSTRUTOR%' OR DES_NORM LIKE 'TECNIC%' OR DES_NORM LIKE 'ENFERMAGEM%' OR
            DES_NORM LIKE 'COORDENADOR%' OR DES_NORM LIKE 'ESPECIALISTA%' OR
            DES_NORM LIKE 'LIDER TECH%' OR DES_NORM LIKE 'CHEFE%' OR
            DES_NORM LIKE 'CONTROLLER%' OR DES_NORM LIKE 'MEDICO%' OR
            DES_NORM LIKE 'CAIXA GERAL%') AND DES_NORM NOT LIKE '%TRAINEE%' THEN 'ESPECIAL'*/
 

      /* 7) Administrativo (override assessor) */ --BACKUP
    /*WHEN DES_NORM LIKE 'ASSESSOR%' THEN 'ADMIN'
      WHEN (DES_NORM LIKE '%ADMINISTRAT%' OR DES_NORM LIKE '%ESCRITORIO%' OR DES_NORM LIKE '%PESSOAL%' OR
            DES_NORM LIKE '%CONTABIL%' OR DES_NORM LIKE '%FINANCEIR%' OR DES_NORM LIKE '%CREDITO%' OR
            DES_NORM LIKE '%COBRANCA%' OR DES_NORM LIKE '%JURIDIC%' OR DES_NORM LIKE '%MARKETING%' OR
            DES_NORM LIKE '%E-COMMERCE%' OR DES_NORM LIKE '%COMUNICACAO%' OR
            DES_NORM LIKE '%SERVICE DESK%' OR DES_NORM LIKE '%INFRAESTRUTUR%' OR
            DES_NORM LIKE 'ARQUIVISTA%' OR DES_NORM LIKE 'DIGITADOR%' OR
            DES_NORM LIKE 'TELEFONISTA%' OR DES_NORM LIKE 'PREPARADOR DE DADOS%' OR
            DES_NORM LIKE 'AGENTE ADMINISTRATIVO%') THEN 'ADMIN'
      WHEN (DES_NORM LIKE 'AUXILIAR DE ESCRITORIO%' OR DES_NORM LIKE 'AUXILIAR DE PESSOAL%' OR
            DES_NORM LIKE 'AUXILIAR DE CONTABILIDADE%' OR DES_NORM LIKE 'AUXILIAR DE COMPRAS%' OR
            DES_NORM LIKE 'ASSISTENTE ADMINISTRATIVO%' OR DES_NORM LIKE 'ASSISTENTE CONTABIL%' OR DES_NORM LIKE 'ASSISTENTE DE MARKETING%' OR
            DES_NORM LIKE 'ASSISTENTE FISCAL%' OR DES_NORM LIKE 'ASSISTENTE FINANCEIRO%' OR 
            DES_NORM LIKE '%TRAINEE' OR DES_NORM LIKE 'PROGRAMADOR TRAINEE%' OR DES_NORM LIKE 'COMPRADOR TRAINEE%') THEN 'ADMIN'*/

      /* 9) Operacional */ --BACKUP
      /*WHEN (DES_NORM LIKE '%AUXILIAR%' OR DES_NORM LIKE '%LOJA%' OR DES_NORM LIKE 'VENDEDOR%' OR DES_NORM LIKE 'VEND.%' OR
            DES_NORM LIKE '%VENDAS%' OR DES_NORM LIKE '%DISTRIBUICAO%' OR
            DES_NORM LIKE '%ALMOXARIF%' OR DES_NORM LIKE '%SERVICOS GERAIS%' OR
            DES_NORM LIKE '%MANUTENCAO%' OR DES_NORM LIKE '%EMPILHADEIR%' OR
            DES_NORM LIKE '%OPERADOR%' OR DES_NORM LIKE '%ESTOQUE%' OR DES_NORM LIKE '%REPOSITOR%' OR DES_NORM LIKE '%NEGOCIO%' OR
            DES_NORM LIKE '%CONFERENTE%' OR DES_NORM LIKE '%EMPACOTAD%' OR
            DES_NORM LIKE '%SEGURANCA%' OR DES_NORM LIKE 'PORTEIRO%' OR
            DES_NORM LIKE 'SERVENTE%' OR DES_NORM LIKE 'CASEIRO%' OR
            DES_NORM LIKE 'JARDINEIRO%' OR DES_NORM LIKE 'GOVERNANTA%' OR
            DES_NORM LIKE '%ORIENTADOR DE VENDA%' OR DES_NORM LIKE '%EXTRACAO%' OR DES_NORM LIKE '%TRABALHADOR%') AND
            DES_NORM NOT LIKE 'CAIXA GERAL%' THEN 'OPER'*/
            
      ELSE 'COLAB'
    END AS NIVEL_KEY
  FROM BASE_ADM
),

CLASSIF_B12_ADM AS (
  /* base normal */
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    SEXO,
    NIVEL_KEY
  FROM CLASSIF_ADM

  UNION ALL

  /* duplicação controlada: mesmos contratos também no conselho */
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    SEXO,
    'CONSELHO_ADM' AS NIVEL_KEY
  FROM CLASSIF_ADM
  WHERE COD_CONTRATO IN (299685, 375780)
    AND NIVEL_KEY IN ('DIR_ESTAT_VAR', 'DIR_ESTAT_FIN')
),


/* =====================================================================
   ======= BLOCO I (para Y e Y-1) - Contagem Geral dos Admitidos ======= */

AGG_I_ADM AS (
  SELECT PERIODO, ANO, NIVEL_KEY,
         COUNT(*) AS TOTAL,
         SUM(CASE WHEN SEXO='F' THEN 1 ELSE 0 END) AS FEM_QTDE,
         SUM(CASE WHEN SEXO='M' THEN 1 ELSE 0 END) AS MASC_QTDE
  FROM CLASSIF_B12_ADM
  GROUP BY PERIODO, ANO, NIVEL_KEY
),

GRID_I_ADM AS (
  SELECT p.PERIODO, p.ANO,
         n.ORDEM, n.NIVEL_KEY, n.NIVEL_DESC,
         NVL(a.FEM_QTDE,0) AS FEM_QTDE,
         ROUND(100*NVL(a.FEM_QTDE,0)/NULLIF(NVL(a.TOTAL,0),0),0) AS FEM_PCT,
         NVL(a.MASC_QTDE,0) AS MASC_QTDE,
         ROUND(100*NVL(a.MASC_QTDE,0)/NULLIF(NVL(a.TOTAL,0),0),0) AS MASC_PCT,
         NVL(a.TOTAL,0) AS TOTAL
  FROM PARAMS p
  CROSS JOIN NIVEIS n
  LEFT JOIN AGG_I_ADM a
    ON a.PERIODO=p.PERIODO AND a.ANO=p.ANO AND a.NIVEL_KEY=n.NIVEL_KEY
),

TOTAIS_I_ADM AS (
  SELECT
    PERIODO,
    ANO,
    COUNT(CASE WHEN SEXO='F' THEN 1 END) AS TOT_FEM_QTDE,
    ROUND(100 * COUNT(CASE WHEN SEXO='F' THEN 1 END) /
          NULLIF(COUNT(*),0),0) AS TOT_FEM_PCT,

    COUNT(CASE WHEN SEXO='M' THEN 1 END) AS TOT_MASC_QTDE,
    ROUND(100 * COUNT(CASE WHEN SEXO='M' THEN 1 END) /
          NULLIF(COUNT(*),0),0) AS TOT_MASC_PCT,

    COUNT(*) AS TOT_GERAL_QTDE,

    ROUND(100 * (
      COUNT(CASE WHEN SEXO='F' THEN 1 END) +
      COUNT(CASE WHEN SEXO='M' THEN 1 END)
    ) / NULLIF(COUNT(*),0),0) AS TOT_GERAL_PCT

  FROM CLASSIF_ADM
  WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
  GROUP BY PERIODO, ANO
),


/* ===========================================================================
   ========= BLOCO II (para Y e Y-1) - Apenas admitidos no Executivo ========= */

BLOCO2_BASE_ADM AS (
  SELECT * FROM GRID_I_ADM
   WHERE NIVEL_KEY IN ('CONSELHO_ADM','CONSELHO_FISC','DIR_ESTAT_VAR', 'DIR_ESTAT_FIN')
),

BLOCO2_TOTAIS_ADM AS (
  SELECT
    PERIODO,
    ANO,
    SUM(CASE WHEN SEXO = 'F' THEN 1 ELSE 0 END) AS B2_TOT_FEM_QTDE,
    ROUND(100 * SUM(CASE WHEN SEXO = 'F' THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 0) AS B2_TOT_FEM_PCT,
    SUM(CASE WHEN SEXO = 'M' THEN 1 ELSE 0 END) AS B2_TOT_MASC_QTDE,
    ROUND(100 * SUM(CASE WHEN SEXO = 'M' THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 0) AS B2_TOT_MASC_PCT,
    COUNT(*) AS B2_TOT_GERAL_QTDE,
    ROUND(100 * (
      SUM(CASE WHEN SEXO = 'F' THEN 1 ELSE 0 END) +
      SUM(CASE WHEN SEXO = 'M' THEN 1 ELSE 0 END)
    ) / NULLIF(COUNT(*),0), 0) AS B2_TOT_GERAL_PCT
  FROM CLASSIF_ADM
  WHERE NIVEL_KEY IN ('CONSELHO_ADM','CONSELHO_FISC','DIR_ESTAT_VAR','DIR_ESTAT_FIN')
    AND NIVEL_KEY <> 'DIR_ESTAT_FIN'
  GROUP BY PERIODO, ANO
),

BLOCO2_LINHAS_ADM AS (
  SELECT PERIODO, ANO, 1 AS B2_TARGET_ORDEM,
         NIVEL_DESC AS B2_NIVEL,
         FEM_QTDE AS B2_FEM_QTDE, FEM_PCT AS B2_FEM_PCT,
         MASC_QTDE AS B2_MASC_QTDE, MASC_PCT AS B2_MASC_PCT,
         TOTAL AS B2_TOTAL
    FROM BLOCO2_BASE_ADM WHERE NIVEL_KEY='CONSELHO_ADM'
  UNION ALL
  SELECT PERIODO, ANO, 2, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE_ADM WHERE NIVEL_KEY='CONSELHO_FISC'
  UNION ALL
  SELECT PERIODO, ANO, 3, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE_ADM WHERE NIVEL_KEY='DIR_ESTAT_VAR'
  UNION ALL
  SELECT PERIODO, ANO, 4, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE_ADM WHERE NIVEL_KEY='DIR_ESTAT_FIN'
),


/* ========================================================================
   ========= BLOCO III (para Y e Y-1) - Remuneração dos admitidos ========= */

BLOCO3_BASE_ADM AS (
  SELECT
    cl.PERIODO,
    cl.ANO,
    cl.NIVEL_KEY,
    cl.SEXO,
    NVL(rf.REMUN_FIXA,0) AS REMUN_FIXA
  FROM CLASSIF_ADM cl
  LEFT JOIN REMUN_FX_CONTRATO rf
    ON rf.PERIODO = cl.PERIODO
   AND rf.ANO     = cl.ANO
   AND rf.COD_CONTRATO = cl.COD_CONTRATO
),

BLOCO3_AGG_ADM AS (
  SELECT
    PERIODO,
    ANO,
    NIVEL_KEY,
    SUM(CASE WHEN SEXO='F' THEN 1 ELSE 0 END) AS FEM_QTDE,
    SUM(CASE WHEN SEXO='M' THEN 1 ELSE 0 END) AS MASC_QTDE,
    SUM(CASE WHEN SEXO = 'F' THEN REMUN_FIXA ELSE 0 END) AS FEM_VAL,
    SUM(CASE WHEN SEXO = 'M' THEN REMUN_FIXA ELSE 0 END) AS MASC_VAL,
    SUM(REMUN_FIXA) AS TOTAL_VAL
  FROM BLOCO3_BASE_ADM
  GROUP BY PERIODO, ANO, NIVEL_KEY
),

BLOCO3_GRID_ADM AS (
  SELECT
    PERIODO,
    ANO,
    NIVEL_KEY,
    FEM_QTDE,
    FEM_VAL,
    MASC_QTDE,
    MASC_VAL,
    (NVL(FEM_QTDE,0) + NVL(MASC_QTDE,0)) AS TOTAL_QTDE,
    TOTAL_VAL,
    ROUND(100 * FEM_VAL  / NULLIF(TOTAL_VAL,0), 2) AS B3_FEM_PCT,
    ROUND(100 * MASC_VAL / NULLIF(TOTAL_VAL,0), 2) AS B3_MASC_PCT
  FROM BLOCO3_AGG_ADM
),

/*BLOCO3_TOTAIS_ADM AS (
  SELECT
    r.PERIODO,
    r.ANO,
    r.B3_TOT_FEM_VAL,
    r.B3_TOT_MASC_VAL,
    r.B3_TOT_GERAL_VAL,
    q.B3_TOT_FEM_QTDE,
    q.B3_TOT_MASC_QTDE,
    q.B3_TOT_GERAL_QTDE
  FROM (
    SELECT
      PERIODO,
      ANO,
      SUM(FEM_VAL)   AS B3_TOT_FEM_VAL,
      SUM(MASC_VAL)  AS B3_TOT_MASC_VAL,
      SUM(TOTAL_VAL) AS B3_TOT_GERAL_VAL
    FROM BLOCO3_AGG_ADM
    WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
    GROUP BY PERIODO, ANO
  ) r
  JOIN (
    SELECT
      PERIODO,
      ANO,
      SUM(CASE WHEN SEXO = 'F' THEN 1 ELSE 0 END) AS B3_TOT_FEM_QTDE,
      SUM(CASE WHEN SEXO = 'M' THEN 1 ELSE 0 END) AS B3_TOT_MASC_QTDE,
      COUNT(*) AS B3_TOT_GERAL_QTDE
    FROM CLASSIF_ADM
    WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
    GROUP BY PERIODO, ANO
  ) q
    ON q.PERIODO = r.PERIODO
   AND q.ANO     = r.ANO
)
*/

BLOCO3_TOTAIS_ADM AS (
  SELECT
    PERIODO,
    ANO,
    SUM(FEM_QTDE)  AS B3_TOT_FEM_QTDE,
    SUM(MASC_QTDE) AS B3_TOT_MASC_QTDE,
    SUM(FEM_QTDE) + SUM(MASC_QTDE) AS B3_TOT_GERAL_QTDE,
    SUM(FEM_VAL)   AS B3_TOT_FEM_VAL,
    SUM(MASC_VAL)  AS B3_TOT_MASC_VAL,
    SUM(TOTAL_VAL) AS B3_TOT_GERAL_VAL
  FROM BLOCO3_AGG_ADM
  WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
  GROUP BY PERIODO, ANO
)


/* ======================================================
   ========= SELECT FINAL (Y-1 e Y lado a lado) ========= 
   ====================================================== */

SELECT
  '8, 282, 1629' AS "Cód. Empresa",
  '008 - Grazziotin S/A | 282 - Grazziotin Financeira S/A | 1629 - Floresta Grazziotin LTDA' as "Empresas Relacionadas",
  /* Identificação do ano anterior */
  a.ANO_Y1 AS "Ano Anterior",

  /* ========================
     == ANO ANTERIOR (Y-1) ==
     ======================== */

  /* BLOCO I (Ano Anterior) */
    /* Chave principal */
  n.NIVEL_DESC AS "Ant. | I - Nível de Cargo",
  g1.FEM_QTDE  AS "Ano Ant. | I - Fem (Qtd)",
  g1.FEM_PCT   AS "Ano Ant. | I - Fem (%)",
  g1.MASC_QTDE AS "Ano Ant. | I - Masc (Qtd)",
  g1.MASC_PCT  AS "Ano Ant. | I - Masc (%)",
  g1.TOTAL     AS "Ano Ant. | I - Total",

  /* Totais Bloco I (Ano Anterior) */
  t1.BTOT_FEM_QTDE   AS "Ano Ant. | I - TOT Fem (Qtd)",
  t1.BTOT_FEM_PCT    AS "Ano Ant. | I - TOT Fem (%)",
  t1.BTOT_MASC_QTDE  AS "Ano Ant. | I - TOT Masc (Qtd)",
  t1.BTOT_MASC_PCT   AS "Ano Ant. | I - TOT Masc (%)",
  t1.BTOT_GERAL_QTDE AS "Ano Ant. | I - TOT G (Qtd)",
  t1.BTOT_GERAL_PCT  AS "Ano Ant. | I - TOT G (%)",

  /* BLOCO II (Ano Anterior) - só aparece nas 3 linhas alvo */
  b21.B2_NIVEL     AS "Ano Ant. | II - Nível",
  b21.B2_FEM_QTDE  AS "Ano Ant. | II - Fem (Qtd)",
  b21.B2_FEM_PCT   AS "Ano Ant. | II - Fem (%)",
  b21.B2_MASC_QTDE AS "Ano Ant. | II - Masc (Qtd)",
  b21.B2_MASC_PCT  AS "Ano Ant. | II - Masc (%)",
  b21.B2_TOTAL     AS "Ano Ant. | II - Total",

  /* Totais Bloco II (Ano Anterior) - só preenche onde Bloco II aparece */
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_FEM_QTDE  END AS "Ano Ant. | II - TOT Fem (Qtd)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_FEM_PCT   END AS "Ano Ant. | II - TOT Fem (%)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_MASC_QTDE END AS "Ano Ant. | II - TOT Masc (Qtd)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_MASC_PCT  END AS "Ano Ant. | II - TOT Masc (%)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_GERAL_QTDE END AS "Ano Ant. | II - TOT G (Qtd)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_GERAL_PCT  END AS "Ano Ant. | II - TOT G (%)",
    
  
  /* BLOCO III (Ano Anterior) */
  n.NIVEL_DESC AS "Ant. | III - Nível de Cargo",
  b31.FEM_QTDE  AS "Ano Ant. | III - Fem(Qtd)",
  TO_CHAR(NVL( b31.FEM_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III - R. Fem(V)",
  b31.B3_FEM_PCT   AS "Ano Ant. | III - R. Fem(%)",
  
  b31.MASC_QTDE AS "Ano Ant. | III - Masc(Qtd)",
  TO_CHAR(NVL(b31.MASC_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III - R. Masc(V)",
  b31.B3_MASC_PCT  AS "Ano Ant. | III - R. Masc(%)",
  
  b31.TOTAL_QTDE AS "Ano Ant. | III - Total(Qtd)",
  TO_CHAR(NVL(b31.TOTAL_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III - R. Total(V)",

  /* Totais Bloco III (Ano Anterior) */  
  
  t31.B3_TOT_FEM_QTDE   AS "Ano Ant. | III - TOT F(Qtd)",
  TO_CHAR(NVL(t31.B3_TOT_FEM_VAL, 0),   'FM999G999G990D00') AS "Ano Ant. | III - TOT Fem(V)",
  ROUND(100 * t31.B3_TOT_FEM_VAL  / NULLIF(t31.B3_TOT_GERAL_VAL,0), 2) AS "Ano Ant. | III - TOT Fem(%)",
  
  t31.B3_TOT_MASC_QTDE  AS "Ano Ant. | III - TOT M(Qtd)",
  TO_CHAR(NVL(t31.B3_TOT_MASC_VAL, 0),  'FM999G999G990D00') AS "Ano Ant. | III - TOT Masc(V)",
  ROUND(100 * t31.B3_TOT_MASC_VAL / NULLIF(t31.B3_TOT_GERAL_VAL,0), 2) AS "Ano Ant. | III - TOT Masc(%)",
  
  t31.B3_TOT_GERAL_QTDE AS "Ano Ant. | III - TOT G(Qtd)",
  TO_CHAR(NVL(t31.B3_TOT_GERAL_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III - TOT G(V)",
  ROUND(100 * (t31.B3_TOT_FEM_VAL + t31.B3_TOT_MASC_VAL) / NULLIF(t31.B3_TOT_GERAL_VAL,0), 2) AS "Ano Ant. | III - TOT G(%)",  
  
  /* BLOCO III (Ano Anterior) */
/*  n.NIVEL_DESC AS "Ant. | III - Nível de Cargo",
  TO_CHAR(NVL(b31.FEM_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III - R. Fem (V)",
  b31.B3_FEM_PCT AS "Ano Ant. | III - R. Fem (%)",
  TO_CHAR(NVL(b31.MASC_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III - R. Masc (V)",
  b31.B3_MASC_PCT AS "Ano Ant. | III - R. Masc (%)",
  TO_CHAR(NVL(b31.TOTAL_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III - R. Total (V)",*/

  /* Totais Bloco III (Ano Anterior) */
/*  ROUND(
    100 * (t31.B3_TOT_FEM_VAL / NULLIF(t31.B3_TOT_FEM_QTDE, 0))
        / NULLIF((t31.B3_TOT_GERAL_VAL / NULLIF(t31.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Ant. | III - TOT Fem (%)",

  ROUND(
    100 * (t31.B3_TOT_MASC_VAL / NULLIF(t31.B3_TOT_MASC_QTDE, 0))
        / NULLIF((t31.B3_TOT_GERAL_VAL / NULLIF(t31.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Ant. | III - TOT Masc (%)",

  ROUND(
    100 * ((t31.B3_TOT_FEM_VAL + t31.B3_TOT_MASC_VAL) / NULLIF(t31.B3_TOT_GERAL_QTDE, 0))
        / NULLIF((t31.B3_TOT_GERAL_VAL / NULLIF(t31.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Ant. | III - TOT G (%)",*/


  /* =========================
     ===== ANO ATUAL (Y) =====
     ========================= */
  /* Identificação do ano antual */
  a.ANO_Y  AS "Ano Atual",

  /* BLOCO I (Ano Atual) */
  n.NIVEL_DESC AS "Atu. | I - Nível de Cargo",
  gy.FEM_QTDE  AS "Ano Atu. | I - Fem (Qtd)",
  gy.FEM_PCT   AS "Ano Atu. | I - Fem (%)",
  gy.MASC_QTDE AS "Ano Atu. | I - Masc (Qtd)",
  gy.MASC_PCT  AS "Ano Atu. | I - Masc (%)",
  gy.TOTAL     AS "Ano Atu. | I - Total",

  /* Totais Bloco I (Ano Atual) */
  ty.BTOT_FEM_QTDE   AS "Ano Atu. | I - TOT Fem (Qtd)",
  ty.BTOT_FEM_PCT    AS "Ano Atu. | I - TOT Fem (%)",
  ty.BTOT_MASC_QTDE  AS "Ano Atu. | I - TOT Masc (Qtd)",
  ty.BTOT_MASC_PCT   AS "Ano Atu. | I - TOT Masc (%)",
  ty.BTOT_GERAL_QTDE AS "Ano Atu. | I - TOT G (Qtd)",
  ty.BTOT_GERAL_PCT  AS "Ano Atu. | I - TOT G (%)",

  /* BLOCO II (Ano Atual) */
  b2y.B2_NIVEL     AS "Ano Atu. | II - Nível",
  b2y.B2_FEM_QTDE  AS "Ano Atu. | II - Fem (Qtd)",
  b2y.B2_FEM_PCT   AS "Ano Atu. | II - Fem (%)",
  b2y.B2_MASC_QTDE AS "Ano Atu. | II - Masc (Qtd)",
  b2y.B2_MASC_PCT  AS "Ano Atu. | II - Masc (%)",
  b2y.B2_TOTAL     AS "Ano Atu. | II - Total",

  /* Totais Bloco II (Ano Atual) */
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_FEM_QTDE  END AS "Ano Atu. | II - TOT Fem (Qtd)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_FEM_PCT   END AS "Ano Atu. | II - TOT Fem (%)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_MASC_QTDE END AS "Ano Atu. | II - TOT Masc (Qtd)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_MASC_PCT  END AS "Ano Atu. | II - TOT Masc (%)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_GERAL_QTDE END AS "Ano Atu. | II - TOT G (Qtd)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_GERAL_PCT  END AS "Ano Atu. | II - TOT G (%)",
    
  
    /* BLOCO III (Ano Atu.) */
  n.NIVEL_DESC AS "Atu.| III - Nível de Cargo",
  b3y.FEM_QTDE  AS "Ano Atu. | III - Fem(Qtd)",
  TO_CHAR(NVL(b3y.FEM_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III - R. Fem(V)",
  b3y.B3_FEM_PCT   AS "Ano Atu. | III - R. Fem(%)",
  
  b3y.MASC_QTDE AS "Ano Atu. | III - Masc(Qtd)",
  TO_CHAR(NVL(b3y.MASC_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III - R. Masc(V)",
  b3y.B3_MASC_PCT  AS "Ano Atu. | III - R. Masc(%)",
  
  b3y.TOTAL_QTDE AS "Ano Atu. | III - Total(Qtd)",
  TO_CHAR(NVL(b3y.TOTAL_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III - R. Total(V)",

  /* Totais Bloco III (Ano Atual) */
  t3y.B3_TOT_FEM_QTDE   AS "Ano Atu. | III - TOT F(Qtd)",  
  TO_CHAR(NVL(t3y.B3_TOT_FEM_VAL, 0),   'FM999G999G990D00') AS "Ano Atu. | III - TOT Fem(V)",
  ROUND(100 * t3y.B3_TOT_FEM_VAL  / NULLIF(t3y.B3_TOT_GERAL_VAL,0), 2) AS "Ano Atu. | III - TOT Fem(%)",
  
  t3y.B3_TOT_MASC_QTDE  AS "Ano Atu. | III - TOT M(Qtd)",
  TO_CHAR(NVL(t3y.B3_TOT_MASC_VAL, 0),  'FM999G999G990D00') AS "Ano Atu. | III - TOT Masc(V)",
  ROUND(100 * t3y.B3_TOT_MASC_VAL / NULLIF(t3y.B3_TOT_GERAL_VAL,0), 2) AS "Ano Atu. | III - TOT Masc(%)",  
  
  t3y.B3_TOT_GERAL_QTDE AS "Ano Atu. | III - TOT G(Qtd)",
  TO_CHAR(NVL(t3y.B3_TOT_GERAL_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III - TOT G(V)",
  ROUND(100 * (t3y.B3_TOT_FEM_VAL + t3y.B3_TOT_MASC_VAL) / NULLIF(t3y.B3_TOT_GERAL_VAL,0), 2) AS "Ano Atu. | III - TOT G(%)",

  /* BLOCO III (Ano Atu.) */
/*  n.NIVEL_DESC AS "Atu.| III - Nível de Cargo",
  TO_CHAR(NVL(b3y.FEM_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III - R. Fem (V)",
  b3y.B3_FEM_PCT AS "Ano Atu. | III - R. Fem (%)",
  TO_CHAR(NVL(b3y.MASC_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III - R. Masc (V)",
  b3y.B3_MASC_PCT AS "Ano Atu. | III - R. Masc (%)",
  TO_CHAR(NVL(b3y.TOTAL_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III - R. Total (V)",*/

  /* Totais Bloco III (Ano Atual) */
/*  ROUND(
    100 * (t3y.B3_TOT_FEM_VAL / NULLIF(t3y.B3_TOT_FEM_QTDE, 0))
        / NULLIF((t3y.B3_TOT_GERAL_VAL / NULLIF(t3y.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Atu. | III - TOT Fem (%)",

  ROUND(
    100 * (t3y.B3_TOT_MASC_VAL / NULLIF(t3y.B3_TOT_MASC_QTDE, 0))
        / NULLIF((t3y.B3_TOT_GERAL_VAL / NULLIF(t3y.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Atu. | III - TOT Masc (%)",

  ROUND(
    100 * ((t3y.B3_TOT_FEM_VAL + t3y.B3_TOT_MASC_VAL) / NULLIF(t3y.B3_TOT_GERAL_QTDE, 0))
        / NULLIF((t3y.B3_TOT_GERAL_VAL / NULLIF(t3y.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Atu. | III - TOT G (%)",*/
    
    
   /* ==============================================================
      ============= COLUNAS BLOCO ADMITIDOS (Y-1 e Y) ============== */
  
  a.ANO_Y1 AS "Ano Anterior",     
  /* BLOCO I (Ano Anterior) - Admitidos */
  g1a.NIVEL_DESC AS "Ant. | I - Nível de Cargo",
  g1a.FEM_QTDE  AS "Ano Ant. | I (Adm) - F(Qtd)",
  g1a.FEM_PCT   AS "Ano Ant. | I (Adm) - F(%)",
  g1a.MASC_QTDE AS "Ano Ant. | I (Adm) - M(Qtd)",
  g1a.MASC_PCT  AS "Ano Ant. | I (Adm) - M(%)",
  g1a.TOTAL     AS "Ano Ant. | I (Adm) - Total",

  /* Totais Bloco I (Ano Anterior) - Admitidos */
  t1a.BTOT_FEM_QTDE   AS "Ano Ant. | I (Adm) - T F(Qtd)",
  t1a.BTOT_FEM_PCT    AS "Ano Ant. | I (Adm) - T F(%)",
  t1a.BTOT_MASC_QTDE  AS "Ano Ant. | I (Adm) - T M(Qtd)",
  t1a.BTOT_MASC_PCT   AS "Ano Ant. | I (Adm) - T M(%)",
  t1a.BTOT_GERAL_QTDE AS "Ano Ant. | I (Adm) - T G(Qtd)",
  t1a.BTOT_GERAL_PCT  AS "Ano Ant. | I (Adm) - T G(%)",
  
    /* Bloco II (Ano Anterior) - Admitidos */
  b21a.B2_NIVEL     AS "Ano Ant. | II (Adm) - Nível",
  b21a.B2_FEM_QTDE  AS "Ano Ant. | II (Adm) - F(Qtd)",
  b21a.B2_FEM_PCT   AS "Ano Ant. | II (Adm) - F(%)",
  b21a.B2_MASC_QTDE AS "Ano Ant. | II (Adm) - M(Qtd)",
  b21a.B2_MASC_PCT  AS "Ano Ant. | II (Adm) - M(%)",
  b21a.B2_TOTAL     AS "Ano Ant. | II (Adm) - Total",
  
  /* Totais Bloco II (Ano Anterior) - Admitidos */
  CASE WHEN b21a.B2_NIVEL IS NOT NULL THEN bt1a.B2_TOT_FEM_QTDE END AS "Ano Ant. | II (Adm) - T F(Qtd)",
  CASE WHEN b21a.B2_NIVEL IS NOT NULL THEN bt1a.B2_TOT_FEM_PCT  END AS "Ano Ant. | II (Adm) - T F(%)",
  CASE WHEN b21a.B2_NIVEL IS NOT NULL THEN bt1a.B2_TOT_MASC_QTDE END AS "Ano Ant. | II (Adm) - T M(Qtd)",
  CASE WHEN b21a.B2_NIVEL IS NOT NULL THEN bt1a.B2_TOT_MASC_PCT  END AS "Ano Ant. | II (Adm) - T M(%)",
  CASE WHEN b21a.B2_NIVEL IS NOT NULL THEN bt1a.B2_TOT_GERAL_QTDE END AS "Ano Ant. | II (Adm) - T G(Qtd)",
  CASE WHEN b21a.B2_NIVEL IS NOT NULL THEN bt1a.B2_TOT_GERAL_PCT  END AS "Ano Ant. | II (Adm) - T G(%)",
    
  
    /* Bloco III (Ano Anterior) - Admitidos */
  n.NIVEL_DESC     AS "Atu.| III - Nível de Cargo",
  b31a.FEM_QTDE  AS "Ano Ant. | III (Adm) - F(Qtd)",
  TO_CHAR(NVL(b31a.FEM_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III (Adm) - R.F(V)",
  b31a.B3_FEM_PCT   AS "Ano Ant. | III (Adm) - R.F(%)",
  
  b31a.MASC_QTDE AS "Ano Ant. | III (Adm) - M(Qtd)",
  TO_CHAR(NVL(b31a.MASC_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III (Adm) - R.M(V)",
  b31a.B3_MASC_PCT  AS "Ano Ant. | III (Adm) - R.M(%)",
  
  b31a.TOTAL_QTDE AS "Ano Ant. | III (Adm) - T(Qtd)",
  TO_CHAR(NVL(b31a.TOTAL_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III (Adm) - R.T(V)",
  
  /* Totais Bloco III (Ano Anterior) - Admitidos */
  t31a.B3_TOT_FEM_QTDE   AS "Ano Ant. | III (Adm) - TF(Qtd)",
  TO_CHAR(NVL(t31a.B3_TOT_FEM_VAL, 0),   'FM999G999G990D00') AS "Ano Ant. | III (Adm) - TF(V)",
  ROUND(100 * t31a.B3_TOT_FEM_VAL  / NULLIF(t31a.B3_TOT_GERAL_VAL,0), 2) AS "Ano Ant. | III (Adm) - TF(%)",
  
  t31a.B3_TOT_MASC_QTDE  AS "Ano Ant. | III (Adm) - TM(Qtd)",
  TO_CHAR(NVL(t31a.B3_TOT_MASC_VAL, 0),  'FM999G999G990D00') AS "Ano Ant. | III (Adm) - TM(V)",
  ROUND(100 * t31a.B3_TOT_MASC_VAL / NULLIF(t31a.B3_TOT_GERAL_VAL,0), 2) AS "Ano Ant. | III (Adm) - TM(%)",
  
  t31a.B3_TOT_GERAL_QTDE AS "Ano Ant. | III (Adm) - TG(Qtd)",
  TO_CHAR(NVL(t31a.B3_TOT_GERAL_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III (Adm) - TG(V)",
  ROUND(100 * (t31a.B3_TOT_FEM_VAL + t31a.B3_TOT_MASC_VAL) / NULLIF(t31a.B3_TOT_GERAL_VAL,0), 2) AS "Ano Ant. | III (Adm) - TG(%)",  

  /* Bloco III (Ano Anterior) - Admitidos */
/*  n.NIVEL_DESC AS "Atu.| III - Nível de Cargo",
  TO_CHAR(NVL(b31a.FEM_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III (Adm) - R. F(V)",
  b31a.B3_FEM_PCT AS "Ano Ant. | III (Adm) - R. F(%)",
  TO_CHAR(NVL(b31a.MASC_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III (Adm) - R. M(V)",
  b31a.B3_MASC_PCT AS "Ano Ant. | III (Adm) - R. M(%)",
  TO_CHAR(NVL(b31a.TOTAL_VAL, 0), 'FM999G999G990D00') AS "Ano Ant. | III (Adm) - R. T(V)",*/
  
  /* Totais Bloco III (Ano Anterior) - Admitidos */
  /*ROUND(
    100 * (t31a.B3_TOT_FEM_VAL / NULLIF(t31a.B3_TOT_FEM_QTDE, 0))
        / NULLIF((t31a.B3_TOT_GERAL_VAL / NULLIF(t31a.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Ant. | III (Adm) - T F(%)",

  ROUND(
    100 * (t31a.B3_TOT_MASC_VAL / NULLIF(t31a.B3_TOT_MASC_QTDE, 0))
        / NULLIF((t31a.B3_TOT_GERAL_VAL / NULLIF(t31a.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Ant. | III (Adm) - T M(%)",

  ROUND(
    100 * ((t31a.B3_TOT_FEM_VAL + t31a.B3_TOT_MASC_VAL) / NULLIF(t31a.B3_TOT_GERAL_QTDE, 0))
        / NULLIF((t31a.B3_TOT_GERAL_VAL / NULLIF(t31a.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Ant. | III (Adm) - T G(%)",*/
  
  /*======= ANO ATUAL =======*/
  
  a.ANO_Y  AS "Ano Atual",
  /* BLOCO I (Ano Atual) - Admitidos */
  g1a.NIVEL_DESC AS "Atu. | I - Nível de Cargo",
  gya.FEM_QTDE  AS "Ano Atu. | I (Adm) - F(Qtd)",
  gya.FEM_PCT   AS "Ano Atu. | I (Adm) - F(%)",
  gya.MASC_QTDE AS "Ano Atu. | I (Adm) - M(Qtd)",
  gya.MASC_PCT  AS "Ano Atu. | I (Adm) - M(%)",
  gya.TOTAL     AS "Ano Atu. | I (Adm) - Total",

  /* Totais Bloco I (Ano Atual) - Admitidos */
  tya.BTOT_FEM_QTDE   AS "Ano Atu. | I (Adm) - T F(Qtd)",
  tya.BTOT_FEM_PCT    AS "Ano Atu. | I (Adm) - T F(%)",
  tya.BTOT_MASC_QTDE  AS "Ano Atu. | I (Adm) - T M(Qtd)",
  tya.BTOT_MASC_PCT   AS "Ano Atu. | I (Adm) - T M(%)",
  tya.BTOT_GERAL_QTDE AS "Ano Atu. | I (Adm) - T G(Qtd)",
  tya.BTOT_GERAL_PCT  AS "Ano Atu. | I (Adm) - T G(%)",
  
  /* Bloco II (Ano Atual) - Admitidos */
  b2ya.B2_NIVEL     AS "Ano Atu. | II (Adm) - Nível",
  b2ya.B2_FEM_QTDE  AS "Ano Atu. | II (Adm) - F(Qtd)",
  b2ya.B2_FEM_PCT   AS "Ano Atu. | II (Adm) - F(%)",
  b2ya.B2_MASC_QTDE AS "Ano Atu. | II (Adm) - M(Qtd)",
  b2ya.B2_MASC_PCT  AS "Ano Atu. | II (Adm) - M(%)",
  b2ya.B2_TOTAL     AS "Ano Atu. | II (Adm) - Total",
  
  /* Totais Bloco II (Ano Atual) - Admitidos */
  CASE WHEN b2ya.B2_NIVEL IS NOT NULL THEN btya.B2_TOT_FEM_QTDE END AS "Ano Atu. | II (Adm) - T F(Qtd)",
  CASE WHEN b2ya.B2_NIVEL IS NOT NULL THEN btya.B2_TOT_FEM_PCT  END AS "Ano Atu. | II (Adm) - T F(%)",
  CASE WHEN b2ya.B2_NIVEL IS NOT NULL THEN btya.B2_TOT_MASC_QTDE END AS "Ano Atu. | II (Adm) - T M(Qtd)",
  CASE WHEN b2ya.B2_NIVEL IS NOT NULL THEN btya.B2_TOT_MASC_PCT  END AS "Ano Atu. | II (Adm) - T M(%)",
  CASE WHEN b2ya.B2_NIVEL IS NOT NULL THEN btya.B2_TOT_GERAL_QTDE END AS "Ano Atu. | II (Adm) - T G(Qtd)",
  CASE WHEN b2ya.B2_NIVEL IS NOT NULL THEN btya.B2_TOT_GERAL_PCT  END AS "Ano Atu. | II (Adm) - T G(%)",  
  
    /* Bloco III (Ano Atual) - Admitidos */
  n.NIVEL_DESC AS "Atu.| III - Nível de Cargo",
  b3ya.FEM_QTDE  AS "Ano Atu. | III (Adm) - F(Qtd)",
  TO_CHAR(NVL(b3ya.FEM_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III (Adm) - R. F(V)",
  b3ya.B3_FEM_PCT   AS "Ano Atu. | III (Adm) - R. F(%)",
  
  b3ya.MASC_QTDE AS "Ano Atu. | III (Adm) - M(Qtd)",
  TO_CHAR(NVL(b3ya.MASC_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III (Adm) - R. M(V)",
  b3ya.B3_MASC_PCT  AS "Ano Atu. | III (Adm) - R. M(%)",
  
  b3ya.TOTAL_QTDE AS "Ano Atu. | III (Adm) - T(Qtd)",
  TO_CHAR(NVL(b3ya.TOTAL_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III (Adm) - R. T(V)",

  /* Totais Bloco III (Ano Atual) - Admitidos */
  t3ya.B3_TOT_FEM_QTDE   AS "Ano Atu. | III (Adm) - TF(Qtd)",
  TO_CHAR(NVL(t3ya.B3_TOT_FEM_VAL, 0),   'FM999G999G990D00') AS "Ano Atu. | III (Adm) - TF(V)",
  ROUND(100 * t3ya.B3_TOT_FEM_VAL  / NULLIF(t3ya.B3_TOT_GERAL_VAL,0), 2) AS "Ano Atu. | III (Adm) - TF(%)",
  
  t3ya.B3_TOT_MASC_QTDE  AS "Ano Atu. | III (Adm) - TM(Qtd)",
  TO_CHAR(NVL(t3ya.B3_TOT_MASC_VAL, 0),  'FM999G999G990D00') AS "Ano Atu. | III (Adm) - TM(V)",
  ROUND(100 * t3ya.B3_TOT_MASC_VAL / NULLIF(t3ya.B3_TOT_GERAL_VAL,0), 2) AS "Ano Atu. | III (Adm) - TM(%)",
  
  t3ya.B3_TOT_GERAL_QTDE AS "Ano Atu. | III (Adm) - TG(Qtd)",
  TO_CHAR(NVL(t3ya.B3_TOT_GERAL_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III (Adm) - TG(V)",
  ROUND(100 * (t3ya.B3_TOT_FEM_VAL + t3ya.B3_TOT_MASC_VAL) / NULLIF(t3ya.B3_TOT_GERAL_VAL,0), 2) AS "Ano Atu. | III (Adm) - TG(%)"

  /* Bloco III (Ano Atual) - Admitidos */
/*  n.NIVEL_DESC AS "Atu.| III - Nível de Cargo",
  TO_CHAR(NVL(b3ya.FEM_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III (Adm) - R. F(V)",
  b3ya.B3_FEM_PCT AS "Ano Atu. | III (Adm) - R. F(%)",
  TO_CHAR(NVL(b3ya.MASC_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III (Adm) - R. M(V)",
  b3ya.B3_MASC_PCT AS "Ano Atu. | III (Adm) - R. M(%)",
  TO_CHAR(NVL(b3ya.TOTAL_VAL, 0), 'FM999G999G990D00') AS "Ano Atu. | III (Adm) - R. T(V)",*/

  /* Totais Bloco III (Ano Atual) - Admitidos */
/*  ROUND(
    100 * (t3ya.B3_TOT_FEM_VAL / NULLIF(t3ya.B3_TOT_FEM_QTDE, 0))
        / NULLIF((t3ya.B3_TOT_GERAL_VAL / NULLIF(t3ya.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Atu. | III (Adm) - T F(%)",

  ROUND(
    100 * (t3ya.B3_TOT_MASC_VAL / NULLIF(t3ya.B3_TOT_MASC_QTDE, 0))
        / NULLIF((t3ya.B3_TOT_GERAL_VAL / NULLIF(t3ya.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Atu. | III (Adm) - T M(%)",

  ROUND(
    100 * ((t3ya.B3_TOT_FEM_VAL + t3ya.B3_TOT_MASC_VAL) / NULLIF(t3ya.B3_TOT_GERAL_QTDE, 0))
        / NULLIF((t3ya.B3_TOT_GERAL_VAL / NULLIF(t3ya.B3_TOT_GERAL_QTDE, 0)), 0)
  , 2) AS "Ano Atu. | III (Adm) - T G(%)"*/

FROM NIVEIS n
CROSS JOIN PARAMS_BASE pb
CROSS JOIN ANOS a

LEFT JOIN GRID_I g1
  ON g1.NIVEL_KEY = n.NIVEL_KEY AND g1.PERIODO='Y-1'
LEFT JOIN GRID_I gy
  ON gy.NIVEL_KEY = n.NIVEL_KEY AND gy.PERIODO='Y'

LEFT JOIN (
  SELECT PERIODO,
         TOT_FEM_QTDE   AS BTOT_FEM_QTDE,
         TOT_FEM_PCT    AS BTOT_FEM_PCT,
         TOT_MASC_QTDE  AS BTOT_MASC_QTDE,
         TOT_MASC_PCT   AS BTOT_MASC_PCT,
         TOT_GERAL_QTDE AS BTOT_GERAL_QTDE,
         TOT_GERAL_PCT  AS BTOT_GERAL_PCT
    FROM TOTAIS_I
) t1
  ON t1.PERIODO='Y-1'
LEFT JOIN (
  SELECT PERIODO,
         TOT_FEM_QTDE   AS BTOT_FEM_QTDE,
         TOT_FEM_PCT    AS BTOT_FEM_PCT,
         TOT_MASC_QTDE  AS BTOT_MASC_QTDE,
         TOT_MASC_PCT   AS BTOT_MASC_PCT,
         TOT_GERAL_QTDE AS BTOT_GERAL_QTDE,
         TOT_GERAL_PCT  AS BTOT_GERAL_PCT
    FROM TOTAIS_I
) ty
  ON ty.PERIODO='Y'

LEFT JOIN BLOCO2_LINHAS b21
  ON b21.PERIODO='Y-1' AND b21.B2_TARGET_ORDEM = n.ORDEM
LEFT JOIN BLOCO2_LINHAS b2y
  ON b2y.PERIODO='Y' AND b2y.B2_TARGET_ORDEM = n.ORDEM

LEFT JOIN BLOCO2_TOTAIS bt1
  ON bt1.PERIODO='Y-1'
LEFT JOIN BLOCO2_TOTAIS bty
  ON bty.PERIODO='Y'

LEFT JOIN BLOCO3_GRID b31
  ON b31.PERIODO='Y-1' AND b31.NIVEL_KEY = n.NIVEL_KEY
LEFT JOIN BLOCO3_GRID b3y
  ON b3y.PERIODO='Y' AND b3y.NIVEL_KEY = n.NIVEL_KEY

LEFT JOIN BLOCO3_TOTAIS t31
  ON t31.PERIODO='Y-1'
LEFT JOIN BLOCO3_TOTAIS t3y
  ON t3y.PERIODO='Y'
  

/* ====== JOINS BLOCO ADMITIDOS (Y-1 e Y) ====== */

/* BLOCO I - Admitidos */
LEFT JOIN GRID_I_ADM g1a
  ON g1a.NIVEL_KEY = n.NIVEL_KEY AND g1a.PERIODO = 'Y-1'
LEFT JOIN GRID_I_ADM gya
  ON gya.NIVEL_KEY = n.NIVEL_KEY AND gya.PERIODO = 'Y'

LEFT JOIN (
  SELECT PERIODO,
         TOT_FEM_QTDE   AS BTOT_FEM_QTDE,
         TOT_FEM_PCT    AS BTOT_FEM_PCT,
         TOT_MASC_QTDE  AS BTOT_MASC_QTDE,
         TOT_MASC_PCT   AS BTOT_MASC_PCT,
         TOT_GERAL_QTDE AS BTOT_GERAL_QTDE,
         TOT_GERAL_PCT  AS BTOT_GERAL_PCT
    FROM TOTAIS_I_ADM
) t1a
  ON t1a.PERIODO = 'Y-1'
LEFT JOIN (
  SELECT PERIODO,
         TOT_FEM_QTDE   AS BTOT_FEM_QTDE,
         TOT_FEM_PCT    AS BTOT_FEM_PCT,
         TOT_MASC_QTDE  AS BTOT_MASC_QTDE,
         TOT_MASC_PCT   AS BTOT_MASC_PCT,
         TOT_GERAL_QTDE AS BTOT_GERAL_QTDE,
         TOT_GERAL_PCT  AS BTOT_GERAL_PCT
    FROM TOTAIS_I_ADM
) tya
  ON tya.PERIODO = 'Y'

/* BLOCO II - Admitidos */
LEFT JOIN BLOCO2_LINHAS_ADM b21a
  ON b21a.PERIODO = 'Y-1' AND b21a.B2_TARGET_ORDEM = n.ORDEM
LEFT JOIN BLOCO2_LINHAS_ADM b2ya
  ON b2ya.PERIODO = 'Y' AND b2ya.B2_TARGET_ORDEM = n.ORDEM

LEFT JOIN BLOCO2_TOTAIS_ADM bt1a
  ON bt1a.PERIODO = 'Y-1'
LEFT JOIN BLOCO2_TOTAIS_ADM btya
  ON btya.PERIODO = 'Y'

/* BLOCO III - Admitidos */
LEFT JOIN BLOCO3_GRID_ADM b31a
  ON b31a.PERIODO='Y-1' AND b31a.NIVEL_KEY = n.NIVEL_KEY
LEFT JOIN BLOCO3_GRID_ADM b3ya
  ON b3ya.PERIODO='Y' AND b3ya.NIVEL_KEY = n.NIVEL_KEY

LEFT JOIN BLOCO3_TOTAIS_ADM t31a
  ON t31a.PERIODO='Y-1'
LEFT JOIN BLOCO3_TOTAIS_ADM t3ya
  ON t3ya.PERIODO='Y'

ORDER BY n.ORDEM



