WITH
-- CTE para obter contratos totais de todas as redes e empresas
CONTRATOS_TOTAIS AS (
    SELECT
        D.COD_REDE_LOCAL AS IDENTIFICADOR,  -- Usando a coluna COD_REDE_LOCAL como identificador
        MAX(D.DES_REDE_LOCAL) AS DESCRICAO,
        COUNT(DISTINCT D.COD_CONTRATO) AS QTDE_TOTAL_CONTRATOS
    FROM
        V_DADOS_PESSOA_ALTER_AVT D
    WHERE
        D.EDICAO_EMP = '008'
        AND D.COD_REDE_LOCAL IN ('10', '30', '40', '50', '70', '001', '013')
    GROUP BY
        D.COD_REDE_LOCAL

    UNION ALL

    SELECT
        D.EDICAO_EMP AS IDENTIFICADOR,  -- Usando a coluna EDICAO_EMP como identificador
        MAX(D.DES_EMPRESA) AS DESCRICAO,
        COUNT(DISTINCT D.COD_CONTRATO) AS QTDE_TOTAL_CONTRATOS
    FROM
        V_DADOS_PESSOA_ALTER_AVT D
    WHERE
        D.COD_EMP = '008'
    GROUP BY
        D.EDICAO_EMP
),

-- CTE para obter absenteísmo consolidado de todas as redes e empresas
ABSENTEISMO AS (
    SELECT
        D.COD_REDE_LOCAL AS IDENTIFICADOR,  -- Usando a coluna COD_REDE_LOCAL como identificador
        B.DATA_REFERENCIA,
        COUNT(DISTINCT A.COD_CONTRATO) AS QTDE_CONTRATOS_ABS,
        SUM(CASE WHEN A.COD_VD IN (631, 632, 831, 832) THEN A.QTDE_VD ELSE 0 END) AS TOTAL_FALTAS,
        SUM(CASE WHEN A.COD_VD = 897 THEN A.QTDE_VD ELSE 0 END) AS TOTAL_ATESTADOS,
        'REDE_LOCAL' AS TIPO_IDENTIFICADOR
    FROM
        RHFP1006 A
    LEFT JOIN
        V_DADOS_PESSOA_ALTER_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO
    INNER JOIN
        RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    WHERE
        D.COD_EMP = '008'
        AND D.COD_REDE_LOCAL IN ('10', '30', '40', '50', '70', '001', '013')
        AND B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
        AND A.COD_VD IN (631, 632, 831, 832, 897)
    GROUP BY
        D.COD_REDE_LOCAL, B.DATA_REFERENCIA

    UNION ALL

    SELECT
        D.EDICAO_EMP AS IDENTIFICADOR,  -- Usando a coluna EDICAO_EMP como identificador
        B.DATA_REFERENCIA,
        COUNT(DISTINCT A.COD_CONTRATO) AS QTDE_CONTRATOS_ABS,
        SUM(CASE WHEN A.COD_VD IN (631, 632, 831, 832) THEN A.QTDE_VD ELSE 0 END) AS TOTAL_FALTAS,
        SUM(CASE WHEN A.COD_VD = 897 THEN A.QTDE_VD ELSE 0 END) AS TOTAL_ATESTADOS,
        'EMPRESA' AS TIPO_IDENTIFICADOR
    FROM
        RHFP1006 A
    LEFT JOIN
        V_DADOS_PESSOA_ALTER_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO
    INNER JOIN
        RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    WHERE
        D.COD_EMP = '008'
        AND B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
        AND A.COD_VD IN (631, 632, 831, 832, 897)
    GROUP BY
        D.EDICAO_EMP, B.DATA_REFERENCIA
),

-- Lista de datas de referência para evitar a multiplicação de registros
DATAS AS (
    SELECT DISTINCT DATA_REFERENCIA
    FROM ABSENTEISMO
)

-- Consulta final
SELECT
    REPLACE(TRIM(TO_CHAR(D.DATA_REFERENCIA, 'Month/YYYY', 'NLS_DATE_LANGUAGE=PORTUGUESE')), ' ', '') AS REFERENCIA,  -- Removendo espaços na referência
    CASE
        WHEN D.DATA_REFERENCIA != LAST_DAY(D.DATA_REFERENCIA)
        THEN D.DATA_REFERENCIA
        ELSE NULL
    END AS DTA_REF,

    -- Identificador genérico e descrição (pode ser rede local ou empresa)
    COALESCE(CT.IDENTIFICADOR, 'N/A') || ' - ' || COALESCE(CT.DESCRICAO, 'N/A') AS DESCRICAO,

    -- Dados de contratos
    COALESCE(CT.QTDE_TOTAL_CONTRATOS, 0) AS CONTRATOS_ATUAIS,
    COALESCE(AR.QTDE_CONTRATOS_ABS, 0) AS CONTRATOS_ABS,
    TO_CHAR(COALESCE(AR.TOTAL_FALTAS, 0), 'FM999G999G990D00') AS FALTAS,
    TO_CHAR(COALESCE(AR.TOTAL_ATESTADOS, 0), 'FM999G999G990D00') AS ATESTADOS,

    'Período informado: ' || TO_CHAR(:DATA_INICIO, 'DD/MM/YYYY') || ' à ' || TO_CHAR(:DATA_FIM, 'DD/MM/YYYY') AS PERIODO

FROM
    DATAS D
LEFT JOIN ABSENTEISMO AR ON D.DATA_REFERENCIA = AR.DATA_REFERENCIA
LEFT JOIN CONTRATOS_TOTAIS CT ON AR.IDENTIFICADOR = CT.IDENTIFICADOR

ORDER BY
    CASE
        WHEN CT.IDENTIFICADOR = '10' THEN 1
        WHEN CT.IDENTIFICADOR = '30' THEN 2
        WHEN CT.IDENTIFICADOR = '40' THEN 3
        WHEN CT.IDENTIFICADOR = '50' THEN 4
        WHEN CT.IDENTIFICADOR = '70' THEN 5
        WHEN CT.IDENTIFICADOR = '001' THEN 6
        WHEN CT.IDENTIFICADOR = '013' THEN 7
        ELSE 8
    END,
    D.DATA_REFERENCIA;
