WITH
/*==============================INDICES POR UNIDADES E REDE============================================*/
-- CTE para gerar todos os meses do período de apuração
PARAMS AS (
/*PARA TESTES*/
/*
SELECT TRUNC(TO_DATE('&DATA_INICIO', 'DD/MM/YYYY'), 'MM') AS DATA_INICIO,
       TRUNC(TO_DATE('&DATA_FIM', 'DD/MM/YYYY'), 'MM') AS DATA_FIM,
       TO_CHAR(ADD_MONTHS(TRUNC(TO_DATE('&DATA_INICIO', 'DD/MM/YYYY'), 'MM'),
                          LEVEL - 1),
               'MM/YYYY') AS MES_ANO,
       ADD_MONTHS(TRUNC(TO_DATE('&DATA_INICIO', 'DD/MM/YYYY'), 'MM'),
                  LEVEL - 1) AS DATA_MES,
       TO_CHAR(ADD_MONTHS(TRUNC(TO_DATE('&DATA_INICIO', 'DD/MM/YYYY'), 'MM'),
                          LEVEL - 1),
               'fmMonth YYYY',
               'NLS_DATE_LANGUAGE=PORTUGUESE') AS MES_ANO_EXTENSO
  FROM DUAL
CONNECT BY LEVEL <=
           MONTHS_BETWEEN(TRUNC(TO_DATE('&DATA_FIM', 'DD/MM/YYYY'), 'MM'),
                          TRUNC(TO_DATE('&DATA_INICIO', 'DD/MM/YYYY'), 'MM')) + 1
*/
  SELECT
    TRUNC(:DATA_INICIO, 'MM') AS DATA_INICIO,
    TRUNC(:DATA_FIM,     'MM') AS DATA_FIM,
    ADD_MONTHS(TRUNC(:DATA_INICIO, 'MM'), LEVEL-1)           AS DATA_MES,
    LAST_DAY(ADD_MONTHS(TRUNC(:DATA_INICIO, 'MM'), LEVEL-1)) AS DATA_MES_FIM
  FROM DUAL
  CONNECT BY LEVEL <= MONTHS_BETWEEN(TRUNC(:DATA_FIM,'MM'), TRUNC(:DATA_INICIO,'MM')) + 1

),

CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.DES_DEFICIENCIA,
                CT.SEXO,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
 --CROSS JOIN DATAS_REF M
 CROSS JOIN PARAMS P
 WHERE CT.DATA_ADMISSAO <= P.DATA_FIM
 AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31') >= P.DATA_INICIO --lógica para pegar todos os contratos durante o período
/*VERSÕES ALTERNATIVAS DE FILTRAR POR DATA
(('31/03/2025' BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= '31/03/2025' AND CT.DATA_DEMISSAO IS NULL))
AND (CT.DATA_ADMISSAO <= TO_DATE('31/07/2025','DD/MM/YYYY'))
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= TO_DATE('01/07/2025','DD/MM/YYYY'))
AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= '01/07/2025')*/

 AND P.DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
 AND P.DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
 AND P.DATA_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
 AND ORG.COD_EMP = 4
 --AND ORG.COD_TIPO = 1
 AND ORG.EDICAO_ORG_4 IS NOT NULL
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
--AND ORG.COD_UNIDADE = 004
 ORDER BY CT.COD_CONTRATO

),


AFASTADOS AS (
SELECT DISTINCT ORG.COD_EMP,
                CT.COD_CONTRATO,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFAST,
                NF.NOME_CAUSA_AFAST AS DES_AFAST,
                AF.DATA_INICIO AS DATA_INI_AFAST,
                AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306                AF,
       RHFP0300                CT,
       RHFP0100                NF,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT   FN,
       PARAMS                  P
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND AF.COD_CAUSA_AFAST = NF.COD_CAUSA_AFAST
   AND CT.DATA_INICIO <= P.DATA_FIM
   AND NVL(CT.DATA_FIM, DATE '2999-12-31') >= P.DATA_INICIO
      /* AND (CT.DATA_INICIO <= '31/03/2025')
               AND (CT.DATA_INICIO IS NULL OR CT.DATA_FIM >= '01/01/2025')*/
   AND P.DATA_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND P.DATA_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND P.DATA_FIM BETWEEN AF.DATA_INICIO(+) AND
       NVL(AF.DATA_FIM(+), DATE '2999-12-31')
   AND ORG.COD_EMP = 4
--AND ORG.COD_TIPO = 1
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)

),

TOT_AFAST AS (
SELECT CT.COD_EMP,
       COUNT(DISTINCT AF.COD_CONTRATO) AS QTD_AFASTADOS
FROM AFASTADOS AF
JOIN CONTRATOS CT ON CT.COD_CONTRATO = AF.COD_CONTRATO
WHERE AF.STATUS_AFAST NOT IN (0,7)
GROUP BY CT.COD_EMP
)


SELECT AF.COD_CONTRATO || ' - ' || CT.DES_PESSOA AS COLABORADOR,
       CT.DES_FUNCAO,
       CT.DATA_ADMISSAO,
       CT.DATA_DEMISSAO,
       CT.DES_UNIDADE,
       AF.STATUS_AFAST,
       AF.DES_AFAST,
       AF.DATA_INI_AFAST,
       AF.DATA_FIM_AFAST,
       CT.IND_DEFICIENCIA,
       CASE
           WHEN CT.IND_DEFICIENCIA = 'N' THEN
            NULL
           ELSE
            'Qual? ' || CT.DES_DEFICIENCIA
       END AS DES_DEF,
       TOT.QTD_AFASTADOS,

       SYSDATE AS DTA_SISTEMA,
       'Setor: ' || TO_CHAR(:SETOR) || ' | ' ||
       'Data de: ' || TO_CHAR(:DATA_INICIO, 'DD/MM/YYYY') || ' à ' || TO_CHAR(:DATA_FIM, 'DD/MM/YYYY') AS PARAMETROS
FROM AFASTADOS AF
JOIN CONTRATOS CT ON CT.COD_CONTRATO = AF.COD_CONTRATO
LEFT JOIN TOT_AFAST TOT ON TOT.COD_EMP = AF.COD_EMP
WHERE AF.STATUS_AFAST NOT IN (0,7)
 AND (:SETOR = 0 OR CT.COD_UNIDADE = :SETOR)
ORDER BY CT.DES_UNIDADE, AF.COD_CONTRATO;

