/*SQL CTE PADRÃO OFICIAL DE GERAÇÃO DE DADOS COLABORADORES COM USABILIDADE RETROATIVA*/

WITH
CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                CT.COD_DEMISSAO,
                CT.DES_DEMISSAO,
                CT.COD_VINCULO_EMPREG,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.IDADE,
                CT.SEXO,
                CT.DDD || '  ' || CT.CELULAR AS CELULAR,
                CT.EMAIL,
                CT.EMAIL_ALTER,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
 FROM V_DADOS_CONTRATO_AVT CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_HIST_HORAS_COLAB_AVT HR,
       VH_CARGO_CONTRATO_AVT   FN
 WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
   AND CT.COD_CONTRATO = HR.COD_CONTRATO
   AND CT.COD_CONTRATO = FN.COD_CONTRATO
   /*AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= TO_DATE('01/07/2025', 'DD/MM/YYYY')) --VESÃO ALTERNATIVA, PARA RETORNAR ATÉ QUEM JÁ FOI DEMITIDO ATÉ ATÉ A DATA_DEMISSAO*/
   /*AND (('24/07/2025' BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= '24/07/2025' AND CT.DATA_DEMISSAO IS NULL))*/
   AND CT.DATA_DEMISSAO BETWEEN :DEMISSAO_INICIO AND :DEMISSAO_FIM
   --AND CT.DATA_DEMISSAO BETWEEN '01/07/2025' AND '31/07/2025'
   AND :DEMISSAO_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND :DEMISSAO_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :DEMISSAO_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
   AND ORG.COD_EMP = 8
   AND CT.STATUS = 1
   --AND ORG.COD_TIPO = 1
   AND ORG.EDICAO_ORG_4 IS NOT NULL
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   --AND ORG.COD_UNIDADE = 004
 ORDER BY CT.COD_CONTRATO

),

STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_ORGANOGRAMA,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST,
       AF.DATA_INICIO AS DATA_INI_AFAST,
       AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   /*AND ((:DEMISSAO_FIM BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= :DEMISSAO_FIM AND CT.DATA_FIM IS NULL))*/
   AND CT.DATA_FIM BETWEEN :DEMISSAO_INICIO AND :DEMISSAO_FIM
   --AND CT.DATA_FIM BETWEEN '01/07/2025' AND :DEMISSAO_FIM
   AND :DEMISSAO_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DEMISSAO_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND :DEMISSAO_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   AND ORG.COD_EMP = 8
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608)
   --AND ORG.COD_TIPO = 1
),

TOTAL_CONTRATOS_UNI AS (
SELECT COD_UNIDADE,
       COUNT(DISTINCT CT.COD_CONTRATO) AS TOT_CONTRATOS_UNI
FROM CONTRATOS CT
GROUP BY COD_UNIDADE
),

TOTAL_CONTRATOS AS (
SELECT
      COUNT(DISTINCT CT.COD_CONTRATO) AS TOT_CONTRATOS
FROM CONTRATOS CT
)

SELECT CT.COD_CONTRATO || ' - ' || CT.DES_PESSOA AS COLABORADOR,
       CT.DATA_ADMISSAO AS ADMISSAO,
       CT.DATA_DEMISSAO AS DEMISSAO,
       CT.DES_DEMISSAO,
       CT.DES_FUNCAO AS FUNCAO,
       CT.CELULAR,
       CT.EMAIL,
       CT.EMAIL_ALTER,
       CT.IDADE,
       CT.DES_UNIDADE AS UNIDADE,
       CT.COD_REDE,
       CT.DES_REDE AS REDE,
       TU.TOT_CONTRATOS_UNI AS DEMITIDOS_UNIDADE,
       TT.TOT_CONTRATOS AS DEMITIDOS_CIA,

       :DEMISSAO_INICIO || ' - ' || :DEMISSAO_FIM AS REFERENCIA
FROM CONTRATOS CT
LEFT JOIN STATUS_AFASTADOS AF ON CT.COD_CONTRATO = AF.COD_CONTRATO
LEFT JOIN TOTAL_CONTRATOS_UNI TU ON CT.COD_UNIDADE = TU.COD_UNIDADE
CROSS JOIN TOTAL_CONTRATOS TT
WHERE (CT.COD_TIPO = :TIPO OR :TIPO = 0)
  AND (CT.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
  AND (CT.COD_REDE = :REDE OR :REDE = 0)

ORDER BY CT.COD_UNIDADE, CT.DATA_DEMISSAO, CT.COD_CONTRATO
