WITH
PARAMS AS (
  /*SELECT TO_DATE('&DATA_INICIO','DD/MM/YYYY') AS D_INI,
         TO_DATE('&DATA_FIM'   ,'DD/MM/YYYY') AS D_FIM
  FROM DUAL*/

  SELECT :DATA_INICIO AS D_INI,
         :DATA_FIM AS D_FIM
  FROM DUAL

),
DATAS_REF AS (
  SELECT ADD_MONTHS(p.D_INI, LEVEL-1)                          AS DTA_INI,
         LAST_DAY(ADD_MONTHS(p.D_INI, LEVEL-1))                AS DTA_FIM,
         TO_CHAR(ADD_MONTHS(p.D_INI, LEVEL-1),'MM/YYYY')       AS MES_ANO
  FROM PARAMS p
  CONNECT BY LEVEL <= MONTHS_BETWEEN(p.D_FIM, p.D_INI) + 1
),



CONTRATOS AS (
SELECT DISTINCT CT.STATUS,
                CT.COD_CONTRATO,
                CT.DES_PESSOA,
                CT.DATA_NASCIMENTO,
                CT.DATA_ADMISSAO,
                CT.DATA_DEMISSAO,
                FN.COD_FUNCAO,
                FN.DES_FUNCAO,
                FN.DATA_INI_CLH,
                FN.DATA_FIM_CLH,
                HR.HR_BASE_MES,
                HR.DATA_INI_HR,
                HR.DATA_FIM_HR,
                CT.IND_DEFICIENCIA,
                CT.SEXO,
                ORG.COD_EMP,
                ORG.EDICAO_EMP,
                ORG.DES_EMP,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                ORG.DES_UNIDADE,
                ORG.DATA_INI_ORG,
                ORG.DATA_FIM_ORG,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_3
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME3
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME3
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_FILIAL,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.EDICAO_ORG_4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.EDICAO_ORG_4
                  ELSE
                   ORG.COD_UNIDADE
                END AS COD_DIVISAO,
                CASE
                  WHEN ORG.COD_TIPO = 2 THEN
                   ORG.NOME4
                  WHEN ORG.COD_TIPO = 3 THEN
                   ORG.NOME4
                  ELSE
                   ORG.DES_UNIDADE
                END AS DES_DIVISAO,
                ORG.COD_REDE,
                ORG.DES_REDE,
                ORG.COD_TIPO,
                ORG.DES_TIPO
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
 CROSS JOIN DATAS_REF M
 CROSS JOIN PARAMS P
 WHERE -- CONTRATOS ATIVOS EM QUALQUER DIA DO MÊS
 CT.DATA_ADMISSAO <= M.DTA_FIM
 AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31') >= M.DTA_INI
/*VERSÕES ALTERNATIVAS DE FILTRAR POR DATA
(('31/03/2025' BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= '31/03/2025' AND CT.DATA_DEMISSAO IS NULL))
AND (CT.DATA_ADMISSAO <= TO_DATE('31/07/2025','DD/MM/YYYY'))
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= TO_DATE('01/07/2025','DD/MM/YYYY'))
AND (CT.DATA_DEMISSAO IS NULL OR
       CT.DATA_DEMISSAO >= '01/07/2025')*/

 AND P.D_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
 AND P.D_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
 AND P.D_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
 AND ORG.COD_EMP = 4
 --AND ORG.COD_TIPO = 1
 AND ORG.EDICAO_ORG_4 IS NOT NULL
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
--AND ORG.COD_UNIDADE = 004
 ORDER BY CT.COD_CONTRATO
),

/*MAPEIA TODOS OS COLABORADORES MAS TAMBÉM COM INFO DE AFASTAMENTO*/
STATUS_AFASTADOS AS (
SELECT DISTINCT ORG.COD_EMP,
                CT.COD_CONTRATO,
                ORG.COD_ORGANOGRAMA,
                ORG.COD_UNIDADE,
                NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFAST,
                AF.DATA_INICIO AS DATA_INI_AFAST,
                AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306                AF,
       RHFP0300                CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT   FN,
       DATAS_REF               M,
       PARAMS                  P
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND CT.DATA_INICIO <= M.DTA_FIM
   AND NVL(CT.DATA_FIM, DATE '2999-12-31') >= M.DTA_INI
      /* AND (CT.DATA_INICIO <= '31/03/2025')
         AND (CT.DATA_INICIO IS NULL OR CT.DATA_FIM >= '01/01/2025')*/
   AND P.D_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND P.D_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND P.D_FIM BETWEEN AF.DATA_INICIO(+) AND
       NVL(AF.DATA_FIM(+), DATE '2999-12-31')
   AND ORG.COD_EMP = 4
   --AND ORG.COD_TIPO = 1
--AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)

),

/*uso para testes*/
/*SELECT A.*
FROM CONTRATOS A

SELECT DISTINCT COD_CONTRATO FROM V_DADOS_COLAB_AVT
WHERE (DATA_DEMISSAO IS NULL OR
       DATA_DEMISSAO >= :DATA_FIM)
AND COD_EMP :EMPRESA
AND COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
ORDER BY COD_CONTRATO*/


EFETIVO_INICIAL_UNI AS (
    SELECT CTR.COD_ORGANOGRAMA,
           CTR.COD_UNIDADE,
           CTR.COD_REDE,
           CTR.COD_EMP,
           CTR.COD_TIPO,
           M.DTA_INI,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
      FROM CONTRATOS CTR
     CROSS JOIN DATAS_REF M
     WHERE ('01/' || TO_CHAR(M.DTA_INI, 'MM/YYYY')) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND ('01/' || TO_CHAR(M.DTA_INI, 'MM/YYYY')) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE 'COMPRADOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')

     GROUP BY CTR.COD_ORGANOGRAMA,
              CTR.COD_UNIDADE,
              CTR.COD_REDE,
              CTR.COD_EMP,
              M.DTA_INI,
              CTR.COD_TIPO
),
EFETIVO_FINAL_UNI AS (
    SELECT CTR.COD_ORGANOGRAMA,
           CTR.COD_UNIDADE,
           CTR.COD_REDE,
           CTR.COD_EMP,
           CTR.COD_TIPO,
           M.DTA_FIM,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
      FROM CONTRATOS CTR
     CROSS JOIN DATAS_REF M
     WHERE LAST_DAY(TO_DATE('' || TO_CHAR(M.DTA_FIM, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.DTA_FIM, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE 'COMPRADOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')

     GROUP BY CTR.COD_ORGANOGRAMA,
              CTR.COD_UNIDADE,
              CTR.COD_REDE,
              CTR.COD_EMP,
              M.DTA_FIM,
              CTR.COD_TIPO
),


DATAMETRICS_UNI AS (
SELECT A.COD_ORGANOGRAMA,
       A.COD_UNIDADE,
       A.DES_UNIDADE,
       A.COD_REDE,
       A.COD_EMP,
       A.COD_TIPO,
       M.DTA_INI,
       M.DTA_FIM,

       /*COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > M.DTA_FIM THEN
                A.COD_CONTRATO
             END) AS ATIVOS_ATUAIS,*/
       COUNT(DISTINCT A.COD_CONTRATO) AS ATIVOS_ATUAIS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO <= M.DTA_FIM AND
                   (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.DTA_FIM) THEN
                A.COD_CONTRATO
             END) AS ATIVOS_PERIODO,

       COUNT(DISTINCT CASE
               WHEN B.DATA_INI_AFAST <= M.DTA_FIM AND
                   (B.DATA_FIM_AFAST IS NULL OR B.DATA_FIM_AFAST >= M.DTA_INI) AND
                    /*B.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND*/
                    B.STATUS_AFAST <> 7 THEN
                A.COD_CONTRATO
             END) AS AFAST_PERIODO,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO BETWEEN M.DTA_INI AND M.DTA_FIM THEN
                A.COD_CONTRATO
             END) AS ADMITIDOS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO BETWEEN M.DTA_INI AND M.DTA_FIM THEN
                A.COD_CONTRATO
             END) AS DEMITIDOS

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
 CROSS JOIN DATAS_REF M
 WHERE (UPPER(A.DES_FUNCAO) LIKE '%GERENTE%' OR
        UPPER(A.DES_FUNCAO) LIKE 'COMPRADOR%' OR
        UPPER(A.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
        UPPER(A.DES_FUNCAO) LIKE '%DIRETOR%')

 GROUP BY A.COD_ORGANOGRAMA,
          A.COD_UNIDADE,
          A.DES_UNIDADE,
          A.COD_REDE,
          A.COD_EMP,
          A.COD_TIPO,
          M.DTA_INI,
          M.DTA_FIM
),

TURNOVER_UNI AS (
SELECT A.COD_ORGANOGRAMA,
       A.COD_UNIDADE,
       A.DES_UNIDADE,
       A.COD_REDE,
       A.DES_REDE,
       A.COD_EMP,
       A.COD_TIPO,
       DM.ATIVOS_ATUAIS,
       DM.ATIVOS_PERIODO,
       DM.AFAST_PERIODO,
       DM.ADMITIDOS,
       DM.DEMITIDOS,
       EI.EFETIVO_INICIAL,
       EF.EFETIVO_FINAL,
       (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DM.DEMITIDOS * 100) /
                ((EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER
  FROM (SELECT DISTINCT COD_ORGANOGRAMA,
                        COD_UNIDADE,
                        DES_UNIDADE,
                        COD_REDE,
                        DES_REDE,
                        COD_EMP,
                        COD_TIPO
          FROM CONTRATOS) A
   LEFT JOIN EFETIVO_INICIAL_UNI EI ON A.COD_ORGANOGRAMA =
                                      EI.COD_ORGANOGRAMA
   LEFT JOIN EFETIVO_FINAL_UNI EF ON A.COD_ORGANOGRAMA = EF.COD_ORGANOGRAMA
  INNER JOIN DATAMETRICS_UNI DM ON A.COD_ORGANOGRAMA = DM.COD_ORGANOGRAMA
                               AND (NVL(DM.ATIVOS_PERIODO, 0) > 0 OR
                                    NVL(DM.ADMITIDOS, 0) > 0 OR
                                    NVL(DM.DEMITIDOS, 0) > 0 OR
                                    NVL(DM.ATIVOS_ATUAIS, 0) > 0 -- opcional, se quiser exigir “ativo hoje”
                                   )
  WHERE (A.COD_UNIDADE = :SETOR OR :SETOR = 0)
    --AND (A.COD_REDE = :REDE OR :REDE = 0)
    --AND (A.COD_TIPO = :TIPO OR :TIPO = 0)
    AND A.COD_EMP = 4
  ORDER BY A.COD_UNIDADE

),


/*================================*/


/*RELAÇÃO GERAL DA COMPANHIA*/

EFETIVO_INICIAL_EMP AS (
    SELECT CTR.COD_EMP,
           M.DTA_INI,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
      FROM CONTRATOS CTR
     CROSS JOIN DATAS_REF M
     WHERE ('01/' || TO_CHAR(M.DTA_INI, 'MM/YYYY')) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND ('01/' || TO_CHAR(M.DTA_INI, 'MM/YYYY')) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) NOT LIKE '%ESTAGIARIO%' AND
            UPPER(CTR.DES_FUNCAO) NOT LIKE '%APRENDIZ%' AND
            UPPER(CTR.DES_FUNCAO) NOT LIKE '%TEMPORARIO%')
     GROUP BY CTR.COD_EMP,
              M.DTA_INI

),
EFETIVO_FINAL_EMP AS (
    SELECT CTR.COD_EMP,
           M.DTA_FIM,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
      FROM CONTRATOS CTR
     CROSS JOIN DATAS_REF M
     WHERE LAST_DAY(TO_DATE('' || TO_CHAR(M.DTA_FIM, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_ADMISSAO AND NVL(CTR.DATA_DEMISSAO, '31/12/9999')
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.DTA_FIM, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_INI_ORG AND NVL(CTR.DATA_FIM_ORG, '31/12/9999')
       AND (UPPER(CTR.DES_FUNCAO) LIKE '%GERENTE%' OR
            UPPER(CTR.DES_FUNCAO) LIKE 'COMPRADOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
            UPPER(CTR.DES_FUNCAO) LIKE '%DIRETOR%')

     GROUP BY CTR.COD_EMP,
              M.DTA_FIM

),


DATAMETRICS_EMP AS (
SELECT A.COD_EMP,
       M.DTA_INI,
       M.DTA_FIM,

       /*COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > M.DTA_FIM THEN
                A.COD_CONTRATO
             END) AS ATIVOS_ATUAIS,*/
       COUNT(DISTINCT A.COD_CONTRATO) AS ATIVOS_ATUAIS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO <= M.DTA_FIM AND
                   (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.DTA_FIM) THEN
                A.COD_CONTRATO
             END) AS ATIVOS_PERIODO,

       COUNT(DISTINCT CASE
               WHEN B.DATA_INI_AFAST <= M.DTA_FIM AND
                   (B.DATA_FIM_AFAST IS NULL OR B.DATA_FIM_AFAST >= M.DTA_INI) AND
                    /*B.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND*/
                    B.STATUS_AFAST <> 7 THEN
                A.COD_CONTRATO
             END) AS AFAST_PERIODO,

       COUNT(DISTINCT CASE
               WHEN A.DATA_ADMISSAO BETWEEN M.DTA_INI AND M.DTA_FIM THEN
                A.COD_CONTRATO
             END) AS ADMITIDOS,

       COUNT(DISTINCT CASE
               WHEN A.DATA_DEMISSAO BETWEEN M.DTA_INI AND M.DTA_FIM THEN
                A.COD_CONTRATO
             END) AS DEMITIDOS

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
 CROSS JOIN DATAS_REF M
 WHERE (UPPER(A.DES_FUNCAO) LIKE '%GERENTE%' OR
        UPPER(A.DES_FUNCAO) LIKE 'COMPRADOR%' OR
        UPPER(A.DES_FUNCAO) LIKE '%SUPERVISOR%' OR
        UPPER(A.DES_FUNCAO) LIKE '%DIRETOR%')

 GROUP BY A.COD_EMP,
          M.DTA_INI,
          M.DTA_FIM
),

TURNOVER_EMP AS (
SELECT A.COD_EMP,
       A.DES_EMP,
       DM.ATIVOS_ATUAIS,
       DM.ATIVOS_PERIODO,
       DM.AFAST_PERIODO,
       DM.ADMITIDOS,
       DM.DEMITIDOS,
       EI.EFETIVO_INICIAL,
       EF.EFETIVO_FINAL,
       (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DM.DEMITIDOS * 100) /
                ((EI.EFETIVO_INICIAL + EF.EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER

  FROM (SELECT DISTINCT COD_EMP,
                        DES_EMP
          FROM CONTRATOS) A
  LEFT JOIN EFETIVO_INICIAL_EMP EI
         ON A.COD_EMP = EI.COD_EMP
  LEFT JOIN EFETIVO_FINAL_EMP EF
         ON A.COD_EMP = EF.COD_EMP
  LEFT JOIN DATAMETRICS_EMP DM
         ON A.COD_EMP = DM.COD_EMP
  /*WHERE (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (A.COD_REDE = :REDE OR :REDE = 0)
    AND (A.COD_TIPO = :TIPO OR :TIPO = 0)*/


),


/*============================*/

TURNOVER_UNIDADE AS (
  SELECT ROW_NUMBER() OVER(ORDER BY COD_TIPO, COD_REDE, COD_UNIDADE, COD_ORGANOGRAMA, COD_EMP) AS RN,
         T.*
    FROM TURNOVER_UNI T

),


TURNOVER_EMPRESA AS (
  SELECT ROW_NUMBER() OVER(ORDER BY COD_EMP, DES_EMP) AS RN, E.*
    FROM TURNOVER_EMP E
)

/*PERIODO AS (
  SELECT MIN(MONTH_START) AS INI, MAX(MONTH_END) AS FIM FROM MONTHS
)*/


/*SELECT FINAL COM TODOS OS INDICADORES*/
SELECT --LOJAS/SETORES
       U.COD_ORGANOGRAMA,
       U.COD_TIPO,
       U.COD_UNIDADE,
       U.DES_UNIDADE,
       U.DES_REDE AS DES_REDE_UNI,
       'Ref: ' || P.D_INI || ' - ' || P.D_FIM AS REFERENCIA,

       --NVL(PFM.TOT_COLAB, 0) AS COLABORADORES,
       U.ATIVOS_ATUAIS,
       U.ATIVOS_PERIODO,
       U.AFAST_PERIODO,
       U.ADMITIDOS,
       U.DEMITIDOS,
       U.EFETIVO_INICIAL,
       U.EFETIVO_FINAL,
       U.EFETIVO_MEDIO,

       ROUND(U.TURNOVER, 2) AS "%_TURNOVER",

       --GERAL DA COMPANHIA
       E.COD_EMP,
       E.DES_EMP,
       E.ATIVOS_ATUAIS AS ATV_ATUAIS_EMP,
       E.ATIVOS_PERIODO AS ATV_PERIODO_EMP,
       E.AFAST_PERIODO AS AFAST_PERIODO_EMP,
       E.ADMITIDOS AS ADMITIDOS_EMP,
       E.DEMITIDOS AS DEMITIDOS_EMP,
       E.EFETIVO_INICIAL AS EFTV_INICIAL_EMP,
       E.EFETIVO_FINAL AS EFTV_FINAL_EMP,
       E.EFETIVO_MEDIO AS EFTV_MEDIO_EMP,

       ROUND(E.TURNOVER, 2) AS "%_TURNOVER_EMP",

       'De ' || :DATA_INICIO || ' até ' || :DATA_FIM AS PERIODO,

       'Setor: ' || :SETOR AS PARAMETROS,

       'Efetivo Médio = Efetivo Inicial + Efetivo Final' AS FORMULA_EFT_MEDIO,
       'Turnover = Demitidos * 100 / Efetivo Médio' AS FORMULA_TURNOVER,

       'Aprendiz | Estagiário | Temporários' AS CARGOS_NAO_CONTEM

  FROM TURNOVER_UNIDADE U
  FULL OUTER JOIN TURNOVER_EMPRESA E ON U.RN = E.RN
  CROSS JOIN PARAMS P

ORDER BY COALESCE(U.RN, E.RN);


