WITH
CONTRATOS AS (
SELECT COD_CONTRATO,
       COD_CONTRATO || ' - ' || DES_PESSOA AS COLABORADOR,
       DATA_ADMISSAO,
       DATA_DEMISSAO,
       DES_FUNCAO,
       COD_UNIDADE,
       DES_UNIDADE,
       DES_REDE_LOCAL,
       IND_BATE_PONTO,
       HR_BASE_MES,
       HOR_1_ENT,
       HOR_1_SAI,
       HOR_2_ENT,
       HOR_2_SAI,
       HOR_3_ENT,
       HOR_3_SAI,
       HOR_4_ENT,
       HOR_4_SAI,
       COD_SINDICATO || ' - ' || DES_SINDICATO AS SINDICATO,
       COD_TIPO
FROM V_DADOS_COLAB_AVT
WHERE STATUS = 0
AND COD_EMP = 8
AND IND_BATE_PONTO = 'S'
AND (COD_TIPO = :TIPO OR :TIPO = 0)
AND (COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
AND (COD_REDE_LOCAL = :REDE OR :REDE = 0)
--AND COD_CONTRATO = 389622

),

TOTAL_CONTRATOS AS (
SELECT COD_UNIDADE,
       COUNT(DISTINCT COD_CONTRATO) AS QTDE_CONTRATOS
FROM CONTRATOS
GROUP BY COD_UNIDADE

)

SELECT A.*,
       B.QTDE_CONTRATOS,
       'TIPO: ' || :TIPO || ' | ' || 'UNIDADE: ' || :UNIDADE ||
       ' | ' || 'REDE: ' || :REDE AS PARAMETROS
FROM CONTRATOS A
LEFT JOIN TOTAL_CONTRATOS B ON A.COD_UNIDADE = B.COD_UNIDADE

ORDER BY A.COD_TIPO, A.COD_UNIDADE, A.COD_CONTRATO
