WITH
VENDAS_UNI AS (
SELECT GE.COD_QUEBRA REGIAO,
       DECODE(A.COD_UNIDADE,
              7022, 22,
              7047, 47,
              7059, 59,
              7065, 65,
              7138, 138,
              7140, 140,
              7183, 183,
              7244, 244,
              7353, 353,
              7386, 386,
              7412, 412,
              7430, 430,
              7442, 442,
              7461, 461,
              7466, 466,
              7491, 491,
              7543, 543,
              7555, 555,
              7570, 570,
              7577, 653,
              7587, 587,
              7588, 588,
              7592, 592,
              7597, 597,
              7601, 601,
              7602, 608,
              7620, 620,
              7500, 651,
              7051, 652,
              7066, 654,
              7643, 643,
              A.COD_UNIDADE) COD_UNIDADE,
       GE.COD_GRUPO,
       MIN(D.DES_FANTASIA) DES_FANTASIA,
       MIN(D.DTA_CADASTRO) DTA_CADASTRO,
       MIN(A.DTA_EMISSAO) DTA_ATUALIZACAO,
       SUM(OPER.VLR_OPERACAO) VALOR_VENDA_LOJA,
       SUM(CASE
             WHEN TO_CHAR(A.DTA_EMISSAO, 'D') = 1 THEN
              NVL(OPER.VLR_OPERACAO, 0)
             ELSE
              0
           END) VDA_DOMINGO
  FROM NL.NS_NOTAS@NLGRZ A
  JOIN NL.NS_NOTAS_OPERACOES@NLGRZ OPER ON A.NUM_SEQ = OPER.NUM_SEQ
                                       AND A.COD_MAQUINA = OPER.COD_MAQUINA
  JOIN NL.GE_GRUPOS_UNIDADES@NLGRZ GE ON A.COD_UNIDADE = GE.COD_UNIDADE
  JOIN NL.PS_PESSOAS@NLGRZ D ON A.COD_UNIDADE = D.COD_PESSOA
 WHERE A.DTA_EMISSAO BETWEEN :DATA_INICIO AND :DATA_FIM
   AND GE.COD_GRUPO = :COD_GRUPO_REDE
   AND GE.COD_EMP = 1
   AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND A.IND_STATUS = 1
   AND A.TIP_NOTA = 4
   AND D.IND_INATIVO = 0
 GROUP BY GE.COD_QUEBRA,
          DECODE(A.COD_UNIDADE,
                 7022, 22,
                 7047, 47,
                 7059, 59,
                 7065, 65,
                 7138, 138,
                 7140, 140,
                 7183, 183,
                 7244, 244,
                 7353, 353,
                 7386, 386,
                 7412, 412,
                 7430, 430,
                 7442, 442,
                 7461, 461,
                 7466, 466,
                 7491, 491,
                 7543, 543,
                 7555, 555,
                 7570, 570,
                 7577, 653,
                 7587, 587,
                 7588, 588,
                 7592, 592,
                 7597, 597,
                 7601, 601,
                 7602, 608,
                 7620, 620,
                 7500, 651,
                 7051, 652,
                 7066, 654,
                 7643, 643,
                 A.COD_UNIDADE),
          GE.COD_GRUPO
 ORDER BY GE.COD_QUEBRA, COD_UNIDADE, DES_FANTASIA
),

VLR_EXTRAS_BONUS_DOM_UNI AS (
  SELECT
    COD_UNIDADE,
    SUM(VLR_HORAS_EXTRAS) AS VLR_HORAS_EXTRAS,
    SUM(VLR_BONUS_DOM) AS VLR_BONUS_DOM
  FROM (
    SELECT
      A.COD_UNIDADE,
      TRUNC(LAST_DAY(A.DATA_REFERENCIA)) AS MES_REF,
      SUM(A.VLR_HORAS_EXTRAS) AS VLR_HORAS_EXTRAS,
      SUM(A.VLR_BONUS_DOM) AS VLR_BONUS_DOM
    FROM V_VALOR_HORAS_EXTRAS_AVT A
    WHERE A.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
      AND A.COD_EVENTO IN (1, 8)
      AND (:UNIDADE = 0 OR A.COD_UNIDADE = :UNIDADE)
    GROUP BY A.COD_UNIDADE, TRUNC(LAST_DAY(A.DATA_REFERENCIA))
  )
  GROUP BY COD_UNIDADE
),

CONTRATOS_UNI AS (
SELECT DISTINCT
       ORG.COD_EMP,
       ORG.COD_UNIDADE,
       SUM(DECODE(HR.HR_BASE_MES, 220, 1, 0)) QTD_220,
       SUM(DECODE(HR.HR_BASE_MES, 195, 1, 0)) QTD_195,
       SUM(DECODE(HR.HR_BASE_MES, 180, 1, 0)) QTD_180,
       SUM(DECODE(HR.HR_BASE_MES, 165, 1, 0)) QTD_165,
       SUM(DECODE(HR.HR_BASE_MES, 150, 1, 0)) QTD_150,
       SUM(DECODE(HR.HR_BASE_MES, 120, 1, 0)) QTD_120,
       SUM(DECODE(HR.HR_BASE_MES, 110, 1, 0)) QTD_110,
       SUM(DECODE(HR.HR_BASE_MES, 100, 1, 0)) QTD_100,
       SUM(CASE
             WHEN CT.IND_DEFICIENCIA = 'N' THEN
              1
             WHEN CT.IND_DEFICIENCIA = 'S' AND HR.HR_BASE_MES > 120 THEN
              1
             ELSE
              0
           END) AS COLABS_PROD,
       SUM(DECODE(CT.IND_DEFICIENCIA, 'S', 1, 0)) AS QTD_PCDS,
       SUM(CASE
             WHEN FN.COD_FUNCAO = 204 THEN
              1
             ELSE
              0
           END) AS QTD_TEMPORARIOS
  FROM V_DADOS_CONTRATO_AVT    CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_HIST_HORAS_COLAB_AVT HR,
       VH_CARGO_CONTRATO_AVT   FN
 WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
   AND CT.COD_CONTRATO = HR.COD_CONTRATO
   AND CT.COD_CONTRATO = FN.COD_CONTRATO
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
       (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :DATA_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
   AND ORG.COD_EMP = 8
   AND ORG.COD_TIPO = 1
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   AND FN.COD_FUNCAO NOT IN (74, 75, 310, 409, 68)
   AND NOT EXISTS
 (SELECT 1
          FROM RHFP0306 AF
         WHERE AF.COD_CONTRATO = CT.COD_CONTRATO
           AND :DATA_FIM BETWEEN AF.DATA_INICIO AND AF.DATA_FIM
           AND AF.COD_CAUSA_AFAST NOT IN (6, 7, 107)
        )
 GROUP BY ORG.COD_UNIDADE, ORG.COD_EMP
 ORDER BY ORG.COD_UNIDADE
),

MESES_REF AS (
SELECT LAST_DAY(ADD_MONTHS(:DATA_INICIO, LEVEL - 1)) AS MES_REF
  FROM DUAL
CONNECT BY LEVEL <= MONTHS_BETWEEN(:DATA_FIM, :DATA_INICIO) + 1
),

BASE_CONTRATOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       ORG.COD_UNIDADE,
       CT.COD_CONTRATO,
       HR.HR_BASE_MES,
       CT.IND_DEFICIENCIA,
       M.MES_REF
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
  JOIN MESES_REF M ON 1 = 1
 WHERE ORG.COD_EMP = 8
   AND ORG.COD_TIPO = 1
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   AND FN.COD_FUNCAO NOT IN (74, 75, 310, 409, 68)
   AND NOT EXISTS
 (SELECT 1
          FROM RHFP0306 AF
         WHERE AF.COD_CONTRATO = CT.COD_CONTRATO
           AND M.MES_REF BETWEEN AF.DATA_INICIO AND AF.DATA_FIM
           AND AF.COD_CAUSA_AFAST NOT IN (6, 7, 107))
   AND CT.DATA_ADMISSAO <= LAST_DAY(M.MES_REF)
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= M.MES_REF)
   AND M.MES_REF BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND M.MES_REF BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND M.MES_REF BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
),

TOTAL_HORAS_UNI AS (
SELECT COD_UNIDADE,
       SUM(CASE
             WHEN IND_DEFICIENCIA = 'S' AND HR_BASE_MES > 120 THEN
              TO_NUMBER(HR_BASE_MES)
             WHEN IND_DEFICIENCIA = 'S' THEN
              0
             ELSE
              TO_NUMBER(HR_BASE_MES)
           END) AS TOTAL_HRS
  FROM BASE_CONTRATOS
 GROUP BY COD_UNIDADE
 ORDER BY COD_UNIDADE
),

CTE_TEMPORARIOS_UNI AS (
SELECT ORG.COD_EMP, ORG.COD_UNIDADE, COUNT(1) AS QTD_TEMPORARIOS
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON FN.COD_CONTRATO = ORG.COD_CONTRATO
 WHERE ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
       (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND FN.COD_FUNCAO = 204
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND ORG.COD_TIPO = 1
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608)
 GROUP BY ORG.COD_UNIDADE, ORG.COD_EMP
),

CTE_APRENDIZES_UNI AS (
  SELECT ORG.COD_EMP, ORG.COD_UNIDADE, COUNT(1) AS QTD_APRENDIZ
    FROM V_DADOS_CONTRATO_AVT CT
    JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
    JOIN VH_EST_ORG_CONTRATO_AVT ORG ON FN.COD_CONTRATO = ORG.COD_CONTRATO
   WHERE ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
         (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
     AND FN.COD_FUNCAO IN (74, 75, 310, 409)
     AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
     AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
     AND ORG.COD_TIPO = 1
     AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   GROUP BY ORG.COD_UNIDADE, ORG.COD_EMP
),

CTE_SERVENTES_UNI AS (
SELECT ORG.COD_EMP, ORG.COD_UNIDADE, COUNT(1) AS QTD_SERVENTES
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON FN.COD_CONTRATO = ORG.COD_CONTRATO
 WHERE ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
       (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND FN.COD_FUNCAO = 68
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND ORG.COD_TIPO = 1
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_UNIDADE, ORG.COD_EMP

),


STATUS_AFASTADOS_UNI AS (
SELECT ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFASTAMENTO
  FROM RHFP0306 AF, RHFP0300 CT, VH_EST_ORG_CONTRATO_AVT ORG
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND :DATA_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND ORG.COD_TIPO = 1
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)

),


AFASTADOS_UNI AS (
SELECT ORG.COD_EMP,
       ORG.COD_UNIDADE,
       NVL(COUNT(AF.COD_CONTRATO), 0) AS QTD_AFASTADOS
  FROM RHFP0306                AF,
       RHFP0100                AF2,
       RHFP0323                MT,
       RHFP0115                TP,
       RHFP0121                TRAB,
       PESSOA                  PS,
       VH_EST_ORG_CONTRATO_AVT ORG
 WHERE AF.COD_CAUSA_AFAST = AF2.COD_CAUSA_AFAST
   AND AF.COD_MOTIVO = MT.COD_MOTIVO(+)
   AND MT.COD_TIPO_MOTIVO = TP.COD_TIPO_MOTIVO(+)
   AND AF.COD_PESSOA = PS.COD_PESSOA(+)
   AND AF2.COD_MOVIMENTO_TRAB = TRAB.COD_MOVIMENTO_TRAB(+)
   AND AF.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND :DATA_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND AF.COD_CAUSA_AFAST NOT IN (6, 7, 107)
   AND ORG.COD_TIPO = 1
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_UNIDADE, ORG.COD_EMP
),


HORAS_REALIZADAS_UNI AS (
SELECT ORG.COD_EMP,
       ORG.COD_UNIDADE,
       SUM(A.NUM_HORAS) AS HORAS_REAIS
  FROM RHAF1123 A
  LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
 WHERE A.DATA_OCORRENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND A.COD_OCORRENCIA = 2
   AND ORG.COD_TIPO = 1
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_UNIDADE, ORG.COD_EMP

),


TOTAL_CONTRATOS_UNI AS (
SELECT ORG.COD_EMP,
       ORG.COD_UNIDADE,
       COUNT(DISTINCT CT.COD_CONTRATO) TOTAL_COLABS
  FROM V_DADOS_CONTRATO_AVT    CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_HIST_HORAS_COLAB_AVT HR,
       VH_CARGO_CONTRATO_AVT   FN
 WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
   AND CT.COD_CONTRATO = HR.COD_CONTRATO
   AND CT.COD_CONTRATO = FN.COD_CONTRATO
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
       (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND ORG.COD_EMP = 8
   AND ORG.COD_TIPO = 1
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_UNIDADE, ORG.COD_EMP
 ORDER BY ORG.COD_UNIDADE

),


RESULTADO_FINAL_UNI AS (
SELECT DISTINCT B.COD_EMP,
                A.COD_GRUPO,
                A.COD_UNIDADE,
                A.DES_FANTASIA,
                TO_CHAR(NVL(A.VALOR_VENDA_LOJA, 0), 'FM999G999G990D00') AS VLR_VENDA_BRUTA,
                TT.TOTAL_HRS AS HRS_ACUM,
                TRUNC(A.VALOR_VENDA_LOJA / NULLIF(TT.TOTAL_HRS, 0)) AS PRO_ACUM,
                D.HORAS_REAIS AS HRS_REALIZADAS,
                TO_CHAR(NVL(J.VLR_HORAS_EXTRAS, 0), 'FM999G999G990D00') AS VLR_HORAS_EXTRAS,
                TRUNC(A.VALOR_VENDA_LOJA / NULLIF(D.HORAS_REAIS, 0)) AS PROD_REALI,
                TO_CHAR(NVL(A.VDA_DOMINGO, 0), 'FM999G999G990D00') AS VLR_VENDA_DOM,
                TO_CHAR(NVL(J.VLR_BONUS_DOM, 0), 'FM999G999G990D00') AS VLR_BONUS_DOM,
                B.COLABS_PROD,
                H.TOTAL_COLABS,
                B.QTD_220,
                B.QTD_195,
                B.QTD_180,
                B.QTD_165,
                B.QTD_150,
                B.QTD_120,
                B.QTD_110,
                B.QTD_100,
                B.QTD_PCDS,
                NVL(I.QTD_TEMPORARIOS, 0) AS QTD_TEMPORARIO,
                NVL(F.QTD_APRENDIZ, 0) AS QTD_APRENDIZ,
                NVL(G.QTD_SERVENTES, 0) AS QTD_SERVENTE,
                NVL(C.QTD_AFASTADOS, 0) AS QTD_AFASTADOS
  FROM VENDAS_UNI A
  JOIN CONTRATOS_UNI B ON A.COD_UNIDADE = B.COD_UNIDADE
  LEFT JOIN TOTAL_HORAS_UNI TT ON A.COD_UNIDADE = TT.COD_UNIDADE
  LEFT JOIN AFASTADOS_UNI C ON C.COD_UNIDADE = B.COD_UNIDADE
  LEFT JOIN HORAS_REALIZADAS_UNI D ON D.COD_UNIDADE = B.COD_UNIDADE
  LEFT JOIN STATUS_AFASTADOS_UNI E ON E.COD_UNIDADE = B.COD_UNIDADE
  LEFT JOIN CTE_APRENDIZES_UNI F ON A.COD_UNIDADE = F.COD_UNIDADE
  LEFT JOIN CTE_SERVENTES_UNI G ON A.COD_UNIDADE = G.COD_UNIDADE
  LEFT JOIN TOTAL_CONTRATOS_UNI H ON A.COD_UNIDADE = H.COD_UNIDADE
  LEFT JOIN CTE_TEMPORARIOS_UNI I ON A.COD_UNIDADE = I.COD_UNIDADE
  LEFT JOIN VLR_EXTRAS_BONUS_DOM_UNI J ON A.COD_UNIDADE = J.COD_UNIDADE
 WHERE E.STATUS_AFASTAMENTO = 0

),

/*=================================================================*/

/*GERAL DA COMPANHIA*/

VENDAS_EMP AS (
SELECT CASE
         WHEN GE.COD_EMP = 1 THEN
          8
         ELSE
          0
       END AS COD_EMP,
       GE.COD_GRUPO,
       MIN(D.DTA_CADASTRO) DTA_CADASTRO,
       MIN(A.DTA_EMISSAO) DTA_ATUALIZACAO,
       SUM(OPER.VLR_OPERACAO) VALOR_VENDA_LOJA,
       SUM(CASE
             WHEN TO_CHAR(A.DTA_EMISSAO, 'D') = 1 THEN
              NVL(OPER.VLR_OPERACAO, 0)
             ELSE
              0
           END) VDA_DOMINGO
  FROM NL.NS_NOTAS@NLGRZ A
  JOIN NL.NS_NOTAS_OPERACOES@NLGRZ OPER ON A.NUM_SEQ = OPER.NUM_SEQ
                                       AND A.COD_MAQUINA = OPER.COD_MAQUINA
  JOIN NL.GE_GRUPOS_UNIDADES@NLGRZ GE ON A.COD_UNIDADE = GE.COD_UNIDADE
  JOIN NL.PS_PESSOAS@NLGRZ D ON A.COD_UNIDADE = D.COD_PESSOA
 WHERE A.DTA_EMISSAO BETWEEN :DATA_INICIO AND :DATA_FIM
   AND GE.COD_EMP = 1
   AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND GE.COD_GRUPO = :COD_GRUPO_REDE
   AND A.IND_STATUS = 1
   AND A.TIP_NOTA = 4
   AND D.IND_INATIVO = 0
 GROUP BY GE.COD_EMP, GE.COD_GRUPO
 ORDER BY GE.COD_GRUPO

),

VLR_EXTRAS_BONUS_DOM_EMP AS (
  SELECT
    A.COD_EMP,
    SUM(A.VLR_HORAS_EXTRAS) AS VLR_HRS_EXTRAS,
    SUM(A.VLR_BONUS_DOM) AS VLR_BONUS_DOM
  FROM (
    SELECT
      ORG.COD_EMP,
      ORG.COD_UNIDADE,
      TRUNC(LAST_DAY(A.DATA_REFERENCIA)) AS MES_REF,
      SUM(DISTINCT A.VLR_HORAS_EXTRAS + A.COD_EVENTO * 0) AS VLR_HORAS_EXTRAS,
      SUM(DISTINCT A.VLR_BONUS_DOM + A.COD_EVENTO * 0) AS VLR_BONUS_DOM
    FROM V_VALOR_HORAS_EXTRAS_AVT A
    JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_UNIDADE = ORG.COD_UNIDADE
    WHERE A.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
      AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
      AND ORG.COD_TIPO = 1
      AND (:UNIDADE = 0 OR A.COD_UNIDADE = :UNIDADE)
      AND (:REDE = 0 OR ORG.COD_REDE = :REDE)
    GROUP BY ORG.COD_EMP, ORG.COD_UNIDADE, TRUNC(LAST_DAY(A.DATA_REFERENCIA))
  ) A
  GROUP BY A.COD_EMP

),

CONTRATOS_EMP AS (
SELECT ORG.COD_EMP,
       SUM(DECODE(HR.HR_BASE_MES, 220, 1, 0)) QTD_220,
       SUM(DECODE(HR.HR_BASE_MES, 195, 1, 0)) QTD_195,
       SUM(DECODE(HR.HR_BASE_MES, 180, 1, 0)) QTD_180,
       SUM(DECODE(HR.HR_BASE_MES, 165, 1, 0)) QTD_165,
       SUM(DECODE(HR.HR_BASE_MES, 150, 1, 0)) QTD_150,
       SUM(DECODE(HR.HR_BASE_MES, 120, 1, 0)) QTD_120,
       SUM(DECODE(HR.HR_BASE_MES, 110, 1, 0)) QTD_110,
       SUM(DECODE(HR.HR_BASE_MES, 100, 1, 0)) QTD_100,
       SUM(DECODE(CT.IND_DEFICIENCIA, 'S', 0, HR_BASE_MES)) TOTAL_HRS,
       SUM(CASE
             WHEN CT.IND_DEFICIENCIA = 'N' THEN
              1
             WHEN CT.IND_DEFICIENCIA = 'S' AND HR.HR_BASE_MES > 120 THEN
              1
             ELSE
              0
           END) AS COLABS_PROD,
       SUM(DECODE(CT.IND_DEFICIENCIA, 'S', 1, 0)) AS QTD_PCDS,
       SUM(CASE
             WHEN FN.COD_FUNCAO = 204 THEN
              1
             ELSE
              0
           END) AS QTD_TEMPORARIOS
  FROM V_DADOS_CONTRATO_AVT    CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_HIST_HORAS_COLAB_AVT HR,
       VH_CARGO_CONTRATO_AVT   FN
 WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
   AND CT.COD_CONTRATO = HR.COD_CONTRATO
   AND CT.COD_CONTRATO = FN.COD_CONTRATO
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
       (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :DATA_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
   AND ORG.COD_EMP = 8
   AND ORG.COD_TIPO = 1
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   AND FN.COD_FUNCAO NOT IN (74, 75, 310, 409, 68)
   AND NOT EXISTS
 (SELECT 1
          FROM RHFP0306 AF
         WHERE AF.COD_CONTRATO = CT.COD_CONTRATO
           AND :DATA_FIM BETWEEN AF.DATA_INICIO AND AF.DATA_FIM
           AND AF.COD_CAUSA_AFAST NOT IN (6, 7, 107)
        )

 GROUP BY ORG.COD_EMP
),

BASE_CONTRATOS_EMP AS (
SELECT DISTINCT
       ORG.COD_EMP,
       ORG.COD_UNIDADE,
       CT.COD_CONTRATO,
       HR.HR_BASE_MES,
       CT.IND_DEFICIENCIA,
       M.MES_REF
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON CT.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR ON CT.COD_CONTRATO = HR.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
  JOIN MESES_REF M ON 1 = 1
 WHERE ORG.COD_EMP = 8
   AND ORG.COD_TIPO = 1
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
   AND FN.COD_FUNCAO NOT IN (74, 75, 310, 409, 68)
   AND NOT EXISTS
 (SELECT 1
          FROM RHFP0306 AF
         WHERE AF.COD_CONTRATO = CT.COD_CONTRATO
           AND M.MES_REF BETWEEN AF.DATA_INICIO AND AF.DATA_FIM
           AND AF.COD_CAUSA_AFAST NOT IN (6, 7, 107))
   AND CT.DATA_ADMISSAO <= LAST_DAY(M.MES_REF)
   AND (CT.DATA_DEMISSAO IS NULL OR CT.DATA_DEMISSAO >= M.MES_REF)
   AND M.MES_REF BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND M.MES_REF BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND M.MES_REF BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
),

TOTAL_HORAS_EMP AS (
SELECT COD_EMP,
       SUM(CASE
             WHEN IND_DEFICIENCIA = 'S' AND HR_BASE_MES > 120 THEN
              TO_NUMBER(HR_BASE_MES)
             WHEN IND_DEFICIENCIA = 'S' THEN
              0
             ELSE
              TO_NUMBER(HR_BASE_MES)
           END) AS TOTAL_HRS
  FROM BASE_CONTRATOS_EMP
 GROUP BY COD_EMP
 ORDER BY COD_EMP

),


CTE_APRENDIZES_EMP AS (
SELECT ORG.COD_EMP, COUNT(1) AS QTD_APRENDIZ
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON FN.COD_CONTRATO = ORG.COD_CONTRATO
 WHERE ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
       (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND FN.COD_FUNCAO IN (74, 75, 310, 409)
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND ORG.COD_TIPO = 1
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_EMP
),

CTE_SERVENTES_EMP AS (
SELECT ORG.COD_EMP, COUNT(1) AS QTD_SERVENTES
  FROM V_DADOS_CONTRATO_AVT CT
  JOIN VH_CARGO_CONTRATO_AVT FN ON CT.COD_CONTRATO = FN.COD_CONTRATO
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON FN.COD_CONTRATO = ORG.COD_CONTRATO
 WHERE ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
       (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND FN.COD_FUNCAO = 68
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND ORG.COD_TIPO = 1
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_EMP

),


STATUS_AFASTADOS_EMP AS (
SELECT ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFASTAMENTO
  FROM RHFP0306 AF, RHFP0300 CT, VH_EST_ORG_CONTRATO_AVT ORG
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND :DATA_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND ORG.COD_TIPO = 1
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
),


AFASTADOS_EMP AS (
SELECT ORG.COD_EMP, NVL(COUNT(AF.COD_CONTRATO), 0) AS QTD_AFASTADOS
  FROM RHFP0306                AF,
       RHFP0100                AF2,
       RHFP0323                MT,
       RHFP0115                TP,
       RHFP0121                TRAB,
       PESSOA                  PS,
       VH_EST_ORG_CONTRATO_AVT ORG
 WHERE AF.COD_CAUSA_AFAST = AF2.COD_CAUSA_AFAST
   AND AF.COD_MOTIVO = MT.COD_MOTIVO(+)
   AND MT.COD_TIPO_MOTIVO = TP.COD_TIPO_MOTIVO(+)
   AND AF.COD_PESSOA = PS.COD_PESSOA(+)
   AND AF2.COD_MOVIMENTO_TRAB = TRAB.COD_MOVIMENTO_TRAB(+)
   AND AF.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND :DATA_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND AF.COD_CAUSA_AFAST NOT IN (6, 7, 107)
   AND ORG.COD_TIPO = 1
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_EMP
),


HORAS_REALIZADAS_EMP AS (
SELECT ORG.COD_EMP, SUM(A.NUM_HORAS) AS HORAS_REAIS
  FROM RHAF1123 A
  LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
 WHERE A.DATA_OCORRENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND A.COD_OCORRENCIA = 2
   AND ORG.COD_TIPO = 1
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_EMP

),


TOTAL_CONTRATOS_EMP AS (
SELECT ORG.COD_EMP, COUNT(DISTINCT CT.COD_CONTRATO) AS TOTAL_COLABS
  FROM V_DADOS_CONTRATO_AVT    CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_HIST_HORAS_COLAB_AVT HR,
       VH_CARGO_CONTRATO_AVT   FN
 WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
   AND CT.COD_CONTRATO = HR.COD_CONTRATO
   AND CT.COD_CONTRATO = FN.COD_CONTRATO
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
       (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
   AND ORG.COD_EMP = 8
   AND ORG.COD_TIPO = 1
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)
   AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 7586, 7608)
 GROUP BY ORG.COD_EMP

),


RESULTADO_FINAL_EMP AS (
SELECT DISTINCT B.COD_EMP,
                A.COD_GRUPO,
                NULL AS COD_UNIDADE,
                NULL AS DES_FANTASIA,
                TO_CHAR(NVL(A.VALOR_VENDA_LOJA, 0), 'FM999G999G990D00') AS VLR_VENDA_BRUTA_EMP,
                I.TOTAL_HRS AS HRS_ACUM_EMP,
                TRUNC(A.VALOR_VENDA_LOJA / NULLIF(I.TOTAL_HRS, 0)) AS PRO_ACUM_EMP,
                D.HORAS_REAIS AS HRS_REALIZADAS_EMP,
                TO_CHAR(NVL(J.VLR_HRS_EXTRAS, 0), 'FM999G999G990D00') AS VLR_HRS_EXTRAS_EMP,
                TRUNC(A.VALOR_VENDA_LOJA / NULLIF(D.HORAS_REAIS, 0)) AS PROD_REALI_EMP,
                TO_CHAR(NVL(A.VDA_DOMINGO, 0), 'FM999G999G990D00') AS VLR_VENDA_DOM_EMP,
                TO_CHAR(NVL(J.VLR_BONUS_DOM, 0), 'FM999G999G990D00') AS VLR_BONUS_DOM_EMP,
                B.COLABS_PROD AS COLABS_PROD_EMP,
                H.TOTAL_COLABS AS TOTAL_COLABS_EMP,
                B.QTD_220 AS QTD_220_EMP,
                B.QTD_195 AS QTD_195_EMP,
                B.QTD_180 AS QTD_180_EMP,
                B.QTD_165 AS QTD_165_EMP,
                B.QTD_150 AS QTD_150_EMP,
                B.QTD_120 AS QTD_120_EMP,
                B.QTD_110 AS QTD_110_EMP,
                B.QTD_100 AS QTD_100_EMP,
                B.QTD_PCDS AS QTD_PCDS_EMP,
                NVL(B.QTD_TEMPORARIOS, 0) AS QTD_TEMPORARIO_EMP,
                NVL(F.QTD_APRENDIZ, 0) AS QTD_APRENDIZ_EMP,
                NVL(G.QTD_SERVENTES, 0) AS QTD_SERVENTE_EMP,
                NVL(C.QTD_AFASTADOS, 0) AS QTD_AFASTADOS_EMP
  FROM VENDAS_EMP A
  JOIN CONTRATOS_EMP B ON A.COD_EMP = B.COD_EMP
  LEFT JOIN AFASTADOS_EMP C ON C.COD_EMP = B.COD_EMP
  LEFT JOIN HORAS_REALIZADAS_EMP D ON D.COD_EMP = B.COD_EMP
  LEFT JOIN STATUS_AFASTADOS_EMP E ON E.COD_EMP = B.COD_EMP
  LEFT JOIN CTE_APRENDIZES_EMP F ON A.COD_EMP = F.COD_EMP
  LEFT JOIN CTE_SERVENTES_EMP G ON A.COD_EMP = G.COD_EMP
  LEFT JOIN TOTAL_CONTRATOS_EMP H ON A.COD_EMP = H.COD_EMP
  LEFT JOIN TOTAL_HORAS_EMP I ON A.COD_EMP = I.COD_EMP
  LEFT JOIN VLR_EXTRAS_BONUS_DOM_EMP J ON A.COD_EMP = J.COD_EMP
 WHERE E.STATUS_AFASTAMENTO = 0
)

SELECT 1 AS ORDENADOR,
       NULL AS COD_EMP,
       NULL AS COD_GRUPO,
       NULL AS QTD_MESES,
       NULL AS COD_UNIDADE,
       CAST('ÍNDICE DE PRODUTIVIDADE | ESTUDO QUADROS | Período: ' ||
            TO_CHAR(:DATA_INICIO, 'DD/MM/YYYY') || ' - ' ||
            TO_CHAR(:DATA_FIM, 'DD/MM/YYYY') AS VARCHAR2(100)) AS DES_FANTASIA,
       NULL AS VLR_VENDA_BRUTA,
       NULL AS HRS_ACUM,
       NULL AS PRO_ACUM,
       NULL AS HRS_REALIZADAS,
       NULL AS VLR_HRS_EXTRAS,
       NULL AS PROD_REALI,
       NULL AS VLR_VENDA_DOM,
       NULL AS VLR_BONUS_DOM,
       NULL AS COLABS_PROD,
       NULL AS TOTAL_COLABS,
       NULL AS QTD_220,
       NULL AS QTD_195,
       NULL AS QTD_180,
       NULL AS QTD_165,
       NULL AS QTD_150,
       NULL AS QTD_120,
       NULL AS QTD_110,
       NULL AS QTD_100,
       NULL AS QTD_PCDS,
       NULL AS QTD_TEMPORARIO,
       NULL AS QTD_APRENDIZ,
       NULL AS QTD_SERVENTE,
       NULL AS QTD_AFASTADOS
  FROM DUAL

UNION ALL

SELECT * FROM (
  SELECT 2 AS ORDENADOR,
         A.COD_EMP,
         A.COD_GRUPO,
         ROUND(MONTHS_BETWEEN(TRUNC(:DATA_FIM, 'MM'), TRUNC(:DATA_INICIO, 'MM')) + 1) AS QTD_MESES,
         A.COD_UNIDADE,
         A.DES_FANTASIA,
         A.VLR_VENDA_BRUTA,
         A.HRS_ACUM,
         A.PRO_ACUM,
         A.HRS_REALIZADAS,
         A.VLR_HORAS_EXTRAS,
         A.PROD_REALI,
         A.VLR_VENDA_DOM,
         A.VLR_BONUS_DOM,
         A.COLABS_PROD,
         A.TOTAL_COLABS,
         A.QTD_220,
         A.QTD_195,
         A.QTD_180,
         A.QTD_165,
         A.QTD_150,
         A.QTD_120,
         A.QTD_110,
         A.QTD_100,
         A.QTD_PCDS,
         A.QTD_TEMPORARIO,
         A.QTD_APRENDIZ,
         A.QTD_SERVENTE,
         A.QTD_AFASTADOS
    FROM RESULTADO_FINAL_UNI A
    LEFT JOIN RESULTADO_FINAL_EMP B ON A.COD_EMP = B.COD_EMP


  UNION ALL

  -- Linha de totais
  SELECT 3 AS ORDENADOR,
         NULL,
         NULL,
         NULL,
         NULL,
         'TOTALIZADORES',
         VLR_VENDA_BRUTA_EMP,
         HRS_ACUM_EMP,
         PRO_ACUM_EMP,
         HRS_REALIZADAS_EMP,
         VLR_HRS_EXTRAS_EMP,
         PROD_REALI_EMP,
         VLR_VENDA_DOM_EMP,
         VLR_BONUS_DOM_EMP,
         COLABS_PROD_EMP,
         TOTAL_COLABS_EMP,
         QTD_220_EMP,
         QTD_195_EMP,
         QTD_180_EMP,
         QTD_165_EMP,
         QTD_150_EMP,
         QTD_120_EMP,
         QTD_110_EMP,
         QTD_100_EMP,
         QTD_PCDS_EMP,
         QTD_TEMPORARIO_EMP,
         QTD_APRENDIZ_EMP,
         QTD_SERVENTE_EMP,
         QTD_AFASTADOS_EMP
    FROM RESULTADO_FINAL_EMP
)
ORDER BY ORDENADOR, COD_UNIDADE
