SELECT 
  /* Total geral */
  COUNT(DISTINCT COD_CONTRATO) AS QTDE_TOTAL_CONTRATOS,

  /* Gênero - Total */
  COUNT(DISTINCT CASE WHEN SEXO = 'M' THEN COD_CONTRATO END) AS QTD_MASC,
  COUNT(DISTINCT CASE WHEN SEXO = 'F' THEN COD_CONTRATO END) AS QTD_FEM,

  /* Gênero por liderança */
  COUNT(DISTINCT CASE WHEN SEXO = 'M' AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_MASC_LIDERANCA,
  COUNT(DISTINCT CASE WHEN SEXO = 'M' AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_MASC_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN SEXO = 'F' AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_FEM_LIDERANCA,
  COUNT(DISTINCT CASE WHEN SEXO = 'F' AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_FEM_NAO_LIDERANCA,

  /* Totais por liderança */
  COUNT(DISTINCT CASE WHEN IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_LIDERANCA,
  COUNT(DISTINCT CASE WHEN IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_NAO_LIDERANCA,

  /* Raça/Cor - Total */
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 6 THEN COD_CONTRATO END) AS QTD_AMARELA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 2 THEN COD_CONTRATO END) AS QTD_BRANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 4 THEN COD_CONTRATO END) AS QTD_PRETA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 8 THEN COD_CONTRATO END) AS QTD_PARDA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 1 THEN COD_CONTRATO END) AS QTD_INDIGENA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR NOT IN (1,2,4,6,8) OR COD_RACA_COR IS NULL THEN COD_CONTRATO END) AS QTD_COR_NAO_RESPONDIDA,

  /* === Raça/Cor por Liderança === */
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 6 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_AMARELA_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 2 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_BRANCA_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 4 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_PRETA_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 8 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_PARDA_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 1 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_INDIGENA_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 9 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTD_RACA_OUTRAS_LIDERANCA,
  
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 6 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_AMARELA_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 2 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_BRANCA_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 4 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_PRETA_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 8 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_PARDA_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 1 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_INDIGENA_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 9 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTD_RACA_OUTRAS_NAO_LIDERANCA,
  
  /*RAÇA/COR/SEXO */  
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 6 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTD_AMARELA_M,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 2 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTD_BRANCA_M,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 4 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTD_PRETA_M,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 8 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTD_PARDA_M,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 1 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTD_INDIGENA_M,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 9 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTD_RACA_OUTRAS_M,
  
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 6 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTD_AMARELA_F,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 2 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTD_BRANCA_F,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 4 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTD_PRETA_F,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 8 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTD_PARDA_F,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 1 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTD_INDIGENA_F,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 9 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTD_RACA_OUTRAS_F,


  /* === Faixa Etária - Total === */
  COUNT(DISTINCT CASE WHEN IDADE <= 30 THEN COD_CONTRATO END) AS QTDE_ATE_30,
  COUNT(DISTINCT CASE WHEN IDADE > 30 AND IDADE < 50 THEN COD_CONTRATO END) AS QTDE_30_50,
  COUNT(DISTINCT CASE WHEN IDADE >= 50 THEN COD_CONTRATO END) AS QTDE_50_MAIS,
  

  /* === Faixa Etária - Liderança === */
  COUNT(DISTINCT CASE WHEN IDADE <= 30 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_LIDERANCA_ATE_30,
  COUNT(DISTINCT CASE WHEN IDADE > 30 AND IDADE < 50 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_LIDERANCA_30_50,
  COUNT(DISTINCT CASE WHEN IDADE >= 50 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_LIDERANCA_50,
  
  COUNT(DISTINCT CASE WHEN IDADE <= 30 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_ATE_30_F,
  COUNT(DISTINCT CASE WHEN IDADE > 30 AND IDADE < 50 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_30_50_F,
  COUNT(DISTINCT CASE WHEN IDADE >= 50 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_50_MAIS_F,
 

  /* === Faixa Etária - Não liderança === */
  COUNT(DISTINCT CASE WHEN IDADE <= 30 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_NAO_LIDERANCA_ATE_30,
  COUNT(DISTINCT CASE WHEN IDADE > 30 AND IDADE < 50 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_NAO_LIDERANCA_30_50,
  COUNT(DISTINCT CASE WHEN IDADE >= 50 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_NAO_LIDERANCA_50,
  
  COUNT(DISTINCT CASE WHEN IDADE <= 30 AND IS_LIDERANCA = 1 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_ATE_30_M,
  COUNT(DISTINCT CASE WHEN IDADE > 30 AND IDADE < 50 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_30_50_M,
  COUNT(DISTINCT CASE WHEN IDADE >= 50 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_50_MAIS_M,
  

  /* === Pessoas com Deficiência === */
  COUNT(DISTINCT CASE WHEN IND_DEFICIENCIA = 'S' THEN COD_CONTRATO END) AS QTDE_PCD_TOTAL,  
  COUNT(DISTINCT CASE WHEN IND_DEFICIENCIA = 'S' AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_PCD_LIDERANCA,  
  COUNT(DISTINCT CASE WHEN IND_DEFICIENCIA = 'S' AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_PCD_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN IND_DEFICIENCIA = 'S' AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_PCD_F,
  COUNT(DISTINCT CASE WHEN IND_DEFICIENCIA = 'S' AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_PCD_M,
  
  COUNT(DISTINCT CASE WHEN IND_DEFICIENCIA <> 'S' OR IND_DEFICIENCIA IS NULL THEN COD_CONTRATO END) AS QTDE_SEM_PCD_TOTAL,  
  COUNT(DISTINCT CASE WHEN (IND_DEFICIENCIA <> 'S' OR IND_DEFICIENCIA IS NULL) AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_SEM_PCD_LIDERANCA,  
  COUNT(DISTINCT CASE WHEN (IND_DEFICIENCIA <> 'S' OR IND_DEFICIENCIA IS NULL) AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_SEM_PCD_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN (IND_DEFICIENCIA <> 'S' OR IND_DEFICIENCIA IS NULL) AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_SEM_PCD_F,
  COUNT(DISTINCT CASE WHEN (IND_DEFICIENCIA <> 'S' OR IND_DEFICIENCIA IS NULL) AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_SEM_PCD_M,
  
  /* === Por Grau de Escolaridade*/
  
 ----COM LIDERANÇA
  
  --FUNDAMENTAL INCOMPLETO COD 2
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 2 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_2_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 2 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_2_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 2 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_2_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 2 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_2_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 2 THEN COD_CONTRATO END) AS QTDE_INSTU_2_TOT,
																
    --FUNDAMENTAL INCOMPLETO COD 3                              
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 3 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_3_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 3 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_3_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 3 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_3_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 3 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_3_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 3 THEN COD_CONTRATO END) AS QTDE_INSTU_3_TOT,
																
    --FUNDAMENTAL INCOMPLETO COD 4                              
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 4 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_4_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 4 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_4_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 4 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_4_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 4 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_4_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 4 THEN COD_CONTRATO END) AS QTDE_INSTU_4_TOT,
																
    --FUNDAMENTAL COMPLETO COD 5                                
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 5 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_5_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 5 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_5_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 5 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_5_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 5 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_5_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 5 THEN COD_CONTRATO END) AS QTDE_INSTU_5_TOT,
																
    --MÉDIO INCOMPLETO COD 6                                    
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 6 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_6_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 6 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_6_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 6 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_6_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 6 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_6_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 6 THEN COD_CONTRATO END) AS QTDE_INSTU_6_TOT,
																
    --MÉDIO COMPLETO COD 7                                      
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 7 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_7_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 7 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_7_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 7 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_7_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 7 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_7_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 7 THEN COD_CONTRATO END) AS QTDE_INSTU_7_TOT,
																
    --SUPERIOR INCOMPLETO COD 8                                 
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 8 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_8_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 8 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_8_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 8 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_8_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 8 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_8_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 8 THEN COD_CONTRATO END) AS QTDE_INSTU_8_TOT,
																
    --SUPERIOR COMPLETO COD 9                                   
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 9 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_9_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 9 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_9_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 9 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_9_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 9 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_9_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 9 THEN COD_CONTRATO END) AS QTDE_INSTU_9_TOT,
																
    --MESTRADO INCOMPLETO COD 10                                  
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 10 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_10_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 10 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_10_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 10 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_10_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 10 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_10_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 10 THEN COD_CONTRATO END) AS QTDE_INSTU_10_TOT,
  
   --MESTRADO COMPLETO COD 11                                 
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 11 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_11_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 11 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_11_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 11 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_11_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 11 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_11_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 11 THEN COD_CONTRATO END) AS QTDE_INSTU_11_TOT,
  
    --MESTRADO INCOMPLETO COD 12                                
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 12 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_12_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 12 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_12_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 12 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_12_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 12 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_12_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 12 THEN COD_CONTRATO END) AS QTDE_INSTU_12_TOT,
  
    --MESTRADO INCOMPLETO COD 13                                 
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 13 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_13_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 13 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_13_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 13 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_13_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 13 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_13_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 13 THEN COD_CONTRATO END) AS QTDE_INSTU_13_TOT,

    --DOUTORADO INCOMPLETO COD 14                                 
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 14 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_14_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 14 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_14_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 14 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_14_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 14 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_14_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 14 THEN COD_CONTRATO END) AS QTDE_INSTU_14_TOT,

    --DOUTORADO COMPLETO COD 15                                 
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 15 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_15_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 15 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_15_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 15 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_15_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 15 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_15_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 15 THEN COD_CONTRATO END) AS QTDE_INSTU_15_TOT,

    --PÓS-DOUTORADO INCOMPLETO COD 16                                 
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 16 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_16_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 16 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_16_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 16 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_16_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 16 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_16_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 16 THEN COD_CONTRATO END) AS QTDE_INSTU_16_TOT,

    --PÓS-DOUTORADO COMPLETO COD 17                                 
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 17 AND IS_LIDERANCA = 1 THEN COD_CONTRATO END) AS QTDE_INSTU_17_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 17 AND IS_LIDERANCA = 0 THEN COD_CONTRATO END) AS QTDE_INSTU_17_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 17 AND SEXO = 'F' THEN COD_CONTRATO END) AS QTDE_INSTU_17_F,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 17 AND SEXO = 'M' THEN COD_CONTRATO END) AS QTDE_INSTU_17_M,
  COUNT(DISTINCT CASE WHEN COD_INSTRUCAO = 17 THEN COD_CONTRATO END) AS QTDE_INSTU_17_TOT,
  

  /* === Localização Geográfica (fixas) === */
  0 AS QTDE_NORTE,
  0 AS QTDE_NORDESTE,
  0 AS QTDE_CENTRO_OESTE,
  0 AS QTDE_SUDESTE,
  --SUL
  COUNT(DISTINCT CASE WHEN IS_LIDERANCA = 1 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_LIDERANCA,
  COUNT(DISTINCT CASE WHEN IS_LIDERANCA = 0 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_TOTAL,
  
  --EXTERIOR
  COUNT(DISTINCT CASE WHEN IS_LIDERANCA = 1 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_LIDERANCA,
  COUNT(DISTINCT CASE WHEN IS_LIDERANCA = 0 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_NAO_LIDERANCA,
  COUNT(DISTINCT CASE WHEN COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_TOTAL,
 -- 0 AS QTDE_EXTERIOR,


  /* === Localização + Cor === */
  --SUL
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 6 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_AMARELA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 2 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_BRANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 4 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_PRETA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 8 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_PARDA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 1 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_INDIGENA,  
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 9 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_OUTRAS,
  
  --EXTERIOR
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 6 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_AMARELA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 2 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_BRANCA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 4 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_PRETA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 8 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_PARDA,
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 1 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_INDIGENA,  
  COUNT(DISTINCT CASE WHEN COD_RACA_COR = 9 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_OUTRAS,

  0 AS QTDE_DEMAIS_REG_COR,

  /* Localização + Faixa Etária */
  --SUL
  COUNT(DISTINCT CASE WHEN IDADE <= 30 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_ATE_30,
  COUNT(DISTINCT CASE WHEN IDADE > 30 AND IDADE < 50 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_30_50,
  COUNT(DISTINCT CASE WHEN IDADE >= 50 AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_50_MAIS,
  
  --EXTERIOR
  COUNT(DISTINCT CASE WHEN IDADE <= 30 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_ATE_30,
  COUNT(DISTINCT CASE WHEN IDADE > 30 AND IDADE < 50 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_30_50,
  COUNT(DISTINCT CASE WHEN IDADE >= 50 AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_50_MAIS,

  0 AS QTDE_DEMAIS_REG_ATE_30, 
  0 AS QTDE_DEMAIS_REG_30_50, 
  0 AS QTDE_DEMAIS_REG_50_MAIS,

  /* Localização + Gênero */
  --SUL
  COUNT(DISTINCT CASE WHEN SEXO = 'F' AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_FEMININO,
  COUNT(DISTINCT CASE WHEN SEXO = 'M' AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_MASCULINO,
  COUNT(DISTINCT CASE WHEN SEXO IN ('F','M') AND COD_NACIONALIDADE = 10 THEN COD_CONTRATO END) AS QTDE_SUL_FEM_MASC,
  
  --EXTERIOR
  COUNT(DISTINCT CASE WHEN SEXO = 'F' AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_FEMININO,
  COUNT(DISTINCT CASE WHEN SEXO = 'M' AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_MASCULINO,
  COUNT(DISTINCT CASE WHEN SEXO IN ('F','M') AND COD_NACIONALIDADE <> 10 THEN COD_CONTRATO END) AS QTDE_EXTERIOR_FEM_MASC,

  0 AS QTDE_LOCAL_FEM_MASC

FROM (
  SELECT 
    A.*,
    CASE
      WHEN (
        A.DES_FUNCAO LIKE '%CHEFE DE SECAO%' OR 
        A.DES_FUNCAO LIKE '%GERENTE%' OR 
        A.DES_FUNCAO LIKE '%SUPERVISOR%' OR 
        A.DES_FUNCAO LIKE '%DIRETOR%'
      ) AND A.DES_FUNCAO NOT LIKE '%ACESSOR DE DIRETORIA%'
      THEN 1 ELSE 0 
    END AS IS_LIDERANCA
  FROM V_DADOS_COLAB_AVT A
  WHERE A.STATUS = 0 AND A.COD_EMP = 8
) SUB

