/* ====================== PARÂMETROS E DIMENSÃO DE MESES ====================== */
WITH
PARAMS AS (
  SELECT
    TRUNC(:DATA_INICIO, 'MM') AS DATA_INICIO,
    TRUNC(:DATA_FIM,     'MM') AS DATA_FIM,
    ADD_MONTHS(TRUNC(:DATA_INICIO, 'MM'), LEVEL-1)           AS DATA_MES,
    LAST_DAY(ADD_MONTHS(TRUNC(:DATA_INICIO, 'MM'), LEVEL-1)) AS DATA_MES_FIM
  FROM DUAL
  CONNECT BY LEVEL <= MONTHS_BETWEEN(TRUNC(:DATA_FIM,'MM'), TRUNC(:DATA_INICIO,'MM')) + 1
),

/* ====================== SNAPSHOT CONTRATO x MÊS (1 linha por contrato/mês) ====================== */
DIM AS (
  SELECT
    CT.STATUS,
    CT.COD_CONTRATO,
    CT.DES_PESSOA,
    CT.DATA_NASCIMENTO,
    CT.DATA_ADMISSAO,
    CT.DATA_DEMISSAO,
    FN.COD_FUNCAO,
    FN.DES_FUNCAO,
    FN.DATA_INI_CLH,
    FN.DATA_FIM_CLH,
    HR.HR_BASE_MES,
    HR.DATA_INI_HR,
    HR.DATA_FIM_HR,
    CT.IND_DEFICIENCIA,
    CT.SEXO,
    ORG.COD_EMP,
    ORG.EDICAO_EMP,
    ORG.DES_EMP,
    ORG.COD_ORGANOGRAMA,
    ORG.COD_UNIDADE,
    ORG.DES_UNIDADE,
    ORG.DATA_INI_ORG,
    ORG.DATA_FIM_ORG,
    CASE WHEN ORG.COD_TIPO IN (2,3) THEN ORG.EDICAO_ORG_3 ELSE ORG.COD_UNIDADE END AS COD_FILIAL,
    CASE WHEN ORG.COD_TIPO IN (2,3) THEN ORG.NOME3        ELSE ORG.DES_UNIDADE END AS DES_FILIAL,
    CASE WHEN ORG.COD_TIPO IN (2,3) THEN ORG.EDICAO_ORG_4 ELSE ORG.COD_UNIDADE END AS COD_DIVISAO,
    CASE WHEN ORG.COD_TIPO IN (2,3) THEN ORG.NOME4        ELSE ORG.DES_UNIDADE END AS DES_DIVISAO,
    ORG.COD_REDE,
    ORG.DES_REDE,
    ORG.COD_TIPO,
    ORG.DES_TIPO,
    P.DATA_MES,
    P.DATA_MES_FIM,
    TO_CHAR(P.DATA_MES,'MM/YYYY') AS MES_ANO,
    TO_CHAR(P.DATA_MES,'fmMonth YYYY','NLS_DATE_LANGUAGE=PORTUGUESE') AS MES_ANO_EXTENSO,
    /* expor início/fim do período como colunas */
    P.DATA_INICIO,
    P.DATA_FIM
  FROM V_DADOS_CONTRATO_AVT    CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON ORG.COD_CONTRATO = CT.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR  ON HR.COD_CONTRATO  = CT.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT   FN  ON FN.COD_CONTRATO  = CT.COD_CONTRATO
  JOIN PARAMS P ON 1=1
  WHERE ORG.COD_EMP = 8
    AND ORG.EDICAO_ORG_4 IS NOT NULL
    /* contrato vigente em algum dia do mês */
    AND CT.DATA_ADMISSAO <= P.DATA_MES_FIM
    AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31') >= P.DATA_MES
    /* vigências no mês (sargável) */
    AND P.DATA_MES BETWEEN ORG.DATA_INI_ORG AND NVL(ORG.DATA_FIM_ORG, DATE '2999-12-31')
    AND P.DATA_MES BETWEEN FN.DATA_INI_CLH  AND NVL(FN.DATA_FIM_CLH , DATE '2999-12-31')
    AND P.DATA_MES BETWEEN HR.DATA_INI_HR   AND NVL(HR.DATA_FIM_HR  , DATE '2999-12-31')
),

/* ====================== HORAS TRABALHADAS (turno != 85 e afastamento permitido) ====================== */
H AS (
  SELECT
    D.COD_CONTRATO,
    D.DATA_MES,
    SUM(CASE WHEN HM.COD_OCORRENCIA = 2 THEN HM.NUM_HORAS ELSE 0 END) AS TOT_HORAS_TRAB
  FROM DIM D
  JOIN RHAF1123 HM
    ON HM.COD_CONTRATO = D.COD_CONTRATO
   AND HM.DATA_OCORRENCIA >= D.DATA_MES
   AND HM.DATA_OCORRENCIA <  ADD_MONTHS(D.DATA_MES, 1)
  JOIN RHAF1119 TU
    ON TU.COD_CONTRATO = D.COD_CONTRATO
   AND TU.DATA_INICIO <= D.DATA_MES_FIM
   AND NVL(TU.DATA_FIM, DATE '2999-12-31') >= D.DATA_MES
   AND TU.COD_TURNO <> 85
  LEFT JOIN RHFP0306 AF
    ON AF.COD_CONTRATO = D.COD_CONTRATO
   AND AF.DATA_INICIO <= D.DATA_MES_FIM
   AND NVL(AF.DATA_FIM, DATE '2999-12-31') >= D.DATA_MES
  WHERE NVL(AF.COD_CAUSA_AFAST, 0) IN (0,6,7)
  GROUP BY D.COD_CONTRATO, D.DATA_MES
),

/* ====================== FALTAS / ATESTADOS ====================== */
A1 AS (
  SELECT
    D.COD_CONTRATO,
    D.DATA_MES,
    SUM(CASE WHEN C.COD_VD = 632 THEN C.QTDE_VD ELSE 0 END) AS TOT_FALTAS,
    SUM(CASE WHEN C.COD_VD = 897 THEN C.QTDE_VD ELSE 0 END) AS TOT_ATESTADOS,
    SUM(CASE WHEN C.COD_VD IN (632,897) THEN C.QTDE_VD ELSE 0 END) AS TOT_FALTAS_ATESTADOS
  FROM DIM D
  JOIN RHFP1006 C
    ON C.COD_CONTRATO = D.COD_CONTRATO
  JOIN RHFP1003 E
    ON E.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
   AND E.DATA_REFERENCIA >= D.DATA_MES
   AND E.DATA_REFERENCIA <  ADD_MONTHS(D.DATA_MES, 1)
  WHERE E.COD_ORGANOGRAMA = 8
  GROUP BY D.COD_CONTRATO, D.DATA_MES
)

/* ====================== RESULTADO ====================== */
SELECT
  D.COD_ORGANOGRAMA,
  D.COD_CONTRATO,
  D.DES_PESSOA,
  D.COD_UNIDADE,
  D.DES_UNIDADE,
  D.COD_REDE,
  D.DES_REDE,
  D.COD_TIPO,
  D.MES_ANO,
  D.MES_ANO_EXTENSO,
  ROUND(NVL(H.TOT_HORAS_TRAB, 0), 2)        AS TOT_HR_TRAB_UNI,
  ROUND(NVL(A1.TOT_FALTAS, 0), 2)           AS TOT_FALTAS_UNI,
  ROUND(NVL(A1.TOT_ATESTADOS, 0), 2)        AS TOT_ATESTADOS_UNI,
  ROUND(NVL(A1.TOT_FALTAS_ATESTADOS, 0), 2) AS TOT_FT_ATEST_UNI,
  NVL(ROUND(NVL(A1.TOT_FALTAS_ATESTADOS, 0) * 100 /
            NULLIF(NVL(H.TOT_HORAS_TRAB, 0), 0), 2), 0) AS PERC_ABSENTEISMO_UNI,
  SYSDATE AS DATA_SISTEMA,
  D.DATA_INICIO,
  D.DATA_FIM
FROM DIM D
LEFT JOIN H  ON H.COD_CONTRATO  = D.COD_CONTRATO AND H.DATA_MES  = D.DATA_MES
LEFT JOIN A1 ON A1.COD_CONTRATO = D.COD_CONTRATO AND A1.DATA_MES = D.DATA_MES
/* filtros opcionais com binds — ordem “short-circuit” para manter sargabilidade */
WHERE (:TIPO   = 0 OR D.COD_TIPO    = :TIPO)
  AND (:FILIAL = 0 OR D.COD_UNIDADE = :FILIAL)
  AND (:REDE   = 0 OR D.COD_REDE    = TO_CHAR(:REDE))
ORDER BY D.COD_TIPO, D.DES_UNIDADE, D.DATA_MES;
