CREATE OR REPLACE FUNCTION FN_STATUS_AFASTAMENTO (
  P_COD_CONTRATO     IN NUMBER,
  P_DATA_REFERENCIA  IN DATE
) RETURN VARCHAR2
IS
  V_STATUS VARCHAR2(1) := 'N';
BEGIN
  FOR R IN (
    SELECT 1
    FROM RHFP0306 AF
    WHERE AF.COD_CONTRATO = P_COD_CONTRATO
      AND P_DATA_REFERENCIA BETWEEN AF.DATA_INICIO AND NVL(AF.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
  ) LOOP
    V_STATUS := 'S';
    EXIT;
  END LOOP;

  RETURN V_STATUS;
END;
/
