/*RELAÇÃO DA MONTAGEM CONTÁBIL NA FOLHA*/
SELECT NULL AS COD_CLASSE_CONT,
       NULL AS NOME_CLASSE_CONT,
       NULL AS COD_TOTAL,
       NULL AS NOME_TOTAL,
       'RELAÇÃO CONTABIL ATUALIZADA - ' || TO_CHAR(SYSDATE, 'dd/mm/yyyy') AS ESPAÇO,
       NULL AS COD_VD,
       NULL AS NOME_VD,
       NULL AS COD_CONTA_CONTABIL,
       NULL AS NOME_CONTA_CONTABIL,
       NULL AS COD_CONTRAPARTIDA,
       NULL AS TIPO_LANCAMENTO,
       NULL AS COD_HISTORICO,
       NULL AS DES_HISTORICO 
FROM DUAL


UNION ALL 

SELECT NULL AS COD_CLASSE_CONT,
       NULL AS NOME_CLASSE_CONT,
       NULL AS COD_TOTAL,
       NULL AS NOME_TOTAL,
       NULL AS ESPAÇO,
       NULL AS COD_VD,
       NULL AS NOME_VD,
       NULL AS COD_CONTA_CONTABIL,
       NULL AS NOME_CONTA_CONTABIL,
       NULL AS COD_CONTRAPARTIDA,
       NULL AS TIPO_LANCAMENTO,
       NULL AS COD_HISTORICO,
       NULL AS DES_HISTORICO 
FROM DUAL

UNION ALL

SELECT COD_CLASSE_CONT,
       NOME_CLASSE_CONT,
       COD_TOTAL,
       NOME_TOTAL,
       ' ' AS ESPAÇO,
       COD_VD,
       NOME_VD,
       COD_CONTA_CONTABIL,
       NOME_CONTA_CONTABIL,
       COD_CONTRAPARTIDA,
       TIPO_LANCAMENTO,
       COD_HISTORICO,
       DES_HISTORICO 
FROM V_DADOS_CONTABIL_AVT
WHERE COD_CLASSE_CONT = 21

UNION ALL 

SELECT NULL AS COD_CLASSE_CONT,
       NULL AS NOME_CLASSE_CONT,
       NULL AS COD_TOTAL,
       NULL AS NOME_TOTAL,
       NULL AS ESPAÇO,
       NULL AS COD_VD,
       NULL AS NOME_VD,
       NULL AS COD_CONTA_CONTABIL,
       NULL AS NOME_CONTA_CONTABIL,
       NULL AS COD_CONTRAPARTIDA,
       NULL AS TIPO_LANCAMENTO,
       NULL AS COD_HISTORICO,
       NULL AS DES_HISTORICO 
FROM DUAL

UNION ALL

SELECT COD_CLASSE_CONT,
       NOME_CLASSE_CONT,
       COD_TOTAL,
       NOME_TOTAL,
       ' ' AS ESPAÇO,
       COD_VD,
       NOME_VD,
       COD_CONTA_CONTABIL,
       NOME_CONTA_CONTABIL,
       COD_CONTRAPARTIDA,
       TIPO_LANCAMENTO,
       COD_HISTORICO,
       DES_HISTORICO 
FROM V_DADOS_CONTABIL_AVT
WHERE COD_CLASSE_CONT = 22

UNION ALL 

SELECT NULL AS COD_CLASSE_CONT,
       NULL AS NOME_CLASSE_CONT,
       NULL AS COD_TOTAL,
       NULL AS NOME_TOTAL,
       NULL AS ESPAÇO,
       NULL AS COD_VD,
       NULL AS NOME_VD,
       NULL AS COD_CONTA_CONTABIL,
       NULL AS NOME_CONTA_CONTABIL,
       NULL AS COD_CONTRAPARTIDA,
       NULL AS TIPO_LANCAMENTO,
       NULL AS COD_HISTORICO,
       NULL AS DES_HISTORICO 
FROM DUAL

UNION ALL

SELECT COD_CLASSE_CONT,
       NOME_CLASSE_CONT,
       COD_TOTAL,
       NOME_TOTAL,
       ' ' AS ESPAÇO,
       COD_VD,
       NOME_VD,
       COD_CONTA_CONTABIL,
       NOME_CONTA_CONTABIL,
       COD_CONTRAPARTIDA,
       TIPO_LANCAMENTO,
       COD_HISTORICO,
       DES_HISTORICO 
FROM V_DADOS_CONTABIL_AVT
WHERE COD_CLASSE_CONT = 23
