WITH
CONTRATOS AS (
  SELECT DISTINCT CT.STATUS,
                  CT.COD_CONTRATO,
                  CT.DES_PESSOA,
                  CT.DATA_ADMISSAO,
                  CT.DATA_DEMISSAO,
                  FN.COD_FUNCAO,
                  FN.DES_FUNCAO,
                  HR.HR_BASE_MES,
                  CT.IND_DEFICIENCIA,
                  CT.SEXO,
                  ORG.COD_EMP,
                  ORG.EDICAO_EMP,
                  ORG.DES_EMP,
                  ORG.COD_UNIDADE,
                  ORG.DES_UNIDADE,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_3
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME3
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_4
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_DIVISAO,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME4
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_DIVISAO,
                  ORG.COD_REDE,
                  ORG.DES_REDE,
                  ORG.COD_TIPO,
                  ORG.DES_TIPO
    FROM V_DADOS_CONTRATO_AVT CT,
         VH_EST_ORG_CONTRATO_AVT ORG,
         VH_HIST_HORAS_COLAB_AVT HR,
         VH_CARGO_CONTRATO_AVT FN
   WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
     AND CT.COD_CONTRATO = HR.COD_CONTRATO
     AND CT.COD_CONTRATO = FN.COD_CONTRATO
     AND ((:DATA_REFERENCIA BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
          (CT.DATA_ADMISSAO <= :DATA_REFERENCIA AND CT.DATA_DEMISSAO IS NULL))
     AND :DATA_REFERENCIA BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
     AND :DATA_REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
     AND :DATA_REFERENCIA BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
     AND ORG.COD_EMP = 8
     AND ORG.EDICAO_ORG_4 IS NOT NULL
   --ORDER BY ORG.COD_TIPO, ORG.COD_REDE, ORG.COD_UNIDADE, CT.COD_CONTRATO
),

STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       PF.NOME_PESSOA,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST,
       NA.NOME_CAUSA_AFAST AS DES_AFAST,
       AF.DATA_INICIO AS DATA_INI_AFAST,
       AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN,
       RHFP0100 NA,
       PESSOA_FISICA PF
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND AF.COD_CAUSA_AFAST = NA.COD_CAUSA_AFAST(+)
   AND CT.COD_FUNC = PF.COD_PESSOA(+)
   AND ((:DATA_REFERENCIA BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= :DATA_REFERENCIA AND CT.DATA_FIM IS NULL))
   AND :DATA_REFERENCIA BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_REFERENCIA BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND :DATA_REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   AND ORG.COD_EMP = 8
   --AND ORG.COD_TIPO = 1
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608) --657 essa ainda irá inaugurar em agosto
 --ORDER BY ORG.COD_UNIDADE

),


INFORMACOES_CONTRATO AS (
SELECT
  COD_CONTRATO,
  MAX(CASE WHEN COD_CAMPO = 11 THEN CONT_ALFA END) AS NIVEL_SALARIO,
  MAX(CASE WHEN COD_CAMPO = 10 THEN CONT_ALFA END) AS DATA_NIVEL

FROM RHFP0308
WHERE COD_CAMPO IN (10, 11)
  --AND COD_CONTRATO = 389622
GROUP BY COD_CONTRATO
),


MOVIMENTOS AS (
SELECT COD_CONTRATO,
       MAX(CASE
             WHEN COD_EVENTO = 1 AND COD_VD = 905 AND DATA_MOV >= TRUNC(SYSDATE) AND
                  VALOR_VD > 0 THEN
              VALOR_VD
           END) AS ANTECIPACAO,
       MAX(CASE
             WHEN COD_EVENTO = 1 AND COD_VD = 935 AND DATA_MOV >= TRUNC(SYSDATE) AND
                  VALOR_VD > 0 THEN
              VALOR_VD
           END) AS GRATIFICACAO
  FROM RHFP1004
 WHERE DATA_MOV >= TRUNC(SYSDATE)
   AND COD_VD IN (905, 935)
 GROUP BY COD_CONTRATO

),


-- 1. TOTAL LOJAS
RESULTADO_FINAL AS (
SELECT A.COD_CONTRATO || ' - ' || A.DES_PESSOA AS COLABORADOR,
       A.DATA_ADMISSAO,
       A.DES_FUNCAO,
       B.NIVEL_SALARIO,
       B.DATA_NIVEL,
       TO_CHAR(D.VALOR_SALARIO, 'FM999G999G999D90') AS SALARIO,
       TO_CHAR(C.ANTECIPACAO, 'FM999G999G999D90') AS ANTECIPACAO,
       TO_CHAR(C.GRATIFICACAO, 'FM999G999G999D90') AS GRATIFICACAO,
       /* aqui assumimos que C.ANTECIPACAO e C.GRATIFICACAO são NUMÉRICOS */
       TO_CHAR(NVL(D.VALOR_SALARIO, 0) + NVL(C.ANTECIPACAO, 0) +
               NVL(C.GRATIFICACAO, 0),
               'FM999G999G999D90') AS SALARIO_TOTAL,
       A.COD_UNIDADE,
       A.DES_UNIDADE,
       A.COD_REDE,
       A.DES_REDE,
       A.COD_TIPO
  FROM CONTRATOS A
  LEFT JOIN INFORMACOES_CONTRATO B ON A.COD_CONTRATO = B.COD_CONTRATO
  LEFT JOIN MOVIMENTOS C ON A.COD_CONTRATO = C.COD_CONTRATO
  JOIN RHFP0608 D ON A.COD_CONTRATO = D.COD_CONTRATO
                 AND D.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY')
  LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
 WHERE (:NIVEL = '0' -- tudo
       OR (:NIVEL = 'S' AND B.NIVEL_SALARIO IS NOT NULL) OR
       (:NIVEL = 'N' AND B.NIVEL_SALARIO IS NULL))
      
   AND (:GERENTE = '0' -- sem filtro
       OR (:GERENTE = 'S' AND (A.DES_FUNCAO LIKE '%GERENTE%' OR
       A.DES_FUNCAO LIKE '%SUPERVISOR%' OR
       A.DES_FUNCAO LIKE '%DIRETOR%')) OR
       (:GERENTE = 'N' AND NOT (A.DES_FUNCAO LIKE '%GERENTE%' OR
        A.DES_FUNCAO LIKE '%SUPERVISOR%' OR
        A.DES_FUNCAO LIKE '%DIRETOR%')))
      
   AND (A.COD_TIPO = :TIPO OR :TIPO = 0)
   AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (A.COD_REDE = :REDE OR :REDE = 0)

 )

  SELECT A.*,
   :DATA_REFERENCIA AS REFERENCIA,
   'TIPO: ' || :TIPO || ' | ' || 'UNIDADE: ' || :UNIDADE ||
   ' | ' || 'REDE: ' || :REDE || ' | ' || 'NIVEL? ' || :NIVEL AS PARAMETROS_USADOS
  
    FROM RESULTADO_FINAL A
   ORDER BY A.COD_TIPO, -- se precisar manter a ordem por tipo
      A.COD_REDE,
      A.COD_UNIDADE,
      A.COLABORADOR
