SELECT 
    COD_CONTRATO,
    DES_PESSOA,
    DES_FUNCAO,
    DES_UNIDADE,
    DES_REDE_LOCAL,
    DATA_ADMISSAO,
    DATA_AVANCO,
    TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO) / 12) || ' anos e ' || 
    TRUNC(MOD(MONTHS_BETWEEN(SYSDATE, DATA_AVANCO), 12)) || ' meses' AS TEMPO_AVANCO
FROM 
    V_DADOS_COLAB_AVT
WHERE 
    STATUS = 0
    AND COD_EMP = 8
    AND STATUS_AFAST IN ('EM ATIVIDADE', 'EM FÉRIAS', 'AFASTADO TEMP')
    AND DATA_AVANCO <= :DATA_REFERENCIA
ORDER BY DES_UNIDADE
