SELECT DISTINCT AFS.COD_CONTRATO,
                AFS.COD_VD,
                AFS.TIPO_INF_VD,
                AFS.PRESTACAO_VD,
                AFS.QTDE_VD,
                AFS.VALOR_VD,
                AFS.COD_ORIGEM_MOV,
                MS.COD_MESTRE_EVENTO,
                MS.DATA_REFERENCIA
  FROM RHFP1006 AFS, RHFP1003 MS, RHFP0306 AF
 WHERE AFS.COD_MESTRE_EVENTO = MS.COD_MESTRE_EVENTO
   AND AF.COD_CONTRATO = AFS.COD_CONTRATO
   AND AF.COD_CAUSA_AFAST = 6
   AND AFS.COD_VD = 897
   AND MS.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND AF.COD_CID_10 IN ('J11', 'Z20.9', 'Z29.0', 'B34.2', 'B34.9')
   AND AF.DATA_INICIO BETWEEN MS.DATA_INI_MOV AND MS.DATA_FIM_MOV
 GROUP BY AFS.COD_CONTRATO,
          AFS.COD_VD,
          AFS.TIPO_INF_VD,
          AFS.PRESTACAO_VD,
          AFS.QTDE_VD,
          AFS.VALOR_VD,
          AFS.COD_ORIGEM_MOV,
          MS.COD_MESTRE_EVENTO,
          MS.DATA_REFERENCIA
 ORDER BY AFS.COD_CONTRATO, MS.DATA_REFERENCIA ASC