SELECT CT.COD_CONTRATO || ' - ' || PF.NOME_PESSOA AS COLABORADOR,
       SUBSTR(LPAD(PF.CPF, 11, '0'), 1, 3) || '.' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 4, 3) || '.' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 7, 3) || '-' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 10, 2) AS CPF_FORMATADO,
       B.EDICAO_ORG_2 || ' - ' || B.NOME2 AS EMPRESA,
       B.EDICAO_ORG || ' - ' || B.NOME_ORGANOGRAMA AS FILIAL,
       213901 AS CONTA_CONTABIL,

       CT.COD_BCO_PGTO || ' - ' || BC.DES_BANCO || ' / ' || 
CT.COD_AGE_PGTO || CASE
         WHEN AG.DIGITO IS NOT NULL THEN
          ' - ' || AG.DIGITO
         ELSE
          ''
       END AS BANCO_AGE,

       AG.DES_AGENCIA,
       CT.NRO_CONTA_PGTO AS NUM_CONTA,       
       TO_CHAR(SUM(VLR6.VALOR_VD), 'FM999G999G990D00') AS 
VALOR_RESCISAO,

       -- Total geral do período e empresa
       TO_CHAR(SUM(SUM(VLR6.VALOR_VD)) OVER (), 'FM999G999G990D00') AS 
TOTAL_GERAL,

       EV6.COD_EVENTO,
       DEV.NOME_EVENTO,
       EV6.COD_MESTRE_EVENTO,
       EV6.SITUACAO_PROCESSO,
       REC.DATA_PAGAMENTO,
       -- Quantidade de funcionários (contratos distintos)
       COUNT(DISTINCT CT.COD_CONTRATO) OVER () AS TOTAL_FUNCIONARIOS,

       UPPER(TO_CHAR(EV6.DATA_REFERENCIA, 'MONTH')) || '/' || TO_CHAR
(EV6.DATA_REFERENCIA, 'YYYY') AS REFERENCIA
       
FROM RHFP0300 CT
LEFT JOIN V_DADOS_BANCOS_AVT BC ON CT.COD_BCO_PGTO = BC.COD_BANCO
LEFT JOIN V_AGENCIAS_BANCOS_AVT AG ON CT.COD_AGE_PGTO = AG.COD_AGENCIA
                                   AND CT.COD_BCO_PGTO = AG.COD_BANCO
INNER JOIN RHFP0350 REC ON CT.COD_CONTRATO = REC.COD_CONTRATO
INNER JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
INNER JOIN RHFP0310 A ON CT.COD_CONTRATO = A.COD_CONTRATO
                     AND A.DATA_FIM = '31/12/2999'
INNER JOIN V_EST_ORG_AVT B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
LEFT JOIN RHFP1006 VLR6 ON CT.COD_CONTRATO = VLR6.COD_CONTRATO
LEFT JOIN RHFP1003 EV6 ON VLR6.COD_MESTRE_EVENTO = EV6.COD_MESTRE_EVENTO
  LEFT JOIN RHFP1002 DEV ON EV6.COD_EVENTO = DEV.COD_EVENTO
WHERE CT.DATA_FIM IS NOT NULL
  AND EV6.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
  AND EV6.COD_EVENTO IN (17,19)
  --AND EV6.COD_EVENTO = :EVENTO
  AND VLR6.COD_VD = 1003
  --AND VLR6.VALOR_VD <> 0
  AND EV6.SITUACAO_PROCESSO = 'I'
  AND B.COD2 = :EMPRESA -- Filtro da empresa na consulta principal
  AND (:COD_CONTRATO = '0' OR
       CT.COD_CONTRATO IN
       (SELECT * FROM TABLE(SPLIT_CONTRACTS(:COD_CONTRATO))))
GROUP BY CT.COD_CONTRATO,
         PF.NOME_PESSOA,
         PF.CPF,
         B.EDICAO_ORG_2,
         B.NOME2,
         B.EDICAO_ORG,
         B.NOME_ORGANOGRAMA,
         CT.COD_BCO_PGTO,
         BC.DES_BANCO,
         CT.COD_AGE_PGTO,
         AG.DIGITO,
         AG.DES_AGENCIA,
         CT.NRO_CONTA_PGTO,
         EV6.COD_EVENTO,
         DEV.NOME_EVENTO,
         EV6.COD_MESTRE_EVENTO,
         EV6.SITUACAO_PROCESSO,
         REC.DATA_PAGAMENTO,
         EV6.DATA_REFERENCIA
