CREATE OR REPLACE VIEW V_DADOS_FILIAIS_AVT AS
SELECT B.EDICAO_NIVEL3 AS FILIAL,
       DECODE(D.COD_SEQ_JORNADA,
              1,
              'DOMINGO',
              2,
              'SEGUNDA',
              3,
              'TERÇA',
              4,
              'QUARTA',
              5,
              'QUINTA',
              6,
              'SEXTA',
              7,
              'SABADO') AS DIA,
       D.COD_SEQ_JORNADA,
       E.HORA_ENT,
       E.HORA_SAI,
       E.COD_SEQ_HORARIO,
       A.DATA_INICIO,
       A.DATA_FIM
  FROM RHAF1149 A, RHFP0401 B, RHAF1145 C, RHAF1120 D, RHAF1117 E
 WHERE A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
   AND A.COD_TURNO = C.COD_TURNO
   AND A.COD_TURNO = D.COD_TURNO
   AND E.COD_HORARIO = D.COD_HORARIO_1
   AND B.COD_ORGANOGRAMA_SUB = 8
   AND E.COD_SEQ_HORARIO = 1
   AND A.DATA_INICIO <= TRUNC(SYSDATE)
   AND A.DATA_FIM >= TRUNC(SYSDATE)
 ORDER BY B.EDICAO_NIVEL3, D.COD_SEQ_JORNADA

