CREATE OR REPLACE VIEW V_HORAS_EXTRAS_AVT AS
WITH HORAS_EXTRAS_CALCULADAS AS (
    SELECT A.COD_CONTRATO,
           C.NOME_PESSOA,
           A.DATA_OCORRENCIA AS DATA_REFERENCIA,
           A.NUM_HORAS,
           CASE
             WHEN A.NUM_HORAS > 8.9667 THEN A.NUM_HORAS - 8.9667
             ELSE 0
           END AS HORAS_EXTRAS
      FROM RHAF1123 A
      LEFT JOIN RHFP0300 B ON A.COD_CONTRATO = B.COD_CONTRATO
      LEFT JOIN PESSOA_FISICA C ON B.COD_FUNC = C.COD_PESSOA
     WHERE A.COD_OCORRENCIA = 2
)
SELECT COD_CONTRATO,
       'TOTAL' AS DES_PESSOA,
       DATA_REFERENCIA,
       TO_CHAR(SUM(HORAS_EXTRAS), 'FM00') || ':' ||
       TO_CHAR(MOD(SUM(HORAS_EXTRAS) * 60, 60), 'FM00') AS HORAS_EXTRAS
  FROM HORAS_EXTRAS_CALCULADAS
 GROUP BY COD_CONTRATO, DATA_REFERENCIA

