CREATE OR REPLACE VIEW V_SUPERIOR_IMEDIATO_AVT AS
WITH
CONTRATOS AS (
SELECT DISTINCT A.COD_CONTRATO,
                F.NOME_PESSOA AS DES_PESSOA,
                FS.CPF,
                D.COD_CLH AS COD_FUNCAO,
                E.NOME_CLH AS DES_FUNCAO,
                A.COD_ORGANOGRAMA,
                B.EDICAO_ORG AS COD_UNIDADE,
                B.NOME_ORGANOGRAMA_B AS DES_UNIDADE,
                B.COD_REDE,
                B.DES_REDE,
                B.COD_TIPO,
                B.DES_TIPO,
                B.COD_NIVEL_ORG AS COD_NIVEL,
                B.NOME_NIVEL_ORG AS DES_NIVEL
FROM RHFP0310 A
 LEFT JOIN V_EST_ORG_AVT B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
 LEFT JOIN RHFP0300 C ON A.COD_CONTRATO = C.COD_CONTRATO
 LEFT JOIN RHFP0340 D ON A.COD_CONTRATO = D.COD_CONTRATO
 LEFT JOIN RHFP0500 E ON D.COD_CLH = E.COD_CLH
 LEFT JOIN PESSOA F ON C.COD_FUNC = F.COD_PESSOA
 LEFT JOIN PESSOA_FISICA FS ON C.COD_FUNC = FS.COD_PESSOA
 WHERE SYSDATE BETWEEN A.DATA_INICIO AND A.DATA_FIM
   AND SYSDATE BETWEEN B.DATA_INICIO AND B.DATA_FIM
   AND SYSDATE BETWEEN D.DATA_INICIO AND D.DATA_FIM
   AND C.DATA_FIM IS NULL
   AND (E.NOME_CLH LIKE 'GERENTE%' OR E.NOME_CLH LIKE 'SUPERVISOR%' OR E.NOME_CLH LIKE 'DIRETOR%')
   AND B.COD2 = 8
 ORDER BY B.COD_TIPO, B.EDICAO_ORG, A.COD_CONTRATO

),

RESPONSAVEL AS (
SELECT COD_CONTRATO_RESP,
       CASE
           WHEN MAX(CASE WHEN DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN 1 ELSE 0 END) = 1 THEN
            'S'
           ELSE
            'N'
       END AS IND_RESP_UNI
FROM RHFP0397
GROUP BY COD_CONTRATO_RESP

),

AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_ORGANOGRAMA,
       ORG.COD_UNIDADE,
       AF.COD_CAUSA_AFAST AS COD_AFAST,
       AFN.NOME_CAUSA_AFAST AS DES_AFAST,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST,
       CASE
         WHEN CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < SYSDATE THEN
          'INATIVO'
         WHEN AF.COD_CAUSA_AFAST <> 0 AND AF.COD_CAUSA_AFAST <> 4 AND
              AF.COD_CAUSA_AFAST <> 21 AND AF.COD_CAUSA_AFAST <> 60 AND
              AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'AFASTADO'
         WHEN AF.COD_CAUSA_AFAST IN (21, 60) THEN
          'ATIVO, SEM RETORNO'
         WHEN AF.COD_CAUSA_AFAST = 7 THEN
          'EM FÉRIAS'
         WHEN AF.COD_CAUSA_AFAST IN (3, 6) THEN
          'AFASTADO TEMP'
         WHEN AF.COD_CAUSA_AFAST = 4 AND
              AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'PODERÁ RETORNAR'
         ELSE
          'EM ATIVIDADE'
       END AS DES_STATUS_AFAST,
       AF.DATA_INICIO AS DATA_INI_AFAST,
       AF.DATA_FIM AS DATA_FIM_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN,
       RHFP0100 AFN
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND AF.COD_CAUSA_AFAST = AFN.COD_CAUSA_AFAST(+)
   AND ((SYSDATE BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= SYSDATE AND CT.DATA_FIM IS NULL))
   AND SYSDATE BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND SYSDATE BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND SYSDATE BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   AND ORG.COD_EMP = 8

)



SELECT A."COD_CONTRATO",A."DES_PESSOA",A."CPF",A."COD_FUNCAO",A."DES_FUNCAO",A."COD_ORGANOGRAMA",A."COD_UNIDADE",A."DES_UNIDADE",A."COD_REDE",A."DES_REDE",A."COD_TIPO",A."DES_TIPO",A."COD_NIVEL",A."DES_NIVEL",
       B.IND_RESP_UNI,
       C.COD_AFAST,
       C.DES_AFAST,
       C.DATA_INI_AFAST,
       C.DATA_FIM_AFAST,
       C.STATUS_AFAST,
       C.DES_STATUS_AFAST
FROM CONTRATOS A
LEFT JOIN RESPONSAVEL B ON A.COD_CONTRATO = B.COD_CONTRATO_RESP
LEFT JOIN AFASTADOS C ON A.COD_CONTRATO = C.COD_CONTRATO
ORDER BY A.COD_TIPO, A.COD_UNIDADE



/*SELECT DISTINCT A.COD_CONTRATO,
                H.NOME_PESSOA AS DES_PESSOA,
                F.COD_CLH AS COD_FUNCAO,
                G.NOME_CLH AS DES_FUNCAO,
                A.COD_ORGANOGRAMA,
                B.EDICAO_ORG AS COD_UNIDADE,
                B.NOME_ORGANOGRAMA_B AS DES_UNIDADE,
                B.COD_REDE,
                B.DES_REDE,
                B.COD_TIPO,
                B.DES_TIPO,
                B.COD_NIVEL_ORG AS COD_NIVEL,
                B.NOME_NIVEL_ORG AS DES_NIVEL,

                COALESCE(
                  (SELECT CASE
                            WHEN MAX(CASE WHEN RESP.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN 1 ELSE 0 END) = 1 THEN 'S'
                            ELSE 'N'
                          END
                   FROM RHFP0397 RESP
                   WHERE RESP.COD_ORGANOGRAMA = A.COD_ORGANOGRAMA
                     AND RESP.COD_CONTRATO_RESP = A.COD_CONTRATO
                   GROUP BY RESP.COD_ORGANOGRAMA, RESP.COD_CONTRATO_RESP),
                  'N'
                ) AS IND_RESP_UNI
  FROM RHFP0310 A
  LEFT JOIN V_EST_ORG_AVT B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
  LEFT JOIN RHFP0400 B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
  LEFT JOIN RHFP0401 C ON B.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
  LEFT JOIN RHFP0402 D ON B.COD_CUSTO_CONTABIL = D.COD_CUSTO_CONTABIL
  LEFT JOIN RHFP0300 E ON A.COD_CONTRATO = E.COD_CONTRATO
  LEFT JOIN RHFP0340 F ON A.COD_CONTRATO = F.COD_CONTRATO
  LEFT JOIN RHFP0500 G ON F.COD_CLH = G.COD_CLH
  LEFT JOIN PESSOA H ON E.COD_FUNC = H.COD_PESSOA
  LEFT JOIN RHFP0397 RESP ON A.COD_ORGANOGRAMA = RESP.COD_ORGANOGRAMA
                         AND A.COD_CONTRATO = RESP.COD_CONTRATO_RESP
 WHERE SYSDATE BETWEEN A.DATA_INICIO AND A.DATA_FIM
   AND SYSDATE BETWEEN C.DATA_INICIO AND C.DATA_FIM
   AND SYSDATE BETWEEN F.DATA_INICIO AND F.DATA_FIM
   AND E.DATA_FIM IS NULL
   AND (G.NOME_CLH LIKE 'GERENTE%' OR G.NOME_CLH LIKE 'SUPERVISOR%' OR G.NOME_CLH LIKE 'DIRETOR%')
   AND C.COD_NIVEL2 = 8
\*   AND NOT EXISTS (SELECT 1
                     FROM RHFP0306 AF
                    WHERE AF.COD_CONTRATO = E.COD_CONTRATO
                      AND AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY'))*\
 ORDER BY \*CASE
            WHEN TIPO = 'LOJA' THEN 1
            WHEN TIPO = 'SETOR' THEN 2
            WHEN TIPO = 'DEPÓSITO' THEN 3
            ELSE 4
          END,*\
          B.COD_TIPO,
          B.EDICAO_ORG ASC*/



/*SELECT * FROM V_ORGANOGRAMA_CONTRATO_AVT
WHERE COD_CONTRATO = 389622


SELECT * FROM V_EST_ORG_AVT*/

