CREATE OR REPLACE VIEW V_UMENTOR_FILIAIS AS
SELECT ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.EDICAO_ORG, ORGANOGRAMA.NOME_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA_SUB
    FROM RHFP0400 ORGANOGRAMA
    INNER JOIN RHFP0401 ORGANOGRAMA_NIVEIS ON ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
    WHERE TRUNC(SYSDATE) BETWEEN ORGANOGRAMA_NIVEIS.DATA_INICIO AND ORGANOGRAMA_NIVEIS.DATA_FIM
      AND ORGANOGRAMA.COD_NIVEL_ORG = 1
    UNION
    SELECT ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.EDICAO_ORG, ORGANOGRAMA.NOME_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA_SUB
    FROM RHFP0400 ORGANOGRAMA
    INNER JOIN RHFP0401 ORGANOGRAMA_NIVEIS ON ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
    WHERE TRUNC(SYSDATE) BETWEEN ORGANOGRAMA_NIVEIS.DATA_INICIO AND ORGANOGRAMA_NIVEIS.DATA_FIM
      AND ORGANOGRAMA.COD_NIVEL_ORG = 2
    UNION
    SELECT ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.EDICAO_ORG, ORGANOGRAMA.NOME_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA_SUB
    FROM RHFP0400 ORGANOGRAMA
    INNER JOIN RHFP0401 ORGANOGRAMA_NIVEIS ON ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
    WHERE TRUNC(SYSDATE) BETWEEN ORGANOGRAMA_NIVEIS.DATA_INICIO AND ORGANOGRAMA_NIVEIS.DATA_FIM
      AND ORGANOGRAMA.COD_NIVEL_ORG = 3
    UNION
    SELECT ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.EDICAO_ORG, ORGANOGRAMA.NOME_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA_SUB
    FROM RHFP0400 ORGANOGRAMA
    INNER JOIN RHFP0401 ORGANOGRAMA_NIVEIS ON ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
    WHERE TRUNC(SYSDATE) BETWEEN ORGANOGRAMA_NIVEIS.DATA_INICIO AND ORGANOGRAMA_NIVEIS.DATA_FIM
      AND ORGANOGRAMA.COD_NIVEL_ORG = 4
    UNION
    SELECT ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.EDICAO_ORG, ORGANOGRAMA.NOME_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA_SUB
    FROM RHFP0400 ORGANOGRAMA
    INNER JOIN RHFP0401 ORGANOGRAMA_NIVEIS ON ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
    WHERE TRUNC(SYSDATE) BETWEEN ORGANOGRAMA_NIVEIS.DATA_INICIO AND ORGANOGRAMA_NIVEIS.DATA_FIM
      AND ORGANOGRAMA.COD_NIVEL_ORG = 5
    UNION
    SELECT ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.EDICAO_ORG, ORGANOGRAMA.NOME_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA_SUB
    FROM RHFP0400 ORGANOGRAMA
    INNER JOIN RHFP0401 ORGANOGRAMA_NIVEIS ON ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
    WHERE TRUNC(SYSDATE) BETWEEN ORGANOGRAMA_NIVEIS.DATA_INICIO AND ORGANOGRAMA_NIVEIS.DATA_FIM
      AND ORGANOGRAMA.COD_NIVEL_ORG = 6
    UNION
    SELECT ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.EDICAO_ORG, ORGANOGRAMA.NOME_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA_SUB
    FROM RHFP0400 ORGANOGRAMA
    INNER JOIN RHFP0401 ORGANOGRAMA_NIVEIS ON ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
    WHERE TRUNC(SYSDATE) BETWEEN ORGANOGRAMA_NIVEIS.DATA_INICIO AND ORGANOGRAMA_NIVEIS.DATA_FIM
      AND ORGANOGRAMA.COD_NIVEL_ORG = 7
    UNION
    SELECT ORGANOGRAMA.COD_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.EDICAO_ORG, ORGANOGRAMA.NOME_ORGANOGRAMA, ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA_SUB
    FROM RHFP0400 ORGANOGRAMA
    INNER JOIN RHFP0401 ORGANOGRAMA_NIVEIS ON ORGANOGRAMA_NIVEIS.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
    WHERE TRUNC(SYSDATE) BETWEEN ORGANOGRAMA_NIVEIS.DATA_INICIO AND ORGANOGRAMA_NIVEIS.DATA_FIM
      AND ORGANOGRAMA.COD_NIVEL_ORG = 8
    ORDER BY 1,2, 4

