CREATE OR REPLACE VIEW VH_AFAST_CONTRATO_AVT AS
SELECT CASE
         WHEN CT.DATA_FIM IS NULL THEN
          0
         ELSE
          1
       END AS STATUS,
       CASE
         WHEN CT.DATA_FIM IS NULL THEN
          'ATIVO'
         ELSE
          'INATIVO'
       END AS DES_STATUS,
       CT.COD_CONTRATO,
       PF.NOME_PESSOA AS DES_PESSOA,
       NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFAST,
       CASE
         WHEN AF.COD_CAUSA_AFAST <> 0 AND AF.COD_CAUSA_AFAST <> 4 AND
              AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'AFASTADO'
         WHEN AF.COD_CAUSA_AFAST = 7 THEN
          'EM F�RIAS'
         WHEN AF.COD_CAUSA_AFAST IN (3, 6) THEN
          'AFASTADO TEMP'
         WHEN AF.COD_CAUSA_AFAST = 4 AND
              AF.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'PODER� RETORNAR'
         ELSE
          NULL
       END AS DES_STATUS_AFAST,
       AF.COD_CAUSA_AFAST AS COD_AFAST,
       CAU.NOME_CAUSA_AFAST AS DES_AFAST,
       AF.DATA_INICIO AS DATA_INI_AFAST,
       AF.DATA_FIM AS DATA_FIM_AFAST,
       CASE
         WHEN AF.DATA_FIM <> TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          AF.DATA_FIM - AF.DATA_INICIO
         WHEN AF.DATA_FIM <> TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          AF.DATA_FIM - TRUNC(SYSDATE)
         ELSE
          0
       END AS QTD_DIAS_AFAST,
       CASE
         WHEN SYSDATE BETWEEN AF.DATA_INICIO AND AF.DATA_FIM THEN
          'S'
         ELSE
          'N'
       END AS EM_AFASTAMENTO

  FROM RHFP0306 AF, RHFP0300 CT, PESSOA_FISICA PF, RHFP0100 CAU, RHFP0310 ORG, RHFP0401 ORG1, RHFP0400 ORG2
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_FUNC = PF.COD_PESSOA(+)
   AND AF.COD_CAUSA_AFAST = CAU.COD_CAUSA_AFAST(+)
   AND AF.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND ORG.COD_ORGANOGRAMA = ORG1.COD_ORGANOGRAMA(+)
   AND ORG.COD_ORGANOGRAMA = ORG2.COD_ORGANOGRAMA(+)
--AND '31/05/2025' BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
--AND CT.COD_CONTRATO = 389622




/*SELECT CASE
         WHEN CT.DATA_FIM IS NULL THEN
          0
         ELSE
          1
       END AS STATUS,
       AFAST.COD_CONTRATO,
       PF.NOME_PESSOA AS DES_PESSOA,
       CT.DATA_INICIO AS DATA_ADMISSAO,
       CT.DATA_FIM AS DATA_DEMISSAO,
       AFAST.COD_CAUSA_AFAST AS COD_AFAST,
       CAU.NOME_CAUSA_AFAST AS DES_AFAST,
       MT.COD_TIPO_MOTIVO,
       MT2.NOME_TIPO_MOTIVO AS DES_TIPO_MOTIVO,
       MT.COD_MOTIVO,
       MT.NOME_MOTIVO AS DES_MOTIVO,
       AFAST.DATA_INICIO AS DATA_INI_AFAST,
       AFAST.DATA_FIM AS DATA_FIM_AFAST,
       CASE
         WHEN AFAST.DATA_FIM <> TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          AFAST.DATA_FIM - AFAST.DATA_INICIO
         ELSE
          9999
       END AS QTD_DIAS_AFAST,
       CASE
          WHEN AFAST.COD_CAUSA_AFAST IS NULL OR
               TRIM(TO_CHAR(AFAST.COD_CAUSA_AFAST)) IS NULL THEN
           0
          ELSE
           AFAST.COD_CAUSA_AFAST
        END AS COD_STATUS_AFAST,
       CASE
         WHEN CT.DATA_FIM IS NOT NULL AND CT.DATA_FIM < SYSDATE THEN
          'INATIVO'
         WHEN AFAST.COD_CAUSA_AFAST <> 0 AND AFAST.COD_CAUSA_AFAST <> 4 AND
              AFAST.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'AFASTADO'
         WHEN AFAST.COD_CAUSA_AFAST = 7 THEN
          'EM F�RIAS'
         WHEN AFAST.COD_CAUSA_AFAST IN (3, 6) THEN
          'AFASTADO TEMP'
         WHEN AFAST.COD_CAUSA_AFAST = 4 AND
              AFAST.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY') THEN
          'PODER� RETORNAR'
         ELSE
          'EM ATIVIDADE'
       END AS STATUS_AFAST
  FROM RHFP0300 CT
  LEFT JOIN RHFP0306 AFAST ON AFAST.COD_CONTRATO = CT.COD_CONTRATO
  LEFT JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
  LEFT JOIN RHFP0323 MT ON AFAST.COD_MOTIVO = MT.COD_MOTIVO
  LEFT JOIN RHFP0115 MT2 ON MT.COD_TIPO_MOTIVO = MT2.COD_TIPO_MOTIVO
  LEFT JOIN RHFP0100 CAU ON AFAST.COD_CAUSA_AFAST = CAU.COD_CAUSA_AFAST
  --WHERE CT.COD_CONTRATO = 389622
 ORDER BY AFAST.COD_CONTRATO, AFAST.DATA_INICIO*/

