CREATE OR REPLACE VIEW V_CUSTO_FOLHA_COLAB_AVT AS
WITH
  Base_V AS (
    SELECT
      A.COD_CONTRATO AS COD_CONTRATO_REP,
      A.COD_CONTRATO,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      TO_DATE(R.DATA_REFERENCIA, 'DD/MM/YYYY') AS DATA_REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER(PARTITION BY A.COD_CONTRATO ORDER BY A.COD_VD) AS RN
    FROM RHFP1006 A
    JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
    JOIN RHFP0310 D 
      ON A.COD_CONTRATO = D.COD_CONTRATO
      -- Filtro de data fica por conta da view externa
    JOIN RHFP1003 R 
      ON A.COD_MESTRE_EVENTO = R.COD_MESTRE_EVENTO
    LEFT JOIN RHFP0401 E 
      ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA 
         AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, DATE '2999-12-31')
    LEFT JOIN RHFP0400 F 
      ON F.COD_ORGANOGRAMA = COALESCE(E.COD_NIVEL5, E.COD_NIVEL4)
    WHERE
      E.EDICAO_NIVEL2 = '008'
      AND B.TIPO_VD = 'V'
      AND A.COD_VD NOT IN (292, 4033)
      AND A.VALOR_VD <> 0
    GROUP BY
      A.COD_CONTRATO, E.EDICAO_ORG, F.NOME_ORGANOGRAMA,
      R.DATA_REFERENCIA, A.COD_VD, B.NOME_VD
  ),
  Base_D AS (
    SELECT
      A.COD_CONTRATO AS COD_CONTRATO_REP,
      A.COD_CONTRATO,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      TO_DATE(R.DATA_REFERENCIA, 'DD/MM/YYYY') AS DATA_REFERENCIA,
      CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END AS COD_VD,
      CASE WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões' ELSE B.NOME_VD END AS NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER (
        PARTITION BY A.COD_CONTRATO 
        ORDER BY CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END
      ) AS RN
    FROM RHFP1006 A
    JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
    LEFT JOIN RHFP1003 EV ON A.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
    JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO
    JOIN RHFP1003 R ON A.COD_MESTRE_EVENTO = R.COD_MESTRE_EVENTO
    LEFT JOIN RHFP0401 E 
      ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA 
         AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, DATE '2999-12-31')
    LEFT JOIN RHFP0400 F 
      ON F.COD_ORGANOGRAMA = COALESCE(E.COD_NIVEL5, E.COD_NIVEL4)
    WHERE
      E.EDICAO_NIVEL2 = '008'
      AND (
        B.TIPO_VD = 'D'
        OR (A.COD_VD = 1003 AND EV.COD_EVENTO IN (17, 19))
      )
      AND A.VALOR_VD <> 0
    GROUP BY
      A.COD_CONTRATO, E.EDICAO_ORG, F.NOME_ORGANOGRAMA,
      R.DATA_REFERENCIA,
      CASE WHEN A.COD_VD = 1003 THEN 1004 ELSE A.COD_VD END,
      CASE WHEN A.COD_VD = 1003 THEN 'Líquido Pago nas Rescisões' ELSE B.NOME_VD END
  ),
  Base_O AS (
    SELECT
      A.COD_CONTRATO AS COD_CONTRATO_REP,
      A.COD_CONTRATO,
      E.EDICAO_ORG,
      CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMMERCE'
        ELSE F.NOME_ORGANOGRAMA
      END AS NOME_ORGANOGRAMA,
      TO_DATE(R.DATA_REFERENCIA, 'DD/MM/YYYY') AS DATA_REFERENCIA,
      A.COD_VD,
      B.NOME_VD,
      SUM(NVL(A.VALOR_VD, 0)) AS TOTAL_MES,
      ROW_NUMBER() OVER(PARTITION BY A.COD_CONTRATO ORDER BY A.COD_VD) AS RN
    FROM RHFP1006 A
    JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
    JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO
    JOIN RHFP1003 R ON A.COD_MESTRE_EVENTO = R.COD_MESTRE_EVENTO
    LEFT JOIN RHFP0401 E 
      ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA 
         AND SYSDATE BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, DATE '2999-12-31')
    LEFT JOIN RHFP0400 F 
      ON F.COD_ORGANOGRAMA = COALESCE(E.COD_NIVEL5, E.COD_NIVEL4)
    WHERE
      E.EDICAO_NIVEL2 = '008'
      AND A.COD_VD IN (
        12, 885, 908, 910, 912, 914, 915, 916, 924, 925, 926, 927, 1004, 1063, 1064, 
        1067, 1068, 1231, 1232, 1233, 1234, 1456, 1457, 1458, 1459, 1461, 1462, 1463, 
        1464, 1910, 1924, 1934, 1935, 1941, 2222, 2232, 2601, 2602, 2605, 2611, 2612, 
        2615, 2616, 2617, 2701, 2705, 2706, 2711, 2712, 2713, 2714, 2715, 2716, 2717
      )
      AND A.VALOR_VD <> 0
    GROUP BY
      A.COD_CONTRATO, E.EDICAO_ORG, F.NOME_ORGANOGRAMA,
      R.DATA_REFERENCIA, A.COD_VD, B.NOME_VD
  ),
  Combined_Base AS (
    SELECT DISTINCT
      COALESCE(V.COD_CONTRATO_REP, D.COD_CONTRATO_REP, O.COD_CONTRATO_REP) AS COD_CONTRATO_REP,
      COALESCE(V.COD_CONTRATO, D.COD_CONTRATO, O.COD_CONTRATO) AS COD_CONTRATO,
      COALESCE(V.EDICAO_ORG, D.EDICAO_ORG, O.EDICAO_ORG) AS EDICAO_ORG,
      COALESCE(V.NOME_ORGANOGRAMA, D.NOME_ORGANOGRAMA, O.NOME_ORGANOGRAMA) AS NOME_ORGANOGRAMA,
      COALESCE(V.DATA_REFERENCIA, D.DATA_REFERENCIA, O.DATA_REFERENCIA) AS DATA_REFERENCIA,
      CASE WHEN V.COD_VD <> 0 THEN V.COD_VD END AS COD_VD_V,
      V.NOME_VD         AS NOME_VD_V,
      TO_CHAR(V.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_V,
      CASE WHEN D.COD_VD <> 0 THEN D.COD_VD END AS COD_VD_D,
      D.NOME_VD         AS NOME_VD_D,
      TO_CHAR(D.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_D,
      CASE WHEN O.COD_VD <> 0 THEN O.COD_VD END AS COD_VD_O,
      O.NOME_VD         AS NOME_VD_O,
      TO_CHAR(O.TOTAL_MES, 'FM999G999G990D00') AS TOTAL_MES_O,
      COALESCE(V.RN, D.RN, O.RN) AS RN,
      DENSE_RANK() OVER(
        PARTITION BY COALESCE(V.EDICAO_ORG, D.EDICAO_ORG, O.EDICAO_ORG)
        ORDER BY COALESCE(
          CASE WHEN V.COD_VD = 1003 THEN 1004 ELSE V.COD_VD END,
          CASE WHEN D.COD_VD = 1003 THEN 1004 ELSE D.COD_VD END,
          O.COD_VD
        )
      ) AS DR
    FROM Base_V V
    FULL OUTER JOIN Base_D D ON V.COD_CONTRATO = D.COD_CONTRATO AND V.RN = D.RN
    FULL OUTER JOIN Base_O O ON COALESCE(V.COD_CONTRATO, D.COD_CONTRATO) = O.COD_CONTRATO
       AND COALESCE(V.RN, D.RN) = O.RN
    WHERE
      NVL(V.TOTAL_MES, 0) + NVL(D.TOTAL_MES, 0) + NVL(O.TOTAL_MES, 0) <> 0
  )
SELECT *
FROM Combined_Base;
