CREATE OR REPLACE VIEW V_DADOS_PESSOA AS
SELECT FP03.COD_CONTRATO COD_CONTRATO,
       INITCAP(P.COD_PESSOA) COD_PESSOA,
       INITCAP(P.NOME_PESSOA) DES_PESSOA,
       INITCAP(SUBSTR(P.NOME_PESSOA, 1, INSTR(P.NOME_PESSOA, ' ') - 1)) DES_NOME,
       INITCAP(SUBSTR(P.NOME_PESSOA, INSTR(P.NOME_PESSOA, ' ') + 1, 50)) DES_SOBRENOME,
       FP03.DATA_INICIO DTA_ADMISSAO,
       FP03.DATA_FIM DTA_DEMISSAO,
       FUNCOES.COD_CLH COD_FUNCAO,
       FUNCOES.NOME_CLH DES_FUNCAO,
       CONTRFUNC.DATA_INICIO DTA_INI_FUNCAO,
       CONTRFUNC.DATA_FIM DTA_FIM_FUNCAO,
       ORG_CUSTO_CTB.CUSTO_CONTABIL COD_UNIDADE,
       ORGANOGRAMA.NOME_ORGANOGRAMA,
       CASE
           WHEN ORG_CUSTO_CTB.EDICAO_NIVEL3 = '1' THEN
            'GRZ'
           WHEN ORG_CUSTO_CTB.EDICAO_NIVEL3 = '3' THEN
            'PRM'
           WHEN ORG_CUSTO_CTB.EDICAO_NIVEL3 = '4' THEN
            'FRG'
           WHEN ORG_CUSTO_CTB.EDICAO_NIVEL3 = '2' THEN
            'TOT'
           WHEN ORG_CUSTO_CTB.EDICAO_NIVEL3 = '7' THEN
            'GZT'
           WHEN ORG_EMP.COD_NIVEL3 = 9 THEN
            'ADM'
           WHEN ORG_EMP.COD_NIVEL3 = 21 THEN
            'CD'
           ELSE
            NULL
       END AS SIGLA_REDE,
       INITCAP(ORG_CUSTO_CTB.NOME_CUSTO_CONTABIL) NOME_CUSTO_CONTABIL,
       CONTR_ORGANOGRAMA.DATA_INICIO DTA_INI_ORG,
       CONTR_ORGANOGRAMA.DATA_FIM DTA_FIM_ORG,
       ORG_EMP.COD_NIVEL3,
       CASE
           WHEN ORG_EMP.COD_NIVEL2 = 8 AND ORG_EMP.COD_NIVEL3 = 9 THEN
            2
           WHEN ORG_EMP.COD_NIVEL2 = 8 AND ORG_EMP.COD_NIVEL3 = 21 THEN
            3
           WHEN ORG_EMP.COD_NIVEL2 <> 8 THEN
            4
           ELSE
            1
       END AS COD_TIPO,
       CASE
           WHEN ORG_EMP.COD_NIVEL2 = 8 AND ORG_EMP.COD_NIVEL3 = 9 THEN
            'SETOR'
           WHEN ORG_EMP.COD_NIVEL2 = 8 AND ORG_EMP.COD_NIVEL3 = 21 THEN
            'DEPÓSITO'
           WHEN ORG_EMP.COD_NIVEL2 <> 8 THEN
            'COLIGADA'
           ELSE
            'LOJA'
       END AS DES_TIPO,
       NVL(ORG_CUSTO_CTB.EDICAO_NIVEL3, 0) COD_GRUPO,
       DECODE(ORG_CUSTO_CTB.EDICAO_NIVEL3,
              '1',
              'GRAZZIOTIN',
              '2',
              'TOTTAL',
              '3',
              'PORMENOS',
              '4',
              'FRANCO GIORGI',
              '7',
              'GZT STORE') DES_GRUPO,
       ORG_EMP.COD_NIVEL2 COD_EMP,
       SENHA.COD_GRUPO COD_GRUPO_UNIDADE,
       TO_CHAR(FP02.DATA_NASCIMENTO, 'ddmmyyyy') DATA_NASCIMENTO_OLD,
       SENHA.DES_SENHA DATA_NASCIMENTO,
       INITCAP(MUN.NOME_MUNIC) DES_MUNIC,
       DECODE(FIS.COD_UF, 'RS', 'BR', 'SC', 'BR', 'PR', 'BR') DES_PAIS,
       CASE
          WHEN FUNCOES.COD_CLH = 325 THEN
            FP03.COD_CONTRATO || '@grupograzziotin.com.br'
          WHEN FUNCOES.COD_CLH <> 325 THEN
            FP03.COD_CONTRATO || '@grazziotin.com.br'
          ELSE
           NULL
       END DES_EMAIL,
       FIS.CPF,
       FP02.NRO_PIS_PASEP
  FROM RHFP0200 FP02
 INNER JOIN RHFP0300 FP03 ON FP03.COD_FUNC = FP02.COD_FUNC
 INNER JOIN PESSOA P ON P.COD_PESSOA = FP02.COD_FUNC
 INNER JOIN FISICA FIS ON FIS.COD_PESSOA = FP02.COD_FUNC
 INNER JOIN MUNICI MUN ON MUN.COD_MUNIC = FIS.COD_MUNIC
 INNER JOIN RHFP0310 CONTR_ORGANOGRAMA ON CONTR_ORGANOGRAMA.COD_CONTRATO =
                                          FP03.COD_CONTRATO
 INNER JOIN RHFP0400 ORGANOGRAMA ON ORGANOGRAMA.COD_ORGANOGRAMA =
                                    CONTR_ORGANOGRAMA.COD_ORGANOGRAMA
 INNER JOIN RHFP0401 ORG_EMP ON ORG_EMP.COD_ORGANOGRAMA =
                                ORGANOGRAMA.COD_ORGANOGRAMA
  LEFT JOIN RHFP0402 ORG_CUSTO_CTB ON ORG_CUSTO_CTB.COD_CUSTO_CONTABIL =
                                      ORGANOGRAMA.COD_CUSTO_CONTABIL
 INNER JOIN RHFP0340 CONTRFUNC ON CONTRFUNC.COD_CONTRATO =
                                  FP03.COD_CONTRATO
 INNER JOIN RHFP0500 FUNCOES ON FUNCOES.COD_CLH = CONTRFUNC.COD_CLH
  LEFT JOIN MDL_USUARIO SENHA ON SENHA.COD_CONTRATO = FP03.COD_CONTRATO
 WHERE ORG_EMP.COD_NIVEL2 IN (4, 8, 282, 276, 006, 1629)
   AND ORG_EMP.DATA_INICIO <= TRUNC(SYSDATE)
      --AND CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
      --AND CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
   AND (CONTR_ORGANOGRAMA.DATA_INICIO <= TRUNC(SYSDATE) AND
       (CONTR_ORGANOGRAMA.DATA_FIM IS NULL OR
       CONTR_ORGANOGRAMA.DATA_FIM >= TRUNC(SYSDATE)))
   AND (FP03.DATA_FIM IS NULL OR TRUNC(FP03.DATA_FIM) >= TRUNC(SYSDATE))
   AND (CONTRFUNC.DATA_INICIO <= TRUNC(SYSDATE) AND
       (CONTRFUNC.DATA_FIM IS NULL OR CONTRFUNC.DATA_FIM >= TRUNC(SYSDATE)))
   AND SYSDATE BETWEEN CONTRFUNC.DATA_INICIO AND
       nvl(CONTRFUNC.DATA_FIM, SYSDATE)
   AND SYSDATE BETWEEN ORG_EMP.DATA_INICIO AND
       nvl(ORG_EMP.DATA_FIM, SYSDATE)

