CREATE OR REPLACE VIEW V_HORARIOS_LOJAS_AVT AS
SELECT UNI.COD_UNIDADE,
       UNI.DES_UNIDADE,
       TU.COD_TURNO,
       HOR.COD_SEQ_JORNADA,
       HOR.DIA_ESOCIAL,
       CASE
         WHEN HOR.COD_SEQ_JORNADA = 1 THEN
          'DOMINGO'
         WHEN HOR.COD_SEQ_JORNADA = 2 THEN
          'SEGUNDA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 3 THEN
          'TERÇA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 4 THEN
          'QUARTA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 5 THEN
          'QUINTA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 6 THEN
          'SEXTA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 7 THEN
          'SÁBADO'
       END AS DIA_SEMANA,
       CASE
         WHEN HOR.COD_SEQ_JORNADA = 1 AND
              (HOR.HORENT_ESOCIAL IS NULL OR HOR.HORENT_ESOCIAL = '') THEN
          'DSR'
         ELSE
          HOR.HORENT_ESOCIAL
       END HORA_ENTRADA,
       CASE
         WHEN HOR.COD_SEQ_JORNADA = 1 AND
              (HOR.HORSAI_ESOCIAL IS NULL OR HOR.HORSAI_ESOCIAL = '') THEN
          'DSR'
         ELSE
          HOR.HORSAI_ESOCIAL
       END HORA_SAIDA
  FROM V_DADOS_LOJAS_AVT UNI
  LEFT JOIN (
        SELECT A.COD_ORGANOGRAMA AS ORG,
               C.EDICAO_NIVEL3 AS EDICAO_ORG,
               C.EDICAO_ORG AS UNIDADE,
               B.NOME_ORGANOGRAMA,
               A.COD_TURNO,
               A.DATA_INICIO,
               A.DATA_FIM
        FROM RHAF1149 A
        INNER JOIN RHFP0400 B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
        INNER JOIN RHFP0401 C ON B.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
        WHERE A.DATA_FIM = TO_DATE('31/12/2999', 'DD/MM/YYYY')
          AND C.DATA_FIM = '31/12/2999'
    ) TU ON UNI.COD_UNIDADE = TU.UNIDADE
 INNER JOIN RHAF1120 HOR ON TU.COD_TURNO = HOR.COD_TURNO
 ORDER BY UNI.COD_UNIDADE ASC, HOR.COD_SEQ_JORNADA ASC

