/* ===============================================
   == CRIANDO RELATÓRIO DADOS CONTRATOS ALUGUÉS ==
   =============================================== */


WITH BASE_CONTRATOS AS (
/*MAPEAMENTO BASE DOS DADOS*/
SELECT A.COD_UNIDADE,
       V.DES_FANTASIA AS DES_UNIDADE,
       A.COD_CONTRATO,
       A.IND_INATIVO,
       A.DTA_INICIO,
       A.DTA_TERMINO,       
       B.VAL_FIXO,
       B.VAL_ANTIGO_ALUGUEL,
       
       B.VAL_NOVO_ALUGUEL,
       B.DTA_ALTERACAO,
       
       B.VAL_DIFERENCA,
       B.DTA_VALIDADE_DIF,
       
       B.VAL_DESCTO,
       B.DTA_DESCTO_INI,
       B.DTA_DESCTO_FIM       
  FROM GRAZZ.GRZ_LOC_CONTRATOS A
  JOIN GRAZZ.GRZ_LOC_CONTR_VALORES B ON B.COD_CONTRATO = A.COD_CONTRATO
  JOIN SISLOGWEB.V_UNIDADES_ATIVAS V ON V.COD_UNIDADE = A.COD_UNIDADE
 WHERE A.COD_EMPRESA = 1
   AND A.IND_INATIVO = 0
   AND B.IND_INATIVO = 0
   AND B.COD_VALOR = 1
   --AND A.COD_UNIDADE = 34
),


/*APENAS VERIFICA A DATA DE REAJUSTE*/
REAJUSTE AS (
SELECT COD_UNIDADE,
       LAST_DAY(ADD_MONTHS(DTA_ALTERACAO, -1)) AS DTA_ALTERACAO
FROM BASE_CONTRATOS
WHERE DTA_ALTERACAO >= TRUNC(SYSDATE)
         
),

--SELECT * FROM REAJUSTE


/*LOJAS QUE POSSUEM DESCONTOS*/
DESCONTOS AS (
SELECT COD_UNIDADE,
       VAL_DESCTO,
       DTA_DESCTO_INI,
       DTA_DESCTO_FIM,
       LAST_DAY(ADD_MONTHS(DTA_DESCTO_FIM, -1)) AS DESCONTO_ATE
FROM BASE_CONTRATOS
WHERE DTA_DESCTO_FIM >= TRUNC(SYSDATE)
         
),

--SELECT * FROM DESCONTOS

/*LOJAS QUE POSSUEM DIFERENÇAS*/
DIFERENCAS AS (
SELECT COD_UNIDADE,
       VAL_DIFERENCA,
       DTA_VALIDADE_DIF,
       LAST_DAY(ADD_MONTHS(DTA_VALIDADE_DIF, -1)) AS VALIDADE_DIF
FROM BASE_CONTRATOS
WHERE DTA_VALIDADE_DIF >= TRUNC(SYSDATE)
         
),

--SELECT * FROM DIFERENCAS

/*LOJAS QUE POSSUEM EMPRÉSTIMOS*/
LOJAS_EMPRESTIMOS AS ( 
SELECT A.COD_UNIDADE,
       SUM(NVL(A.VLR_ADIANTAMENTO, 0)) AS VLR_EMPRESTIMO,
       NULL AS EMPRESTIMO_ATE
  FROM GRAZZ.GRZ_LOC_MVTO A
  JOIN GRAZZ.GRZ_LOC_ADIANTAMENTOS B ON B.COD_PESSOA = A.COD_PESSOA
                                    AND B.COD_CONTRATO = A.COD_CONTRATO
 WHERE A.ANO_REFERENCIA = 2025
   AND A.MES_REFERENCIA = 10
   AND A.VLR_ADIANTAMENTO <> 0
 GROUP BY A.COD_UNIDADE
 
),

CONTRATOS AS (
SELECT B.COD_UNIDADE AS UNIDADE,
       MAX(B.DES_UNIDADE) AS DES_UNIDADE,
       CASE
         WHEN MIN(B.IND_INATIVO) = 0 THEN
          'ATIVO'
         WHEN MAX(B.IND_INATIVO) = 1 THEN
          'INATIVO'
         ELSE
          TO_CHAR(MAX(B.IND_INATIVO))
       END AS DES_SITUACAO,
       
       MIN(B.DTA_INICIO) AS DTA_INICIO,
       MAX(B.DTA_TERMINO) AS DTA_TERMINO,
       MAX(R.DTA_ALTERACAO) AS DTA_ALTERACAO,
       
       SUM(NVL(B.VAL_FIXO, 0)) AS VLR_ALUGUEL_FIXO,
       SUM(NVL(B.VAL_NOVO_ALUGUEL, 0))     AS VLR_NOVO_ALUGUEL, 
       SUM(NVL(B.VAL_ANTIGO_ALUGUEL, 0)) AS VLR_ANTIGO_ALUGUEL,
       
       SUM(NVL(F.VAL_DIFERENCA, 0)) AS VLR_DIFERENCA,
       MAX(F.VALIDADE_DIF) AS DTA_DIFERENCA,
       
       SUM(NVL(D.VAL_DESCTO, 0)) AS VLR_DESCONTO,
       MAX(D.DESCONTO_ATE) AS DESCONTO_ATE,
       
       SUM(NVL(E.VLR_EMPRESTIMO, 0)) AS VLR_EMPRESTIMO,
       MAX(E.EMPRESTIMO_ATE) AS EMPRESTIMO_ATE,
       
       /* LISTA DE CONTRATOS SEM DISTINCT NO LISTAGG */
       (SELECT LISTAGG(X.COD_CONTRATO, ',') WITHIN
         GROUP(
         ORDER BY X.COD_CONTRATO)
          FROM (SELECT DISTINCT COD_CONTRATO
                  FROM BASE_CONTRATOS
                 WHERE COD_UNIDADE = B.COD_UNIDADE) X) AS CONTRATOS
  FROM BASE_CONTRATOS B
  LEFT JOIN DESCONTOS D ON D.COD_UNIDADE = B.COD_UNIDADE
  LEFT JOIN DIFERENCAS F ON F.COD_UNIDADE = B.COD_UNIDADE
  LEFT JOIN LOJAS_EMPRESTIMOS E ON E.COD_UNIDADE = B.COD_UNIDADE
  LEFT JOIN REAJUSTE R ON R.COD_UNIDADE = B.COD_UNIDADE
 GROUP BY B.COD_UNIDADE
 ORDER BY B.COD_UNIDADE

)



/*SELEÇÃO FINAL PRINCIPAL*/
SELECT CT.UNIDADE,
       CT.DES_UNIDADE,
       CT.DTA_INICIO,
       CT.DTA_TERMINO,
       
       TO_CHAR(SUM(CASE
                     WHEN CT.DTA_ALTERACAO IS NOT NULL THEN
                      NVL(CT.VLR_ANTIGO_ALUGUEL, 0)
                     ELSE
                      NVL(NULLIF(CT.VLR_ALUGUEL_FIXO, 0), CT.VLR_NOVO_ALUGUEL)
                   END),
               'FM999G999G990D00') AS VLR_ALUGUEL,
       
       TO_CHAR(SUM(CT.VLR_DIFERENCA), 'FM999G999G990D00') AS DIFERENCA,
       TO_CHAR(CT.DTA_DIFERENCA,
               'fmMonth/yyyy',
               'NLS_DATE_LANGUAGE=Portuguese') AS DTA_DIFERENCA,
       
       TO_CHAR(SUM(CT.VLR_DESCONTO), 'FM999G999G990D00') AS DESCONTO,
       TO_CHAR(CT.DESCONTO_ATE,
               'fmMonth/yyyy',
               'NLS_DATE_LANGUAGE=Portuguese') AS DESCONTO_ATE,
       
       TO_CHAR(SUM(CT.VLR_EMPRESTIMO), 'FM999G999G990D00') AS EMPRESTIMO,
       TO_CHAR(CT.EMPRESTIMO_ATE,
               'fmMonth/yyyy',
               'NLS_DATE_LANGUAGE=Portuguese') AS EMPRESTIMO_ATE,
       
       /*SALDO - SOMA A DIFERENÇA OU SUBTRAI O DESCONTO E/OU EMPRÉSTIMO*/
       TO_CHAR(SUM(CASE
                     WHEN CT.DTA_ALTERACAO IS NOT NULL THEN
                      NVL(CT.VLR_ANTIGO_ALUGUEL, 0)
                     ELSE
                      NVL(NULLIF(CT.VLR_ALUGUEL_FIXO, 0), CT.VLR_NOVO_ALUGUEL)
                   END + NVL(CT.VLR_DIFERENCA, 0) - NVL(CT.VLR_DESCONTO, 0) -
                   NVL(CT.VLR_EMPRESTIMO, 0)),
               'FM999G999G990D00') AS SALDO

  FROM CONTRATOS CT
 GROUP BY CT.UNIDADE,
          CT.DES_UNIDADE,
          CT.DTA_INICIO,
          CT.DTA_TERMINO,
          CT.DTA_ALTERACAO,
          CT.DTA_DIFERENCA,
          CT.DESCONTO_ATE,
          CT.EMPRESTIMO_ATE
 ORDER BY UNIDADE