WITH
PARAMS AS (
SELECT '01/01/2025' AS DTA_INICIO,
       '31/12/2025' AS DTA_FIM
FROM DUAL

),

/*DATA_REFERENCIA AS (
SELECT A.COD_UNIDADE,
       A.DTA_REF_FINAL,
       A.VLR_BRUTO_NOTA,
       A.VLR_IRRF,
       A.NUM_CPF
FROM NL.LF_REL_REINF A
CROSS JOIN PARAMS P
WHERE A.COD_SERIE = 'ALG'
AND A.DTA_REF_FINAL >= P.DTA_INICIO
AND A.DTA_REF_FINAL <= P.DTA_FIM


),*/


DADOS_IRRF AS (
SELECT A.COD_UNIDADE,
       B.NUM_CPF_CNPJ AS NUM_CPF,
       B.DES_PESSOA,
       A.DTA_VCTO,
       --NVL(DF.DTA_REF_FINAL, LAST_DAY(A.DTA_VCTO)) AS DTA_REF_FINAL,
       SUM(NVL(A.VAL_TOTAL, 0)) AS VAL_TOTAL,
       --SUM(NVL(A.VAL_TOTAL,0)) AS VAL_TOTAL2,
       SUM(NVL(A.VAL_IRRF, 0)) AS VAL_IRRF,
       SUM(NVL(A.VAL_LIQUIDO, 0)) AS VAL_LIQUIDO,
       --SUM(NVL(VAL_DED_BC_IRRF, 0)) AS VAL_DED_BC_IRRF,
       --SUM(NVL(VAL_BC_IRRF, 0)) AS VAL_BC_IRRF
       P.DTA_INICIO,
       P.DTA_FIM,
       1 AS ORDEM
  FROM GRAZZ.GRZ_LOC_MVTO A
  LEFT JOIN GRAZZ.GRZ_PESSOAS B ON A.COD_PESSOA = B.COD_PESSOA
/*  LEFT JOIN DATA_REFERENCIA DF ON DF.COD_UNIDADE = A.COD_UNIDADE
                              AND DF.NUM_CPF = B.NUM_CPF_CNPJ
                              AND TRUNC(DF.DTA_REF_FINAL, 'MM') = TRUNC(A.DTA_VCTO, 'MM')*/
  CROSS JOIN PARAMS P 
 WHERE A.COD_EMPRESA = 1
   AND COD_VALOR = 1
   --AND A.COD_UNIDADE = 219
   AND A.DTA_VCTO >= P.DTA_INICIO
   AND A.DTA_VCTO <= P.DTA_FIM
 GROUP BY A.COD_UNIDADE, 
          B.NUM_CPF_CNPJ, 
          B.DES_PESSOA, 
          A.DTA_VCTO,
          --NVL(DF.DTA_REF_FINAL, LAST_DAY(A.DTA_VCTO)),
          P.DTA_INICIO, 
          P.DTA_FIM

),

TOTAIS_CPF AS (
SELECT 2 AS ORDEM,
       A.COD_UNIDADE,
       B.NUM_CPF_CNPJ AS NUM_CPF,
       SUM(NVL(A.VAL_TOTAL, 0)) AS TOT_VAL_TOTAL,
       SUM(NVL(A.VAL_IRRF, 0)) AS TOT_VAL_IRRF,
       SUM(NVL(A.VAL_LIQUIDO, 0)) AS TOT_VAL_LIQUIDO
  FROM GRAZZ.GRZ_LOC_MVTO A
  LEFT JOIN GRAZZ.GRZ_PESSOAS B ON A.COD_PESSOA = B.COD_PESSOA
  CROSS JOIN PARAMS P
 WHERE A.COD_EMPRESA = 1
   AND COD_VALOR = 1
   AND A.DTA_VCTO >= P.DTA_INICIO
   AND A.DTA_VCTO <= P.DTA_FIM
 GROUP BY A.COD_UNIDADE, B.NUM_CPF_CNPJ
),

TOTAIS_UNIDADE AS (
SELECT 3 AS ORDEM,
       A.COD_UNIDADE,
       SUM(NVL(A.VAL_TOTAL, 0)) AS TOT_VAL_TOTAL,
       SUM(NVL(A.VAL_IRRF, 0)) AS TOT_VAL_IRRF,
       SUM(NVL(A.VAL_LIQUIDO, 0)) AS TOT_VAL_LIQUIDO
  FROM GRAZZ.GRZ_LOC_MVTO A
  LEFT JOIN GRAZZ.GRZ_PESSOAS B ON A.COD_PESSOA = B.COD_PESSOA
  CROSS JOIN PARAMS P
 WHERE A.COD_EMPRESA = 1
   AND COD_VALOR = 1
   AND A.DTA_VCTO >= P.DTA_INICIO
   AND A.DTA_VCTO <= P.DTA_FIM
 GROUP BY A.COD_UNIDADE

)



SELECT ORDEM,
       DTA_REFERENCIA,
       NUM_CPF_SHOW AS NUM_CPF,
       DES_PESSOA,
       COD_UNIDADE_SHOW AS COD_UNIDADE,
       VAL_TOTAL,
       VAL_IRRF,
       VAL_LIQUIDO
FROM (
    SELECT ORDEM, 
           DTA_VCTO AS DTA_REFERENCIA,
           NUM_CPF AS NUM_CPF_ORDEM,
           NUM_CPF AS NUM_CPF_SHOW,
           DES_PESSOA,
           COD_UNIDADE AS COD_UNIDADE_ORDEM,
           COD_UNIDADE AS COD_UNIDADE_SHOW,
           TO_CHAR(NVL(VAL_TOTAL, 0), 'FM999G999G990D00') AS VAL_TOTAL,
           TO_CHAR(NVL(VAL_IRRF, 0), 'FM999G999G990D00') AS VAL_IRRF,
           TO_CHAR(NVL(VAL_LIQUIDO, 0), 'FM999G999G990D00') AS VAL_LIQUIDO        
    FROM DADOS_IRRF

    UNION ALL

    SELECT ORDEM,
           NULL AS DTA_REFERENCIA,
           NUM_CPF AS NUM_CPF_ORDEM,
           NULL AS NUM_CPF_SHOW,
           NULL AS DES_PESSOA,
           COD_UNIDADE AS COD_UNIDADE_ORDEM,
           NULL AS COD_UNIDADE_SHOW,
           TO_CHAR(NVL(TOT_VAL_TOTAL, 0), 'FM999G999G990D00') AS TOT_VAL_TOTAL,
           TO_CHAR(NVL(TOT_VAL_IRRF, 0), 'FM999G999G990D00') AS TOT_VAL_IRRF,
           TO_CHAR(NVL(TOT_VAL_LIQUIDO, 0), 'FM999G999G990D00') AS TOT_VAL_LIQUIDO
    FROM TOTAIS_CPF

    UNION ALL

    SELECT ORDEM,
           NULL AS DTA_REFERENCIA,
           '99999999999999' AS NUM_CPF_ORDEM,
           NULL AS NUM_CPF_SHOW,
           NULL AS DES_PESSOA,
           COD_UNIDADE AS COD_UNIDADE_ORDEM,
           NULL AS COD_UNIDADE_SHOW,
           TO_CHAR(NVL(TOT_VAL_TOTAL, 0), 'FM999G999G990D00') AS TOT_VAL_TOTAL,
           TO_CHAR(NVL(TOT_VAL_IRRF, 0), 'FM999G999G990D00') AS TOT_VAL_IRRF,
           TO_CHAR(NVL(TOT_VAL_LIQUIDO, 0), 'FM999G999G990D00') AS TOT_VAL_LIQUIDO
    FROM TOTAIS_UNIDADE
)
ORDER BY COD_UNIDADE_ORDEM, NUM_CPF_ORDEM, ORDEM, DTA_REFERENCIA









