--TENTANDO AJUSTAR A VIEW V_DADOS_FILIAIS PARA CONTER O CÓDIGO E NOME DA REDE


-- SELECT * FROM V_DADOS_FILIAIS
-- SELECT * FROM V_DADOS_PESSOA

-- SELECT * FROM RHFP0400
-- SELECT * FROM RHFP0131

-- SELECT DISTINCT G.COD_CUSTO_CONTABIL
-- FROM RHFP0402 G;

-- SELECT DISTINCT COD_CUSTO_CONTABIL
-- FROM RHFP0400
-- ORDER BY 1


SELECT B.EDICAO_NIVEL3 AS FILIAL,
       F.NOME_ORGANOGRAMA,
       NVL(G.EDICAO_NIVEL3, 0) COD_GRUPO,
       NVL(DECODE(G.EDICAO_NIVEL3,1,'GRAZZIOTIN',2,'TOTTAL',3,'PORMENOS',4,'FRANCO GIORGI',7,'GZT STORE'), 'N/A') DES_GRUPO,
       DECODE(D.COD_SEQ_JORNADA,
              1,'DOMINGO',
              2,'SEGUNDA',
              3,'TERÇA',
              4,'QUARTA',
              5,'QUINTA',
              6,'SEXTA',
              7,'SABADO') AS DIA,
       D.COD_SEQ_JORNADA,
       E.HORA_ENT,
       E.HORA_SAI,
       E.COD_SEQ_HORARIO,
       A.DATA_INICIO,
       A.DATA_FIM
FROM RHAF1149 A
JOIN RHFP0401 B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
JOIN RHAF1145 C ON A.COD_TURNO = C.COD_TURNO
JOIN RHAF1120 D ON A.COD_TURNO = D.COD_TURNO
JOIN RHAF1117 E ON E.COD_HORARIO = D.COD_HORARIO_1
JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
LEFT JOIN RHFP0402 G ON G.COD_CUSTO_CONTABIL = F.COD_CUSTO_CONTABIL
WHERE B.COD_ORGANOGRAMA_SUB = 8
AND E.COD_SEQ_HORARIO = 1
AND A.DATA_INICIO <= TRUNC(SYSDATE)
AND A.DATA_FIM >= TRUNC(SYSDATE)
ORDER BY B.EDICAO_NIVEL3, D.COD_SEQ_JORNADA