
SELECT * FROM all_tab_columns  WHERE UPPER (table_name)  LIKE '%RHCS%'
AND COLUMN_NAME LIKE '%PESQUISA%'


---tabelas referente as pesquisas no módulo cargos e salários

SELECT * FROM RHCS0870; -- OITAVA A DELETAR 

SELECT * FROM RHCS0880; -- SÉTIMA A DELETAR

SELECT * FROM RHCS0900; --SEXTA A DELETAR

SELECT * FROM RHCS0910; -- QUINTA A DELETAR

SELECT * FROM RHCS0920; -- QUARTA A DELETAR

SELECT * FROM RHCS0930; --TERCEIRA A DELETAR

SELECT * FROM RHCS0915; --SEGUNDA A DELETAR

SELECT * FROM RHCS0890; -- PRIMEIRA A DELETAR 

DELETE
FROM RHCS0900
WHERE COD_PESQUISA_OPINIAO = 1

DELETE
FROM RHCS0870
WHERE COD_PESQUISA_OPINIAO = 1