INSERT INTO RHFP0298 (COD_FUNC,DATA_HISTORICO,COD_GRAU_INSTRUCAO,COD_ESTADO_CIVIL,COD_NACIONALIDADE,COD_PESSOA_PARENTE,
COD_PESSOA_PAI,COD_NACION_PAI,COD_PESSOA_MAE,COD_NACION_MAE,COD_PESSOA_CONJUGE,COD_NACION_CONJUGE,
DATA_NASCIMENTO,SEXO,COD_MUNIC_NASCIMENTO,COD_UF_NASCIMENTO,NRO_PIS_PASEP,DATA_PIS_PASEP,
NRO_CONT_INDIVIDUAL,DATA_CONT_INDIVIDUAL,NRO_CTPS,NRO_SERIE_CTPS,DATA_EXP_CTPS,COD_UF_CTPS,
NRO_TITULO,NRO_ZONA_TITULO,NRO_SECAO_TITULO,DATA_EMISSAO_TITULO,COD_UF_TITULO,COD_MUN_TITULO,
NRO_HABILITACAO,NRO_PRONTUARIO_HAB,DATA_EMISSAO_HAB,COD_CATEGORIA_HAB,DATA_VALIDADE_HAB,NRO_IDENTIDADE,
COD_ORG_IDENTIDADE,DATA_EMI_IDENTIDADE,COD_UF_IDENTIDADE,NRO_RESERVISTA,SERVICO_MILITAR,NRO_PASSAPORTE,
DATA_EMI_PASSAPORTE,DATA_VAL_PASSAPORTE,ORGAO_EMISSOR_PASSAP,COD_CONSELHO,COD_ESCOLA,DATA_DIPLOMACAO,
DATA_VALIDADE,NRO_REGISTRO,NRO_LIVRO,NRO_FOLHA,NRO_DOCUMENTO_01,NRO_DOCUMENTO_02,DATA_CASAMENTO,DATA_APOSENTADORIA,
COD_RACA_COR,CANDIDATO,IND_DEFICIENCIA,COD_DEFICIENCIA,DATA_CHEG_BRASIL,DATA_NATURALIZACAO,IND_CASADO_BRASIL,
NRO_TIT_DECLARATORIO,NRO_CARTEIRA_ESTRANG,COD_ORGAO_RNE,DATA_EMI_RNE,IND_FILHO_BRASIL,DATA_EMI_OC,COD_ORGAO_HAB,
IND_DEF_MOTORA,IND_DEF_VISUAL,IND_DEF_AUDITIVA)
SELECT
      FU.COD_FUNC,
      :DATA_REF AS DATA_HISTORICO,
      FU.COD_GRAU_INSTRUCAO,FU.COD_ESTADO_CIVIL,FU.COD_NACIONALIDADE,FU.COD_PESSOA_PARENTE,
      FU.COD_PESSOA_PAI,FU.COD_NACION_PAI,FU.COD_PESSOA_MAE,FU.COD_NACION_MAE,FU.COD_PESSOA_CONJUGE,FU.COD_NACION_CONJUGE,
      FU.DATA_NASCIMENTO,FU.SEXO,FU.COD_MUNIC_NASCIMENTO,FU.COD_UF_NASCIMENTO,FU.NRO_PIS_PASEP,FU.DATA_PIS_PASEP,
      FU.NRO_CONT_INDIVIDUAL,FU.DATA_CONT_INDIVIDUAL,FU.NRO_CTPS,FU.NRO_SERIE_CTPS,FU.DATA_EXP_CTPS,FU.COD_UF_CTPS,
      FU.NRO_TITULO,FU.NRO_ZONA_TITULO,FU.NRO_SECAO_TITULO,FU.DATA_EMISSAO_TITULO,FU.COD_UF_TITULO,FU.COD_MUN_TITULO,
      FU.NRO_HABILITACAO,FU.NRO_PRONTUARIO_HAB,FU.DATA_EMISSAO_HAB,FU.COD_CATEGORIA_HAB,FU.DATA_VALIDADE_HAB,FU.NRO_IDENTIDADE,
      FU.COD_ORG_IDENTIDADE,FU.DATA_EMI_IDENTIDADE,FU.COD_UF_IDENTIDADE,FU.NRO_RESERVISTA,FU.SERVICO_MILITAR,FU.NRO_PASSAPORTE,
      FU.DATA_EMI_PASSAPORTE,FU.DATA_VAL_PASSAPORTE,FU.ORGAO_EMISSOR_PASSAP,FU.COD_CONSELHO,FU.COD_ESCOLA,FU.DATA_DIPLOMACAO,
      FU.DATA_VALIDADE,FU.NRO_REGISTRO,FU.NRO_LIVRO,FU.NRO_FOLHA,FU.NRO_DOCUMENTO_01,FU.NRO_DOCUMENTO_02,FU.DATA_CASAMENTO,
      FU.DATA_APOSENTADORIA,FU.COD_RACA_COR,FU.CANDIDATO,FU.IND_DEFICIENCIA,FU.COD_DEFICIENCIA,FU.DATA_CHEG_BRASIL,
      FU.DATA_NATURALIZACAO,FU.IND_CASADO_BRASIL,FU.NRO_TIT_DECLARATORIO,FU.NRO_CARTEIRA_ESTRANG,FU.COD_ORGAO_RNE,FU.DATA_EMI_RNE,
      FU.IND_FILHO_BRASIL,FU.DATA_EMI_OC,FU.COD_ORGAO_HAB,FU.IND_DEF_MOTORA,FU.IND_DEF_VISUAL,FU.IND_DEF_AUDITIVA
FROM RHFP0200 FU                                               
WHERE FU.COD_FUNC IN (nnnn,nnnn)                    
    
	
	
	evento 2205
	
	CPF DEPENDENTES
	
	EXECUTAR A ROTINA NÃO PERÍODO PRIMEIRO
	E DEPOIS A ''' PERIODICO
	
	COLOCAR O CPF NOS Q FALTAM 