---====SCRIPTS PARA GERAR VALORES DA APR DE GERENTES ADM, SUPERVISORES, REGIONAIS E DIRETORES=====---


--==DIRETORES==--

SELECT B.COD_CONTRATO,
       B.DES_PESSOA,
       B.COD_UNIDADE,
       B.DES_FUNCAO,
       TO_CHAR(ROUND(SUM(A.VALOR_VD), 2), 'FM999G999G990D00') AS SALARIO,
       TO_CHAR(ROUND(SUM(A.VALOR_VD * 10), 2), 'FM999G999G990D00') AS SALARIO_X10,
       TO_CHAR(C.VALOR_VD, 'FM999G999G990D00') AS NOTA_AVALIACAO,
       TO_CHAR(
         ROUND(
           (SUM(A.VALOR_VD * 10) * NVL(C.VALOR_VD, 100)) / 100,
           2
         ),
         'FM999G999G990D00'
       ) AS APR_CALCULADA
  FROM RHFP1006 A
 INNER JOIN V_DADOS_PESSOA B ON B.COD_CONTRATO = A.COD_CONTRATO
  LEFT JOIN RHFP1005 C ON B.COD_CONTRATO = C.COD_CONTRATO AND C.COD_EVENTO = 9 AND C.COD_VD = 1146                      
 WHERE B.DES_FUNCAO LIKE '%DIRETOR%'
   AND B.DES_FUNCAO NOT LIKE '%ASSESSOR DE DIRETORIA%'
   AND B.DES_FUNCAO NOT LIKE '%DIRETOR PRESIDENTE%'
   AND B.DES_FUNCAO NOT LIKE '%DIRETOR VICE-PRESIDENTE%'
   AND A.COD_CONTRATO NOT IN (386492)
   AND A.COD_MESTRE_EVENTO = 16413
   AND A.COD_VD = 1700
 GROUP BY B.COD_CONTRATO,
          B.DES_PESSOA,
          B.COD_UNIDADE,
          B.DES_FUNCAO,
          C.VALOR_VD
 ORDER BY B.COD_UNIDADE ASC;



--==SUPERVISOR==--

SELECT B.COD_CONTRATO,
       B.DES_PESSOA,
       B.COD_UNIDADE,
       B.DES_FUNCAO,
       TO_CHAR(ROUND(SUM(A.VALOR_VD), 2), 'FM999G999G990D00') AS SALARIO,
       TO_CHAR(ROUND(SUM(A.VALOR_VD * 6), 2), 'FM999G999G990D00') AS SALARIO_X6,
       TO_CHAR((C.VALOR_VD), 'FM999G999G990D00') AS NOTA_AVALIACAO,
       CASE
         WHEN C.VALOR_VD IS NOT NULL THEN
          TO_CHAR(((ROUND(SUM(A.VALOR_VD * 6), 2) * C.VALOR_VD) / 100),
                  'FM999G999G990D00')
         ELSE
          NULL -- Ou pode ser uma string vazia ou outro valor default se necessário
       END AS APR_CALCULADA
  FROM RHFP1006 A
 INNER JOIN V_DADOS_PESSOA B ON B.COD_CONTRATO = A.COD_CONTRATO
  LEFT JOIN RHFP1005 C ON B.COD_CONTRATO = C.COD_CONTRATO
                      AND C.COD_EVENTO = 9
                      AND C.COD_VD = 1146
 WHERE B.DES_FUNCAO LIKE '%SUPERVISOR%'
   AND B.COD_GRUPO IN (8, 9)
   AND A.COD_MESTRE_EVENTO = 16413
   AND A.COD_VD = 1700
 GROUP BY B.COD_CONTRATO,
          B.DES_PESSOA,
          B.COD_UNIDADE,
          B.DES_FUNCAO,
          C.VALOR_VD
 ORDER BY B.COD_UNIDADE ASC;
          
          
          

--==REGIONAL==--

SELECT B.COD_CONTRATO,
       B.DES_PESSOA,
       B.COD_UNIDADE,
       B.DES_FUNCAO,
       TO_CHAR(ROUND(SUM(A.VALOR_VD), 2), 'FM999G999G990D00') AS SALARIO,       
       TO_CHAR(ROUND(SUM(A.VALOR_VD * 4), 2), 'FM999G999G990D00') AS SALARIO_MULTIPLICADO,
       C.NOTA_APR,
       TO_CHAR(((ROUND(SUM(A.VALOR_VD * 4), 2) * C.NOTA_APR) / 100),
               'FM999G999G990D00') AS APR_CALCULADA
  FROM GRZ_FOLHA.RHFP1006 A,
       V_DADOS_PESSOA B,
       (SELECT COD_UNIDADE,
               T.COD_REGIONAL,
               SUM(NVL(TREINAMENTO, 0) + NVL(TRAINEE, 0) + NVL(ORCADO, 0) +
                   NVL(MARGEM_PERC, 0) + NVL(LUCRO, 0) + NVL(PERMANENCIA, 0) +
                   NVL(INVENTARIO, 0) + NVL(PREVENTIVA, 0) +
                   NVL(VALE_TRANSP, 0) + NVL(PRODUTIVIDADE, 0) +
                   NVL(FOLHA, 0) + NVL(TURN_OVER, 0)) NOTA_APR
          FROM NL.GRZ_DADOS_CALCULO_APR_ANUAL@NLGRZ A,
               NL.GRZ_EMAIL_REGIONAL@NLGRZ          T
         WHERE A.ANO = 2023
              --AND COD_REDE = 70
           AND A.REGIAO < 8730
           AND A.COD_UNIDADE = T.COD_REGIAO
           AND A.COD_UNIDADE BETWEEN 8700 AND 8720
           AND A.COD_UNIDADE NOT IN (1549, 3549, 4549, 5549, 7549, 0)
         GROUP BY COD_UNIDADE, T.COD_REGIONAL) C
 WHERE B.COD_CONTRATO = A.COD_CONTRATO
   AND B.COD_CONTRATO = C.COD_REGIONAL
   AND B.COD_FUNCAO = 325
      --AND B.COD_GRUPO IN ( 1 ,2 ,3 ,4 , 7)
   AND A.COD_MESTRE_EVENTO = 16413
   AND A.COD_VD = 1700
 GROUP BY B.COD_CONTRATO,
          B.DES_PESSOA,
          B.COD_UNIDADE,
          B.DES_FUNCAO,
          C.NOTA_APR
 ORDER BY COD_UNIDADE ASC
 
 
 
--==GERENTES ADM==--
 
 
SELECT B.COD_CONTRATO,
       B.DES_PESSOA,
       B.COD_UNIDADE,
       B.DES_FUNCAO,
       TO_CHAR(ROUND(SUM(A.VALOR_VD), 2), 'FM999G999G990D00') AS SALARIO,       
       TO_CHAR(ROUND(SUM(A.VALOR_VD * 4), 2), 'FM999G999G990D00') AS SALARIO_X4,
       'NOTA PLR' AS NOTA_AVALIACAO,
       TO_CHAR(((ROUND(SUM(A.VALOR_VD * 4), 2) /** C.VALOR_VD) / 100*/)),
               'FM999G999G990D00') AS APR_CALCULADA
  FROM RHFP1006 A, V_DADOS_PESSOA B/*, RHCS0310 C*/
 WHERE B.COD_CONTRATO = A.COD_CONTRATO
   --AND B.COD_CONTRATO = C.COD_CONTRATO
   AND B.COD_FUNCAO IN
       (7, 8, 78, 79, 86, 87, 128, 137, 184, 186, 189, 190, 275, 283, 294, 299, 318, 325, 328, 330, 355, 188, 14, 88, 81, 345, 80, 77, 192, 90, 185, 264, 255, 15)
      --AND B.COD_GRUPO IN(8,9)
   AND B.COD_GRUPO_UNIDADE >= 700
   AND B.COD_GRUPO_UNIDADE <= 907
   AND A.COD_MESTRE_EVENTO = 16413
   AND A.COD_VD = 1700
   --AND C.DATA_AVALIACAO >= '01/01/2023'
 GROUP BY B.COD_CONTRATO,
          B.DES_PESSOA,
          B.COD_UNIDADE,
          B.DES_FUNCAO
         -- C.NUM_PONTOS