SELECT COD_CONTRATO, DES_PESSOA, DES_FUNCAO, COD_UNIDADE, NOME_ORGANOGRAMA
  FROM V_DADOS_PESSOA
 WHERE (DES_FUNCAO LIKE '%GERENTE%' OR DES_FUNCAO LIKE '%SUPERVISOR%')
   AND COD_EMP = 8
   AND COD_GRUPO NOT IN (1, 2, 3, 4, 7)
 ORDER BY COD_UNIDADE ASC