SELECT A.EDICAO AS CENTRO_CUSTO, '3.4.2.1.24' AS CONTA_DEVEDOR
      ,ROUND(SUM(C.VALOR_PASSAGENS),2) AS VALOR_PASSAGENS, D.NOME_MESTRE, A.NOME_ORGANOGRAMA
FROM SELORG_FPRE0021A A, RHFP0310 B, RHFP0383 C, RHFP0385 D
WHERE A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
AND B.COD_CONTRATO = C.COD_CONTRATO
AND C.COD_MESTRE = D.COD_MESTRE
AND B.DATA_FIM = '31/12/2999'
--AND C.COD_MESTRE = :COD_MESTRE
AND A.COD2 = :COD_EMPRESA
AND A.NOME_ORGANOGRAMA = 'PASSO FUNDO'
--AND D.DATA_INICIO_DISTRIB BETWEEN :DATA_INICIO AND :DATA_FIM
--AND A.EDICAO LIKE '%762%'
--AND SUBSTR(A.EDICAO,1,11) IN ('001.008.001', '001.008.013')
GROUP BY A.EDICAO, '3.4.2.1.24', D.NOME_MESTRE, A.NOME_ORGANOGRAMA
ORDER BY D.NOME_MESTRE, A.EDICAO

SELECT * FROM SELORG_FPRE0021A