SELECT 
FROM JURIDICA J, PESSOA P,


SELECT DISTINCT ORG1.COD_ORGANOGRAMA, FIL.NOME_ESTAB, ORG2.EDICAO_ORG 
FROM FILIAL_ESTAB FIL, RHFP0400 ORG1, RHFP0401 ORG2, RHFP0310 CORG--, RHFP0300 CT, RHFP0306 AFAST
WHERE FIL.NOME_ESTAB = ORG1.NOME_ORGANOGRAMA
AND ORG2.COD_ORGANOGRAMA = ORG1.COD_ORGANOGRAMA
--AND CORG.COD_ORGANOGRAMA = ORG1.COD_ORGANOGRAMA
--AND CT.COD_CONTRATO = CORG.COD_CONTRATO
--AND AFAST.COD_CONTRATO = CT.COD_CONTRATO
AND ORG2.COD_ORGANOGRAMA_SUB = 8
AND ORG2.DATA_FIM = '31/12/2999'
--AND CORG.DATA_FIM = '31/12/2999'
--AND CT.DATA_FIM IS NULL
ORDER BY ORG2.EDICAO_ORG ASC

SELECT * FROM ATIVID
WHERE COD_CONTRATO = 389622

SELECT DISTINCT A1.COD_CONTRATO, A2.COD_ORGANOGRAMA
FROM RHFP0300 A1
INNER JOIN RHFP0310 A2 ON A1.COD_CONTRATO = A2.COD_CONTRATO
LEFT JOIN (
    SELECT DISTINCT RHFP0306.COD_CONTRATO,
           NVL(RHFP0306.COD_CAUSA_AFAST, 0) AS STATUS_AFASTAMENTO
      FROM RHFP0306 RHFP0306
           RIGHT JOIN RHFP0300 RHFP0300 ON RHFP0306.COD_CONTRATO = RHFP0300.COD_CONTRATO
     WHERE '22/08/2023' BETWEEN RHFP0306.DATA_INICIO(+) AND RHFP0306.DATA_FIM(+)
       AND RHFP0300.DATA_FIM IS NULL
       AND NVL(RHFP0306.COD_CAUSA_AFAST, 0) = 0
) Subquery ON A1.COD_CONTRATO = Subquery.COD_CONTRATO
WHERE A1.DATA_FIM IS NULL
  AND A2.DATA_FIM = '31/12/2999';





SELECT DISTINCT RHFP0300.COD_CONTRATO,
       NVL(RHFP0306.COD_CAUSA_AFAST, 0) AS STATUS_AFASTAMENTO
  FROM RHFP0306 RHFP0306,
       RHFP0300 RHFP0300 
 WHERE RHFP0300.COD_CONTRATO = RHFP0306.COD_CONTRATO(+) 
   AND '22/08/2023' BETWEEN RHFP0306.DATA_INICIO(+) AND RHFP0306.DATA_FIM(+)
   AND RHFP0300.DATA_FIM IS NULL
   AND NVL(RHFP0306.COD_CAUSA_AFAST, 0) = 0;

   
   
SELECT 
FROM V_DADOS_PESSOA

SELECT DISTINCT
       ORG_CUSTO_CTB.CUSTO_CONTABIL COD_UNIDADE,
       ORGANOGRAMA.NOME_ORGANOGRAMA,
       INITCAP(ORG_CUSTO_CTB.NOME_CUSTO_CONTABIL) NOME_CUSTO_CONTABIL,
       ORG_EMP.COD_NIVEL2 COD_EMP
  FROM RHFP0200 FP02
  INNER JOIN RHFP0300 FP03             ON FP03.COD_FUNC = FP02.COD_FUNC
  INNER JOIN PESSOA P                  ON P.COD_PESSOA = FP02.COD_FUNC
  INNER JOIN FISICA FIS                ON FIS.COD_PESSOA = FP02.COD_FUNC
  INNER JOIN MUNICI MUN                ON MUN.COD_MUNIC = FIS.COD_MUNIC
  INNER JOIN RHFP0310 CONTR_ORGANOGRAMA ON CONTR_ORGANOGRAMA.COD_CONTRATO = FP03.COD_CONTRATO
  INNER JOIN RHFP0400 ORGANOGRAMA ON ORGANOGRAMA.COD_ORGANOGRAMA = CONTR_ORGANOGRAMA.COD_ORGANOGRAMA
  INNER JOIN RHFP0401 ORG_EMP ON ORG_EMP.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
  LEFT JOIN RHFP0402 ORG_CUSTO_CTB ON ORG_CUSTO_CTB.COD_CUSTO_CONTABIL = ORGANOGRAMA.COD_CUSTO_CONTABIL
  INNER JOIN RHFP0340 CONTRFUNC ON CONTRFUNC.COD_CONTRATO = FP03.COD_CONTRATO
  INNER JOIN RHFP0500 FUNCOES ON FUNCOES.COD_CLH = CONTRFUNC.COD_CLH
  LEFT JOIN MDL_USUARIO SENHA ON SENHA.COD_CONTRATO = FP03.COD_CONTRATO
 WHERE CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
   AND ORG_EMP.COD_NIVEL2 = 8
   AND ORG_EMP.DATA_INICIO <= TRUNC(SYSDATE)
   AND CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
   AND FP03.DATA_FIM IS NULL
   AND SYSDATE BETWEEN CONTRFUNC.DATA_INICIO AND nvl(CONTRFUNC.DATA_FIM,SYSDATE)
   AND SYSDATE BETWEEN ORG_EMP.DATA_INICIO AND nvl(ORG_EMP.DATA_FIM,SYSDATE);
   
   
   
   
   
SELECT DISTINCT
       ORG_CUSTO_CTB.CUSTO_CONTABIL COD_UNIDADE,
       ORGANOGRAMA.NOME_ORGANOGRAMA,
       INITCAP(ORG_CUSTO_CTB.NOME_CUSTO_CONTABIL) NOME_CUSTO_CONTABIL,
       ORG_EMP.COD_NIVEL2 COD_EMP
  FROM RHFP0200 FP02
  INNER JOIN RHFP0300 FP03             ON FP03.COD_FUNC = FP02.COD_FUNC
  INNER JOIN PESSOA P                  ON P.COD_PESSOA = FP02.COD_FUNC
  INNER JOIN FISICA FIS                ON FIS.COD_PESSOA = FP02.COD_FUNC
  INNER JOIN MUNICI MUN                ON MUN.COD_MUNIC = FIS.COD_MUNIC
  INNER JOIN RHFP0310 CONTR_ORGANOGRAMA ON CONTR_ORGANOGRAMA.COD_CONTRATO = FP03.COD_CONTRATO
  INNER JOIN RHFP0400 ORGANOGRAMA ON ORGANOGRAMA.COD_ORGANOGRAMA = CONTR_ORGANOGRAMA.COD_ORGANOGRAMA
  INNER JOIN RHFP0401 ORG_EMP ON ORG_EMP.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
  LEFT JOIN RHFP0402 ORG_CUSTO_CTB ON ORG_CUSTO_CTB.COD_CUSTO_CONTABIL = ORGANOGRAMA.COD_CUSTO_CONTABIL
  INNER JOIN RHFP0340 CONTRFUNC ON CONTRFUNC.COD_CONTRATO = FP03.COD_CONTRATO
  INNER JOIN RHFP0500 FUNCOES ON FUNCOES.COD_CLH = CONTRFUNC.COD_CLH
  LEFT JOIN MDL_USUARIO SENHA ON SENHA.COD_CONTRATO = FP03.COD_CONTRATO
 WHERE CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
   AND ORG_EMP.COD_NIVEL2 = 8
   AND ORG_EMP.DATA_INICIO <= TRUNC(SYSDATE)
   AND CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
   AND FP03.DATA_FIM IS NULL
   AND SYSDATE BETWEEN CONTRFUNC.DATA_INICIO AND nvl(CONTRFUNC.DATA_FIM,SYSDATE)
   AND SYSDATE BETWEEN ORG_EMP.DATA_INICIO AND nvl(ORG_EMP.DATA_FIM,SYSDATE)
   AND ORG_CUSTO_CTB.CUSTO_CONTABIL NOT IN (
       SELECT DISTINCT RHFP0300.COD_CONTRATO
         FROM RHFP0306 RHFP0306,
              RHFP0300 RHFP0300 
        WHERE RHFP0300.COD_CONTRATO = RHFP0306.COD_CONTRATO(+) 
          AND '22/08/2023' BETWEEN RHFP0306.DATA_INICIO(+) AND RHFP0306.DATA_FIM(+)
          AND RHFP0300.DATA_FIM IS NULL
          AND NVL(RHFP0306.COD_CAUSA_AFAST, 0) = 0
   );



SELECT DISTINCT
       ORG_CUSTO_CTB.CUSTO_CONTABIL COD_UNIDADE,
       ORGANOGRAMA.NOME_ORGANOGRAMA,
       INITCAP(ORG_CUSTO_CTB.NOME_CUSTO_CONTABIL) NOME_CUSTO_CONTABIL,
       ORG_EMP.COD_NIVEL2 COD_EMP
  FROM RHFP0200 FP02
  INNER JOIN RHFP0300 FP03             ON FP03.COD_FUNC = FP02.COD_FUNC
  INNER JOIN PESSOA P                  ON P.COD_PESSOA = FP02.COD_FUNC
  INNER JOIN FISICA FIS                ON FIS.COD_PESSOA = FP02.COD_FUNC
  INNER JOIN MUNICI MUN                ON MUN.COD_MUNIC = FIS.COD_MUNIC
  INNER JOIN RHFP0310 CONTR_ORGANOGRAMA ON CONTR_ORGANOGRAMA.COD_CONTRATO = FP03.COD_CONTRATO
  INNER JOIN RHFP0400 ORGANOGRAMA ON ORGANOGRAMA.COD_ORGANOGRAMA = CONTR_ORGANOGRAMA.COD_ORGANOGRAMA
  INNER JOIN RHFP0401 ORG_EMP ON ORG_EMP.COD_ORGANOGRAMA = ORGANOGRAMA.COD_ORGANOGRAMA
  LEFT JOIN RHFP0402 ORG_CUSTO_CTB ON ORG_CUSTO_CTB.COD_CUSTO_CONTABIL = ORGANOGRAMA.COD_CUSTO_CONTABIL
  INNER JOIN RHFP0340 CONTRFUNC ON CONTRFUNC.COD_CONTRATO = FP03.COD_CONTRATO
  INNER JOIN RHFP0500 FUNCOES ON FUNCOES.COD_CLH = CONTRFUNC.COD_CLH
  LEFT JOIN MDL_USUARIO SENHA ON SENHA.COD_CONTRATO = FP03.COD_CONTRATO
  LEFT JOIN RHFP0306 AFASTAMENTO ON AFASTAMENTO.COD_CONTRATO = FP03.COD_CONTRATO
 WHERE CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
   AND ORG_EMP.COD_NIVEL2 = 8
   AND ORG_EMP.DATA_INICIO <= TRUNC(SYSDATE)
   AND CONTR_ORGANOGRAMA.DATA_FIM > SYSDATE
   AND FP03.DATA_FIM IS NULL
   AND SYSDATE BETWEEN CONTRFUNC.DATA_INICIO AND nvl(CONTRFUNC.DATA_FIM,SYSDATE)
   AND SYSDATE BETWEEN ORG_EMP.DATA_INICIO AND nvl(ORG_EMP.DATA_FIM,SYSDATE)
   AND (AFASTAMENTO.COD_CONTRATO IS NULL OR 
        (AFASTAMENTO.COD_CAUSA_AFAST != 0 AND 
         TO_CHAR(AFASTAMENTO.DATA_FIM, 'DD/MM/YYYY') != '31/12/2999'))



SELECT * FROM FUNCIONARIOS
WHERE STATUS_CONTRATO = 0