SELECT CON_EMP.COD_EMPRESA
,CON_EMP.NOME_EMPRESA
,CON_EMP.RAZAO_SOCIAL_EMPRESA
,CON_EMP.COD_PESSOA_EMPRESA
,CON_EMP.ESTEMP_CNPJ
,CON_EMP.EDICAO_FILIAL
,CON_ORG.NOME_ORGANOGRAMA
,CON_EMP.EDICAO_EMPRESA
From RHFP0300 RHFP0300
,  (
SELECT
 RHFP0310.COD_CONTRATO,
 RHFP0310.DATA_INICIO AS DATA_INICIO_ORG,
 RHFP0310.DATA_FIM AS DATA_FIM_ORG,
 RHFP0310.COD_ORGANOGRAMA,
 SUBSTR(RHYF0002(RHFP0310.COD_ORGANOGRAMA,RHFP0400.COD_NIVEL_ORG,:DATA_REFERENCIA),1,80) AS EDICAO_ORGANOGRAMA,
 RHFP0400.NOME_ORGANOGRAMA,
 RHFP0400.COD_NIVEL_ORG,
 RHFP0117.NOME_NIVEL_ORG,
 RHFP0400.COD_PESSOA AS COD_EMPFIL,
 PESSOA_EMPFIL.NOME_PESSOA AS NOME_EMPRESA_FILIAL,
 RHFP0400.CLIENTE,
 RHFP0400.COD_DRT,
 PESSOA_DRT.NOME_PESSOA AS NOME_DRT,
 RHFP0400.ULTIMA_FICHA_REG,
 RHFP0400.COD_CUSTO_CONTABIL,
 RHFP0402.NOME_CUSTO_CONTABIL,
 RHFP0402.CUSTO_CONTABIL,
 RHFP0310.COD_MOTIVO,
 RHFP0323.NOME_MOTIVO,
 RHFP0323.COD_TIPO_MOTIVO,
 RHFP0115.NOME_TIPO_MOTIVO,
 RHFP0310.COD_CAUSA_DEMISSAO,
 RHFP0102.NOME_CAUSA_DEMISSAO,
 RHFP0401.DATA_INICIO AS DATA_INICIO_EST,
 RHFP0401.DATA_FIM AS DATA_FIM_EST,
 RHFP0401.COD_ORGANOGRAMA_SUB,
 RHFP0401.EDICAO_ORG,
 RHFP0401.IND_LANCAMENTO,
 RHFP0436.CCUST_RH,
 RHFP3170.LOTACAO_SIAPE,
 ANTERIOR.DATA_INICIO_ORG AS DATA_INICIO_ORG_ANT,
 ANTERIOR.DATA_FIM_ORG AS DATA_FIM_ORG_ANT,
 ANTERIOR.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_ANT,
 ANTERIOR.NOME_ORGANOGRAMA AS NOME_ORGANOGRAMA_ANT,
 ANTERIOR.EDICAO_ORGANOGRAMA AS EDICAO_ORGANOGRAMA_ANT,
 ANTERIOR.COD_NIVEL_ORG AS COD_NIVEL_ORG_ANT,
 ANTERIOR.NOME_NIVEL_ORG AS NOME_NIVEL_ORG_ANT,
 ANTERIOR.COD_EMPFIL AS COD_EMPFIL_ANT,
 ANTERIOR.NOME_EMPRESA_FILIAL AS NOME_EMPRESA_FILIAL_ANT,
 ANTERIOR.CLIENTE AS CLIENTE_ANT,
 ANTERIOR.COD_DRT AS COD_DRT_ANT,
 ANTERIOR.NOME_DRT AS NOME_DRT_ANT,
 ANTERIOR.ULTIMA_FICHA_REG AS ULTIMA_FICHA_REF_ANT,
 ANTERIOR.COD_CUSTO_CONTABIL AS COD_CUSTO_CONTABIL_ANT,
 ANTERIOR.NOME_CUSTO_CONTABIL AS NOME_CUSTO_CONTABIL_ANT,
 ANTERIOR.CUSTO_CONTABIL AS CUSTO_CONTABIL_ANT,
 ANTERIOR.COD_MOTIVO AS COD_MOTIVO_ANT,
 ANTERIOR.NOME_MOTIVO AS NOME_MOTIVO_ANT,
 ANTERIOR.COD_TIPO_MOTIVO AS COD_TIPO_MOTIVO_ANT,
 ANTERIOR.NOME_TIPO_MOTIVO AS NOME_TIPO_MOTIVO_ANT,
 ANTERIOR.COD_CAUSA_DEMISSAO AS COD_CAUSA_DEMISSAO_ANT,
 ANTERIOR.NOME_CAUSA_DEMISSAO AS NOME_CAUSA_DEMISSAO_ANT,
 ANTERIOR.CCUST_RH AS CCUST_RH_ANT,
 ANTERIOR.LOTACAO_SIAPE AS LOTACAO_SIAPE_ANT,
 DECODE(ORESP.COD_CONTRATO_RESP, RHFP0310.COD_CONTRATO, 'S', 'N') AS IND_RESPONSAVEL,
 ORESP.COD_CONTRATO_RESP AS COD_CONTRATO_RESPORG,
 CTR_ORESP.COD_FUNC AS COD_FUNC_RESPORG,
 PESSOA_ORESP.NOME_PESSOA AS NOME_PESSOA_RESPORG,
 FISICA_ORESP.CPF AS CPF_PESSSOA_RESPORG,
 FISICA_ORESP.EMAIL AS EMAIL_PESSOA_RESPORG
FROM
  RHFP0310 RHFP0310,
  RHFP0300 CTR_ORESP,
  RHFP0400 RHFP0400,
  RHFP0323 RHFP0323,
  RHFP0115 RHFP0115,
  RHFP0102 RHFP0102,
  RHFP0402 RHFP0402,
  RHFP0401 RHFP0401,
  RHFP0436 RHFP0436,
  RHFP3170 RHFP3170,
  PESSOA PESSOA_DRT,
  PESSOA PESSOA_EMPFIL,
  PESSOA PESSOA_ORESP,
  FISICA FISICA_ORESP,
  RHFP0117 RHFP0117,
  RHFP0397 ORESP,
  (SELECT RHFP0310.COD_CONTRATO,
          RHFP0310.DATA_INICIO AS DATA_INICIO_ORG,
          RHFP0310.DATA_FIM AS DATA_FIM_ORG,
          RHFP0310.COD_ORGANOGRAMA,
          RHFP0400.NOME_ORGANOGRAMA,
          SUBSTR(RHYF0002(RHFP0310.COD_ORGANOGRAMA,RHFP0400.COD_NIVEL_ORG,RHFP0310.DATA_INICIO),1,80) AS EDICAO_ORGANOGRAMA,
          RHFP0400.COD_NIVEL_ORG,
          RHFP0117.NOME_NIVEL_ORG,
          RHFP0400.COD_PESSOA AS COD_EMPFIL,
          PESSOA_EMPFIL.NOME_PESSOA AS NOME_EMPRESA_FILIAL,
          RHFP0400.CLIENTE,
          RHFP0400.COD_DRT,
          PESSOA_DRT.NOME_PESSOA AS NOME_DRT,
          RHFP0400.ULTIMA_FICHA_REG,
          RHFP0400.COD_CUSTO_CONTABIL,
          RHFP0402.NOME_CUSTO_CONTABIL,
          RHFP0402.CUSTO_CONTABIL,
          RHFP0310.COD_MOTIVO,
          RHFP0323.NOME_MOTIVO,
          RHFP0323.COD_TIPO_MOTIVO,
          RHFP0115.NOME_TIPO_MOTIVO,
          RHFP0310.COD_CAUSA_DEMISSAO,
          RHFP0102.NOME_CAUSA_DEMISSAO,
          RHFP0436.CCUST_RH,
          RHFP3170.LOTACAO_SIAPE
     FROM RHFP0310 RHFP0310,
          RHFP0400 RHFP0400,
          RHFP0323 RHFP0323,
          RHFP0115 RHFP0115,
          RHFP0102 RHFP0102,
          RHFP0402 RHFP0402,
          RHFP0436 RHFP0436,
          RHFP3170 RHFP3170,
          PESSOA PESSOA_DRT,
          PESSOA PESSOA_EMPFIL,
          RHFP0117 RHFP0117
    WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
      AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
      AND RHFP0310.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO(+)
      AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
      AND RHFP0400.COD_CUSTO_CONTABIL = RHFP0402.COD_CUSTO_CONTABIL(+)
      AND RHFP0400.COD_PESSOA = PESSOA_EMPFIL.COD_PESSOA(+)
      AND RHFP0400.COD_DRT = PESSOA_DRT.COD_PESSOA(+)
      AND RHFP0400.COD_NIVEL_ORG = RHFP0117.COD_NIVEL_ORG(+)
      AND RHFP0310.COD_ORGANOGRAMA = RHFP0436.COD_ORGANOGRAMA(+)
      AND RHFP0310.COD_ORGANOGRAMA = RHFP3170.COD_ORGANOGRAMA(+)
     ) ANTERIOR
WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
      AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
      AND RHFP0310.COD_CAUSA_DEMISSAO = RHFP0102.COD_CAUSA_DEMISSAO(+)
      AND RHFP0323.COD_TIPO_MOTIVO = RHFP0115.COD_TIPO_MOTIVO(+)
      AND RHFP0400.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA(+)
      AND RHFP0400.COD_CUSTO_CONTABIL = RHFP0402.COD_CUSTO_CONTABIL(+)
      AND RHFP0400.COD_PESSOA = PESSOA_EMPFIL.COD_PESSOA(+)
      AND RHFP0400.COD_DRT = PESSOA_DRT.COD_PESSOA(+)
      AND RHFP0400.COD_NIVEL_ORG = RHFP0117.COD_NIVEL_ORG(+)
      AND :DATA_REFERENCIA BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM
      AND RHFP0310.COD_CONTRATO = ANTERIOR.COD_CONTRATO(+)
      AND RHFP0310.DATA_INICIO - 1 = ANTERIOR.DATA_FIM_ORG(+)
      AND :DATA_REFERENCIA BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
      AND RHFP0310.COD_ORGANOGRAMA = RHFP0436.COD_ORGANOGRAMA(+)
      AND RHFP0310.COD_ORGANOGRAMA = RHFP3170.COD_ORGANOGRAMA(+)
      AND RHFP0310.COD_ORGANOGRAMA = ORESP.COD_ORGANOGRAMA(+)
      AND :DATA_REFERENCIA BETWEEN ORESP.DATA_INICIO(+) AND ORESP.DATA_FIM(+)
      AND ORESP.COD_CONTRATO_RESP = CTR_ORESP.COD_CONTRATO(+)
      AND CTR_ORESP.COD_FUNC   = PESSOA_ORESP.COD_PESSOA(+)
      AND PESSOA_ORESP.COD_PESSOA = FISICA_ORESP.COD_PESSOA(+)
 ) CON_ORG
,(
SELECT
        RHFP0310.COD_CONTRATO,
        RHFP0310.DATA_INICIO,
        RHFP0310.DATA_FIM,
        RHFP0310.COD_MOTIVO,
        RHFP0323.NOME_MOTIVO,
        RHFP0401.COD_NIVEL2 AS COD_EMPRESA,
        RHFP0401.COD_NIVEL3 AS COD_FILIAL,
        RHFP0401.COD_NIVEL4,
        RHFP0401.COD_NIVEL5,
        RHFP0401.COD_NIVEL6,
        RHFP0401.COD_NIVEL7,
        RHFP0401.COD_NIVEL8,
       (RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMSEMP_NIVEL4,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5) AS EDICAO_COMSEMP_NIVEL5,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6) AS EDICAO_COMSEMP_NIVEL6,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7) AS EDICAO_COMSEMP_NIVEL7,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7||'.'||RHFP0401.EDICAO_NIVEL8) AS EDICAO_COMSEMP_NIVEL8,
        RHFP0401.EDICAO_NIVEL2 AS EDICAO_COMPOSTA_EMPRESA,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3) AS EDICAO_COMPOSTA_FILIAL,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMPOSTA_NIVEL4,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5) AS EDICAO_COMPOSTA_NIVEL5,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6) AS EDICAO_COMPOSTA_NIVEL6,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7) AS EDICAO_COMPOSTA_NIVEL7,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7||'.'||RHFP0401.EDICAO_NIVEL8) AS EDICAO_COMPOSTA_NIVEL8,
        RHFP0401.EDICAO_NIVEL2 AS EDICAO_EMPRESA,
        RHFP0401.EDICAO_NIVEL3 AS EDICAO_FILIAL,
        RHFP0401.EDICAO_NIVEL4,
        RHFP0401.EDICAO_NIVEL5,
        RHFP0401.EDICAO_NIVEL6,
        RHFP0401.EDICAO_NIVEL7,
        RHFP0401.EDICAO_NIVEL8,

        PESEMP.COD_PESSOA   AS COD_PESSOA_EMPRESA,
        PESFIL.COD_PESSOA   AS COD_PESSOA_FILIAL,
        PESN04.COD_PESSOA   AS COD_PESSOA_NIVEL4,
        PESN05.COD_PESSOA   AS COD_PESSOA_NIVEL5,
        PESEMP.NOME_PESSOA  AS RAZAO_SOCIAL_EMPRESA,
        PESFIL.NOME_PESSOA  AS RAZAO_SOCIAL_FILIAL,
        PESN04.NOME_PESSOA  AS RAZAO_SOCIAL_NIVEL4,
        PESN05.NOME_PESSOA  AS RAZAO_SOCIAL_NIVEL5,
        RESPEMP.COD_PESSOA AS COD_RESP_EMPRESA,
        RESPEMP.NOME_PESSOA AS NOME_RESP_EMPRESA,
        FISEMP.EMAIL AS EMAIL_RESP_EMPRESA,
        RESPFIL.COD_PESSOA AS COD_RESP_FILIAL,
        RESPFIL.NOME_PESSOA AS NOME_RESP_FILIAL,
        FISFIL.EMAIL AS EMAIL_RESP_FILIAL,
        EMP400.NOME_ORGANOGRAMA  AS NOME_EMPRESA,
        FIL400.NOME_ORGANOGRAMA  AS NOME_FILIAL,
        JURFIL.FANTASIA          AS NOME_FANTASIA_FILIAL,
        N4.NOME_ORGANOGRAMA      AS NOME_NIVEL4,
        N5.NOME_ORGANOGRAMA      AS NOME_NIVEL5,
        N6.NOME_ORGANOGRAMA      AS NOME_NIVEL6,
        N7.NOME_ORGANOGRAMA      AS NOME_NIVEL7,
        N8.NOME_ORGANOGRAMA      AS NOME_NIVEL8,
        LOGEMP.NOME_LOGRA     AS LOGRADOURO_EMPRESA,
        JUREMP.NUMERO         AS NUMERO_EMPRESA,
        JUREMP.COMPLEMENTO    AS COMPLEMENTO_EMPRESA,
        BAIEMP.NOME_BAIRRO    AS BAIRRO_EMPRESA,
        MUNEMP.NOME_MUNIC     AS MUNICIPIO_EMPRESA,
        JUREMP.CEP            AS CEP_EMPRESA,
        JUREMP.COD_UF         AS UF_EMPRESA,
        JUREMP.CGC            AS CGC_EMPRESA,
        JUREMP.TIP_LOGRA      AS TIPO_LOG_EMPRESA,
        JUREMP.INSC_EST       AS INSC_ESTADUAL_EMPRESA,
        JUREMP.INSC_MUNIC     AS INSC_MUNICIPAL_EMPRESA,

        LOGFIL.NOME_LOGRA     AS LOGRADOURO_FILIAL,
        JURFIL.NUMERO         AS NUMERO_FILIAL,
        JURFIL.COMPLEMENTO    AS COMPLEMENTO_FILIAL,
        BAIFIL.NOME_BAIRRO    AS BAIRRO_FILIAL,
        MUNFIL.NOME_MUNIC     AS MUNICIPIO_FILIAL,
        JURFIL.CEP            AS CEP_FILIAL,
        JURFIL.COD_UF         AS UF_FILIAL,
        JURFIL.CGC            AS CGC_FILIAL,
        JURFIL.TIP_LOGRA      AS TIPO_LOG_FILIAL,
        JURFIL.DDD            AS DDD_FILIAL,
        JURFIL.FONE           AS FONE_FILIAL,
        JURFIL.INSC_EST       AS INSC_ESTADUAL_FILIAL,
        JURFIL.INSC_MUNIC     AS INSC_MUNICIPAL_FILIAL,

       LOGN4.NOME_LOGRA       AS LOGRADOURO_NIVEL4,
       JURN4.NUMERO           AS NUMERO_NIVEL4,
       JURN4.COMPLEMENTO      AS COMPLEMENTO_NIVEL4,
       BAIN4.NOME_BAIRRO      AS BAIRRO_NIVEL4,
       MUNN4.NOME_MUNIC       AS MUNICIPIO_NIVEL4,
       JURN4.CEP              AS CEP_NIVEL4,
       JURN4.COD_UF           AS UF_NIVEL4,
       JURN4.CGC              AS CGC_NIVEL4,
       JURN4.TIP_LOGRA        AS TIPO_LOG_NIVEL4,
       JURN4.INSC_EST         AS INSC_ESTADUAL_NIVEL4,
       JURN4.INSC_MUNIC       AS INSC_MUNICIPAL_NIVEL4,

       LOGN5.NOME_LOGRA       AS LOGRADOURO_NIVEL5,
       JURN5.NUMERO           AS NUMERO_NIVEL5,
       JURN5.COMPLEMENTO      AS COMPLEMENTO_NIVEL5,
       BAIN5.NOME_BAIRRO      AS BAIRRO_NIVEL5,
       MUNN5.NOME_MUNIC       AS MUNICIPIO_NIVEL5,
       JURN5.CEP              AS CEP_NIVEL5,
       JURN5.COD_UF           AS UF_NIVEL5,
       JURN5.CGC              AS CGC_NIVEL5,
       JURN5.TIP_LOGRA        AS TIPO_LOG_NIVEL5,

       R430EMP.BANCO_DEBITO   AS ESTEMP_BANCO_DEBITO,
       R430EMP.CODAGE_DEBITO  AS ESTEMP_CODAGE_DEBITO,
       R430EMP.DIGAGE_DEBITO  AS ESTEMP_DIGAGE_DEBITO,
       R430EMP.CONTA_DEBITO   AS ESTEMP_CONTA_DEBITO,
       R430EMP.TIPO_INSCRICAO AS ESTEMP_TIPO_INSCRICAO,
       R430EMP.CPF            AS ESTEMP_CPF,
       R430EMP.COD_CEI        AS ESTEMP_COD_CEI,
       JUREMP.CGC             AS ESTEMP_CNPJ,
       SUBSTR(JUREMP.CGC,9,6) AS ESTEMP_COMP_CNPJ,

       R430FIL.BANCO_DEBITO   AS ESTFIL_BANCO_DEBITO,
       R430FIL.CODAGE_DEBITO  AS ESTFIL_CODAGE_DEBITO,
       R430FIL.DIGAGE_DEBITO  AS ESTFIL_DIGAGE_DEBITO,
       R430FIL.CONTA_DEBITO   AS ESTFIL_CONTA_DEBITO,
       R430FIL.TIPO_INSCRICAO AS ESTFIL_TIPO_INSCRICAO,
       R430FIL.CPF            AS ESTFIL_CPF,
       R430FIL.COD_CEI        AS ESTFIL_COD_CEI,
       JURFIL.CGC             AS ESTFIL_CNPJ,
       SUBSTR(JURFIL.CGC,9,6) AS ESTFIL_COMP_CNPJ,


       PESBANEMP.NOME_PESSOA AS ESTEMP_NOME_BANCO_DEBITO,
       PESBANFIL.NOME_PESSOA AS ESTFIL_NOME_BANCO_DEBITO,
       PESAGEEMP.NOME_PESSOA AS ESTEMP_NOME_AGENCIA_DEBITO,
       PESAGEFIL.NOME_PESSOA AS ESTFIL_NOME_AGENCIA_DEBITO,

       ANTERIOR.COD_EMPRESA                        AS ANT_COD_EMPRESA,
       ANTERIOR.DATA_INICIO                        AS ANT_DATA_INICIO,
       ANTERIOR.DATA_FIM                           AS ANT_DATA_FIM,
       ANTERIOR.COD_MOTIVO                         AS ANT_COD_MOTIVO,
       ANTERIOR.NOME_MOTIVO                        AS ANT_NOME_MOTIVO,
       ANTERIOR.COD_FILIAL                         AS ANT_COD_FILIAL,
       ANTERIOR.COD_NIVEL4                         AS ANT_COD_NIVEL4,
       ANTERIOR.COD_NIVEL5                         AS ANT_COD_NIVEL5,
       ANTERIOR.COD_NIVEL6                         AS ANT_COD_NIVEL6,
       ANTERIOR.COD_NIVEL7                         AS ANT_COD_NIVEL7,
       ANTERIOR.COD_NIVEL8                         AS ANT_COD_NIVEL8,
       ANTERIOR.EDICAO_COMSEMP_NIVEL4              AS ANT_EDICAO_COMSEMP_NIVEL4,
       ANTERIOR.EDICAO_COMSEMP_NIVEL5              AS ANT_EDICAO_COMSEMP_NIVEL5,
       ANTERIOR.EDICAO_COMSEMP_NIVEL6              AS ANT_EDICAO_COMSEMP_NIVEL6,
       ANTERIOR.EDICAO_COMSEMP_NIVEL7              AS ANT_EDICAO_COMSEMP_NIVEL7,
       ANTERIOR.EDICAO_COMSEMP_NIVEL8              AS ANT_EDICAO_COMSEMP_NIVEL8,
       ANTERIOR.EDICAO_COMPOSTA_EMPRESA            AS ANT_EDICAO_COMPOSTA_EMPRESA,
       ANTERIOR.EDICAO_COMPOSTA_FILIAL             AS ANT_EDICAO_COMPOSTA_FILIAL,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL4             AS ANT_EDICAO_COMPOSTA_NIVEL4,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL5             AS ANT_EDICAO_COMPOSTA_NIVEL5,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL6             AS ANT_EDICAO_COMPOSTA_NIVEL6,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL7             AS ANT_EDICAO_COMPOSTA_NIVEL7,
       ANTERIOR.EDICAO_COMPOSTA_NIVEL8             AS ANT_EDICAO_COMPOSTA_NIVEL8,
       ANTERIOR.EDICAO_EMPRESA                     AS ANT_EDICAO_EMPRESA,
       ANTERIOR.EDICAO_FILIAL                      AS ANT_EDICAO_FILIAL,
       ANTERIOR.EDICAO_NIVEL4                      AS ANT_EDICAO_NIVEL4,
       ANTERIOR.EDICAO_NIVEL5                      AS ANT_EDICAO_NIVEL5,
       ANTERIOR.EDICAO_NIVEL6                      AS ANT_EDICAO_NIVEL6,
       ANTERIOR.EDICAO_NIVEL7                      AS ANT_EDICAO_NIVEL7,
       ANTERIOR.EDICAO_NIVEL8                      AS ANT_EDICAO_NIVEL8,

       ANTERIOR.COD_PESSOA_EMPRESA                 AS ANT_COD_PESSOA_EMPRESA,
       ANTERIOR.COD_PESSOA_FILIAL                  AS ANT_COD_PESSOA_FILIAL,
       ANTERIOR.COD_PESSOA_NIVEL4                  AS ANT_COD_PESSOA_NIVEL4,
       ANTERIOR.COD_PESSOA_NIVEL5                  AS ANT_COD_PESSOA_NIVEL5,

       ANTERIOR.RAZAO_SOCIAL_EMPRESA               AS ANT_RAZAO_SOCIAL_EMPRESA,
       ANTERIOR.RAZAO_SOCIAL_FILIAL                AS ANT_RAZAO_SOCIAL_FILIAL,
       ANTERIOR.RAZAO_SOCIAL_NIVEL4                AS ANT_RAZAO_SOVIAL_NIVEL4,
       ANTERIOR.RAZAO_SOCIAL_NIVEL5                AS ANT_RAZAO_SOVIAL_NIVEL5,

       ANTERIOR.COD_RESP_EMPRESA                   AS ANT_COD_RESP_EMPRESA,
       ANTERIOR.NOME_RESP_EMPRESA                  AS ANT_NOME_RESP_EMPRESA,
       ANTERIOR.EMAIL_RESP_EMPRESA                 AS ANT_EMAIL_RESP_EMPRESA,
       ANTERIOR.COD_RESP_FILIAL                    AS ANT_COD_RESP_FILIAL,
       ANTERIOR.NOME_RESP_FILIAL                   AS ANT_NOME_RESP_FILIAL,
       ANTERIOR.EMAIL_RESP_FILIAL                  AS ANT_EMAIL_RESP_FILIAL,

       ANTERIOR.NOME_EMPRESA                       AS ANT_NOME_EMPRESA,
       ANTERIOR.NOME_FILIAL                        AS ANT_NOME_FILIAL,
       ANTERIOR.NOME_NIVEL4                        AS ANT_NOME_NIVEL4,
       ANTERIOR.NOME_NIVEL5                        AS ANT_NOME_NIVEL5,
       ANTERIOR.NOME_NIVEL6                        AS ANT_NOME_NIVEL6,
       ANTERIOR.NOME_NIVEL7                        AS ANT_NOME_NIVEL7,
       ANTERIOR.NOME_NIVEL8                        AS ANT_NOME_NIVEL8,

       ANTERIOR.LOGRADOURO_EMPRESA                 AS ANT_LOGRADOURO_EMPRESA,
       ANTERIOR.NUMERO_EMPRESA                     AS ANT_NUMERO_EMPRESA,
       ANTERIOR.COMPLEMENTO_EMPRESA                AS ANT_COMPLEMENTO_EMPRESA,
       ANTERIOR.BAIRRO_EMPRESA                     AS ANT_BAIRRO_EMPRESA,
       ANTERIOR.MUNICIPIO_EMPRESA                  AS ANT_MUNICIPIO_EMPRESA,
       ANTERIOR.CEP_EMPRESA                        AS ANT_CEP_EMPRESA,
       ANTERIOR.UF_EMPRESA                         AS ANT_UF_EMPRESA,
       ANTERIOR.CGC_EMPRESA                        AS ANT_CGC_EMPRESA,
       ANTERIOR.TIPO_LOG_EMPRESA                   AS ANT_TIPO_LOG_EMPRESA,
       ANTERIOR.INSC_EST_EMPRESA                   AS ANT_INSC_ESTADUAL_EMPRESA,
       ANTERIOR.INSC_MUNIC_EMPRESA                 AS ANT_INSC_MUNICIPAL_EMPRESA,

       ANTERIOR.LOGRADOURO_FILIAL                  AS ANT_LOGRADOURO_FILIAL,
       ANTERIOR.NUMERO_FILIAL                      AS ANT_NUMERO_FILIAL,
       ANTERIOR.COMPLEMENTO_FILIAL                 AS ANT_COMPLEMENTO_FILIAL,
       ANTERIOR.BAIRRO_FILIAL                      AS ANT_BAIRRO_FILIAL,
       ANTERIOR.MUNICIPIO_FILIAL                   AS ANT_MUNICIPIO_FILIAL,
       ANTERIOR.CEP_FILIAL                         AS ANT_CEP_FILIAL,
       ANTERIOR.UF_FILIAL                          AS ANT_UF_FILIAL,
       ANTERIOR.CGC_FILIAL                         AS ANT_CGC_FILIAL,
       ANTERIOR.TIPO_LOG_FILIAL                    AS ANT_TIPO_LOG_FILIAL,
       ANTERIOR.INSC_EST_FILIAL                    AS ANT_INSC_ESTADUAL_FILIAL,
       ANTERIOR.INSC_MUNIC_FILIAL                  AS ANT_INSC_MUNICIPAL_FILIAL,

       ANTERIOR.LOGRADOURO_NIVEL4                  AS ANT_LOGRADOURO_NIVEL4,
       ANTERIOR.NUMERO_NIVEL4                      AS ANT_NUMERO_NIVEL4,
       ANTERIOR.COMPLEMENTO_NIVEL4                 AS ANT_COMPLEMENTO_NIVEL4,
       ANTERIOR.BAIRRO_NIVEL4                      AS ANT_BAIRRO_NIVEL4,
       ANTERIOR.MUNICIPIO_NIVEL4                   AS ANT_MUNICIPIO_NIVEL4,
       ANTERIOR.CEP_NIVEL4                         AS ANT_CEP_NIVEL4,
       ANTERIOR.UF_NIVEL4                          AS ANT_UF_NIVEL4,
       ANTERIOR.CGC_NIVEL4                         AS ANT_CGC_NIVEL4,
       ANTERIOR.TIPO_LOG_NIVEL4                    AS ANT_TIPO_LOG_NIVEL4,
       ANTERIOR.INSC_EST_NIVEL4                    AS ANT_INSC_ESTADUAL_NIVEL4,
       ANTERIOR.INSC_MUNIC_NIVEL4                  AS ANT_INSC_MUNICIPAL_NIVEL4,

       ANTERIOR.LOGRADOURO_NIVEL5                  AS ANT_LOGRADOURO_NIVEL5,
       ANTERIOR.NUMERO_NIVEL5                      AS ANT_NUMERO_NIVEL5,
       ANTERIOR.COMPLEMENTO_NIVEL5                 AS ANT_COMPLEMENTO_NIVEL5,
       ANTERIOR.BAIRRO_NIVEL5                      AS ANT_BAIRRO_NIVEL5,
       ANTERIOR.MUNICIPIO_NIVEL5                   AS ANT_MUNICIPIO_NIVEL5,
       ANTERIOR.CEP_NIVEL5                         AS ANT_CEP_NIVEL5,
       ANTERIOR.UF_NIVEL5                          AS ANT_UF_NIVEL5,
       ANTERIOR.CGC_NIVEL5                         AS ANT_CGC_NIVEL5,
       ANTERIOR.TIPO_LOG_NIVEL5                    AS ANT_TIPO_LOG_NIVEL5,

       ANTERIOR.ESTEMP_BANCO_DEBITO                AS ANT_ESTEMP_BANCO_DEBITO,
       ANTERIOR.ESTEMP_CODAGE_DEBITO               AS ANT_ESTEMP_CODAGE_DEBITO,
       ANTERIOR.ESTEMP_DIGAGE_DEBITO               AS ANT_ESTEMP_DIGAGE_DEBITO,
       ANTERIOR.ESTEMP_CONTA_DEBITO                AS ANT_ESTEMP_CONTA_DEBITO,
       ANTERIOR.ESTEMP_TIPO_INSCRICAO              AS ANT_ESTEMP_TIPO_INSCRICAO,
       ANTERIOR.ESTEMP_CPF                         AS ANT_ESTEMP_CPF,
       ANTERIOR.ESTEMP_COD_CEI                     AS ANT_ESTEMP_COD_CEI,
       ANTERIOR.ESTEMP_CNPJ                        AS ANT_ESTEMP_CNPJ,

       ANTERIOR.ESTFIL_BANCO_DEBITO                AS ANT_ESTFIL_BANCO_DEBITO,
       ANTERIOR.ESTFIL_CODAGE_DEBITO               AS ANT_ESTFIL_CODAGE_DEBITO,
       ANTERIOR.ESTFIL_DIGAGE_DEBITO               AS ANT_ESTFIL_DIGAGE_DEBITO,
       ANTERIOR.ESTFIL_CONTA_DEBITO                AS ANT_ESTFIL_CONTA_DEBITO,
       ANTERIOR.ESTFIL_TIPO_INSCRICAO              AS ANT_ESTFIL_TIPO_INSCRICAO,
       ANTERIOR.ESTFIL_CPF                         AS ANT_ESTFIL_CPF,
       ANTERIOR.ESTFIL_COD_CEI                     AS ANT_ESTFIL_COD_CEI,
       ANTERIOR.ESTFIL_CNPJ                        AS ANT_ESTFIL_CNPJ,

       ANTERIOR.ESTEMP_NOME_BANCO_DEBITO           AS ANT_ESTEMP_NOME_BANCO_DEBITO,
       ANTERIOR.ESTFIL_NOME_BANCO_DEBITO           AS ANT_ESTFIL_NOME_BANCO_DEBITO,
       ANTERIOR.ESTEMP_NOME_AGENCIA_DEBITO         AS ANT_ESTEMP_NOME_AGENCIA_DEBITO,
       ANTERIOR.ESTFIL_NOME_AGENCIA_DEBITO         AS ANT_ESTFIL_NOME_AGENCIA_DEBITO


  FROM RHFP0310 RHFP0310,
       RHFP0401 RHFP0401,
       RHFP0400 EMP400,
       RHFP0400 FIL400,
       RHFP0400 N4,
       RHFP0400 N5,
       RHFP0400 N6,
       RHFP0400 N7,
       RHFP0400 N8,

       FISICA FISEMP,
       FISICA FISFIL,
       PESSOA PESEMP,
       PESSOA PESFIL,
       PESSOA PESN04,
       PESSOA PESN05,
       PESSOA RESPEMP,
       PESSOA RESPFIL,

       LOGRA    LOGEMP,
       JURIDICA JUREMP,
       MUNICI   MUNEMP,
       BAIRRO   BAIEMP,

       LOGRA    LOGFIL,
       JURIDICA JURFIL,
       MUNICI   MUNFIL,
       BAIRRO   BAIFIL,

       LOGRA    LOGN4,
       JURIDICA JURN4,
       MUNICI   MUNN4,
       BAIRRO   BAIN4,

       LOGRA    LOGN5,
       JURIDICA JURN5,
       MUNICI   MUNN5,
       BAIRRO   BAIN5,

       RHFP0430 R430EMP,
       RHFP0430 R430FIL,

       BANCO BANEMP,
       AGENCIA AGEEMP,
       BANCO BANFIL,
       AGENCIA AGEFIL,

       PESSOA PESBANEMP,
       PESSOA PESBANFIL,
       PESSOA PESAGEEMP,
       PESSOA PESAGEFIL,
       RHFP0323 RHFP0323,
(
SELECT
       RHFP0310.COD_CONTRATO,
       RHFP0310.DATA_INICIO,
       RHFP0310.DATA_FIM,
       RHFP0310.COD_MOTIVO,
       RHFP0323.NOME_MOTIVO,
       RHFP0401.COD_NIVEL2 AS COD_EMPRESA,
        RHFP0401.COD_NIVEL3 AS COD_FILIAL,
        RHFP0401.COD_NIVEL4,
        RHFP0401.COD_NIVEL5,
        RHFP0401.COD_NIVEL6,
        RHFP0401.COD_NIVEL7,
        RHFP0401.COD_NIVEL8,
       (RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMSEMP_NIVEL4,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5) AS EDICAO_COMSEMP_NIVEL5,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6) AS EDICAO_COMSEMP_NIVEL6,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7) AS EDICAO_COMSEMP_NIVEL7,
       (RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7||'.'||RHFP0401.EDICAO_NIVEL8) AS EDICAO_COMSEMP_NIVEL8,
       RHFP0401.EDICAO_NIVEL2 AS EDICAO_COMPOSTA_EMPRESA,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3) AS EDICAO_COMPOSTA_FILIAL,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4) AS EDICAO_COMPOSTA_NIVEL4,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5) AS EDICAO_COMPOSTA_NIVEL5,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6) AS EDICAO_COMPOSTA_NIVEL6,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7) AS EDICAO_COMPOSTA_NIVEL7,
       (RHFP0401.EDICAO_NIVEL2||'.'||RHFP0401.EDICAO_NIVEL3||'.'||RHFP0401.EDICAO_NIVEL4||'.'||RHFP0401.EDICAO_NIVEL5||'.'||RHFP0401.EDICAO_NIVEL6||'.'||RHFP0401.EDICAO_NIVEL7||'.'||RHFP0401.EDICAO_NIVEL8) AS EDICAO_COMPOSTA_NIVEL8,
       RHFP0401.EDICAO_NIVEL2 AS EDICAO_EMPRESA,
        RHFP0401.EDICAO_NIVEL3 AS EDICAO_FILIAL,
        RHFP0401.EDICAO_NIVEL4,
        RHFP0401.EDICAO_NIVEL5,
        RHFP0401.EDICAO_NIVEL6,
        RHFP0401.EDICAO_NIVEL7,
        RHFP0401.EDICAO_NIVEL8,

       PESEMP.COD_PESSOA   AS COD_PESSOA_EMPRESA,
       PESFIL.COD_PESSOA   AS COD_PESSOA_FILIAL,
       PESN04.COD_PESSOA   AS COD_PESSOA_NIVEL4,
       PESN05.COD_PESSOA   AS COD_PESSOA_NIVEL5,
       PESEMP.NOME_PESSOA  AS RAZAO_SOCIAL_EMPRESA,
       PESFIL.NOME_PESSOA  AS RAZAO_SOCIAL_FILIAL,
       PESN04.NOME_PESSOA  AS RAZAO_SOCIAL_NIVEL4,
       PESN05.NOME_PESSOA  AS RAZAO_SOCIAL_NIVEL5,

       EMP400.NOME_ORGANOGRAMA  AS NOME_EMPRESA,
       FIL400.NOME_ORGANOGRAMA  AS NOME_FILIAL,
       N4.NOME_ORGANOGRAMA      AS NOME_NIVEL4,
       N5.NOME_ORGANOGRAMA      AS NOME_NIVEL5,
       N6.NOME_ORGANOGRAMA      AS NOME_NIVEL6,
       N7.NOME_ORGANOGRAMA      AS NOME_NIVEL7,
       N8.NOME_ORGANOGRAMA      AS NOME_NIVEL8,

       RESPEMP.COD_PESSOA AS COD_RESP_EMPRESA,
       RESPEMP.NOME_PESSOA AS NOME_RESP_EMPRESA,
       FISEMP.EMAIL AS EMAIL_RESP_EMPRESA,
       RESPFIL.COD_PESSOA AS COD_RESP_FILIAL,
       RESPFIL.NOME_PESSOA AS NOME_RESP_FILIAL,
       FISFIL.EMAIL AS EMAIL_RESP_FILIAL,

       LOGEMP.NOME_LOGRA     AS LOGRADOURO_EMPRESA,
       JUREMP.NUMERO         AS NUMERO_EMPRESA,
       JUREMP.COMPLEMENTO    AS COMPLEMENTO_EMPRESA,
       BAIEMP.NOME_BAIRRO    AS BAIRRO_EMPRESA,
       MUNEMP.NOME_MUNIC     AS MUNICIPIO_EMPRESA,
       JUREMP.CEP            AS CEP_EMPRESA,
       JUREMP.COD_UF         AS UF_EMPRESA,
       JUREMP.CGC            AS CGC_EMPRESA,
       JUREMP.TIP_LOGRA      AS TIPO_LOG_EMPRESA,
       JUREMP.INSC_EST       AS INSC_EST_EMPRESA,
       JUREMP.INSC_MUNIC     AS INSC_MUNIC_EMPRESA,

       LOGFIL.NOME_LOGRA     AS LOGRADOURO_FILIAL,
       JURFIL.NUMERO         AS NUMERO_FILIAL,
       JURFIL.COMPLEMENTO    AS COMPLEMENTO_FILIAL,
       BAIFIL.NOME_BAIRRO    AS BAIRRO_FILIAL,
       MUNFIL.NOME_MUNIC     AS MUNICIPIO_FILIAL,
       JURFIL.CEP            AS CEP_FILIAL,
       JURFIL.COD_UF         AS UF_FILIAL,
       JURFIL.CGC            AS CGC_FILIAL,
       JURFIL.TIP_LOGRA      AS TIPO_LOG_FILIAL,
       JURFIL.INSC_EST       AS INSC_EST_FILIAL,
       JURFIL.INSC_MUNIC     AS INSC_MUNIC_FILIAL,

       LOGN4.NOME_LOGRA     AS LOGRADOURO_NIVEL4,
       JURN4.NUMERO         AS NUMERO_NIVEL4,
       JURN4.COMPLEMENTO    AS COMPLEMENTO_NIVEL4,
       BAIN4.NOME_BAIRRO    AS BAIRRO_NIVEL4,
       MUNN4.NOME_MUNIC     AS MUNICIPIO_NIVEL4,
       JURN4.CEP            AS CEP_NIVEL4,
       JURN4.COD_UF         AS UF_NIVEL4,
       JURN4.CGC            AS CGC_NIVEL4,
       JURN4.TIP_LOGRA      AS TIPO_LOG_NIVEL4,
       JURN4.INSC_EST       AS INSC_EST_NIVEL4,
       JURN4.INSC_MUNIC     AS INSC_MUNIC_NIVEL4,

       LOGN5.NOME_LOGRA     AS LOGRADOURO_NIVEL5,
       JURN5.NUMERO         AS NUMERO_NIVEL5,
       JURN5.COMPLEMENTO    AS COMPLEMENTO_NIVEL5,
       BAIN5.NOME_BAIRRO    AS BAIRRO_NIVEL5,
       MUNN5.NOME_MUNIC     AS MUNICIPIO_NIVEL5,
       JURN5.CEP            AS CEP_NIVEL5,
       JURN5.COD_UF         AS UF_NIVEL5,
       JURN5.CGC            AS CGC_NIVEL5,
       JURN5.TIP_LOGRA      AS TIPO_LOG_NIVEL5,

       R430EMP.BANCO_DEBITO   AS ESTEMP_BANCO_DEBITO,
       R430EMP.CODAGE_DEBITO  AS ESTEMP_CODAGE_DEBITO,
       R430EMP.DIGAGE_DEBITO  AS ESTEMP_DIGAGE_DEBITO,
       R430EMP.CONTA_DEBITO   AS ESTEMP_CONTA_DEBITO,
       R430EMP.TIPO_INSCRICAO AS ESTEMP_TIPO_INSCRICAO,
       R430EMP.CPF            AS ESTEMP_CPF,
       R430EMP.COD_CEI        AS ESTEMP_COD_CEI,
       JUREMP.CGC             AS ESTEMP_CNPJ,

       R430FIL.BANCO_DEBITO   AS ESTFIL_BANCO_DEBITO,
       R430FIL.CODAGE_DEBITO  AS ESTFIL_CODAGE_DEBITO,
       R430FIL.DIGAGE_DEBITO  AS ESTFIL_DIGAGE_DEBITO,
       R430FIL.CONTA_DEBITO   AS ESTFIL_CONTA_DEBITO,
       R430FIL.TIPO_INSCRICAO AS ESTFIL_TIPO_INSCRICAO,
       R430FIL.CPF            AS ESTFIL_CPF,
       R430FIL.COD_CEI        AS ESTFIL_COD_CEI,
       JURFIL.CGC             AS ESTFIL_CNPJ,

       PESBANEMP.NOME_PESSOA AS ESTEMP_NOME_BANCO_DEBITO,
       PESBANFIL.NOME_PESSOA AS ESTFIL_NOME_BANCO_DEBITO,
       PESAGEEMP.NOME_PESSOA AS ESTEMP_NOME_AGENCIA_DEBITO,
       PESAGEFIL.NOME_PESSOA AS ESTFIL_NOME_AGENCIA_DEBITO

  FROM RHFP0310 RHFP0310,
       RHFP0401 RHFP0401,

       RHFP0400 EMP400,
       RHFP0400 FIL400,
       RHFP0400 N4,
       RHFP0400 N5,
       RHFP0400 N6,
       RHFP0400 N7,
       RHFP0400 N8,

       LOGRA    LOGEMP,
       JURIDICA JUREMP,
       MUNICI   MUNEMP,
       BAIRRO   BAIEMP,

       LOGRA    LOGFIL,
       JURIDICA JURFIL,
       MUNICI   MUNFIL,
       BAIRRO   BAIFIL,

       LOGRA    LOGN4,
       JURIDICA JURN4,
       MUNICI   MUNN4,
       BAIRRO   BAIN4,

       LOGRA    LOGN5,
       JURIDICA JURN5,
       MUNICI   MUNN5,
       BAIRRO   BAIN5,

       RHFP0430 R430EMP,
       RHFP0430 R430FIL,

       BANCO BANEMP,
       AGENCIA AGEEMP,
       BANCO BANFIL,
       AGENCIA AGEFIL,

       PESSOA PESBANEMP,
       PESSOA PESBANFIL,
       PESSOA PESAGEEMP,
       PESSOA PESAGEFIL,

       FISICA FISEMP,
       FISICA FISFIL,
       PESSOA PESEMP,
       PESSOA PESFIL,
       PESSOA PESN04,
       PESSOA PESN05,
       PESSOA RESPEMP,
       PESSOA RESPFIL,

       RHFP0323 RHFP0323

 WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA
   AND RHFP0310.DATA_INICIO BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
   AND RHFP0401.COD_NIVEL2 = R430EMP.COD_ESTABELECIMENTO(+)
   AND RHFP0401.COD_NIVEL3 = R430FIL.COD_ESTABELECIMENTO(+)

   AND R430EMP.BANCO_DEBITO = BANEMP.COD_BANCO(+)
   AND R430FIL.BANCO_DEBITO = BANFIL.COD_BANCO(+)
   AND R430EMP.BANCO_DEBITO = AGEEMP.COD_BANCO(+)
   AND R430EMP.CODAGE_DEBITO = AGEEMP.COD_AGENCIA(+)
   AND R430FIL.BANCO_DEBITO = AGEFIL.COD_BANCO(+)
   AND R430FIL.CODAGE_DEBITO = AGEFIL.COD_AGENCIA(+)

   AND R430EMP.COD_RESPONSAVEL = RESPEMP.COD_PESSOA(+)
   AND RESPEMP.COD_PESSOA      = FISEMP.COD_PESSOA(+)
   AND R430FIL.COD_RESPONSAVEL = RESPFIL.COD_PESSOA(+)
   AND RESPFIL.COD_PESSOA      = FISFIL.COD_PESSOA(+)

   AND BANEMP.COD_PESSOA = PESBANEMP.COD_PESSOA(+)
   AND BANFIL.COD_PESSOA = PESBANFIL.COD_PESSOA(+)
   AND AGEEMP.COD_PESSOA = PESAGEEMP.COD_PESSOA(+)
   AND AGEFIL.COD_PESSOA = PESAGEFIL.COD_PESSOA(+)

   AND RHFP0401.COD_NIVEL2 = EMP400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL3 = FIL400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL4 = N4.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL5 = N5.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL6 = N6.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL7 = N7.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL8 = N8.COD_ORGANOGRAMA(+)

   AND EMP400.COD_PESSOA = PESEMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = PESFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA     = PESN04.COD_PESSOA(+)
   AND N5.COD_PESSOA     = PESN05.COD_PESSOA(+)

   AND EMP400.COD_PESSOA = JUREMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = JURFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA     = JURN4.COD_PESSOA(+)
   AND N5.COD_PESSOA     = JURN5.COD_PESSOA(+)

   AND JUREMP.COD_LOGRA = LOGEMP.COD_LOGRA(+)
   AND JUREMP.COD_MUNIC = LOGEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF    = LOGEMP.COD_UF(+)
   AND JUREMP.COD_MUNIC = MUNEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF    = MUNEMP.COD_UF(+)
   AND JUREMP.COD_BAIRRO = BAIEMP.COD_BAIRRO(+)
   AND JUREMP.COD_MUNIC  = BAIEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF     = BAIEMP.COD_UF(+)

   AND JURFIL.COD_LOGRA = LOGFIL.COD_LOGRA(+)
   AND JURFIL.COD_MUNIC = LOGFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF    = LOGFIL.COD_UF(+)
   AND JURFIL.COD_MUNIC = MUNFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF    = MUNFIL.COD_UF(+)
   AND JURFIL.COD_BAIRRO = BAIFIL.COD_BAIRRO(+)
   AND JURFIL.COD_MUNIC  = BAIFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF     = BAIFIL.COD_UF(+)

   AND JURN4.COD_LOGRA  = LOGN4.COD_LOGRA(+)
   AND JURN4.COD_MUNIC  = LOGN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = LOGN4.COD_UF(+)
   AND JURN4.COD_MUNIC  = MUNN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = MUNN4.COD_UF(+)
   AND JURN4.COD_BAIRRO = BAIN4.COD_BAIRRO(+)
   AND JURN4.COD_MUNIC  = BAIN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = BAIN4.COD_UF(+)

   AND JURN5.COD_LOGRA  = LOGN5.COD_LOGRA(+)
   AND JURN5.COD_MUNIC  = LOGN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = LOGN5.COD_UF(+)
   AND JURN5.COD_MUNIC  = MUNN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = MUNN5.COD_UF(+)
   AND JURN5.COD_BAIRRO = BAIN5.COD_BAIRRO(+)
   AND JURN5.COD_MUNIC  = BAIN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = BAIN5.COD_UF(+)

   AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
) ANTERIOR

 WHERE RHFP0310.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA
   AND :DATA_REFERENCIA BETWEEN RHFP0401.DATA_INICIO AND RHFP0401.DATA_FIM
   AND :DATA_REFERENCIA BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM

   AND RHFP0401.COD_NIVEL2 = R430EMP.COD_ESTABELECIMENTO(+)
   AND RHFP0401.COD_NIVEL3 = R430FIL.COD_ESTABELECIMENTO(+)
   AND R430EMP.BANCO_DEBITO = BANEMP.COD_BANCO(+)
   AND R430FIL.BANCO_DEBITO = BANFIL.COD_BANCO(+)
   AND R430EMP.BANCO_DEBITO = AGEEMP.COD_BANCO(+)
   AND R430EMP.CODAGE_DEBITO = AGEEMP.COD_AGENCIA(+)
   AND R430FIL.BANCO_DEBITO = AGEFIL.COD_BANCO(+)
   AND R430FIL.CODAGE_DEBITO = AGEFIL.COD_AGENCIA(+)

   AND EMP400.COD_PESSOA = PESEMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = PESFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA     = PESN04.COD_PESSOA(+)
   AND N5.COD_PESSOA     = PESN05.COD_PESSOA(+)

   AND R430EMP.COD_RESPONSAVEL = RESPEMP.COD_PESSOA(+)
   AND RESPEMP.COD_PESSOA = FISEMP.COD_PESSOA(+)
   AND R430FIL.COD_RESPONSAVEL = RESPFIL.COD_PESSOA(+)
   AND RESPFIL.COD_PESSOA = FISFIL.COD_PESSOA(+)

   AND BANEMP.COD_PESSOA = PESBANEMP.COD_PESSOA(+)
   AND BANFIL.COD_PESSOA = PESBANFIL.COD_PESSOA(+)
   AND AGEEMP.COD_PESSOA = PESAGEEMP.COD_PESSOA(+)
   AND AGEFIL.COD_PESSOA = PESAGEFIL.COD_PESSOA(+)

   AND RHFP0401.COD_NIVEL2 = EMP400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL3 = FIL400.COD_ORGANOGRAMA
   AND RHFP0401.COD_NIVEL4 = N4.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL5 = N5.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL6 = N6.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL7 = N7.COD_ORGANOGRAMA(+)
   AND RHFP0401.COD_NIVEL8 = N8.COD_ORGANOGRAMA(+)

   AND EMP400.COD_PESSOA = JUREMP.COD_PESSOA(+)
   AND FIL400.COD_PESSOA = JURFIL.COD_PESSOA(+)
   AND N4.COD_PESSOA = JURN4.COD_PESSOA(+)
   AND N5.COD_PESSOA = JURN5.COD_PESSOA(+)

   AND JUREMP.COD_LOGRA = LOGEMP.COD_LOGRA(+)
   AND JUREMP.COD_MUNIC = LOGEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF    = LOGEMP.COD_UF(+)
   AND JUREMP.COD_MUNIC = MUNEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF    = MUNEMP.COD_UF(+)
   AND JUREMP.COD_BAIRRO = BAIEMP.COD_BAIRRO(+)
   AND JUREMP.COD_MUNIC  = BAIEMP.COD_MUNIC(+)
   AND JUREMP.COD_UF     = BAIEMP.COD_UF(+)

   AND JURFIL.COD_LOGRA = LOGFIL.COD_LOGRA(+)
   AND JURFIL.COD_MUNIC = LOGFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF    = LOGFIL.COD_UF(+)
   AND JURFIL.COD_MUNIC = MUNFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF    = MUNFIL.COD_UF(+)
   AND JURFIL.COD_BAIRRO = BAIFIL.COD_BAIRRO(+)
   AND JURFIL.COD_MUNIC  = BAIFIL.COD_MUNIC(+)
   AND JURFIL.COD_UF     = BAIFIL.COD_UF(+)

   AND JURN4.COD_LOGRA  = LOGN4.COD_LOGRA(+)
   AND JURN4.COD_MUNIC  = LOGN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = LOGN4.COD_UF(+)
   AND JURN4.COD_MUNIC  = MUNN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = MUNN4.COD_UF(+)
   AND JURN4.COD_BAIRRO = BAIN4.COD_BAIRRO(+)
   AND JURN4.COD_MUNIC  = BAIN4.COD_MUNIC(+)
   AND JURN4.COD_UF     = BAIN4.COD_UF(+)

   AND JURN5.COD_LOGRA  = LOGN5.COD_LOGRA(+)
   AND JURN5.COD_MUNIC  = LOGN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = LOGN5.COD_UF(+)
   AND JURN5.COD_MUNIC  = MUNN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = MUNN5.COD_UF(+)
   AND JURN5.COD_BAIRRO = BAIN5.COD_BAIRRO(+)
   AND JURN5.COD_MUNIC  = BAIN5.COD_MUNIC(+)
   AND JURN5.COD_UF     = BAIN5.COD_UF(+)

   AND RHFP0310.COD_CONTRATO = ANTERIOR.COD_CONTRATO(+)
   AND RHFP0310.DATA_INICIO -1 = ANTERIOR.DATA_FIM(+)
   AND RHFP0310.COD_MOTIVO = RHFP0323.COD_MOTIVO(+)
 ) CON_EMP
Where RHFP0300.COD_CONTRATO = CON_EMP.COD_CONTRATO(+)
 and RHFP0300.COD_CONTRATO = CON_ORG.COD_CONTRATO(+)
Group by CON_EMP.COD_EMPRESA
 , CON_EMP.NOME_EMPRESA
 , CON_EMP.RAZAO_SOCIAL_EMPRESA
 , CON_EMP.COD_PESSOA_EMPRESA
 , CON_EMP.ESTEMP_CNPJ
 , CON_EMP.EDICAO_FILIAL
 , CON_ORG.NOME_ORGANOGRAMA
 , CON_EMP.EDICAO_EMPRESA