-----===FORMULÁRIOS===-----

--PROCESSO PAR EXCLUIR UM PEDIDO DE DEMISSÃO NOS FORMULÁRIOS F569 --DELETAR APENAS SE NECESSÁRIO, CASO CONTRARIO APENAS DELETAR NA CONSULTA

DELETE 
FROM GRZ_FORM_PED_DEMISSAO
WHERE COD_COLABORADOR = 386898

SELECT * FROM GRZ_FORM_PED_DEMISSAO
WHERE COD_COLABORADOR = 386898

--=============================================--

--TABELA CONSULTAS DAS RESCISÕES


SELECT * FROM GRZ_FORM_DEMISSAO
WHERE COD_COLABORADOR = 386898

DELETE 
FROM GRZ_FORM_DEMISSAO
WHERE COD_COLABORADOR = 386898