ALTER TABLE RHWW0066 ADD COD_ANEXO NUMBER

/

UPDATE RHWW0066 SET COD_ANEXO = 1

/

ALTER TABLE RHWW0066 ADD NOME_ANEXO VARCHAR(150)

/

ALTER TABLE RHWW0066 ADD NOME_ANEXO_RESPOSTA VARCHAR(150)

/

UPDATE RHWW0066 A SET A.NOME_ANEXO = (SELECT R.NOME_ANEXO FROM RHWW0065 R WHERE R.COD_SOLICITACAO = A.COD_SOLICITACAO)

/

UPDATE RHWW0066 A SET A.NOME_ANEXO_RESPOSTA = (SELECT R.NOME_ANEXO_RESPOSTA FROM RHWW0065 R WHERE R.COD_SOLICITACAO = A.COD_SOLICITACAO)