--SQLs PARA RETORNAR DADOS DAS RESCISÕES, VALORES E CONTAS PARA PAGAMENTO




/*CORRETO ATÉ AQUI*/

SELECT DISTINCT CT.COD_CONTRATO,
                PF.NOME_PESSOA,
                SUBSTR(LPAD(PF.CPF, 11, '0'), 1, 3) || '.' ||
                SUBSTR(LPAD(PF.CPF, 11, '0'), 4, 3) || '.' ||
                SUBSTR(LPAD(PF.CPF, 11, '0'), 7, 3) || '-' ||
                SUBSTR(LPAD(PF.CPF, 11, '0'), 10, 2) AS CPF_FORMATADO,
                B.EDICAO_ORG_2 || ' - ' || B.NOME2 AS EMPRESA,
                B.EDICAO_ORG || ' - ' || B.NOME_ORGANOGRAMA AS FILIAL,
                CT.COD_BCO_PGTO AS COD_BANCO,
                BC.DES_BANCO,
                CT.COD_AGE_PGTO || ' - ' || AG.DIGITO AS COD_AGENCIA,
                AG.DES_AGENCIA,
                CT.NRO_CONTA_PGTO AS NUM_CONTA,
                TO_CHAR(SUM(VLR.VALOR_VD), 'FM999G999G990D00') AS VALOR_RESCISAO
  FROM RHFP0300 CT
  LEFT JOIN V_DADOS_BANCOS_AVT BC ON CT.COD_BCO_PGTO = BC.COD_BANCO
  LEFT JOIN V_AGENCIAS_BANCOS_AVT AG ON CT.COD_AGE_PGTO = AG.COD_AGENCIA
                                    AND CT.COD_BCO_PGTO = AG.COD_BANCO
 INNER JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
 INNER JOIN RHFP0310 A ON CT.COD_CONTRATO = A.COD_CONTRATO
                      AND A.DATA_FIM = '31/12/2999'
 INNER JOIN V_EST_ORG_AVT B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
  LEFT JOIN RHFP1005 VLR ON CT.COD_CONTRATO = VLR.COD_CONTRATO
  LEFT JOIN RHFP1003 EV ON VLR.COD_MESTRE_EVENTO = EV.COD_MESTRE_EVENTO
 WHERE CT.DATA_FIM IS NOT NULL
   AND EV.DATA_REFERENCIA BETWEEN '01/09/2024' AND '30/09/2024'
   AND EV.COD_EVENTO = 17
   AND VLR.COD_VD = 1003
      -- Aqui aplicamos o filtro apenas se o valor passado não for '0'
   AND (:COD_CONTRATO = '0' OR
       CT.COD_CONTRATO IN
       (SELECT * FROM TABLE(SPLIT_CONTRACTS(:COD_CONTRATO))))
 GROUP BY CT.COD_CONTRATO,
          PF.NOME_PESSOA,
          PF.CPF,
          B.EDICAO_ORG_2,
          B.NOME2,
          B.EDICAO_ORG,
          B.NOME_ORGANOGRAMA,
          CT.COD_BCO_PGTO,
          BC.DES_BANCO,
          CT.COD_AGE_PGTO,
          AG.DIGITO,
          AG.DES_AGENCIA,
          CT.NRO_CONTA_PGTO







/*=======================================================VERSÕES ALTERNATIVAS================================================================*/



/*SQL PARA QUANDO OS CÁLCULOS AINDA ESTIVEREM SENDO CALCULADOS, COM SITUAÇÃO EM ABERTO*/

SELECT CT.COD_CONTRATO,
       PF.NOME_PESSOA,
       SUBSTR(LPAD(PF.CPF, 11, '0'), 1, 3) || '.' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 4, 3) || '.' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 7, 3) || '-' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 10, 2) AS CPF_FORMATADO,
       B.EDICAO_ORG_2 || ' - ' || B.NOME2 AS EMPRESA,
       B.EDICAO_ORG || ' - ' || B.NOME_ORGANOGRAMA AS FILIAL,
       CT.COD_BCO_PGTO AS COD_BANCO,
       BC.DES_BANCO,
       CT.COD_AGE_PGTO || ' - ' || AG.DIGITO AS COD_AGENCIA,
       AG.DES_AGENCIA,
       CT.NRO_CONTA_PGTO AS NUM_CONTA,
       EV5.COD_MESTRE_EVENTO,
       EV5.SITUACAO_PROCESSO,
       EV5.DATA_PAGAMENTO,
       TO_CHAR(SUM(VLR5.VALOR_VD), 'FM999G999G990D00') AS VALOR_RESCISAO,
       
       -- Total geral de rescisões
       TO_CHAR(SUM(SUM(VLR5.VALOR_VD)) OVER(), 'FM999G999G990D00') AS TOTAL_GERAL,
       
       -- Quantidade total de funcionários (contratos distintos)
       COUNT(DISTINCT CT.COD_CONTRATO) OVER() AS TOTAL_FUNCIONARIOS

  FROM RHFP0300 CT
  LEFT JOIN V_DADOS_BANCOS_AVT BC ON CT.COD_BCO_PGTO = BC.COD_BANCO
  LEFT JOIN V_AGENCIAS_BANCOS_AVT AG ON CT.COD_AGE_PGTO = AG.COD_AGENCIA
                                    AND CT.COD_BCO_PGTO = AG.COD_BANCO
 INNER JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
 INNER JOIN RHFP0310 A ON CT.COD_CONTRATO = A.COD_CONTRATO
                      AND A.DATA_FIM = '31/12/2999'
 INNER JOIN V_EST_ORG_AVT B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
  LEFT JOIN RHFP1005 VLR5 ON CT.COD_CONTRATO = VLR5.COD_CONTRATO
  LEFT JOIN RHFP1003 EV5 ON VLR5.COD_MESTRE_EVENTO = EV5.COD_MESTRE_EVENTO
 WHERE CT.DATA_FIM IS NOT NULL
   AND EV5.DATA_REFERENCIA BETWEEN '01/09/2024' AND '30/09/2024'
   AND EV5.COD_EVENTO = 17
   AND VLR5.COD_VD = 1003
      --AND VLR5.VALOR_VD <> 0
   AND EV5.SITUACAO_PROCESSO = 'C'
   AND B.COD2 = 8 -- Filtro de empresa
   AND (:COD_CONTRATO = '0' OR
       CT.COD_CONTRATO IN
       (SELECT * FROM TABLE(SPLIT_CONTRACTS(:COD_CONTRATO))))
 GROUP BY CT.COD_CONTRATO,
          PF.NOME_PESSOA,
          PF.CPF,
          B.EDICAO_ORG_2,
          B.NOME2,
          B.EDICAO_ORG,
          B.NOME_ORGANOGRAMA,
          CT.COD_BCO_PGTO,
          BC.DES_BANCO,
          CT.COD_AGE_PGTO,
          AG.DIGITO,
          AG.DES_AGENCIA,
          CT.NRO_CONTA_PGTO,
          EV5.COD_MESTRE_EVENTO,
          EV5.SITUACAO_PROCESSO,
          EV5.DATA_PAGAMENTO

          
          
          
          
/*SQL PARA QUANDO OS CÁLCULOS JÁ ESTIVEREM INCORPORADOS NO FINANCEIRO*/

SELECT CT.COD_CONTRATO,
       PF.NOME_PESSOA,
       SUBSTR(LPAD(PF.CPF, 11, '0'), 1, 3) || '.' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 4, 3) || '.' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 7, 3) || '-' ||
       SUBSTR(LPAD(PF.CPF, 11, '0'), 10, 2) AS CPF_FORMATADO,
       B.EDICAO_ORG_2 || ' - ' || B.NOME2 AS EMPRESA,
       B.EDICAO_ORG || ' - ' || B.NOME_ORGANOGRAMA AS FILIAL,
       CT.COD_BCO_PGTO AS COD_BANCO,
       BC.DES_BANCO,
       CT.COD_AGE_PGTO || ' - ' || AG.DIGITO AS COD_AGENCIA,
       AG.DES_AGENCIA,
       CT.NRO_CONTA_PGTO AS NUM_CONTA,
       EV6.COD_MESTRE_EVENTO,
       EV6.SITUACAO_PROCESSO,
       EV6.DATA_PAGAMENTO,
       TO_CHAR(SUM(VLR6.VALOR_VD), 'FM999G999G990D00') AS VALOR_RESCISAO,
       
       -- Total geral do período e empresa
       TO_CHAR(SUM(SUM(VLR6.VALOR_VD)) OVER(), 'FM999G999G990D00') AS TOTAL_GERAL,
       
       -- Quantidade de funcionários (contratos distintos)
       COUNT(DISTINCT CT.COD_CONTRATO) OVER() AS TOTAL_FUNCIONARIOS

  FROM RHFP0300 CT
  LEFT JOIN V_DADOS_BANCOS_AVT BC ON CT.COD_BCO_PGTO = BC.COD_BANCO
  LEFT JOIN V_AGENCIAS_BANCOS_AVT AG ON CT.COD_AGE_PGTO = AG.COD_AGENCIA
                                    AND CT.COD_BCO_PGTO = AG.COD_BANCO
 INNER JOIN PESSOA_FISICA PF ON CT.COD_FUNC = PF.COD_PESSOA
 INNER JOIN RHFP0310 A ON CT.COD_CONTRATO = A.COD_CONTRATO
                      AND A.DATA_FIM = '31/12/2999'
 INNER JOIN V_EST_ORG_AVT B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
  LEFT JOIN RHFP1006 VLR6 ON CT.COD_CONTRATO = VLR6.COD_CONTRATO
  LEFT JOIN RHFP1003 EV6 ON VLR6.COD_MESTRE_EVENTO = EV6.COD_MESTRE_EVENTO
 WHERE CT.DATA_FIM IS NOT NULL
   AND EV6.DATA_REFERENCIA BETWEEN '01/09/2024' AND '30/09/2024'
   AND EV6.COD_EVENTO = 17
   AND VLR6.COD_VD = 1003
      --AND VLR6.VALOR_VD <> 0
   AND EV6.SITUACAO_PROCESSO = 'I'
   AND B.COD2 = 8 -- Filtro da empresa na consulta principal
   AND (:COD_CONTRATO = '0' OR
       CT.COD_CONTRATO IN
       (SELECT * FROM TABLE(SPLIT_CONTRACTS(:COD_CONTRATO))))
 GROUP BY CT.COD_CONTRATO,
          PF.NOME_PESSOA,
          PF.CPF,
          B.EDICAO_ORG_2,
          B.NOME2,
          B.EDICAO_ORG,
          B.NOME_ORGANOGRAMA,
          CT.COD_BCO_PGTO,
          BC.DES_BANCO,
          CT.COD_AGE_PGTO,
          AG.DIGITO,
          AG.DES_AGENCIA,
          CT.NRO_CONTA_PGTO,
          EV6.COD_MESTRE_EVENTO,
          EV6.SITUACAO_PROCESSO,
          EV6.DATA_PAGAMENTO