--UPDATE PARA REMOVER A DATA_ENCERRAMETO DE UM PERIODO AQUISITIVO
--ONDE AS FÉRIAS FORAM CANCELADAS E JÁ PAGAS, MAS POR SOLICITAÇÃO DO RH,
--PRECISAVA SER REMOVIDA A DATA PARA EFETUAR A EXCLUSÃO DA PROGRAMAÇÃO DE FÉRIAS.
SELECT * FROM RHFP0325
WHERE COD_CONTRATO = 390280;

UPDATE RHFP0325
SET DATA_ENCERRAMENTO = NULL
WHERE COD_CONTRATO = 390280
AND DATA_ENCERRAMENTO = '06/04/2022'