
---= SQLs PARA GERAR OS VALORES DOS VDs 2601, 2605, 2611, 2612, 2615, 2616, 2617 PARA A CONTABILIDADE
  -- PARA QUE FOSSE REALIZADO A CONFERÊNCIA DOS VALORES GERADOS PELOS VDs AOS QUAIS GEROU DIFERENÇAS 
  -- AO INTEGRAR A CONTABILIDADE DA FOLHA.


--SQL SOMENTE O TOTAL DOS VALORES DO VD FILTRADO

SELECT CASE
         WHEN GROUPING(A.COD_VD) = 1 THEN
          NULL
         ELSE
          G.EDICAO_ORG
       END AS "EDICAO_ORG",
       --B.COD_CONTRATO,
       F.NOME_ORGANOGRAMA,
       A.COD_VD,
       A.NOME_VD,
       CASE
         WHEN GROUPING(F.NOME_ORGANOGRAMA) = 1 THEN
          'TOTAL DO VD'
         ELSE
          NULL
       END AS "TOTAL",
       TO_CHAR(SUM(B.VALOR_VD), '9G999G999G990D00') AS VALOR,
       C.COD_EVENTO,
       H.NOME_EVENTO,
       C.DATA_REFERENCIA
  FROM RHFP1000 A,
       RHFP1006 B,
       RHFP1003 C,
       RHFP0300 D,
       RHFP0310 E,
       RHFP0400 F,
       RHFP0401 G,
       RHFP1002 H
 WHERE A.COD_VD = B.COD_VD
   AND B.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
   AND B.COD_CONTRATO = D.COD_CONTRATO
   AND D.COD_CONTRATO = E.COD_CONTRATO
   AND E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
   AND F.COD_ORGANOGRAMA = G.COD_ORGANOGRAMA
   AND H.COD_EVENTO = C.COD_EVENTO
   AND G.COD_NIVEL2 = 8
   AND A.COD_VD = 2601 --2601, 2605, 2611, 2612, 2615, 2616, 2617
   AND C.DATA_REFERENCIA >= '01/04/2022'
   AND C.DATA_REFERENCIA <= '30/04/2022'
   AND E.DATA_FIM = '31/12/2999'
 GROUP BY GROUPING SETS((G.EDICAO_ORG),
                        (G.EDICAO_ORG, 
                         --B.COD_CONTRATO, 
                         F.NOME_ORGANOGRAMA, 
                         A.COD_VD, 
                         A.NOME_VD, 
                         C.COD_EVENTO, 
                         H.NOME_EVENTO, 
                         C.DATA_REFERENCIA));
 
 
 
-- SQL QUE LISTA TODOS OS COLABORADORES COM VALORES NO VD FILTRADO(COD_CONTRATO MASCARADO)
 
SELECT CASE
         WHEN GROUPING(A.COD_VD) = 1 THEN
          NULL
         ELSE
          G.EDICAO_ORG
       END AS "EDICAO_ORG",
       LPAD('', LENGTH(B.COD_CONTRATO), 'X') AS COD_CONTRATO_MASK,
       F.NOME_ORGANOGRAMA,
       A.COD_VD,
       A.NOME_VD,
       CASE
         WHEN GROUPING(F.NOME_ORGANOGRAMA) = 1 THEN
          'TOTAL DO VD'
         ELSE
          NULL
       END AS "TOTAL",
       TO_CHAR(SUM(B.VALOR_VD), '9G999G999G990D00') AS VALOR,
       C.COD_EVENTO,
       H.NOME_EVENTO,
       C.DATA_REFERENCIA
  FROM RHFP1000 A,
       RHFP1006 B,
       RHFP1003 C,
       RHFP0300 D,
       RHFP0310 E,
       RHFP0400 F,
       RHFP0401 G,
       RHFP1002 H
 WHERE A.COD_VD = B.COD_VD
   AND B.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
   AND B.COD_CONTRATO = D.COD_CONTRATO
   AND D.COD_CONTRATO = E.COD_CONTRATO
   AND E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
   AND F.COD_ORGANOGRAMA = G.COD_ORGANOGRAMA
   AND H.COD_EVENTO = C.COD_EVENTO
   AND G.COD_NIVEL2 = 8
   AND A.COD_VD = 2601 --2601, 2605, 2611, 2612, 2615, 2616, 2617
   AND C.DATA_REFERENCIA >= '01/04/2022'
   AND C.DATA_REFERENCIA <= '30/04/2022'
   AND E.DATA_FIM = '31/12/2999'
 GROUP BY GROUPING SETS((G.EDICAO_ORG),(G.EDICAO_ORG, B.COD_CONTRATO, F.NOME_ORGANOGRAMA, A.COD_VD, A.NOME_VD, A.NOME_VD, C.COD_EVENTO, H.NOME_EVENTO, C.DATA_REFERENCIA));


--======


--SQL SEM MASCARAR OS CONTRATOS

SELECT CASE
         WHEN GROUPING(A.COD_VD) = 1 THEN
          NULL
         ELSE
          G.EDICAO_ORG
       END AS "EDICAO_ORG",
       B.COD_CONTRATO,
       F.NOME_ORGANOGRAMA,
       A.COD_VD,
       CASE
         WHEN GROUPING(F.NOME_ORGANOGRAMA) = 1 THEN
          'TOTAL DO VD'
         ELSE
          NULL
       END AS "TOTAL",
       TO_CHAR(SUM(B.VALOR_VD), '9G999G999G990D00') AS VALOR,
       C.COD_EVENTO,
       H.NOME_EVENTO,
       C.DATA_REFERENCIA
  FROM RHFP1000 A,
       RHFP1006 B,
       RHFP1003 C,
       RHFP0300 D,
       RHFP0310 E,
       RHFP0400 F,
       RHFP0401 G,
       RHFP1002 H
 WHERE A.COD_VD = B.COD_VD
   AND B.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
   AND B.COD_CONTRATO = D.COD_CONTRATO
   AND D.COD_CONTRATO = E.COD_CONTRATO
   AND E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
   AND F.COD_ORGANOGRAMA = G.COD_ORGANOGRAMA
   AND H.COD_EVENTO = C.COD_EVENTO
   AND G.COD_NIVEL2 = 8
   AND A.COD_VD = 2611 --2601, 2605, 2611, 2612, 2615, 2616, 2617
   AND C.DATA_REFERENCIA >= '01/04/2022'
   AND C.DATA_REFERENCIA <= '30/04/2022'
   AND E.DATA_FIM = '31/12/2999'
 GROUP BY GROUPING SETS((G.EDICAO_ORG),(G.EDICAO_ORG, B.COD_CONTRATO, F.NOME_ORGANOGRAMA, A.COD_VD, A.NOME_VD, C.COD_EVENTO, H.NOME_EVENTO, C.DATA_REFERENCIA));
 
 
 
--================================================================================================================================================--
--================================================================================================================================================--


--SQL PARA TRAZER OS TOTAIS DOS VDS INFORMADOS E A DESCRIÇÃO DOS MESES QUE GEROU

SELECT G.EDICAO_ORG,
       --LPAD('', LENGTH(B.COD_CONTRATO), 'X') AS COD_CONTRATO_MASK,
       F.NOME_ORGANOGRAMA,
       A.COD_VD,
       A.NOME_VD,
       EXTRACT(MONTH FROM TRUNC(C.DATA_REFERENCIA, 'MM')) AS MES,
       TO_CHAR(TRUNC(C.DATA_REFERENCIA, 'MM'), 'Month') AS MES_NOME,
       EXTRACT(YEAR FROM TRUNC(C.DATA_REFERENCIA, 'MM')) AS ANO,
       TO_CHAR(SUM(B.VALOR_VD), '9G999G999G990D00') AS VALOR,
       C.COD_EVENTO,
       H.NOME_EVENTO,
       TRUNC(C.DATA_REFERENCIA, 'MM') AS DATA_REFERENCIA
  FROM RHFP1000 A,
       RHFP1006 B,
       RHFP1003 C,
       RHFP0300 D,
       RHFP0310 E,
       RHFP0400 F,
       RHFP0401 G,
       RHFP1002 H
 WHERE A.COD_VD = B.COD_VD
   AND B.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
   AND B.COD_CONTRATO = D.COD_CONTRATO
   AND D.COD_CONTRATO = E.COD_CONTRATO
   AND E.COD_ORGANOGRAMA = F.COD_ORGANOGRAMA
   AND F.COD_ORGANOGRAMA = G.COD_ORGANOGRAMA
   AND H.COD_EVENTO = C.COD_EVENTO
   AND G.COD_NIVEL2 = 8
   AND A.COD_VD IN (2601, 2605, 2611, 2612, 2615, 2616, 2617)
   AND C.DATA_REFERENCIA >= '01/04/2022' 
   AND C.DATA_REFERENCIA <= '30/04/2023'
   AND E.DATA_FIM = '31/12/2999'
 GROUP BY G.EDICAO_ORG, F.NOME_ORGANOGRAMA, A.COD_VD, A.NOME_VD, TRUNC(C.DATA_REFERENCIA, 'MM'), C.COD_EVENTO, H.NOME_EVENTO
 ORDER BY G.EDICAO_ORG, F.NOME_ORGANOGRAMA, A.COD_VD, ANO, MES;