
VERSÃO ALTERNATIVA DA V_DADOS_LOJAS_AVT

---CREATE OR REPLACE VIEW V_DADOS_LOJAS_AVT AS
SELECT
    LOJASATV.COD_PESSOA,
    LOJASATV.ORG_LOJA,
    LOJASATV.COD_ORGANOGRAMA_SUB,
    LOJASATV.COD_ORGANOGRAMA,
    LOJASATV.UNIDADE AS COD_UNIDADE,
    LOJASATV.DES_UNIDADE,
    LOJASATV.DATA_INICIO,
    LOJASATV.DATA_FIM,
    LOJASATV.COD_REDE,
    LOJASATV.DES_REDE,
    LOJASATV.EDICAO_NIVEL2 AS COD_EMP,
    LOJASATV.DES_EMAIL,
    --LOJASATV.CELULAR AS NUM_CELULAR,
    LOJASATV.REGIAO AS COD_REGIAO,
    LOJASATV.EDICAO_NIVEL1 || '.' ||
    LOJASATV.EDICAO_NIVEL2 || '.' ||
    LOJASATV.EDICAO_NIVEL3 || '.' ||
    LOJASATV.EDICAO_NIVEL4 || '.' ||
    LOJASATV.EDICAO_NIVEL5 AS EDICAO_COMPLETA,
    LOJASATV.NUM_CGC AS NUM_CNPJ_CGC,
    LOJASATV.CEP AS NUM_CEP,
    LOJASATV.TIP_LOGRA AS TIP_LOGRA,
    LOJASATV.NOME_LOGRA AS DES_LOGRA,
    LOJASATV.NUMERO AS NUM_LOCAL,
    LOJASATV.NOME_BAIRRO AS DES_BAIRRO,
    LOJASATV.NOME_MUNIC AS DES_CIDADE,
    LOJASATV.COD_UF
FROM (
    SELECT
        J.COD_PESSOA,
        A1.COD_NIVEL3 AS ORG_LOJA,
        A1.COD_ORGANOGRAMA_SUB,
        A2.COD_ORGANOGRAMA,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END UNIDADE,
        CASE
            WHEN UNI.REDE IN (10, 30, 40, 50) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 AND UNI.COD_UNIDADE IN (566, 580) THEN
                LPAD(UNI.COD_UNIDADE, 3, '0')
            WHEN UNI.REDE = 70 THEN
                LPAD(UNI.COD_UNIDADE, 4, '0')
        END || ' - ' || UNI.DES_FANTASIA AS DES_UNIDADE,
        A1.DATA_INICIO,
        A1.DATA_FIM,
        NVL(UNI.REDE, 0) COD_REDE,
        DECODE(UNI.REDE,
            10,
            'GRAZZIOTIN',
            30,
            'PORMENOS',
            40,
            'FRANCO GIORGI',
            50,
            'TOTTAL',
            70,
            'GZT STORE') DES_REDE,
        A1.EDICAO_NIVEL2 AS EMPRESA,
        J.EMAIL AS DES_EMAIL,
        --TEL.NUM_FONE AS CELULAR,
        /*CASE
          WHEN TEL.NUM_SEQ = 4 THEN TEL.NUM_FONE
          ELSE NULL
        END AS CELULAR,
        CASE
          WHEN TEL.NUM_SEQ = 2 THEN TEL.NUM_FONE
          ELSE NULL
        END AS COMERCIAL,*/
        REG.COD_GRUPO AS REGIAO,
        UNI.NUM_CGC,
        J.CEP,
        L.TIP_LOGRA,
        L.NOME_LOGRA,
        J.NUMERO,
        B.NOME_BAIRRO,
        M.NOME_MUNIC,
        J.COD_UF,
        A1.EDICAO_NIVEL1,
        A1.EDICAO_NIVEL2,
        A1.EDICAO_NIVEL3,
        A1.EDICAO_NIVEL4,
        A1.EDICAO_NIVEL5,
        ROW_NUMBER() OVER (PARTITION BY UNI.COD_UNIDADE ORDER BY
            CASE WHEN A2.COD_NIVEL_ORG = 5 AND A3.COD_NIVEL_CONTABIL = 5 THEN 0 ELSE 1 END
        ) AS RN
    FROM
    SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI
    INNER JOIN RHFP0401 A1 ON UNI.COD_UNIDADE = A1.EDICAO_ORG
    INNER JOIN RHFP0400 A2 ON A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 A3 ON A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
     --LEFT JOIN RHFP0310 B1 ON B1.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
    INNER JOIN JURIDICA J ON J.CGC = UNI.NUM_CGC
    INNER JOIN NL.GE_GRUPOS_UNIDADES@NLGRZ REG ON REG.COD_UNIDADE = UNI.COD_UNIDADE
    INNER JOIN MUNICI M ON M.COD_MUNIC = J.COD_MUNIC
    INNER JOIN BAIRRO B ON B.COD_BAIRRO = J.COD_BAIRRO
    INNER JOIN LOGRA L ON L.COD_LOGRA = J.COD_LOGRA
    --LEFT  JOIN NL.PS_TELEFONES@NLGRZ TEL ON TEL.COD_PESSOA = UNI.COD_UNIDADE
    WHERE
        UNI.COD_UNIDADE = A1.EDICAO_ORG
        AND A2.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND A3.COD_CUSTO_CONTABIL = A2.COD_CUSTO_CONTABIL
        --AND B1.COD_ORGANOGRAMA = A1.COD_ORGANOGRAMA
        AND J.CGC = UNI.NUM_CGC
        AND REG.COD_UNIDADE = UNI.COD_UNIDADE
        AND M.COD_MUNIC = J.COD_MUNIC
        AND B.COD_BAIRRO = J.COD_BAIRRO
        AND L.COD_LOGRA = J.COD_LOGRA
        --AND TEL.COD_PESSOA = UNI.COD_UNIDADE
        AND UNI.COD_UNIDADE NOT IN (900, 1549, 3549, 4549, 5549, 7549)
        AND REG.COD_GRUPO BETWEEN 8701 AND 8719
        AND A2.COD_NIVEL_ORG = 5
        AND A3.COD_NIVEL_CONTABIL = 5
        --AND TEL.NUM_SEQ = 4
        AND A3.EDICAO_NIVEL5 IS NOT NULL
        AND A1.COD_NIVEL2 NOT IN (004, 006, 128, 276, 282)
        AND A1.COD_NIVEL2 = 8
        AND A1.DATA_FIM = '31/12/2999'
        --AND B1.DATA_FIM = '31/12/2999'
        /*AND (
            (UNI.COD_UNIDADE LIKE '7%' AND B1.DATA_INICIO <= SYSDATE AND (B1.DATA_FIM IS NULL OR B1.DATA_FIM > SYSDATE))
            OR
            (UNI.COD_UNIDADE NOT LIKE '7%')
        )*/
) LOJASATV
WHERE RN = 1
ORDER BY
    LOJASATV.UNIDADE ASC

