---====UPDATE PARA ATUALIZAR A DATA E HORA DE AGENDAMENTO E PÓXIMA EXECUSÃO DE UM PROCESSO

SELECT * FROM RHWF0405
WHERE COD_PROCESSO BETWEEN 1050 AND 1400;

--==================--


UPDATE RHWF0405 r
SET (r.DATA_AGENDAMENTO, r.PROX_EXECUCAO) = (
              /*DEVE-SE SEMPRE INFORMAR A DATA E HORA A SER EXECUTADO*/
  SELECT TO_TIMESTAMP('12/03/2024 09:20:00', 'DD/MM/YYYY HH24:MI:SS') 
         + NUMTODSINTERVAL((rn - 1) * 2, 'MINUTE'),
         TO_TIMESTAMP('12/03/2024 10:00:00', 'DD/MM/YYYY HH24:MI:SS') 
         + NUMTODSINTERVAL((rn - 1) * 2, 'MINUTE')
  FROM (
    SELECT COD_PROCESSO, ROW_NUMBER() OVER (ORDER BY COD_PROCESSO) as rn
    FROM RHWF0405
    WHERE COD_PROCESSO BETWEEN 1051 AND 1400 /*INFORMAR O INTERVALO DE PROCESSOS A SER REAGENDADO*/
  ) 
  WHERE COD_PROCESSO = r.COD_PROCESSO
)
WHERE r.COD_PROCESSO BETWEEN 1051 AND 1400 /*INFORMAR O INTERVALO DE PROCESSOS A SER REAGENDADO*/;