WITH PARAMS AS (
    SELECT
        TO_DATE('01/03/2026', 'DD/MM/YYYY') AS DATA_INICIO,
        TO_DATE('31/03/2026', 'DD/MM/YYYY') AS DATA_FIM,
        :COD_ORGANOGRAMA AS COD_ORGANOGRAMA,
        0.10 AS TOLERANCIA
    FROM DUAL
),

/* =========================
   MAPA BASE
   ========================= */
A_BASE AS (
    SELECT
        A.COD_CLASSE_CONT,
        A.NOME_CLASSE_CONT,
        A.COD_TOTAL,
        A.NOME_TOTAL,
        A.SINAL_OPERACAO,
        A.COD_LANCAMENTO,
        A.COD_CONTA_CONTABIL,
        A.TIPO_LANCAMENTO,
        A.COD_VD
    FROM V_DADOS_CONTABIL_AVT A
    WHERE A.COD_CLASSE_CONT IN (21, 22, 23)
),

CLASSE_BASE AS (
    SELECT DISTINCT
        COD_CLASSE_CONT,
        NOME_CLASSE_CONT
    FROM A_BASE
),

MAP_TOTAL_VD AS (
    SELECT DISTINCT
        COD_CLASSE_CONT,
        NOME_CLASSE_CONT,
        COD_TOTAL,
        NOME_TOTAL,
        SINAL_OPERACAO,
        COD_VD
    FROM A_BASE
),

VD_TOTAL AS (
    SELECT
        X.COD_CLASSE_CONT,
        X.COD_TOTAL,
        X.NOME_TOTAL,
        LISTAGG(X.COD_VD, ' | ') WITHIN GROUP (ORDER BY X.COD_VD) AS VDS_DO_TOTAL
    FROM (
        SELECT DISTINCT
            COD_CLASSE_CONT,
            COD_TOTAL,
            NOME_TOTAL,
            COD_VD
        FROM MAP_TOTAL_VD
    ) X
    GROUP BY
        X.COD_CLASSE_CONT,
        X.COD_TOTAL,
        X.NOME_TOTAL
),

/* =========================
   MAPA CONTÁBIL
   ========================= */
A_MAPA_CONTABIL AS (
    SELECT DISTINCT
        COD_CLASSE_CONT,
        NOME_CLASSE_CONT,
        COD_TOTAL,
        NOME_TOTAL,
        COD_LANCAMENTO,
        COD_CONTA_CONTABIL,
        TIPO_LANCAMENTO
    FROM A_BASE
),

A_MAPA_CHAVE AS (
    SELECT DISTINCT
        COD_CLASSE_CONT,
        COD_LANCAMENTO,
        COD_CONTA_CONTABIL,
        TIPO_LANCAMENTO
    FROM A_MAPA_CONTABIL
),

CHAVE_CONTABIL_REUTILIZADA AS (
    SELECT
        COD_CLASSE_CONT,
        COD_LANCAMENTO,
        COD_CONTA_CONTABIL,
        TIPO_LANCAMENTO,
        COUNT(DISTINCT COD_TOTAL) AS QTD_TOTAIS
    FROM A_MAPA_CONTABIL
    GROUP BY
        COD_CLASSE_CONT,
        COD_LANCAMENTO,
        COD_CONTA_CONTABIL,
        TIPO_LANCAMENTO
    HAVING COUNT(DISTINCT COD_TOTAL) > 1
),

/* =========================
   RHFP0408
   ========================= */
B_BASE AS (
    SELECT
        B.COD_ORGANOGRAMA,
        B.COD_CLASSE_CONT,
        B.COD_CUSTO_CONTABIL,
        B.COD_CUSTO_DESTINO,
        B.COD_LANCAMENTO,
        B.COD_CONTA_CONTABIL,
        B.TIPO_LANCAMENTO,
        NVL(B.VALOR_LANCAMENTO, 0) AS VALOR_LANCAMENTO
    FROM RHFP0408 B
    CROSS JOIN PARAMS P
    WHERE B.COD_ORGANOGRAMA = P.COD_ORGANOGRAMA
      AND B.COD_CLASSE_CONT IN (21, 22, 23)

      /* SE EXISTIR CAMPO DE COMPETÊNCIA NA RHFP0408, FILTRE AQUI.
         EXEMPLOS:
         AND B.DATA_REFERENCIA >= P.DATA_INICIO
         AND B.DATA_REFERENCIA <  P.DATA_FIM + 1
      */
),

B_AGREGADA AS (
    SELECT
        B.COD_CLASSE_CONT,
        B.COD_LANCAMENTO,
        B.COD_CONTA_CONTABIL,
        B.TIPO_LANCAMENTO,
        ROUND(SUM(CASE WHEN B.TIPO_LANCAMENTO = 'D' THEN B.VALOR_LANCAMENTO ELSE 0 END), 2) AS VALOR_DEBITO,
        ROUND(SUM(CASE WHEN B.TIPO_LANCAMENTO = 'C' THEN B.VALOR_LANCAMENTO ELSE 0 END), 2) AS VALOR_CREDITO,
        COUNT(*) AS QTD_LINHAS_RHFP0408,
        COUNT(DISTINCT B.COD_CUSTO_CONTABIL) AS QTD_CUSTOS_CONTABEIS,
        COUNT(DISTINCT B.COD_CUSTO_DESTINO)  AS QTD_CUSTOS_DESTINO
    FROM B_BASE B
    GROUP BY
        B.COD_CLASSE_CONT,
        B.COD_LANCAMENTO,
        B.COD_CONTA_CONTABIL,
        B.TIPO_LANCAMENTO
),

/* =========================
   MATCH CONTÁBIL MAPEADO
   ========================= */
CONTABIL_MATCH_MAPEADO AS (
    SELECT
        M.COD_CLASSE_CONT,
        M.NOME_CLASSE_CONT,
        M.COD_TOTAL,
        M.NOME_TOTAL,
        M.COD_LANCAMENTO,
        M.COD_CONTA_CONTABIL,
        M.TIPO_LANCAMENTO,

        NVL(B.VALOR_DEBITO, 0) AS VALOR_DEBITO_CHAVE,
        NVL(B.VALOR_CREDITO, 0) AS VALOR_CREDITO_CHAVE,

        NVL(B.QTD_LINHAS_RHFP0408, 0) AS QTD_LINHAS_RHFP0408,
        NVL(B.QTD_CUSTOS_CONTABEIS, 0) AS QTD_CUSTOS_CONTABEIS,
        NVL(B.QTD_CUSTOS_DESTINO, 0) AS QTD_CUSTOS_DESTINO,

        CASE
            WHEN B.COD_LANCAMENTO IS NOT NULL THEN 1
            ELSE 0
        END AS CHAVE_ENCONTRADA,

        0 AS CHAVE_SEM_MAPA_VIEW,

        CASE
            WHEN R.COD_LANCAMENTO IS NOT NULL THEN 1
            ELSE 0
        END AS CHAVE_REUTILIZADA

    FROM A_MAPA_CONTABIL M
    LEFT JOIN B_AGREGADA B
           ON B.COD_CLASSE_CONT    = M.COD_CLASSE_CONT
          AND B.COD_LANCAMENTO     = M.COD_LANCAMENTO
          AND B.COD_CONTA_CONTABIL = M.COD_CONTA_CONTABIL
          AND B.TIPO_LANCAMENTO    = M.TIPO_LANCAMENTO
    LEFT JOIN CHAVE_CONTABIL_REUTILIZADA R
           ON R.COD_CLASSE_CONT    = M.COD_CLASSE_CONT
          AND R.COD_LANCAMENTO     = M.COD_LANCAMENTO
          AND R.COD_CONTA_CONTABIL = M.COD_CONTA_CONTABIL
          AND R.TIPO_LANCAMENTO    = M.TIPO_LANCAMENTO
),

/* =========================
   CHAVES DA RHFP0408 SEM MAPA NA VIEW
   ========================= */
CONTABIL_CHAVE_NAO_MAPEADA AS (
    SELECT
        B.COD_CLASSE_CONT,
        C.NOME_CLASSE_CONT,
        -1 AS COD_TOTAL,
        'SEM MAPEAMENTO NA VIEW' AS NOME_TOTAL,
        B.COD_LANCAMENTO,
        B.COD_CONTA_CONTABIL,
        B.TIPO_LANCAMENTO,

        B.VALOR_DEBITO AS VALOR_DEBITO_CHAVE,
        B.VALOR_CREDITO AS VALOR_CREDITO_CHAVE,

        B.QTD_LINHAS_RHFP0408,
        B.QTD_CUSTOS_CONTABEIS,
        B.QTD_CUSTOS_DESTINO,

        1 AS CHAVE_ENCONTRADA,
        1 AS CHAVE_SEM_MAPA_VIEW,
        0 AS CHAVE_REUTILIZADA
    FROM B_AGREGADA B
    JOIN CLASSE_BASE C
      ON C.COD_CLASSE_CONT = B.COD_CLASSE_CONT
    LEFT JOIN A_MAPA_CHAVE M
           ON M.COD_CLASSE_CONT    = B.COD_CLASSE_CONT
          AND M.COD_LANCAMENTO     = B.COD_LANCAMENTO
          AND M.COD_CONTA_CONTABIL = B.COD_CONTA_CONTABIL
          AND M.TIPO_LANCAMENTO    = B.TIPO_LANCAMENTO
    WHERE M.COD_LANCAMENTO IS NULL
),

CONTABIL_MATCH AS (
    SELECT * FROM CONTABIL_MATCH_MAPEADO
    UNION ALL
    SELECT * FROM CONTABIL_CHAVE_NAO_MAPEADA
),

CONTABIL_TOTAL AS (
    SELECT
        C.COD_CLASSE_CONT,
        C.NOME_CLASSE_CONT,
        C.COD_TOTAL,
        C.NOME_TOTAL,

        COUNT(*) AS QTD_CHAVES_MAPA,
        SUM(C.CHAVE_ENCONTRADA) AS QTD_CHAVES_ENCONTRADAS,
        SUM(C.CHAVE_SEM_MAPA_VIEW) AS QTD_CHAVES_SEM_MAPA_VIEW,
        COUNT(*) - SUM(C.CHAVE_ENCONTRADA) AS QTD_CHAVES_SEM_MOVIMENTO,
        MAX(C.CHAVE_REUTILIZADA) AS FLAG_CHAVE_REUTILIZADA,

        SUM(C.QTD_LINHAS_RHFP0408) AS QTD_LINHAS_RHFP0408,
        SUM(C.QTD_CUSTOS_CONTABEIS) AS QTD_CUSTOS_CONTABEIS,
        SUM(C.QTD_CUSTOS_DESTINO) AS QTD_CUSTOS_DESTINO,

        ROUND(SUM(C.VALOR_DEBITO_CHAVE), 2) AS VALOR_DEBITO,
        ROUND(SUM(C.VALOR_CREDITO_CHAVE), 2) AS VALOR_CREDITO
    FROM CONTABIL_MATCH C
    GROUP BY
        C.COD_CLASSE_CONT,
        C.NOME_CLASSE_CONT,
        C.COD_TOTAL,
        C.NOME_TOTAL
),

/* =========================
   FOLHA
   ========================= */
FOLHA_BASE AS (
    SELECT DISTINCT
        B.COD_MESTRE_EVENTO,
        B.COD_EVENTO
    FROM RHFP1003 B
    CROSS JOIN PARAMS P
    WHERE B.COD_EVENTO IN (1, 17, 19, 26)
      AND B.DATA_REFERENCIA >= P.DATA_INICIO
      AND B.DATA_REFERENCIA <  P.DATA_FIM + 1
      AND B.COD_ORGANOGRAMA = P.COD_ORGANOGRAMA
),

FOLHA_VD_EVENTO AS (
    SELECT
        A.COD_VD,
        B.COD_EVENTO,
        ROUND(SUM(NVL(A.VALOR_VD, 0)), 2) AS VALOR_VD
    FROM RHFP1006 A
    JOIN FOLHA_BASE B
      ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    GROUP BY
        A.COD_VD,
        B.COD_EVENTO
),

FOLHA_TOTAL AS (
    SELECT
        M.COD_CLASSE_CONT,
        M.NOME_CLASSE_CONT,
        M.COD_TOTAL,
        M.NOME_TOTAL,

        ROUND(SUM(
            CASE
                WHEN M.COD_TOTAL = 27
                 AND M.COD_VD = 1003
                 AND F.COD_EVENTO NOT IN (17, 19) THEN 0
                WHEN M.SINAL_OPERACAO = '+' THEN NVL(F.VALOR_VD, 0)
                WHEN M.SINAL_OPERACAO = '-' THEN NVL(F.VALOR_VD, 0) * -1
                ELSE 0
            END
        ), 2) AS VALOR_FOLHA
    FROM MAP_TOTAL_VD M
    LEFT JOIN FOLHA_VD_EVENTO F
           ON F.COD_VD = M.COD_VD
    GROUP BY
        M.COD_CLASSE_CONT,
        M.NOME_CLASSE_CONT,
        M.COD_TOTAL,
        M.NOME_TOTAL
),

/* =========================
   CONFLITO DE SINAL
   ========================= */
MAPA_SINAL_CONFLITO AS (
    SELECT
        COD_CLASSE_CONT,
        COD_TOTAL,
        NOME_TOTAL,
        LISTAGG(COD_VD, ' | ') WITHIN GROUP (ORDER BY COD_VD) AS VDS_CONFLITANTES
    FROM (
        SELECT
            COD_CLASSE_CONT,
            COD_TOTAL,
            NOME_TOTAL,
            COD_VD
        FROM A_BASE
        GROUP BY
            COD_CLASSE_CONT,
            COD_TOTAL,
            NOME_TOTAL,
            COD_VD
        HAVING COUNT(DISTINCT SINAL_OPERACAO) > 1
    )
    GROUP BY
        COD_CLASSE_CONT,
        COD_TOTAL,
        NOME_TOTAL
),

/* =========================
   RESULTADO
   ========================= */
RESULTADO AS (
    SELECT
        C.COD_CLASSE_CONT,
        C.NOME_CLASSE_CONT,
        C.COD_TOTAL,
        C.NOME_TOTAL,
        V.VDS_DO_TOTAL,
        MSC.VDS_CONFLITANTES,

        C.QTD_CHAVES_MAPA,
        C.QTD_CHAVES_ENCONTRADAS,
        C.QTD_CHAVES_SEM_MAPA_VIEW,
        C.QTD_CHAVES_SEM_MOVIMENTO,
        C.FLAG_CHAVE_REUTILIZADA,
        C.QTD_LINHAS_RHFP0408,
        C.QTD_CUSTOS_CONTABEIS,
        C.QTD_CUSTOS_DESTINO,

        NVL(C.VALOR_DEBITO, 0)  AS VALOR_DEBITO,
        NVL(C.VALOR_CREDITO, 0) AS VALOR_CREDITO,
        NVL(F.VALOR_FOLHA, 0)   AS VALOR_FOLHA,

        CASE
            WHEN NVL(C.VALOR_DEBITO, 0) <> 0 AND NVL(C.VALOR_CREDITO, 0) = 0 THEN 'DEBITO'
            WHEN NVL(C.VALOR_CREDITO, 0) <> 0 AND NVL(C.VALOR_DEBITO, 0) = 0 THEN 'CREDITO'
            WHEN NVL(C.VALOR_CREDITO, 0) <> 0 AND NVL(C.VALOR_DEBITO, 0) <> 0 THEN 'AMBOS'
            ELSE 'SEM_MOVIMENTO'
        END AS LADO_CONTABIL,

        ROUND(
            CASE
                WHEN NVL(C.VALOR_DEBITO, 0) <> 0 AND NVL(C.VALOR_CREDITO, 0) = 0 THEN NVL(C.VALOR_DEBITO, 0)
                WHEN NVL(C.VALOR_CREDITO, 0) <> 0 AND NVL(C.VALOR_DEBITO, 0) = 0 THEN NVL(C.VALOR_CREDITO, 0)
                ELSE NVL(C.VALOR_DEBITO, 0) - NVL(C.VALOR_CREDITO, 0)
            END
        , 2) AS VALOR_CONTABIL,

        ROUND(
            (
                CASE
                    WHEN NVL(C.VALOR_DEBITO, 0) <> 0 AND NVL(C.VALOR_CREDITO, 0) = 0 THEN NVL(C.VALOR_DEBITO, 0)
                    WHEN NVL(C.VALOR_CREDITO, 0) <> 0 AND NVL(C.VALOR_DEBITO, 0) = 0 THEN NVL(C.VALOR_CREDITO, 0)
                    ELSE NVL(C.VALOR_DEBITO, 0) - NVL(C.VALOR_CREDITO, 0)
                END
            ) - NVL(F.VALOR_FOLHA, 0)
        , 2) AS DIFERENCA_CONTABIL_X_FOLHA

    FROM CONTABIL_TOTAL C
    LEFT JOIN FOLHA_TOTAL F
           ON F.COD_CLASSE_CONT = C.COD_CLASSE_CONT
          AND F.COD_TOTAL       = C.COD_TOTAL
          AND F.NOME_TOTAL      = C.NOME_TOTAL
    LEFT JOIN VD_TOTAL V
           ON V.COD_CLASSE_CONT = C.COD_CLASSE_CONT
          AND V.COD_TOTAL       = C.COD_TOTAL
          AND V.NOME_TOTAL      = C.NOME_TOTAL
    LEFT JOIN MAPA_SINAL_CONFLITO MSC
           ON MSC.COD_CLASSE_CONT = C.COD_CLASSE_CONT
          AND MSC.COD_TOTAL       = C.COD_TOTAL
          AND MSC.NOME_TOTAL      = C.NOME_TOTAL
)

SELECT
    R.COD_CLASSE_CONT AS "Código Classe",
    R.COD_TOTAL AS "Código Totalizador",
    CASE
        WHEN R.COD_TOTAL = -1 THEN R.NOME_TOTAL
        ELSE TO_CHAR(R.COD_TOTAL) || ' - ' || TRIM(R.NOME_TOTAL)
    END AS "Totalizador",
    R.VDS_DO_TOTAL AS "VDs do Total",

    R.QTD_CHAVES_MAPA AS "Qtd Chaves do Mapa",
    R.QTD_CHAVES_ENCONTRADAS AS "Qtd Chaves Encontradas",
    R.QTD_CHAVES_SEM_MAPA_VIEW AS "Qtd Chaves sem Mapa View",
    R.QTD_CHAVES_SEM_MOVIMENTO AS "Qtd Chaves sem Movimento",
    R.QTD_LINHAS_RHFP0408 AS "Qtd Linhas RHFP0408",
    R.QTD_CUSTOS_CONTABEIS AS "Qtd Custos Contábeis",
    R.QTD_CUSTOS_DESTINO AS "Qtd Custos Destino",

    CASE
        WHEN R.FLAG_CHAVE_REUTILIZADA = 1 THEN 'SIM'
        ELSE 'NAO'
    END AS "Chave Reutilizada",

    R.LADO_CONTABIL AS "Lado Contábil",

    TO_CHAR(R.VALOR_DEBITO,   'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS "Valor Débito",
    TO_CHAR(R.VALOR_CREDITO,  'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS "Valor Crédito",
    TO_CHAR(R.VALOR_CONTABIL, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS "Valor Contábil",
    TO_CHAR(R.VALOR_FOLHA,    'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS "Valor Folha",
    TO_CHAR(R.DIFERENCA_CONTABIL_X_FOLHA, 'FM999G999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS "Diferença",

    CASE
        WHEN R.COD_TOTAL = -1 THEN 'SEM_MAPEAMENTO_VIEW'
        WHEN R.VDS_CONFLITANTES IS NOT NULL THEN 'REVISAR_MAPEAMENTO'
        WHEN R.FLAG_CHAVE_REUTILIZADA = 1 THEN 'REVISAR_CONTABIL'
        WHEN R.LADO_CONTABIL = 'AMBOS' THEN 'REVISAR_LADO'
        WHEN ABS(R.DIFERENCA_CONTABIL_X_FOLHA) <= (SELECT TOLERANCIA FROM PARAMS) THEN 'OK'
        ELSE 'DIVERGENTE'
    END AS "Status"

FROM RESULTADO R
ORDER BY
    R.COD_CLASSE_CONT,
    R.COD_TOTAL;
