/*AJUSTANDO - RELATÓRIO ADMITIDOS*/

WITH
PARAMS AS (
/*EXECUTÁVEL NA FOLHA*/
SELECT :DEMISSAO_INICIO AS DEMISSAO_INICIO,
       :DEMISSAO_FIM AS DEMISSAO_FIM
FROM DUAL


/*APENAS PARA TESTES NO PL/SQL*/
/*SELECT '&ADMISSAO_INICIO' AS ADMISSAO_INICIO,
       '&ADMISSAO_FIM' AS ADMISSAO_FIM
FROM DUAL*/

),

CONTRATOS AS (
SELECT DISTINCT
       A.COD_CONTRATO,
       A.DES_PESSOA,
       A.DATA_NASCIMENTO,
       A.IDADE,
       A.SEXO,
       A.DES_EST_CIVIL,
       CASE
           WHEN A.DES_DEFICIENCIA IS NOT NULL THEN
            A.DES_DEFICIENCIA
           ELSE
            'Não Contém'
       END AS DEFICIENCIA,
       SUBSTR(A.CPF, 1, 3) || '.' || SUBSTR(A.cpf, 4, 3) || '.' ||
       SUBSTR(A.CPF, 7, 3) || '-' || SUBSTR(A.cpf, 10, 2) AS CPF,
       A.NRO_IDENTIDADE || ' ' || A.EMISSOR AS IDENTIDADE,
       A.NRO_PIS_PASEP,
       A.CTPS,
       A.NACIONALIDADE,
       A.DES_RACA_COR,
       A.COD_CEP AS CEP,
       INITCAP(A.DES_LOGRA) AS DES_LOGRA,
       A.NUMERO,
       INITCAP(A.DES_BAIRRO) AS DES_BAIRRO,
       INITCAP(A.DES_CIDADE) AS DES_CIDADE,
       A.COD_UF,
       CASE
           WHEN A.DES_PAI IS NOT NULL THEN
            INITCAP(A.DES_PAI)
           ELSE
            'Não Contém Informação'
       END AS PAI,
       CASE
           WHEN A.DES_MAE IS NOT NULL THEN
            INITCAP(A.DES_MAE)
           ELSE
            'Não Contém Informação'
       END AS MAE,


       --DADOS CONTRATUAIS
       A.DATA_ADMISSAO,
       A.DATA_DEMISSAO,
       A.DES_DEMISSAO,
       INITCAP(A.DES_FUNCAO) AS DES_FUNCAO,
       CASE
           WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' THEN
            A.COD_VINCULO_EMPREG || '/' || A.COD_ESOCIAL || ' - APRENDIZ'
           ELSE
            NULL
       END AS VINCULO,
       A.DATA_INICIO_CLH,
       A.DATA_FIM_CLH,
       A.HR_BASE_MES,
       A.HR_BASE_SEM,
       A.HR_BASE_DIA,
       A.DATA_INICIO_HR,
       A.DATA_FIM_HR,
       A.IND_BATE_PONTO,
       CASE
         WHEN A.COD_SINDICATO IS NOT NULL THEN
          A.COD_SINDICATO || ' - ' || INITCAP(A.DES_SINDICATO)
         ELSE
          'Não Contém Informação'
       END AS SINDICATO,
       A.IND_CONT_SINDICAL,
       A.DATA_INI_SIND,
       A.DATA_FIM_SIND,
       A.CONTA_BANCARIA,
       INITCAP(A.DES_BANCO) AS DES_BANCO,
       A.COD_UNIDADE,
       A.DES_UNIDADE,
       A.DATA_INI_ORG,
       A.DATA_FIM_ORG,
       A.COD_REDE_LOCAL,
       A.DES_REDE_LOCAL,
       A.COD_TIPO,
       A.DES_TIPO,
       A.STATUS
  FROM V_DADOS_COLAB_AVT A
  CROSS JOIN PARAMS P
 WHERE A.DATA_DEMISSAO BETWEEN P.DEMISSAO_INICIO AND P.DEMISSAO_FIM
   AND A.COD_EMP = 8
   AND A.STATUS = 1
   --AND A.COD_CONTRATO = 397017

),

DEMISSAO AS (
SELECT A.COD_CONTRATO,
       A.COD_CAUSA_DEMISSAO,
       A.DATA_RESCISAO,
       A.DATA_PAGAMENTO,
       A.DATA_AVISO_PREVIO,
       A.DATA_FIM_AVISO,
       CASE
           WHEN A.AVISO_INDENIZADO = 'N' THEN
            'TRABALHADO'
           WHEN A.AVISO_INDENIZADO = 'S' THEN
            'INDENIZADO'
           ELSE
            'NÃO HÁ'
       END AS AVISO,
       A.DIAS_AV_TOTAL AS DIAS_TOTAL,
       A.DIAS_AV_TRAB AS TRABALHADOS,
       A.DIAS_AV_DISP AS DISPENSADOS,
       A.DIAS_AV_FUNC AS FUNCIONARIO,
       A.DIAS_AVISO_PREVIO AS EMPRESA
FROM RHFP0350 A
CROSS JOIN PARAMS P
WHERE A.DATA_RESCISAO BETWEEN P.DEMISSAO_INICIO AND P.DEMISSAO_FIM

),


DEMISSAO_COMPL AS (
SELECT A.COD_CONTRATO,
       A.DATA_RESCISAO AS DATA_RESCISAO_COMPL,
       A.DATA_COMPLEMENTO AS DATA_COMPLEMENTO_COMPL,
       A.DATA_PAGAMENTO AS DATA_PAGAMENTO_COMPL
FROM RHFP0351 A
CROSS JOIN PARAMS P
WHERE A.DATA_COMPLEMENTO BETWEEN P.DEMISSAO_INICIO AND P.DEMISSAO_FIM

),


INFORMACOES_CONTRATO AS (
SELECT DISTINCT
  COD_CONTRATO,
  MAX(CASE WHEN COD_CAMPO = 5 THEN CONT_ALFA END) AS INFO_HOR_5,
  MAX(CASE WHEN COD_CAMPO = 6 THEN CONT_ALFA END) AS INFO_HOR_6,
  MAX(CASE WHEN COD_CAMPO = 7 THEN CONT_ALFA END) AS INFO_HOR_7,
  MAX(CASE WHEN COD_CAMPO = 8 THEN CONT_ALFA END) AS INFO_HOR_8
FROM RHFP0308
WHERE COD_CAMPO IN (5, 6, 7, 8)
  --AND COD_CONTRATO = 396890
GROUP BY COD_CONTRATO
),


HORARIOS AS (
SELECT DISTINCT
       A.COD_CONTRATO,
       A.DATA_INICIO AS DATA_INICIO_HOR,
       A.DATA_FIM AS DATA_FIM_HOR,
       A.COD_TURNO,
       D.NOME_TURNO AS DES_TURNO,
       A.COD_MOTIVO,
       B.NOME_MOTIVO,
       A.TIPO_TURNO,
       DECODE(D.HORARIO_1_ENT,
              NULL,
              NULL,
              LPAD(RHYF0118(RHYF0117(D.HORARIO_1_ENT), 'S'), 5, '0')) AS HOR_1_ENT,
       DECODE(D.HORARIO_1_SAI,
              NULL,
              NULL,
              LPAD(RHYF0118(RHYF0117(D.HORARIO_1_SAI), 'S'), 5, '0')) AS HOR_1_SAI,
       DECODE(D.HORARIO_2_ENT,
              NULL,
              NULL,
              LPAD(RHYF0118(RHYF0117(D.HORARIO_2_ENT), 'S'), 5, '0')) AS HOR_2_ENT,
       DECODE(D.HORARIO_2_SAI,
              NULL,
              NULL,
              LPAD(RHYF0118(RHYF0117(D.HORARIO_2_SAI), 'S'), 5, '0')) AS HOR_2_SAI,
       DECODE(D.HORARIO_3_ENT,
              NULL,
              NULL,
              LPAD(RHYF0118(RHYF0117(D.HORARIO_3_ENT), 'S'), 5, '0')) AS HOR_3_ENT,
       DECODE(D.HORARIO_3_SAI,
              NULL,
              NULL,
              LPAD(RHYF0118(RHYF0117(D.HORARIO_3_SAI), 'S'), 5, '0')) AS HOR_3_SAI,
       DECODE(D.HORARIO_4_ENT,
              NULL,
              NULL,
              LPAD(RHYF0118(RHYF0117(D.HORARIO_4_ENT), 'S'), 5, '0')) AS HOR_4_ENT,
       DECODE(D.HORARIO_4_SAI,
              NULL,
              NULL,
              LPAD(RHYF0118(RHYF0117(D.HORARIO_4_SAI), 'S'), 5, '0')) AS HOR_4_SAI
  FROM RHAF1119 A, RHFP0323 B, RHFP0115 C, RHAF1145 D, RHAF1103 F, PARAMS P
 WHERE A.COD_MOTIVO = B.COD_MOTIVO(+)
   AND B.COD_TIPO_MOTIVO = C.COD_TIPO_MOTIVO(+)
   AND A.COD_TURNO = D.COD_TURNO(+)
   AND D.COD_CLASSE_TURNO = F.COD_CLASSE_TURNO(+)
   AND P.DEMISSAO_FIM BETWEEN A.DATA_INICIO AND A.DATA_FIM
   --AND a.COD_CONTRATO = 397017

),

CONTRATO_EXPERIENCIA AS (
SELECT
  A.COD_CONTRATO,
  A.DATA_INICIO AS DATA_INI_EXP,
  A.DATA_FIM AS DATA_FIM_EXP,
  TO_NUMBER(TRUNC(A.DATA_FIM - A.DATA_INICIO)+1) AS DIAS_CONTRATO,
  B.DATA_AVALIACAO,
  B.IND_AVALIACAO,
  C.NUM_DIAS,
  C.IND_AVALIACOES,
  D.NOME_TIPO_CONTRATO,
  D.DURACAO_CONTRATO
FROM RHFP0304 A,
     RHFP0305 B,
     RHFP0314 C,
     RHFP0116 D,
     PARAMS P
WHERE P.DEMISSAO_FIM BETWEEN A.DATA_INICIO AND A.DATA_FIM
  AND B.COD_CONTRATO(+) = A.COD_CONTRATO
  AND B.DATA_INICIO(+) = A.DATA_INICIO
  AND A.COD_TP_CONTRATO = C.COD_TP_CONTRATO
  AND C.COD_TIPO_CONTRATO = D.COD_TIPO_CONTRATO

),

SALARIOS AS (
SELECT DISTINCT
       A.COD_CONTRATO,
       TO_CHAR(A.VALOR_SALARIO, 'FM999G999G990D00') AS SALARIO,
       A.DATA_INICIO AS DATA_INI_SAL,
       A.DATA_FIM AS DATA_FIM_SAL,
       A.TIPO_SALARIO,
       DECODE(A.TIPO_SALARIO,'M','Mês','H','Hora','') AS NOME_TIPO_SALARIO
FROM RHFP0608 A
CROSS JOIN PARAMS P
WHERE P.DEMISSAO_FIM BETWEEN A.DATA_INICIO AND A.DATA_FIM
--AND A.COD_CONTRATO = 397017

),

ANTECIPACAO AS (
SELECT DISTINCT
       A.COD_CONTRATO,
       A.COD_MESTRE_EVENTO,
       ROUND(A.VALOR_VD, 2) AS VALOR_ANTE,
       ROUND(A.QTDE_VD, 2) AS QTDE_VD,
       A.COD_VD
  FROM RHFP1006 A,
       (SELECT B.COD_MESTRE_EVENTO,
               B.DATA_REFERENCIA,
               B.COD_EVENTO,
               B.DATA_PAGAMENTO,
               B.DATA_INI_MOV,
               B.DATA_FIM_MOV,
               B.DATA_PROCESSO,
               B.DATA_INCORPORACAO,
               B.SITUACAO_PROCESSO,
               B.IND_CONTABIL,
               B.DATA_APROPRIACAO,
               B.COD_ORGANOGRAMA,
               B.NOME_MESTRE_EVENTO,
               C.NOME_EVENTO
          FROM RHFP1003 B
          JOIN RHFP1002 C ON B.COD_EVENTO = C.COD_EVENTO
          CROSS JOIN PARAMS P
         WHERE B.SITUACAO_PROCESSO = 'I'
           AND B.DATA_REFERENCIA BETWEEN P.DEMISSAO_INICIO AND
               P.DEMISSAO_FIM) MESTRE
 WHERE MESTRE.COD_MESTRE_EVENTO = A.COD_MESTRE_EVENTO
   AND A.COD_VD IN (905)
   --AND A.COD_CONTRATO = 397017


),

DEPENDENTES AS (
SELECT DISTINCT
       A.COD_PESSOA_COLAB,
       A.COD_CONTRATO,
       A.DES_COLAB,
       A.COD_PESSOA_DEPEND,
       A.CPF_DEPEND,
       A.DES_DEPEND,
       A.DTA_NASC_DEPEND,
       A.DATA_INICIO,
       A.DATA_FIM,
       A.COD_GRAU_PARENT,
       A.DES_GRAU_PARENT,
       A.SEXO_DEPEND,
       A.IDADE_DEPEND,
       A.COD_NACIONALIDADE,
       A.NOME_NACIONALIDADE
FROM V_DADOS_DEPEND_COLAB_AVT2 A
CROSS JOIN PARAMS P
WHERE P.DEMISSAO_FIM BETWEEN A.DATA_INICIO AND A.DATA_FIM
--AND A.COD_CONTRATO = 398149

),

DEPENDENTES_NUM AS (
    SELECT
           D.COD_CONTRATO,
           D.DES_DEPEND,
           D.DES_GRAU_PARENT,
           ROW_NUMBER() OVER (
               PARTITION BY D.COD_CONTRATO
               ORDER BY D.DTA_NASC_DEPEND, D.DES_DEPEND, D.COD_PESSOA_DEPEND
           ) AS RN
      FROM DEPENDENTES D
),

DEPENDENTES_PIVOT AS (
    SELECT
           COD_CONTRATO,

           MAX(CASE WHEN RN = 1 THEN DES_DEPEND END)      AS DEPENDENTE_1,
           MAX(CASE WHEN RN = 1 THEN DES_GRAU_PARENT END) AS GRAU_PARENT_1,

           MAX(CASE WHEN RN = 2 THEN DES_DEPEND END)      AS DEPENDENTE_2,
           MAX(CASE WHEN RN = 2 THEN DES_GRAU_PARENT END) AS GRAU_PARENT_2,

           MAX(CASE WHEN RN = 3 THEN DES_DEPEND END)      AS DEPENDENTE_3,
           MAX(CASE WHEN RN = 3 THEN DES_GRAU_PARENT END) AS GRAU_PARENT_3,

           MAX(CASE WHEN RN = 4 THEN DES_DEPEND END)      AS DEPENDENTE_4,
           MAX(CASE WHEN RN = 4 THEN DES_GRAU_PARENT END) AS GRAU_PARENT_4,

           MAX(CASE WHEN RN = 5 THEN DES_DEPEND END)      AS DEPENDENTE_5,
           MAX(CASE WHEN RN = 5 THEN DES_GRAU_PARENT END) AS GRAU_PARENT_5,

           MAX(CASE WHEN RN = 6 THEN DES_DEPEND END)      AS DEPENDENTE_6,
           MAX(CASE WHEN RN = 6 THEN DES_GRAU_PARENT END) AS GRAU_PARENT_6,

           MAX(CASE WHEN RN = 7 THEN DES_DEPEND END)      AS DEPENDENTE_7,
           MAX(CASE WHEN RN = 7 THEN DES_GRAU_PARENT END) AS GRAU_PARENT_7
      FROM DEPENDENTES_NUM
     GROUP BY COD_CONTRATO
),

QTD_CONTRATOS_DISTINCT AS (
  SELECT COUNT(DISTINCT A.COD_CONTRATO) AS QTD_TOTAL
  FROM CONTRATOS A
  JOIN SALARIOS B ON A.COD_CONTRATO = B.COD_CONTRATO
  LEFT JOIN ANTECIPACAO C ON A.COD_CONTRATO = C.COD_CONTRATO
  LEFT JOIN DEPENDENTES D ON A.COD_CONTRATO = D.COD_CONTRATO
  LEFT JOIN HORARIOS E ON A.COD_CONTRATO = E.COD_CONTRATO
  WHERE (A.COD_TIPO = :TIPO OR :TIPO = 0)
    AND (A.COD_UNIDADE = :FILIAL OR :FILIAL = 0)
    AND (A.COD_REDE_LOCAL = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
    AND (A.SEXO = TO_CHAR(:SEXO) OR TO_CHAR(:SEXO) = '0')

)

SELECT DISTINCT
       A.COD_UNIDADE AS UNIDADE,
       A.*,
       R.DATA_RESCISAO,
       R.DATA_PAGAMENTO,
       R.DATA_AVISO_PREVIO,
       R.DATA_FIM_AVISO,
       R.AVISO,
       R.DIAS_TOTAL,
       R.TRABALHADOS,
       R.DISPENSADOS,
       R.FUNCIONARIO,
       R.EMPRESA,
       R1.DATA_RESCISAO_COMPL,
       R1.DATA_COMPLEMENTO_COMPL,
       R1.DATA_PAGAMENTO_COMPL,
       E.HOR_1_ENT,
       E.HOR_1_SAI,
       E.HOR_2_ENT,
       E.HOR_2_SAI,
       E.HOR_3_ENT,
       E.HOR_3_SAI,
       E.HOR_4_ENT,
       E.HOR_4_SAI,
       G.INFO_HOR_5,
       G.INFO_HOR_6,
       G.INFO_HOR_7,
       G.INFO_HOR_8,
       B.SALARIO,
       C.VALOR_ANTE,
       F.NUM_DIAS AS DIAS_CONT_EXP,
       F.DATA_INI_EXP,
       F.DATA_FIM_EXP,

       /*CASE
          WHEN D.DES_DEPEN IS NOT NULL THEN
           REGEXP_SUBSTR(D.DES_DEPEN, '^\S+') || -- Primeiro nome completo

          -- Segundo nome abreviado, se existir
           CASE
          WHEN REGEXP_SUBSTR(D.DES_DEPEN, '^\S+\s+(\S+)', 1, 1, NULL, 1) IS NOT NULL THEN
           ' ' ||
           SUBSTR(REGEXP_SUBSTR(D.DES_DEPEN, '^\S+\s+(\S+)', 1, 1, NULL, 1), 1, 1) || '.'
          ELSE
           ''
        END ||

       -- Se houver ao menos 3 nomes (ou seja, existe 1 sobrenome ou mais)
        CASE
          WHEN REGEXP_SUBSTR(D.DES_DEPEN, '^(\S+\s+){2}(\S+)', 1, 1, NULL, 2) IS NOT NULL AND
               REGEXP_SUBSTR(D.DES_DEPEN, '^(\S+\s+){3}(\S+)', 1, 1, NULL, 2) IS NOT NULL THEN
           ' ' ||
           SUBSTR(REGEXP_SUBSTR(D.DES_DEPEN, '^(\S+\s+){2}(\S+)', 1, 1, NULL, 2),
                  1,
                  1) || '.' || ' ' ||
           REGEXP_SUBSTR(D.DES_DEPEN, '^(\S+\s+){3}(.*)$', 1, 1, NULL, 2)
          WHEN REGEXP_SUBSTR(D.DES_DEPEN, '^(\S+\s+){2}(\S+)', 1, 1, NULL, 2) IS NOT NULL THEN
           ' ' || REGEXP_SUBSTR(D.DES_DEPEN, '^(\S+\s+){2}(\S+)', 1, 1, NULL, 2)
          ELSE
           ''
        END

       ELSE 'Não Contém Informação' END AS DEPENDENTE,*/

       CASE
           WHEN D.DEPENDENTE_1 IS NOT NULL THEN
            INITCAP(D.DEPENDENTE_1) || ' (' || INITCAP(D.GRAU_PARENT_1) || ')'
           ELSE
            NULL
       END AS DEPENDENTE_1,
       CASE
           WHEN D.DEPENDENTE_2 IS NOT NULL THEN
            INITCAP(D.DEPENDENTE_2) || ' (' || INITCAP(D.GRAU_PARENT_2) || ')'
           ELSE
            NULL
       END AS DEPENDENTE_2,
       CASE
           WHEN D.DEPENDENTE_3 IS NOT NULL THEN
            INITCAP(D.DEPENDENTE_3) || ' (' || INITCAP(D.GRAU_PARENT_3) || ')'
           ELSE
            NULL
       END AS DEPENDENTE_3,
       CASE
           WHEN D.DEPENDENTE_4 IS NOT NULL THEN
            INITCAP(D.DEPENDENTE_4) || ' (' || INITCAP(D.GRAU_PARENT_4) || ')'
           ELSE
            NULL
       END AS DEPENDENTE_4,
       CASE
           WHEN D.DEPENDENTE_5 IS NOT NULL THEN
            INITCAP(D.DEPENDENTE_5) || ' (' || INITCAP(D.GRAU_PARENT_5) || ')'
           ELSE
            NULL
       END AS DEPENDENTE_5,
       CASE
           WHEN D.DEPENDENTE_6 IS NOT NULL THEN
            INITCAP(D.DEPENDENTE_6) || ' (' || INITCAP(D.GRAU_PARENT_6) || ')'
           ELSE
            NULL
       END AS DEPENDENTE_6,
       CASE
           WHEN D.DEPENDENTE_7 IS NOT NULL THEN
            INITCAP(D.DEPENDENTE_7) || ' (' || INITCAP(D.GRAU_PARENT_7) || ')'
           ELSE
            NULL
       END AS DEPENDENTE_7,

       (SELECT QTD_TOTAL FROM QTD_CONTRATOS_DISTINCT) AS QTD_CONTRATOS,
       'De ' || :DEMISSAO_INICIO || ' à ' || :DEMISSAO_FIM AS PERIODO_GERACAO
  FROM CONTRATOS A
  JOIN SALARIOS B ON A.COD_CONTRATO = B.COD_CONTRATO
  LEFT JOIN ANTECIPACAO C ON A.COD_CONTRATO = C.COD_CONTRATO
  LEFT JOIN DEPENDENTES_PIVOT D ON A.COD_CONTRATO = D.COD_CONTRATO
  LEFT JOIN HORARIOS E ON A.COD_CONTRATO = E.COD_CONTRATO
  LEFT JOIN CONTRATO_EXPERIENCIA F ON A.COD_CONTRATO = F.COD_CONTRATO
  LEFT JOIN INFORMACOES_CONTRATO G ON A.COD_CONTRATO = G.COD_CONTRATO
  LEFT JOIN DEMISSAO R ON A.COD_CONTRATO = R.COD_CONTRATO
  LEFT JOIN DEMISSAO_COMPL R1 ON A.COD_CONTRATO = R1.COD_CONTRATO
 WHERE (A.COD_TIPO = :TIPO OR :TIPO = 0)
   AND (A.COD_UNIDADE = :FILIAL OR :FILIAL = 0)
   AND (A.COD_REDE_LOCAL = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
   AND (A.SEXO = TO_CHAR(:SEXO) OR TO_CHAR(:SEXO) = '0')
   --AND (A.STATUS = TO_CHAR(:STATUS) OR TO_CHAR(:STATUS) = '0')
   /*AND (
        :STATUS = 'E'                          -- 'E' = ambos
     OR (:STATUS = 'A' AND TO_CHAR(A.STATUS) = '0')      -- apenas ativos
     OR (:STATUS = 'D' AND TO_CHAR(A.STATUS) = '1')      -- apenas demitidos
  )*/
--AND A.COD_CONTRATO = 398149
ORDER BY A.COD_UNIDADE
