/*=== V2. RELATÓRIO ANÁLISE QUANTITATIVA ORGANIZACIONAL ===*/


/*=== RELATÓRIO ANÁLISE QUANTITATIVA ORGANIZACIONAL (Y x Y-1) ===*/

WITH
PARAMS_BASE AS (
/*modo padrão com data direta*/
/* SELECT
    DATE '2025-12-31'                 AS DT_REF_ATUAL,      -- <<<<<< ALTERE SÓ AQUI
    ADD_MONTHS(DATE '2025-12-31',-12) AS DT_REF_ANT,
    '8, 282, 1629' AS COD_EMP,
    '8, 282, 1629' AS COD_ORGANOGRAMA
  FROM DUAL*/

/*modo PL/SQL com entrada de data*/
/*SELECT
  TO_DATE('&REFERENCIA','DD/MM/YYYY')                  AS DT_REF_ATUAL,
  ADD_MONTHS(TO_DATE('&REFERENCIA','DD/MM/YYYY'),-12)  AS DT_REF_ANT,
  '8, 282, 1629' AS COD_EMP,
  '8, 282, 1629' AS COD_ORGANOGRAMA
FROM DUAL*/

/*modo pra usar em outros SGBS ou pelo sistema da folha*/
SELECT
  :REFERENCIA                   AS DT_REF_ATUAL,
  ADD_MONTHS(:REFERENCIA,-12) AS DT_REF_ANT,
  '8, 282, 1629' AS COD_EMP,
  '8, 282, 1629' AS COD_ORGANOGRAMA
FROM DUAL


),

EMP_LIST AS (
  SELECT 8 AS COD_EMP,
         8 AS COD_ORGANOGRAMA 
  FROM DUAL
  UNION ALL 
  SELECT 282 AS COD_EMP,
         282 AS COD_ORGANOGRAMA
  FROM DUAL
  UNION ALL 
  SELECT 1629 AS COD_EMP,
         1629 AS COD_ORGANOGRAMA
  FROM DUAL
),

ANOS AS (
  SELECT
    EXTRACT(YEAR FROM DT_REF_ANT)   AS ANO_Y1,
    EXTRACT(YEAR FROM DT_REF_ATUAL) AS ANO_Y
  FROM PARAMS_BASE
),

PARAMS AS (
  SELECT 'Y-1' AS PERIODO,
         EXTRACT(YEAR FROM b.DT_REF_ANT) AS ANO,
         b.DT_REF_ANT AS DT_REF
    FROM PARAMS_BASE b
  UNION ALL
  SELECT 'Y' AS PERIODO,
         EXTRACT(YEAR FROM b.DT_REF_ATUAL) AS ANO,
         b.DT_REF_ATUAL AS DT_REF
    FROM PARAMS_BASE b
),

/* Chaves SEM acento (pra nunca mais dar “sumiu estagiário”) */
NIVEIS AS (
  SELECT 1 ORDEM,  'CONSELHO_ADM'   NIVEL_KEY, 'CONSELHO ADMINISTRACAO'  NIVEL_DESC FROM DUAL UNION ALL
  SELECT 2,        'CONSELHO_FISC'  ,          'CONSELHO FISCAL'                    FROM DUAL UNION ALL
  SELECT 3,        'DIR_ESTAT_VAR'  ,          'DIRETORIA ESTATUTÁRIA VAREJO'       FROM DUAL UNION ALL
  SELECT 4,        'DIR_ESTAT_FIN'  ,          'DIRETORIA ESTATUTÁRIA FINANCEIRA'   FROM DUAL UNION ALL
  SELECT 5,        'DIRETORIA_ADJ'  ,          'DIRETORIA ADJUNTA'                  FROM DUAL UNION ALL
  SELECT 6,        'GER_SUP'        ,          'GERÊNCIA/SUPERVISÃO'                FROM DUAL UNION ALL
  SELECT 7,        'ESPECIAL'       ,          'ESPECIALISTAS'                      FROM DUAL UNION ALL
  SELECT 8,        'ADMIN'          ,          'ADMINISTRATIVO'                     FROM DUAL UNION ALL
  SELECT 9,        'OPER'           ,          'OPERACIONAL'                        FROM DUAL UNION ALL
  SELECT 10,       'APRENDIZ'       ,          'APRENDIZ'                           FROM DUAL UNION ALL
  SELECT 11,       'ESTAGIARIO'     ,          'ESTAGIÁRIO'                         FROM DUAL
),

/* ========= Base contratos (para os 2 anos) ========= */
CONTRATOS AS (
  SELECT DISTINCT
         p.PERIODO,
         p.ANO,
         ct.COD_CONTRATO,
         ct.SEXO,
         fn.DES_FUNCAO
    FROM PARAMS p
    JOIN V_DADOS_CONTRATO_AVT ct
      ON 1=1
    JOIN VH_EST_ORG_CONTRATO_AVT org
      ON org.COD_CONTRATO = ct.COD_CONTRATO
    JOIN VH_HIST_HORAS_COLAB_AVT hr
      ON hr.COD_CONTRATO = ct.COD_CONTRATO
    JOIN VH_CARGO_CONTRATO_AVT fn
      ON fn.COD_CONTRATO = ct.COD_CONTRATO
   WHERE ((p.DT_REF BETWEEN ct.DATA_ADMISSAO AND ct.DATA_DEMISSAO)
       OR (ct.DATA_ADMISSAO <= p.DT_REF AND ct.DATA_DEMISSAO IS NULL))
     AND p.DT_REF BETWEEN org.DATA_INI_ORG AND org.DATA_FIM_ORG
     AND p.DT_REF BETWEEN org.DATA_INICIO  AND org.DATA_FIM
     AND p.DT_REF BETWEEN hr.DATA_INI_HR   AND hr.DATA_FIM_HR
     AND p.DT_REF BETWEEN fn.DATA_INI_CLH  AND fn.DATA_FIM_CLH
     AND org.COD_EMP IN (SELECT COD_EMP FROM EMP_LIST)
     AND org.EDICAO_ORG_4 IS NOT NULL
),



BASE AS (
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    CASE
      WHEN UPPER(SEXO) LIKE 'F%' THEN 'F'
      WHEN UPPER(SEXO) LIKE 'M%' THEN 'M'
      ELSE 'N'
    END AS SEXO,
    UPPER(TRANSLATE(TRIM(DES_FUNCAO),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüç',
      'AAAAAEEEEIIIIOOOOOUUUUCaaaaaeeeeiiiiooooouuuuc')) AS DES_NORM
  FROM CONTRATOS
),

/* ========= Classificação (para os 2 anos) ========= */
CLASSIF AS (
  SELECT
    PERIODO,
    ANO,
    COD_CONTRATO,
    SEXO,
    CASE
      /* 1) Aprendiz / Estágio */
      WHEN DES_NORM LIKE '%APRENDIZ%'   THEN 'APRENDIZ'
      WHEN DES_NORM LIKE 'ESTAGIARIO%'  THEN 'ESTAGIARIO'

      /* 2) Conselho */
      WHEN DES_NORM LIKE 'CONSELHO ADMINISTRACAO%' THEN 'CONSELHO_ADM'
      WHEN DES_NORM LIKE 'CONSELHO FISCAL%' OR DES_NORM LIKE 'CONSELHEIRO FISCAL%' THEN 'CONSELHO_FISC'
      WHEN DES_NORM LIKE 'CONSELHO%' OR DES_NORM LIKE 'CONSELHEIRO%' THEN 'CONSELHO_ADM'

      /* 3) Diretoria estatutária varejo*/
      WHEN COD_CONTRATO IN (299685, 375780, 386492) THEN 'DIR_ESTAT_VAR'
        
     /* 4) Diretoria estatutária financeira*/
      WHEN COD_CONTRATO IN (377540, 379244, 386731) THEN 'DIR_ESTAT_FIN'

      /* 5) Diretoria */
      WHEN DES_NORM LIKE 'DIRETOR%' AND COD_CONTRATO NOT IN (299685, 375780, 386492, 377540, 379244, 386731) THEN 'DIRETORIA_ADJ'

      /* 6) Gerência/Supervisão */
      WHEN (DES_NORM LIKE 'GERENTE%' OR DES_NORM LIKE 'SUPERVISOR%' OR
            DES_NORM LIKE 'COMPRADOR%' OR DES_NORM LIKE 'ENCARREGAD%') THEN 'GER_SUP'

      /* 7) Especialistas */
      WHEN (DES_NORM LIKE 'ANALISTA%' OR DES_NORM LIKE 'PROGRAMADOR%' OR
            DES_NORM LIKE 'DESENVOLVEDOR%' OR DES_NORM LIKE 'AUDITOR%' OR
            DES_NORM LIKE 'INSTRUTOR%' OR DES_NORM LIKE 'TECNIC%' OR DES_NORM LIKE 'ENFERMAGEM%' OR
            DES_NORM LIKE 'COORDENADOR%' OR DES_NORM LIKE 'ESPECIALISTA%' OR
            DES_NORM LIKE 'LIDER TECH%' OR DES_NORM LIKE 'CHEFE%' OR
            DES_NORM LIKE 'CONTROLLER%' OR DES_NORM LIKE 'MEDICO%') THEN 'ESPECIAL'

      /* 8) Administrativo (override assessor) */
      WHEN DES_NORM LIKE 'ASSESSOR%' THEN 'ADMIN'
      WHEN (DES_NORM LIKE '%ADMINISTRAT%' OR DES_NORM LIKE '%ESCRITORIO%' OR DES_NORM LIKE '%PESSOAL%' OR
            DES_NORM LIKE '%CONTABIL%' OR DES_NORM LIKE '%FINANCEIR%' OR DES_NORM LIKE '%CREDITO%' OR
            DES_NORM LIKE '%COBRANCA%' OR DES_NORM LIKE '%JURIDIC%' OR DES_NORM LIKE '%MARKETING%' OR
            DES_NORM LIKE '%E-COMMERCE%' OR DES_NORM LIKE '%COMUNICACAO%' OR
            DES_NORM LIKE '%SERVICE DESK%' OR DES_NORM LIKE '%INFRAESTRUTUR%' OR
            DES_NORM LIKE 'ARQUIVISTA%' OR DES_NORM LIKE 'DIGITADOR%' OR
            DES_NORM LIKE 'TELEFONISTA%' OR DES_NORM LIKE 'PREPARADOR DE DADOS%' OR
            DES_NORM LIKE 'AGENTE ADMINISTRATIVO%') THEN 'ADMIN'
      WHEN (DES_NORM LIKE 'AUXILIAR DE ESCRITORIO%' OR DES_NORM LIKE 'AUXILIAR DE PESSOAL%' OR
            DES_NORM LIKE 'AUXILIAR DE CONTABILIDADE%' OR DES_NORM LIKE 'AUXILIAR DE COMPRAS%' OR
            DES_NORM LIKE 'ASSISTENTE ADMINISTRATIVO%' OR DES_NORM LIKE 'ASSISTENTE CONTABIL%' OR DES_NORM LIKE 'ASSISTENTE DE MARKETING%' OR
            DES_NORM LIKE 'ASSISTENTE FISCAL%' OR DES_NORM LIKE 'ASSISTENTE FINANCEIRO%') THEN 'ADMIN'

      /* 9) Operacional */
      WHEN (DES_NORM LIKE '%AUXILIAR%' OR DES_NORM LIKE '%LOJA%' OR DES_NORM LIKE 'VENDEDOR%' OR DES_NORM LIKE 'VEND.%' OR
            DES_NORM LIKE 'CAIXA%' OR DES_NORM LIKE '%VENDAS%' OR DES_NORM LIKE '%DISTRIBUICAO%' OR
            DES_NORM LIKE '%ALMOXARIF%' OR DES_NORM LIKE '%SERVICOS GERAIS%' OR
            DES_NORM LIKE '%MANUTENCAO%' OR DES_NORM LIKE '%EMPILHADEIR%' OR
            DES_NORM LIKE '%OPERADOR%' OR DES_NORM LIKE '%ESTOQUE%' OR DES_NORM LIKE '%REPOSITOR%' OR DES_NORM LIKE '%NEGOCIO%' OR
            DES_NORM LIKE '%CONFERENTE%' OR DES_NORM LIKE '%EMPACOTAD%' OR
            DES_NORM LIKE '%SEGURANCA%' OR DES_NORM LIKE 'PORTEIRO%' OR
            DES_NORM LIKE 'SERVENTE%' OR DES_NORM LIKE 'CASEIRO%' OR
            DES_NORM LIKE 'JARDINEIRO%' OR DES_NORM LIKE 'GOVERNANTA%' OR
            DES_NORM LIKE '%ORIENTADOR DE VENDA%' OR DES_NORM LIKE '%EXTRACAO%' OR DES_NORM LIKE '%TRABALHADOR%') THEN 'OPER'

      ELSE 'OPER'
    END AS NIVEL_KEY
  FROM BASE
),

/* ========= BLOCO I (Y e Y-1) ========= */
AGG_I AS (
  SELECT
    PERIODO, ANO, NIVEL_KEY,
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN SEXO='F' THEN 1 ELSE 0 END) AS FEM_QTDE,
    SUM(CASE WHEN SEXO='M' THEN 1 ELSE 0 END) AS MASC_QTDE
  FROM CLASSIF
  GROUP BY PERIODO, ANO, NIVEL_KEY
),

GRID_I AS (
  SELECT
    p.PERIODO, p.ANO,
    n.ORDEM, n.NIVEL_KEY, n.NIVEL_DESC,
    NVL(a.FEM_QTDE,0) AS FEM_QTDE,
    ROUND(100*NVL(a.FEM_QTDE,0)/NULLIF(NVL(a.TOTAL,0),0),0) AS FEM_PCT,
    NVL(a.MASC_QTDE,0) AS MASC_QTDE,
    ROUND(100*NVL(a.MASC_QTDE,0)/NULLIF(NVL(a.TOTAL,0),0),0) AS MASC_PCT,
    NVL(a.TOTAL,0) AS TOTAL
  FROM PARAMS p
  CROSS JOIN NIVEIS n
  LEFT JOIN AGG_I a
    ON a.PERIODO=p.PERIODO AND a.ANO=p.ANO AND a.NIVEL_KEY=n.NIVEL_KEY
),

TOTAIS_I AS (
  SELECT
    PERIODO, ANO,
    SUM(FEM_QTDE) AS TOT_FEM_QTDE,
    ROUND(100*SUM(FEM_QTDE)/NULLIF(SUM(TOTAL),0),0) AS TOT_FEM_PCT,
    SUM(MASC_QTDE) AS TOT_MASC_QTDE,
    ROUND(100*SUM(MASC_QTDE)/NULLIF(SUM(TOTAL),0),0) AS TOT_MASC_PCT,
    SUM(TOTAL) AS TOT_GERAL_QTDE,
    /* >>> aqui NÃO é fixo: valida se F+M fecha com TOTAL <<< */
    ROUND(100*(SUM(FEM_QTDE)+SUM(MASC_QTDE))/NULLIF(SUM(TOTAL),0),0) AS TOT_GERAL_PCT
  FROM GRID_I
  WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'   -- <<<<<<<<<< AQUI (não soma financeira no total geral)
  GROUP BY PERIODO, ANO
),

/* ========= BLOCO II (3 grupos) para Y e Y-1 ========= */
BLOCO2_BASE AS (
  SELECT * FROM GRID_I
   WHERE NIVEL_KEY IN ('CONSELHO_ADM','CONSELHO_FISC','DIR_ESTAT_VAR', 'DIR_ESTAT_FIN')
),

BLOCO2_TOTAIS AS (
  SELECT
    PERIODO, ANO,
    SUM(FEM_QTDE) AS B2_TOT_FEM_QTDE,
    ROUND(100*SUM(FEM_QTDE)/NULLIF(SUM(TOTAL),0),0) AS B2_TOT_FEM_PCT,
    SUM(MASC_QTDE) AS B2_TOT_MASC_QTDE,
    ROUND(100*SUM(MASC_QTDE)/NULLIF(SUM(TOTAL),0),0) AS B2_TOT_MASC_PCT,
    SUM(TOTAL) AS B2_TOT_GERAL_QTDE,
    /* >>> aqui também não é fixo <<< */
    ROUND(100*(SUM(FEM_QTDE)+SUM(MASC_QTDE))/NULLIF(SUM(TOTAL),0),0) AS B2_TOT_GERAL_PCT
  FROM BLOCO2_BASE
  WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
  GROUP BY PERIODO, ANO
),

BLOCO2_LINHAS AS (
  SELECT PERIODO, ANO, 1 AS B2_TARGET_ORDEM,
         NIVEL_DESC AS B2_NIVEL,
         FEM_QTDE AS B2_FEM_QTDE, FEM_PCT AS B2_FEM_PCT,
         MASC_QTDE AS B2_MASC_QTDE, MASC_PCT AS B2_MASC_PCT,
         TOTAL AS B2_TOTAL
    FROM BLOCO2_BASE WHERE NIVEL_KEY='CONSELHO_ADM'
  UNION ALL
  SELECT PERIODO, ANO, 2, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE WHERE NIVEL_KEY='CONSELHO_FISC'
  UNION ALL
  SELECT PERIODO, ANO, 3, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE WHERE NIVEL_KEY='DIR_ESTAT_VAR'
  UNION ALL
  SELECT PERIODO, ANO, 4, NIVEL_DESC, FEM_QTDE, FEM_PCT, MASC_QTDE, MASC_PCT, TOTAL
    FROM BLOCO2_BASE WHERE NIVEL_KEY='DIR_ESTAT_FIN'
),

/* ========= BLOCO III (Remuneração fixa) para Y e Y-1 ========= */
REMUN_FX_CONTRATO AS (
  SELECT
    p.PERIODO,
    p.ANO,
    a.COD_CONTRATO,
    SUM(a.VALOR_VD) AS REMUN_FIXA
  FROM PARAMS p
  CROSS JOIN EMP_LIST p1
  JOIN RHFP1003 b
    ON b.DATA_REFERENCIA = p.DT_REF
   AND b.COD_ORGANOGRAMA = p1.COD_ORGANOGRAMA
  JOIN RHFP1006 a
    ON a.COD_MESTRE_EVENTO = b.COD_MESTRE_EVENTO
  WHERE a.COD_VD = 1001
    AND b.COD_EVENTO = 1
  GROUP BY p.PERIODO, p.ANO, a.COD_CONTRATO
),

BLOCO3_BASE AS (
  SELECT
    cl.PERIODO,
    cl.ANO,
    cl.NIVEL_KEY,
    cl.SEXO,
    NVL(rf.REMUN_FIXA,0) AS REMUN_FIXA
  FROM CLASSIF cl
  LEFT JOIN REMUN_FX_CONTRATO rf
    ON rf.PERIODO = cl.PERIODO
   AND rf.ANO     = cl.ANO
   AND rf.COD_CONTRATO = cl.COD_CONTRATO
),

BLOCO3_AGG AS (
  SELECT
    PERIODO, ANO, NIVEL_KEY,
    SUM(CASE WHEN SEXO='F' THEN REMUN_FIXA ELSE 0 END) AS FEM_VAL,
    SUM(CASE WHEN SEXO='M' THEN REMUN_FIXA ELSE 0 END) AS MASC_VAL,
    SUM(REMUN_FIXA) AS TOTAL_VAL
  FROM BLOCO3_BASE
  GROUP BY PERIODO, ANO, NIVEL_KEY
),

BLOCO3_GRID AS (
  SELECT
    PERIODO, ANO, NIVEL_KEY,
    ROUND(100*FEM_VAL / NULLIF(TOTAL_VAL,0), 2)  AS B3_FEM_PCT,
    ROUND(100*MASC_VAL/ NULLIF(TOTAL_VAL,0), 2)  AS B3_MASC_PCT
  FROM BLOCO3_AGG
),

BLOCO3_TOTAIS AS (
  SELECT
    PERIODO, ANO,
    SUM(FEM_VAL) AS B3_TOT_FEM_VAL,
    SUM(MASC_VAL) AS B3_TOT_MASC_VAL,
    SUM(TOTAL_VAL) AS B3_TOT_GERAL_VAL
  FROM BLOCO3_AGG
  WHERE NIVEL_KEY <> 'DIR_ESTAT_FIN'
  GROUP BY PERIODO, ANO
)

/* ========= SELECT FINAL (Y-1 e Y lado a lado) ========= */
SELECT
  '8, 282, 1629' AS "Cód. Empresa",
  '008 - Grazziotin S/A | 282 - Grazziotin Financeira S/A | 1629 - Floresta Grazziotin LTDA' as "Empresas Relacionadas",
  /* Identificação do ano anterior */
  a.ANO_Y1 AS "Ano Anterior",

  /* =========================
     ANO ANTERIOR (Y-1)
     ========================= */

  /* BLOCO I (Ano Anterior) */
    /* Chave principal */
  n.NIVEL_DESC AS "Ant. | I - Nível de Cargo",
  g1.FEM_QTDE  AS "Ano Ant. | I - Fem (Qtd)",
  g1.FEM_PCT   AS "Ano Ant. | I - Fem (%)",
  g1.MASC_QTDE AS "Ano Ant. | I - Masc (Qtd)",
  g1.MASC_PCT  AS "Ano Ant. | I - Masc (%)",
  g1.TOTAL     AS "Ano Ant. | I - Total",

  /* Totais Bloco I (Ano Anterior) */
  t1.BTOT_FEM_QTDE   AS "Ano Ant. | I - TOT Fem (Qtd)",
  t1.BTOT_FEM_PCT    AS "Ano Ant. | I - TOT Fem (%)",
  t1.BTOT_MASC_QTDE  AS "Ano Ant. | I - TOT Masc (Qtd)",
  t1.BTOT_MASC_PCT   AS "Ano Ant. | I - TOT Masc (%)",
  t1.BTOT_GERAL_QTDE AS "Ano Ant. | I - TOT G (Qtd)",
  t1.BTOT_GERAL_PCT  AS "Ano Ant. | I - TOT G (%)",

  /* BLOCO II (Ano Anterior) - só aparece nas 3 linhas alvo */
  b21.B2_NIVEL     AS "Ano Ant. | II - Nível",
  b21.B2_FEM_QTDE  AS "Ano Ant. | II - Fem (Qtd)",
  b21.B2_FEM_PCT   AS "Ano Ant. | II - Fem (%)",
  b21.B2_MASC_QTDE AS "Ano Ant. | II - Masc (Qtd)",
  b21.B2_MASC_PCT  AS "Ano Ant. | II - Masc (%)",
  b21.B2_TOTAL     AS "Ano Ant. | II - Total",

  /* Totais Bloco II (Ano Anterior) - só preenche onde Bloco II aparece */
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_FEM_QTDE  END AS "Ano Ant. | II - TOT Fem (Qtd)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_FEM_PCT   END AS "Ano Ant. | II - TOT Fem (%)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_MASC_QTDE END AS "Ano Ant. | II - TOT Masc (Qtd)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_MASC_PCT  END AS "Ano Ant. | II - TOT Masc (%)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_GERAL_QTDE END AS "Ano Ant. | II - TOT G (Qtd)",
  CASE WHEN b21.B2_NIVEL IS NOT NULL THEN bt1.B2_TOT_GERAL_PCT  END AS "Ano Ant. | II - TOT G (%)",

  /* BLOCO III (Ano Anterior) */
  n.NIVEL_DESC AS "Ant. | III - Nível de Cargo",
  b31.B3_FEM_PCT  AS "Ano Ant. | III - Rem. Fem (%)",
  b31.B3_MASC_PCT AS "Ano Ant. | III - Rem. Masc (%)",

  /* Totais Bloco III (Ano Anterior) */
  ROUND(100 * t31.B3_TOT_FEM_VAL  / NULLIF(t31.B3_TOT_GERAL_VAL,0), 2) AS "Ano Ant. | III - TOT Fem (%)",
  ROUND(100 * t31.B3_TOT_MASC_VAL / NULLIF(t31.B3_TOT_GERAL_VAL,0), 2) AS "Ano Ant. | III - TOT Masc (%)",
  ROUND(100 * (t31.B3_TOT_FEM_VAL + t31.B3_TOT_MASC_VAL) / NULLIF(t31.B3_TOT_GERAL_VAL,0), 2)
    AS "Ano Ant. | III - TOT G (%)",


  /* =========================
     ANO Atu. (Y)
     ========================= */
  /* Identificação do ano antual */
  a.ANO_Y  AS "Ano Atual",

  /* BLOCO I (Ano Atual) */
  n.NIVEL_DESC AS "Atu. | I - Nível de Cargo",
  gy.FEM_QTDE  AS "Ano Atu. | I - Fem (Qtd)",
  gy.FEM_PCT   AS "Ano Atu. | I - Fem (%)",
  gy.MASC_QTDE AS "Ano Atu. | I - Masc (Qtd)",
  gy.MASC_PCT  AS "Ano Atu. | I - Masc (%)",
  gy.TOTAL     AS "Ano Atu. | I - Total",

  /* Totais Bloco I (Ano Atual) */
  ty.BTOT_FEM_QTDE   AS "Ano Atu. | I - TOT Fem (Qtd)",
  ty.BTOT_FEM_PCT    AS "Ano Atu. | I - TOT Fem (%)",
  ty.BTOT_MASC_QTDE  AS "Ano Atu. | I - TOT Masc (Qtd)",
  ty.BTOT_MASC_PCT   AS "Ano Atu. | I - TOT Masc (%)",
  ty.BTOT_GERAL_QTDE AS "Ano Atu. | I - TOT G (Qtd)",
  ty.BTOT_GERAL_PCT  AS "Ano Atu. | I - TOT G (%)",

  /* BLOCO II (Ano Atual) */
  b2y.B2_NIVEL     AS "Ano Atu. | II - Nível",
  b2y.B2_FEM_QTDE  AS "Ano Atu. | II - Fem (Qtd)",
  b2y.B2_FEM_PCT   AS "Ano Atu. | II - Fem (%)",
  b2y.B2_MASC_QTDE AS "Ano Atu. | II - Masc (Qtd)",
  b2y.B2_MASC_PCT  AS "Ano Atu. | II - Masc (%)",
  b2y.B2_TOTAL     AS "Ano Atu. | II - Total",

  /* Totais Bloco II (Ano Atual) */
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_FEM_QTDE  END AS "Ano Atu. | II - TOT Fem (Qtd)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_FEM_PCT   END AS "Ano Atu. | II - TOT Fem (%)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_MASC_QTDE END AS "Ano Atu. | II - TOT Masc (Qtd)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_MASC_PCT  END AS "Ano Atu. | II - TOT Masc (%)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_GERAL_QTDE END AS "Ano Atu. | II - TOT G (Qtd)",
  CASE WHEN b2y.B2_NIVEL IS NOT NULL THEN bty.B2_TOT_GERAL_PCT  END AS "Ano Atu. | II - TOT G (%)",

  /* BLOCO III (Ano Atu.) */
  n.NIVEL_DESC AS "Atu.| III - Nível de Cargo",
  b3y.B3_FEM_PCT  AS "Ano Atu. | III - Rem. Fem (%)",
  b3y.B3_MASC_PCT AS "Ano Atu. | III - Rem. Masc (%)",

  /* Totais Bloco III (Ano Atual) */
  ROUND(100 * t3y.B3_TOT_FEM_VAL  / NULLIF(t3y.B3_TOT_GERAL_VAL,0), 2) AS "Ano Atu. | III - TOT Fem (%)",
  ROUND(100 * t3y.B3_TOT_MASC_VAL / NULLIF(t3y.B3_TOT_GERAL_VAL,0), 2) AS "Ano Atu. | III - TOT Masc (%)",
  ROUND(100 * (t3y.B3_TOT_FEM_VAL + t3y.B3_TOT_MASC_VAL) / NULLIF(t3y.B3_TOT_GERAL_VAL,0), 2)
    AS "Ano Atu. | III - TOT G (%)"

FROM NIVEIS n
CROSS JOIN PARAMS_BASE pb
CROSS JOIN ANOS a

LEFT JOIN GRID_I g1
  ON g1.NIVEL_KEY = n.NIVEL_KEY AND g1.PERIODO='Y-1'
LEFT JOIN GRID_I gy
  ON gy.NIVEL_KEY = n.NIVEL_KEY AND gy.PERIODO='Y'

LEFT JOIN (
  SELECT PERIODO,
         TOT_FEM_QTDE   AS BTOT_FEM_QTDE,
         TOT_FEM_PCT    AS BTOT_FEM_PCT,
         TOT_MASC_QTDE  AS BTOT_MASC_QTDE,
         TOT_MASC_PCT   AS BTOT_MASC_PCT,
         TOT_GERAL_QTDE AS BTOT_GERAL_QTDE,
         TOT_GERAL_PCT  AS BTOT_GERAL_PCT
    FROM TOTAIS_I
) t1
  ON t1.PERIODO='Y-1'
LEFT JOIN (
  SELECT PERIODO,
         TOT_FEM_QTDE   AS BTOT_FEM_QTDE,
         TOT_FEM_PCT    AS BTOT_FEM_PCT,
         TOT_MASC_QTDE  AS BTOT_MASC_QTDE,
         TOT_MASC_PCT   AS BTOT_MASC_PCT,
         TOT_GERAL_QTDE AS BTOT_GERAL_QTDE,
         TOT_GERAL_PCT  AS BTOT_GERAL_PCT
    FROM TOTAIS_I
) ty
  ON ty.PERIODO='Y'

LEFT JOIN BLOCO2_LINHAS b21
  ON b21.PERIODO='Y-1' AND b21.B2_TARGET_ORDEM = n.ORDEM
LEFT JOIN BLOCO2_LINHAS b2y
  ON b2y.PERIODO='Y' AND b2y.B2_TARGET_ORDEM = n.ORDEM

LEFT JOIN BLOCO2_TOTAIS bt1
  ON bt1.PERIODO='Y-1'
LEFT JOIN BLOCO2_TOTAIS bty
  ON bty.PERIODO='Y'

LEFT JOIN BLOCO3_GRID b31
  ON b31.PERIODO='Y-1' AND b31.NIVEL_KEY = n.NIVEL_KEY
LEFT JOIN BLOCO3_GRID b3y
  ON b3y.PERIODO='Y' AND b3y.NIVEL_KEY = n.NIVEL_KEY

LEFT JOIN BLOCO3_TOTAIS t31
  ON t31.PERIODO='Y-1'
LEFT JOIN BLOCO3_TOTAIS t3y
  ON t3y.PERIODO='Y'

ORDER BY n.ORDEM



