WITH
MESES AS (
    SELECT
        ADD_MONTHS(TRUNC(:DATA_INICIO, 'MM'), LEVEL - 1) AS DATA_MES,
        LAST_DAY(ADD_MONTHS(TRUNC(:DATA_INICIO, 'MM'), LEVEL - 1)) AS DATA_MES_FIM,
        TO_CHAR(ADD_MONTHS(TRUNC(:DATA_INICIO, 'MM'), LEVEL - 1), 'MM/YYYY') AS MES_ANO,
        TO_CHAR(ADD_MONTHS(TRUNC(:DATA_INICIO, 'MM'), LEVEL - 1),
                'fmMonth YYYY',
                'NLS_DATE_LANGUAGE=PORTUGUESE') AS MES_ANO_EXTENSO
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TRUNC(:DATA_FIM, 'MM'),
                                       TRUNC(:DATA_INICIO, 'MM')) + 1
)

SELECT A.COD_CONTRATO,
       A.DES_PESSOA,
       A.NRO_CONTA_PGTO AS CONTA,
       A.COD_AGE_PGTO AS AGENCIA,
       A.COD_BANCO,
       A.DES_BANCO,
       C.VALOR_VD,
       D.DATA_REFERENCIA
FROM V_DADOS_COLAB_AVT A
JOIN MESES M
  ON A.DATA_ADMISSAO <= M.DATA_MES_FIM
AND NVL(A.DATA_DEMISSAO, DATE '2999-12-31') >= M.DATA_MES
JOIN RHFP1006 C
  ON A.COD_CONTRATO = C.COD_CONTRATO
JOIN RHFP1003 D
  ON C.COD_MESTRE_EVENTO = D.COD_MESTRE_EVENTO
AND D.DATA_INI_MOV <= M.DATA_MES_FIM
AND NVL(D.DATA_FIM_MOV, DATE '2999-12-31') >= M.DATA_MES
WHERE C.COD_VD = 1003
AND D.COD_EVENTO = 1
AND A.COD_EMP = 8
AND C.VALOR_VD <> 0
--AND A.COD_CONTRATO = 389622
ORDER BY A.DES_PESSOA
