SELECT COD_CONTRATO,
       DES_PESSOA,
       DES_FUNCAO,
       DES_UNIDADE,
       DES_REDE_LOCAL,
       DATA_ADMISSAO,
       DATA_DEMISSAO,
       DES_DEMISSAO
FROM V_DADOS_COLAB_AVT
WHERE DES_FUNCAO LIKE '%GERENTE%'
AND DATA_DEMISSAO BETWEEN :DATA_INICIO AND :DATA_FIM
