/*
SQL OFICIAL E AJUSTADO DA CONTAGEM DE COLABORADORES = REPORT
GERAL DA EMPRESA
*/

WITH CTE_DADOS AS (
SELECT DISTINCT AFAST.STATUS,
                CTR.COD_CONTRATO,
                ORGCT.COD_ORGANOGRAMA,
                ORG.EDICAO_ORG AS COD_UNIDADE,
                ORG2.NOME_ORGANOGRAMA_B,
                CASE
                  WHEN ORG2.COD_TIPO = 1 THEN
                   'LOJAS'
                  WHEN ORG2.COD_TIPO = 2 OR
                       (ORG2.COD_NIVEL_ORG = 4) THEN
                   ORG2.NOME4
                  WHEN (ORG2.COD_TIPO = 3 OR ORG2.COD_NIVEL_ORG = 3) THEN
                   ORG2.NOME3
                  ELSE
                   NULL
                END AS DES_LOCAL,
                ORG2.COD_TIPO,
                ORG2.DES_TIPO,
                FUN2.NOME_CLH AS DES_FUNCAO,
                FUN.DATA_INICIO,
                FUN.DATA_FIM,
                AFAST.COD_AFAST,
                AFAST.DATA_INI_AFAST,
                AFAST.DATA_FIM_AFAST
  FROM RHFP0300 CTR
 INNER JOIN RHFP0310 ORGCT ON CTR.COD_CONTRATO = ORGCT.COD_CONTRATO
 INNER JOIN RHFP0340 FUN ON CTR.COD_CONTRATO = FUN.COD_CONTRATO
                        AND :DATA_REFERENCIA BETWEEN FUN.DATA_INICIO AND
                            FUN.DATA_FIM
 INNER JOIN RHFP0500 FUN2 ON FUN.COD_CLH = FUN2.COD_CLH
  LEFT JOIN VH_AFAST_CONTRATO_AVT AFAST ON CTR.COD_CONTRATO =
                                           AFAST.COD_CONTRATO
                                       AND :DATA_REFERENCIA BETWEEN
                                           AFAST.DATA_INI_AFAST AND
                                           AFAST.DATA_FIM_AFAST
  LEFT JOIN RHFP0401 ORG ON ORGCT.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
                        AND :DATA_REFERENCIA BETWEEN ORGCT.DATA_INICIO AND
                            ORGCT.DATA_FIM
  LEFT JOIN V_EST_ORG_ALTER_AVT ORG2 ON ORG.COD_ORGANOGRAMA =
                                        ORG2.COD_ORGANOGRAMA /*AND ORG2.STATUS_ORG = 0*/
                                        AND (:DATA_REFERENCIA BETWEEN ORG2.DATA_INICIO AND ORG2.DATA_FIM)
 WHERE ((:DATA_REFERENCIA BETWEEN CTR.DATA_INICIO AND CTR.DATA_FIM) OR
       (CTR.DATA_INICIO <= :DATA_REFERENCIA AND CTR.DATA_FIM IS NULL))
   AND ORG.COD_NIVEL2 = 8
   --AND FUN2.NOME_CLH LIKE '%SERVENTE%'
   --AND (AFAST.COD_AFAST IN (6,7) OR AFAST.COD_AFAST IS NULL)
   --AND AFAST.COD_AFAST NOT IN (6,7)
   --AND ORG2.COD_TIPO = 2
   --AND CTR.COD_CONTRATO IN (71838, 385858)


),
CTE_AGREGADA AS (
    SELECT DES_LOCAL,
           COD_TIPO,
           DES_TIPO,
           COUNT(DISTINCT COD_CONTRATO) AS QTD_CONTRATOS_GERAL,

           COUNT(DISTINCT CASE
                   WHEN DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                        DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                        DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                        (COD_AFAST IN (6,7) OR COD_AFAST IS NULL) THEN
                    COD_CONTRATO
                 END) AS QTD_COLABORADORES,

           COUNT(DISTINCT CASE
                   WHEN DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                        (COD_AFAST IN (6,7) OR COD_AFAST IS NULL) THEN
                    COD_CONTRATO
                 END) AS QTD_ESTAGIARIOS,

           COUNT(DISTINCT CASE
                   WHEN DES_FUNCAO LIKE '%APRENDIZ%' AND
                        (COD_AFAST IN (6,7) OR COD_AFAST IS NULL) THEN
                    COD_CONTRATO
                 END) AS QTD_APRENDIZ,

           COUNT(DISTINCT CASE
                   WHEN DES_FUNCAO LIKE '%SERVENTE%' AND
                        (COD_AFAST IN (6,7) OR COD_AFAST IS NULL) THEN
                    COD_CONTRATO
                 END) AS QTD_SERVENTES,

           COUNT(DISTINCT CASE
                   WHEN COD_AFAST NOT IN (6,7) THEN
                    COD_CONTRATO
                 END) AS QTD_AFASTADOS

      FROM CTE_DADOS
     GROUP BY DES_LOCAL, COD_TIPO, DES_TIPO
)
SELECT A.*,

       SUM(A.QTD_CONTRATOS_GERAL) OVER() AS QTD_TOTAL_CONTRATOS,

       CASE
         WHEN A.DES_TIPO = 'LOJA' THEN
          QTD_COLABORADORES
         ELSE
          0
       END AS QTD_TOTAL_COLAB_LOJAS,

       SUM(CASE
             WHEN A.COD_TIPO IN (2, 3) THEN
              A.QTD_COLABORADORES
             ELSE
              0
           END) OVER() AS QTD_TOTAL_COLAB_ADM,

       SUM(A.QTD_ESTAGIARIOS) OVER() AS QTD_TOTAL_ESTAGIARIOS,
       SUM(A.QTD_APRENDIZ) OVER() AS QTD_TOTAL_APRENDIZES,
       SUM(A.QTD_SERVENTES) OVER() AS QTD_TOTAL_SERVENTES,
       SUM(A.QTD_AFASTADOS) OVER() AS QTD_TOTAL_AFASTADOS

  FROM CTE_AGREGADA A
 ORDER BY A.DES_TIPO ASC;
