WITH
CONTRATOS AS (
  SELECT DISTINCT CT.STATUS,
                  CT.COD_CONTRATO,
                  CT.DES_PESSOA,
                  CT.DATA_ADMISSAO,
                  CT.DATA_DEMISSAO,
                  FN.COD_FUNCAO,
                  FN.DES_FUNCAO,
                  HR.HR_BASE_MES,
                  CT.IND_DEFICIENCIA,
                  CT.SEXO,
                  ORG.COD_EMP,
                  ORG.EDICAO_EMP,
                  ORG.DES_EMP,
                  ORG.COD_UNIDADE,
                  ORG.DES_UNIDADE,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_3
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME3
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_4
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_DIVISAO,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME4
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_DIVISAO,
                  ORG.COD_REDE,
                  ORG.DES_REDE,
                  ORG.COD_TIPO,
                  ORG.DES_TIPO
    FROM V_DADOS_CONTRATO_AVT CT,
         VH_EST_ORG_CONTRATO_AVT ORG,
         VH_HIST_HORAS_COLAB_AVT HR,
         VH_CARGO_CONTRATO_AVT FN
   WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
     AND CT.COD_CONTRATO = HR.COD_CONTRATO
     AND CT.COD_CONTRATO = FN.COD_CONTRATO
     AND ((:DATA_REFERENCIA BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
          (CT.DATA_ADMISSAO <= :DATA_REFERENCIA AND CT.DATA_DEMISSAO IS NULL))
     AND :DATA_REFERENCIA BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
     AND :DATA_REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
     AND :DATA_REFERENCIA BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
     AND ORG.COD_EMP = 4
     AND ORG.EDICAO_ORG_4 IS NOT NULL
   ORDER BY CT.COD_CONTRATO
),

STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND ((:DATA_REFERENCIA BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= :DATA_REFERENCIA AND CT.DATA_FIM IS NULL))
   AND :DATA_REFERENCIA BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_REFERENCIA BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND :DATA_REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   AND ORG.COD_EMP = 4
   --AND ORG.COD_TIPO = 1
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608) --657 essa ainda irá inaugurar em agosto
),

/***************************************************/

-- 1. ADM SETORES SEPARADOS
RESULTADO_FINAL_ADM AS (
  SELECT A.COD_DIVISAO AS COD_LOCAL,
         A.DES_DIVISAO AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,

         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   --WHERE A.COD_TIPO = 2
   GROUP BY A.COD_DIVISAO, A.DES_DIVISAO
),


-- 7. TOTAL DA COMPANHIA
RESULTADO_FINAL_EMP AS (
  SELECT A.EDICAO_EMP AS COD_LOCAL,
         A.DES_EMP AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,

         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   WHERE A.COD_EMP = 4
   GROUP BY A.EDICAO_EMP, A.DES_EMP
),

-- 8. NUMERAÇÃO DAS LINHAS PARA UNIÃO POR POSIÇÃO
ADM_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, A.*
  FROM RESULTADO_FINAL_ADM A
),

EMP_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, G.*
  FROM RESULTADO_FINAL_EMP G
)


-- 8. UNIR LADO A LADO
SELECT
  'ADMINISTRAÇÃO' AS DES_ADM,
  CASE
      WHEN ADM.COD_LOCAL IS NOT NULL AND ADM.DES_LOCAL IS NOT NULL THEN ADM.DES_LOCAL
      WHEN ADM.COD_LOCAL IS NOT NULL THEN TO_CHAR(ADM.COD_LOCAL)
      WHEN ADM.COD_LOCAL IS NOT NULL THEN ADM.DES_LOCAL
      ELSE NULL
  END AS ADM_LOCAL,
  ADM.QTD_COLABS AS ADM_COLABS,
  ADM.QTD_ESTAG AS ADM_ESTAG,
  ADM.QTD_APRE  AS ADM_APRE,
  ADM.QTD_SERV  AS ADM_SERV,
  ADM.QTD_AFAST AS ADM_AFAST,
  ADM.QTD_COLAB_FEM AS ADM_FEM,
  ADM.PERC_FEM AS ADM_PERC_FEM,
  ADM.QTD_COLAB_MASC AS ADM_MASC,
  ADM.PERC_MASC AS ADM_PERC_MASC,
  ADM.TOT_COLAB AS ADM_TOTAL,

  'EMPRESA' AS DES_EMP,
  CASE
      WHEN EMP.COD_LOCAL IS NOT NULL AND EMP.DES_LOCAL IS NOT NULL THEN TO_CHAR(EMP.COD_LOCAL) || ' - ' || EMP.DES_LOCAL
      WHEN EMP.COD_LOCAL IS NOT NULL THEN TO_CHAR(EMP.COD_LOCAL)
      WHEN EMP.DES_LOCAL IS NOT NULL THEN EMP.DES_LOCAL
      ELSE NULL
  END AS EMP_LOCAL,

  EMP.QTD_COLABS AS EMP_COLABS,
  EMP.QTD_ESTAG AS EMP_ESTAG,
  EMP.QTD_APRE  AS EMP_APRE,
  EMP.QTD_SERV  AS EMP_SERV,
  EMP.QTD_AFAST AS EMP_AFAST,
  EMP.QTD_COLAB_FEM AS EMP_FEM,
  EMP.PERC_FEM AS EMP_PERC_FEM,
  EMP.QTD_COLAB_MASC AS EMP_MASC,
  EMP.PERC_MASC AS EMP_PERC_MASC,
  EMP.TOT_COLAB AS EMP_TOTAL,

  :DATA_REFERENCIA AS REFERENCIA

FROM ADM_NUM ADM
FULL OUTER JOIN EMP_NUM EMP ON ADM.RN = EMP.RN
ORDER BY COALESCE(ADM.RN, EMP.RN)
