WITH
CONTRATOS AS (
  SELECT DISTINCT CT.STATUS,
                  CT.COD_CONTRATO,
                  CT.DES_PESSOA,
                  CT.DATA_ADMISSAO,
                  CT.DATA_DEMISSAO,
                  FN.COD_FUNCAO,
                  FN.DES_FUNCAO,
                  HR.HR_BASE_MES,
                  CT.IND_DEFICIENCIA,
                  CT.SEXO,
                  ORG.COD_EMP,
                  ORG.EDICAO_EMP,
                  ORG.DES_EMP,
                  ORG.COD_UNIDADE,
                  ORG.DES_UNIDADE,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_3
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME3
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_4
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_DIVISAO,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME4
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_DIVISAO,
                  ORG.COD_REDE,
                  ORG.DES_REDE,
                  ORG.COD_TIPO,
                  ORG.DES_TIPO
    FROM V_DADOS_CONTRATO_AVT CT,
         VH_EST_ORG_CONTRATO_AVT ORG,
         VH_HIST_HORAS_COLAB_AVT HR,
         VH_CARGO_CONTRATO_AVT FN
   WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
     AND CT.COD_CONTRATO = HR.COD_CONTRATO
     AND CT.COD_CONTRATO = FN.COD_CONTRATO
     AND ((:DATA_REFERENCIA BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
          (CT.DATA_ADMISSAO <= :DATA_REFERENCIA AND CT.DATA_DEMISSAO IS NULL))
     AND :DATA_REFERENCIA BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
     AND :DATA_REFERENCIA BETWEEN ORG.DATA_INICIO AND ORG.DATA_FIM
     AND :DATA_REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
     AND :DATA_REFERENCIA BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
     AND ORG.COD_EMP = 8
     AND ORG.EDICAO_ORG_4 IS NOT NULL
   ORDER BY CT.COD_CONTRATO
),

STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND ((:DATA_REFERENCIA BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= :DATA_REFERENCIA AND CT.DATA_FIM IS NULL))
   AND :DATA_REFERENCIA BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_REFERENCIA BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND :DATA_REFERENCIA BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   AND ORG.COD_EMP = 8
   --AND ORG.COD_TIPO = 1
   --AND ORG.COD_UNIDADE NOT IN (014, 050, 615, 657, 7586, 7608) --657 essa ainda irá inaugurar em agosto
),


--- SOMENTE PARA RETORNAR A ADM E O CD
RESULTADO_FINAL_ADM_CD AS (
  SELECT A.COD_REDE AS COD_LOCAL,
         A.DES_REDE AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,
         
         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   WHERE A.COD_TIPO IN (2,3)
   GROUP BY A.COD_REDE, A.DES_REDE

),

/***************************************************/

-- 1. ADM SETORES SEPARADOS
RESULTADO_FINAL_ADM AS (
  SELECT A.COD_DIVISAO AS COD_LOCAL,
         A.DES_DIVISAO AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,
         
         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   WHERE A.COD_TIPO = 2
   GROUP BY A.COD_DIVISAO, A.DES_DIVISAO
),

--2. TOTAL DA ADM
RESULTADO_FINAL_ADM_TOT AS (
  SELECT A.COD_REDE AS COD_LOCAL,
         A.DES_REDE AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,
         
         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   WHERE A.COD_TIPO = 2
   GROUP BY A.COD_REDE, A.DES_REDE
),

--3. TOTAL DO CD
RESULTADO_FINAL_CD AS (
  SELECT A.COD_REDE AS COD_LOCAL,
         A.DES_REDE AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,
         
         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   WHERE A.COD_TIPO = 3
   GROUP BY A.COD_REDE, A.DES_REDE
),

-- 4. ADM + CD
ADM_CD_AGREGADO AS (
  SELECT
    '001/013' AS COD_LOCAL,
    'ADMINISTRAÇÃO/LOGÍSTICA' AS DES_LOCAL,
    SUM(QTD_COLABS) AS QTD_COLABS,
    SUM(QTD_ESTAG) AS QTD_ESTAG,
    SUM(QTD_APRE)  AS QTD_APRE,
    SUM(QTD_SERV)  AS QTD_SERV,
    SUM(QTD_AFAST) AS QTD_AFAST,
    SUM(QTD_COLAB_FEM) AS QTD_COLAB_FEM,
    ROUND(SUM(QTD_COLAB_FEM) * 100.0 / NULLIF(SUM(TOT_COLAB), 0), 2) AS PERC_FEM,
    SUM(QTD_COLAB_MASC) AS QTD_COLAB_MASC,
    ROUND(SUM(QTD_COLAB_MASC) * 100.0 / NULLIF(SUM(TOT_COLAB), 0), 2) AS PERC_MASC,
    SUM(TOT_COLAB) AS TOT_COLAB
  FROM RESULTADO_FINAL_ADM_CD
  WHERE COD_LOCAL IN ('001', '013')
),


-- 5. REDES SEPARADAS
RESULTADO_FINAL_REDES AS (
  SELECT A.COD_REDE AS COD_LOCAL,
         A.DES_REDE AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,
         
         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   WHERE A.COD_TIPO = 1
   GROUP BY A.COD_REDE, A.DES_REDE
),

-- 6. TOTAL LOJAS
RESULTADO_FINAL_LOJAS AS (
  SELECT A.COD_TIPO AS COD_LOCAL,
         A.DES_TIPO AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,
         
         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   WHERE A.COD_TIPO = 1
   GROUP BY A.COD_TIPO, A.DES_TIPO
),


-- 7. TOTAL DA COMPANHIA
RESULTADO_FINAL_EMP AS (
  SELECT A.EDICAO_EMP AS COD_LOCAL,
         A.DES_EMP AS DES_LOCAL,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%' AND
                      A.DES_FUNCAO NOT LIKE '%SERVENTE%' AND
                      A.DES_FUNCAO NOT LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_COLABS,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%ESTAGIARIO%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_ESTAG,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_APRE,
         COUNT(DISTINCT CASE
                 WHEN A.DES_FUNCAO LIKE '%SERVENTE%' AND
                      S.STATUS_AFAST IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_SERV,
         COUNT(DISTINCT CASE
                 WHEN S.STATUS_AFAST NOT IN (0, 6, 7, 107) THEN
                  A.COD_CONTRATO
               END) AS QTD_AFAST,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
         ROUND((COUNT(CASE WHEN A.SEXO = 'F' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
         COUNT(DISTINCT CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
         ROUND((COUNT(CASE WHEN A.SEXO = 'M' /*AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'*/ THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,
         
         COUNT(DISTINCT A.COD_CONTRATO) AS TOT_COLAB
    FROM CONTRATOS A
    LEFT JOIN STATUS_AFASTADOS S ON A.COD_CONTRATO = S.COD_CONTRATO
   WHERE A.COD_EMP = 8
   GROUP BY A.EDICAO_EMP, A.DES_EMP
),

-- 8. NUMERAÇÃO DAS LINHAS PARA UNIÃO POR POSIÇÃO
ADM_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, A.*
  FROM RESULTADO_FINAL_ADM A
),

CD_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, B.*
  FROM RESULTADO_FINAL_CD B
),

ADM_TOT_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, C.*
  FROM RESULTADO_FINAL_ADM_TOT C
),

ADM_CD_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, D.*
  FROM ADM_CD_AGREGADO D
),

REDES_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, E.*
  FROM RESULTADO_FINAL_REDES E
),

TOT_LOJAS_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, F.*
  FROM RESULTADO_FINAL_LOJAS F
),

EMP_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY COD_LOCAL) AS RN, G.*
  FROM RESULTADO_FINAL_EMP G
)


-- 8. UNIR LADO A LADO
SELECT
  'ADMINISTRAÇÃO' AS DES_ADM,
  CASE
      WHEN ADM.COD_LOCAL IS NOT NULL AND ADM.DES_LOCAL IS NOT NULL THEN TO_CHAR(ADM.COD_LOCAL) || ' - ' || ADM.DES_LOCAL
      WHEN ADM.COD_LOCAL IS NOT NULL THEN TO_CHAR(ADM.COD_LOCAL)
      WHEN ADM.COD_LOCAL IS NOT NULL THEN ADM.DES_LOCAL
      ELSE NULL
  END AS ADM_LOCAL,
  ADM.QTD_COLABS AS ADM_COLABS,
  ADM.QTD_ESTAG AS ADM_ESTAG,
  ADM.QTD_APRE  AS ADM_APRE,
  ADM.QTD_SERV  AS ADM_SERV,
  ADM.QTD_AFAST AS ADM_AFAST,
  ADM.QTD_COLAB_FEM AS ADM_FEM,
  ADM.PERC_FEM AS ADM_PERC_FEM,
  ADM.QTD_COLAB_MASC AS ADM_MASC,
  ADM.PERC_MASC AS ADM_PERC_MASC,
  ADM.TOT_COLAB AS ADM_TOTAL,

  'LOGÍSTICA' AS DES_CD,
  CASE
      WHEN CD.COD_LOCAL IS NOT NULL AND CD.DES_LOCAL IS NOT NULL THEN TO_CHAR(CD.COD_LOCAL) || ' - ' || CD.DES_LOCAL
      WHEN CD.COD_LOCAL IS NOT NULL THEN TO_CHAR(CD.COD_LOCAL)
      WHEN CD.COD_LOCAL IS NOT NULL THEN CD.DES_LOCAL
      ELSE NULL
  END AS CD_LOCAL,
  CD.QTD_COLABS AS CD_COLABS,
  CD.QTD_ESTAG AS CD_ESTAG,
  CD.QTD_APRE  AS CD_APRE,
  CD.QTD_SERV  AS CD_SERV,
  CD.QTD_AFAST AS CD_AFAST,
  CD.QTD_COLAB_FEM AS CD_FEM,
  CD.PERC_FEM AS CD_PERC_FEM,
  CD.QTD_COLAB_MASC AS CD_MASC,
  CD.PERC_MASC AS CD_PERC_MASC,
  CD.TOT_COLAB AS CD_TOTAL,

  'ADMINISTRAÇÃO TOTAL' AS DES_ADM_TOT,
  CASE
      WHEN ATT.COD_LOCAL IS NOT NULL AND ATT.DES_LOCAL IS NOT NULL THEN TO_CHAR(ATT.COD_LOCAL) || ' - ' || ATT.DES_LOCAL
      WHEN ATT.COD_LOCAL IS NOT NULL THEN TO_CHAR(ATT.COD_LOCAL)
      WHEN ATT.COD_LOCAL IS NOT NULL THEN ATT.DES_LOCAL
      ELSE NULL
  END AS ADM_TOT_LOCAL,
  ATT.QTD_COLABS AS ADM_TOT_COLABS,
  ATT.QTD_ESTAG AS ADM_TOT_ESTAG,
  ATT.QTD_APRE  AS ADM_TOT_APRE,
  ATT.QTD_SERV  AS ADM_TOT_SERV,
  ATT.QTD_AFAST AS ADM_TOT_AFAST,
  ATT.QTD_COLAB_FEM AS ADM_TOT_FEM,
  ATT.PERC_FEM AS ADM_TOT_PERC_FEM,
  ATT.QTD_COLAB_MASC AS ADM_TOT_MASC,
  ATT.PERC_MASC AS ADM_TOT_PERC_MASC,
  ATT.TOT_COLAB AS ADM_TOT_TOTAL,

  'ADMINISTRAÇÃO/LOGÍSTICA' AS DES_ADM_CD,
  CASE
      WHEN AC.COD_LOCAL IS NOT NULL AND AC.DES_LOCAL IS NOT NULL THEN TO_CHAR(AC.COD_LOCAL) || ' - ' || AC.DES_LOCAL
      WHEN AC.COD_LOCAL IS NOT NULL THEN TO_CHAR(AC.COD_LOCAL)
      WHEN AC.COD_LOCAL IS NOT NULL THEN AC.DES_LOCAL
      ELSE NULL
  END AS ADM_CD_LOCAL,
  AC.QTD_COLABS AS ADM_CD_COLABS,
  AC.QTD_ESTAG AS ADM_CD_ESTAG,
  AC.QTD_APRE  AS ADM_CD_APRE,
  AC.QTD_SERV  AS ADM_CD_SERV,
  AC.QTD_AFAST AS ADM_CD_AFAST,
  AC.QTD_COLAB_FEM AS ADM_CD_FEM,
  AC.PERC_FEM AS ADM_CD_PERC_FEM,
  AC.QTD_COLAB_MASC AS ADM_CD_MASC,
  AC.PERC_MASC AS ADM_CD_PERC_MASC,
  AC.TOT_COLAB AS ADM_CD_TOTAL,

  'REDES' AS DES_REDE,
  CASE
      WHEN REDE.COD_LOCAL IS NOT NULL AND REDE.DES_LOCAL IS NOT NULL THEN TO_CHAR(REDE.COD_LOCAL) || ' - ' || REDE.DES_LOCAL
      WHEN REDE.COD_LOCAL IS NOT NULL THEN TO_CHAR(REDE.COD_LOCAL)
      WHEN REDE.COD_LOCAL IS NOT NULL THEN REDE.DES_LOCAL
      ELSE NULL
  END AS REDE_LOCAL,
  REDE.QTD_COLABS AS REDE_COLABS,
  REDE.QTD_ESTAG AS REDE_ESTAG,
  REDE.QTD_APRE  AS REDE_APRE,
  REDE.QTD_SERV  AS REDE_SERV,
  REDE.QTD_AFAST AS REDE_AFAST,
  REDE.QTD_COLAB_FEM AS REDE_FEM,
  REDE.PERC_FEM AS REDE_PERC_FEM,
  REDE.QTD_COLAB_MASC AS REDE_MASC,
  REDE.PERC_MASC AS REDE_PERC_MASC,
  REDE.TOT_COLAB AS REDE_TOTAL,

  'LOJAS' AS DES_LOJAS,
  CASE
      WHEN LOJAS.COD_LOCAL IS NOT NULL AND LOJAS.DES_LOCAL IS NOT NULL THEN TO_CHAR(LOJAS.COD_LOCAL) || ' - ' || LOJAS.DES_LOCAL
      WHEN LOJAS.COD_LOCAL IS NOT NULL THEN TO_CHAR(LOJAS.COD_LOCAL)
      WHEN LOJAS.COD_LOCAL IS NOT NULL THEN LOJAS.DES_LOCAL
      ELSE NULL
  END AS LOJAS_LOCAL,
  LOJAS.QTD_COLABS AS LOJAS_COLABS,
  LOJAS.QTD_ESTAG AS LOJAS_ESTAG,
  LOJAS.QTD_APRE  AS LOJAS_APRE,
  LOJAS.QTD_SERV  AS LOJAS_SERV,
  LOJAS.QTD_AFAST AS LOJAS_AFAST,
  LOJAS.QTD_COLAB_FEM AS LOJAS_FEM,
  LOJAS.PERC_FEM AS LOJAS_PERC_FEM,
  LOJAS.QTD_COLAB_MASC AS LOJAS_MASC,
  LOJAS.PERC_MASC AS LOJAS_PERC_MASC,
  LOJAS.TOT_COLAB AS LOJAS_TOTAL,

  'EMPRESA' AS DES_EMP,
  CASE
      WHEN EMP.COD_LOCAL IS NOT NULL AND EMP.DES_LOCAL IS NOT NULL THEN TO_CHAR(EMP.COD_LOCAL) || ' - ' || EMP.DES_LOCAL
      WHEN EMP.COD_LOCAL IS NOT NULL THEN TO_CHAR(EMP.COD_LOCAL)
      WHEN EMP.DES_LOCAL IS NOT NULL THEN EMP.DES_LOCAL
      ELSE NULL
  END AS EMP_LOCAL,

  EMP.QTD_COLABS AS EMP_COLABS,
  EMP.QTD_ESTAG AS EMP_ESTAG,
  EMP.QTD_APRE  AS EMP_APRE,
  EMP.QTD_SERV  AS EMP_SERV,
  EMP.QTD_AFAST AS EMP_AFAST,
  EMP.QTD_COLAB_FEM AS EMP_FEM,
  EMP.PERC_FEM AS EMP_PERC_FEM,
  EMP.QTD_COLAB_MASC AS EMP_MASC,
  EMP.PERC_MASC AS EMP_PERC_MASC,
  EMP.TOT_COLAB AS EMP_TOTAL,

  :DATA_REFERENCIA AS REFERENCIA

FROM ADM_NUM ADM
FULL OUTER JOIN CD_NUM CD ON ADM.RN = CD.RN
FULL OUTER JOIN ADM_TOT_NUM ATT ON ADM.RN = ATT.RN
FULL OUTER JOIN ADM_CD_NUM AC ON ADM.RN = AC.RN
FULL OUTER JOIN REDES_NUM REDE ON ADM.RN = REDE.RN
FULL OUTER JOIN TOT_LOJAS_NUM LOJAS ON ADM.RN = LOJAS.RN
FULL OUTER JOIN EMP_NUM EMP ON ADM.RN = EMP.RN
ORDER BY NVL(ADM.RN, REDE.RN)
