SELECT DISTINCT
       DES_REDE_LOCAL,
       DES_UNIDADE,
       COD_CONTRATO,
       DES_PESSOA,
       DATA_NASCIMENTO,
       IDADE,
       DES_AFAST
FROM V_DADOS_COLAB_AVT
WHERE STATUS = 0
--AND STATUS_AFAST = '0'
AND DES_FUNCAO LIKE '%GERENTE%'
AND COD_TIPO = 1
AND (COD_REDE_LOCAL = :REDE OR :REDE = 0)
--AND COD_CONTRATO = 388606
ORDER BY DES_UNIDADE
