WITH
CONTRATOS AS (
  SELECT DISTINCT CT.STATUS,
                  CT.COD_CONTRATO,
                  CT.DES_PESSOA,
                  CT.DATA_ADMISSAO,
                  CT.DATA_DEMISSAO,
                  -- Tempo de empresa individual
                  TRUNC(MONTHS_BETWEEN(:DATA_FIM, CT.DATA_AVANCO) / 12) ||
                  ' ano(s)' || ' e ' ||
                  TRUNC(MOD(MONTHS_BETWEEN(:DATA_FIM, CT.DATA_AVANCO), 12)) ||
                  ' mês(es)' AS TEMPO_EMPRESA,
                  CT.DATA_NASCIMENTO,
                  CT.IDADE,
                  FN.COD_FUNCAO,
                  FN.DES_FUNCAO,
                  HR.HR_BASE_MES,
                  CT.IND_DEFICIENCIA,
                  CT.SEXO,
                  ORG.COD_EMP,
                  ORG.EDICAO_EMP,
                  ORG.DES_EMP,
                  ORG.COD_ORGANOGRAMA,
                  ORG.COD_UNIDADE,
                  ORG.DES_UNIDADE,
                  ORG.NOME_ORGANOGRAMA,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_3
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME3
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME3
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_FILIAL,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.EDICAO_ORG_4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.EDICAO_ORG_4
                      ELSE
                       ORG.COD_UNIDADE
                  END AS COD_DIVISAO,
                  CASE
                      WHEN ORG.COD_TIPO = 2 THEN
                       ORG.NOME4
                      WHEN ORG.COD_TIPO = 3 THEN
                       ORG.NOME4
                      ELSE
                       ORG.DES_UNIDADE
                  END AS DES_DIVISAO,
                  ORG.EDICAO,
                  ORG.COD_REDE,
                  ORG.DES_REDE,
                  ORG.COD_TIPO,
                  ORG.DES_TIPO
   FROM V_DADOS_CONTRATO_AVT CT,
         VH_EST_ORG_CONTRATO_AVT ORG,
         VH_HIST_HORAS_COLAB_AVT HR,
         VH_CARGO_CONTRATO_AVT FN
   WHERE CT.COD_CONTRATO = ORG.COD_CONTRATO
     AND CT.COD_CONTRATO = HR.COD_CONTRATO
     AND CT.COD_CONTRATO = FN.COD_CONTRATO
     AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
          (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
     AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
     AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH
     AND :DATA_FIM BETWEEN HR.DATA_INI_HR AND HR.DATA_FIM_HR
     AND ORG.COD_EMP = 4
    /* AND (ORG.COD_TIPO = :TIPO OR :TIPO = 0)
     AND (ORG.COD_UNIDADE = :SETOR OR :SETOR = 0)
     AND (ORG.COD_REDE = :REDE OR :REDE = 0)*/
     AND ORG.EDICAO_ORG_4 IS NOT NULL
   ORDER BY ORG.COD_TIPO, ORG.COD_REDE, ORG.COD_UNIDADE, CT.COD_CONTRATO
),


STATUS_AFASTADOS AS (
SELECT DISTINCT
       ORG.COD_EMP,
       CT.COD_CONTRATO,
       ORG.COD_UNIDADE,
       NVL(AF.COD_CAUSA_AFAST,0) AS STATUS_AFAST,
       NA.NOME_CAUSA_AFAST AS DES_AFAST
  FROM RHFP0306 AF,
       RHFP0300 CT,
       VH_EST_ORG_CONTRATO_AVT ORG,
       VH_CARGO_CONTRATO_AVT FN,
       RHFP0100 NA
 WHERE CT.COD_CONTRATO = AF.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = ORG.COD_CONTRATO(+)
   AND CT.COD_CONTRATO = FN.COD_CONTRATO(+)
   AND AF.COD_CAUSA_AFAST = NA.COD_CAUSA_AFAST(+)
   AND ((:DATA_FIM BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
        (CT.DATA_INICIO <= :DATA_FIM AND CT.DATA_FIM IS NULL))
   AND :DATA_FIM BETWEEN AF.DATA_INICIO(+) AND AF.DATA_FIM(+)
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG(+) AND ORG.DATA_FIM_ORG(+)
   AND :DATA_FIM BETWEEN FN.DATA_INI_CLH AND FN.DATA_FIM_CLH(+)
   /*AND (ORG.COD_TIPO = :TIPO OR :TIPO = 0)
   AND (ORG.COD_UNIDADE = :SETOR OR :SETOR = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)*/
   --AND (ORG.COD_EMP = :EMPRESA OR :EMPRESA = 0)
   AND ORG.COD_EMP = 4
),


HORAS_REALIZADAS_UNI AS (
SELECT ORG.COD_EMP,
       ORG.COD_ORGANOGRAMA,
       ORG.COD_UNIDADE,
       ORG.COD_REDE,
       ORG.COD_TIPO,
       SUM(A.NUM_HORAS) AS HORAS_REAIS
  FROM RHAF1123 A
  LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
  LEFT JOIN V_DADOS_CONTRATO_AVT CT ON A.COD_CONTRATO = CT.COD_CONTRATO
 WHERE A.DATA_OCORRENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND A.COD_OCORRENCIA = 2
   AND ORG.COD_EMP = 4
   --AND (ORG.COD_TIPO = :TIPO OR :TIPO = 0)
   AND (ORG.COD_UNIDADE = :SETOR OR :SETOR = 0)
   --AND (ORG.COD_REDE = :REDE OR :REDE = 0)
 GROUP BY ORG.COD_ORGANOGRAMA,
          ORG.COD_UNIDADE,
          ORG.COD_REDE,
          ORG.COD_TIPO,
          ORG.COD_EMP

),


CONTADORES_UNI AS (
SELECT A.COD_TIPO,
       A.COD_ORGANOGRAMA,
       A.COD_UNIDADE  AS UNIDADE_CONT,
       A.DES_UNIDADE,
       A.COD_REDE,
       A.DES_REDE,
       A.COD_EMP,
       A.DES_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_220,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_200,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_195,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_180,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_165,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_160,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_150,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_140,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_125,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_120,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_110,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_105,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_100,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_80,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_60,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_40,
       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                             AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_COLAB_HRS,

       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_ATV,
       COUNT(DISTINCT CASE WHEN A.IND_DEFICIENCIA = 'S' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_PCD,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST NOT IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_AFSTO,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST = 3 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MATER,

       COUNT(DISTINCT CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
       ROUND((COUNT(CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
       COUNT(DISTINCT CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
       ROUND((COUNT(CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,

       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_APRE,

       COUNT(DISTINCT A.COD_CONTRATO) AS QTD_TOT_COLAB

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
  WHERE /*(A.COD_TIPO = :TIPO OR :TIPO = 0)
    AND*/ (A.COD_UNIDADE = :SETOR OR :SETOR = 0)
    --AND (A.COD_REDE = :REDE OR :REDE = 0)
    --AND (A.COD_EMP = :EMPRESA OR :EMPRESA = 0)
  GROUP BY A.COD_UNIDADE,
           A.DES_UNIDADE,
           A.COD_REDE,
           A.DES_REDE,
           A.COD_EMP,
           A.DES_EMP,
           A.COD_TIPO,
           A.COD_ORGANOGRAMA
  ORDER BY A.COD_TIPO, A.COD_REDE, A.COD_UNIDADE
),


SOMAS_HORAS_BASE_UNI AS (
SELECT A.COD_ORGANOGRAMA,
    A.COD_REDE,
    A.COD_TIPO,
    SUM(CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 220 ELSE 0 END) AS SUM_220,
    SUM(CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 200 ELSE 0 END) AS SUM_200,
    SUM(CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 195 ELSE 0 END) AS SUM_195,
    SUM(CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 180 ELSE 0 END) AS SUM_180,
    SUM(CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 165 ELSE 0 END) AS SUM_165,
    SUM(CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 160 ELSE 0 END) AS SUM_160,
    SUM(CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 150 ELSE 0 END) AS SUM_150,
    SUM(CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 140 ELSE 0 END) AS SUM_140,
    SUM(CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 125 ELSE 0 END) AS SUM_125,
    SUM(CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 120 ELSE 0 END) AS SUM_120,
    SUM(CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 110 ELSE 0 END) AS SUM_110,
    SUM(CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 105 ELSE 0 END) AS SUM_105,
    SUM(CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 100 ELSE 0 END) AS SUM_100,
    SUM(CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 80 ELSE 0 END) AS SUM_80,
    SUM(CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 60 ELSE 0 END) AS SUM_60,
    SUM(CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 40 ELSE 0 END) AS SUM_40,

    SUM(CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                               AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.HR_BASE_MES ELSE TO_CHAR(0) END) AS SUM_TOT_HRS

    --ROUND((SUM(CASE WHEN A.SEXO = 'M' THEN 1 ELSE 0 END) / COUNT(*) * 100), 2) AS PERC_MASC

FROM CONTRATOS A
LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
WHERE /*(A.COD_TIPO = :TIPO OR :TIPO = 0)
  AND*/ (A.COD_UNIDADE = :SETOR OR :SETOR = 0)
  --AND (A.COD_REDE = :REDE OR :REDE = 0)
  --AND (A.COD_EMP = :EMPRESA OR :EMPRESA = 0)
GROUP BY A.COD_ORGANOGRAMA,
         A.COD_TIPO,
         A.COD_REDE
),



HORAS_REALIZADAS_REDE AS (
SELECT ORG.COD_EMP,
       ORG.COD_REDE AS REDE_HR,
       ORG.COD_TIPO,
       SUM(A.NUM_HORAS) AS HORAS_REAIS_RD
  FROM RHAF1123 A
  LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
  LEFT JOIN V_DADOS_CONTRATO_AVT CT ON A.COD_CONTRATO = CT.COD_CONTRATO
 WHERE A.DATA_OCORRENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND A.COD_OCORRENCIA = 2
   AND ORG.COD_EMP = 4
   --AND (ORG.COD_REDE = :REDE OR :REDE = 0)
 GROUP BY ORG.COD_REDE, ORG.COD_TIPO, ORG.COD_EMP

),

CONTADORES_REDE AS (
SELECT A.COD_REDE AS REDE_CONT,
       A.DES_REDE AS DES_REDE_CONT,
       A.COD_TIPO,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_220_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_200_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_195_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_180_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_165_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_160_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_150_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_140_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_125_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_120_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_110_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_105_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_100_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_80_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_60_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_40_RD,
       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                             AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_COLAB_HRS_RD,

       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_ATV_RD,
       COUNT(DISTINCT CASE WHEN A.IND_DEFICIENCIA = 'S' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_PCD_RD,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST NOT IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_AFSTO_RD,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST = 3 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MATER_RD,

       COUNT(DISTINCT CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM_RD,
       ROUND((COUNT(CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM_RD,
       COUNT(DISTINCT CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC_RD,
       ROUND((COUNT(CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC_RD,

       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_APRE_RD,

       COUNT(DISTINCT A.COD_CONTRATO) AS QTD_TOT_COLAB_RD

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
  --WHERE (A.COD_REDE = :REDE OR :REDE = 0)
  GROUP BY A.COD_REDE,
           A.DES_REDE,
           A.COD_TIPO
  ORDER BY A.COD_TIPO, A.COD_REDE
),

SOMAS_HORAS_BASE_REDE AS (
SELECT
    A.COD_REDE AS REDE_SUM,
    A.COD_TIPO,
    SUM(CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 220 ELSE 0 END) AS SUM_220_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 200 ELSE 0 END) AS SUM_200_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 195 ELSE 0 END) AS SUM_195_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 180 ELSE 0 END) AS SUM_180_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 165 ELSE 0 END) AS SUM_165_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 160 ELSE 0 END) AS SUM_160_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 150 ELSE 0 END) AS SUM_150_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 140 ELSE 0 END) AS SUM_140_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 125 ELSE 0 END) AS SUM_125_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 120 ELSE 0 END) AS SUM_120_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 110 ELSE 0 END) AS SUM_110_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 105 ELSE 0 END) AS SUM_105_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 100 ELSE 0 END) AS SUM_100_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 80 ELSE 0 END) AS SUM_80_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 60 ELSE 0 END) AS SUM_60_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 40 ELSE 0 END) AS SUM_40_RD,

    SUM(CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                               AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.HR_BASE_MES ELSE TO_CHAR(0) END) AS SUM_TOT_HRS_RD

    --ROUND((SUM(CASE WHEN A.SEXO = 'M' THEN 1 ELSE 0 END) / COUNT(*) * 100), 2) AS PERC_MASC

FROM CONTRATOS A
LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
--WHERE (A.COD_REDE = :REDE OR :REDE = 0)
GROUP BY A.COD_REDE,
         A.COD_TIPO
ORDER BY A.COD_TIPO, A.COD_REDE
),



HORAS_REALIZADAS_EMP AS (
SELECT ORG.COD_EMP AS EMPRESA_HR,
       --A.COD_CONTRATO,
       SUM(A.NUM_HORAS) AS HORAS_REAIS_EMP
  FROM RHAF1123 A
  LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
  LEFT JOIN V_DADOS_CONTRATO_AVT CT ON A.COD_CONTRATO = CT.COD_CONTRATO
 WHERE A.DATA_OCORRENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND A.COD_OCORRENCIA = 2
   AND ORG.COD_EMP = 4
 GROUP BY ORG.COD_EMP

),


CONTADORES_EMP AS (
SELECT A.COD_EMP AS EMPRESA_CONT,
       A.DES_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_22_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_200_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_195_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_180_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_165_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_160_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_150_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_140_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_125_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_120_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_110_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_105_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_100_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_80_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_60_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_40_EMP,
       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                             AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_COLAB_HRS_EMP,

       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_ATV_EMP,
       COUNT(DISTINCT CASE WHEN A.IND_DEFICIENCIA = 'S' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_PCD_EMP,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST NOT IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_AFSTO_EMP,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST = 3 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MATER_EMP,

       COUNT(DISTINCT CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM_EMP,
       ROUND((COUNT(CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM_EMP,
       COUNT(DISTINCT CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC_EMP,
       ROUND((COUNT(CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC_EMP,

       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_APRE_EMP,

       COUNT(DISTINCT A.COD_CONTRATO) AS QTD_TOT_COLAB_EMP

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
  --WHERE (A.COD_EMP = :EMPRESA OR :EMPRESA = 0)
  GROUP BY A.COD_EMP,
           A.DES_EMP
  ORDER BY A.COD_EMP
),

SOMAS_HORAS_BASE_EMP AS (
SELECT
    A.COD_EMP AS EMPRESA_SUM,
    SUM(CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 220 ELSE 0 END) AS SUM_220_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 200 ELSE 0 END) AS SUM_200_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 195 ELSE 0 END) AS SUM_195_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 180 ELSE 0 END) AS SUM_180_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 165 ELSE 0 END) AS SUM_165_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 160 ELSE 0 END) AS SUM_160_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 150 ELSE 0 END) AS SUM_150_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 140 ELSE 0 END) AS SUM_140_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 125 ELSE 0 END) AS SUM_125_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 120 ELSE 0 END) AS SUM_120_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 110 ELSE 0 END) AS SUM_110_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 105 ELSE 0 END) AS SUM_105_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 100 ELSE 0 END) AS SUM_100_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 80 ELSE 0 END) AS SUM_80_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 60 ELSE 0 END) AS SUM_60_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 40 ELSE 0 END) AS SUM_40_EMP,

    SUM(CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                               AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.HR_BASE_MES ELSE TO_CHAR(0) END) AS SUM_TOT_HRS_EMP

    --ROUND((SUM(CASE WHEN A.SEXO = 'M' THEN 1 ELSE 0 END) / COUNT(*) * 100), 2) AS PERC_MASC

FROM CONTRATOS A
LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
--WHERE (A.COD_EMP = :EMPRESA OR :EMPRESA = 0)

GROUP BY A.COD_EMP

),

HORAS_PONTO_UNI AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A1.COD_TIPO, A1.COD_REDE, A1.COD_ORGANOGRAMA) AS RN, A1.*
  FROM HORAS_REALIZADAS_UNI A1
),

UNI_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A.COD_TIPO, A.COD_REDE, A.UNIDADE_CONT, A.COD_ORGANOGRAMA) AS RN, A.*
  FROM CONTADORES_UNI A
),

SOMAS_HORAS_BASE_UNI_NUM AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY A.COD_TIPO, A.COD_REDE, A.COD_ORGANOGRAMA) AS RN,
    A.*
  FROM SOMAS_HORAS_BASE_UNI A
),

HORAS_PONTO_REDE AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A2.COD_TIPO, A2.REDE_HR) AS RN, A2.*
  FROM HORAS_REALIZADAS_REDE A2
),


REDE_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY B.COD_TIPO, B.REDE_CONT) AS RN, B.*
  FROM CONTADORES_REDE B
),

SOMAS_HORAS_BASE_REDE_NUM AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY B.COD_TIPO, B.REDE_SUM) AS RN,
    B.*
  FROM SOMAS_HORAS_BASE_REDE B
),


HORAS_PONTO_EMP AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A3.EMPRESA_HR) AS RN, A3.*
  FROM HORAS_REALIZADAS_EMP A3
),

EMP_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY EMPRESA_CONT) AS RN, C.*
  FROM CONTADORES_EMP C
),

SOMAS_HORAS_BASE_EMP_NUM AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY EMPRESA_SUM) AS RN,
    C.*
  FROM SOMAS_HORAS_BASE_EMP C
)


SELECT UNI.COD_TIPO,
       UNI.COD_ORGANOGRAMA,
       UNI.UNIDADE_CONT,
       UNI.DES_UNIDADE,
       UNI.COD_REDE,
       UNI.DES_REDE,
       UNI.COD_EMP,
       UNI.DES_EMP,
       UNI.QTD_220,
       SU.SUM_220,
       UNI.QTD_200,
       SU.SUM_200,
       UNI.QTD_195,
       SU.SUM_195,
       UNI.QTD_180,
       SU.SUM_180,
       UNI.QTD_165,
       SU.SUM_165,
       UNI.QTD_160,
       SU.SUM_160,
       UNI.QTD_150,
       SU.SUM_150,
       UNI.QTD_140,
       SU.SUM_140,
       UNI.QTD_125,
       SU.SUM_125,
       UNI.QTD_120,
       SU.SUM_120,
       UNI.QTD_110,
       SU.SUM_110,
       UNI.QTD_105,
       SU.SUM_105,
       UNI.QTD_100,
       SU.SUM_100,
       UNI.QTD_80,
       SU.SUM_80,
       UNI.QTD_60,
       SU.SUM_60,
       UNI.QTD_40,
       SU.SUM_40,

       SU.SUM_TOT_HRS,

       REPLACE(TO_CHAR(HPU.HORAS_REAIS, 'FM9999990.00'), '.', ',') AS HRS_REAIS,
       HPU.HORAS_REAIS,

       UNI.QTD_COLAB_HRS,
       UNI.QTD_COLAB_ATV,
       UNI.QTD_PCD,
       UNI.QTD_AFSTO,
       UNI.QTD_COLAB_MATER,

       UNI.QTD_COLAB_FEM,
       UNI.PERC_FEM,
       UNI.QTD_COLAB_MASC,
       UNI.PERC_MASC,

       UNI.QTD_APRE,

       UNI.QTD_TOT_COLAB,

       REDE.REDE_CONT,
       REDE.DES_REDE_CONT,
       REDE.COD_TIPO,
       REDE.QTD_220_RD,
       REDE.QTD_200_RD,
       REDE.QTD_195_RD,
       REDE.QTD_180_RD,
       REDE.QTD_165_RD,
       REDE.QTD_160_RD,
       REDE.QTD_150_RD,
       REDE.QTD_140_RD,
       REDE.QTD_125_RD,
       REDE.QTD_120_RD,
       REDE.QTD_110_RD,
       REDE.QTD_105_RD,
       REDE.QTD_100_RD,
       REDE.QTD_80_RD,
       REDE.QTD_60_RD,
       REDE.QTD_40_RD,

       REDE.QTD_COLAB_HRS_RD,
       REDE.QTD_COLAB_ATV_RD,
       REDE.QTD_PCD_RD,
       REDE.QTD_AFSTO_RD,
       REDE.QTD_COLAB_MATER_RD,

       REDE.QTD_COLAB_FEM_RD,
       REDE.PERC_FEM_RD,
       REDE.QTD_COLAB_MASC_RD,
       REDE.PERC_MASC_RD,

       REDE.QTD_APRE_RD,

       REDE.QTD_TOT_COLAB_RD,
       SR.*,
       REPLACE(TO_CHAR(HPR.HORAS_REAIS_RD, 'FM9999990.00'), '.', ',') AS HRS_REAIS_RD,
       HPR.HORAS_REAIS_RD,

       EMP.*,
       SE.*,
       REPLACE(TO_CHAR(HPE.HORAS_REAIS_EMP, 'FM9999990.00'), '.', ',') AS HRS_REAIS_EMP,
       HPE.HORAS_REAIS_EMP,

       :DATA_INICIO  || ' - ' || :DATA_FIM AS REFERENCIA,
       'UNIDADE: '   || :UNIDADE  || ' | ' ||
       'AFASTADOS? ' || :AFASTADOS AS PARAMETROS_USADOS


  FROM UNI_NUM UNI
  FULL OUTER JOIN REDE_NUM REDE ON UNI.RN = REDE.RN AND 1 = 1
  FULL OUTER JOIN EMP_NUM EMP ON UNI.RN = EMP.RN
  FULL OUTER JOIN SOMAS_HORAS_BASE_UNI_NUM SU ON UNI.COD_ORGANOGRAMA = SU.COD_ORGANOGRAMA
  FULL OUTER JOIN SOMAS_HORAS_BASE_REDE_NUM SR ON REDE.RN = SR.RN
  FULL OUTER JOIN SOMAS_HORAS_BASE_EMP_NUM SE ON UNI.RN = SE.RN
  FULL OUTER JOIN HORAS_PONTO_UNI HPU ON UNI.RN = HPU.RN
  FULL OUTER JOIN HORAS_PONTO_REDE HPR ON REDE.RN = HPR.RN
  FULL OUTER JOIN HORAS_PONTO_EMP HPE ON UNI.RN = HPE.RN
ORDER BY NVL(UNI.RN, REDE.RN);


