WITH
PARAMS AS (
    SELECT
        TO_DATE(:DATA_INICIO, 'DD/MM/YYYY') AS DATA_INICIO,
        TO_DATE(:DATA_FIM, 'DD/MM/YYYY') AS DATA_FIM
    FROM DUAL

    /*SELECT
        TO_DATE('&DATA_INICIO', 'DD/MM/YYYY') AS DATA_INICIO,
        TO_DATE('&DATA_FIM', 'DD/MM/YYYY') AS DATA_FIM
    FROM DUAL*/
),

ORG_ULT AS (
    SELECT
        ORG.COD_CONTRATO,
        ORG.COD_EMP,
        ORG.EDICAO_EMP,
        ORG.DES_EMP,
        ORG.COD_ORGANOGRAMA,
        ORG.COD_UNIDADE,
        ORG.DES_UNIDADE,
        ORG.DATA_INI_ORG,
        ORG.DATA_FIM_ORG,
        ORG.COD_REDE,
        ORG.DES_REDE,
        ORG.COD_TIPO,
        ORG.DES_TIPO,
        ORG.EDICAO_ORG_3,
        ORG.NOME3,
        ORG.EDICAO_ORG_4,
        ORG.NOME4,
        ROW_NUMBER() OVER (
            PARTITION BY ORG.COD_CONTRATO
            ORDER BY NVL(ORG.DATA_FIM_ORG, DATE '2999-12-31') DESC,
                     ORG.DATA_INI_ORG DESC
        ) AS RN
    FROM VH_EST_ORG_CONTRATO_AVT ORG
    CROSS JOIN PARAMS P
    WHERE ORG.DATA_INI_ORG <= P.DATA_FIM
      AND ORG.COD_EMP = 8
),

FUNCAO_ULT AS (
    SELECT
        FN.COD_CONTRATO,
        FN.COD_FUNCAO,
        FN.DES_FUNCAO,
        FN.DATA_INI_CLH,
        FN.DATA_FIM_CLH,
        ROW_NUMBER() OVER (
            PARTITION BY FN.COD_CONTRATO
            ORDER BY NVL(FN.DATA_FIM_CLH, DATE '2999-12-31') DESC,
                     FN.DATA_INI_CLH DESC
        ) AS RN
    FROM VH_CARGO_CONTRATO_AVT FN
    CROSS JOIN PARAMS P
    WHERE FN.DATA_INI_CLH <= P.DATA_FIM
      AND FN.DES_FUNCAO LIKE '%APRENDIZ%'
),

BASE_APRENDIZ AS (
    SELECT DISTINCT
           CT.STATUS,
           CT.COD_CONTRATO,
           CT.DES_PESSOA,
           CT.DATA_NASCIMENTO,
           CT.DATA_ADMISSAO,
           CT.DATA_DEMISSAO,
           CT.COD_VINCULO_EMPREG,
           FN.COD_FUNCAO,
           FN.DES_FUNCAO,
           ORG.COD_EMP,
           ORG.EDICAO_EMP,
           ORG.DES_EMP,
           ORG.COD_ORGANOGRAMA,
           ORG.COD_UNIDADE,
           ORG.DES_UNIDADE,
           ORG.DATA_INI_ORG,
           ORG.DATA_FIM_ORG,
           CASE
             WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.EDICAO_ORG_3
             ELSE ORG.COD_UNIDADE
           END AS COD_FILIAL,
           CASE
             WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.NOME3
             ELSE ORG.DES_UNIDADE
           END AS DES_FILIAL,
           CASE
             WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.EDICAO_ORG_4
             ELSE ORG.COD_UNIDADE
           END AS COD_DIVISAO,
           CASE
             WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.NOME4
             ELSE ORG.DES_UNIDADE
           END AS DES_DIVISAO,
           ORG.COD_REDE,
           ORG.DES_REDE,
           ORG.COD_TIPO,
           ORG.DES_TIPO
      FROM V_DADOS_CONTRATO_AVT CT
      JOIN ORG_ULT ORG
        ON ORG.COD_CONTRATO = CT.COD_CONTRATO
       AND ORG.RN = 1
      JOIN FUNCAO_ULT FN
        ON FN.COD_CONTRATO = CT.COD_CONTRATO
       AND FN.RN = 1
     WHERE ORG.EDICAO_ORG_4 IS NOT NULL
),

CONTRATO_EXPERIENCIA AS (
    SELECT
        A.COD_CONTRATO,
        A.DATA_INICIO AS DATA_INI_EXP,
        A.DATA_FIM AS DATA_FIM_EXP,
        TO_NUMBER(TRUNC(A.DATA_FIM - A.DATA_INICIO) + 1) AS DIAS_CONTRATO,
        B.DATA_AVALIACAO,
        B.IND_AVALIACAO,
        C.NUM_DIAS,
        C.IND_AVALIACOES,
        D.NOME_TIPO_CONTRATO,
        D.DURACAO_CONTRATO,
        ROW_NUMBER() OVER (
            PARTITION BY A.COD_CONTRATO
            ORDER BY A.DATA_FIM DESC, A.DATA_INICIO DESC
        ) AS RN
    FROM RHFP0304 A
    LEFT JOIN RHFP0305 B
           ON B.COD_CONTRATO = A.COD_CONTRATO
          AND B.DATA_INICIO = A.DATA_INICIO
    JOIN RHFP0314 C
      ON A.COD_TP_CONTRATO = C.COD_TP_CONTRATO
    JOIN RHFP0116 D
      ON C.COD_TIPO_CONTRATO = D.COD_TIPO_CONTRATO
    CROSS JOIN PARAMS P
    WHERE P.DATA_FIM BETWEEN A.DATA_INICIO AND A.DATA_FIM
),

STATUS_AFASTADOS AS (
    SELECT
        X.COD_CONTRATO,
        X.COD_AFAST,
        X.DES_AFAST,
        X.DES_STATUS_AFAST,
        X.DATA_INI_AFAST,
        X.DATA_FIM_AFAST
    FROM (
        SELECT
            B.COD_CONTRATO,
            AF.COD_CAUSA_AFAST AS COD_AFAST,
            AFN.NOME_CAUSA_AFAST AS DES_AFAST,
            NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFAST,
           CASE
             WHEN B.DATA_DEMISSAO IS NOT NULL
              AND B.DATA_DEMISSAO < SYSDATE THEN
                'INATIVO'
                WHEN AF.COD_CAUSA_AFAST <> 0
                 AND AF.COD_CAUSA_AFAST <> 4
                 AND AF.COD_CAUSA_AFAST <> 21
                 AND AF.COD_CAUSA_AFAST <> 60
                 AND NVL(AF.DATA_FIM, DATE '2999-12-31') = DATE '2999-12-31' THEN
                    'AFASTADO'
                WHEN AF.COD_CAUSA_AFAST IN (21, 60) THEN
                    'ATIVO, SEM RETORNO'
                WHEN AF.COD_CAUSA_AFAST = 7 THEN
                    'EM FÉRIAS'
                WHEN AF.COD_CAUSA_AFAST IN (3, 6) THEN
                    'AFASTADO TEMP'
                WHEN AF.COD_CAUSA_AFAST = 4
                 AND NVL(AF.DATA_FIM, DATE '2999-12-31') = DATE '2999-12-31' THEN
                    'PODERÁ RETORNAR'
                ELSE
                    'EM ATIVIDADE'
            END AS DES_STATUS_AFAST,
            AF.DATA_INICIO AS DATA_INI_AFAST,
            AF.DATA_FIM AS DATA_FIM_AFAST,
            ROW_NUMBER() OVER (
                PARTITION BY B.COD_CONTRATO
                ORDER BY
                    CASE
                        WHEN AF.COD_CAUSA_AFAST IS NOT NULL
                         AND NVL(AF.COD_CAUSA_AFAST, 0) <> 0 THEN 1
                        ELSE 2
                    END,
                    NVL(AF.DATA_FIM, DATE '2999-12-31') DESC,
                    AF.DATA_INICIO DESC
            ) AS RN
        FROM BASE_APRENDIZ B
        CROSS JOIN PARAMS P
        LEFT JOIN RHFP0306 AF
               ON AF.COD_CONTRATO = B.COD_CONTRATO
              AND P.DATA_FIM BETWEEN AF.DATA_INICIO
                                 AND NVL(AF.DATA_FIM, DATE '2999-12-31')
        LEFT JOIN RHFP0100 AFN
               ON AFN.COD_CAUSA_AFAST = AF.COD_CAUSA_AFAST
    ) X
    WHERE X.RN = 1
),

APRENDIZES_ATIVOS AS (
    SELECT
        B.COD_UNIDADE,
        B.DES_UNIDADE,
        B.COD_ORGANOGRAMA,
        B.COD_REDE,
        B.DES_REDE,
        B.COD_TIPO,
        B.DES_TIPO,
        1 AS COD_STATUS_REL,
        'ATIVO' AS STATUS_REL,
        B.COD_CONTRATO,
        B.DES_PESSOA,
        B.DATA_ADMISSAO,
        B.DATA_DEMISSAO,
        B.COD_VINCULO_EMPREG,
        CE.DATA_INI_EXP,
        CE.DATA_FIM_EXP,
        CE.DIAS_CONTRATO,
        CE.DATA_AVALIACAO,
        CE.IND_AVALIACAO,
        CE.NUM_DIAS,
        CE.IND_AVALIACOES,
        CE.NOME_TIPO_CONTRATO,
        CE.DURACAO_CONTRATO,
        SA.COD_AFAST,
        SA.DES_AFAST,
        SA.DES_STATUS_AFAST,
        SA.DATA_INI_AFAST,
        SA.DATA_FIM_AFAST,
        ROW_NUMBER() OVER (
            PARTITION BY B.COD_ORGANOGRAMA, B.COD_UNIDADE
            ORDER BY B.DES_PESSOA, B.COD_CONTRATO
        ) AS ORDEM_PESSOA
    FROM BASE_APRENDIZ B
    CROSS JOIN PARAMS P
    LEFT JOIN CONTRATO_EXPERIENCIA CE
           ON CE.COD_CONTRATO = B.COD_CONTRATO
          AND CE.RN = 1
    LEFT JOIN STATUS_AFASTADOS SA
           ON SA.COD_CONTRATO = B.COD_CONTRATO
    WHERE B.DATA_ADMISSAO <= P.DATA_FIM
      AND (B.DATA_DEMISSAO IS NULL OR B.DATA_DEMISSAO > P.DATA_FIM)
),

APRENDIZES_DEMITIDOS_PERIODO AS (
    SELECT
        B.COD_UNIDADE,
        B.DES_UNIDADE,
        B.COD_ORGANOGRAMA,
        B.COD_REDE,
        B.DES_REDE,
        B.COD_TIPO,
        B.DES_TIPO,
        2 AS COD_STATUS_REL,
        'DEMITIDO' AS STATUS_REL,
        B.COD_CONTRATO,
        B.DES_PESSOA,
        B.DATA_ADMISSAO,
        B.DATA_DEMISSAO,
        B.COD_VINCULO_EMPREG,
        ROW_NUMBER() OVER (
            PARTITION BY B.COD_ORGANOGRAMA, B.COD_UNIDADE
            ORDER BY B.DATA_DEMISSAO, B.DES_PESSOA, B.COD_CONTRATO
        ) AS ORDEM_PESSOA
    FROM BASE_APRENDIZ B
    CROSS JOIN PARAMS P
    WHERE B.DATA_DEMISSAO BETWEEN P.DATA_INICIO AND P.DATA_FIM
),



ATIVOS_REL AS (
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY
                A.COD_UNIDADE,
                A.COD_ORGANOGRAMA,
                A.DES_PESSOA,
                A.COD_CONTRATO
        ) AS RN_GERAL,

        /* BLOCO ATIVO */
        A.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_ATIVO,
        A.COD_UNIDADE     AS COD_UNIDADE_ATIVO,
        A.DES_UNIDADE     AS UNIDADE_ATIVO,
        A.COD_REDE        AS COD_REDE_ATIVO,
        A.DES_REDE        AS REDE_ATIVO,
        A.COD_TIPO        AS COD_TIPO_ATIVO,
        A.DES_TIPO        AS TIPO_ATIVO,
        A.COD_STATUS_REL  AS COD_STATUS_ATIVO,
        A.STATUS_REL      AS STATUS_ATIVO,
        A.COD_CONTRATO || ' - ' || A.DES_PESSOA AS APRENDIZ_ATIVO,
        A.DATA_ADMISSAO   AS DT_ADMISSAO_ATIVO,
        A.COD_VINCULO_EMPREG AS VINCULO_ATIVO,
        A.DATA_INI_EXP    AS DT_INI_CONTRATO_EXP,
        A.DATA_FIM_EXP    AS DT_FIM_CONTRATO_EXP,
        A.DIAS_CONTRATO,
        A.NOME_TIPO_CONTRATO,
        A.DURACAO_CONTRATO,
        A.COD_AFAST        AS COD_AFAST_ATIVO,
        A.DES_AFAST        AS DES_AFAST_ATIVO,
        A.DES_STATUS_AFAST AS STATUS_AFAST_ATIVO,
        A.DATA_INI_AFAST   AS DT_INI_AFAST_ATIVO,
        A.DATA_FIM_AFAST   AS DT_FIM_AFAST_ATIVO
    FROM APRENDIZES_ATIVOS A
    WHERE (A.COD_TIPO = :TIPO OR :TIPO = 0)
      AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
      AND (A.COD_REDE = :REDE OR :REDE = 0)
),

DEMITIDOS_REL AS (
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY
                D.COD_UNIDADE,
                D.COD_ORGANOGRAMA,
                D.DATA_DEMISSAO,
                D.DES_PESSOA,
                D.COD_CONTRATO
        ) AS RN_GERAL,

        /* BLOCO DEMITIDO */
        D.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_DEMITIDO,
        D.COD_UNIDADE     AS COD_UNIDADE_DEMITIDO,
        D.DES_UNIDADE     AS UNIDADE_DEMITIDO,
        D.COD_REDE        AS COD_REDE_DEMITIDO,
        D.DES_REDE        AS REDE_DEMITIDO,
        D.COD_TIPO        AS COD_TIPO_DEMITIDO,
        D.DES_TIPO        AS TIPO_DEMITIDO,
        D.COD_STATUS_REL  AS COD_STATUS_DEMITIDO,
        D.STATUS_REL      AS STATUS_DEMITIDO,
        D.COD_CONTRATO || ' - ' || D.DES_PESSOA AS APRENDIZ_DEMITIDO,
        D.DATA_ADMISSAO   AS DT_ADMISSAO_DEMITIDO,
        D.DATA_DEMISSAO   AS DT_DEMISSAO_DEMITIDO,
        D.COD_VINCULO_EMPREG AS VINCULO_DEMITIDO
    FROM APRENDIZES_DEMITIDOS_PERIODO D
    WHERE (D.COD_TIPO = :TIPO OR :TIPO = 0)
      AND (D.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
      AND (D.COD_REDE = :REDE OR :REDE = 0)
)

SELECT
    /* BLOCO ATIVOS */
    A.COD_ORGANOGRAMA_ATIVO,
    A.COD_UNIDADE_ATIVO,
    A.UNIDADE_ATIVO,
    A.COD_REDE_ATIVO,
    A.REDE_ATIVO,
    A.COD_TIPO_ATIVO,
    A.TIPO_ATIVO,
    A.COD_STATUS_ATIVO,
    A.STATUS_ATIVO,
    A.APRENDIZ_ATIVO,
    A.DT_ADMISSAO_ATIVO,
    A.VINCULO_ATIVO,
    A.DT_INI_CONTRATO_EXP,
    A.DT_FIM_CONTRATO_EXP,
    A.DIAS_CONTRATO,
    A.NOME_TIPO_CONTRATO,
    A.DURACAO_CONTRATO,
    A.COD_AFAST_ATIVO,
    A.DES_AFAST_ATIVO,
    A.STATUS_AFAST_ATIVO,
    A.DT_INI_AFAST_ATIVO,
    A.DT_FIM_AFAST_ATIVO,

    /* BLOCO DEMITIDOS */
    D.COD_ORGANOGRAMA_DEMITIDO,
    D.COD_UNIDADE_DEMITIDO,
    D.UNIDADE_DEMITIDO,
    D.COD_REDE_DEMITIDO,
    D.REDE_DEMITIDO,
    D.COD_TIPO_DEMITIDO,
    D.TIPO_DEMITIDO,
    D.COD_STATUS_DEMITIDO,
    D.STATUS_DEMITIDO,
    D.APRENDIZ_DEMITIDO,
    D.DT_ADMISSAO_DEMITIDO,
    D.DT_DEMISSAO_DEMITIDO,
    D.VINCULO_DEMITIDO

FROM ATIVOS_REL A
FULL OUTER JOIN DEMITIDOS_REL D
    ON A.RN_GERAL = D.RN_GERAL
ORDER BY NVL(A.RN_GERAL, D.RN_GERAL)




/*================== VERSÃO ALTERNATIVA =================*/

,
WITH
PARAMS AS (
    SELECT
        TO_DATE(:DATA_INICIO, 'DD/MM/YYYY') AS DATA_INICIO,
        TO_DATE(:DATA_FIM, 'DD/MM/YYYY') AS DATA_FIM
    FROM DUAL

    /*SELECT
        TO_DATE('&DATA_INICIO', 'DD/MM/YYYY') AS DATA_INICIO,
        TO_DATE('&DATA_FIM', 'DD/MM/YYYY') AS DATA_FIM
    FROM DUAL*/
),

ORG_ULT AS (
    SELECT
        ORG.COD_CONTRATO,
        ORG.COD_EMP,
        ORG.EDICAO_EMP,
        ORG.DES_EMP,
        ORG.COD_ORGANOGRAMA,
        ORG.COD_UNIDADE,
        ORG.DES_UNIDADE,
        ORG.DATA_INI_ORG,
        ORG.DATA_FIM_ORG,
        ORG.COD_REDE,
        ORG.DES_REDE,
        ORG.COD_TIPO,
        ORG.DES_TIPO,
        ORG.EDICAO_ORG_3,
        ORG.NOME3,
        ORG.EDICAO_ORG_4,
        ORG.NOME4,
        ROW_NUMBER() OVER (
            PARTITION BY ORG.COD_CONTRATO
            ORDER BY NVL(ORG.DATA_FIM_ORG, DATE '2999-12-31') DESC,
                     ORG.DATA_INI_ORG DESC
        ) AS RN
    FROM VH_EST_ORG_CONTRATO_AVT ORG
    CROSS JOIN PARAMS P
    WHERE ORG.DATA_INI_ORG <= P.DATA_FIM
      AND ORG.COD_EMP = 8
),

FUNCAO_ULT AS (
    SELECT
        FN.COD_CONTRATO,
        FN.COD_FUNCAO,
        FN.DES_FUNCAO,
        FN.DATA_INI_CLH,
        FN.DATA_FIM_CLH,
        ROW_NUMBER() OVER (
            PARTITION BY FN.COD_CONTRATO
            ORDER BY NVL(FN.DATA_FIM_CLH, DATE '2999-12-31') DESC,
                     FN.DATA_INI_CLH DESC
        ) AS RN
    FROM VH_CARGO_CONTRATO_AVT FN
    CROSS JOIN PARAMS P
    WHERE FN.DATA_INI_CLH <= P.DATA_FIM
      AND FN.DES_FUNCAO LIKE '%APRENDIZ%'
),

BASE_APRENDIZ AS (
    SELECT DISTINCT
           CT.DES_STATUS,
           CT.COD_CONTRATO,
           CT.DES_PESSOA,
           CT.DATA_NASCIMENTO,
           CT.DATA_ADMISSAO,
           CT.DATA_DEMISSAO,
           CT.COD_VINCULO_EMPREG,
           FN.COD_FUNCAO,
           FN.DES_FUNCAO,
           ORG.COD_EMP,
           ORG.EDICAO_EMP,
           ORG.DES_EMP,
           ORG.COD_ORGANOGRAMA,
           ORG.COD_UNIDADE,
           ORG.DES_UNIDADE,
           ORG.DATA_INI_ORG,
           ORG.DATA_FIM_ORG,
           CASE
             WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.EDICAO_ORG_3
             ELSE ORG.COD_UNIDADE
           END AS COD_FILIAL,
           CASE
             WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.NOME3
             ELSE ORG.DES_UNIDADE
           END AS DES_FILIAL,
           CASE
             WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.EDICAO_ORG_4
             ELSE ORG.COD_UNIDADE
           END AS COD_DIVISAO,
           CASE
             WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.NOME4
             ELSE ORG.DES_UNIDADE
           END AS DES_DIVISAO,
           ORG.COD_REDE,
           ORG.DES_REDE,
           ORG.COD_TIPO,
           ORG.DES_TIPO
      FROM V_DADOS_CONTRATO_AVT CT
      JOIN ORG_ULT ORG
        ON ORG.COD_CONTRATO = CT.COD_CONTRATO
       AND ORG.RN = 1
      JOIN FUNCAO_ULT FN
        ON FN.COD_CONTRATO = CT.COD_CONTRATO
       AND FN.RN = 1
     WHERE ORG.EDICAO_ORG_4 IS NOT NULL
),

CONTRATO_EXPERIENCIA AS (
    SELECT
        A.COD_CONTRATO,
        A.DATA_INICIO AS DATA_INI_EXP,
        A.DATA_FIM AS DATA_FIM_EXP,
        TO_NUMBER(TRUNC(A.DATA_FIM - A.DATA_INICIO) + 1) AS DIAS_CONTRATO,
        B.DATA_AVALIACAO,
        B.IND_AVALIACAO,
        C.NUM_DIAS,
        C.IND_AVALIACOES,
        D.NOME_TIPO_CONTRATO,
        D.DURACAO_CONTRATO,
        ROW_NUMBER() OVER (
            PARTITION BY A.COD_CONTRATO
            ORDER BY A.DATA_FIM DESC, A.DATA_INICIO DESC
        ) AS RN
    FROM RHFP0304 A
    LEFT JOIN RHFP0305 B
           ON B.COD_CONTRATO = A.COD_CONTRATO
          AND B.DATA_INICIO = A.DATA_INICIO
    JOIN RHFP0314 C
      ON A.COD_TP_CONTRATO = C.COD_TP_CONTRATO
    JOIN RHFP0116 D
      ON C.COD_TIPO_CONTRATO = D.COD_TIPO_CONTRATO
    CROSS JOIN PARAMS P
    WHERE P.DATA_FIM BETWEEN A.DATA_INICIO AND A.DATA_FIM
),

STATUS_AFASTADOS AS (
    SELECT
        X.COD_CONTRATO,
        X.COD_AFAST,
        X.DES_AFAST,
        X.DES_STATUS_AFAST,
        X.DATA_INI_AFAST,
        X.DATA_FIM_AFAST
    FROM (
        SELECT
            B.COD_CONTRATO,
            AF.COD_CAUSA_AFAST AS COD_AFAST,
            AFN.NOME_CAUSA_AFAST AS DES_AFAST,
            NVL(AF.COD_CAUSA_AFAST, 0) AS STATUS_AFAST,
           CASE
             WHEN B.DATA_DEMISSAO IS NOT NULL
              AND B.DATA_DEMISSAO < SYSDATE THEN
                'INATIVO'
                WHEN AF.COD_CAUSA_AFAST <> 0
                 AND AF.COD_CAUSA_AFAST <> 4
                 AND AF.COD_CAUSA_AFAST <> 21
                 AND AF.COD_CAUSA_AFAST <> 60
                 AND NVL(AF.DATA_FIM, DATE '2999-12-31') = DATE '2999-12-31' THEN
                    'AFASTADO'
                WHEN AF.COD_CAUSA_AFAST IN (21, 60) THEN
                    'ATIVO, SEM RETORNO'
                WHEN AF.COD_CAUSA_AFAST = 7 THEN
                    'EM FÉRIAS'
                WHEN AF.COD_CAUSA_AFAST IN (3, 6) THEN
                    'AFASTADO TEMP'
                WHEN AF.COD_CAUSA_AFAST = 4
                 AND NVL(AF.DATA_FIM, DATE '2999-12-31') = DATE '2999-12-31' THEN
                    'PODERÁ RETORNAR'
                ELSE
                    'EM ATIVIDADE'
            END AS DES_STATUS_AFAST,
            AF.DATA_INICIO AS DATA_INI_AFAST,
            AF.DATA_FIM AS DATA_FIM_AFAST,
            ROW_NUMBER() OVER (
                PARTITION BY B.COD_CONTRATO
                ORDER BY
                    CASE
                        WHEN AF.COD_CAUSA_AFAST IS NOT NULL
                         AND NVL(AF.COD_CAUSA_AFAST, 0) <> 0 THEN 1
                        ELSE 2
                    END,
                    NVL(AF.DATA_FIM, DATE '2999-12-31') DESC,
                    AF.DATA_INICIO DESC
            ) AS RN
        FROM BASE_APRENDIZ B
        CROSS JOIN PARAMS P
        LEFT JOIN RHFP0306 AF
               ON AF.COD_CONTRATO = B.COD_CONTRATO
              AND P.DATA_FIM BETWEEN AF.DATA_INICIO
                                 AND NVL(AF.DATA_FIM, DATE '2999-12-31')
        LEFT JOIN RHFP0100 AFN
               ON AFN.COD_CAUSA_AFAST = AF.COD_CAUSA_AFAST
    ) X
    WHERE X.RN = 1
),

APRENDIZES_ATIVOS AS (
    SELECT
        B.DES_STATUS,
        B.COD_UNIDADE,
        B.DES_UNIDADE,
        B.COD_ORGANOGRAMA,
        B.COD_REDE,
        B.DES_REDE,
        B.COD_TIPO,
        B.DES_TIPO,
        1 AS COD_STATUS_REL,
        'ATIVO' AS STATUS_REL,
        B.COD_CONTRATO,
        B.DES_PESSOA,
        B.DATA_ADMISSAO,
        B.DATA_DEMISSAO,
        B.COD_VINCULO_EMPREG,
        CE.DATA_INI_EXP,
        CE.DATA_FIM_EXP,
        CE.DIAS_CONTRATO,
        CE.DATA_AVALIACAO,
        CE.IND_AVALIACAO,
        CE.NUM_DIAS,
        CE.IND_AVALIACOES,
        CE.NOME_TIPO_CONTRATO,
        CE.DURACAO_CONTRATO,
        SA.COD_AFAST,
        SA.DES_AFAST,
        SA.DES_STATUS_AFAST,
        SA.DATA_INI_AFAST,
        SA.DATA_FIM_AFAST,
        ROW_NUMBER() OVER (
            PARTITION BY B.COD_ORGANOGRAMA, B.COD_UNIDADE
            ORDER BY B.DES_PESSOA, B.COD_CONTRATO
        ) AS ORDEM_PESSOA
    FROM BASE_APRENDIZ B
    CROSS JOIN PARAMS P
    LEFT JOIN CONTRATO_EXPERIENCIA CE
           ON CE.COD_CONTRATO = B.COD_CONTRATO
          AND CE.RN = 1
    LEFT JOIN STATUS_AFASTADOS SA
           ON SA.COD_CONTRATO = B.COD_CONTRATO
    WHERE B.DATA_ADMISSAO <= P.DATA_FIM
      AND (B.DATA_DEMISSAO IS NULL OR B.DATA_DEMISSAO > P.DATA_FIM)
),

APRENDIZES_DEMITIDOS_PERIODO AS (
    SELECT
        B.DES_STATUS,
        B.COD_UNIDADE,
        B.DES_UNIDADE,
        B.COD_ORGANOGRAMA,
        B.COD_REDE,
        B.DES_REDE,
        B.COD_TIPO,
        B.DES_TIPO,
        2 AS COD_STATUS_REL,
        'DEMITIDO' AS STATUS_REL,
        B.COD_CONTRATO,
        B.DES_PESSOA,
        B.DATA_ADMISSAO,
        B.DATA_DEMISSAO,
        B.COD_VINCULO_EMPREG,
        ROW_NUMBER() OVER (
            PARTITION BY B.COD_ORGANOGRAMA, B.COD_UNIDADE
            ORDER BY B.DATA_DEMISSAO, B.DES_PESSOA, B.COD_CONTRATO
        ) AS ORDEM_PESSOA
    FROM BASE_APRENDIZ B
    CROSS JOIN PARAMS P
    WHERE B.DATA_DEMISSAO BETWEEN P.DATA_INICIO AND P.DATA_FIM
),



DETALHE_RELATORIO AS (
    /* ATIVOS */
    SELECT
        A.DES_STATUS,
        A.COD_ORGANOGRAMA,
        A.COD_UNIDADE,
        A.DES_UNIDADE AS UNIDADE,
        A.COD_REDE,
        A.DES_REDE AS REDE,
        A.COD_TIPO,
        A.DES_TIPO AS TIPO,

        A.COD_STATUS_REL,
        A.STATUS_REL,
        A.COD_CONTRATO,
        A.DES_PESSOA,
        A.COD_CONTRATO || ' - ' || A.DES_PESSOA AS APRENDIZ,
        A.DATA_ADMISSAO AS DT_ADMISSAO,
        A.DATA_DEMISSAO AS DT_DEMISSAO,
        A.COD_VINCULO_EMPREG AS VINCULO,
        A.DATA_INI_EXP AS DT_INI_CONTRATO_EXP,
        A.DATA_FIM_EXP AS DT_FIM_CONTRATO_EXP,
        A.DIAS_CONTRATO,
        A.NOME_TIPO_CONTRATO,
        A.DURACAO_CONTRATO,
        A.COD_AFAST,
        A.DES_AFAST,
        A.DES_STATUS_AFAST AS STATUS_AFAST,
        A.DATA_INI_AFAST AS DT_INI_AFAST,
        A.DATA_FIM_AFAST AS DT_FIM_AFAST,
        A.ORDEM_PESSOA
    FROM APRENDIZES_ATIVOS A
    WHERE (A.COD_TIPO = :TIPO OR :TIPO = 0)
      AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
      AND (A.COD_REDE = :REDE OR :REDE = 0)

    UNION ALL

    /* DEMITIDOS */
    SELECT
        D.DES_STATUS,
        D.COD_ORGANOGRAMA,
        D.COD_UNIDADE,
        D.DES_UNIDADE AS UNIDADE,
        D.COD_REDE,
        D.DES_REDE AS REDE,
        D.COD_TIPO,
        D.DES_TIPO AS TIPO,

        D.COD_STATUS_REL,
        D.STATUS_REL,
        D.COD_CONTRATO,
        D.DES_PESSOA,
        D.COD_CONTRATO || ' - ' || D.DES_PESSOA AS APRENDIZ,
        D.DATA_ADMISSAO AS DT_ADMISSAO,
        D.DATA_DEMISSAO AS DT_DEMISSAO,
        D.COD_VINCULO_EMPREG AS VINCULO,
        CAST(NULL AS DATE) AS DT_INI_CONTRATO_EXP,
        CAST(NULL AS DATE) AS DT_FIM_CONTRATO_EXP,
        CAST(NULL AS NUMBER) AS DIAS_CONTRATO,
        CAST(NULL AS VARCHAR2(200)) AS NOME_TIPO_CONTRATO,
        CAST(NULL AS NUMBER) AS DURACAO_CONTRATO,
        CAST(NULL AS NUMBER) AS COD_AFAST,
        CAST(NULL AS VARCHAR2(200)) AS DES_AFAST,
        CAST(NULL AS VARCHAR2(200)) AS STATUS_AFAST,
        CAST(NULL AS DATE) AS DT_INI_AFAST,
        CAST(NULL AS DATE) AS DT_FIM_AFAST,
        D.ORDEM_PESSOA
    FROM APRENDIZES_DEMITIDOS_PERIODO D
    WHERE (D.COD_TIPO = :TIPO OR :TIPO = 0)
      AND (D.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
      AND (D.COD_REDE = :REDE OR :REDE = 0)
)

SELECT
    D.DES_STATUS,
    D.COD_ORGANOGRAMA,
    D.COD_UNIDADE,
    D.UNIDADE,
    D.COD_REDE,
    D.REDE,
    D.COD_TIPO,
    D.TIPO,

    D.COD_STATUS_REL,
    D.STATUS_REL,
    D.COD_CONTRATO,
    D.DES_PESSOA,
    D.APRENDIZ,
    D.DT_ADMISSAO,
    D.DT_DEMISSAO,
    D.VINCULO,
    D.DT_INI_CONTRATO_EXP,
    D.DT_FIM_CONTRATO_EXP,
    D.DIAS_CONTRATO,
    D.NOME_TIPO_CONTRATO,
    D.DURACAO_CONTRATO,
    D.COD_AFAST,
    D.DES_AFAST,
    D.STATUS_AFAST,
    D.DT_INI_AFAST,
    D.DT_FIM_AFAST,

    ROW_NUMBER() OVER (
        PARTITION BY D.COD_ORGANOGRAMA, D.COD_UNIDADE
        ORDER BY D.DES_PESSOA, D.COD_STATUS_REL, D.COD_CONTRATO
    ) AS SEQ_UNIDADE

FROM DETALHE_RELATORIO D
ORDER BY
    D.COD_UNIDADE,
    D.COD_ORGANOGRAMA,
    D.DES_PESSOA,
    D.COD_STATUS_REL,
    D.COD_CONTRATO
