WITH
PARAMS AS (
    SELECT
        TRUNC(CAST(:DATA_INICIO AS DATE)) AS DATA_INICIO,
        TRUNC(CAST(:DATA_FIM    AS DATE)) AS DATA_FIM
    FROM DUAL
),

/* =========================================================
   1. BASE-MÃE OFICIAL
   Mesma lógica do Perfil / RE7001.
========================================================= */
BASE_PERFIL AS (
    SELECT *
    FROM (
        SELECT
            V.COD_PESSOA,
            V.COD_CONTRATO,
            V.DES_PESSOA,
            V.STATUS,
            V.DATA_ADMISSAO,
            V.DATA_DEMISSAO,
            V.DATA_AVANCO,
            V.DATA_NASCIMENTO,
            V.IDADE,
            V.IND_DEFICIENCIA,
            V.SEXO,
            NVL(V.COD_AFAST, 0) AS COD_AFAST,
            V.DES_AFAST,
            V.STATUS_AFAST,
            V.COD_EMP,
            V.DES_EMPRESA,
            V.COD_REDE_LOCAL,
            V.DES_REDE_LOCAL,

            ROW_NUMBER() OVER (
                PARTITION BY V.COD_CONTRATO
                ORDER BY
                    NVL(V.DATA_DEMISSAO, DATE '2999-12-31') DESC,
                    V.DATA_ADMISSAO DESC,
                    V.COD_CONTRATO DESC
            ) AS RN_CONTRATO

        FROM V_DADOS_COLAB_AVT V
        CROSS JOIN PARAMS P
        WHERE V.COD_EMP = 8
          AND TRUNC(V.DATA_ADMISSAO) <= P.DATA_FIM
          AND (
                 V.DATA_DEMISSAO IS NULL
              OR TRUNC(V.DATA_DEMISSAO) >= P.DATA_FIM
          )
    )
    WHERE RN_CONTRATO = 1
),

/* =========================================================
   2. ORGANOGRAMA OFICIAL NA REFERÊNCIA
   Não usa VH_EST_ORG_CONTRATO_AVT.
   Usa RHFP0310 + V_EST_ORG_ALTER_AVT, como ajustamos no RE7001.
========================================================= */
ORG_REF AS (
    SELECT *
    FROM (
        SELECT
            H.COD_CONTRATO,

            H.DATA_INICIO AS DATA_INI_ORG,
            H.DATA_FIM    AS DATA_FIM_ORG,
            H.COD_ORGANOGRAMA,

            A.COD_ORG_2 AS COD_EMP,
            A.EDICAO_ORG_2 AS EDICAO_EMP,
            A.NOME2 AS DES_EMP,

            A.EDICAO_ORG AS COD_UNIDADE,
            A.NOME_ORGANOGRAMA_B AS DES_UNIDADE,

            A.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_REF,
            A.NOME_ORGANOGRAMA,
            A.NOME_ORGANOGRAMA_A,
            A.COD_NIVEL_ORG,
            A.COD_ORGANOGRAMA_SUB,
            A.EDICAO,

            A.DATA_INICIO,
            A.DATA_FIM,

            A.COD_ORG_1,
            A.EDICAO_ORG_1,
            A.NOME1,

            A.COD_ORG_2,
            A.EDICAO_ORG_2,
            A.NOME2,

            A.COD_ORG_3,
            A.EDICAO_ORG_3,
            A.NOME3,

            A.COD_ORG_4,
            A.EDICAO_ORG_4,
            A.NOME4,

            A.COD_ORG_5,
            A.EDICAO_ORG_5,
            A.NOME5,

            A.COD_ORG_6,
            A.EDICAO_ORG_6,
            A.NOME6,

            A.COD_ORG_7,
            A.EDICAO_ORG_7,
            A.NOME7,

            A.COD_ORG_8,
            A.EDICAO_ORG_8,
            A.NOME8,

            A.COD_REDE,
            A.DES_REDE,

            CASE
                WHEN A.COD_ORG_2 = 8 THEN
                    CASE
                        WHEN A.COD_ORG_3 = 9  THEN 2
                        WHEN A.COD_ORG_3 = 21 THEN 3
                        ELSE 1
                    END
                ELSE 4
            END AS COD_TIPO,

            CASE
                WHEN A.COD_ORG_2 = 8 THEN
                    CASE
                        WHEN A.COD_ORG_3 = 9  THEN 'SETOR'
                        WHEN A.COD_ORG_3 = 21 THEN 'DEPÓSITO'
                        ELSE 'LOJA'
                    END
                ELSE 'COLIGADA'
            END AS DES_TIPO,

            ROW_NUMBER() OVER (
                PARTITION BY H.COD_CONTRATO
                ORDER BY
                    CASE
                        WHEN P.DATA_FIM BETWEEN TRUNC(H.DATA_INICIO)
                                           AND NVL(TRUNC(H.DATA_FIM), DATE '2999-12-31')
                        THEN 0 ELSE 1
                    END,

                    CASE
                        WHEN P.DATA_FIM BETWEEN TRUNC(A.DATA_INICIO)
                                           AND NVL(TRUNC(A.DATA_FIM), DATE '2999-12-31')
                        THEN 0 ELSE 1
                    END,

                    H.DATA_INICIO DESC,
                    A.DATA_INICIO DESC,
                    NVL(H.DATA_FIM, DATE '2999-12-31') DESC,
                    NVL(A.DATA_FIM, DATE '2999-12-31') DESC
            ) AS RN_ORG

        FROM RHFP0310 H
        INNER JOIN V_EST_ORG_ALTER_AVT A
            ON A.COD_ORGANOGRAMA = H.COD_ORGANOGRAMA
        CROSS JOIN PARAMS P
        WHERE A.COD_ORG_2 = 8
          AND TRUNC(H.DATA_INICIO) <= P.DATA_FIM
          AND TRUNC(A.DATA_INICIO) <= P.DATA_FIM
    )
    WHERE RN_ORG = 1
),

/* =========================================================
   3. CARGO NA REFERÊNCIA
   LEFT JOIN para não derrubar colaborador.
========================================================= */
CARGO_REF AS (
    SELECT *
    FROM (
        SELECT
            F.COD_CONTRATO,
            F.COD_FUNCAO,
            F.DES_FUNCAO,
            ROW_NUMBER() OVER (
                PARTITION BY F.COD_CONTRATO
                ORDER BY
                    F.DATA_INI_CLH DESC,
                    NVL(F.DATA_FIM_CLH, DATE '2999-12-31') DESC
            ) AS RN_CARGO
        FROM VH_CARGO_CONTRATO_AVT F
        CROSS JOIN PARAMS P
        WHERE TRUNC(F.DATA_INI_CLH) <= P.DATA_FIM
          AND NVL(TRUNC(F.DATA_FIM_CLH), DATE '2999-12-31') >= P.DATA_FIM
    )
    WHERE RN_CARGO = 1
),

/* =========================================================
   4. HORAS BASE NA REFERÊNCIA
   LEFT JOIN para não derrubar colaborador.
========================================================= */
HORAS_REF AS (
    SELECT *
    FROM (
        SELECT
            H.COD_CONTRATO,
            H.HR_BASE_MES,
            ROW_NUMBER() OVER (
                PARTITION BY H.COD_CONTRATO
                ORDER BY
                    H.DATA_INI_HR DESC,
                    NVL(H.DATA_FIM_HR, DATE '2999-12-31') DESC
            ) AS RN_HR
        FROM VH_HIST_HORAS_COLAB_AVT H
        CROSS JOIN PARAMS P
        WHERE TRUNC(H.DATA_INI_HR) <= P.DATA_FIM
          AND NVL(TRUNC(H.DATA_FIM_HR), DATE '2999-12-31') >= P.DATA_FIM
    )
    WHERE RN_HR = 1
),

/* =========================================================
   5. CONTRATOS FINAL
   Mantém os nomes de colunas esperados pelo restante do SQL.
========================================================= */
CONTRATOS AS (
    SELECT DISTINCT
           CT.STATUS,
           CT.COD_CONTRATO,
           CT.DES_PESSOA,
           CT.DATA_ADMISSAO,
           CT.DATA_DEMISSAO,

           TRUNC(MONTHS_BETWEEN(P.DATA_FIM, CT.DATA_AVANCO) / 12) ||
           ' ano(s)' || ' e ' ||
           TRUNC(MOD(MONTHS_BETWEEN(P.DATA_FIM, CT.DATA_AVANCO), 12)) ||
           ' mês(es)' AS TEMPO_EMPRESA,

           CT.DATA_NASCIMENTO,
           CT.IDADE,

           FN.COD_FUNCAO,
           NVL(FN.DES_FUNCAO, 'FUNÇÃO NÃO INFORMADA') AS DES_FUNCAO,

           NVL(HR.HR_BASE_MES, 0) AS HR_BASE_MES,

           CT.IND_DEFICIENCIA,
           CT.SEXO,

           ORG.COD_EMP,
           ORG.EDICAO_EMP,
           ORG.DES_EMP,

           ORG.COD_ORGANOGRAMA,
           ORG.COD_UNIDADE,
           ORG.DES_UNIDADE,
           ORG.NOME_ORGANOGRAMA,

           CASE
               WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.EDICAO_ORG_3
               ELSE ORG.COD_UNIDADE
           END AS COD_FILIAL,

           CASE
               WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.NOME3
               ELSE ORG.DES_UNIDADE
           END AS DES_FILIAL,

           CASE
               WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.EDICAO_ORG_4
               ELSE ORG.COD_UNIDADE
           END AS COD_DIVISAO,

           CASE
               WHEN ORG.COD_TIPO IN (2, 3) THEN ORG.NOME4
               ELSE ORG.DES_UNIDADE
           END AS DES_DIVISAO,

           ORG.EDICAO,
           ORG.COD_REDE,
           ORG.DES_REDE,
           ORG.COD_TIPO,
           ORG.DES_TIPO,

           CT.COD_AFAST,
           CT.DES_AFAST,
           CT.STATUS_AFAST

    FROM BASE_PERFIL CT
    CROSS JOIN PARAMS P
    LEFT JOIN ORG_REF ORG
        ON ORG.COD_CONTRATO = CT.COD_CONTRATO
    LEFT JOIN CARGO_REF FN
        ON FN.COD_CONTRATO = CT.COD_CONTRATO
    LEFT JOIN HORAS_REF HR
        ON HR.COD_CONTRATO = CT.COD_CONTRATO

    WHERE ORG.COD_EMP = 8
),

/* =========================================================
   6. STATUS DE AFASTAMENTO
   Agora vem da mesma base, sem outro join que derruba gente.
========================================================= */
STATUS_AFASTADOS AS (
    SELECT DISTINCT
           A.COD_EMP,
           A.COD_CONTRATO,
           A.COD_UNIDADE,
           NVL(A.COD_AFAST, 0) AS STATUS_AFAST,
           A.DES_AFAST
    FROM CONTRATOS A
),

HORAS_REALIZADAS_UNI AS (
SELECT ORG.COD_EMP,
       ORG.COD_ORGANOGRAMA,
       ORG.COD_UNIDADE,
       ORG.COD_REDE,
       ORG.COD_TIPO,
       SUM(A.NUM_HORAS) AS HORAS_REAIS
  FROM RHAF1123 A
  LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
  LEFT JOIN V_DADOS_CONTRATO_AVT CT ON A.COD_CONTRATO = CT.COD_CONTRATO
 WHERE A.DATA_OCORRENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND A.COD_OCORRENCIA = 2
   AND ORG.COD_EMP = 8
   AND (ORG.COD_TIPO = :TIPO OR :TIPO = 0)
   AND (ORG.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
   AND (ORG.COD_REDE = :REDE OR :REDE = 0)
 GROUP BY ORG.COD_ORGANOGRAMA,
          ORG.COD_UNIDADE,
          ORG.COD_REDE,
          ORG.COD_TIPO,
          ORG.COD_EMP

),


CONTADORES_UNI AS (
SELECT A.COD_TIPO,
       A.COD_ORGANOGRAMA,
       A.COD_UNIDADE  AS UNIDADE_CONT,
       A.DES_UNIDADE,
       A.COD_REDE,
       A.DES_REDE,
       A.COD_EMP,
       A.DES_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_220,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_200,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_195,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_180,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_165,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_160,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_150,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_140,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_125,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_120,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_110,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_105,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_100,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_80,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_60,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_40,
       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                             AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_COLAB_HRS,

       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_ATV,
       COUNT(DISTINCT CASE WHEN A.IND_DEFICIENCIA = 'S' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_PCD,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST NOT IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_AFSTO,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST = 3 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MATER,

       COUNT(DISTINCT CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM,
       ROUND((COUNT(CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM,
       COUNT(DISTINCT CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC,
       ROUND((COUNT(CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC,

       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_APRE,

       COUNT(DISTINCT A.COD_CONTRATO) AS QTD_TOT_COLAB

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
  WHERE (A.COD_TIPO = :TIPO OR :TIPO = 0)
    AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
    AND (A.COD_REDE = :REDE OR :REDE = 0)
    --AND (A.COD_EMP = :EMPRESA OR :EMPRESA = 0)
  GROUP BY A.COD_UNIDADE,
           A.DES_UNIDADE,
           A.COD_REDE,
           A.DES_REDE,
           A.COD_EMP,
           A.DES_EMP,
           A.COD_TIPO,
           A.COD_ORGANOGRAMA
  ORDER BY A.COD_TIPO, A.COD_REDE, A.COD_UNIDADE
),


SOMAS_HORAS_BASE_UNI AS (
SELECT A.COD_ORGANOGRAMA,
    A.COD_REDE,
    A.COD_TIPO,
    SUM(CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 220 ELSE 0 END) AS SUM_220,
    SUM(CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 200 ELSE 0 END) AS SUM_200,
    SUM(CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 195 ELSE 0 END) AS SUM_195,
    SUM(CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 180 ELSE 0 END) AS SUM_180,
    SUM(CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 165 ELSE 0 END) AS SUM_165,
    SUM(CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 160 ELSE 0 END) AS SUM_160,
    SUM(CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 150 ELSE 0 END) AS SUM_150,
    SUM(CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 140 ELSE 0 END) AS SUM_140,
    SUM(CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 125 ELSE 0 END) AS SUM_125,
    SUM(CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 120 ELSE 0 END) AS SUM_120,
    SUM(CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 110 ELSE 0 END) AS SUM_110,
    SUM(CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 105 ELSE 0 END) AS SUM_105,
    SUM(CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 100 ELSE 0 END) AS SUM_100,
    SUM(CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 80 ELSE 0 END) AS SUM_80,
    SUM(CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 60 ELSE 0 END) AS SUM_60,
    SUM(CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 40 ELSE 0 END) AS SUM_40,

    SUM(CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                               AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.HR_BASE_MES ELSE TO_CHAR(0) END) AS SUM_TOT_HRS

    --ROUND((SUM(CASE WHEN A.SEXO = 'M' THEN 1 ELSE 0 END) / COUNT(*) * 100), 2) AS PERC_MASC

FROM CONTRATOS A
LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
WHERE (A.COD_TIPO = :TIPO OR :TIPO = 0)
  AND (A.COD_UNIDADE = :UNIDADE OR :UNIDADE = 0)
  AND (A.COD_REDE = :REDE OR :REDE = 0)
  --AND (A.COD_EMP = :EMPRESA OR :EMPRESA = 0)
GROUP BY A.COD_ORGANOGRAMA,
         A.COD_TIPO,
         A.COD_REDE
),



HORAS_REALIZADAS_REDE AS (
SELECT ORG.COD_EMP,
       ORG.COD_REDE AS REDE_HR,
       ORG.COD_TIPO,
       SUM(A.NUM_HORAS) AS HORAS_REAIS_RD
  FROM RHAF1123 A
  LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
  LEFT JOIN V_DADOS_CONTRATO_AVT CT ON A.COD_CONTRATO = CT.COD_CONTRATO
 WHERE A.DATA_OCORRENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND A.COD_OCORRENCIA = 2
   AND ORG.COD_EMP = 8
   --AND (ORG.COD_REDE = :REDE OR :REDE = 0)
 GROUP BY ORG.COD_REDE, ORG.COD_TIPO, ORG.COD_EMP

),

CONTADORES_REDE AS (
SELECT A.COD_REDE AS REDE_CONT,
       A.DES_REDE AS DES_REDE_CONT,
       A.COD_TIPO,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_220_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_200_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_195_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_180_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_165_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_160_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_150_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_140_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_125_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_120_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_110_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_105_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_100_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_80_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_60_RD,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_40_RD,
       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                             AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_COLAB_HRS_RD,

       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_ATV_RD,
       COUNT(DISTINCT CASE WHEN A.IND_DEFICIENCIA = 'S' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_PCD_RD,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST NOT IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_AFSTO_RD,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST = 3 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MATER_RD,

       COUNT(DISTINCT CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM_RD,
       ROUND((COUNT(CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM_RD,
       COUNT(DISTINCT CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC_RD,
       ROUND((COUNT(CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC_RD,

       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_APRE_RD,

       COUNT(DISTINCT A.COD_CONTRATO) AS QTD_TOT_COLAB_RD

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
  --WHERE (A.COD_REDE = :REDE OR :REDE = 0)
  GROUP BY A.COD_REDE,
           A.DES_REDE,
           A.COD_TIPO
  ORDER BY A.COD_TIPO, A.COD_REDE
),

SOMAS_HORAS_BASE_REDE AS (
SELECT
    A.COD_REDE AS REDE_SUM,
    A.COD_TIPO,
    SUM(CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 220 ELSE 0 END) AS SUM_220_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 200 ELSE 0 END) AS SUM_200_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 195 ELSE 0 END) AS SUM_195_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 180 ELSE 0 END) AS SUM_180_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 165 ELSE 0 END) AS SUM_165_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 160 ELSE 0 END) AS SUM_160_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 150 ELSE 0 END) AS SUM_150_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 140 ELSE 0 END) AS SUM_140_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 125 ELSE 0 END) AS SUM_125_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 120 ELSE 0 END) AS SUM_120_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 110 ELSE 0 END) AS SUM_110_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 105 ELSE 0 END) AS SUM_105_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 100 ELSE 0 END) AS SUM_100_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 80 ELSE 0 END) AS SUM_80_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 60 ELSE 0 END) AS SUM_60_RD,
    SUM(CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 40 ELSE 0 END) AS SUM_40_RD,

    SUM(CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                               AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.HR_BASE_MES ELSE TO_CHAR(0) END) AS SUM_TOT_HRS_RD

    --ROUND((SUM(CASE WHEN A.SEXO = 'M' THEN 1 ELSE 0 END) / COUNT(*) * 100), 2) AS PERC_MASC

FROM CONTRATOS A
LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
--WHERE (A.COD_REDE = :REDE OR :REDE = 0)
GROUP BY A.COD_REDE,
         A.COD_TIPO
ORDER BY A.COD_TIPO, A.COD_REDE
),



HORAS_REALIZADAS_EMP AS (
SELECT ORG.COD_EMP AS EMPRESA_HR,
       --A.COD_CONTRATO,
       SUM(A.NUM_HORAS) AS HORAS_REAIS_EMP
  FROM RHAF1123 A
  LEFT JOIN VH_EST_ORG_CONTRATO_AVT ORG ON A.COD_CONTRATO =
                                           ORG.COD_CONTRATO
  LEFT JOIN V_DADOS_CONTRATO_AVT CT ON A.COD_CONTRATO = CT.COD_CONTRATO
 WHERE A.DATA_OCORRENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
   AND ((:DATA_FIM BETWEEN CT.DATA_ADMISSAO AND CT.DATA_DEMISSAO) OR
        (CT.DATA_ADMISSAO <= :DATA_FIM AND CT.DATA_DEMISSAO IS NULL))
   AND :DATA_FIM BETWEEN ORG.DATA_INI_ORG AND ORG.DATA_FIM_ORG
   AND A.COD_OCORRENCIA = 2
   AND ORG.COD_EMP = 8
 GROUP BY ORG.COD_EMP

),


CONTADORES_EMP AS (
SELECT A.COD_EMP AS EMPRESA_CONT,
       A.DES_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_22_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_200_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_195_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_180_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_165_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_160_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_150_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_140_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_125_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_120_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_110_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_105_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                    AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_100_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_80_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_60_EMP,
       COUNT(DISTINCT CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                                   AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_40_EMP,
       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                             AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.COD_CONTRATO END) AS QTD_COLAB_HRS_EMP,

       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_ATV_EMP,
       COUNT(DISTINCT CASE WHEN A.IND_DEFICIENCIA = 'S' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_PCD_EMP,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST NOT IN (0, 6, 7) AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_AFSTO_EMP,
       COUNT(DISTINCT CASE WHEN B.STATUS_AFAST = 3 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MATER_EMP,

       COUNT(DISTINCT CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_FEM_EMP,
       ROUND((COUNT(CASE WHEN A.SEXO = 'F' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_FEM_EMP,
       COUNT(DISTINCT CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_COLAB_MASC_EMP,
       ROUND((COUNT(CASE WHEN A.SEXO = 'M' AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%' THEN 1 END) * 100.0 / COUNT(*)), 2) AS PERC_MASC_EMP,

       COUNT(DISTINCT CASE WHEN A.DES_FUNCAO LIKE '%APRENDIZ%' THEN A.COD_CONTRATO END) AS QTD_APRE_EMP,

       COUNT(DISTINCT A.COD_CONTRATO) AS QTD_TOT_COLAB_EMP

  FROM CONTRATOS A
  LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
  --WHERE (A.COD_EMP = :EMPRESA OR :EMPRESA = 0)
  GROUP BY A.COD_EMP,
           A.DES_EMP
  ORDER BY A.COD_EMP
),

SOMAS_HORAS_BASE_EMP AS (
SELECT
    A.COD_EMP AS EMPRESA_SUM,
    SUM(CASE WHEN A.HR_BASE_MES = 220 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 220 ELSE 0 END) AS SUM_220_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 200 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 200 ELSE 0 END) AS SUM_200_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 195 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 195 ELSE 0 END) AS SUM_195_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 180 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 180 ELSE 0 END) AS SUM_180_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 165 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 165 ELSE 0 END) AS SUM_165_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 160 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 160 ELSE 0 END) AS SUM_160_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 150 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 150 ELSE 0 END) AS SUM_150_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 140 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 140 ELSE 0 END) AS SUM_140_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 125 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 125 ELSE 0 END) AS SUM_125_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 120 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 120 ELSE 0 END) AS SUM_120_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 110 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 110 ELSE 0 END) AS SUM_110_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 105 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 105 ELSE 0 END) AS SUM_105_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 100 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                      AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 100 ELSE 0 END) AS SUM_100_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 80 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 80 ELSE 0 END) AS SUM_80_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 60 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 60 ELSE 0 END) AS SUM_60_EMP,
    SUM(CASE WHEN A.HR_BASE_MES = 40 AND A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                                     AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN 40 ELSE 0 END) AS SUM_40_EMP,

    SUM(CASE WHEN A.DES_FUNCAO NOT LIKE '%APRENDIZ%'
                               AND (:AFASTADOS = 'S' OR (:AFASTADOS = 'N' AND B.STATUS_AFAST IN (0, 6, 7))) THEN A.HR_BASE_MES ELSE TO_CHAR(0) END) AS SUM_TOT_HRS_EMP

    --ROUND((SUM(CASE WHEN A.SEXO = 'M' THEN 1 ELSE 0 END) / COUNT(*) * 100), 2) AS PERC_MASC

FROM CONTRATOS A
LEFT JOIN STATUS_AFASTADOS B ON A.COD_CONTRATO = B.COD_CONTRATO
--WHERE (A.COD_EMP = :EMPRESA OR :EMPRESA = 0)

GROUP BY A.COD_EMP

),

HORAS_PONTO_UNI AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A1.COD_TIPO, A1.COD_REDE, A1.COD_ORGANOGRAMA) AS RN, A1.*
  FROM HORAS_REALIZADAS_UNI A1
),

UNI_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A.COD_TIPO, A.COD_REDE, A.UNIDADE_CONT, A.COD_ORGANOGRAMA) AS RN, A.*
  FROM CONTADORES_UNI A
),

SOMAS_HORAS_BASE_UNI_NUM AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY A.COD_TIPO, A.COD_REDE, A.COD_ORGANOGRAMA) AS RN,
    A.*
  FROM SOMAS_HORAS_BASE_UNI A
),

HORAS_PONTO_REDE AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A2.COD_TIPO, A2.REDE_HR) AS RN, A2.*
  FROM HORAS_REALIZADAS_REDE A2
),


REDE_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY B.COD_TIPO, B.REDE_CONT) AS RN, B.*
  FROM CONTADORES_REDE B
),

SOMAS_HORAS_BASE_REDE_NUM AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY B.COD_TIPO, B.REDE_SUM) AS RN,
    B.*
  FROM SOMAS_HORAS_BASE_REDE B
),


HORAS_PONTO_EMP AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A3.EMPRESA_HR) AS RN, A3.*
  FROM HORAS_REALIZADAS_EMP A3
),

EMP_NUM AS (
  SELECT ROW_NUMBER() OVER (ORDER BY EMPRESA_CONT) AS RN, C.*
  FROM CONTADORES_EMP C
),

SOMAS_HORAS_BASE_EMP_NUM AS (
  SELECT
    ROW_NUMBER() OVER (ORDER BY EMPRESA_SUM) AS RN,
    C.*
  FROM SOMAS_HORAS_BASE_EMP C
)


SELECT UNI.COD_TIPO,
       UNI.COD_ORGANOGRAMA,
       UNI.UNIDADE_CONT,
       UNI.DES_UNIDADE,
       UNI.COD_REDE,
       UNI.DES_REDE,
       UNI.COD_EMP,
       UNI.DES_EMP,
       UNI.QTD_220,
       SU.SUM_220,
       UNI.QTD_200,
       SU.SUM_200,
       UNI.QTD_195,
       SU.SUM_195,
       UNI.QTD_180,
       SU.SUM_180,
       UNI.QTD_165,
       SU.SUM_165,
       UNI.QTD_160,
       SU.SUM_160,
       UNI.QTD_150,
       SU.SUM_150,
       UNI.QTD_140,
       SU.SUM_140,
       UNI.QTD_125,
       SU.SUM_125,
       UNI.QTD_120,
       SU.SUM_120,
       UNI.QTD_110,
       SU.SUM_110,
       UNI.QTD_105,
       SU.SUM_105,
       UNI.QTD_100,
       SU.SUM_100,
       UNI.QTD_80,
       SU.SUM_80,
       UNI.QTD_60,
       SU.SUM_60,
       UNI.QTD_40,
       SU.SUM_40,

       SU.SUM_TOT_HRS,

       REPLACE(TO_CHAR(HPU.HORAS_REAIS, 'FM9999990.00'), '.', ',') AS HRS_REAIS,
       HPU.HORAS_REAIS,

       UNI.QTD_COLAB_HRS,
       UNI.QTD_COLAB_ATV,
       UNI.QTD_PCD,
       UNI.QTD_AFSTO,
       UNI.QTD_COLAB_MATER,

       UNI.QTD_COLAB_FEM,
       UNI.PERC_FEM,
       UNI.QTD_COLAB_MASC,
       UNI.PERC_MASC,

       UNI.QTD_APRE,

       UNI.QTD_TOT_COLAB,

       REDE.REDE_CONT,
       REDE.DES_REDE_CONT,
       REDE.COD_TIPO,
       REDE.QTD_220_RD,
       REDE.QTD_200_RD,
       REDE.QTD_195_RD,
       REDE.QTD_180_RD,
       REDE.QTD_165_RD,
       REDE.QTD_160_RD,
       REDE.QTD_150_RD,
       REDE.QTD_140_RD,
       REDE.QTD_125_RD,
       REDE.QTD_120_RD,
       REDE.QTD_110_RD,
       REDE.QTD_105_RD,
       REDE.QTD_100_RD,
       REDE.QTD_80_RD,
       REDE.QTD_60_RD,
       REDE.QTD_40_RD,

       REDE.QTD_COLAB_HRS_RD,
       REDE.QTD_COLAB_ATV_RD,
       REDE.QTD_PCD_RD,
       REDE.QTD_AFSTO_RD,
       REDE.QTD_COLAB_MATER_RD,

       REDE.QTD_COLAB_FEM_RD,
       REDE.PERC_FEM_RD,
       REDE.QTD_COLAB_MASC_RD,
       REDE.PERC_MASC_RD,

       REDE.QTD_APRE_RD,

       REDE.QTD_TOT_COLAB_RD,
       SR.*,
       REPLACE(TO_CHAR(HPR.HORAS_REAIS_RD, 'FM9999990.00'), '.', ',') AS HRS_REAIS_RD,
       HPR.HORAS_REAIS_RD,

       EMP.*,
       SE.*,
       REPLACE(TO_CHAR(HPE.HORAS_REAIS_EMP, 'FM9999990.00'), '.', ',') AS HRS_REAIS_EMP,
       HPE.HORAS_REAIS_EMP,

       :DATA_INICIO  || ' - ' || :DATA_FIM AS REFERENCIA,
       'TIPO: '      || :TIPO     || ' | ' ||
       'UNIDADE: '   || :UNIDADE  || ' | ' ||
       'REDE: '      || :REDE || ' | ' ||
       'AFASTADOS? ' || :AFASTADOS AS PARAMETROS_USADOS


  FROM UNI_NUM UNI
  FULL OUTER JOIN REDE_NUM REDE ON UNI.RN = REDE.RN AND 1 = 1
  FULL OUTER JOIN EMP_NUM EMP ON UNI.RN = EMP.RN
  FULL OUTER JOIN SOMAS_HORAS_BASE_UNI_NUM SU ON UNI.COD_ORGANOGRAMA = SU.COD_ORGANOGRAMA
  FULL OUTER JOIN SOMAS_HORAS_BASE_REDE_NUM SR ON REDE.RN = SR.RN
  FULL OUTER JOIN SOMAS_HORAS_BASE_EMP_NUM SE ON UNI.RN = SE.RN
  FULL OUTER JOIN HORAS_PONTO_UNI HPU ON UNI.RN = HPU.RN
  FULL OUTER JOIN HORAS_PONTO_REDE HPR ON REDE.RN = HPR.RN
  FULL OUTER JOIN HORAS_PONTO_EMP HPE ON UNI.RN = HPE.RN
ORDER BY NVL(UNI.RN, REDE.RN)


