SELECT A.REGIAO,
       SUM(A.VLR_VENDA_ORC) VENDA_ORCADO,
       SUM(A.VLR_VENDA_REAL) VENDA_REL,
       SUM(A.VLR_MARGEM_ORC) MARGEM_ORC,
       SUM(A.VLR_MARGEM_REAL) MARGEM_REL,
       SUM(A.VLR_VENDA_LIQUIDA) VENDA_LIQ,
       SUM(A.VLR_FALTA_INVENTARIO) INVENTARIO,
       SUM(A.VLR_LUCRO) LUCRO,
       SUM(A.VLR_CUSTO_PERM) VLR_PERM,
       SUM(A.VLR_EST_MEDIO_PERM) EST_PERM,
       SUM(A.VLR_PREVENTIVA) PREVENTIVA,
       SUM(A.QTD_MESES) QTD_MESES,
       SUM(A.VALE_TRANSP) TRANSPORTE,
       SUM(A.HORAS_TRAB) HORAS,
       SUM(A.FOLHA) FOLHA,
       SUM(A.DEMISSOES) DEMISSOES,
       SUM(A.EFET_INI) EFI,
       SUM(A.VLR_DEVOLUCAO) VLR_DEVOLUCAO,
       SUM(A.VLR_VENDA_ANO_ANT) VLR_VENDA_ANO_ANT
  FROM nl.GRZ_VALORES_REGIOES_APR_ANUAL A
 WHERE A.VLR_VENDA_LIQUIDA > 0
   AND A.ANO = SUBSTR('31/12/2025', 7, 4)
--AND   A.COD_REDE = PI_CODREDE-- SUBSTR(PI_CODGRUPO,2,2)
 group by a.regiao
 order by a.regiao;