WITH
-- Subconsulta para obter a quantidade total de contratos por unidade
Total_Contratos_Unidade AS (
    SELECT
        D.COD_UNIDADE,
        D.COD_ORGANOGRAMA,
        D.COD_REDE_LOCAL,
        COUNT(DISTINCT D.COD_CONTRATO) AS QTDE_TOTAL_CONTRATOS
    FROM V_DADOS_PESSOA_ALTER_AVT D
    WHERE D.COD_EMP = '008'
    GROUP BY D.COD_UNIDADE, D.COD_ORGANOGRAMA, D.COD_REDE_LOCAL
),

-- Subconsulta para obter a quantidade de contratos com absenteísmo por unidade
Contratos_Absenteismo_Unidade AS (
    SELECT
        D.COD_UNIDADE,
        D.COD_ORGANOGRAMA,
        D.COD_REDE_LOCAL,
        COUNT(DISTINCT A.COD_CONTRATO) AS QTDE_CONTRATOS_ABS,
        SUM(CASE WHEN A.COD_VD IN (631, 632, 831, 832) THEN A.QTDE_VD ELSE 0 END) AS TOTAL_FALTAS_UNID,
        SUM(CASE WHEN A.COD_VD = 897 THEN A.QTDE_VD ELSE 0 END) AS TOTAL_ATESTADOS_UNID
    FROM RHFP1006 A
    LEFT JOIN V_DADOS_PESSOA_ALTER_AVT D ON A.COD_CONTRATO = D.COD_CONTRATO
    INNER JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    WHERE D.COD_EMP = '008'
        AND B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
        AND A.COD_VD IN (631, 632, 831, 832, 897)
    GROUP BY D.COD_UNIDADE, D.COD_ORGANOGRAMA, D.COD_REDE_LOCAL
),

-- Subconsulta para obter os totais por rede
Totais_Rede AS (
    SELECT
        D.COD_REDE_LOCAL,
        COUNT(DISTINCT D.COD_CONTRATO) AS QTDE_TOTAL_CONTRATOS_REDE,
        COUNT(DISTINCT CASE WHEN A.COD_VD IN (631, 632, 831, 832, 897) THEN A.COD_CONTRATO END) AS QTDE_CONTRATOS_ABS_REDE,
        SUM(CASE WHEN A.COD_VD IN (631, 632, 831, 832) THEN A.QTDE_VD ELSE 0 END) AS TOTAL_FALTAS_REDE,
        SUM(CASE WHEN A.COD_VD = 897 THEN A.QTDE_VD ELSE 0 END) AS TOTAL_ATESTADOS_REDE
    FROM V_DADOS_PESSOA_ALTER_AVT D
    LEFT JOIN RHFP1006 A ON A.COD_CONTRATO = D.COD_CONTRATO
    LEFT JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    WHERE D.COD_EMP = '008'
        AND (B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM OR B.DATA_REFERENCIA IS NULL)
    GROUP BY D.COD_REDE_LOCAL
),

-- Subconsulta para obter os totais gerais da empresa
Totais_Gerais AS (
    SELECT
        COUNT(DISTINCT D.COD_CONTRATO) AS TOTAL_CONTRATOS,
        COUNT(DISTINCT CASE WHEN A.COD_VD IN (631, 632, 831, 832, 897) THEN A.COD_CONTRATO END) AS TOTAL_CONTR_ABS,
        SUM(CASE WHEN A.COD_VD IN (631, 632, 831, 832) THEN A.QTDE_VD ELSE 0 END) AS TOTAL_FALTAS,
        SUM(CASE WHEN A.COD_VD = 897 THEN A.QTDE_VD ELSE 0 END) AS TOTAL_ATESTADOS
    FROM V_DADOS_PESSOA_ALTER_AVT D
    LEFT JOIN RHFP1006 A ON A.COD_CONTRATO = D.COD_CONTRATO
    LEFT JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    WHERE D.COD_EMP = '008'
        AND (B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM OR B.DATA_REFERENCIA IS NULL)
)

-- Consulta final
SELECT
    D.COD_UNIDADE,
    D.DES_UNIDADE,
    D.COD_REDE_LOCAL,
    D.COD_ORGANOGRAMA,
    MAX(D.DES_REDE_LOCAL) AS DES_REDE_LOCAL,
    B.DATA_REFERENCIA,
    INITCAP(TRIM(TO_CHAR(B.DATA_REFERENCIA, 'MONTH'))) || '/' || TO_CHAR(B.DATA_REFERENCIA, 'YYYY') AS REFERENCIA,
    MAX(TU.QTDE_TOTAL_CONTRATOS) AS QTDE_CONTR_UNID,
    MAX(CAU.QTDE_CONTRATOS_ABS) AS QTDE_ABS_UNID,
    TO_CHAR(MAX(CAU.TOTAL_FALTAS_UNID), 'FM999G999G990D00') AS FALTAS_UNID,
    TO_CHAR(MAX(CAU.TOTAL_ATESTADOS_UNID), 'FM999G999G990D00') AS ATESTADOS_UNID,

    -- Totais por rede (lado a lado)
    MAX(TR1.QTDE_TOTAL_CONTRATOS_REDE) AS CONTR_REDE_10,
    MAX(TR1.QTDE_CONTRATOS_ABS_REDE) AS ABS_REDE_10,
    TO_CHAR(MAX(TR1.TOTAL_FALTAS_REDE), 'FM999G999G990D00') AS FALTAS_REDE_10,
    TO_CHAR(MAX(TR1.TOTAL_ATESTADOS_REDE), 'FM999G999G990D00') AS ATESTADOS_REDE_10,

    MAX(TR2.QTDE_TOTAL_CONTRATOS_REDE) AS CONTR_REDE_30,
    MAX(TR2.QTDE_CONTRATOS_ABS_REDE) AS ABS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_FALTAS_REDE), 'FM999G999G990D00') AS FALTAS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_ATESTADOS_REDE), 'FM999G999G990D00') AS ATESTADOS_REDE_30,
    
    MAX(TR2.QTDE_TOTAL_CONTRATOS_REDE) AS CONTR_REDE_30,
    MAX(TR2.QTDE_CONTRATOS_ABS_REDE) AS ABS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_FALTAS_REDE), 'FM999G999G990D00') AS FALTAS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_ATESTADOS_REDE), 'FM999G999G990D00') AS ATESTADOS_REDE_30,
    
    MAX(TR2.QTDE_TOTAL_CONTRATOS_REDE) AS CONTR_REDE_30,
    MAX(TR2.QTDE_CONTRATOS_ABS_REDE) AS ABS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_FALTAS_REDE), 'FM999G999G990D00') AS FALTAS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_ATESTADOS_REDE), 'FM999G999G990D00') AS ATESTADOS_REDE_30,
    
    MAX(TR2.QTDE_TOTAL_CONTRATOS_REDE) AS CONTR_REDE_30,
    MAX(TR2.QTDE_CONTRATOS_ABS_REDE) AS ABS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_FALTAS_REDE), 'FM999G999G990D00') AS FALTAS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_ATESTADOS_REDE), 'FM999G999G990D00') AS ATESTADOS_REDE_30,
    
    MAX(TR2.QTDE_TOTAL_CONTRATOS_REDE) AS CONTR_REDE_30,
    MAX(TR2.QTDE_CONTRATOS_ABS_REDE) AS ABS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_FALTAS_REDE), 'FM999G999G990D00') AS FALTAS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_ATESTADOS_REDE), 'FM999G999G990D00') AS ATESTADOS_REDE_30,
    
    MAX(TR2.QTDE_TOTAL_CONTRATOS_REDE) AS CONTR_REDE_30,
    MAX(TR2.QTDE_CONTRATOS_ABS_REDE) AS ABS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_FALTAS_REDE), 'FM999G999G990D00') AS FALTAS_REDE_30,
    TO_CHAR(MAX(TR2.TOTAL_ATESTADOS_REDE), 'FM999G999G990D00') AS ATESTADOS_REDE_30,

    -- Outros totais para redes omitidos por brevidade...

    -- Totais gerais da empresa
    TG.TOTAL_CONTRATOS AS TOTAL_CONTRATOS,
    TG.TOTAL_CONTR_ABS AS TOTAL_CONTR_ABS,
    TO_CHAR(TG.TOTAL_FALTAS, 'FM999G999G990D00') AS TOTAL_FALTAS,
    TO_CHAR(TG.TOTAL_ATESTADOS, 'FM999G999G990D00') AS TOTAL_ATESTADOS

FROM
    V_DADOS_PESSOA_ALTER_AVT D
    LEFT JOIN RHFP1006 A ON A.COD_CONTRATO = D.COD_CONTRATO
    LEFT JOIN RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    LEFT JOIN Total_Contratos_Unidade TU ON D.COD_UNIDADE = TU.COD_UNIDADE AND D.COD_REDE_LOCAL = TU.COD_REDE_LOCAL AND D.COD_ORGANOGRAMA = TU.COD_ORGANOGRAMA
    LEFT JOIN Contratos_Absenteismo_Unidade CAU ON D.COD_UNIDADE = CAU.COD_UNIDADE AND D.COD_REDE_LOCAL = CAU.COD_REDE_LOCAL AND D.COD_ORGANOGRAMA = CAU.COD_ORGANOGRAMA
    LEFT JOIN Totais_Rede TR1 ON TR1.COD_REDE_LOCAL = '10'
    LEFT JOIN Totais_Rede TR2 ON TR2.COD_REDE_LOCAL = '30'
    LEFT JOIN Totais_Rede TR2 ON TR2.COD_REDE_LOCAL = '40'
    LEFT JOIN Totais_Rede TR2 ON TR2.COD_REDE_LOCAL = '50'
    LEFT JOIN Totais_Rede TR2 ON TR2.COD_REDE_LOCAL = '70'
    LEFT JOIN Totais_Rede TR2 ON TR2.COD_REDE_LOCAL = '001'
    LEFT JOIN Totais_Rede TR2 ON TR2.COD_REDE_LOCAL = '013'
    CROSS JOIN Totais_Gerais TG

WHERE B.DATA_REFERENCIA BETWEEN :DATA_INICIO AND :DATA_FIM
    AND A.COD_VD IN (631, 632, 831, 832, 897)
    AND D.COD_EMP = '008'
GROUP BY D.COD_UNIDADE,
         D.DES_UNIDADE,
         D.COD_REDE_LOCAL,
         D.COD_ORGANOGRAMA,
         B.DATA_REFERENCIA,
         TG.TOTAL_CONTRATOS,
         TG.TOTAL_CONTR_ABS,
         TG.TOTAL_FALTAS,
         TG.TOTAL_ATESTADOS
ORDER BY
    CASE
        WHEN D.COD_REDE_LOCAL = '10' THEN 1
        WHEN D.COD_REDE_LOCAL = '30' THEN 2
        WHEN D.COD_REDE_LOCAL = '40' THEN 3
        WHEN D.COD_REDE_LOCAL = '50' THEN 4
        WHEN D.COD_REDE_LOCAL = '70' THEN 5
        WHEN D.COD_REDE_LOCAL = '001' THEN 6
        WHEN D.COD_REDE_LOCAL = '013' THEN 7
        ELSE 8
    END,
    D.COD_UNIDADE,
    D.COD_ORGANOGRAMA,
    B.DATA_REFERENCIA
