accept PASSWORD_SYS prompt "SENHA DO USUARIO SYS: " HIDE
accept OWNER prompt "NOME DO USUARIO : "
accept HOST_STRING prompt "STRING DO HOST : "

CONNECT SYS/&&PASSWORD_SYS@&&HOST_STRING AS SYSDBA;

GRANT SELECT ON SYS.DBA_CONS_COLUMNS TO &&OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_CONSTRAINTS TO &&OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_TAB_COLUMNS TO &&OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.V_$SESSION TO &&OWNER WITH GRANT OPTION;
