BACKUP = TRIGGER RHDP2142_HIS ORIGINAL


CREATE OR REPLACE TRIGGER RHDP2142_HIS
  BEFORE INSERT OR UPDATE OR DELETE ON RHDP2142 FOR EACH ROW
DECLARE
  V_COD_SEQ_ALTERACAO NUMBER(15);
  V_COD_TURMA NUMBER(15);
  V_OPERACAO VARCHAR2(1);

BEGIN

  V_COD_TURMA := :NEW.COD_TURMA;

  SELECT NVL(MAX(COD_SEQ_ALTERACAO),0) INTO V_COD_SEQ_ALTERACAO
    FROM RHDP2142_H
   WHERE COD_TURMA = :NEW.COD_TURMA;

  V_COD_SEQ_ALTERACAO := V_COD_SEQ_ALTERACAO + 1;

  :NEW.DATA_ALTERACAO := SYSDATE;

  IF INSERTING THEN
     V_OPERACAO := 'I';
  ELSE
     IF UPDATING THEN
        V_OPERACAO := 'A';
     ELSE
        IF DELETING THEN
           V_OPERACAO := 'E';
        ELSE
           V_OPERACAO := 'N';
        END IF;
     END IF;
  END IF;

  IF INSERTING THEN
  INSERT INTO RHDP2142_H   (COD_TURMA, COD_SEQ_ALTERACAO, DATA_ALTERACAO, COD_OPERADOR, OPERACAO, NOME_TURMA,
                            COD_EVENTO, COD_TURNO_GENERICO, DATA_INICIO, DATA_FIM, STATUS_TURMA, COD_ENTIDADE,
                            IND_PLANEJAMENTO, COD_SEQUENCIA, VALOR_INSCRICAO, PERC_APROVACAO,COD_CAUSA_AFAST,
                            OBSERVACOES_TXT, TIPO_AMBIENTE, COD_TURMA_SUB, IND_SESSOES_PART, DATA_VALIDADE, CARGA_HORARIA_INF)
              VALUES       (:NEW.COD_TURMA, V_COD_SEQ_ALTERACAO, :NEW.DATA_ALTERACAO, :NEW.COD_OPERADOR, V_OPERACAO, :NEW.NOME_TURMA,
                            :NEW.COD_EVENTO, :NEW.COD_TURNO_GENERICO, :NEW.DATA_INICIO, :NEW.DATA_FIM, :NEW.STATUS_TURMA, :NEW.COD_ENTIDADE,
                            :NEW.IND_PLANEJAMENTO, :NEW.COD_SEQUENCIA, :NEW.VALOR_INSCRICAO, :NEW.PERC_APROVACAO, :NEW.COD_CAUSA_AFAST,
                            :NEW.OBSERVACOES_TXT, :NEW.TIPO_AMBIENTE, :NEW.COD_TURMA_SUB, :NEW.IND_SESSOES_PART, :NEW.DATA_VALIDADE, :NEW.CARGA_HORARIA_INF);

  ELSE
  INSERT INTO RHDP2142_H   (COD_TURMA, COD_SEQ_ALTERACAO, DATA_ALTERACAO, COD_OPERADOR, OPERACAO, NOME_TURMA,
                            COD_EVENTO, COD_TURNO_GENERICO, DATA_INICIO, DATA_FIM, STATUS_TURMA, COD_ENTIDADE,
                            IND_PLANEJAMENTO, COD_SEQUENCIA, VALOR_INSCRICAO, PERC_APROVACAO,COD_CAUSA_AFAST,
                            OBSERVACOES_TXT, TIPO_AMBIENTE, COD_TURMA_SUB, IND_SESSOES_PART, DATA_VALIDADE, CARGA_HORARIA_INF)
              VALUES       (:NEW.COD_TURMA, V_COD_SEQ_ALTERACAO, :OLD.DATA_ALTERACAO, :OLD.COD_OPERADOR, V_OPERACAO, :OLD.NOME_TURMA,
                            :OLD.COD_EVENTO, :OLD.COD_TURNO_GENERICO, :OLD.DATA_INICIO, :OLD.DATA_FIM, :OLD.STATUS_TURMA, :OLD.COD_ENTIDADE,
                            :OLD.IND_PLANEJAMENTO, :OLD.COD_SEQUENCIA, :OLD.VALOR_INSCRICAO, :OLD.PERC_APROVACAO, :OLD.COD_CAUSA_AFAST,
                            :OLD.OBSERVACOES_TXT, :OLD.TIPO_AMBIENTE, :OLD.COD_TURMA_SUB, :OLD.IND_SESSOES_PART, :OLD.DATA_VALIDADE, :OLD.CARGA_HORARIA_INF);
  END IF;

END;

