---COMANDO PARA INSERIR DADOS DOS GESTORES AO SUAS RESPECTIVAS SUB-UNIDADES

INSERT INTO GRZ_GESTORES_GRUPO (COD_CONTRATO, DES_GESTOR, CPF, COD_FUNCAO, DES_FUNCAO, COD_UNIDADE, DES_UNIDADE, TIPO_LOCAL, COD_UNIDADE_SUB)
SELECT COD_CONTRATO,
       DES_PESSOA,
       CPF,
       COD_FUNCAO,
       DES_FUNCAO,
       COD_UNIDADE,
       DES_UNIDADE,
       TIPO,
       COD_UNIDADE || LPAD(ROW_NUMBER() OVER (PARTITION BY COD_UNIDADE ORDER BY DES_PESSOA), 1, '0') AS COD_UNIDADE_SUB
FROM V_DADOS_COLAB_AVT
WHERE STATUS = 0
AND (DES_FUNCAO LIKE '%GERENTE%' 
OR DES_FUNCAO LIKE '%SUPERVISOR%' 
OR DES_FUNCAO LIKE '%DIRETOR%')
AND COD_EMP = 8
AND TIPO = 'SETOR'
--AND COD_UNIDADE IN (768, 769)