--SQL PARA MAPEAR AS TABELAS QUE CONTENHAM OS PARAMETROS DOS FILTROS ABAIXO
SELECT table_name, column_name
FROM all_tab_columns
WHERE table_name LIKE '%USUARIO%'
OR column_name LIKE '%SENHA%'


--SQL PARA MAPEAR TRIGGERS E PROCEDURES RELACIONADAS AO USUÁRIO E SENHA
SELECT name, type
FROM all_source
WHERE type IN ('TRIGGER', 'PROCEDURE')
AND UPPER(text) LIKE '%SENHA%'


--SELECT PARA RETORNAR A ESTRUTURA DE UMA FUNÇÃO
SELECT text
FROM user_source
WHERE name = 'RHYF0205'
AND type = 'FUNCTION'
ORDER BY line