--=====COMANDOS SQL PARA INSERIR NOVOS ARQUIVOS E SEUS PARAMETROS NA TABELA RHFP3003

SELECT * FROM RHFP3003
WHERE COD_ARQUIVO IN (5051, 5052, 5053, 5054, 5055, 5056, 5057, 5058, 5059, 5060, 5061, 5062, 5063, 5064, 5065, 5066, 5067, 5068, 5069, 5071, 5072, 5073, 5074)
ORDER BY COD_ARQUIVO ASC, COD_FUNCAO ASC



INSERT INTO RHFP3003 (COD_ARQUIVO, COD_FUNCAO, DESCRICAO, SELECAO, ORIGEM, DICIONARIO, TIPO_FUNCAO, NIVEL_LIMPA)
SELECT DISTINCT COD_ARQUIVO, COD_FUNCAO, DESCRICAO, SELECAO, ORIGEM, DICIONARIO, TIPO_FUNCAO, NIVEL_LIMPA FROM (
SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       1 AS COD_FUNCAO,
       'TOTAL DE REGISTROS' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       2 AS COD_FUNCAO,
       'TOTAL DE REGISTROS 1 + 3 + 5' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       3 AS COD_FUNCAO,
       'SEQUENCIAL - 1' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       4 AS COD_FUNCAO,
       'SOMA DE VALORES' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       5 AS COD_FUNCAO,
       'SEQUENCIAL - 4' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

--=====

UNION ALL

--=====

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       1 AS COD_FUNCAO,
       'TOTAL DE REGISTROS' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       2 AS COD_FUNCAO,
       'TOTAL DE REGISTROS 1 + 3 + 5 ' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       3 AS COD_FUNCAO,
       'SEQUENCIAL - 1' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       4 AS COD_FUNCAO,
       'SOMA DE VALORES' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       5 AS COD_FUNCAO,
       'SEQUENCIAL FINAL' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       6 AS COD_FUNCAO,
       'SEQUENCIA + PARTE 1' AS DESCRICAO,
       'ENCHE' AS SELECAO,
       'S' AS ORIGEM,
       NULL AS DICIONARIO,
       'S' AS TIPO_FUNCAO,
       'D' AS NIVEL_LIMPA
FROM RHFP3003
);