--=====COMANDOS SQL PARA INSERIR NOVOS ARQUIVOS E SEUS PARAMETROS NA TABELA RHFP3002

SELECT * FROM RHFP3002
WHERE COD_ARQUIVO IN (5051, 5052, 5053, 5054, 5055, 5056, 5057, 5058, 5059, 5060, 5071, 5072, 5073, 5074);


INSERT INTO RHFP3002 (COD_ARQUIVO, COD_VARIAVEL, DESCRICAO, TIPO_VARIAVEL, VALOR_NUMERICO, VALOR_DATA, VALOR_ALFANUMERICO, VALOR_MEMO, INFOMAR_EXECUCAO, SELECAO, ORIGEM, DICIONARIO)
SELECT DISTINCT COD_ARQUIVO, COD_VARIAVEL, DESCRICAO, TIPO_VARIAVEL, VALOR_NUMERICO, VALOR_DATA, VALOR_ALFANUMERICO, VALOR_MEMO, INFORMAR_EXECUCAO, SELECAO, ORIGEM, DICIONARIO FROM (
SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       1 AS COD_VARIAVEL,
       'DATA PAGAMENTO' AS DESCRICAO,
       3 AS TIPO_VARIAVEL,
       NULL AS VALOR_NUMERICO,
       NULL AS VALOR_DATA,
       NULL AS VALOR_ALFANUMERICO,
       NULL AS VALOR_MEMO,
       'S' AS INFORMAR_EXECUCAO,
       'ENCHE' AS SELECAO,
       NULL AS ORIGEM,
       NULL AS DICIONARIO
FROM RHFP3002

UNION ALL

SELECT DISTINCT
       5073 AS COD_ARQUIVO,
       2 AS COD_VARIAVEL,
       'VALOR TICKET' AS DESCRICAO,
       2 AS TIPO_VARIAVEL,
       315.0000 AS VALOR_NUMERICO,
       NULL AS VALOR_DATA,
       NULL AS VALOR_ALFANUMERICO,
       NULL AS VALOR_MEMO,
       'N' AS INFORMAR_EXECUCAO,
       'ENCHE' AS SELECAO,
       NULL AS ORIGEM,
       NULL AS DICIONARIO
FROM RHFP3002

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       2 AS COD_VARIAVEL,
       'VALOR TICKET' AS DESCRICAO,
       2 AS TIPO_VARIAVEL,
       315.0000 AS VALOR_NUMERICO,
       NULL AS VALOR_DATA,
       NULL AS VALOR_ALFANUMERICO,
       NULL AS VALOR_MEMO,
       'N' AS INFORMAR_EXECUCAO,
       'ENCHE' AS SELECAO,
       NULL AS ORIGEM,
       NULL AS DICIONARIO
FROM RHFP3002

UNION ALL

SELECT DISTINCT
       5074 AS COD_ARQUIVO,
       3 AS COD_VARIAVEL,
       'ULTIMA SEQUENCIA DA PARTE 1' AS DESCRICAO,
       2 AS TIPO_VARIAVEL,
       3.0000 AS VALOR_NUMERICO,
       NULL AS VALOR_DATA,
       NULL AS VALOR_ALFANUMERICO,
       NULL AS VALOR_MEMO,
       'N' AS INFORMAR_EXECUCAO,
       'ENCHE' AS SELECAO,
       NULL AS ORIGEM,
       NULL AS DICIONARIO
FROM RHFP3002
);