--===CTE HORAS EXTRAS E ATRASOS

WITH OCORRENCIAS AS (
    SELECT B.COD_CONTRATO,
        B.DES_PESSOA,
        SUM(DECODE(COD_OCORRENCIA, 203, NUM_HORAS, 0)) AS "EXTRAS DIURNAS 60% ( GERAL )",
        SUM(DECODE(COD_OCORRENCIA, 205, NUM_HORAS, 0)) AS "ATRASOS DIURNO ( GERAL )",
        SUM(DECODE(COD_OCORRENCIA, 205, NUM_HORAS, 0)) AS "ATRASOS DIURNO ( GERAL )",
        SUM(DECODE(COD_OCORRENCIA, 203, NUM_HORAS, 0)) - SUM(DECODE(COD_OCORRENCIA, 205, NUM_HORAS, 0))  AS  TOTAL,
        SUM(DECODE(COD_OCORRENCIA, 1034, NUM_HORAS, 0)) AS BANCO_HORAS
    FROM RHAF1123 A
    INNER JOIN V_DADOS_PESSOA B ON B.COD_CONTRATO = A.COD_CONTRATO
    WHERE A.COD_OCORRENCIA IN (203, 205, 1034)
    AND COD_UNIDADE IN ('768', '769')
    AND A.DATA_OCORRENCIA BETWEEN  TO_DATE('01/05/2024', 'DD/MM/YYYY') AND  TO_DATE('29/05/2024', 'DD/MM/YYYY')
    GROUP BY B.COD_CONTRATO, B.DES_PESSOA
)
SELECT
    COD_CONTRATO,
    DES_PESSOA,
    CASE
        WHEN BANCO_HORAS < 0 THEN '-' || TRUNC(ABS(BANCO_HORAS)) || ':' || LPAD(ROUND(MOD(ABS(BANCO_HORAS), 1) * 60), 2, '0')
        ELSE TRUNC(BANCO_HORAS) || ':' || LPAD(ROUND(MOD(BANCO_HORAS, 1) * 60), 2, '0')
    END AS "BCO FALTAS ( GERAL )",
    CASE
        WHEN TOTAL < 0 THEN '-' || TRUNC(ABS(TOTAL)) || ':' || LPAD(ROUND(MOD(ABS(TOTAL), 1) * 60), 2, '0')
        ELSE TRUNC(TOTAL) || ':' || LPAD(ROUND(MOD(TOTAL, 1) * 60), 2, '0')
    END AS COMPENSAR
FROM
    OCORRENCIAS
   GROUP BY COD_CONTRATO,
            DES_PESSOA,
            TOTAL,
            BANCO_HORAS
    ORDER BY DES_PESSOA