--==================================================================================--

--============== SQL TURN-OVER CORRETO ATÉ O MOMENTO ====================---

--==================================================================================--

--===VERSÃO DA CONSULTA GERAL

/*SQL TURN-OVER OFICIAL E OTIMIZADO*/
    
    
WITH MONTHS AS (
    SELECT ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
           LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
      FROM DUAL
    CONNECT BY LEVEL <=
               MONTHS_BETWEEN(TO_DATE('31/01/2024', 'DD/MM/YYYY'),
                              TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_INICIAL AS (
    SELECT CCO.COD_ORGANOGRAMA,
           M.MONTH_START,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
      FROM RHFP0300 CTR
     INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
     CROSS JOIN MONTHS M
     WHERE ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, '31/12/9999')
       AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, '31/12/9999')
     GROUP BY CCO.COD_ORGANOGRAMA, M.MONTH_START
),
EFETIVO_FINAL AS (
    SELECT CCO.COD_ORGANOGRAMA,
           M.MONTH_END,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
      FROM RHFP0300 CTR
     INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
     CROSS JOIN MONTHS M
     WHERE LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, '31/12/9999')
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, '31/12/9999')
     GROUP BY CCO.COD_ORGANOGRAMA, M.MONTH_END
),
DATEMETRICS AS (
    SELECT A.COD_UNIDADE,
           A.DES_UNIDADE,
           A.COD_REDE_LOCAL,
           A.DES_REDE_LOCAL,
           A.COD_TIPO,
           A.DES_TIPO,
           A.COD_ORGANOGRAMA,
           M.MONTH_START,
           M.MONTH_END,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN
                    A.COD_CONTRATO
                 END) AS ATIVOS_ATUAIS,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_ADMISSAO <= M.MONTH_END AND
                        (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN
                    A.COD_CONTRATO
                 END) AS ATIVOS_PERIODO,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_INI_AFAST <= M.MONTH_END AND
                        (A.DATA_FIM_AFAST IS NULL OR
                        A.DATA_FIM_AFAST >= M.MONTH_START) AND
                        A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND
                        A.COD_AFAST <> 7 THEN
                    A.COD_CONTRATO
                 END) AS AFAST_PERIODO,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                    A.COD_CONTRATO
                 END) AS ADMITIDOS,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                    A.COD_CONTRATO
                 END) AS DEMITIDOS,
           NVL(EI.EFETIVO_INICIAL, 0) AS EFETIVO_INICIAL,
           NVL(EF.EFETIVO_FINAL, 0) AS EFETIVO_FINAL
      FROM V_DADOS_COLAB_AVT A
     CROSS JOIN MONTHS M
      LEFT JOIN EFETIVO_INICIAL EI ON A.COD_ORGANOGRAMA =
                                      EI.COD_ORGANOGRAMA
                                  AND M.MONTH_START = EI.MONTH_START
      LEFT JOIN EFETIVO_FINAL EF ON A.COD_ORGANOGRAMA = EF.COD_ORGANOGRAMA
                                AND M.MONTH_END = EF.MONTH_END
     WHERE A.COD_EMP = '008' AND A.COD_SETOR_LOJA = '001'
     GROUP BY A.COD_ORGANOGRAMA,
              A.COD_UNIDADE,
              A.DES_UNIDADE,
              A.COD_REDE_LOCAL,
              A.DES_REDE_LOCAL,
              A.COD_TIPO,
              A.DES_TIPO,
              M.MONTH_START,
              M.MONTH_END,
              NVL(EI.EFETIVO_INICIAL, 0),
              NVL(EF.EFETIVO_FINAL, 0)
)
SELECT COD_UNIDADE,
       DES_UNIDADE,
       COD_REDE_LOCAL,
       DES_REDE_LOCAL,
       COD_TIPO,
       DES_TIPO,
       MONTH_START,
       MONTH_END,
       ATIVOS_ATUAIS,
       ATIVOS_PERIODO,
       AFAST_PERIODO,
       ADMITIDOS,
       DEMITIDOS,
       EFETIVO_INICIAL,
       EFETIVO_FINAL,
       (EFETIVO_INICIAL + EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EFETIVO_INICIAL + EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DEMITIDOS * 100) / ((EFETIVO_INICIAL + EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER,
       'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
       'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/01/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS
ORDER BY
    COD_UNIDADE, MONTH_START



--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO


/*SQL TURN-OVER OFICIAL E OTIMIZADO
  COM PARÂMETRO DE DATA PARA INFORMAR*/


WITH MONTHS AS (
    SELECT ADD_MONTHS(TO_CHAR(:DATA_INICIO, 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
           LAST_DAY(ADD_MONTHS(TO_CHAR(:DATA_INICIO, 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
      FROM DUAL
    CONNECT BY LEVEL <=
               MONTHS_BETWEEN(TO_CHAR(:DATA_FIM, 'DD/MM/YYYY'),
                              TO_CHAR(:DATA_INICIO, 'DD/MM/YYYY')) + 1
),
EFETIVO_INICIAL AS (
    SELECT CCO.COD_ORGANOGRAMA,
           M.MONTH_START,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL
      FROM RHFP0300 CTR
     INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
     CROSS JOIN MONTHS M
     WHERE ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, '31/12/9999')
       AND ('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY')) BETWEEN
           CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, '31/12/9999')
     GROUP BY CCO.COD_ORGANOGRAMA, M.MONTH_START
),
EFETIVO_FINAL AS (
    SELECT CCO.COD_ORGANOGRAMA,
           M.MONTH_END,
           COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL
      FROM RHFP0300 CTR
     INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
     CROSS JOIN MONTHS M
     WHERE LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, '31/12/9999')
       AND LAST_DAY(TO_DATE('' || TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'))) BETWEEN
           CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, '31/12/9999')
     GROUP BY CCO.COD_ORGANOGRAMA, M.MONTH_END
),
DATEMETRICS AS (
    SELECT A.COD_UNIDADE,
           A.COD_UNIDADE || ' - ' || A.DES_UNIDADE AS DES_UNIDADE,
           A.COD_REDE_LOCAL,
           A.DES_REDE_LOCAL,
           A.COD_TIPO,
           A.DES_TIPO,
           A.COD_ORGANOGRAMA,
           M.MONTH_START,
           M.MONTH_END,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN
                    A.COD_CONTRATO
                 END) AS ATIVOS_ATUAIS,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_ADMISSAO <= M.MONTH_END AND
                        (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN
                    A.COD_CONTRATO
                 END) AS ATIVOS_PERIODO,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_INI_AFAST <= M.MONTH_END AND
                        (A.DATA_FIM_AFAST IS NULL OR
                        A.DATA_FIM_AFAST >= M.MONTH_START) AND
                        A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND
                        A.COD_AFAST <> 7 THEN
                    A.COD_CONTRATO
                 END) AS AFAST_PERIODO,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                    A.COD_CONTRATO
                 END) AS ADMITIDOS,
           COUNT(DISTINCT CASE
                   WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN
                    A.COD_CONTRATO
                 END) AS DEMITIDOS,
           NVL(EI.EFETIVO_INICIAL, 0) AS EFETIVO_INICIAL,
           NVL(EF.EFETIVO_FINAL, 0) AS EFETIVO_FINAL
      FROM V_DADOS_COLAB_AVT A
     CROSS JOIN MONTHS M
      LEFT JOIN EFETIVO_INICIAL EI ON A.COD_ORGANOGRAMA =
                                      EI.COD_ORGANOGRAMA
                                  AND M.MONTH_START = EI.MONTH_START
      LEFT JOIN EFETIVO_FINAL EF ON A.COD_ORGANOGRAMA = EF.COD_ORGANOGRAMA
                                AND M.MONTH_END = EF.MONTH_END
     WHERE A.COD_EMP = '008'
     GROUP BY A.COD_ORGANOGRAMA,
              A.COD_UNIDADE,
              A.DES_UNIDADE,
              A.COD_REDE_LOCAL,
              A.DES_REDE_LOCAL,
              A.COD_TIPO,
              A.DES_TIPO,
              M.MONTH_START,
              M.MONTH_END,
              NVL(EI.EFETIVO_INICIAL, 0),
              NVL(EF.EFETIVO_FINAL, 0)
)
SELECT COD_UNIDADE,
       DES_UNIDADE,
       COD_REDE_LOCAL,
       DES_REDE_LOCAL,
       COD_TIPO,
       DES_TIPO,
       MONTH_START,
       MONTH_END,
       ATIVOS_ATUAIS,
       ATIVOS_PERIODO,
       AFAST_PERIODO,
       ADMITIDOS,
       DEMITIDOS,
       EFETIVO_INICIAL,
       EFETIVO_FINAL,
       (EFETIVO_INICIAL + EFETIVO_FINAL) / 2 AS EFETIVO_MEDIO,
       ROUND(CASE
               WHEN (EFETIVO_INICIAL + EFETIVO_FINAL) / 2 = 0 THEN
                0
               ELSE
                (DEMITIDOS * 100) / ((EFETIVO_INICIAL + EFETIVO_FINAL) / 2)
             END,
             2) AS TURNOVER,
       'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
       'Período informado: ' || TO_CHAR(:DATA_INICIO, 'DD/MM/YYYY') || ' à ' || TO_CHAR(:DATA_FIM, 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS
ORDER BY
    COD_UNIDADE, MONTH_START





    



--============================================================================================================================--
--============================================================================================================================--

--===VERSÃO TURNOVER POR REDE E DA EMPRESA!===--

WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('29/02/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
-- CTE for Grazziotin
EFETIVO_INICIAL_GRZ AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_GRZ
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '1'
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_GRZ AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_GRZ
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '1'
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_GRZ AS (
    SELECT
       '10 - GRAZZIOTIN' AS DES_LOCAL,
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_GRZ,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_GRZ,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_GRZ,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_GRZ,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_GRZ,
        NVL(EI.EFETIVO_INICIAL_GRZ, 0) AS EFETIVO_INICIAL_GRZ,
        NVL(EF.EFETIVO_FINAL_GRZ, 0) AS EFETIVO_FINAL_GRZ
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_GRZ EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_GRZ EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 10 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_GRZ, 0),
        NVL(EF.EFETIVO_FINAL_GRZ, 0)
),
-- CTE for Por Menos
EFETIVO_INICIAL_PRM AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_PRM
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '3'
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_PRM AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_PRM
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '3'
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_PRM AS (
    SELECT
       '30 - POR MENOS' AS DES_LOCAL,
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_PRM,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_PRM,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_PRM,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_PRM,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_PRM,
        NVL(EI.EFETIVO_INICIAL_PRM, 0) AS EFETIVO_INICIAL_PRM,
        NVL(EF.EFETIVO_FINAL_PRM, 0) AS EFETIVO_FINAL_PRM
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_PRM EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_PRM EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 30 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_PRM, 0),
        NVL(EF.EFETIVO_FINAL_PRM, 0)
),
-- CTE for Franco
EFETIVO_INICIAL_FRG AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_FRG
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '4'
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_FRG AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_FRG
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '4'
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_FRG AS (
    SELECT
        '40 - FRANCO GIORGI' AS DES_LOCAL,
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_FRG,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_FRG,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_FRG,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_FRG,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_FRG,
        NVL(EI.EFETIVO_INICIAL_FRG, 0) AS EFETIVO_INICIAL_FRG,
        NVL(EF.EFETIVO_FINAL_FRG, 0) AS EFETIVO_FINAL_FRG
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_FRG EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_FRG EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 40 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_FRG, 0),
        NVL(EF.EFETIVO_FINAL_FRG, 0)
),
-- CTE for Tottal
EFETIVO_INICIAL_TOT AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_TOT
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '2'
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_TOT AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_TOT
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '2'
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_TOT AS (
    SELECT
        '50 - TOTTAL' AS DES_LOCAL,
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_TOT,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_TOT,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_TOT,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_TOT,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_TOT,
        NVL(EI.EFETIVO_INICIAL_TOT, 0) AS EFETIVO_INICIAL_TOT,
        NVL(EF.EFETIVO_FINAL_TOT, 0) AS EFETIVO_FINAL_TOT
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_TOT EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_TOT EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 50 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_TOT, 0),
        NVL(EF.EFETIVO_FINAL_TOT, 0)
),
-- CTE for GZT Store
EFETIVO_INICIAL_GZT AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_GZT
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '7'
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_GZT AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_GZT
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '7'
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_GZT AS (
    SELECT 
        '70 - GZT STORE' AS DES_LOCAL,
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_GZT,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_GZT,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_GZT,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_GZT,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_GZT,
        NVL(EI.EFETIVO_INICIAL_GZT, 0) AS EFETIVO_INICIAL_GZT,
        NVL(EF.EFETIVO_FINAL_GZT, 0) AS EFETIVO_FINAL_GZT
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_GZT EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_GZT EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 70 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_GZT, 0),
        NVL(EF.EFETIVO_FINAL_GZT, 0)
),
-- CTE for Administração
EFETIVO_ADM AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN M.MONTH_START BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_INICIAL_ADM,
        COUNT(DISTINCT CASE WHEN M.MONTH_END BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_FINAL_ADM
    FROM MONTHS M
    INNER JOIN RHFP0300 CTR ON (CTR.DATA_INICIO <= M.MONTH_END AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0401 ORG1 ON ORG1.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA 
        AND (ORG1.DATA_INICIO <= M.MONTH_END AND ORG1.DATA_FIM >= M.MONTH_START)
    WHERE
        ORG.COD_ORGANOGRAMA IN (SELECT DISTINCT B.COD_ORGANOGRAMA FROM RHFP0401 B WHERE B.EDICAO_NIVEL3 = '001')
        AND ORG1.COD_NIVEL2 = 8
        AND ORG1.COD_NIVEL3 = 9
        AND (CCO.DATA_INICIO <= M.MONTH_END AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    GROUP BY M.MONTH_START, M.MONTH_END
),
DATEMETRICS_ADM AS (
    SELECT
        '001 - ADMNISTRAÇÃO' AS DES_LOCAL,
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_ADM,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_ADM,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_ADM,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_ADM,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_ADM,
        NVL(EA.EFETIVO_INICIAL_ADM, 0) AS EFETIVO_INICIAL_ADM,
        NVL(EA.EFETIVO_FINAL_ADM, 0) AS EFETIVO_FINAL_ADM
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_ADM EA ON M.MONTH_START = EA.MONTH_START AND M.MONTH_END = EA.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_SETOR_LOJA = '001'
    GROUP BY
        M.MONTH_START,
        M.MONTH_END,
        NVL(EA.EFETIVO_INICIAL_ADM, 0),
        NVL(EA.EFETIVO_FINAL_ADM, 0)
),
-- CTE for Logística
EFETIVO_CD AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN M.MONTH_START BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_INICIAL_CD,
        COUNT(DISTINCT CASE WHEN M.MONTH_END BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_FINAL_CD
    FROM MONTHS M
    INNER JOIN RHFP0300 CTR ON (CTR.DATA_INICIO <= M.MONTH_END AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0401 ORG1 ON ORG1.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA 
        AND (ORG1.DATA_INICIO <= M.MONTH_END AND ORG1.DATA_FIM >= M.MONTH_START)
    WHERE
        ORG.COD_ORGANOGRAMA IN (SELECT DISTINCT B.COD_ORGANOGRAMA FROM RHFP0401 B WHERE B.EDICAO_NIVEL3 = '013')
        AND ORG1.COD_NIVEL2 = 8
        AND ORG1.COD_NIVEL3 = 21
        AND (CCO.DATA_INICIO <= M.MONTH_END AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    GROUP BY M.MONTH_START, M.MONTH_END
),
DATEMETRICS_CD AS (
    SELECT
       '013 - LOGÍSTICA' AS DES_LOCAL,
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_CD,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_CD,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_CD,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_CD,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_CD,
        NVL(EA.EFETIVO_INICIAL_CD, 0) AS EFETIVO_INICIAL_CD,
        NVL(EA.EFETIVO_FINAL_CD, 0) AS EFETIVO_FINAL_CD
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_CD EA ON M.MONTH_START = EA.MONTH_START AND M.MONTH_END = EA.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_SETOR_LOJA = '013'
    GROUP BY
        M.MONTH_START,
        M.MONTH_END,
        NVL(EA.EFETIVO_INICIAL_CD, 0),
        NVL(EA.EFETIVO_FINAL_CD, 0)
),
-- CTE for the entire company
EFETIVO_EMP AS (
    SELECT       
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN M.MONTH_START BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_INICIAL_EMP,
        COUNT(DISTINCT CASE WHEN M.MONTH_END BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_FINAL_EMP
    FROM MONTHS M
    INNER JOIN RHFP0300 CTR ON (CTR.DATA_INICIO <= M.MONTH_END AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0401 ORG1 ON ORG1.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA 
        AND (ORG1.DATA_INICIO <= M.MONTH_END AND ORG1.DATA_FIM >= M.MONTH_START)
    WHERE
        ORG.COD_ORGANOGRAMA IN (SELECT DISTINCT B.COD_ORGANOGRAMA FROM RHFP0401 B WHERE B.EDICAO_NIVEL2 = '008')
        AND ORG1.COD_NIVEL2 = 8
        AND (CCO.DATA_INICIO <= M.MONTH_END AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    GROUP BY M.MONTH_START, M.MONTH_END
),
DATEMETRICS_EMP AS (
    SELECT
       '008 - GRAZZIOTIN EMPRESSAO' AS DES_LOCAL,
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_EMP,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_EMP,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_EMP,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_EMP,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_EMP,
        NVL(EA.EFETIVO_INICIAL_EMP, 0) AS EFETIVO_INICIAL_EMP,
        NVL(EA.EFETIVO_FINAL_EMP, 0) AS EFETIVO_FINAL_EMP
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_EMP EA ON M.MONTH_START = EA.MONTH_START AND M.MONTH_END = EA.MONTH_END
    WHERE
        A.COD_EMP = '008'
    GROUP BY
        M.MONTH_START,
        M.MONTH_END,
        NVL(EA.EFETIVO_INICIAL_EMP, 0),
        NVL(EA.EFETIVO_FINAL_EMP, 0)
)
-- Final Query Combining All Metrics
SELECT
    M.MONTH_START,
    M.MONTH_END,
    'GRZ  ==> ' AS ESPACO,
    /*GRAZZIOTN*/
    G.DES_LOCAL, 
    G.ATIVOS_ATUAIS_GRZ, 
    G.ATIVOS_PERIODO_GRZ, 
    G.AFAST_PERIODO_GRZ, 
    G.ADMITIDOS_GRZ, 
    G.DEMITIDOS_GRZ, 
    G.EFETIVO_INICIAL_GRZ, 
    G.EFETIVO_FINAL_GRZ, 
    (G.EFETIVO_INICIAL_GRZ + G.EFETIVO_FINAL_GRZ) / 2 AS EFETIVO_MEDIO_GRZ, 
    ROUND(CASE WHEN (SUM(G.EFETIVO_INICIAL_GRZ) + SUM(G.EFETIVO_FINAL_GRZ)) / 2 = 0 THEN 0 ELSE (SUM(G.DEMITIDOS_GRZ) * 100) / ((SUM(G.EFETIVO_INICIAL_GRZ) + SUM(G.EFETIVO_FINAL_GRZ)) / 2) END, 2) AS TURNOVER_GRZ,
    'PRM  ==> ' AS ESPACO,
    /*POR MENOS*/
    P.DES_LOCAL, 
    P.ATIVOS_ATUAIS_PRM, 
    P.ATIVOS_PERIODO_PRM, 
    P.AFAST_PERIODO_PRM, 
    P.ADMITIDOS_PRM, 
    P.DEMITIDOS_PRM, 
    P.EFETIVO_INICIAL_PRM, 
    P.EFETIVO_FINAL_PRM, 
    (P.EFETIVO_INICIAL_PRM + P.EFETIVO_FINAL_PRM) / 2 AS EFETIVO_MEDIO_PRM, 
    ROUND(CASE WHEN (SUM(P.EFETIVO_INICIAL_PRM) + SUM(P.EFETIVO_FINAL_PRM)) / 2 = 0 THEN 0 ELSE (SUM(P.DEMITIDOS_PRM) * 100) / ((SUM(P.EFETIVO_INICIAL_PRM) + SUM(P.EFETIVO_FINAL_PRM)) / 2) END, 2) AS TURNOVER_PRM,
    'FRG  ==> ' AS ESPACO,
    /*FRANCO*/
    F.DES_LOCAL, 
    F.ATIVOS_ATUAIS_FRG, 
    F.ATIVOS_PERIODO_FRG, 
    F.AFAST_PERIODO_FRG, 
    F.ADMITIDOS_FRG, 
    F.DEMITIDOS_FRG, 
    F.EFETIVO_INICIAL_FRG, 
    F.EFETIVO_FINAL_FRG, 
    (F.EFETIVO_INICIAL_FRG + F.EFETIVO_FINAL_FRG) / 2 AS EFETIVO_MEDIO_FRG, 
    ROUND(CASE WHEN (SUM(F.EFETIVO_INICIAL_FRG) + SUM(F.EFETIVO_FINAL_FRG)) / 2 = 0 THEN 0 ELSE (SUM(F.DEMITIDOS_FRG) * 100) / ((SUM(F.EFETIVO_INICIAL_FRG) + SUM(F.EFETIVO_FINAL_FRG)) / 2) END, 2) AS TURNOVER_FRG,
    'TOT  ==> ' AS ESPACO,
    /*TOTTAL*/
    T.DES_LOCAL, 
    T.ATIVOS_ATUAIS_TOT, 
    T.ATIVOS_PERIODO_TOT, 
    T.AFAST_PERIODO_TOT, 
    T.ADMITIDOS_TOT, 
    T.DEMITIDOS_TOT, 
    T.EFETIVO_INICIAL_TOT, 
    T.EFETIVO_FINAL_TOT, 
    (T.EFETIVO_INICIAL_TOT + T.EFETIVO_FINAL_TOT) / 2 AS EFETIVO_MEDIO_TOT, 
    ROUND(CASE WHEN (SUM(T.EFETIVO_INICIAL_TOT) + SUM(T.EFETIVO_FINAL_TOT)) / 2 = 0 THEN 0 ELSE (SUM(T.DEMITIDOS_TOT) * 100) / ((SUM(T.EFETIVO_INICIAL_TOT) + SUM(T.EFETIVO_FINAL_TOT)) / 2) END, 2) AS TURNOVER_TOT,
    'GZT  ==> ' AS ESPACO,
    /*GZT*/
    Z.DES_LOCAL, 
    Z.ATIVOS_ATUAIS_GZT, 
    Z.ATIVOS_PERIODO_GZT, 
    Z.AFAST_PERIODO_GZT, 
    Z.ADMITIDOS_GZT, 
    Z.DEMITIDOS_GZT, 
    Z.EFETIVO_INICIAL_GZT, 
    Z.EFETIVO_FINAL_GZT, 
    (Z.EFETIVO_INICIAL_GZT + Z.EFETIVO_FINAL_GZT) / 2 AS EFETIVO_MEDIO_GZT, 
    ROUND(CASE WHEN (SUM(Z.EFETIVO_INICIAL_GZT) + SUM(Z.EFETIVO_FINAL_GZT)) / 2 = 0 THEN 0 ELSE (SUM(Z.DEMITIDOS_GZT) * 100) / ((SUM(Z.EFETIVO_INICIAL_GZT) + SUM(Z.EFETIVO_FINAL_GZT)) / 2) END, 2) AS TURNOVER_GZT,
    'ADM  ==> ' AS ESPACO,
    /*ADM*/
    A.DES_LOCAL, 
    A.ATIVOS_ATUAIS_ADM, 
    A.ATIVOS_PERIODO_ADM, 
    A.AFAST_PERIODO_ADM, 
    A.ADMITIDOS_ADM, 
    A.DEMITIDOS_ADM, 
    A.EFETIVO_INICIAL_ADM, 
    A.EFETIVO_FINAL_ADM, 
    (A.EFETIVO_INICIAL_ADM + A.EFETIVO_FINAL_ADM) / 2 AS EFETIVO_MEDIO_ADM, 
    ROUND(CASE WHEN (SUM(A.EFETIVO_INICIAL_ADM) + SUM(A.EFETIVO_FINAL_ADM)) / 2 = 0 THEN 0 ELSE (SUM(A.DEMITIDOS_ADM) * 100) / ((SUM(A.EFETIVO_INICIAL_ADM) + SUM(A.EFETIVO_FINAL_ADM)) / 2) END, 2) AS TURNOVER_ADM,
    'CD  ==> ' AS ESPACO,
    /*CD*/
    C.DES_LOCAL, 
    C.ATIVOS_ATUAIS_CD,  
    C.ATIVOS_PERIODO_CD, 
    C.AFAST_PERIODO_CD, 
    C.ADMITIDOS_CD, 
    C.DEMITIDOS_CD, 
    C.EFETIVO_INICIAL_CD, 
    C.EFETIVO_FINAL_CD, 
    (C.EFETIVO_INICIAL_CD + C.EFETIVO_FINAL_CD) / 2 AS EFETIVO_MEDIO_CD, 
    ROUND(CASE WHEN (SUM(C.EFETIVO_INICIAL_CD) + SUM(C.EFETIVO_FINAL_CD)) / 2 = 0 THEN 0 ELSE (SUM(C.DEMITIDOS_CD) * 100) / ((SUM(C.EFETIVO_INICIAL_CD) + SUM(C.EFETIVO_FINAL_CD)) / 2) END, 2) AS TURNOVER_CD,
    'EMPRESA  ==> ' AS ESPACO,
    /*EMPRESA*/
    E.DES_LOCAL, 
    E.ATIVOS_ATUAIS_EMP, 
    E.ATIVOS_PERIODO_EMP, 
    E.AFAST_PERIODO_EMP, 
    E.ADMITIDOS_EMP, 
    E.DEMITIDOS_EMP, 
    E.EFETIVO_INICIAL_EMP, 
    E.EFETIVO_FINAL_EMP, 
    (E.EFETIVO_INICIAL_EMP + E.EFETIVO_FINAL_EMP) / 2 AS EFETIVO_MEDIO_EMP, 
    ROUND(CASE WHEN (SUM(E.EFETIVO_INICIAL_EMP) + SUM(E.EFETIVO_FINAL_EMP)) / 2 = 0 THEN 0 ELSE (SUM(E.DEMITIDOS_EMP) * 100) / ((SUM(E.EFETIVO_INICIAL_EMP) + SUM(E.EFETIVO_FINAL_EMP)) / 2) END, 2) AS TURNOVER_EMP,    
    REPLACE(TRIM(TO_CHAR(M.MONTH_START, 'Month/YYYY', 'NLS_DATE_LANGUAGE = PORTUGUESE')), ' ', '') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
    
FROM
    MONTHS M
LEFT JOIN DATEMETRICS_GRZ G ON M.MONTH_START = G.MONTH_START 
                            AND M.MONTH_END = G.MONTH_END
LEFT JOIN DATEMETRICS_PRM P ON M.MONTH_START = P.MONTH_START 
                            AND M.MONTH_END = P.MONTH_END
LEFT JOIN DATEMETRICS_FRG F ON M.MONTH_START = F.MONTH_START 
                            AND M.MONTH_END = F.MONTH_END
LEFT JOIN DATEMETRICS_TOT T ON M.MONTH_START = T.MONTH_START 
                            AND M.MONTH_END = T.MONTH_END
LEFT JOIN DATEMETRICS_GZT Z ON M.MONTH_START = Z.MONTH_START 
                            AND M.MONTH_END = Z.MONTH_END
LEFT JOIN DATEMETRICS_ADM A ON M.MONTH_START = A.MONTH_START 
                            AND M.MONTH_END = A.MONTH_END
LEFT JOIN DATEMETRICS_CD C ON M.MONTH_START = C.MONTH_START 
                           AND M.MONTH_END = C.MONTH_END
LEFT JOIN DATEMETRICS_EMP E ON M.MONTH_START = E.MONTH_START 
                            AND M.MONTH_END = E.MONTH_END
GROUP BY
        M.MONTH_START,
        M.MONTH_END,
        G.DES_LOCAL, 
        G.ATIVOS_ATUAIS_GRZ, 
        G.ATIVOS_PERIODO_GRZ, 
        G.AFAST_PERIODO_GRZ, 
        G.ADMITIDOS_GRZ, 
        G.DEMITIDOS_GRZ, 
        G.EFETIVO_INICIAL_GRZ, 
        G.EFETIVO_FINAL_GRZ,
        /*=================*/
        P.DES_LOCAL, 
        P.ATIVOS_ATUAIS_PRM, 
        P.ATIVOS_PERIODO_PRM, 
        P.AFAST_PERIODO_PRM, 
        P.ADMITIDOS_PRM, 
        P.DEMITIDOS_PRM, 
        P.EFETIVO_INICIAL_PRM, 
        P.EFETIVO_FINAL_PRM,
        /*=================*/
        F.DES_LOCAL, 
        F.ATIVOS_ATUAIS_FRG, 
        F.ATIVOS_PERIODO_FRG, 
        F.AFAST_PERIODO_FRG, 
        F.ADMITIDOS_FRG, 
        F.DEMITIDOS_FRG, 
        F.EFETIVO_INICIAL_FRG, 
        F.EFETIVO_FINAL_FRG,
        /*=================*/
        T.DES_LOCAL, 
        T.ATIVOS_ATUAIS_TOT, 
        T.ATIVOS_PERIODO_TOT, 
        T.AFAST_PERIODO_TOT, 
        T.ADMITIDOS_TOT, 
        T.DEMITIDOS_TOT, 
        T.EFETIVO_INICIAL_TOT, 
        T.EFETIVO_FINAL_TOT,
        /*=================*/
        Z.DES_LOCAL, 
        Z.ATIVOS_ATUAIS_GZT, 
        Z.ATIVOS_PERIODO_GZT, 
        Z.AFAST_PERIODO_GZT, 
        Z.ADMITIDOS_GZT, 
        Z.DEMITIDOS_GZT, 
        Z.EFETIVO_INICIAL_GZT, 
        Z.EFETIVO_FINAL_GZT,
        /*=================*/
        A.DES_LOCAL, 
        A.ATIVOS_ATUAIS_ADM, 
        A.ATIVOS_PERIODO_ADM, 
        A.AFAST_PERIODO_ADM, 
        A.ADMITIDOS_ADM, 
        A.DEMITIDOS_ADM, 
        A.EFETIVO_INICIAL_ADM, 
        A.EFETIVO_FINAL_ADM,
        /*=================*/
        C.DES_LOCAL, 
        C.ATIVOS_ATUAIS_CD,  
        C.ATIVOS_PERIODO_CD, 
        C.AFAST_PERIODO_CD, 
        C.ADMITIDOS_CD, 
        C.DEMITIDOS_CD, 
        C.EFETIVO_INICIAL_CD, 
        C.EFETIVO_FINAL_CD,
        /*=================*/
        E.DES_LOCAL, 
        E.ATIVOS_ATUAIS_EMP, 
        E.ATIVOS_PERIODO_EMP, 
        E.AFAST_PERIODO_EMP, 
        E.ADMITIDOS_EMP, 
        E.DEMITIDOS_EMP, 
        E.EFETIVO_INICIAL_EMP, 
        E.EFETIVO_FINAL_EMP
ORDER BY
        M.MONTH_START;


    


--============================================================================================================================--
--============================================================================================================================--

--============================================================--

/*RELAÇÃO DO TURN-OVER POR REDE/SETOR E TOTAL DA EMPRESA*/

--============================================================--


--==CONTAGEM GERAL DA GRAZZIOTIN


WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('31/05/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_INICIAL_GRZ AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_GRZ
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '1'
        --AND CTB.COD_REDE_LOCAL = 10
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_GRZ AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_GRZ
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '1'
        --AND CTB.COD_REDE_LOCAL = 10
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_GRZ AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_GRZ,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_GRZ,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_GRZ,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_GRZ,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_GRZ,
        NVL(EI.EFETIVO_INICIAL_GRZ, 0) AS EFETIVO_INICIAL_GRZ,
        NVL(EF.EFETIVO_FINAL_GRZ, 0) AS EFETIVO_FINAL_GRZ
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_GRZ EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_GRZ EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 10 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_GRZ, 0),
        NVL(EF.EFETIVO_FINAL_GRZ, 0)
)
SELECT
    G.MONTH_START,
    G.MONTH_END,
    SUM(G.ATIVOS_ATUAIS_GRZ) AS ATIVOS_ATUAIS_GRZ,
    SUM(G.AFAST_PERIODO_GRZ) AS AFAST_PERIODO_GRZ,
    SUM(G.ADMITIDOS_GRZ) AS ADMITIDOS_GRZ,
    SUM(G.DEMITIDOS_GRZ) AS DEMITIDOS_GRZ,
    SUM(G.EFETIVO_INICIAL_GRZ) AS EFETIVO_INICIAL_GRZ,
    SUM(G.EFETIVO_FINAL_GRZ) AS EFETIVO_FINAL_GRZ,
    (SUM(G.EFETIVO_INICIAL_GRZ) + SUM(G.EFETIVO_FINAL_GRZ)) / 2 AS EFETIVO_MEDIO_GRZ,
    ROUND(CASE WHEN (SUM(G.EFETIVO_INICIAL_GRZ) + SUM(G.EFETIVO_FINAL_GRZ)) / 2 = 0 THEN 0 ELSE (SUM(G.DEMITIDOS_GRZ) * 100) / ((SUM(G.EFETIVO_INICIAL_GRZ) + SUM(G.EFETIVO_FINAL_GRZ)) / 2) END, 2) AS TURNOVER_GRZ,
    'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS_GRZ G
GROUP BY
    G.MONTH_START,
    G.MONTH_END
ORDER BY
    G.MONTH_START


--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO --GRZ









--==================================================================--

--==CONTAGEM DA POR MENOS


WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('31/05/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_INICIAL_PRM AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_PRM
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '3'
        --AND CTB.COD_REDE_LOCAL = 10
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_PRM AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_PRM
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '3'
        --AND CTB.COD_REDE_LOCAL = 10
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_PRM AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_PRM,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_PRM,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_PRM,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_PRM,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_PRM,
        NVL(EI.EFETIVO_INICIAL_PRM, 0) AS EFETIVO_INICIAL_PRM,
        NVL(EF.EFETIVO_FINAL_PRM, 0) AS EFETIVO_FINAL_PRM
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_PRM EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_PRM EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 30 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_PRM, 0),
        NVL(EF.EFETIVO_FINAL_PRM, 0)
)
SELECT
    P.MONTH_START,
    P.MONTH_END,
    SUM(P.ATIVOS_ATUAIS_PRM) AS ATIVOS_ATUAIS_PRM,
    SUM(P.AFAST_PERIODO_PRM) AS AFAST_PERIODO_PRM,
    SUM(P.ADMITIDOS_PRM) AS ADMITIDOS_PRM,
    SUM(P.DEMITIDOS_PRM) AS DEMITIDOS_PRM,
    SUM(P.EFETIVO_INICIAL_PRM) AS EFETIVO_INICIAL_PRM,
    SUM(P.EFETIVO_FINAL_PRM) AS EFETIVO_FINAL_PRM,
    (SUM(P.EFETIVO_INICIAL_PRM) + SUM(P.EFETIVO_FINAL_PRM)) / 2 AS EFETIVO_MEDIO_PRM,
    ROUND(CASE WHEN (SUM(P.EFETIVO_INICIAL_PRM) + SUM(P.EFETIVO_FINAL_PRM)) / 2 = 0 THEN 0 ELSE (SUM(P.DEMITIDOS_PRM) * 100) / ((SUM(P.EFETIVO_INICIAL_PRM) + SUM(P.EFETIVO_FINAL_PRM)) / 2) END, 2) AS TURNOVER_PRM,
    'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS_PRM P
GROUP BY
    P.MONTH_START,
    P.MONTH_END
ORDER BY
    P.MONTH_START



--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO --PRM








--===================================================================--


--==CONTAGEM DA FRANCO

WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('31/05/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_INICIAL_FRG AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_FRG
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '4'
        --AND CTB.COD_REDE_LOCAL = 10
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_FRG AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_FRG
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '4'
        --AND CTB.COD_REDE_LOCAL = 10
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_FRG AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_FRG,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_FRG,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_FRG,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_FRG,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_FRG,
        NVL(EI.EFETIVO_INICIAL_FRG, 0) AS EFETIVO_INICIAL_FRG,
        NVL(EF.EFETIVO_FINAL_FRG, 0) AS EFETIVO_FINAL_FRG
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_FRG EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_FRG EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 40 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_FRG, 0),
        NVL(EF.EFETIVO_FINAL_FRG, 0)
)
SELECT
    F.MONTH_START,
    F.MONTH_END,
    SUM(F.ATIVOS_ATUAIS_FRG) AS ATIVOS_ATUAIS_FRG,
    SUM(F.AFAST_PERIODO_FRG) AS AFAST_PERIODO_FRG,
    SUM(F.ADMITIDOS_FRG) AS ADMITIDOS_FRG,
    SUM(F.DEMITIDOS_FRG) AS DEMITIDOS_FRG,
    SUM(F.EFETIVO_INICIAL_FRG) AS EFETIVO_INICIAL_FRG,
    SUM(F.EFETIVO_FINAL_FRG) AS EFETIVO_FINAL_FRG,
    (SUM(F.EFETIVO_INICIAL_FRG) + SUM(F.EFETIVO_FINAL_FRG)) / 2 AS EFETIVO_MEDIO_FRG,
    ROUND(CASE WHEN (SUM(F.EFETIVO_INICIAL_FRG) + SUM(F.EFETIVO_FINAL_FRG)) / 2 = 0 THEN 0 ELSE (SUM(F.DEMITIDOS_FRG) * 100) / ((SUM(F.EFETIVO_INICIAL_FRG) + SUM(F.EFETIVO_FINAL_FRG)) / 2) END, 2) AS TURNOVER_FRG,
    'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS_FRG F
GROUP BY
    F.MONTH_START,
    F.MONTH_END
ORDER BY
    F.MONTH_START



--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO --FRG








--============================================================================--



--==CONTAGEM DA TOTTAL

WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('31/05/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_INICIAL_TOT AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_TOT
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '2'
        --AND CTB.COD_REDE_LOCAL = 10
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_TOT AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_TOT
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '2'
        --AND CTB.COD_REDE_LOCAL = 10
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_TOT AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_TOT,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_TOT,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_TOT,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_TOT,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_TOT,
        NVL(EI.EFETIVO_INICIAL_TOT, 0) AS EFETIVO_INICIAL_TOT,
        NVL(EF.EFETIVO_FINAL_TOT, 0) AS EFETIVO_FINAL_TOT
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_TOT EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_TOT EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 50 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_TOT, 0),
        NVL(EF.EFETIVO_FINAL_TOT, 0)
)
SELECT
    T.MONTH_START,
    T.MONTH_END,
    SUM(T.ATIVOS_ATUAIS_TOT) AS ATIVOS_ATUAIS_TOT,
    SUM(T.AFAST_PERIODO_TOT) AS AFAST_PERIODO_TOT,
    SUM(T.ADMITIDOS_TOT) AS ADMITIDOS_TOT,
    SUM(T.DEMITIDOS_TOT) AS DEMITIDOS_TOT,
    SUM(T.EFETIVO_INICIAL_TOT) AS EFETIVO_INICIAL_TOT,
    SUM(T.EFETIVO_FINAL_TOT) AS EFETIVO_FINAL_TOT,
    (SUM(T.EFETIVO_INICIAL_TOT) + SUM(T.EFETIVO_FINAL_TOT)) / 2 AS EFETIVO_MEDIO_TOT,
    ROUND(CASE WHEN (SUM(T.EFETIVO_INICIAL_TOT) + SUM(T.EFETIVO_FINAL_TOT)) / 2 = 0 THEN 0 ELSE (SUM(T.DEMITIDOS_TOT) * 100) / ((SUM(T.EFETIVO_INICIAL_TOT) + SUM(T.EFETIVO_FINAL_TOT)) / 2) END, 2) AS TURNOVER_TOT,
    'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS_TOT T
GROUP BY
    T.MONTH_START,
    T.MONTH_END
ORDER BY
    T.MONTH_START



--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO --TOT








--==================================================================================--


--==CONTAGEM DA GZT STORE

WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('31/05/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_INICIAL_GZT AS (
    SELECT
        M.MONTH_START,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_INICIAL_GZT
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '7'
        --AND CTB.COD_REDE_LOCAL = 10
        AND TO_DATE('01/' || TO_CHAR(M.MONTH_START, 'MM/YYYY'), 'DD/MM/YYYY') BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_START
),
EFETIVO_FINAL_GZT AS (
    SELECT
        M.MONTH_END,
        COUNT(DISTINCT CTR.COD_CONTRATO) AS EFETIVO_FINAL_GZT
    FROM RHFP0300 CTR
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0402 CTB ON ORG.COD_CUSTO_CONTABIL = CTB.COD_CUSTO_CONTABIL
    CROSS JOIN MONTHS M
    WHERE
        LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
        AND CTB.EDICAO_NIVEL3 = '7'
        --AND CTB.COD_REDE_LOCAL = 10
        AND LAST_DAY(TO_DATE(TO_CHAR(M.MONTH_END, 'DD/MM/YYYY'), 'DD/MM/YYYY')) BETWEEN CCO.DATA_INICIO AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY'))
    GROUP BY M.MONTH_END
),
DATEMETRICS_GZT AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_GZT,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_GZT,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_GZT,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_GZT,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_GZT,
        NVL(EI.EFETIVO_INICIAL_GZT, 0) AS EFETIVO_INICIAL_GZT,
        NVL(EF.EFETIVO_FINAL_GZT, 0) AS EFETIVO_FINAL_GZT
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_INICIAL_GZT EI ON M.MONTH_START = EI.MONTH_START
    LEFT JOIN EFETIVO_FINAL_GZT EF ON M.MONTH_END = EF.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_REDE_LOCAL = 70 AND A.COD_TIPO = 1
    GROUP BY
        A.COD_REDE_LOCAL,
        A.DES_REDE_LOCAL,
        A.COD_TIPO,
        A.DES_TIPO,
        M.MONTH_START,
        M.MONTH_END,
        NVL(EI.EFETIVO_INICIAL_GZT, 0),
        NVL(EF.EFETIVO_FINAL_GZT, 0)
)
SELECT
    Z.MONTH_START,
    Z.MONTH_END,
    SUM(Z.ATIVOS_ATUAIS_GZT) AS ATIVOS_ATUAIS_GZT,
    SUM(Z.AFAST_PERIODO_GZT) AS AFAST_PERIODO_GZT,
    SUM(Z.ADMITIDOS_GZT) AS ADMITIDOS_GZT,
    SUM(Z.DEMITIDOS_GZT) AS DEMITIDOS_GZT,
    SUM(Z.EFETIVO_INICIAL_GZT) AS EFETIVO_INICIAL_GZT,
    SUM(Z.EFETIVO_FINAL_GZT) AS EFETIVO_FINAL_GZT,
    (SUM(Z.EFETIVO_INICIAL_GZT) + SUM(Z.EFETIVO_FINAL_GZT)) / 2 AS EFETIVO_MEDIO_GZT,
    ROUND(CASE WHEN (SUM(Z.EFETIVO_INICIAL_GZT) + SUM(Z.EFETIVO_FINAL_GZT)) / 2 = 0 THEN 0 ELSE (SUM(Z.DEMITIDOS_GZT) * 100) / ((SUM(Z.EFETIVO_INICIAL_GZT) + SUM(Z.EFETIVO_FINAL_GZT)) / 2) END, 2) AS TURNOVER_GZT,
    'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS_GZT Z
GROUP BY
    Z.MONTH_START,
    Z.MONTH_END
ORDER BY
    Z.MONTH_START



--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO --GZT








--======================================================================================--



--==CONTAGEM DA ADMINISTRAÇÃO


WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('31/05/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_ADM AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN M.MONTH_START BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_INICIAL_ADM,
        COUNT(DISTINCT CASE WHEN M.MONTH_END BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_FINAL_ADM
    FROM MONTHS M
    INNER JOIN RHFP0300 CTR ON (CTR.DATA_INICIO <= M.MONTH_END AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0401 ORG1 ON ORG1.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA 
        AND (ORG1.DATA_INICIO <= M.MONTH_END AND ORG1.DATA_FIM >= M.MONTH_START)
    WHERE
        ORG.COD_ORGANOGRAMA IN (SELECT DISTINCT B.COD_ORGANOGRAMA FROM RHFP0401 B WHERE B.EDICAO_NIVEL3 = '001')
        AND ORG1.COD_NIVEL2 = 8
        AND ORG1.COD_NIVEL3 = 9
        AND (CCO.DATA_INICIO <= M.MONTH_END AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    GROUP BY M.MONTH_START, M.MONTH_END
),
DATEMETRICS_ADM AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_ADM,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_ADM,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_ADM,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_ADM,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_ADM,
        NVL(EA.EFETIVO_INICIAL_ADM, 0) AS EFETIVO_INICIAL_ADM,
        NVL(EA.EFETIVO_FINAL_ADM, 0) AS EFETIVO_FINAL_ADM
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_ADM EA ON M.MONTH_START = EA.MONTH_START AND M.MONTH_END = EA.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_SETOR_LOJA = '001'
    GROUP BY
        M.MONTH_START,
        M.MONTH_END,
        NVL(EA.EFETIVO_INICIAL_ADM, 0),
        NVL(EA.EFETIVO_FINAL_ADM, 0)
)
SELECT
    D.MONTH_START,
    D.MONTH_END,
    SUM(D.ATIVOS_ATUAIS_ADM) AS ATIVOS_ATUAIS_ADM,
    SUM(D.AFAST_PERIODO_ADM) AS AFAST_PERIODO_ADM,
    SUM(D.ATIVOS_PERIODO_ADM) AS ATIVOS_PERIODO_ADM,
    SUM(D.ADMITIDOS_ADM) AS ADMITIDOS_ADM,
    SUM(D.DEMITIDOS_ADM) AS DEMITIDOS_ADM,
    SUM(D.EFETIVO_INICIAL_ADM) AS EFETIVO_INICIAL_ADM,
    SUM(D.EFETIVO_FINAL_ADM) AS EFETIVO_FINAL_ADM,
    (SUM(D.EFETIVO_INICIAL_ADM) + SUM(D.EFETIVO_FINAL_ADM)) / 2 AS EFETIVO_MEDIO_ADM,
    ROUND(CASE WHEN (SUM(D.EFETIVO_INICIAL_ADM) + SUM(D.EFETIVO_FINAL_ADM)) / 2 = 0 THEN 0 ELSE (SUM(D.DEMITIDOS_ADM) * 100) / ((SUM(D.EFETIVO_INICIAL_ADM) + SUM(D.EFETIVO_FINAL_ADM)) / 2) END, 2) AS TURNOVER_ADM,
    'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS_ADM D
GROUP BY
    D.MONTH_START,
    D.MONTH_END
ORDER BY
    D.MONTH_START;



--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO --ADM








--======================================================================================--



--==CONTAGEM LOGÍSTICA


WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('31/05/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_CD AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN M.MONTH_START BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_INICIAL_CD,
        COUNT(DISTINCT CASE WHEN M.MONTH_END BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_FINAL_CD
    FROM MONTHS M
    INNER JOIN RHFP0300 CTR ON (CTR.DATA_INICIO <= M.MONTH_END AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0401 ORG1 ON ORG1.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA 
        AND (ORG1.DATA_INICIO <= M.MONTH_END AND ORG1.DATA_FIM >= M.MONTH_START)
    WHERE
        ORG.COD_ORGANOGRAMA IN (SELECT DISTINCT B.COD_ORGANOGRAMA FROM RHFP0401 B WHERE B.EDICAO_NIVEL3 = '013')
        AND ORG1.COD_NIVEL2 = 8
        AND ORG1.COD_NIVEL3 = 21
        AND (CCO.DATA_INICIO <= M.MONTH_END AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    GROUP BY M.MONTH_START, M.MONTH_END
),
DATEMETRICS_CD AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_CD,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_CD,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_CD,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_CD,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_CD,
        NVL(EA.EFETIVO_INICIAL_CD, 0) AS EFETIVO_INICIAL_CD,
        NVL(EA.EFETIVO_FINAL_CD, 0) AS EFETIVO_FINAL_CD
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_CD EA ON M.MONTH_START = EA.MONTH_START AND M.MONTH_END = EA.MONTH_END
    WHERE
        A.COD_EMP = '008' AND A.COD_SETOR_LOJA = '013'
    GROUP BY
        M.MONTH_START,
        M.MONTH_END,
        NVL(EA.EFETIVO_INICIAL_CD, 0),
        NVL(EA.EFETIVO_FINAL_CD, 0)
)
SELECT
    L.MONTH_START,
    L.MONTH_END,
    SUM(L.ATIVOS_ATUAIS_CD) AS ATIVOS_ATUAIS_CD,
    SUM(L.AFAST_PERIODO_CD) AS AFAST_PERIODO_CD,
    SUM(L.ATIVOS_PERIODO_CD) AS ATIVOS_PERIODO_CD,
    SUM(L.ADMITIDOS_CD) AS ADMITIDOS_CD,
    SUM(L.DEMITIDOS_CD) AS DEMITIDOS_CD,
    SUM(L.EFETIVO_INICIAL_CD) AS EFETIVO_INICIAL_CD,
    SUM(L.EFETIVO_FINAL_CD) AS EFETIVO_FINAL_CD,
    (SUM(L.EFETIVO_INICIAL_CD) + SUM(L.EFETIVO_FINAL_CD)) / 2 AS EFETIVO_MEDIO_CD,
    ROUND(CASE WHEN (SUM(L.EFETIVO_INICIAL_CD) + SUM(L.EFETIVO_FINAL_CD)) / 2 = 0 THEN 0 ELSE (SUM(L.DEMITIDOS_CD) * 100) / ((SUM(L.EFETIVO_INICIAL_CD) + SUM(L.EFETIVO_FINAL_CD)) / 2) END, 2) AS TURNOVER_CD,
    'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS_CD L
GROUP BY
    L.MONTH_START,
    L.MONTH_END
ORDER BY
    L.MONTH_START;




--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO --CD








--============================================================================================--


--==CONTAGEM GERAL DA EMPRESA TODA


WITH MONTHS AS (
    SELECT
        ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1) AS MONTH_START,
        LAST_DAY(ADD_MONTHS(TO_DATE('01/01/2024', 'DD/MM/YYYY'), LEVEL - 1)) AS MONTH_END
    FROM DUAL
    CONNECT BY LEVEL <= MONTHS_BETWEEN(TO_DATE('31/05/2024', 'DD/MM/YYYY'), TO_DATE('01/01/2024', 'DD/MM/YYYY')) + 1
),
EFETIVO_EMP AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN M.MONTH_START BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_INICIAL_EMP,
        COUNT(DISTINCT CASE WHEN M.MONTH_END BETWEEN CTR.DATA_INICIO AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) THEN CTR.COD_CONTRATO END) AS EFETIVO_FINAL_EMP
    FROM MONTHS M
    INNER JOIN RHFP0300 CTR ON (CTR.DATA_INICIO <= M.MONTH_END AND NVL(CTR.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    INNER JOIN RHFP0310 CCO ON CTR.COD_CONTRATO = CCO.COD_CONTRATO
    INNER JOIN RHFP0400 ORG ON CCO.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
    INNER JOIN RHFP0401 ORG1 ON ORG1.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA 
        AND (ORG1.DATA_INICIO <= M.MONTH_END AND ORG1.DATA_FIM >= M.MONTH_START)
    WHERE
        ORG.COD_ORGANOGRAMA IN (SELECT DISTINCT B.COD_ORGANOGRAMA FROM RHFP0401 B WHERE B.EDICAO_NIVEL2 = '008')
        AND ORG1.COD_NIVEL2 = 8
        AND (CCO.DATA_INICIO <= M.MONTH_END AND NVL(CCO.DATA_FIM, TO_DATE('31/12/9999', 'DD/MM/YYYY')) >= M.MONTH_START)
    GROUP BY M.MONTH_START, M.MONTH_END
),
DATEMETRICS_CD AS (
    SELECT
        M.MONTH_START,
        M.MONTH_END,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO > SYSDATE THEN A.COD_CONTRATO END) AS ATIVOS_ATUAIS_EMP,
        COUNT(DISTINCT CASE WHEN A.DATA_INI_AFAST <= M.MONTH_END AND (A.DATA_FIM_AFAST IS NULL OR A.DATA_FIM_AFAST >= M.MONTH_START) AND A.DATA_FIM_AFAST <> TO_DATE('31/12/2999', 'DD/MM/YYYY') AND A.COD_AFAST <> 7 THEN A.COD_CONTRATO END) AS AFAST_PERIODO_EMP,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO <= M.MONTH_END AND (A.DATA_DEMISSAO IS NULL OR A.DATA_DEMISSAO >= M.MONTH_END) THEN A.COD_CONTRATO END) AS ATIVOS_PERIODO_EMP,
        COUNT(DISTINCT CASE WHEN A.DATA_ADMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS ADMITIDOS_EMP,
        COUNT(DISTINCT CASE WHEN A.DATA_DEMISSAO BETWEEN M.MONTH_START AND M.MONTH_END THEN A.COD_CONTRATO END) AS DEMITIDOS_EMP,
        NVL(EA.EFETIVO_INICIAL_EMP, 0) AS EFETIVO_INICIAL_EMP,
        NVL(EA.EFETIVO_FINAL_EMP, 0) AS EFETIVO_FINAL_EMP
    FROM
        V_DADOS_COLAB_AVT A
    CROSS JOIN MONTHS M
    LEFT JOIN EFETIVO_EMP EA ON M.MONTH_START = EA.MONTH_START AND M.MONTH_END = EA.MONTH_END
    WHERE
        A.COD_EMP = '008'
    GROUP BY
        M.MONTH_START,
        M.MONTH_END,
        NVL(EA.EFETIVO_INICIAL_EMP, 0),
        NVL(EA.EFETIVO_FINAL_EMP, 0)
)
SELECT
    E.MONTH_START,
    E.MONTH_END,
    SUM(E.ATIVOS_ATUAIS_EMP) AS ATIVOS_ATUAIS_EMP,
    SUM(E.AFAST_PERIODO_EMP) AS AFAST_PERIODO_EMP,
    SUM(E.ATIVOS_PERIODO_EMP) AS ATIVOS_PERIODO_EMP,
    SUM(E.ADMITIDOS_EMP) AS ADMITIDOS_EMP,
    SUM(E.DEMITIDOS_EMP) AS DEMITIDOS_EMP,
    SUM(E.EFETIVO_INICIAL_EMP) AS EFETIVO_INICIAL_EMP,
    SUM(E.EFETIVO_FINAL_EMP) AS EFETIVO_FINAL_EMP,
    (SUM(E.EFETIVO_INICIAL_EMP) + SUM(E.EFETIVO_FINAL_EMP)) / 2 AS EFETIVO_MEDIO_EMP,
    ROUND(CASE WHEN (SUM(E.EFETIVO_INICIAL_EMP) + SUM(E.EFETIVO_FINAL_EMP)) / 2 = 0 THEN 0 ELSE (SUM(E.DEMITIDOS_EMP) * 100) / ((SUM(E.EFETIVO_INICIAL_EMP) + SUM(E.EFETIVO_FINAL_EMP)) / 2) END, 2) AS TURNOVER_EMP,
    'Referência: ' || TO_CHAR(MONTH_START, 'DD/MM/YYYY') || ' à ' || TO_CHAR(MONTH_END, 'DD/MM/YYYY') AS REFERENCIA,
    'Período informado: ' || TO_DATE('01/01/2024', 'DD/MM/YYYY') || ' à ' || TO_DATE('31/05/2024', 'DD/MM/YYYY') AS PERIODO
FROM
    DATEMETRICS_EMP E
GROUP BY
    E.MONTH_START,
    E.MONTH_END
ORDER BY
    E.MONTH_START;



--==============================================--

--======VERSÃO COM PARÂMETRO DE DATA INFORMADO --EMP








