CTEs PARA RELATÓRIO VALORES RESCISÕES


WITH Rescisao_Valores AS (
    SELECT 
        TO_CHAR(B.DATA_INI_MOV, 'MM/YYYY') AS MES_ANO,
        
        -- Valor total de rescisão
        SUM(TO_NUMBER(A.VALOR_VD)) AS VLR_TOT_RESCISAO,
        
        -- Valor de rescisão específico para cada causa de demissão
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 10 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_10,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 11 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_11,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 12 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_12,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 13 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_13,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 14 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_14,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 21 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_21,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 33 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_33
        
    FROM 
        RHFP1006 A
    INNER JOIN 
        RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
    LEFT JOIN 
        RHFP0300 C ON A.COD_CONTRATO = C.COD_CONTRATO AND C.DATA_FIM IS NOT NULL
    WHERE 
        B.DATA_INI_MOV >= '01/01/2024'
        AND B.DATA_INI_MOV <= '31/10/2024'
        AND B.COD_EVENTO = 17
        AND A.COD_VD = 1003
    GROUP BY 
        TO_CHAR(B.DATA_INI_MOV, 'MM/YYYY')
),

Demissoes_Causas AS (
    SELECT 
        TO_CHAR(TO_DATE(DATA_RESCISAO, 'MM/YYYY'), 'MM/YYYY') AS MES_ANO,
        
        -- Contagem das demissões por causa
        SUM(DEMISSAO_COD_10) AS DEMISSAO_COD_10,
        SUM(DEMISSAO_COD_11) AS DEMISSAO_COD_11,
        SUM(DEMISSAO_COD_12) AS DEMISSAO_COD_12,
        SUM(DEMISSAO_COD_13) AS DEMISSAO_COD_13,
        SUM(DEMISSAO_COD_14) AS DEMISSAO_COD_14,
        SUM(DEMISSAO_COD_21) AS DEMISSAO_COD_21,
        SUM(DEMISSAO_COD_33) AS DEMISSAO_COD_33,
        
        -- Total de demissões para o mês
        SUM(TOTAL_DEMISSOES) AS TOTAL_DEMISSOES
    FROM 
        V_QTDE_DEMISSOES_AVT
    WHERE 
        TO_DATE(DATA_RESCISAO, 'MM/YYYY') BETWEEN TO_DATE('01/2024', 'MM/YYYY') AND TO_DATE('10/2024', 'MM/YYYY')
    GROUP BY 
        TO_CHAR(TO_DATE(DATA_RESCISAO, 'MM/YYYY'), 'MM/YYYY')
),

Totais AS (
    SELECT 
        -- Total geral de valor de rescisão
        SUM(R.VLR_TOT_RESCISAO) AS TOTAL_VLR_TOT_RESCISAO,
        
        -- Totais gerais para quantidade, valor e percentuais de cada causa de demissão
        SUM(D.DEMISSAO_COD_10) AS TOTAL_DEMISSAO_COD_10,
        SUM(R.VLR_RESCISAO_COD_10) AS TOTAL_VLR_RESCISAO_COD_10,
        ROUND(SUM(R.VLR_RESCISAO_COD_10) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_10,
        
        SUM(D.DEMISSAO_COD_11) AS TOTAL_DEMISSAO_COD_11,
        SUM(R.VLR_RESCISAO_COD_11) AS TOTAL_VLR_RESCISAO_COD_11,
        ROUND(SUM(R.VLR_RESCISAO_COD_11) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_11,
        
        SUM(D.DEMISSAO_COD_12) AS TOTAL_DEMISSAO_COD_12,
        SUM(R.VLR_RESCISAO_COD_12) AS TOTAL_VLR_RESCISAO_COD_12,
        ROUND(SUM(R.VLR_RESCISAO_COD_12) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_12,
        
        SUM(D.DEMISSAO_COD_13) AS TOTAL_DEMISSAO_COD_13,
        SUM(R.VLR_RESCISAO_COD_13) AS TOTAL_VLR_RESCISAO_COD_13,
        ROUND(SUM(R.VLR_RESCISAO_COD_13) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_13,
        
        SUM(D.DEMISSAO_COD_14) AS TOTAL_DEMISSAO_COD_14,
        SUM(R.VLR_RESCISAO_COD_14) AS TOTAL_VLR_RESCISAO_COD_14,
        ROUND(SUM(R.VLR_RESCISAO_COD_14) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_14,
        
        SUM(D.DEMISSAO_COD_21) AS TOTAL_DEMISSAO_COD_21,
        SUM(R.VLR_RESCISAO_COD_21) AS TOTAL_VLR_RESCISAO_COD_21,
        ROUND(SUM(R.VLR_RESCISAO_COD_21) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_21,
        
        SUM(D.DEMISSAO_COD_33) AS TOTAL_DEMISSAO_COD_33,
        SUM(R.VLR_RESCISAO_COD_33) AS TOTAL_VLR_RESCISAO_COD_33,
        ROUND(SUM(R.VLR_RESCISAO_COD_33) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2) AS TOTAL_PERC_COD_33,
        
        -- Total de demissões geral e cálculo do percentual total dos totais gerais
        SUM(D.TOTAL_DEMISSOES) AS TOTAL_TOTAL_DEMISSOES,
        ROUND(
            (SUM(R.VLR_RESCISAO_COD_10) + SUM(R.VLR_RESCISAO_COD_11) + SUM(R.VLR_RESCISAO_COD_12) +
             SUM(R.VLR_RESCISAO_COD_13) + SUM(R.VLR_RESCISAO_COD_14) + SUM(R.VLR_RESCISAO_COD_21) +
             SUM(R.VLR_RESCISAO_COD_33)) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2
        ) AS TOTAL_PERCENTUAL_GERAL
        
    FROM 
        Rescisao_Valores R
    LEFT JOIN 
        Demissoes_Causas D ON R.MES_ANO = D.MES_ANO
)

SELECT 
    R.MES_ANO,
    TO_CHAR(R.VLR_TOT_RESCISAO, 'FM999G999G990D00') AS VLR_TOT_RESCISAO,
    
    D.DEMISSAO_COD_10,
    TO_CHAR(R.VLR_RESCISAO_COD_10, 'FM999G999G990D00') AS VLR_RESCISAO_COD_10,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_10 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_10,
    
    D.DEMISSAO_COD_11,
    TO_CHAR(R.VLR_RESCISAO_COD_11, 'FM999G999G990D00') AS VLR_RESCISAO_COD_11,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_11 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_11,
    
    D.DEMISSAO_COD_12,
    TO_CHAR(R.VLR_RESCISAO_COD_12, 'FM999G999G990D00') AS VLR_RESCISAO_COD_12,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_12 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_12,
    
    D.DEMISSAO_COD_13,
    TO_CHAR(R.VLR_RESCISAO_COD_13, 'FM999G999G990D00') AS VLR_RESCISAO_COD_13,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_13 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_13,
    
    D.DEMISSAO_COD_14,
    TO_CHAR(R.VLR_RESCISAO_COD_14, 'FM999G999G990D00') AS VLR_RESCISAO_COD_14,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_14 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_14,
    
    D.DEMISSAO_COD_21,
    TO_CHAR(R.VLR_RESCISAO_COD_21, 'FM999G999G990D00') AS VLR_RESCISAO_COD_21,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_21 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_21,
    
    D.DEMISSAO_COD_33,
    TO_CHAR(R.VLR_RESCISAO_COD_33, 'FM999G999G990D00') AS VLR_RESCISAO_COD_33,
    TO_CHAR(ROUND(R.VLR_RESCISAO_COD_33 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_33,
    
    D.TOTAL_DEMISSOES,
    
    -- Coluna de Percentual Total para cada mês
    TO_CHAR(
        ROUND(
            (R.VLR_RESCISAO_COD_10 + R.VLR_RESCISAO_COD_11 + R.VLR_RESCISAO_COD_12 +
             R.VLR_RESCISAO_COD_13 + R.VLR_RESCISAO_COD_14 + R.VLR_RESCISAO_COD_21 +
             R.VLR_RESCISAO_COD_33) * 100.0 / R.VLR_TOT_RESCISAO, 2
        ), 'FM990.00'
    ) || '%' AS PERCENTUAL_TOTAL,
    
    -- Totais em colunas
    TO_CHAR(T.TOTAL_VLR_TOT_RESCISAO, 'FM999G999G990D00') AS TOTAL_VLR_TOT_RESCISAO,
    T.TOTAL_DEMISSAO_COD_10 AS TOTAL_DEMISSAO_COD_10,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_10, 'FM999G999G990D00') AS TOTAL_VLR_RESCISAO_COD_10,
    TO_CHAR(T.TOTAL_PERC_COD_10, 'FM990.00') || '%' AS TOTAL_PERC_COD_10,
    
    T.TOTAL_DEMISSAO_COD_11 AS TOTAL_DEMISSAO_COD_11,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_11, 'FM999G999G990D00') AS TOTAL_VLR_RESCISAO_COD_11,
    TO_CHAR(T.TOTAL_PERC_COD_11, 'FM990.00') || '%' AS TOTAL_PERC_COD_11,
    
    T.TOTAL_DEMISSAO_COD_12 AS TOTAL_DEMISSAO_COD_12,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_12, 'FM999G999G990D00') AS TOTAL_VLR_RESCISAO_COD_12,
    TO_CHAR(T.TOTAL_PERC_COD_12, 'FM990.00') || '%' AS TOTAL_PERC_COD_12,
    
    T.TOTAL_DEMISSAO_COD_13 AS TOTAL_DEMISSAO_COD_13,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_13, 'FM999G999G990D00') AS TOTAL_VLR_RESCISAO_COD_13,
    TO_CHAR(T.TOTAL_PERC_COD_13, 'FM990.00') || '%' AS TOTAL_PERC_COD_13,
    
    T.TOTAL_DEMISSAO_COD_14 AS TOTAL_DEMISSAO_COD_14,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_14, 'FM999G999G990D00') AS TOTAL_VLR_RESCISAO_COD_14,
    TO_CHAR(T.TOTAL_PERC_COD_14, 'FM990.00') || '%' AS TOTAL_PERC_COD_14,
    
    T.TOTAL_DEMISSAO_COD_21 AS TOTAL_DEMISSAO_COD_21,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_21, 'FM999G999G990D00') AS TOTAL_VLR_RESCISAO_COD_21,
    TO_CHAR(T.TOTAL_PERC_COD_21, 'FM990.00') || '%' AS TOTAL_PERC_COD_21,
    
    T.TOTAL_DEMISSAO_COD_33 AS TOTAL_DEMISSAO_COD_33,
    TO_CHAR(T.TOTAL_VLR_RESCISAO_COD_33, 'FM999G999G990D00') AS TOTAL_VLR_RESCISAO_COD_33,
    TO_CHAR(T.TOTAL_PERC_COD_33, 'FM990.00') || '%' AS TOTAL_PERC_COD_33,
    
    T.TOTAL_TOTAL_DEMISSOES AS TOTAL_TOTAL_DEMISSOES,
    
    -- Novo campo: percentual total para os totais gerais
    TO_CHAR(T.TOTAL_PERCENTUAL_GERAL, 'FM990.00') || '%' AS TOTAL_PERCENTUAL_GERAL

FROM 
    Rescisao_Valores R
LEFT JOIN 
    Demissoes_Causas D ON R.MES_ANO = D.MES_ANO
CROSS JOIN 
    Totais T
ORDER BY 
    R.MES_ANO;



--===oficial


WITH Rescisao_Valores AS (
    SELECT 
        TO_CHAR(B.DATA_INI_MOV, 'MM/YYYY') AS MES_ANO,
        
        -- Valor total de rescisão
        SUM(TO_NUMBER(A.VALOR_VD)) AS VLR_TOT_RESCISAO,
        
        -- Valor de rescisão específico para cada causa de demissão
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 10 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_10,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 11 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_11,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 12 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_12,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 13 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_13,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 14 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_14,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 21 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_21,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 33 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_33
        
    FROM 
        RHFP1006 A
    INNER JOIN 
        RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
     LEFT JOIN RHFP0300 C ON A.COD_CONTRATO = C.COD_CONTRATO AND C.DATA_FIM IS NOT NULL
    WHERE 
        B.DATA_INI_MOV >= '01/01/2024'
        AND B.DATA_INI_MOV <= '31/10/2024'
        AND B.COD_EVENTO = 17
        AND A.COD_VD = 1003
    GROUP BY 
        TO_CHAR(B.DATA_INI_MOV, 'MM/YYYY')
),

Demissoes_Causas AS (
    SELECT 
        TO_CHAR(TO_DATE(DATA_RESCISAO, 'MM/YYYY'), 'MM/YYYY') AS MES_ANO,
        
        SUM(DEMISSAO_COD_10) AS RESC_COM_JUSTA_CAUSA,
        SUM(DEMISSAO_COD_11) AS RESC_SEM_JUSTA_CAUSA,
        SUM(DEMISSAO_COD_12) AS RESC_TERM_CONT_TRAB,
        SUM(DEMISSAO_COD_13) AS RESC_ANTEC_TERM_CONT_TRAB,
        SUM(DEMISSAO_COD_14) AS DEMISSAO_COD_14,
        SUM(DEMISSAO_COD_21) AS DEMISSAO_COD_21,
        SUM(DEMISSAO_COD_33) AS DEMISSAO_COD_33,
        
        SUM(TOTAL_DEMISSOES) AS TOTAL_DEMISSOES
    FROM 
        V_QTDE_DEMISSOES_AVT
    WHERE 
        TO_DATE(DATA_RESCISAO, 'MM/YYYY') BETWEEN TO_DATE('01/2024', 'MM/YYYY') AND TO_DATE('10/2024', 'MM/YYYY')
    GROUP BY 
        TO_CHAR(TO_DATE(DATA_RESCISAO, 'MM/YYYY'), 'MM/YYYY')
),

Totais AS (
    SELECT 
        'Total Geral' AS MES_ANO,
        SUM(R.VLR_TOT_RESCISAO) AS VLR_TOT_RESCISAO,
        
        SUM(D.DEMISSAO_COD_10) AS DEMISSAO_COD_10,
        SUM(R.VLR_RESCISAO_COD_10) AS VLR_RESCISAO_COD_10,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_10) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_10,
        
        SUM(D.DEMISSAO_COD_11) AS DEMISSAO_COD_11,
        SUM(R.VLR_RESCISAO_COD_11) AS VLR_RESCISAO_COD_11,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_11) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_11,
        
        SUM(D.DEMISSAO_COD_12) AS DEMISSAO_COD_12,
        SUM(R.VLR_RESCISAO_COD_12) AS VLR_RESCISAO_COD_12,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_12) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_12,
        
        SUM(D.DEMISSAO_COD_13) AS DEMISSAO_COD_13,
        SUM(R.VLR_RESCISAO_COD_13) AS VLR_RESCISAO_COD_13,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_13) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_13,
        
        SUM(D.DEMISSAO_COD_14) AS DEMISSAO_COD_14,
        SUM(R.VLR_RESCISAO_COD_14) AS VLR_RESCISAO_COD_14,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_14) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_14,
        
        SUM(D.DEMISSAO_COD_21) AS DEMISSAO_COD_21,
        SUM(R.VLR_RESCISAO_COD_21) AS VLR_RESCISAO_COD_21,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_21) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_21,
        
        SUM(D.DEMISSAO_COD_33) AS DEMISSAO_COD_33,
        SUM(R.VLR_RESCISAO_COD_33) AS VLR_RESCISAO_COD_33,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_33) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_33,
        
        SUM(D.TOTAL_DEMISSOES) AS TOTAL_DEMISSOES,
        
        -- Cálculo dinâmico do PERCENTUAL_TOTAL para o Total Geral
        TO_CHAR(
            ROUND(
                (SUM(R.VLR_RESCISAO_COD_10) + SUM(R.VLR_RESCISAO_COD_11) + SUM(R.VLR_RESCISAO_COD_12) +
                 SUM(R.VLR_RESCISAO_COD_13) + SUM(R.VLR_RESCISAO_COD_14) + SUM(R.VLR_RESCISAO_COD_21) +
                 SUM(R.VLR_RESCISAO_COD_33)) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2
            ), 'FM990.00'
        ) || '%' AS PERCENTUAL_TOTAL
        
    FROM 
        Rescisao_Valores R
    LEFT JOIN 
        Demissoes_Causas D ON R.MES_ANO = D.MES_ANO
)

-- União dos resultados mensais com a linha de "Total Geral"
SELECT *
FROM (
    SELECT 
        R.MES_ANO,
        TO_CHAR(R.VLR_TOT_RESCISAO, 'FM999G999G990D00') AS VLR_TOT_RESCISAO,
        
        D.DEMISSAO_COD_10,
        TO_CHAR(R.VLR_RESCISAO_COD_10, 'FM999G999G990D00') AS VLR_RESCISAO_COD_10,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_10 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_10,
        
        D.DEMISSAO_COD_11,
        TO_CHAR(R.VLR_RESCISAO_COD_11, 'FM999G999G990D00') AS VLR_RESCISAO_COD_11,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_11 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_11,
        
        D.DEMISSAO_COD_12,
        TO_CHAR(R.VLR_RESCISAO_COD_12, 'FM999G999G990D00') AS VLR_RESCISAO_COD_12,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_12 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_12,
        
        D.DEMISSAO_COD_13,
        TO_CHAR(R.VLR_RESCISAO_COD_13, 'FM999G999G990D00') AS VLR_RESCISAO_COD_13,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_13 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_13,
        
        D.DEMISSAO_COD_14,
        TO_CHAR(R.VLR_RESCISAO_COD_14, 'FM999G999G990D00') AS VLR_RESCISAO_COD_14,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_14 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_14,
        
        D.DEMISSAO_COD_21,
        TO_CHAR(R.VLR_RESCISAO_COD_21, 'FM999G999G990D00') AS VLR_RESCISAO_COD_21,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_21 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_21,
        
        D.DEMISSAO_COD_33,
        TO_CHAR(R.VLR_RESCISAO_COD_33, 'FM999G999G990D00') AS VLR_RESCISAO_COD_33,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_33 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_33,
        
        D.TOTAL_DEMISSOES,
        
        -- Cálculo dinâmico do PERCENTUAL_TOTAL para cada mês
        TO_CHAR(
            ROUND(
                (R.VLR_RESCISAO_COD_10 + R.VLR_RESCISAO_COD_11 + R.VLR_RESCISAO_COD_12 +
                 R.VLR_RESCISAO_COD_13 + R.VLR_RESCISAO_COD_14 + R.VLR_RESCISAO_COD_21 +
                 R.VLR_RESCISAO_COD_33) * 100.0 / R.VLR_TOT_RESCISAO, 2
            ), 'FM990.00'
        ) || '%' AS PERCENTUAL_TOTAL

    FROM 
        Rescisao_Valores R
    LEFT JOIN 
        Demissoes_Causas D ON R.MES_ANO = D.MES_ANO

    UNION ALL

    SELECT 
        T.MES_ANO,
        TO_CHAR(T.VLR_TOT_RESCISAO, 'FM999G999G990D00') AS VLR_TOT_RESCISAO,
        
        T.DEMISSAO_COD_10,
        TO_CHAR(T.VLR_RESCISAO_COD_10, 'FM999G999G990D00') AS VLR_RESCISAO_COD_10,
        T.PERC_COD_10,
        
        T.DEMISSAO_COD_11,
        TO_CHAR(T.VLR_RESCISAO_COD_11, 'FM999G999G990D00') AS VLR_RESCISAO_COD_11,
        T.PERC_COD_11,
        
        T.DEMISSAO_COD_12,
        TO_CHAR(T.VLR_RESCISAO_COD_12, 'FM999G999G990D00') AS VLR_RESCISAO_COD_12,
        T.PERC_COD_12,
        
        T.DEMISSAO_COD_13,
        TO_CHAR(T.VLR_RESCISAO_COD_13, 'FM999G999G990D00') AS VLR_RESCISAO_COD_13,
        T.PERC_COD_13,
        
        T.DEMISSAO_COD_14,
        TO_CHAR(T.VLR_RESCISAO_COD_14, 'FM999G999G990D00') AS VLR_RESCISAO_COD_14,
        T.PERC_COD_14,
        
        T.DEMISSAO_COD_21,
        TO_CHAR(T.VLR_RESCISAO_COD_21, 'FM999G999G990D00') AS VLR_RESCISAO_COD_21,
        T.PERC_COD_21,
        
        T.DEMISSAO_COD_33,
        TO_CHAR(T.VLR_RESCISAO_COD_33, 'FM999G999G990D00') AS VLR_RESCISAO_COD_33,
        T.PERC_COD_33,
        
        T.TOTAL_DEMISSOES,

        -- Percentual total dinâmico para a linha de total geral
        T.PERCENTUAL_TOTAL

    FROM 
        Totais T
)
ORDER BY 
    CASE WHEN MES_ANO = 'Total Geral' THEN 1 ELSE 0 END,
    MES_ANO;


    
















WITH Rescisao_Valores AS (
    SELECT
        TO_CHAR(B.DATA_INI_MOV, 'MM/YYYY') AS MES_ANO,

        -- Valor total de rescisão
        SUM(TO_NUMBER(A.VALOR_VD)) AS VLR_TOT_RESCISAO,

        -- Valor de rescisão específico para cada causa de demissão
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 10 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_10,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 11 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_11,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 12 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_12,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 13 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_13,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 14 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_14,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 21 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_21,
        SUM(CASE WHEN C.COD_CAUSA_DEMISSAO = 33 THEN TO_NUMBER(A.VALOR_VD) ELSE 0 END) AS VLR_RESCISAO_COD_33

    FROM
        RHFP1006 A
    INNER JOIN
        RHFP1003 B ON A.COD_MESTRE_EVENTO = B.COD_MESTRE_EVENTO
     LEFT JOIN RHFP0300 C ON A.COD_CONTRATO = C.COD_CONTRATO AND C.DATA_FIM IS NOT NULL
    WHERE
        B.DATA_INI_MOV >= TRUNC(TO_DATE(:MES_ANO_INICIO, 'MM/YYYY'), 'MM') -- Primeiro dia do mês inicial
        AND B.DATA_INI_MOV <= LAST_DAY(TO_DATE(:MES_ANO_FIM, 'MM/YYYY'))  -- Último dia do mês final
        AND B.COD_EVENTO = 17
        AND A.COD_VD = 1003
    GROUP BY
        TO_CHAR(B.DATA_INI_MOV, 'MM/YYYY')
),

Demissoes_Causas AS (
    SELECT
        TO_CHAR(TO_DATE(DATA_RESCISAO, 'MM/YYYY'), 'MM/YYYY') AS MES_ANO,

        SUM(DEMISSAO_COD_10) AS DEMISSAO_COD_10,
        SUM(DEMISSAO_COD_11) AS DEMISSAO_COD_11,
        SUM(DEMISSAO_COD_12) AS DEMISSAO_COD_12,
        SUM(DEMISSAO_COD_13) AS DEMISSAO_COD_13,
        SUM(DEMISSAO_COD_14) AS DEMISSAO_COD_14,
        SUM(DEMISSAO_COD_21) AS DEMISSAO_COD_21,
        SUM(DEMISSAO_COD_33) AS DEMISSAO_COD_33,

        SUM(TOTAL_DEMISSOES) AS TOTAL_DEMISSOES
    FROM
        V_QTDE_DEMISSOES_AVT
    WHERE
        TO_DATE(DATA_RESCISAO, 'MM/YYYY') BETWEEN TRUNC(TO_DATE(:MES_ANO_INICIO, 'MM/YYYY'), 'MM')
        AND LAST_DAY(TO_DATE(:MES_ANO_FIM, 'MM/YYYY'))
    GROUP BY
        TO_CHAR(TO_DATE(DATA_RESCISAO, 'MM/YYYY'), 'MM/YYYY')
),

Totais AS (
    SELECT
        'Total Geral' AS MES_ANO,
        SUM(R.VLR_TOT_RESCISAO) AS VLR_TOT_RESCISAO,

        SUM(D.DEMISSAO_COD_10) AS DEMISSAO_COD_10,
        SUM(R.VLR_RESCISAO_COD_10) AS VLR_RESCISAO_COD_10,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_10) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_10,

        SUM(D.DEMISSAO_COD_11) AS DEMISSAO_COD_11,
        SUM(R.VLR_RESCISAO_COD_11) AS VLR_RESCISAO_COD_11,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_11) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_11,

        SUM(D.DEMISSAO_COD_12) AS DEMISSAO_COD_12,
        SUM(R.VLR_RESCISAO_COD_12) AS VLR_RESCISAO_COD_12,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_12) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_12,

        SUM(D.DEMISSAO_COD_13) AS DEMISSAO_COD_13,
        SUM(R.VLR_RESCISAO_COD_13) AS VLR_RESCISAO_COD_13,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_13) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_13,

        SUM(D.DEMISSAO_COD_14) AS DEMISSAO_COD_14,
        SUM(R.VLR_RESCISAO_COD_14) AS VLR_RESCISAO_COD_14,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_14) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_14,

        SUM(D.DEMISSAO_COD_21) AS DEMISSAO_COD_21,
        SUM(R.VLR_RESCISAO_COD_21) AS VLR_RESCISAO_COD_21,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_21) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_21,

        SUM(D.DEMISSAO_COD_33) AS DEMISSAO_COD_33,
        SUM(R.VLR_RESCISAO_COD_33) AS VLR_RESCISAO_COD_33,
        TO_CHAR(ROUND(SUM(R.VLR_RESCISAO_COD_33) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2), 'FM990.00') || '%' AS PERC_COD_33,

        SUM(D.TOTAL_DEMISSOES) AS TOTAL_DEMISSOES,

        -- Cálculo dinâmico do PERCENTUAL_TOTAL para o Total Geral
        TO_CHAR(
            ROUND(
                (SUM(R.VLR_RESCISAO_COD_10) + SUM(R.VLR_RESCISAO_COD_11) + SUM(R.VLR_RESCISAO_COD_12) +
                 SUM(R.VLR_RESCISAO_COD_13) + SUM(R.VLR_RESCISAO_COD_14) + SUM(R.VLR_RESCISAO_COD_21) +
                 SUM(R.VLR_RESCISAO_COD_33)) * 100.0 / SUM(R.VLR_TOT_RESCISAO), 2
            ), 'FM990.00'
        ) || '%' AS PERCENTUAL_TOTAL

    FROM
        Rescisao_Valores R
    LEFT JOIN
        Demissoes_Causas D ON R.MES_ANO = D.MES_ANO
)

SELECT
    'Referência' AS MES_ANO,
    'Valor total das Rescisões por Mês e o Total Geral' AS VLR_TOT_RESCISAO,
    NULL AS R_C_J_C_I_EMP,
    'Causa 10 = Resc. COM Justa causa - Inici. da Empresa' AS VLR_R_C_J_C_I_EMP,
    NULL AS PERC_R_C_J_C_I_EMP,
    NULL AS R_S_J_C_I_COLAB,
    'Causa 11 = Resc. SEM Justa causa - Inici. do Empregado' AS VLR_RESCISAO_COD_11,
    NULL AS PERC_COD_11,
    NULL AS DEMISSAO_COD_12,
    'Causa 12 = Resc. por Término do Contrato de Trabalho' AS VLR_RESCISAO_COD_12,
    NULL AS PERC_COD_12,
    NULL AS DEMISSAO_COD_13,
    'Causa 13 = Antec. Term. Cont. de Trabalho Inici. da Empresa' AS VLR_RESCISAO_COD_13,
    NULL AS PERC_COD_13,
    NULL AS DEMISSAO_COD_14,
    'Causa 14 = Antec. Term. Cont. de Trabalho Inici. do Empregado' AS VLR_RESCISAO_COD_14,
    NULL AS PERC_COD_13,
    NULL AS DEMISSAO_COD_21,
    'Causa 21 = Pedido de Demissão' AS VLR_RESCISAO_COD_21,
    NULL AS PERC_COD_21,
    NULL AS DEMISSAO_COD_33,
    'Causa 33 = Resc. por ACORDO entre as partes' AS VLR_RESCISAO_COD_33,
    NULL AS PERC_COD_13,
    NULL AS TOTAL_DEMISSOES,
    NULL AS PERCENTUAL_TOTAL
FROM DUAL

UNION ALL
-- União dos resultados mensais com a linha de "Total Geral"
SELECT *
FROM (
    SELECT
        R.MES_ANO,
        TO_CHAR(R.VLR_TOT_RESCISAO, 'FM999G999G990D00') AS VLR_TOT_RESCISAO,

        D.DEMISSAO_COD_10 AS DEM_COD_10,
        TO_CHAR(R.VLR_RESCISAO_COD_10, 'FM999G999G990D00') AS VLR_DEM_COD_10,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_10 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_10,

        D.DEMISSAO_COD_11 AS DEM_COD_11,
        TO_CHAR(R.VLR_RESCISAO_COD_11, 'FM999G999G990D00') AS VLR_RESCISAO_COD_11,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_11 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_11,

        D.DEMISSAO_COD_12,
        TO_CHAR(R.VLR_RESCISAO_COD_12, 'FM999G999G990D00') AS VLR_RESCISAO_COD_12,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_12 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_12,

        D.DEMISSAO_COD_13,
        TO_CHAR(R.VLR_RESCISAO_COD_13, 'FM999G999G990D00') AS VLR_RESCISAO_COD_13,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_13 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_13,

        D.DEMISSAO_COD_14,
        TO_CHAR(R.VLR_RESCISAO_COD_14, 'FM999G999G990D00') AS VLR_RESCISAO_COD_14,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_14 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_14,

        D.DEMISSAO_COD_21,
        TO_CHAR(R.VLR_RESCISAO_COD_21, 'FM999G999G990D00') AS VLR_RESCISAO_COD_21,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_21 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_21,

        D.DEMISSAO_COD_33,
        TO_CHAR(R.VLR_RESCISAO_COD_33, 'FM999G999G990D00') AS VLR_RESCISAO_COD_33,
        TO_CHAR(ROUND(R.VLR_RESCISAO_COD_33 * 100.0 / R.VLR_TOT_RESCISAO, 2), 'FM990.00') || '%' AS PERC_COD_33,

        D.TOTAL_DEMISSOES,

        -- Cálculo dinâmico do PERCENTUAL_TOTAL para cada mês
        TO_CHAR(
            ROUND(
                (R.VLR_RESCISAO_COD_10 + R.VLR_RESCISAO_COD_11 + R.VLR_RESCISAO_COD_12 +
                 R.VLR_RESCISAO_COD_13 + R.VLR_RESCISAO_COD_14 + R.VLR_RESCISAO_COD_21 +
                 R.VLR_RESCISAO_COD_33) * 100.0 / R.VLR_TOT_RESCISAO, 2
            ), 'FM990.00'
        ) || '%' AS PERCENTUAL_TOTAL

    FROM
        Rescisao_Valores R
    LEFT JOIN
        Demissoes_Causas D ON R.MES_ANO = D.MES_ANO

    UNION ALL

    SELECT
        T.MES_ANO,
        TO_CHAR(T.VLR_TOT_RESCISAO, 'FM999G999G990D00') AS VLR_TOT_RESCISAO,

        T.DEMISSAO_COD_10,
        TO_CHAR(T.VLR_RESCISAO_COD_10, 'FM999G999G990D00') AS VLR_RESCISAO_COD_10,
        T.PERC_COD_10,

        T.DEMISSAO_COD_11,
        TO_CHAR(T.VLR_RESCISAO_COD_11, 'FM999G999G990D00') AS VLR_RESCISAO_COD_11,
        T.PERC_COD_11,

        T.DEMISSAO_COD_12,
        TO_CHAR(T.VLR_RESCISAO_COD_12, 'FM999G999G990D00') AS VLR_RESCISAO_COD_12,
        T.PERC_COD_12,

        T.DEMISSAO_COD_13,
        TO_CHAR(T.VLR_RESCISAO_COD_13, 'FM999G999G990D00') AS VLR_RESCISAO_COD_13,
        T.PERC_COD_13,

        T.DEMISSAO_COD_14,
        TO_CHAR(T.VLR_RESCISAO_COD_14, 'FM999G999G990D00') AS VLR_RESCISAO_COD_14,
        T.PERC_COD_14,

        T.DEMISSAO_COD_21,
        TO_CHAR(T.VLR_RESCISAO_COD_21, 'FM999G999G990D00') AS VLR_RESCISAO_COD_21,
        T.PERC_COD_21,

        T.DEMISSAO_COD_33,
        TO_CHAR(T.VLR_RESCISAO_COD_33, 'FM999G999G990D00') AS VLR_RESCISAO_COD_33,
        T.PERC_COD_33,

        T.TOTAL_DEMISSOES,

        -- Percentual total dinâmico para a linha de total geral
        T.PERCENTUAL_TOTAL

    FROM
        Totais T
)
ORDER BY
    CASE WHEN MES_ANO = 'Total Geral' THEN 1 ELSE 0 END,
    MES_ANO