--PROCESSO NECESSÁRIO PARA DELETAR UM REGISTRO DE EXAME MÉDICO DO CONTRATO 
  --NO MÓDULO >> MEDICINA E SEGURANÇA, NO MENU >>> MEDICINA NO TRABALHO, 
  --POR CONTA TE TER SIDO INSERIDO COM DATA INCORRETA E NÃO TER NENHUM ASO CADASTRADO PARA O MESMO

SELECT * FROM RHMS0285
WHERE COD_ASO = 11764;

SELECT * FROM RHMS0280
WHERE COD_ASO = 11764;

DELETE 
FROM RHMS0285
WHERE COD_ASO = 11764
AND COD_PESSOA = 83627

--UPDATE RHMS0280
--SET IND_APTIDAO = 'S'
--WHERE COD_ASO = 11764