--PROCESSO PARA DELETAR UMA REQUISIÇÃO DE PESSOAL QUE FOI CRIADA ERRADA.
 
--==================================--
 
SELECT * FROM RHRS0315
WHERE COD_REQUISICAO = 666;
 
DELETE 
FROM RHRS0315
WHERE COD_REQUISICAO = 666;
 
--====================================--
 
SELECT * FROM RHWF0255
WHERE COD_EXEC_PROC = 1897;
 
DELETE 
FROM RHWF0255
WHERE COD_EXEC_PROC = 1897;
 
 
--====================================--
 
SELECT * FROM RHWF0250
WHERE COD_EXEC_PROC = 1897;
 
DELETE 
FROM RHWF0250
WHERE COD_EXEC_PROC = 1897;
 
--===================================--
 
SELECT * FROM RHRS0200
WHERE COD_REQUISICAO = 666
 
DELETE 
FROM RHRS0200
WHERE COD_REQUISICAO = 666

