DELETE FROM RHRF0100
WHERE (DATA_REFEICAO, COD_CONTRATO, HORA_REFEICAO) IN (
    SELECT DATA_REFEICAO, COD_CONTRATO, MIN(HORA_REFEICAO)
    FROM RHRF0100
    WHERE DATA_REFEICAO BETWEEN '11/03/2024' AND '27/03/2024'
    AND COD_COLETOR = 1
    GROUP BY DATA_REFEICAO, COD_CONTRATO
)
AND COD_COLETOR = 1;