SELECT CTR.COD_CONTRATO, PF.NOME_PESSOA, CCO.COD_ORGANOGRAMA, AVT.COD_UNIDADE, AVT.DES_UNIDADE
  FROM RHFP0300 CTR,
       PESSOA_FISICA PF,
       RHFP0310 CCO,
       V_DADOS_ORGANOGRAMAS_AVT AVT
 WHERE (('01/01/2024' AND '31/01/2024' BETWEEN CTR.DATA_INICIO AND CTR.DATA_FIM)
       OR (CTR.DATA_INICIO <= '01/01/2024' AND CTR.DATA_FIM IS NULL))
   AND CTR.DATA_INICIO <= '01/01/2024'
   AND CTR.COD_CONTRATO = CCO.COD_CONTRATO
   AND PF.COD_PESSOA = CTR.COD_FUNC
   AND CCO.COD_ORGANOGRAMA = AVT.COD_ORGANOGRAMA
   AND '01/01/2024' BETWEEN CCO.DATA_INICIO AND CCO.DATA_FIM
   AND AVT.COD_UNIDADE = 159



--=====SQL 2 EXEMPLO===

SELECT CTR.COD_CONTRATO, PF.NOME_PESSOA, CCO.COD_ORGANOGRAMA
  FROM RHFP0300 CTR, RHFP0310 CCO, PESSOA_FISICA PF
 WHERE (('31/01/2024' BETWEEN CTR.DATA_INICIO AND CTR.DATA_FIM) OR
       (CTR.DATA_INICIO <= '31/01/2024' AND CTR.DATA_FIM IS NULL))
   AND CTR.COD_CONTRATO = CCO.COD_CONTRATO
   AND CTR.COD_FUNC = PF.COD_PESSOA
   AND '31/01/2024' BETWEEN CCO.DATA_INICIO AND CCO.DATA_FIM
   AND CCO.COD_ORGANOGRAMA = 645