/*PROCEDIMENTO PARA CRIAR CRACHÁS PROVISÓRIOS PARA OS TERCEIRIZADOS EM INSERÇÃO EM MASSA*/
INSERT INTO RHAF1109 (
    COD_CRACHA_PROV,
    NOME_CRACHA_PROV,
    DATA_INICIO,
    DATA_FIM,
    IND_VISITANTE,
    COD_MOTIVO,
    COD_MODULO,
    COD_SIMPLES
)
SELECT 
    710000 + LEVEL AS COD_CRACHA_PROV,
    'TERCEIROS' AS NOME_CRACHA_PROV,
    DATE '2025-04-01' AS DATA_INICIO,
    DATE '2999-12-31' AS DATA_FIM,
    'N' AS IND_VISITANTE,
    569 AS COD_MOTIVO,
    'AF' AS COD_MODULO,
    NULL AS COD_SIMPLES
FROM DUAL
CONNECT BY LEVEL <= 70;