--INSERTS TABELA RHFP0399 ÁREAS QUADRO E LOTAÇÕES - GRZZIOTIN

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(004, 'GRZ ERECHIM', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(014, 'GRZ SANTA ROSA', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(015, 'GRZ SANTO ANGELO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(019, 'GRZ CACHOEIRA', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(025, 'GRZ SANTA MARIA', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(034, 'GRZ BAGE', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(052, 'GRZ PATO BRANCO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(061, 'GRZ BENTO GONCALVES', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(282, 'GRZ SAO GABRIEL', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(466, 'GRZ AGUDO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(471, 'GRZ ESPUMOSO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(476, 'GRZ SANTO AUGUSTO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(482, 'GRZ LAGOA VERMELHA', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(488, 'GRZ NOVO HAMBURGO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(490, 'GRZ MONTENEGRO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(498, 'GRZ PASSO FUNDO II', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(504, 'GRZ CERRO LARGO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(508, 'GRZ MARAU', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(511, 'GRZ HORIZONTINA', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(520, 'GRZ NONOAI', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(524, 'GRZ TEUTONIA', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(529, 'GRZ PASSO FUNDO IV', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(530, 'GRZ SANTA MARIA II', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(531, 'GRZ PALMEIRA MISSOES', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(565, 'GRZ SAO MIGUEL D O', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(567, 'GRZ JAGUARAO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(568, 'GRZ RIO PARDO', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(575, 'GRZ CLEVELANDIA', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(606, 'GRZ GUARAPUAVA', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(615, 'GRZ PELOTAS', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(616, 'GRZ SARANDI', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(619, 'GRZ SAO JOAQUIM', 1);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(623, 'GRZ OSORIO', 1);
