--INSERTS TABELA RHFP0399 ÁREAS QUADRO E LOTAÇÕES - TOTTAL

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(033, 'TOT SANTO ANGELO', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(050, 'TOT SANTA ROSA', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(055, 'TOT CRUZ ALTA', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(057, 'TOT CARAZINHO', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(079, 'TOT FCO. BELTRAO', 4); 
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(084, 'TOT BENTO GONCALVES', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(094, 'TOT SAO BORJA', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(128, 'TOT SAO GABRIEL', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(187, 'TOT LAGOA VERMELHA', 4); 
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(205, 'TOT JAGUARAO', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(206, 'TOT ITAQUI', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(366, 'TOT QUARAI', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(371, 'TOT S.VITORIA PALMAR', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(392, 'TOT ARROIO GRANDE', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(402, 'TOT SANTA MARIA III', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(409, 'TOT PANAMBI', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(410, 'TOT SAO SEPE', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(414, 'TOT GIRUA', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(428, 'TOT LIVRAMENTO II', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(467, 'TOT ALEGRETE II', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(499, 'TOT PASSO FUNDO III', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(501, 'TOT ERECHIM', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(515, 'TOT PASSO FUNDO IV', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(519, 'TOT MARAU', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(554, 'TOT BAGE', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(590, 'TOT GUAPORE', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(611, 'TOT ESPUMOSO', 4);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(617, 'TOT SARANDI', 4);
