--INSERTS TABELA RHFP0399 ÁREAS QUADRO E LOTAÇÕES - PORMENOS

INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(016, 'PRM ARROIO GRANDE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(023, 'PRM SAO FCO DE ASSIS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(028, 'PRM NOVA PRATA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(040, 'PRM PELOTAS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(042, 'PRM S. LIVRAMENTO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(043, 'PRM SANTO AUGUSTO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(053, 'PRM PASSO FUNDO II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(054, 'PRM IBIRUBA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(064, 'PRM CANGUCU', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(073, 'PRM TRES COROAS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(074, 'PRM FRAIBURGO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(075, 'PRM DOIS VIZINHOS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(080, 'PRM QUARAI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(082, 'PRM TRIUNFO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(096, 'PRM STA. CRUZ DO SUL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(121, 'PRM SAO BORJA II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(124, 'PRM SANTO ANGELO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(125, 'PRM ERECHIM', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(129, 'PRM PALMEIRA MISSOES', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(154, 'PRM VACARIA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(155, 'PRM SAO LUIZ GONZAGA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(159, 'PRM PASSO FUNDO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(160, 'PRM CURITIBANOS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(163, 'PRM CRUZ ALTA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(177, 'PRM ROSARIO DO SUL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(184, 'PRM BAGE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(186, 'PRM SANTA ROSA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(199, 'PRM SANTIAGO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(219, 'PRM LAGOA VERMELHA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(227, 'PRM CACADOR', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(239, 'PRM SANTA MARIA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(242, 'PRM ALEGRETE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(243, 'PRM SAO GABRIEL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(259, 'PRM DOM PEDRITO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(261, 'PRM CACHOEIRA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(263, 'PRM ITAQUI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(264, 'PRM PANAMBI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(267, 'PRM CANOINHAS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(284, 'PRM MARAU', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(288, 'PRM MAFRA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(289, 'PRM JAGUARAO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(299, 'PRM CACAPAVA DO SUL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(306, 'PRM TAPEJARA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(307, 'PRM PASSO FUNDO III', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(309, 'PRM IJUI II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(310, 'PRM SANTO ANGELO II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(311, 'PRM FLORES DA CUNHA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(313, 'PRM SAO SEPE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(315, 'PRM S. PEDRO DO SUL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(316, 'PRM TAQUARI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(319, 'PRM CERRO LARGO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(322, 'PRM XAXIM', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(323, 'PRM SERAFINA CORREA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(324, 'PRM SAO MARCOS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(325, 'PRM HORIZONTINA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(326, 'PRM CACEQUI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(327, 'PRM BUTIA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(328, 'PRM CAMAQUA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(329, 'PRM CRISSIUMAL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(330, 'PRM SANTO CRISTO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(331, 'PRM S. LIVRAMENTO II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(332, 'PRM S. VITORIA PALMA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(333, 'PRM VERANOPOLIS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(334, 'PRM ESPUMOSO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(335, 'PRM ANTONIO PRADO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(336, 'PRM S. SEBASTIAO CAI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(337, 'PRM CANDELARIA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(338, 'PRM AGUDO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(339, 'PRM ROLANTE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(340, 'PRM JAGUARI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(341, 'PRM NAO ME TOQUE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(343, 'PRM SAO FCO DE PAULA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(344, 'PRM CHARQUEADAS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(348, 'PRM BARRACAO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(351, 'PRM PALMEIRA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(352, 'PRM MONTENEGRO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(354, 'PRM SARANDI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(356, 'PRM SANANDUVA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(358, 'PRM SANTA ROSA II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(359, 'PRM VIDEIRA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(360, 'PRM PORTO XAVIER', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(361, 'PRM STA BARBARA SUL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(362, 'PRM TENENTE PORTELA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(363, 'PRM VERA CRUZ', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(365, 'PRM TAPES', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(370, 'PRM STO. A. PATRULHA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(372, 'PRM CAPANEMA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(373, 'PRM NONOAI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(375, 'PRM OSORIO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(376, 'PRM PIRAI DO SUL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(377, 'PRM GETULIO VARGAS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(378, 'PRM SAO L. DOESTE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(379, 'PRM CORONEL VIVIDA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(380, 'PRM AMPERE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(381, 'PRM LARANJEIRAS DSUL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(383, 'PRM MARAVILHA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(384, 'PRM ARROIO DO MEIO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(387, 'PRM PALMAS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(391, 'PRM RIO PARDO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(393, 'PRM REALEZA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(397, 'PRM TEUTONIA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(401, 'PRM JULIO CASTILHOS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(403, 'PRM GUARAPUAVA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(404, 'PRM FREDERICO II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(407, 'PRM RESTINGA SECA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(408, 'PRM CLEVELANDIA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(418, 'PRM SAO MATEUS D SUL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(419, 'PRM SEBERI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(422, 'PRM XANXERE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(423, 'PRM CONSTANTINA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(427, 'PRM CORREIA PINTO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(433, 'PRM S.ANT.DA MISSOES', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(436, 'PRM OTACILIO COSTA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(440, 'PRM ABELARDO LUZ', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(444, 'PRM SOBRADINHO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(447, 'PRM URUGUAIANA II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(448, 'PRM TAQUARA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(449, 'PRM SAO JOAQUIM', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(450, 'PRM FAXINAL GUEDES', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(453, 'PRM RODEIO BONITO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(454, 'PRM ARVOREZINHA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(456, 'PRM ERVAL SECO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(457, 'PRM SAO DOMINGOS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(458, 'PRM ENCANTADO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(460, 'PRM SOLEDADE II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(465, 'PRM SAO JERONIMO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(468, 'PRM CRUZ ALTA III', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(469, 'PRM CARAZINHO III', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(472, 'PRM RONDA ALTA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(479, 'PRM TAPERA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(480, 'PRM TUPANCIRETA II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(483, 'PRM S MIGUEL DO ESTE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(497, 'PRM CORONEL BICACO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(507, 'PRM PIRATINI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(512, 'PRM ERECHIM II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(514, 'PRM PASSO FUNDO VI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(517, 'PRM DOIS VIZINHOS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(521, 'PRM PINHEIRO MACHADO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(527, 'PRM ESTRELA II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(528, 'PRM BARROS CASSAL', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(532, 'PRM CASCA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(533, 'PRM SANTA MARIA III', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(537, 'PRM SANTO ANGELO III', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(539, 'PRM BENTO GONCALVE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(542, 'PRM PALMITINHO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(545, 'PRM SELBACH', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(547, 'PRM GUARANI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(550, 'PRM PLANALTO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(552, 'PRM CATUIPE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(553, 'PRM BOSSOROCA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(557, 'PRM SALTO DO JACUI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(562, 'PRM CARLOS BARBOSA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(571, 'PRM MARMELEIRO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(573, 'PRM SANTO ANTONIO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(574, 'PRM VERANOPOLIS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(576, 'PRM SANTA ROSA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(578, 'PRM CHAPADA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(579, 'PRM VERA CRUZ II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(581, 'PRM PASSO FUNDO VII', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(585, 'PRM TUPARENDI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(593, 'PRM FONTOURA XAVIER', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(595, 'PRM CHAPECO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(596, 'PRM IJUI', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(603, 'PRM ENTRE IJUIS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(604, 'PRM SAO P.DAS MISSOE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(605, 'PRM ALEGRETE', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(610, 'PRM IBIRAIARAS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(613, 'PRM TRES DE MAIO II', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(618, 'PRM GAURAMA', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(621, 'PRM SERTAO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(622, 'PRM POUSO REDONDO', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(624, 'PRM CAMPOS NOVOS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(625, 'PRM SIDEROPOLIS', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(626, 'PRM MARAU', 2);
INSERT INTO RHFP0399 (COD_CLASSIFICACAO, NOME_CLASSIFICACAO, COD_AREA)
              VALUES(627, 'PRM ALECRIM', 2);
