SELECT A.COD_CONTRATO_RESP,
       E.NOME_PESSOA,
       A.COD_ORGANOGRAMA,
       B.DES_UNIDADE,
       D.COD_ORGANOGRAMA,
       CASE
         WHEN A.DATA_FIM = '31/12/2999' THEN
          'S'
         ELSE
          'N'
       END AS IND_RESP_UNI
  FROM RHFP0397 A
 INNER JOIN V_DADOS_LOJAS_AVT B ON A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
  LEFT JOIN RHFP0300 C ON A.COD_CONTRATO_RESP = C.COD_CONTRATO
  LEFT JOIN RHFP0310 D ON A.COD_CONTRATO_RESP = D.COD_CONTRATO
  LEFT JOIN PESSOA_FISICA E ON C.COD_FUNC = E.COD_PESSOA
 WHERE A.DATA_FIM = '31/12/2999'
   AND C.DATA_FIM IS NULL
   AND D.DATA_FIM = '31/12/2999'