SET TERMOUT ON HEADING ON FEEDBACK ON VERIFY ON LINESIZE 2000
accept FILE prompt "ARQUIVO: "
accept TABLENAME prompt "NOME DA TABELA: "
SET TERMOUT OFF HEADING OFF FEEDBACK OFF VERIFY OFF
SPOOL &&FILE

SELECT 'PROMPT CRIANDO SINONIMOS...'
FROM DUAL;

SELECT DISTINCT 'CREATE SYNONYM "' || COD_OPERADOR || '".' || '&&TABLENAME FOR '|| USER ||'.'||'&&TABLENAME;'
FROM OPERADOR OP, ALL_USERS AU
WHERE UPPER(AU.USERNAME) = OP.COD_OPERADOR;

SELECT 'PROMPT CONCEDENDO PRIVILEGIOS ...'
FROM DUAL;

SELECT DISTINCT 'GRANT ALL ON ' || USER || '.' || '&&TABLENAME TO "' || COD_OPERADOR || '" WITH GRANT OPTION;'
FROM OPERADOR OP, ALL_USERS AU
WHERE UPPER(AU.USERNAME) = OP.COD_OPERADOR;


SPOOL OFF
SET TERMOUT ON HEADING ON FEEDBACK ON VERIFY ON
@&&FILE
