/*PROCESSO PARA AJUSTAR A SEQUÊNCIA DO ORGANOGRAMA DO CONTRATO,
 POIS TAL CODIGO NÃO PODE DEIXAR DE CONTER NA TABELA PARA CADA CONTRATO*/

SELECT A.*, ROWID FROM RHFP0310 A
WHERE A.SEQ IS NULL

SELECT DISTINCT(SEQ) 
FROM RHFP0310

--===========

SELECT A.*, C.EDICAO_ORG
FROM RHFP0310 A
INNER JOIN RHFP0300 B ON A.COD_CONTRATO = B.COD_CONTRATO
INNER JOIN RHFP0401 C ON A.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
WHERE A.DATA_FIM = '31/12/2999'
AND B.DATA_FIM IS NULL
AND A.SEQ IS NULL
--AND A.COD_CONTRATO = 395287

--==========

UPDATE RHFP0310 A
SET SEQ = 1
WHERE A.DATA_FIM = '31/12/2999'
AND A.SEQ IS NULL
AND EXISTS (
    SELECT 1 
    FROM RHFP0300 B
    WHERE A.COD_CONTRATO = B.COD_CONTRATO
    AND B.DATA_FIM IS NULL
);
