PROCEDURES PARA INATIVAR E ATIVAR MOVIMENTAÇÕES NA WEB.


ROTINA DE INATIVAÇÃO

CREATE OR REPLACE PROCEDURE GRZ_FOLHA_INATIVA_MOV
AS
  wDataAtual DATE;
  dia_20 DATE;

  CURSOR C1 IS
    SELECT OP.COD_OPERADOR, OP.COD_CLIENTE, OP.COD_EMPRESA, OP.COD_PRODUTO, OP.COD_MODULO, OP.COD_MENU, OP.LIB_FUNCAO
    FROM OPERMENU OP, OPERADOR OPER
    WHERE OPER.COD_OPERADOR = OP.COD_OPERADOR
      AND OPER.COD_PERFIL = 21
      AND OP.COD_MENU = 'miWC257';
  r1 C1%ROWTYPE;

BEGIN
  wDataAtual := TRUNC(SYSDATE);
  dia_20 := TO_DATE('20/' || TO_CHAR(wDataAtual, 'MM/YYYY'), 'DD/MM/YYYY'); --A INATIVAÇÃO SERÁ REALIZADA A PARTIR DO DIA 20 (INCLUSIVE) 
                                                                            --INICIARÁ NO DIA 20 E EXECUTARÁ NO DIAS SUBSEQUÊNTES.
  IF wDataAtual >= dia_20 THEN
    FOR R1 IN C1 LOOP
      UPDATE OPERMENU
      SET LIB_FUNCAO = 17 -- PERMISSÃO SOMENTE DE CONSULTAS
      WHERE COD_MENU = 'miWC257'
        AND COD_OPERADOR = r1.COD_OPERADOR;
    END LOOP;
  END IF;
  -- COMMIT;
END GRZ_FOLHA_INATIVA_MOV;


--================================================--



ROTINA DE ATIVAÇÃO


CREATE OR REPLACE PROCEDURE GRZ_FOLHA_ATIVA_MOV
AS
  wDataAtual DATE;
  dia_20 DATE;

  CURSOR C1 IS
    SELECT OP.COD_OPERADOR, OP.COD_CLIENTE, OP.COD_EMPRESA, OP.COD_PRODUTO, OP.COD_MODULO, OP.COD_MENU, OP.LIB_FUNCAO
    FROM OPERMENU OP, OPERADOR OPER
    WHERE OPER.COD_OPERADOR = OP.COD_OPERADOR
      AND OPER.COD_PERFIL = 21
      AND OP.COD_MENU = 'miWC257';
  r1 C1%ROWTYPE;

BEGIN
  wDataAtual := TRUNC(SYSDATE);
  DIA_20 := TO_DATE('20/' || TO_CHAR(WDATAATUAL, 'MM/YYYY'), 'DD/MM/YYYY'); --EXECUTARÁ A PARTIR DO DIA 1 (INCLUSIVE) ATÉ O DIA 19

  IF wDataAtual < dia_20 THEN
    FOR R1 IN C1 LOOP
      UPDATE OPERMENU
      SET LIB_FUNCAO = 31 -- PERMISSÃO DE CONSULTAR, INSERIR, DELETAR E EDITAR
      WHERE COD_MENU = 'miWC257'
        AND COD_OPERADOR = r1.COD_OPERADOR;
    END LOOP;
  END IF;
  -- COMMIT;
END GRZ_FOLHA_ATIVA_MOV;

