/*PROCEDIMENTO DE BACKUPS DA ESTRUTURA ATUAL DOS PROCESSOS AUTOMÁTICOS
  AJUSTANDO PARA PODER RESOLVER O PROBLEMA DE NÃO REALIZAR OS DISPAROS AS LOJAS*/


/*   BACKUP DOS DISPAROS AUTOMÁTICOS - PLANILHA DO QUEBRA DE CAIXA RE0350D
     TABELA BACKUP = BK_WORKFLOW_QCX    */

CREATE TABLE BK_WORKFLOW_QCX AS
SELECT * FROM RHWF0405
WHERE COD_RELAT_GR = 'RE0350D'
ORDER BY COD_PROCESSO ASC


---====================================


/*   BACKUP DOS DISPAROS AUTOMÁTICOS - PLANILHA DO VALE TRANSPORTE RE0050
     TABELA BACKUP = BK_WORKFLOW_VT    */
     
CREATE TABLE BK_WORKFLOW_VT AS
SELECT * FROM RHWF0405
WHERE COD_RELAT_GR = 'RE0050'
ORDER BY COD_PROCESSO ASC


---====================================


/*   BACKUP DOS DISPAROS AUTOMÁTICOS - TERMO DE CONSENTIMENTO DO VALE TRANSPORTE RE0345
     TABELA BACKUP = BK_WORKFLOW_TMVT    */
     
CREATE TABLE BK_WORKFLOW_TMVT AS
SELECT * FROM RHWF0405
WHERE COD_RELAT_GR = 'RE0345'
ORDER BY COD_PROCESSO ASC


---====================================


/*   BACKUP DOS DISPAROS AUTOMÁTICOS - DECLARAÇÃO DE RAÇA/ETINIA DE0001
     TABELA BACKUP = BK_WORKFLOW_RACA    */
     
CREATE TABLE BK_WORKFLOW_RACA AS
SELECT * FROM RHWF0405
WHERE COD_RELAT_GR = 'DE0001'
ORDER BY COD_PROCESSO ASC




--=====================================================================

/*BACKUP  DOS DETALHES DE ENVIO DOS PROCESSOS AUTORMÁTICOS NO WORKFLOW*/

CREATE TABLE BK_WORKFLOW_DETALHES AS
SELECT * FROM RHWF0406