--====PROCESSO PARA INSERIR ACESSOS A MÓDULOS DO SISTEMA A UM PERFIL

INSERT INTO RHUS0020 (COD_PERFIL, COD_PRODUTO, COD_MODULO, COD_MENU, LIB_FUNCAO)
SELECT DISTINCT 
       52 AS COD_PERFIL,
       'RH' AS COD_PRODUTO,
       'MS' AS COD_MODULO,
       B.COD_MENU,
       31 AS LIB_FUNCAO
FROM MENU A 
INNER JOIN RHUS0020 B ON A.COD_MENU = B.COD_MENU
WHERE A.COD_MODULO = 'MS';