PROCESSO PARA ATUALIZAR CPF NO PONTO

/*TABELA COM OS DADOS DOS COLABORADORES PARA MAPEAMENTO DO DE/PARA, PARA ATUALIZAR O CAMPO CPF NA TABELA EMPREGADO*/

SELECT CPF 
FROM DBO.EXPORT_DADOS_COLABS
WHERE COD_CONTRATO = 395529;


SELECT * 
FROM DBO.EMPREGADO
WHERE TECLADO = 389622;

SELECT * 
FROM DBO.EMPREGADO
WHERE cpf IS NOT NULL
AND LEN(cpf) < 11;


/*UPDATE PARA ATUALIZAR OS CPFS DOS COLABORADORES*/

UPDATE E
SET E.CPF = D.CPF
FROM DBO.EMPREGADO E
JOIN DBO.EXPORT_DADOS_COLABS D ON E.TECLADO = D.COD_CONTRATO AND E.PIS = D.NRO_PIS_PASEP
WHERE E.TECLADO = 395529

--==============================--

/*UPDATE PARA ATUALIZAR A MATRICULA DOS COLABORADORES*/

UPDATE E
SET E.MATRICULA = D.COD_CONTRATO
FROM DBO.EMPREGADO E
JOIN DBO.EXPORT_DADOS_COLABS D ON E.TECLADO = D.COD_CONTRATO AND E.PIS = D.NRO_PIS_PASEP
WHERE E.TECLADO = 389622