--PROCESSO PARA VERIFICAR UTILIZAÇÃO DE VIEWS E TABELAS

/*1. Verificar as tabelas e outras views utilizadas pela view*/

SELECT *
FROM ALL_DEPENDENCIES
WHERE NAME = 'MDL_USUARIO'
AND TYPE = 'VIEW'
AND REFERENCED_TYPE IN ('TABLE', 'VIEW', 'PROCEDURE', 'FUNCTION')



/*2. Verificar quais objetos dependem dessa view*/

SELECT *
FROM ALL_DEPENDENCIES
WHERE REFERENCED_NAME = 'GRZ_VIEW_QUEBRA'
AND REFERENCED_TYPE = 'VIEW'



/*3. Obter o script da view*/

SELECT TEXT
FROM ALL_VIEWS
WHERE VIEW_NAME = 'GRZ_VIEW_QUEBRA'