--==PROCESSO PARA INSERIR UM NOVO TIPO DE CONTRATO

SELECT * FROM RHFP0314

SELECT 188 AS COD_TP_CONTRATO,
       'APRENDIZ' AS NOME_TP_CONTRATO,
       3 AS COD_TIPO_CONTRATO,
       750 AS NUM_DIAS,
       'N' AS IND_AVALIACOES,
       NULL AS PROG_AVALIACOES,
       'D' AS TIPO_IMFORMACAO
FROM dual;


INSERT INTO RHFP0314 (COD_TP_CONTRATO, NOME_TP_CONTRATO, COD_TIPO_CONTRATO, NUM_DIAS, IND_AVALIACOES, PROG_AVALIACOES, TIPO_INFORMACAO)
(SELECT 188 AS COD_TP_CONTRATO,
       'APRENDIZ' AS NOME_TP_CONTRATO,
       3 AS COD_TIPO_CONTRATO,
       750 AS NUM_DIAS,
       'N' AS IND_AVALIACOES,
       NULL AS PROG_AVALIACOES,
       'D' AS TIPO_INFORMACAO
FROM dual);