/*PROCESSO PARA DESABILITAR UMA CONSTRAINT EM CASO MUITO ESPECÍFICO,
EM QUE NÃO SE ESTA PERMITINDO INSERSÃO DE DADOS EM UMA TABELA*/

/*DESABILITAR CONSTRAINT*/
ALTER TABLE RHFP0309
DISABLE CONSTRAINT CONTRATO_LOTACAO_01

/*HABILITAR CONSTRAINT*/
ALTER TABLE RHFP0509
ENABLE CONSTRAINT QUADRO_LOTACAO_03


SELECT column_name
FROM all_cons_columns
WHERE constraint_name = 'CONTRATO_LOTACAO_01'
  AND owner = 'GRZ_FOLHA'



SELECT DISTINCT(TABLE_NAME)
FROM ALL_TAB_COLUMNS
WHERE UPPER (TABLE_NAME) LIKE '%RHFP%'
AND COLUMN_NAME LIKE '%LOTACAO%'