/*PROCESSO PARA ATUALIZAR IND_GESTOR PARA LIBERAÇÕES EM CASOS DO GERENTE ESTAR AFASTADO
AI ATRIBUI PARA O COLABORADOR QUE FOR DEFINIDO E AUTORIZADO A REALIZAR ESSES PROCESSOS*/

UPDATE GRZ_ARH_FUNCIONARIOS
SET IND_GESTOR = 1
WHERE COD_FUNCIONARIO = 389033


SELECT * FROM GRZ_ARH_FUNCIONARIOS
WHERE COD_UNIDADE = 7493
AND DTA_DEMISSAO IS NULL




--EXEMPLO DE ROTINA PARA ESSE MESMO FIM


CREATE OR REPLACE PROCEDURE ATUALIZAR_IND_GESTOR(
    P_COD_FUNCIONARIO IN NUMBER,
    P_IND_GESTOR IN NUMBER)
IS
BEGIN
    UPDATE SISLOGWEB.GRZ_ARH_FUNCIONARIOS
    SET IND_GESTOR = P_IND_GESTOR
    WHERE COD_FUNCIONARIO = P_COD_FUNCIONARIO;

    COMMIT;
END ATUALIZAR_IND_GESTOR;
