SELECT TEMPO.COD_USUARIO
           , TO_DATE(TO_CHAR((LAST_DAY(SYSDATE)), 'DD/MM/YYYY')) AS DATA_REFERENCIA
           , SUM((TRIM(TO_CHAR(RHYF0118(TEMPO.TEMPO_LOGIN),'990,00')))) AS TEMPO_LOGIN
           , CT.DATA_FIM
           , TEMPO.QTD_HORBAS_MES
	    FROM
	       	(SELECT A.COD_USUARIO
                , K.QTD_HORBAS_MES
		            , SUM(ROUND((A.TEMPO_LOGIN / 60), 2)) AS TEMPO_LOGIN
	         FROM SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ A, RHFP0340 CARGO, RHFP0500 NMCLH, RHFP0307 G, RHFP0321 K
	         WHERE TO_DATE(SUBSTR(HORA_INICIAL,1, 10)) >= TO_DATE('15/'||TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE),-1),'MM/YYYY'),'DD/MM/YYYY')
           AND TO_DATE(SUBSTR(HORA_INICIAL,1, 10)) <= TO_DATE('15/'||TO_CHAR(TRUNC(SYSDATE),'MM/YYYY')) -- PERÍODO ENTRE DIA 15 DO MES PASSADO AO DIA 15 DO MES ATUAL
           AND CARGO.COD_CONTRATO = A.COD_USUARIO
           AND G.COD_CONTRATO = A.COD_USUARIO
           AND K.COD_HORAS_BASE = G.COD_HORAS_BASE
           AND G.DATA_FIM = '31/12/2999'
           AND CARGO.DATA_FIM = '31/12/2999'
           AND NMCLH.COD_CLH = CARGO.COD_CLH
           AND CARGO.COD_CLH NOT IN (102, 47)
           AND NMCLH.NOME_CLH NOT LIKE '%GERENTE%'
           AND NOT EXISTS (SELECT 1 FROM V_DADOS_PESSOA Y WHERE Y.COD_FUNCAO IN (225, 120)  AND Y.DES_GRUPO LIKE '%FRANCO GIORGI%' AND Y.COD_CONTRATO = A.COD_USUARIO) -- NÃO IMPORTA HORAS OPERADAS DE VENDEDOR DE MODA MASCULINA DAS FILIAIS FRANCO GIORGI
	         GROUP BY A.COD_USUARIO, K.QTD_HORBAS_MES ) TEMPO, RHFP0300 CT
	   WHERE CT.COD_CONTRATO = TEMPO.COD_USUARIO
       AND  NOT EXISTS (SELECT 1 FROM RHFP1004 A WHERE A.COD_CONTRATO = TEMPO.COD_USUARIO AND (DATA_MOV = TO_CHAR((LAST_DAY(SYSDATE)), 'DD/MM/YYYY') OR DATA_MOV = DATA_FIM) AND COD_VD = 838 AND COD_EVENTO IN (1,17)) -- VALIDA/IMPEDE INSERÇÃO CASO JÁ INFORMADO O VD838
       --AND TEMPO.COD_USUARIO IN (383058,379928,337196,387898)
     GROUP BY TEMPO.COD_USUARIO, CT.DATA_FIM, TEMPO.QTD_HORBAS_MES;
     

     

     
     
SELECT *  FROM  SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ A
WHERE TO_DATE(SUBSTR(HORA_INICIAL,1, 10))>= '15/07/2022'
AND TO_DATE(SUBSTR(HORA_INICIAL,1, 10))>= '15/08/2022'
AND COD_USUARIO = 386125

SELECT *  FROM  SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ A
WHERE COD_USUARIO = 386125
AND TO_DATE(SUBSTR(HORA_INICIAL,1, 10))>= '15/07/2022'

SELECT * FROM GER_TEMPO_LOGIN
WHERE COD_UNIDADE = 553
AND TO_DATE(SUBSTR(HORA_INICIAL,0,10)) >= TO_DATE('15/08/2022')
ORDER BY HORA_INICIAL

SELECT TO_DATE(SUBSTR(HORA_INICIAL,1, 10))  
FROM  SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ A
WHERE COD_USUARIO IN (386125, 388267, 389942, 390658, 391910)
--AND COD_UNIDADE IN (362, 392, 440, 7500, 7569)
AND TO_DATE(SUBSTR(HORA_INICIAL,1, 10))>= '15/07/2022'
AND TO_DATE(SUBSTR(HORA_INICIAL,1, 10))<= '15/08/2022'
ORDER BY 1


SELECT TO_DATE('15/'||TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE),-1),'MM/YYYY'),'DD/MM/YYYY') ,TO_DATE('15/'||TO_CHAR(TRUNC(SYSDATE),'MM/YYYY'))
FROM  SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ A
WHERE COD_USUARIO = 386125
AND ROWNUM = 1


SELECT TO_DATE(A.HORA_INICIAL,'DD/MM/YYYY HH24:MI:SS') 
FROM SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ A
WHERE COD_USUARIO = 386125
AND COD_UNIDADE = 440