--Processo utilizado para atualizar a situação da programação de férias de uma colaboradora reintegrada,
  --processo necessário para alterar um período aquisitivo ao qual o colaborador não tirou as férias
  --e aparece como QUITADO na situação em período aquisitivo, com isso realizando esse processo, atualiza a
  --situação para que se encontre como VENCIDO.

SELECT * FROM RHFP0327
WHERE COD_CONTRATO = 390568;

UPDATE RHFP0327
SET SITUACAO_PROGRAMACAO = 0
WHERE COD_CONTRATO = 390568


--========================================================================================--

--PROCESSO NECESSÁRIO PARA REALIZAR A DELETAÇÃO DE FÉRIAS EM UMA REINTEGRAÇÃO

--========================================================--                   

--1º -> DEVE-SE AJUSTAR A SITUAÇÃO DO COLABORADOR, 
      --ATUALIZAR A DATA FIM DA DEMISSÃO PARA NULL 
      --PARA QUE O COLABORADOR VOLTE A FICAR ATIVO

SELECT * FROM RHFP0300
WHERE COD_CONTRATO = 392936;

UPDATE RHFP0300
SET DATA_FIM = NULL
WHERE COD_CONTRATO = 392936 
AND DATA_FIM = '08/12/2022'

UPDATE RHFP0300
SET COD_CAUSA_DEMISSAO = NULL
WHERE COD_CONTRATO = 392936 
AND COD_CAUSA_DEMISSAO = 12


--========================================================--

--2º -> DELETAR O CÁLCULO DAS FÉRIAS DA COLABORADORA 
     --(CASO AS FÉRIAS TENHAM SIDO CALCULADAS NA RESCISÃO, 
     --NÃO DEVE-SE DELETAR O CÁLCULO)


SELECT * FROM RHFP1006
WHERE COD_CONTRATO = 392936
AND COD_MESTRE_EVENTO = 15556


DELETE 
FROM RHFP1006
WHERE COD_CONTRATO = 392936
AND COD_MESTRE_EVENTO = 15556


--========================================================--

--3º PASSO NECESSÁRIO PARA DELETAR UMA 
   --PROGRAMAÇÃO DE FÉRIAS DE COLABORADOR REINTEGRADO

SELECT * FROM RHFP0328
WHERE COD_CONTRATO = 392936;


DELETE RHFP0328
WHERE COD_CONTRATO = 392936
AND DATA_PREVISTA_FERIAS = '08/12/2022'



--==============--

--3º.1

SELECT * FROM RHFP0327
WHERE COD_CONTRATO = 392936;


UPDATE RHFP0327
SET SITUACAO_PROGRAMACAO = 0
WHERE COD_CONTRATO = 392936

UPDATE RHFP0327
SET DATA_PAGAMENTO = NULL
WHERE COD_CONTRATO = 392936

UPDATE RHFP0327
SET DATA_PAGAMENTO = NULL
WHERE COD_CONTRATO = 392936


DELETE RHFP0327
WHERE COD_CONTRATO = 392936
AND DATA_PREVISTA_FERIAS = '08/12/2022'


--OBS: CASO HAJA ALGUM AFASTAMENTO DO CONTRATO PRIMEIRAMENTE CONSULTAR NA TELA DOS AFASTAMENTOS NO GBRH 
     --E SE HOUVER NAQUELA DATA, MAIS PRECISAMENTE DAS FÉRIAS, DEVE-SE TAMBÉM SER DELETADO DA TABELA 
     --RHFP0306 - AFASTAMENTOS DO CONTRATO

--========================================================--