/*versão oficial RELATÓRIO DADOS PARA CONTATO COM PROPRIETÁRIOS DOS IMOVEIS DAS LOJAS*/

SELECT DISTINCT
       CT.COD_UNIDADE,
       LJ.NOME_LOJA AS DES_UNIDADE,
       PS.DES_PESSOA AS "PROPRIETÁRIO",
       CASE 
           WHEN (PS.NUM_TELEFONE IS NOT NULL OR PS.NUM_TELEFONE IS NULL) THEN
            '(54) 9 9999-9999'
       END AS TELEFONE,
       CASE
           WHEN (PS.NUM_FAX IS NOT NULL OR PS.NUM_FAX IS NULL) THEN
            'proprietario@gmail.com'          
       END AS "HOJE FAX > MAS SERÁ > EMAIL"
       --IM.COD_IMOVEL,
       --CT.COD_CONTRATO,
       --CT.DTA_INICIO,
       --CT.DTA_TERMINO
  FROM GRAZZ.GRZ_LOC_CONTRATOS CT
  JOIN GRAZZ.GRZ_LOJAS LJ ON LJ.COD_LOJA = CT.COD_UNIDADE
  JOIN GRAZZ.GRZ_IMOVEIS IM ON IM.COD_IMOVEL = CT.COD_IMOVEL
                           AND IM.IND_INATIVO = 0
  JOIN GRAZZ.GRZ_LOC_LOCADORES LC ON LC.COD_CONTRATO = CT.COD_CONTRATO
                                 AND LC.IND_INATIVO = 0
  JOIN GRAZZ.GRZ_PESSOAS PS ON PS.COD_PESSOA = LC.COD_PESSOA
                           AND PS.IND_INATIVO = 0
  LEFT JOIN GRAZZ.GRZ_REDES RD ON RD.COD_REDE = LJ.COD_REDE
  JOIN GRAZZ.GRZ_UNIDADES UNI ON UNI.COD_UNIDADE = CT.COD_UNIDADE
                             AND UNI.IND_INATIVO = 0
 WHERE CT.IND_INATIVO = 0
   AND CT.DTA_TERMINO > TRUNC(SYSDATE)
   AND (CT.COD_UNIDADE = &UNIDADE OR &UNIDADE = 0)
   AND (LJ.COD_REDE = &REDE OR &REDE = 0)
 ORDER BY CT.COD_UNIDADE;