--SCRIPT PARA ALTERAR A TABELA RHFP064 PARA ADICIONAR A COLUNA COD_TP_CONTRATO_PRO


ALTER TABLE RHFP0641 ADD COD_TP_CONTRATO_PRO NUMBER(15);

ALTER TABLE RHFP0641 ADD CONSTRAINT FORMULARIO_AVAL_02
   FOREIGN KEY (COD_TP_CONTRATO_PRO) REFERENCES RHFP0314(COD_TP_CONTRATO);

 
 
SELECT * FROM RHFP0314;
SELECT * FROM RHFP0641;