---SCRIPT PARA AJUSTAR O COD_CRACHA INCORRETO OU QUE FOI TROCADO PELO CONTRATO DE OUTRO COLABORADOR


SELECT A.COD_CONTRATO, A.COD_CRACHA, C.NOME_PESSOA, A.DATA_INICIO
FROM RHAF1108 A
INNER JOIN RHFP0300 B ON A.COD_CONTRATO = B.COD_CONTRATO
INNER JOIN PESSOA_FISICA C ON B.COD_FUNC = C.COD_PESSOA
WHERE A.DATA_INICIO >= '01/01/2024'
--AND A.COD_CRACHA <> A.COD_CONTRATO
AND B.DATA_FIM IS NULL
AND A.COD_CONTRATO IN (394972, 394973, 394974, 394999)



UPDATE RHAF1108 A
SET A.COD_CRACHA = A.COD_CONTRATO
WHERE A.COD_CONTRATO IN (
    SELECT B.COD_CONTRATO
    FROM RHAF1108 A
    INNER JOIN RHFP0300 B ON A.COD_CONTRATO = B.COD_CONTRATO
    INNER JOIN PESSOA_FISICA C ON B.COD_FUNC = C.COD_PESSOA
    WHERE A.DATA_INICIO >= '01/01/2024'
    AND B.DATA_FIM IS NULL
)
AND A.COD_CRACHA <> A.COD_CONTRATO;