SELECT DISTINCT AF.COD_CONTRATO, PS.NOME_PESSOA AS NOME_FUNCIONARIO, CTC.EDICAO_NIVEL3, OG.NOME_ORGANOGRAMA, AF.DATA_INICIO, AF.DATA_FIM, AFS.COD_VD, 
MS.DATA_REFERENCIA, MS.COD_MESTRE_EVENTO, AFS.QTDE_VD AS QTD_HORAS, AFS.VALOR_VD AS
VALOR_PAGO, AF.COD_CID_10 AS COD_CID, sum(case when AF.DATA_FIM <= MS.DATA_FIM_MOV then 0 else 1 end) IND_FRACIONAMENTO
FROM RHFP1006 AFS, RHFP1003 MS, RHFP0306 AF, RHFP0300 CT, PESSOA PS, RHFP0310 ORG, RHFP0400 OG, RHFP0401 CTC
WHERE AFS.COD_MESTRE_EVENTO = MS.COD_MESTRE_EVENTO
AND AF.COD_CONTRATO = AFS.COD_CONTRATO
AND CT.COD_CONTRATO = AF.COD_CONTRATO
AND ORG.COD_CONTRATO = CT.COD_CONTRATO
AND ORG.DATA_FIM = '31/12/2999'
AND PS.COD_PESSOA = CT.COD_FUNC
AND OG.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
AND CTC.COD_ORGANOGRAMA = OG.COD_ORGANOGRAMA
AND AF.DATA_INICIO < '31/12/2020'
AND AF.COD_CAUSA_AFAST = 6
AND AFS.COD_VD = 897
AND (CT.DATA_FIM IS NULL OR CT.DATA_FIM >= sysdate)
AND MS.DATA_REFERENCIA BETWEEN '01/01/2020' AND '31/12/2020'
AND AF.COD_CID_10 IN ('J11', 'Z20.9', 'Z29.0', 'B34.2', 'B34.9', 'U07.1', 'U07.2', 'Z29.9', 'Z29.8', 'J11.0', 'J11.1', 'J11.8', 'J00', 'J06', 'J06.8', 
'J06.9')
AND AF.DATA_INICIO BETWEEN MS.DATA_INI_MOV AND MS.DATA_FIM_MOV
GROUP BY AF.COD_CONTRATO , PS.NOME_PESSOA,CTC.EDICAO_NIVEL3, OG.NOME_ORGANOGRAMA, AF.DATA_INICIO, AF.DATA_FIM, AFS.COD_VD, MS.DATA_REFERENCIA, 
MS.COD_MESTRE_EVENTO, AFS.QTDE_VD, AFS.VALOR_VD, AF.COD_CID_10
ORDER BY AF.COD_CONTRATO, PS.NOME_PESSOA,CTC.EDICAO_NIVEL3 , MS.DATA_REFERENCIA ASC
