--==SELECT DA ROTINA NL.GRZW_REL_QUADRO_LOJAS_SP DO RELATÓRIO DE QUADROS RH==--

SELECT SUM(DECODE(QTD_HORBAS_MES, 220, 1, 0)) Q220,
       SUM(DECODE(QTD_HORBAS_MES, 195, 1, 0)) Q195,
       SUM(DECODE(QTD_HORBAS_MES, 165, 1, 0)) Q165,
       SUM(DECODE(QTD_HORBAS_MES, 150, 1, 0)) Q150,
       SUM(DECODE(QTD_HORBAS_MES, 120, 1, 0)) Q120,
       SUM(DECODE(QTD_HORBAS_MES, 100, 1, 0)) Q100,
       SUM(DECODE(IND_DEFICIENCIA, 'S', 0, QTD_HORBAS_MES)) TOTAL,
       SUM(DECODE(IND_DEFICIENCIA, 'S', 0, 1)) TOTAL_COLABORADORES,
       SUM(DECODE(COD_CLH, 204, 1, 0)) QTD_TEMPORARIOS
  FROM FUNCIONARIOS@grzfolha
 WHERE EDICAO_FILIAL = '498'
   AND DATA_FIM IS NULL
   AND COD_CLH NOT IN (71, 74, 68) -- APRENDIZ E SERVENTE N¿O ENTRAM
   AND STATUS_AFASTAMENTO IN (0, 7, 107) -- 0 PADRAO / 7 FERIAS / 107 AFASTAMENTO TEMPORARIO
   AND (INSTR(',' || '1' || ',', ',' || EDICAO_NIVEL3 || ',') > 0);
   

--===--  
   
select * from grzw_rel_orcamento_rh
where des_usuario = '388575'
