SELECT 
    A.COD_EVENTO,
    D.NOME_EVENTO,
    A.COD_VD, 
    B.NOME_VD,
    TO_CHAR(SUM(NVL(A.VALOR_VD, 0)), 'FM999G999G990D00') AS "TOTAIS_1005",
    '01/05/2024' AS "DE",
    '31/05/2024' AS "ATE",
    1 AS ORDER_COL
FROM 
    RHFP1005 A
    INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
    INNER JOIN RHFP1003 C ON A.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
    INNER JOIN RHFP1002 D ON A.COD_EVENTO = D.COD_EVENTO
WHERE 
    A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE 
            TO_DATE(DATA_REFERENCIA) BETWEEN '01/05/2024' AND '31/05/2024'
            AND COD_ORGANOGRAMA = 8
            AND COD_EVENTO IN (1)
    )
GROUP BY 
    A.COD_EVENTO,
    D.NOME_EVENTO,
    A.COD_VD, 
    B.NOME_VD

UNION ALL

SELECT 
    NULL AS COD_EVENTO,
    NULL AS NOME_EVENTO,
    NULL AS COD_VD,
    NULL AS NOME_VD,
    NULL AS "TOTAIS_1005",
    NULL AS "DE",
    NULL AS "ATE",
    2 AS ORDER_COL
FROM DUAL

UNION ALL

SELECT 
    A.COD_EVENTO,
    D.NOME_EVENTO,
    A.COD_VD, 
    B.NOME_VD,
    TO_CHAR(SUM(NVL(A.VALOR_VD, 0)), 'FM999G999G990D00') AS "TOTAIS_1005",
    '01/05/2024' AS "DE",
    '31/05/2024' AS "ATE",
    3 AS ORDER_COL
FROM 
    RHFP1005 A
    INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
    INNER JOIN RHFP1003 C ON A.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
    INNER JOIN RHFP1002 D ON A.COD_EVENTO = D.COD_EVENTO
WHERE 
    A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE 
            TO_DATE(DATA_REFERENCIA) BETWEEN '01/05/2024' AND '31/05/2024'
            AND COD_ORGANOGRAMA = 8
            AND COD_EVENTO IN (17)
    )
GROUP BY 
    A.COD_EVENTO,
    D.NOME_EVENTO,
    A.COD_VD, 
    B.NOME_VD

UNION ALL

SELECT 
    NULL AS COD_EVENTO,
    NULL AS NOME_EVENTO,
    NULL AS COD_VD,
    NULL AS NOME_VD,
    NULL AS "TOTAIS_1005",
    NULL AS "DE",
    NULL AS "ATE",
    4 AS ORDER_COL
FROM DUAL

UNION ALL

SELECT 
    A.COD_EVENTO,
    D.NOME_EVENTO,
    A.COD_VD, 
    B.NOME_VD,
    TO_CHAR(SUM(NVL(A.VALOR_VD, 0)), 'FM999G999G990D00') AS "TOTAIS_1005",
    '01/05/2024' AS "DE",
    '31/05/2024' AS "ATE",
    5 AS ORDER_COL
FROM 
    RHFP1005 A
    INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
    INNER JOIN RHFP1003 C ON A.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
    INNER JOIN RHFP1002 D ON A.COD_EVENTO = D.COD_EVENTO
WHERE 
    A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE 
            TO_DATE(DATA_REFERENCIA) BETWEEN '01/05/2024' AND '31/05/2024'
            AND COD_ORGANOGRAMA = 8
            AND COD_EVENTO IN (19)
    )
GROUP BY 
    A.COD_EVENTO,
    D.NOME_EVENTO,
    A.COD_VD, 
    B.NOME_VD

UNION ALL

SELECT 
    NULL AS COD_EVENTO,
    NULL AS NOME_EVENTO,
    NULL AS COD_VD,
    NULL AS NOME_VD,
    NULL AS "TOTAIS_1005",
    NULL AS "DE",
    NULL AS "ATE",
    6 AS ORDER_COL
FROM DUAL

UNION ALL

SELECT 
    A.COD_EVENTO,
    D.NOME_EVENTO,
    A.COD_VD, 
    B.NOME_VD,
    TO_CHAR(SUM(NVL(A.VALOR_VD, 0)), 'FM999G999G990D00') AS "TOTAIS_1005",
    '01/05/2024' AS "DE",
    '31/05/2024' AS "ATE",
    7 AS ORDER_COL
FROM 
    RHFP1005 A
    INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
    INNER JOIN RHFP1003 C ON A.COD_MESTRE_EVENTO = C.COD_MESTRE_EVENTO
    INNER JOIN RHFP1002 D ON A.COD_EVENTO = D.COD_EVENTO
WHERE 
    A.COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE 
            TO_DATE(DATA_REFERENCIA) BETWEEN '01/05/2024' AND '31/05/2024'
            AND COD_ORGANOGRAMA = 8
            AND COD_EVENTO IN (26)
    )
GROUP BY 
    A.COD_EVENTO,
    D.NOME_EVENTO,
    A.COD_VD, 
    B.NOME_VD

UNION ALL

SELECT 
    NULL AS COD_EVENTO,
    NULL AS NOME_EVENTO,
    NULL AS COD_VD,
    NULL AS NOME_VD,
    NULL AS "TOTAIS_1005",
    NULL AS "DE",
    NULL AS "ATE",
    8 AS ORDER_COL
FROM DUAL
ORDER BY 
    ORDER_COL, COD_VD, COD_EVENTO;
