--SELEÇÃO PARA GERAR DADOS DE NOVOS CRACHÁS

SELECT COD_CONTRATO,
       DES_PESSOA,
       DES_NOME,
       COD_FUNCAO,
       DES_FUNCAO,
       COD_UNIDADE,
       DES_UNIDADE,
       COD_REDE_LOCAL,
       COD_REGIAO,
       DATA_DEMISSAO
  FROM V_DADOS_COLAB_AVT
 WHERE COD_EMP = '008'
   AND STATUS = 0
   AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND TIPO = 'LOJA'
   AND (COD_UNIDADE = :FILIAL OR :FILIAL = 'NULL')
   AND (COD_REDE_LOCAL = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 'NULL')
   AND (COD_REGIAO = TO_CHAR(:RERIAO) OR TO_CHAR(:RERIAO) = 'NULL')


--VERSÃO 2 - USADA NO MOMENTO

SELECT COD_CONTRATO,
       DES_PESSOA,
       DES_NOME,
       COD_FUNCAO,
       DES_FUNCAO,
       COD_UNIDADE,
       DES_UNIDADE,
       COD_REDE_LOCAL,
       COD_REGIAO,
       DATA_DEMISSAO
  FROM V_DADOS_COLAB_AVT
 WHERE COD_EMP = '008'
   AND STATUS = 0
   AND STATUS_AFAST IN ('EM ATIVIDADE', 'AFASTADO TEMP')
   AND TIPO = 'LOJA'
   AND (COD_UNIDADE = :FILIAL OR :FILIAL = 0)
   AND (COD_REDE_LOCAL = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
   AND (COD_REGIAO = TO_CHAR(:RERIAO) OR TO_CHAR(:RERIAO) = 0)