--===SELEÇÃO DE QUANTIDADE DE CONTRATOS POR NACIONALIDAE/ESTADO

SELECT 
    COD_UF, 
    DES_NACIONALIDADE, 
    COUNT(DISTINCT COD_CONTRATO) AS TOTAL_CONTRATOS,
    'Referência: ' || TO_CHAR(SYSDATE, 'DD/MM/YYYY') AS DATA_REFERENCIA
FROM 
    V_DADOS_COLAB_AVT
WHERE 
    STATUS = 0
    AND COD_EMP = '008'
    AND COD_UF IN ('RS', 'SC', 'PR')
GROUP BY 
    COD_UF, 
    DES_NACIONALIDADE
ORDER BY 
    CASE 
        WHEN COD_UF = 'RS' THEN 1 
        WHEN COD_UF = 'SC' THEN 2 
        WHEN COD_UF = 'PR' THEN 3 
    END,  
    DES_NACIONALIDADE;