----Passar as OC da Marilei(8029) para a Ana Claudia(5951265) setores 34 e 38

----Ordens da Tottal Setor 38

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=503800005000
               AND TO_NUMBER(C.COD_COMPLETO)<=503899995999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)
             
UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '5951265'
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=503800005000
               AND TO_NUMBER(C.COD_COMPLETO)<=503899995999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)          
             


---Ordens da Grazziotin Setor 38

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=818
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=103800001000
               AND TO_NUMBER(C.COD_COMPLETO)<=103899991999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)

UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '5951265'
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=818
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=103800001000
               AND TO_NUMBER(C.COD_COMPLETO)<=103899991999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)
             
-----Ordens da Por Menos Setor 38

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=838
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=303800003000
               AND TO_NUMBER(C.COD_COMPLETO)<=303899993999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)
             
UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '5951265'
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=838
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=303800003000
               AND TO_NUMBER(C.COD_COMPLETO)<=303899993999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)
----------Setor 34--------------

----Ordens da Tottal Setor 34

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=503400005000
               AND TO_NUMBER(C.COD_COMPLETO)<=503499995999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)

UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '5951265'
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=503400005000
               AND TO_NUMBER(C.COD_COMPLETO)<=503499995999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)
             
-----Ordens da Grazziotin Setor 34

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=818
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=103400001000
               AND TO_NUMBER(C.COD_COMPLETO)<=103499991999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)

UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '5951265'
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=818
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=103400001000
               AND TO_NUMBER(C.COD_COMPLETO)<=103499991999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)
             
-----Ordens da Por Menos Setor 34   

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=838
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=303400003000
               AND TO_NUMBER(C.COD_COMPLETO)<=303499993999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)
             
UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '5951265'
SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '8029'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=838
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
                         ,nl.IE_MASCARAS C
             WHERE A.NUM_SEQ=B.NUM_SEQ
               AND A.COD_MAQUINA=B.COD_MAQUINA
               AND B.COD_ITEM=C.COD_ITEM
               AND C.COD_MASCARA=170
               AND TO_NUMBER(C.COD_COMPLETO)>=303400003000
               AND TO_NUMBER(C.COD_COMPLETO)<=303499993999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
             WHERE D.NUM_SEQ = A.NUM_SEQ
             AND A.COD_EMP = D.COD_EMP
             AND A.COD_UNIDADE = D.COD_UNIDADE)


1488165

--------------Passar as OC da Elaine(4693672) para a Glaucia(1488165) setores 60 da rede Tottal e também o 42.25; 42.35.70.

-----Ordens de compra do setor 60 da Tottal

 

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '4693672'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
,nl.IE_MASCARAS C
WHERE A.NUM_SEQ=B.NUM_SEQ
AND A.COD_MAQUINA=B.COD_MAQUINA
AND B.COD_ITEM=C.COD_ITEM
AND C.COD_MASCARA=170
AND TO_NUMBER(C.COD_COMPLETO)>=506000005000
AND TO_NUMBER(C.COD_COMPLETO)<=506099995999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
WHERE D.NUM_SEQ = A.NUM_SEQ
AND A.COD_EMP = D.COD_EMP
AND A.COD_UNIDADE = D.COD_UNIDADE)

UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '1488165'
WHERE A.COD_COMPRADOR = '4693672'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
,nl.IE_MASCARAS C
WHERE A.NUM_SEQ=B.NUM_SEQ
AND A.COD_MAQUINA=B.COD_MAQUINA
AND B.COD_ITEM=C.COD_ITEM
AND C.COD_MASCARA=170
AND TO_NUMBER(C.COD_COMPLETO)>=506000005000
AND TO_NUMBER(C.COD_COMPLETO)<=506099995999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
WHERE D.NUM_SEQ = A.NUM_SEQ
AND A.COD_EMP = D.COD_EMP
AND A.COD_UNIDADE = D.COD_UNIDADE)

 

-----Ordens de compra do setor 42.25 da Tottal

 

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '4693672'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
,nl.IE_MASCARAS C
WHERE A.NUM_SEQ=B.NUM_SEQ
AND A.COD_MAQUINA=B.COD_MAQUINA
AND B.COD_ITEM=C.COD_ITEM
AND C.COD_MASCARA=170
AND TO_NUMBER(C.COD_COMPLETO)>=504225005000
AND TO_NUMBER(C.COD_COMPLETO)<=504225995999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
WHERE D.NUM_SEQ = A.NUM_SEQ
AND A.COD_EMP = D.COD_EMP
AND A.COD_UNIDADE = D.COD_UNIDADE)

UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '1488165' 
WHERE A.COD_COMPRADOR = '4693672'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
,nl.IE_MASCARAS C
WHERE A.NUM_SEQ=B.NUM_SEQ
AND A.COD_MAQUINA=B.COD_MAQUINA
AND B.COD_ITEM=C.COD_ITEM
AND C.COD_MASCARA=170
AND TO_NUMBER(C.COD_COMPLETO)>=504225005000
AND TO_NUMBER(C.COD_COMPLETO)<=504225995999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
WHERE D.NUM_SEQ = A.NUM_SEQ
AND A.COD_EMP = D.COD_EMP
AND A.COD_UNIDADE = D.COD_UNIDADE)

-----Ordens de compra do setor 42.35.70 da Tottal

 

SELECT * FROM nl.AC_ORDENS_COMPRA A--COUNT(1)FROM nl.AC_ORDENS_COMPRA A
WHERE A.COD_COMPRADOR = '4693672'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
,nl.IE_MASCARAS C
WHERE A.NUM_SEQ=B.NUM_SEQ
AND A.COD_MAQUINA=B.COD_MAQUINA
AND B.COD_ITEM=C.COD_ITEM
AND C.COD_MASCARA=170
AND TO_NUMBER(C.COD_COMPLETO)>=504235705000
AND TO_NUMBER(C.COD_COMPLETO)<=504235705999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
WHERE D.NUM_SEQ = A.NUM_SEQ
AND A.COD_EMP = D.COD_EMP
AND A.COD_UNIDADE = D.COD_UNIDADE)

UPDATE AC_ORDENS_COMPRA A
SET A.COD_COMPRADOR= '1488165'
WHERE A.COD_COMPRADOR = '4693672'
and a.dta_emissao >='01/08/2021'
AND A.COD_UNIDADE=858
AND EXISTS (SELECT 1 FROM nl.AC_ITENS_OC B
,nl.IE_MASCARAS C
WHERE A.NUM_SEQ=B.NUM_SEQ
AND A.COD_MAQUINA=B.COD_MAQUINA
AND B.COD_ITEM=C.COD_ITEM
AND C.COD_MASCARA=170
AND TO_NUMBER(C.COD_COMPLETO)>=504235705000
AND TO_NUMBER(C.COD_COMPLETO)<=504235705999)
AND NOT EXISTS (SELECT 1 FROM NL.AC_RECEBIMENTOS_OC D
WHERE D.NUM_SEQ = A.NUM_SEQ
AND A.COD_EMP = D.COD_EMP
AND A.COD_UNIDADE = D.COD_UNIDADE)

