SELECT * FROM EST_CUPONS
WHERE DTA_MOVIMENTO BETWEEN '15/09/2022' AND '14/10/2022'
AND COD_UNIDADE = 7084;

SELECT * FROM EST_CUPONS
WHERE DTA_MOVIMENTO BETWEEN '15/09/2022' AND '14/10/2022'
AND COD_UNIDADE = 84;


--=========================================================--
--=========================================================--


SELECT COD_UNIDADE
     , DTA_MOVIMENTO
     , NUM_EQUIPAMENTO
     , COUNT(SEQ_CUPOM)
FROM EST_CUPONS
WHERE DTA_MOVIMENTO BETWEEN '15/08/2022' AND '14/09/2022'
AND COD_UNIDADE = 84
GROUP BY COD_UNIDADE, DTA_MOVIMENTO, NUM_EQUIPAMENTO
ORDER BY DTA_MOVIMENTO ASC;


SELECT COD_UNIDADE
     , DTA_MOVIMENTO
     , NUM_EQUIPAMENTO
     , COUNT(SEQ_CUPOM)
FROM EST_CUPONS
WHERE DTA_MOVIMENTO BETWEEN '15/08/2022' AND '14/09/2022'
AND COD_UNIDADE = 7084
GROUP BY COD_UNIDADE, DTA_MOVIMENTO, NUM_EQUIPAMENTO
ORDER BY DTA_MOVIMENTO ASC;

--=========================================================--
--=========================================================--

SELECT COD_UNIDADE
     , DTA_MOVIMENTO
     , NUM_EQUIPAMENTO
     , COUNT(SEQ_CUPOM)
FROM EST_CUPONS
WHERE COD_UNIDADE = 84
AND DTA_MOVIMENTO BETWEEN '15/09/2022' AND '14/10/2022'
GROUP BY COD_UNIDADE, DTA_MOVIMENTO, NUM_EQUIPAMENTO
ORDER BY DTA_MOVIMENTO ASC;


SELECT COD_UNIDADE
     , DTA_MOVIMENTO
     , NUM_EQUIPAMENTO
     , COUNT(SEQ_CUPOM)
FROM EST_CUPONS
WHERE COD_UNIDADE = 7084
AND DTA_MOVIMENTO BETWEEN '15/09/2022' AND '14/10/2022'
GROUP BY COD_UNIDADE, DTA_MOVIMENTO, NUM_EQUIPAMENTO
ORDER BY DTA_MOVIMENTO ASC;