SELECT L.COD_CONTRATO, EDI.EDICAO_NIVEL3, TU.NOME_ORGANOGRAMA
   FROM RHFP0310 L, RHFP0400 TU, RHFP0401 EDI
   WHERE L.DATA_FIM = '31/12/2999'
   AND TU.COD_ORGANOGRAMA = L.COD_ORGANOGRAMA
   AND TU.COD_ORGANOGRAMA = EDI.COD_ORGANOGRAMA


SELECT * FROM RHFP0401

SELECT L.COD_CONTRATO, EDI.EDICAO_ORG, TU.NOME_ORGANOGRAMA
   FROM RHFP0310 L, RHFP0400 TU, RHFP0401 EDI
   WHERE TU.COD_ORGANOGRAMA = L.COD_ORGANOGRAMA
   AND TU.COD_ORGANOGRAMA = EDI.COD_ORGANOGRAMA
   AND L.DATA_FIM <> '31/12/2999'