SELECT
  RD2.COD_AUDITORIA,
  RD1.NOME_USUARIO,
  PE.NOME_PESSOA,
  RD3.NOME_LOGICO_TABELA,
  RD2.NOME_COLUNA,
  RD2.FLAG_CHAVE,
  RD2.VALOR_ANTIGO,
  RD2.VALOR_NOVO,
  RD1.NOME_TERMINAL,
  RD1.TIMESTAMP
FROM
  RHAD0001 RD1
JOIN
  RHAD0002 RD2 ON RD1.COD_AUDITORIA = RD2.COD_AUDITORIA
JOIN
  RHAD0003 RD3 ON RD3.NOME_FISICO_TABELA = RD1.NOME_FISICO_TABELA
JOIN
  OPERADOR OPE ON OPE.COD_OPERADOR = RD1.NOME_USUARIO
JOIN
  PESSOA PE ON PE.COD_PESSOA = OPE.COD_PESSOA
WHERE
  RD1.TIMESTAMP BETWEEN :DATA_INICIO AND :DATA_FIM
  AND RD2.VALOR_NOVO LIKE '%' || :DADO_ALTERADO || '%'
ORDER BY
  RD1.TIMESTAMP DESC