 SELECT VDP.COD_CONTRATO, VDP.des_pessoa, VDP.COD_FUNCAO, VDP.des_funcao, PERF.COD_PERFIL, H.NOME_PERFIL
  FROM RHCS0300       PERF,
       V_DADOS_PESSOA VDP,
       RHFP0310       ORG,
       RHFP0400       E,
       RHFP0401       G,
       RHCS0230       H
 WHERE VDP.COD_CONTRATO = PERF.COD_CONTRATO
   AND ORG.COD_CONTRATO = VDP.cod_contrato
   AND E.COD_ORGANOGRAMA = org.COD_ORGANOGRAMA
   AND E.COD_ORGANOGRAMA = G.COD_ORGANOGRAMA
   AND H.COD_PERFIL = PERF.COD_PERFIL
   AND ORG.DATA_FIM = '31/12/2999'
  -- AND G.EDICAO_NIVEL3 IN ('001', '013') -- SOMENTE LOGISTICA E ADM
   AND G.EDICAO_NIVEL3 NOT IN ('001', '013') -- SOMENTE LOJAS
   AND COD_EMP = 8
   ORDER BY PERF.COD_PERFIL, VDP.COD_FUNCAO  ASC;