/*SQL GERAÇÃO QUEBRA DE CAIXA DA ROTINA - GRZ_FOLHA_TEMPO_OP_CAIXA*/

SELECT TEMPO.COD_USUARIO,
       TO_DATE(TO_CHAR((LAST_DAY(SYSDATE)), 'DD/MM/YYYY')) AS DATA_REFERENCIA,
       SUM((TRIM(TO_CHAR(RHYF0118(TEMPO.TEMPO_LOGIN), '990,00')))) AS TEMPO_LOGIN,
       CT.DATA_FIM,
       TEMPO.QTD_HORBAS_MES,
       TEMPO.NOME_CLH
  FROM (SELECT A.COD_USUARIO,
               K.QTD_HORBAS_MES,
               SUM(ROUND((A.TEMPO_LOGIN / 60), 2)) AS TEMPO_LOGIN,
               NMCLH.NOME_CLH
          FROM SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ A,
               RHFP0340                        CARGO,
               RHFP0500                        NMCLH,
               RHFP0307                        G,
               RHFP0321                        K
         WHERE TO_DATE(SUBSTR(HORA_INICIAL, 1, 10)) >=
               to_date('15/' ||
                       to_char(add_months(TRUNC(SYSDATE), -1), 'mm/yyyy'),
                       'dd/mm/yyyy')
           AND TO_DATE(SUBSTR(HORA_INICIAL, 1, 10)) <=
               to_date('15/' || to_char(TRUNC(SYSDATE), 'mm/yyyy')) -- PERÍODO ENTRE DIA 15 DO MES PASSADO AO DIA 15 DO MES ATUAL
           AND CARGO.COD_CONTRATO = A.COD_USUARIO
           AND G.COD_CONTRATO = A.COD_USUARIO
           AND K.COD_HORAS_BASE = G.COD_HORAS_BASE
           AND G.DATA_FIM = '31/12/2999'
           AND CARGO.DATA_FIM = '31/12/2999'
           AND NMCLH.COD_CLH = CARGO.COD_CLH
           AND CARGO.COD_CLH NOT IN (102, 47, 225, 120)
           AND NMCLH.NOME_CLH NOT LIKE '%GERENTE%'
           AND NOT EXISTS
         (SELECT 1
                  FROM V_DADOS_PESSOA Y
                 WHERE Y.COD_CONTRATO = A.COD_USUARIO
                   AND (Y.DES_GRUPO LIKE '%FRANCO GIORGI%' OR
                       Y.COD_UNIDADE IN ('205', '289', '567', '016', '392'))
           AND Y.COD_CONTRATO = A.COD_USUARIO) -- NÃO IMPORTA HORAS OPERADAS DE VENDEDOR DE MODA MASCULINA DAS FILIAIS FRANCO GIORGI E DAS LOJAS COM SINDICATO (63, 159)
 GROUP BY A.COD_USUARIO, K.QTD_HORBAS_MES, NMCLH.NOME_CLH) TEMPO, RHFP0300 CT
 WHERE CT.COD_CONTRATO = TEMPO.COD_USUARIO
   AND NOT EXISTS
 (SELECT 1
          FROM RHFP1004 A
         WHERE A.COD_CONTRATO = TEMPO.COD_USUARIO
           AND (DATA_MOV = TO_CHAR((LAST_DAY(SYSDATE)), 'DD/MM/YYYY') OR
               DATA_MOV = DATA_FIM)
           AND COD_VD = 838
           AND COD_EVENTO IN (1, 17)) -- VALIDA/IMPEDE INSERÇÃO CASO JÁ INFORMADO O VD838
--AND TEMPO.COD_USUARIO IN (383058,379928,337196,387898)
 GROUP BY TEMPO.COD_USUARIO,
          CT.DATA_FIM,
          TEMPO.QTD_HORBAS_MES,
          TEMPO.NOME_CLH;