/*SQL PARA GERAR CONFERÊNCIA DO CONTÁBIL -- AJUSTANDO*/

/*OFICIAL V1*/

WITH B_AGG AS (
    SELECT
        B.COD_LANCAMENTO,
        B.COD_CONTA_CONTABIL,
        B.TIPO_LANCAMENTO,
        SUM(B.VALOR_LANCAMENTO) AS VALOR_LANCAMENTO
    FROM RHFP0408 B
    GROUP BY
        B.COD_LANCAMENTO,
        B.COD_CONTA_CONTABIL,
        B.TIPO_LANCAMENTO
),
A_AGG AS (
    SELECT
        A.NOME_CLASSE_CONT,
        A.COD_TOTAL,
        A.NOME_TOTAL,
        A.COD_CONTA_CONTABIL,
        A.NOME_CONTA_CONTABIL,
        A.COD_CONTRAPARTIDA,
        A.COD_HISTORICO,
        A.DES_HISTORICO,
        A.COD_LANCAMENTO,
        LISTAGG(A.COD_VD, ' | ') WITHIN GROUP (ORDER BY A.COD_VD) AS COD_VD
    FROM V_DADOS_CONTABIL_AVT A
    WHERE A.COD_CLASSE_CONT = 21
    GROUP BY
        A.NOME_CLASSE_CONT,
        A.COD_TOTAL,
        A.NOME_TOTAL,
        A.COD_CONTA_CONTABIL,
        A.NOME_CONTA_CONTABIL,
        A.COD_CONTRAPARTIDA,
        A.COD_HISTORICO,
        A.DES_HISTORICO,
        A.COD_LANCAMENTO
)
SELECT
    A.NOME_CLASSE_CONT,
    A.COD_TOTAL,
    A.NOME_TOTAL,
    ' ' AS ESPACO,
    A.COD_VD,

    /* ====== DÉBITO (número + formatado) ====== */
    --SUM(CASE WHEN B.TIPO_LANCAMENTO = 'D' THEN B.VALOR_LANCAMENTO ELSE 0 END) AS VALOR_DEBITO,
    TO_CHAR(
      SUM(CASE WHEN B.TIPO_LANCAMENTO = 'D' THEN B.VALOR_LANCAMENTO ELSE 0 END),
      'FM999G999G999G990D00',
      'NLS_NUMERIC_CHARACTERS='',.'''
    ) AS VALOR_DEBITO_FMT,

    /* ====== CRÉDITO (número + formatado) ====== */
    --SUM(CASE WHEN B.TIPO_LANCAMENTO = 'C' THEN B.VALOR_LANCAMENTO ELSE 0 END) AS VALOR_CREDITO,
    TO_CHAR(
      SUM(CASE WHEN B.TIPO_LANCAMENTO = 'C' THEN B.VALOR_LANCAMENTO ELSE 0 END),
      'FM999G999G999G990D00',
      'NLS_NUMERIC_CHARACTERS='',.'''
    ) AS VALOR_CREDITO_FMT,

    A.COD_CONTA_CONTABIL,
    A.NOME_CONTA_CONTABIL,
    A.COD_CONTRAPARTIDA,
    A.COD_HISTORICO,
    A.DES_HISTORICO
FROM A_AGG A
LEFT JOIN B_AGG B
    ON B.COD_LANCAMENTO     = A.COD_LANCAMENTO
   AND B.COD_CONTA_CONTABIL = A.COD_CONTA_CONTABIL
GROUP BY
    A.NOME_CLASSE_CONT,
    A.COD_TOTAL,
    A.NOME_TOTAL,
    A.COD_VD,
    A.COD_CONTA_CONTABIL,
    A.NOME_CONTA_CONTABIL,
    A.COD_CONTRAPARTIDA,
    A.COD_HISTORICO,
    A.DES_HISTORICO
ORDER BY A.COD_TOTAL
   







/*OFICIAL V2*/

WITH B_AGG AS (
    SELECT
        B.COD_LANCAMENTO,
        B.COD_CONTA_CONTABIL,
        B.TIPO_LANCAMENTO,
        SUM(B.VALOR_LANCAMENTO) AS VALOR_LANCAMENTO
    FROM RHFP0408 B
    GROUP BY
        B.COD_LANCAMENTO,
        B.COD_CONTA_CONTABIL,
        B.TIPO_LANCAMENTO
),

/* Base do A */
A_BASE AS (
    SELECT
        A.NOME_CLASSE_CONT,
        A.COD_TOTAL,
        A.NOME_TOTAL,
        A.COD_LANCAMENTO,
        A.COD_CONTA_CONTABIL,
        A.COD_VD
    FROM V_DADOS_CONTABIL_AVT A
    WHERE A.COD_CLASSE_CONT = 23
),

/* 🔥 CHAVES ÚNICAS para somar valores (evita multiplicação) */
A_KEYS AS (
    SELECT DISTINCT
        NOME_CLASSE_CONT,
        COD_TOTAL,
        NOME_TOTAL,
        COD_LANCAMENTO,
        COD_CONTA_CONTABIL
    FROM A_BASE
),

/* Lista de COD_VD por TOTAL (detalhe separado) */
VD_TOTAL AS (
    SELECT
        NOME_CLASSE_CONT,
        COD_TOTAL,
        NOME_TOTAL,
        LISTAGG(COD_VD, ' | ') WITHIN GROUP (ORDER BY COD_VD) AS COD_VD,
        COD_CONTA_CONTABIL
    FROM (
        /* se teu Oracle suportar, você pode trocar por LISTAGG(DISTINCT...) */
        SELECT DISTINCT
            NOME_CLASSE_CONT, COD_TOTAL, NOME_TOTAL, COD_VD, COD_CONTA_CONTABIL
        FROM A_BASE
    )
    GROUP BY
        NOME_CLASSE_CONT,
        COD_TOTAL,
        NOME_TOTAL,
        COD_CONTA_CONTABIL
),

/* Valores por TOTAL (somando a partir das chaves únicas) */
VAL_TOTAL AS (
    SELECT
        K.NOME_CLASSE_CONT,
        K.COD_TOTAL,
        K.NOME_TOTAL,
        SUM(CASE WHEN B.TIPO_LANCAMENTO = 'D' THEN B.VALOR_LANCAMENTO ELSE 0 END) AS VALOR_DEBITO,
        SUM(CASE WHEN B.TIPO_LANCAMENTO = 'C' THEN B.VALOR_LANCAMENTO ELSE 0 END) AS VALOR_CREDITO
    FROM A_KEYS K
    LEFT JOIN B_AGG B
        ON B.COD_LANCAMENTO     = K.COD_LANCAMENTO
       AND B.COD_CONTA_CONTABIL = K.COD_CONTA_CONTABIL
    GROUP BY
        K.NOME_CLASSE_CONT,
        K.COD_TOTAL,
        K.NOME_TOTAL
)

SELECT DISTINCT
    V.NOME_CLASSE_CONT AS "Nome da Classe Contábil",
    V.COD_TOTAL || ' - ' || V.NOME_TOTAL as "Totalizador Contábil",
    V.COD_VD AS "VDs que compõem o contábil",

    TO_CHAR(
      T.VALOR_DEBITO,
      'FM999G999G999G990D00',
      'NLS_NUMERIC_CHARACTERS='',.'''
    ) AS "Valor do Débito",

    TO_CHAR(
      T.VALOR_CREDITO,
      'FM999G999G999G990D00',
      'NLS_NUMERIC_CHARACTERS='',.'''
    ) AS "Valor do Crédito",
    
    v.COD_CONTA_CONTABIL AS "Conta Contábil"

FROM VD_TOTAL V
JOIN VAL_TOTAL T
  ON T.NOME_CLASSE_CONT = V.NOME_CLASSE_CONT
 AND T.COD_TOTAL        = V.COD_TOTAL
 AND T.NOME_TOTAL       = V.NOME_TOTAL
ORDER BY V.COD_TOTAL;







/*
SELECT * FROM RHFP0408
where cod_classe_cont = 21

SELECT DISTINCT COD_TOTAL
FROM V_DADOS_CONTABIL_AVT
where cod_classe_cont = 21

SELECT NOME_CLASSE_CONT,
       COD_TOTAL,
       NOME_TOTAL,
       ' ' AS ESPAÇO,
      -- COD_VD,
       --NOME_VD,
       COD_CONTA_CONTABIL,
       NOME_CONTA_CONTABIL,
       COD_CONTRAPARTIDA,
       --TIPO_LANCAMENTO,
       --COD_HISTORICO,
       --DES_HISTORICO 
FROM V_DADOS_CONTABIL_AVT
WHERE COD_CLASSE_CONT = 21


*/
















