/* Período alvo */
WITH PARAMS AS (
  SELECT DATE '2022-01-01' AS D_INI,
         DATE '2025-12-31' AS D_FIM
  FROM DUAL
),
DATAS_REF AS (
  SELECT ADD_MONTHS(TRUNC(p.D_INI,'MM'), LEVEL-1) AS DTA_INI,
         LAST_DAY(ADD_MONTHS(TRUNC(p.D_INI,'MM'), LEVEL-1)) AS DTA_FIM
  FROM PARAMS p
  CONNECT BY ADD_MONTHS(TRUNC(p.D_INI,'MM'), LEVEL-1) <= TRUNC(p.D_FIM,'MM')
),

/* HISTÓRICO DE CONTRATOS (sem filtrar por EDICAO_ORG_4) */
CONTRATOS AS (
  SELECT DISTINCT
    CT.STATUS,
    CT.COD_CONTRATO,
    CT.DES_PESSOA,
    CT.DATA_NASCIMENTO,
    CT.DATA_ADMISSAO,
    CT.DATA_DEMISSAO,
    FN.COD_FUNCAO,
    FN.DES_FUNCAO,
    FN.DATA_INI_CLH,
    FN.DATA_FIM_CLH,
    HR.HR_BASE_MES,
    HR.DATA_INI_HR,
    HR.DATA_FIM_HR,
    CT.IND_DEFICIENCIA,
    CT.SEXO,
    ORG.COD_EMP,
    ORG.EDICAO_EMP,
    ORG.DES_EMP,
    ORG.COD_ORGANOGRAMA,
    ORG.COD_UNIDADE,
    ORG.DES_UNIDADE,
    ORG.DATA_INI_ORG,
    ORG.DATA_FIM_ORG,
    ORG.COD_REDE,
    ORG.DES_REDE,
    ORG.COD_TIPO,
    ORG.DES_TIPO,
    M.DTA_FIM AS MES_REF
  FROM V_DADOS_CONTRATO_AVT    CT
  JOIN VH_EST_ORG_CONTRATO_AVT ORG ON ORG.COD_CONTRATO = CT.COD_CONTRATO
  JOIN VH_HIST_HORAS_COLAB_AVT HR  ON HR.COD_CONTRATO  = CT.COD_CONTRATO
  JOIN VH_CARGO_CONTRATO_AVT   FN  ON FN.COD_CONTRATO  = CT.COD_CONTRATO
  CROSS JOIN DATAS_REF M
  WHERE
    CT.DATA_ADMISSAO <= M.DTA_FIM
    AND NVL(CT.DATA_DEMISSAO, DATE '2999-12-31') >= M.DTA_INI
    AND ORG.DATA_INI_ORG <= M.DTA_FIM AND NVL(ORG.DATA_FIM_ORG, DATE '2999-12-31') >= M.DTA_INI
    AND FN.DATA_INI_CLH  <= M.DTA_FIM AND NVL(FN.DATA_FIM_CLH,  DATE '2999-12-31') >= M.DTA_INI
    AND HR.DATA_INI_HR   <= M.DTA_FIM AND NVL(HR.DATA_FIM_HR,   DATE '2999-12-31') >= M.DTA_INI
    AND ORG.COD_EMP = 8
    --AND FN.DES_FUNCAO LIKE '%REGIONAL'
),

--SELECT * FROM CONTRATOS

/* LOJAS nas cidades do e-mail (nível 5) + dados do nível 3; adiciono EDICAO_ORG para mapear regionais */
LOJAS_RELACAO AS (
  SELECT 
    T5.COD_ORGANOGRAMA,
    TO_NUMBER(T5.EDICAO_ORG) AS COD_UNIDADE,
    T5.NOME_ORGANOGRAMA_B    AS DES_UNIDADE,
    T5.COD_REDE,
    T5.EDICAO_ORG            AS EDICAO_ORG_LOJA,
    T3.TIP_LOGRA,
    T3.LOGRADOURO,
    T3.BAIRRO,
    T3.CIDADE,
    T3.COD_UF,
    T3.CNPJ
  FROM V_EST_ORG_AVT T5
  LEFT JOIN V_EST_ORG_AVT T3
         ON T3.COD_TIPO = T5.COD_TIPO
        AND T3.COD_NIVEL_ORG = 3
        AND T3.EDICAO_ORG = T5.EDICAO_ORG
  WHERE T5.COD_TIPO = 1
    AND T5.COD_NIVEL_ORG = 5
    AND T3.CIDADE IN ('ALECRIM','CATUIPE','CERRO LARGO','CORONEL BICACO','CRISSIUMAL','CRUZ ALTA',
                      'ENTRE IJUIS','GIRUA','GUARANI DAS MISSOES','HORIZONTINA','IBIRUBA','IJUI',
                      'PANAMBI','PORTO XAVIER','SANTA BARBARA DO SUL','SANTA ROSA','SANTO ANGELO',
                      'SANTO AUGUSTO','SANTO CRISTO','SAO LUIZ GONZAGA','SAO PAULO DAS MISSOES',
                      'TENENTE PORTELA','TRES DE MAIO','TRES PASSOS','TUPANCIRETA','TUPARENDI')
),

/* Mapa REGIONAL (nível 3) ? LOJAS (nível 5) pela mesma EDICAO_ORG */
REGIONAL_MAP AS (
  SELECT DISTINCT
         R.COD_ORGANOGRAMA AS COD_ORG_REGIONAL,
         L.COD_ORGANOGRAMA AS COD_ORG_LOJA
  FROM V_EST_ORG_AVT R
  JOIN LOJAS_RELACAO L
    ON L.EDICAO_ORG_LOJA = R.EDICAO_ORG
  WHERE R.COD_NIVEL_ORG = 3   -- regionais
)

/* ======== SAÍDA ÚNICA ======== */
-- A) GERENTE DE LOJA: casa direto com a loja (nível 5)
SELECT DISTINCT
  LR.COD_UNIDADE,
  LR.DES_UNIDADE,
  LR.CIDADE,
  LR.COD_UF,
  LR.CNPJ,
  C.COD_CONTRATO,
  C.DES_PESSOA,
  C.DATA_ADMISSAO,
  C.DATA_DEMISSAO,
  C.DES_FUNCAO,
  C.DATA_INI_CLH,
  C.DATA_FIM_CLH,
  C.DATA_INI_ORG,
  C.DATA_FIM_ORG
FROM CONTRATOS C
JOIN LOJAS_RELACAO LR
  ON LR.COD_ORGANOGRAMA = C.COD_ORGANOGRAMA
WHERE UPPER(TRIM(C.DES_FUNCAO)) LIKE 'GERENTE%'

UNION ALL

-- B) GERENTE REGIONAL: mapeia regional (nível 3) ? lojas (nível 5) das cidades alvo
SELECT DISTINCT
  LR.COD_UNIDADE,
  LR.DES_UNIDADE,
  LR.CIDADE,
  LR.COD_UF,
  LR.CNPJ,
  C.COD_CONTRATO,
  C.DES_PESSOA,
  C.DATA_ADMISSAO,
  C.DATA_DEMISSAO,
  C.DES_FUNCAO,
  C.DATA_INI_CLH,
  C.DATA_FIM_CLH,
  C.DATA_INI_ORG,
  C.DATA_FIM_ORG
FROM CONTRATOS C
JOIN REGIONAL_MAP RM
  ON RM.COD_ORG_REGIONAL = C.COD_ORGANOGRAMA
JOIN LOJAS_RELACAO LR
  ON LR.COD_ORGANOGRAMA = RM.COD_ORG_LOJA
WHERE UPPER(TRIM(C.DES_FUNCAO)) LIKE '%REGIONAL%'
ORDER BY COD_CONTRATO;
