--SQL PARA MAPEAR HORÁRIOS DAS LOJAS
  --CRIADO VIEW V_HORARIOS_LOJAS_AVT



SELECT UNI.COD_UNIDADE,
       UNI.DES_UNIDADE,
       UNI.COD_TURNO,
       HOR.COD_SEQ_JORNADA,
       HOR.DIA_ESOCIAL,
       CASE
         WHEN HOR.COD_SEQ_JORNADA = 1 THEN
          'DOMINGO'
         WHEN HOR.COD_SEQ_JORNADA = 2 THEN
          'SEGUNDA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 3 THEN
          'TERÇA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 4 THEN
          'QUARTA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 5 THEN
          'QUINTA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 6 THEN
          'SEXTA-FEIRA'
         WHEN HOR.COD_SEQ_JORNADA = 7 THEN
          'SÁBADO'
       END AS DIA_SEMANA,
       CASE
         WHEN HOR.COD_SEQ_JORNADA = 1 AND
              (HOR.HORENT_ESOCIAL IS NULL OR HOR.HORENT_ESOCIAL = '') THEN
          'DSR'
         ELSE
          HOR.HORENT_ESOCIAL
       END HORA_ENTRADA,
       CASE
         WHEN HOR.COD_SEQ_JORNADA = 1 AND
              (HOR.HORSAI_ESOCIAL IS NULL OR HOR.HORSAI_ESOCIAL = '') THEN
          'DSR'
         ELSE
          HOR.HORSAI_ESOCIAL
       END HORA_SAIDA
  FROM V_DADOS_LOJAS_AVT UNI
 INNER JOIN RHAF1120 HOR ON UNI.COD_TURNO = HOR.COD_TURNO
 ORDER BY UNI.COD_UNIDADE ASC, HOR.COD_SEQ_JORNADA ASC