--SQL PARA MAPERAR IDADE, MESES E TEMPO MÉDIO DE EMPRESA POR COLABORADOR

--VERSÃO 1 PROTÓTIPO

SELECT A.COD_CONTRATO,
       A.DES_PESSOA,
       B.DATA_NASCIMENTO,
       A.DTA_ADMISSAO,
       EXTRACT(YEAR FROM :DATA_REFERENCIA) -
       EXTRACT(YEAR FROM B.DATA_NASCIMENTO) AS IDADE,
       TRUNC(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DTA_ADMISSAO) / 12) AS ANOS_NA_EMPRESA,
       ROUND(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DTA_ADMISSAO)) AS MESES_NA_EMPRESA,
       ROUND(AVG(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DTA_ADMISSAO))
             OVER(PARTITION BY EXTRACT(YEAR FROM :DATA_REFERENCIA) -
                  EXTRACT(YEAR FROM B.DATA_NASCIMENTO))) AS MEDIA_MESES_POR_IDADE
  FROM V_DADOS_PESSOA A
  JOIN RHFP0200 B ON A.COD_PESSOA = B.COD_FUNC
 WHERE (EXTRACT(YEAR FROM :DATA_REFERENCIA) -
       EXTRACT(YEAR FROM B.DATA_NASCIMENTO)) IN (18, 19, 20, 21)
 ORDER BY IDADE ASC




--====================================================================--



--VERSÃO 2

SELECT
    A.COD_CONTRATO,
    C.NOME_PESSOA,
    B.DATA_NASCIMENTO,
    A.DATA_INICIO,

    -- Calculando a idade considerando mês e dia
    CASE
        WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM :DATA_REFERENCIA) OR
            (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM :DATA_REFERENCIA) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM :DATA_REFERENCIA)) THEN
            EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
        ELSE
            EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
    END AS Idade,

    TRUNC(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DATA_INICIO) / 12) AS Anos_Na_Empresa,
    ROUND(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DATA_INICIO)) AS Meses_Na_Empresa,
    ROUND(AVG(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DATA_INICIO)) OVER (PARTITION BY
            CASE
                WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM :DATA_REFERENCIA) OR
                    (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM :DATA_REFERENCIA) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM :DATA_REFERENCIA)) THEN
                    EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
                ELSE
                    EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
            END)) AS Media_Meses_Por_Idade

FROM
    RHFP0300 A
JOIN
    RHFP0200 B ON A.COD_FUNC = B.COD_FUNC
JOIN
    PESSOA C ON C.COD_PESSOA = B.COD_FUNC
WHERE
    A.DATA_FIM IS NULL
AND
    CASE
        WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM :DATA_REFERENCIA) OR
            (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM :DATA_REFERENCIA) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM :DATA_REFERENCIA)) THEN
            EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
        ELSE
            EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
    END IN (18, 19, 20, 21)



--==========


SELECT
    A.COD_CONTRATO,
    C.NOME_PESSOA,
    B.DATA_NASCIMENTO,
    A.DATA_INICIO,
    D.COD_UNIDADE,
    D.NOME_ORGANOGRAMA,
    D.COD_EMP,

    -- Calculando a idade considerando mês e dia
    CASE
        WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM :DATA_REFERENCIA) OR
            (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM :DATA_REFERENCIA) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM :DATA_REFERENCIA)) THEN
            EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
        ELSE
            EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
    END AS Idade,

    TRUNC(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DATA_INICIO) / 12) AS Anos_Na_Empresa,
    ROUND(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DATA_INICIO)) AS Meses_Na_Empresa,
    ROUND(AVG(MONTHS_BETWEEN(:DATA_REFERENCIA, A.DATA_INICIO)) OVER (PARTITION BY
            CASE
                WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM :DATA_REFERENCIA) OR
                    (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM :DATA_REFERENCIA) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM :DATA_REFERENCIA)) THEN
                    EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
                ELSE
                    EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
            END)) AS Media_Meses_Por_Idade

FROM
    RHFP0300 A
JOIN
    RHFP0200 B ON A.COD_FUNC = B.COD_FUNC
JOIN
    PESSOA C ON C.COD_PESSOA = B.COD_FUNC
JOIN
    V_DADOS_PESSOA D ON A.COD_CONTRATO = D.COD_CONTRATO
WHERE
    A.DATA_FIM IS NULL
AND
    CASE
        WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM :DATA_REFERENCIA) OR
            (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM :DATA_REFERENCIA) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM :DATA_REFERENCIA)) THEN
            EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
        ELSE
            EXTRACT(YEAR FROM :DATA_REFERENCIA) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
    END IN (18, 19, 20, 21)
AND D.COD_EMP = 8




--================================================================--



--VERSÃO 3

SELECT 
    A.COD_CONTRATO,
    C.NOME_PESSOA,
    B.DATA_NASCIMENTO,
    A.DATA_INICIO,
    
    -- Calculando a idade considerando mês e dia
    CASE 
        WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM SYSDATE) OR 
            (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM SYSDATE) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM SYSDATE)) THEN
            EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
        ELSE
            EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
    END AS Idade,
    
    TRUNC(MONTHS_BETWEEN(SYSDATE, A.DATA_INICIO) / 12) AS Anos_Na_Empresa,
    ROUND(MONTHS_BETWEEN(SYSDATE, A.DATA_INICIO)) AS Meses_Na_Empresa,
    ROUND(AVG(MONTHS_BETWEEN(SYSDATE, A.DATA_INICIO)) OVER (PARTITION BY 
            CASE 
                WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM SYSDATE) OR 
                    (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM SYSDATE) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM SYSDATE)) THEN
                    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
                ELSE
                    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
            END)) AS Media_Meses_Por_Idade
    
FROM 
    RHFP0300 A 
JOIN 
    RHFP0200 B ON A.COD_FUNC = B.COD_FUNC
JOIN 
    PESSOA C ON C.COD_PESSOA = B.COD_FUNC
WHERE 
    A.DATA_FIM IS NULL
AND 
    CASE 
        WHEN EXTRACT(MONTH FROM B.DATA_NASCIMENTO) < EXTRACT(MONTH FROM SYSDATE) OR 
            (EXTRACT(MONTH FROM B.DATA_NASCIMENTO) = EXTRACT(MONTH FROM SYSDATE) AND EXTRACT(DAY FROM B.DATA_NASCIMENTO) <= EXTRACT(DAY FROM SYSDATE)) THEN
            EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO)
        ELSE
            EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM B.DATA_NASCIMENTO) - 1
    END IN (18, 19, 20, 21)