SELECT COD_USUARIO,
       COD_UNIDADE,
       HORA_INICIAL,
       HORA_FINAL,
       TEMPO_LOGIN,
       SUM(ROUND((TEMPO_LOGIN / 60), 2)) AS TEMPO_LOGIN_EM_HORAS
  FROM SISLOGWEB.GER_TEMPO_LOGIN@NLGRZ
WHERE TEMPO_LOGIN LIKE '%-%'
   AND COD_USUARIO = 394070
   /*AND SUBSTR(HORA_INICIAL, 1, 10) BETWEEN '01/01/2025' AND
               '31/07/2025'*/
   AND TO_DATE(HORA_INICIAL, 'DD/MM/YYYY HH24:MI:SS') >=
       TO_DATE('01/01/2025', 'DD/MM/YYYY')
GROUP BY COD_USUARIO, COD_UNIDADE, HORA_INICIAL, HORA_FINAL, TEMPO_LOGIN
ORDER BY TO_DATE(HORA_INICIAL, 'DD/MM/YYYY HH24:MI:SS');