--==SQL QUE RETORNA OS TIPOS DE CADA COLUNA DE UMA TABELA/VIEW

SELECT COLUMN_NAME,
       DATA_TYPE,
       DATA_LENGTH,
       DATA_PRECISION,
       DATA_SCALE,
       NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE TABLE_NAME = 'V_DADOS_COLAB_AVT'