--===TABELA DE BACKUP DAS CONTAS COM NOMES ORIGINAIS ORIGINAIS

RHFP0403_BKP 

--===========================================================

--==TBL DAS CONTAS CONTABEIS
SELECT *
FROM RHFP0403
WHERE COD_CONTA_CONTABIL LIKE '%341%'


---===SQL QUE MAPEIA ESTRUTURA CONTÁBIL - AS 3 CLASSES DA GRAZZIOTIN

SELECT * 
FROM V_DADOS_CONTABIL_AVT
WHERE COD_CLASSE_CONT = 21

UNION ALL

SELECT NULL AS COD_VD,
       NULL AS NOME_VD,
       NULL AS COD_CONTA_CONTABIL,
       NULL AS NOME_CONTA_CONTABIL,
       NULL AS TIPO_LANCAMENTO,
       NULL AS DES_TIPO_LANCAMENTO,
       NULL AS COD_CONTRAPARTIDA,
       NULL AS COD_HISTORICO,
       NULL AS DES_HISTORICO,
       NULL AS COD_HISTORICO_CONTRA,
       NULL AS COD_TOTAL,
       NULL AS NOME_TOTAL,
       NULL AS COD_CLASSE_CONT,
       NULL AS NOME_CLASSE_CONT,
       NULL AS COD_NIVEL_CONTABIL       
FROM DUAL

UNION ALL

SELECT * 
FROM V_DADOS_CONTABIL_AVT
WHERE COD_CLASSE_CONT = 22

UNION ALL

SELECT NULL AS COD_VD,
       NULL AS NOME_VD,
       NULL AS COD_CONTA_CONTABIL,
       NULL AS NOME_CONTA_CONTABIL,
       NULL AS TIPO_LANCAMENTO,
       NULL AS DES_TIPO_LANCAMENTO,
       NULL AS COD_CONTRAPARTIDA,
       NULL AS COD_HISTORICO,
       NULL AS DES_HISTORICO,
       NULL AS COD_HISTORICO_CONTRA,
       NULL AS COD_TOTAL,
       NULL AS NOME_TOTAL,
       NULL AS COD_CLASSE_CONT,
       NULL AS NOME_CLASSE_CONT,
       NULL AS COD_NIVEL_CONTABIL       
FROM DUAL

UNION ALL

SELECT * 
FROM V_DADOS_CONTABIL_AVT
WHERE COD_CLASSE_CONT = 23
