/*SQL REL PAGAMENTOS ALUGUÉIS POR DEPÓSITO = AJUSTANDO*/

SELECT C.COD_GRUPO AS COD_GRUPO,
       C.DES_GRUPO AS DES_GRUPO,
       B.COD_UNIDADE AS COD_UNIDADE,
       E.DES_FANTASIA AS DES_UNIDADE,
       V.COD_CONTA AS COD_CONTA,
       SUM(A.VAL_TOTAL) AS VAL_BRUTO,
       SUM(A.VAL_IRRF) AS VAL_IRRF,
       SUM(A.VAL_LIQUIDO) AS VAL_LIQUIDO,
       SUM(DECODE(A.COD_PESS_RECEB, 415, A.VAL_LIQUIDO, 0)) AS VAL_RETENCAO,
       SUM(A.VAL_LIQUIDO - DECODE(A.COD_PESS_RECEB, 415, A.VAL_LIQUIDO, 0)) AS VAL_DESC_RETENCAO
  FROM GRAZZ.GRZ_LOC_MVTO       A,
       GRAZZ.GRZ_LOC_VALORES    V,
       GRAZZ.GRZ_GRUPO_UNIDADES B,
       GRAZZ.GRZ_GRUPOS         C,
       GRAZZ.GRZ_UNIDADES       E
 WHERE A.COD_EMPRESA = V.COD_EMPRESA
   AND A.COD_VALOR = V.COD_VALOR
   AND A.COD_EMPRESA = E.COD_EMPRESA
   AND A.COD_UNIDADE = E.COD_UNIDADE
   AND A.COD_UNIDADE = B.COD_UNIDADE
   AND B.COD_GRUPO = C.COD_GRUPO
   AND B.COD_GRUPO BETWEEN 0 AND 999
   AND A.COD_UNIDADE BETWEEN 0 AND 9999
   AND A.DTA_VCTO BETWEEN '01/10/2024' AND '15/10/2024'
   --AND V.COD_CONTA = 341410
 GROUP BY C.COD_GRUPO,
          C.DES_GRUPO,
          B.COD_UNIDADE,
          E.DES_FANTASIA,
          V.COD_CONTA
 ORDER BY C.COD_GRUPO, B.COD_UNIDADE;