--SQL PARA AJUSTAR A OPÇÃO DE CONCLUSÃO DAS AVALIAÇÕES DE CONTRATO DE EXPERIÊNCIAS

SELECT * FROM RHFP0643
WHERE COD_CONTRATO = 393167;

UPDATE RHFP0643
SET IND_OPCAO_CONCLUSAO = 'P'
WHERE COD_CONTRATO = 393167;