/*SQL GERAÇÃO SANGRIAS CAIXA DAS LOJAS - SISLOGWEB/NL*/

SELECT A.COD_EMP, 
        A.COD_UNIDADE, 
        A.DTA_MOVIMENTO, 
        B.DES_FANTASIA, 
        F.COD_GRUPO, 
        A.NUM_EQUIPAMENTO, 
        A.NUM_CUPOM, 
        A.COD_OPERADOR, 
        C.DES_USUARIO OPERADOR, 
        D.COD_AUTORIZANTE, 
        E.DES_USUARIO AUTORIZANTE, 
        A.HOR_MVTO, 
        A.VLR_TOTAL 
 FROM NL.GRZ_LOJAS_FORMAS_PAGTO A
 INNER JOIN V_UNIDADES B ON A.COD_UNIDADE = B.COD_UNIDADE 
                         AND A.COD_EMP = B.REDE 
 INNER JOIN NL.GRZ_USUARIO_WEB C ON A.COD_OPERADOR = C.COD_USUARIO 
 INNER JOIN NL.GRZ_LOJAS_MVTO_ACESSOS D ON A.COD_EMP = D.COD_EMP 
                                        AND A.COD_UNIDADE = D.COD_UNIDADE 
                                        AND A.DTA_MOVIMENTO = D.DTA_MVTO 
                                        AND A.NUM_CUPOM = D.NUM_CUPOM 
                                        AND A.COD_OPERADOR = D.COD_OPERADOR 
                                        AND A.IND_STATUS = D.IND_STATUS 
                                        AND A.NUM_EQUIPAMENTO = D.NUM_EQUIPAMENTO 
 LEFT JOIN NL.GRZ_USUARIO_WEB E ON E.COD_USUARIO = D.COD_AUTORIZANTE 
 INNER JOIN NL.GE_GRUPOS_UNIDADES F ON F.COD_UNIDADE = A.COD_UNIDADE 
                                    AND F.COD_GRUPO BETWEEN 8701 AND 8720 
WHERE A.COD_EMP IN (10,30,40,50,70)
 AND A.COD_UNIDADE BETWEEN 7643 AND 7643
 AND A.DTA_MOVIMENTO BETWEEN '01/05/2025' AND '31/05/2025'
 --AND A.NUM_EQUIPAMENTO BETWEEN :SPDVINI AND :SPDVFIM 
 --AND A.COD_OPERADOR BETWEEN :SUSUARIOINI AND :SUSUARIOFIM 
 AND A.TIP_ORIGEM = 2 
 AND ROWNUM <= 1000 
 ORDER BY A.COD_UNIDADE,A.DTA_MOVIMENTO;
 
 
 
SELECT A.COD_EMP,
       A.COD_UNIDADE,
       A.DTA_MOVIMENTO,
       B.DES_FANTASIA,
       F.COD_GRUPO,
       A.NUM_EQUIPAMENTO,
       A.NUM_CUPOM,
       A.COD_OPERADOR,
       C.DES_USUARIO OPERADOR,
       D.COD_AUTORIZANTE,
       E.DES_USUARIO AUTORIZANTE,
       A.HOR_MVTO,
       A.VLR_TOTAL
  FROM NL.GRZ_LOJAS_FORMAS_PAGTO A
 INNER JOIN V_UNIDADES B ON A.COD_UNIDADE = B.COD_UNIDADE
                        AND A.COD_EMP = B.REDE
 INNER JOIN NL.GRZ_USUARIO_WEB C ON A.COD_OPERADOR = C.COD_USUARIO
 INNER JOIN NL.GRZ_LOJAS_MVTO_ACESSOS D ON A.COD_EMP = D.COD_EMP
                                       AND A.COD_UNIDADE = D.COD_UNIDADE
                                       AND A.DTA_MOVIMENTO = D.DTA_MVTO
                                       AND A.NUM_CUPOM = D.NUM_CUPOM
                                       AND A.COD_OPERADOR = D.COD_OPERADOR
                                       AND A.IND_STATUS = D.IND_STATUS
                                       AND A.NUM_EQUIPAMENTO =
                                           D.NUM_EQUIPAMENTO
  LEFT JOIN NL.GRZ_USUARIO_WEB E ON E.COD_USUARIO = D.COD_AUTORIZANTE
 INNER JOIN NL.GE_GRUPOS_UNIDADES F ON F.COD_UNIDADE = A.COD_UNIDADE
                                   AND F.COD_GRUPO BETWEEN 8701 AND 8720
 WHERE A.COD_EMP IN (10, 30, 40, 50, 70)
   AND A.COD_UNIDADE BETWEEN :SUNIDADEINI AND :SUNIDADEFIM
   AND A.DTA_MOVIMENTO BETWEEN :SDATAINI AND :SDATAFIM
   AND A.NUM_EQUIPAMENTO BETWEEN :SPDVINI AND :SPDVFIM
   AND A.COD_OPERADOR BETWEEN :SUSUARIOINI AND :SUSUARIOFIM
   AND A.TIP_ORIGEM = 2
   AND ROWNUM <= 1000
 ORDER BY A.COD_UNIDADE, A.DTA_MOVIMENTO;