--ORDEM DE DELETAÇÃO DE PESQUISAS DO CARGOS E SALÁRIOS


SELECT * FROM RHCS0900;

--PRIMEIRA A DELETAR
DELETE 
FROM RHCS0900
WHERE COD_PESQUISA_OPINIAO = 1

--===========================================--

SELECT * FROM RHCS0920;

--SEGUNDA A DELETAR
DELETE 
FROM RHCS0920
WHERE COD_PESQUISA_OPINIAO = 1

--===========================================--

SELECT * FROM RHCS0910;

--TERCEIRA A DELETAR
DELETE 
FROM RHCS0910
WHERE COD_PESQUISA_OPINIAO = 1

--===========================================--

SELECT * FROM RHCS0890;

--QUARTA A DELETAR
DELETE 
FROM RHCS0890
WHERE COD_PESQUISA_OPINIAO = 1

--===========================================--

SELECT * FROM RHCS0880;

--QUINTA A DELETAR
DELETE 
FROM RHCS0880
WHERE COD_PESQUISA_OPINIAO = 1

--===========================================--

SELECT * FROM RHCS0870;

--SEXTA A DELETAR
DELETE 
FROM RHCS0870
WHERE COD_PESQUISA_OPINIAO = 1