WITH DADOS_PESSOA AS (
    SELECT 
        COD_CONTRATO,
        MAX(CASE 
              WHEN TO_CHAR(COD_FUNCAO) = '325' THEN 1 
              ELSE 0 
            END) AS IND_REGIONAL,
        MAX(CASE 
              WHEN TO_CHAR(COD_FUNCAO) = '325' THEN COD_FUNCAO 
            END) AS COD_FUNCAO,
        MAX(CASE 
              WHEN TO_CHAR(COD_FUNCAO) = '325' THEN DES_FUNCAO 
            END) AS DES_FUNCAO
    FROM V_DADOS_PESSOA
    GROUP BY COD_CONTRATO
)
SELECT distinct
    VLW.COD_CONTRATO,
    VLW.DES_PESSOA,
    DP.COD_FUNCAO,
    DP.DES_FUNCAO,
    VLW.COD_UNIDADE,
    VLW.COD_GRUPO_UNIDADE,
    999  AS NOVO_COD_GRUPO,
    999  AS NOVO_COD_GRUPO_ACESSO,
    9010 AS NOVO_COD_GRUPO_MENUS
FROM V_LOJAS_WEB VLW
INNER JOIN DADOS_PESSOA DP
        ON DP.COD_CONTRATO = VLW.COD_CONTRATO
WHERE DP.IND_REGIONAL = 1
ORDER BY VLW.COD_CONTRATO;