/*SQL - Retrona valores do evento 10 - Adto. Quinzenal*/     

SELECT
    E.EDICAO_ORG AS EDICAO_ORG_REP,
    E.EDICAO_ORG,
    CASE
        WHEN E.EDICAO_ORG = '815' THEN 'COMPRAS GRAZZIOTIN'
        WHEN E.EDICAO_ORG = '835' THEN 'COMPRAS POR MENOS'
        WHEN E.EDICAO_ORG = '845' THEN 'COMPRAS FRANCO GIORGI'
        WHEN E.EDICAO_ORG = '855' THEN 'COMPRAS TOTTAL'
        WHEN E.EDICAO_ORG = '907' THEN 'ADM - E-COMMERCE'
        ELSE F.NOME_ORGANOGRAMA
    END AS NOME_ORGANOGRAMA,
    '01/02/2025' || ' - ' || '28/02/2025' AS REFERENCIA,
    A.COD_VD,
    B.NOME_VD,
    TO_CHAR(SUM(NVL(A.VALOR_VD, 0)), 'FM999G999G990D00') AS TOTAL_MES,  -- FORMATAÇÃO APLICADA
    TO_CHAR(SUM(SUM(NVL(A.VALOR_VD, 0))) OVER(), 'FM999G999G990D00') AS TOTAL_GERAL_LIQ, -- FORMATAÇÃO APLICADA
    ROW_NUMBER() OVER(PARTITION BY TO_NUMBER(E.EDICAO_ORG) ORDER BY A.COD_VD) AS RN
FROM
    RHFP1006 A
    INNER JOIN RHFP1000 B ON A.COD_VD = B.COD_VD
    INNER JOIN RHFP0310 D ON A.COD_CONTRATO = D.COD_CONTRATO 
        AND '28/02/2025' BETWEEN D.DATA_INICIO AND D.DATA_FIM
    LEFT JOIN RHFP0401 E ON D.COD_ORGANOGRAMA = E.COD_ORGANOGRAMA 
        AND '28/02/2025' BETWEEN E.DATA_INICIO AND NVL(E.DATA_FIM, TO_DATE('31/12/2999', 'DD/MM/YYYY'))
    /*LEFT JOIN RHFP0111 FM ON FM.COD_FORMA_PGTO = (
        SELECT CT.COD_FORMA_PGTO 
        FROM RHFP0300 CT 
        WHERE CT.COD_CONTRATO = A.COD_CONTRATO 
        AND '28/02/2025' BETWEEN CT.DATA_INICIO AND CT.DATA_FIM
        FETCH FIRST 1 ROWS ONLY
    ) -- Pega apenas uma forma de pagamento para exibição (se necessário)*/
    LEFT JOIN RHFP0400 F ON F.COD_ORGANOGRAMA = 
        CASE
            WHEN E.EDICAO_ORG = '900' THEN E.COD_NIVEL4  -- FORÇA O AGRUPAMENTO PELO NÍVEL 4 PARA O 900
            WHEN E.COD_NIVEL5 > 0 THEN E.COD_NIVEL5
            ELSE E.COD_NIVEL4
        END
WHERE
    COD_MESTRE_EVENTO IN (
        SELECT COD_MESTRE_EVENTO
        FROM RHFP1003
        WHERE TO_DATE(DATA_REFERENCIA) BETWEEN '01/02/2025' AND '28/02/2025'
        AND COD_ORGANOGRAMA = 8
        AND COD_EVENTO = 10
    )
    AND E.EDICAO_NIVEL2 = '008'
    AND A.COD_VD = 1003
    AND A.VALOR_VD <> 0
    AND NOT EXISTS (
        SELECT 1
        FROM RHFP0300 CT
        WHERE CT.COD_CONTRATO = A.COD_CONTRATO
        AND (('28/02/2025' BETWEEN CT.DATA_INICIO AND CT.DATA_FIM) OR
             (CT.DATA_FIM IS NULL AND CT.DATA_FIM <= '28/02/2025'))
        --AND '28/02/2025' BETWEEN CT.DATA_INICIO AND CT.DATA_FIM
        AND CT.COD_FORMA_PGTO = 1
    )
GROUP BY
    E.EDICAO_ORG,
    F.NOME_ORGANOGRAMA,
    A.COD_VD,
    B.NOME_VD;

