--SQL PARA MAPEAR HORAS COM CARACTERES NÃO NUMERICOS

SELECT * FROM RHFP0306
WHERE HORAS_AFASTAMENTO IS NOT NULL


SELECT * FROM RHFP0306
WHERE REGEXP_LIKE(HORAS_AFASTAMENTO, '[^0-9:]')


UPDATE RHFP0306
SET HORAS_AFASTAMENTO = REGEXP_REPLACE(HORAS_AFASTAMENTO, '[^0-9:]', '')
WHERE REGEXP_LIKE(HORAS_AFASTAMENTO, '[^0-9:]')