SELECT OP.COD_OPERADOR, VDP.DES_PESSOA, ORG.COD_ORGANOGRAMA, EDI.EDICAO_ORG, PE.COD_CAMPO, PE.VALOR
        FROM V_DADOS_PESSOA VDP,
             PE0002         PE,
             RHFP0300       CT,
             OPERADOR       OP,
             RHFP0400       ORG,
             RHFP0401       EDI
       WHERE PE.VALOR = VDP.cod_grupo_unidade
         AND CT.COD_CONTRATO = VDP.COD_CONTRATO
         AND OP.COD_PESSOA = CT.COD_FUNC
         AND ORG.COD_PESSOA = PE.COD_PESSOA
         AND EDI.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
         AND VDP.COD_FUNCAO = 325 -- regionais
         --AND PE.COD_CAMPO = 1
         AND PE.VALOR BETWEEN 8701 AND 8726
         --AND PE.VALOR = 8725
      -- AND VDP.COD_CONTRATO = 378992
      ORDER BY PE.VALOR ASC