--====FORMULÁRIO DE IRREGULARIDADE GERAL, TODAS AS OCORRÊNCIAS====--



SELECT DISTINCT RHAF1123.COD_CONTRATO,
                VDP.DES_PESSOA,
                RHFP0401.EDICAO_ORG AS COD_UNIDADE,
                RHFP0401.EDICAO_ORG || ' - ' || RHFP0400.NOME_ORGANOGRAMA AS DES_UNIDADE,
                
                CASE
                  WHEN VDP.COD_GRUPO = 1 THEN
                   10
                  WHEN VDP.COD_GRUPO = 2 THEN
                   50
                  WHEN VDP.COD_GRUPO = 3 THEN
                   30
                  WHEN VDP.COD_GRUPO = 4 THEN
                   40
                  WHEN VDP.COD_GRUPO = 7 THEN
                   70
                  ELSE
                   NULL
                END AS COD_REDE,
                DECODE(CASE
                         WHEN VDP.COD_GRUPO = 1 THEN
                          10
                         WHEN VDP.COD_GRUPO = 2 THEN
                          50
                         WHEN VDP.COD_GRUPO = 3 THEN
                          30
                         WHEN VDP.COD_GRUPO = 4 THEN
                          40
                         WHEN VDP.COD_GRUPO = 7 THEN
                          70
                         ELSE
                          0
                       END,
                       10,
                       'GRAZZIOTIN',
                       50,
                       'TOTTAL',
                       30,
                       'PORMENOS',
                       40,
                       'FRANCO GIORGI',
                       70,
                       'GZT STORE') AS DES_REDE,
                
                RHAF1129.COD_OCORRENCIA,
                RHAF1129.NOME_OCORRENCIA,
                TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'MONTH') AS NOME_MES,
                TRIM(TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'Month')) || '/' ||
                TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'YYYY') AS MES_OCORRENCIA,
                --TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'DD/MM/YYYY') AS DATA_COMPLETA,
                RHAF1123.ORIGEM,
                
                /*COLUNA +2HRS EXTRAS*/
                CASE
                  WHEN RHAF1123.COD_OCORRENCIA IN
                       (203, 204, 207, 208, 209, 210, 211, 212, 213, 214, 2022, 2023, 2026, 2029, 2036, 2041, 2043) AND
                       ROUND(RHAF1123.NUM_HORAS, 2) > 2 THEN
                   TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
                   TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
                  ELSE
                   'SEM OCORRÊNCIA PARA O PERÍODO'
                END AS HORAS_EXTRAS_MAIS_2HRS,
                /*DATA PARA +2HRS EXTRAS*/
                CASE
                  WHEN RHAF1123.COD_OCORRENCIA IN
                       (203, 204, 207, 208, 209, 210, 211, 212, 213, 214, 2022, 2023, 2026, 2029, 2036, 2041, 2043) AND
                       ROUND(RHAF1123.NUM_HORAS, 2) > 2 THEN
                   TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'DD/MM/YYYY')
                  ELSE
                   'SEM REGISTRO PARA O PERÍODO'
                END AS DATA_OCORR_MAIS_2H,
                
                /*COLUNA +10HRS EXTRAS*/
                CASE
                  WHEN (RHAF1123.COD_OCORRENCIA = 2 AND
                       RHAF1123.NUM_HORAS > 10) THEN
                   TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
                   TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
                  ELSE
                   'SEM OCORRÊNCIA PARA O PERÍODO'
                END AS HORAS_EXTRAS_MAIS_10HRS,
                /*DATA PARA +10HRS EXTRAS*/
                CASE
                  WHEN (RHAF1123.COD_OCORRENCIA = 2 AND
                       RHAF1123.NUM_HORAS > 10) THEN
                   TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'DD/MM/YYYY')
                  ELSE
                   'SEM REGISTRO PARA O PERÍODO'
                END AS DATA_OCORR_MAIS_10H,
                
                /*COLUNA INTERV -15MIN*/
                CASE
                  WHEN (RHAF1145.CARGA_HORARIA BETWEEN 165 AND 180 AND
                       RHAF1123.COD_OCORRENCIA = 2049) THEN
                   TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
                   TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
                  ELSE
                   'SEM OCORRÊNCIA PARA O PERÍODO'
                END AS INTERVALOS_INFERIOR_15MIN,
                /*DATA PARA INTERV -15MIN*/
                CASE
                  WHEN (RHAF1145.CARGA_HORARIA BETWEEN 165 AND 180 AND
                       RHAF1123.COD_OCORRENCIA = 2049) THEN
                   TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'DD/MM/YYYY')
                  ELSE
                   'SEM REGISTRO PARA O PERÍODO'
                END AS DATA_OCORR_INT_INFE_15MIN,
                
                /*COLUNA INTERV -1HR*/
                CASE
                  WHEN (RHAF1145.CARGA_HORARIA BETWEEN 195 AND 220 AND
                       RHAF1123.COD_OCORRENCIA = 2048) THEN
                   TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
                   TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
                  ELSE
                   'SEM OCORRÊNCIA PARA O PERÍODO'
                END AS INTERVALOS_INFERIOR_1H,
                /*DATA PARA INTERV -1HR*/
                CASE
                  WHEN (RHAF1145.CARGA_HORARIA BETWEEN 195 AND 220 AND
                       RHAF1123.COD_OCORRENCIA = 2048) THEN
                   TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'DD/MM/YYYY')
                  ELSE
                   'SEM REGISTRO PARA O PERÍODO'
                END AS DATA_OCORR_INT_INFE_1H,
                
                /*COLUNA INTRAJORN INFE 11HRS*/
                CASE
                  WHEN (RHAF1123.COD_OCORRENCIA = 901) THEN
                   TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
                   TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
                  ELSE
                   'SEM OCORRÊNCIA PARA O PERÍODO'
                END AS INTRAJORNADA_INFE_11HRS,
                /*DATA PARA INTERV -1HR*/
                CASE
                  WHEN (RHAF1123.COD_OCORRENCIA = 901) THEN
                   TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'DD/MM/YYYY')
                  ELSE
                   'SEM REGISTRO PARA O PERÍODO'
                END AS DATA_OCORR_INTRAJOR_INFE_11H,
                
                TRIM(TO_CHAR(SYSDATE, 'MONTH')) || '/' ||
                TO_CHAR(SYSDATE, 'YYYY') AS REFERENCIA,
                TO_CHAR(SYSDATE, 'DD') || ' de ' ||
                TRIM(TO_CHAR(SYSDATE, 'Month')) || ' de ' ||
                TO_CHAR(SYSDATE, 'YYYY') AS REF_COMPLETA,
                GER.DES_PESSOA AS GESTOR

  FROM RHAF1123                RHAF1123,
       RHAF1129                RHAF1129,
       RHAF1138                RHAF1138,
       RHAF1108                RHAF1108,
       RHAF1119                RHAF1119,
       RHAF1145                RHAF1145,
       RHFP0310                RHFP0310,
       RHFP0401                RHFP0401,
       RHFP0400                RHFP0400,
       V_DADOS_PESSOA          VDP,
       V_SUPERIOR_IMEDIATO_AVT GER
 WHERE RHAF1123.COD_OCORRENCIA = RHAF1129.COD_OCORRENCIA
   AND RHAF1123.COD_CONTRATO = RHAF1108.COD_CONTRATO
   AND RHAF1123.COD_CONTRATO = RHAF1119.COD_CONTRATO
   AND RHAF1119.COD_TURNO = RHAF1145.COD_TURNO
   AND RHAF1123.COD_CONTRATO = RHFP0310.COD_CONTRATO
   AND RHFP0310.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA
   AND RHFP0401.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
   AND VDP.COD_CONTRATO = RHAF1123.COD_CONTRATO
   AND RHAF1129.COD_MOTIVO_OCO = RHAF1138.COD_MOTIVO_OCO
   AND GER.COD_UNIDADE = VDP.COD_UNIDADE
   AND RHAF1123.DATA_OCORRENCIA BETWEEN RHAF1108.DATA_INICIO AND
       RHAF1108.DATA_FIM
   AND RHAF1123.DATA_OCORRENCIA BETWEEN ADD_MONTHS(SYSDATE, -6) AND SYSDATE
   AND RHAF1123.DATA_OCORRENCIA BETWEEN :DATA_INI_OCORR AND :DATA_FIM_OCORR
   AND :DATA_REFERENCIA BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM
   AND :DATA_REFERENCIA BETWEEN RHAF1119.DATA_INICIO AND RHAF1119.DATA_FIM
   AND (
       /*COLUNA +2HRS*/
        (ROUND(RHAF1123.NUM_HORAS, 2) > 2 AND
        RHAF1123.COD_OCORRENCIA IN
        (203, 204, 207, 208, 209, 210, 211, 212, 213, 214, 2022, 2023, 2026, 2029, 2036, 2041, 2043)) OR
       /*COLUNA +10HRS*/
        (RHAF1123.COD_OCORRENCIA = 2 AND RHAF1123.NUM_HORAS > 10) OR
       /*COLUNA INTERV -15MIN*/
        (RHAF1145.CARGA_HORARIA BETWEEN 165 AND 180 AND
        RHAF1123.COD_OCORRENCIA = 2049) OR
       /*COLUNA INTERV -1HR*/
        (RHAF1145.CARGA_HORARIA BETWEEN 195 AND 220 AND
        RHAF1123.COD_OCORRENCIA = 2048) OR
       /*COLUNA INTRAJORN INFE 1H*/
        (RHAF1123.COD_OCORRENCIA = 901))
   AND GER.TIPO = 'LOJA'
   AND GER.IND_RESP_UNI = 'S'
   AND (RHFP0401.EDICAO_ORG = :FILIAL OR :FILIAL = 0)
   AND (VDP.COD_GRUPO = TO_CHAR(:REDE) OR TO_CHAR(:REDE) = 0)
 ORDER BY RHFP0401.EDICAO_ORG ASC, RHAF1123.COD_CONTRATO ASC












--===VERSÃO 2 DO SELECT (CASO DE PRA USAR)===--

SELECT RHAF1123.COD_CONTRATO,
       VDP.DES_PESSOA,
       RHFP0401.EDICAO_ORG AS COD_UNIDADE,
       RHFP0401.EDICAO_ORG || ' - ' || RHFP0400.NOME_ORGANOGRAMA AS DES_UNIDADE,
       CASE
         WHEN VDP.COD_GRUPO = 1 THEN
          10
         WHEN VDP.COD_GRUPO = 2 THEN
          50
         WHEN VDP.COD_GRUPO = 3 THEN
          30
         WHEN VDP.COD_GRUPO = 4 THEN
          40
         WHEN VDP.COD_GRUPO = 7 THEN
          70
         ELSE
          NULL
       END AS COD_REDE,
       DECODE(VDP.COD_GRUPO,
              1,
              'GRAZZIOTIN',
              2,
              'TOTTAL',
              3,
              'PORMENOS',
              4,
              'FRANCO GIORGI',
              7,
              'GZT STORE',
              0) AS DES_REDE,
       RHAF1129.COD_OCORRENCIA,
       RHAF1129.NOME_OCORRENCIA,
       TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'MONTH') AS NOME_MES,
       TRIM(TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'Month')) || '/' ||
       TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'YYYY') AS MES_OCORRENCIA,
       TO_CHAR(RHAF1123.DATA_OCORRENCIA, 'DD/MM/YYYY') AS DATA_COMPLETA,
       RHAF1123.ORIGEM,
       CASE
         WHEN RHAF1123.COD_OCORRENCIA IN
              (203, 204, 207, 208, 209, 210, 211, 212, 213, 214, 2022, 2023, 2026, 2029, 2036, 2041, 2043) AND
              ROUND(RHAF1123.NUM_HORAS, 2) > 2 THEN
          TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
          TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
         ELSE
          'SEM OCORRÊNCIA PARA O PERÍODO'
       END AS HORAS_EXTRAS_MAIS_2HRS,
       CASE
         WHEN RHAF1123.COD_OCORRENCIA = 2 AND RHAF1123.NUM_HORAS > 10 THEN
          TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
          TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
         ELSE
          'SEM OCORRÊNCIA PARA O PERÍODO'
       END AS HORAS_EXTRAS_MAIS_10HRS,
       CASE
         WHEN RHAF1145.CARGA_HORARIA BETWEEN 165 AND 180 AND
              RHAF1123.COD_OCORRENCIA = 2049 THEN
          TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
          TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
         ELSE
          'SEM OCORRÊNCIA PARA O PERÍODO'
       END AS INTERVALOS_INFERIOR_15MIN,
       CASE
         WHEN RHAF1145.CARGA_HORARIA BETWEEN 195 AND 220 AND
              RHAF1123.COD_OCORRENCIA = 2048 THEN
          TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
          TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
         ELSE
          'SEM OCORRÊNCIA PARA O PERÍODO'
       END AS INTERVALOS_INFERIOR_1H,
       CASE
         WHEN RHAF1123.COD_OCORRENCIA = 901 THEN
          TO_CHAR(TRUNC(RHAF1123.NUM_HORAS)) || ':' ||
          TO_CHAR(MOD(RHAF1123.NUM_HORAS * 60, 60), 'FM00')
         ELSE
          'SEM OCORRÊNCIA PARA O PERÍODO'
       END AS INTRAJORN_INFERIOR_1H,
       TRIM(TO_CHAR(SYSDATE, 'MONTH')) || '/' || TO_CHAR(SYSDATE, 'YYYY') AS REFERENCIA,
       TO_CHAR(SYSDATE, 'DD') || ' de ' || TRIM(TO_CHAR(SYSDATE, 'Month')) ||
       ' de ' || TO_CHAR(SYSDATE, 'YYYY') AS REF_COMPLETA,
       GER.DES_PESSOA AS GESTOR
  FROM RHAF1123
  JOIN RHAF1129 ON RHAF1123.COD_OCORRENCIA = RHAF1129.COD_OCORRENCIA
  JOIN RHAF1108 ON RHAF1123.COD_CONTRATO = RHAF1108.COD_CONTRATO
  JOIN RHAF1119 ON RHAF1123.COD_CONTRATO = RHAF1119.COD_CONTRATO
  JOIN RHAF1145 ON RHAF1119.COD_TURNO = RHAF1145.COD_TURNO
  JOIN RHFP0310 ON RHAF1123.COD_CONTRATO = RHFP0310.COD_CONTRATO
  JOIN RHFP0401 ON RHFP0310.COD_ORGANOGRAMA = RHFP0401.COD_ORGANOGRAMA
  JOIN RHFP0400 ON RHFP0401.COD_ORGANOGRAMA = RHFP0400.COD_ORGANOGRAMA
  JOIN V_DADOS_PESSOA VDP ON VDP.COD_CONTRATO = RHAF1123.COD_CONTRATO
  JOIN RHAF1138 ON RHAF1129.COD_MOTIVO_OCO = RHAF1138.COD_MOTIVO_OCO
  JOIN V_SUPERIOR_IMEDIATO_AVT GER ON GER.COD_UNIDADE = VDP.COD_UNIDADE
 WHERE RHAF1123.DATA_OCORRENCIA BETWEEN '01/10/2023' AND '31/10/2023'
   AND '01/10/2023' BETWEEN RHFP0310.DATA_INICIO AND RHFP0310.DATA_FIM
   AND '01/10/2023' BETWEEN RHAF1119.DATA_INICIO AND RHAF1119.DATA_FIM
   AND ((ROUND(RHAF1123.NUM_HORAS, 2) > 2 AND
       RHAF1123.COD_OCORRENCIA IN
       (203, 204, 207, 208, 209, 210, 211, 212, 213, 214, 2022, 2023, 2026, 2029, 2036, 2041, 2043)) OR
       (RHAF1123.COD_OCORRENCIA = 2 AND RHAF1123.NUM_HORAS > 10) OR
       (RHAF1145.CARGA_HORARIA BETWEEN 165 AND 180 AND
       RHAF1123.COD_OCORRENCIA = 2049) OR (RHAF1145.CARGA_HORARIA BETWEEN 195 AND 220 AND
       RHAF1123.COD_OCORRENCIA = 2048) OR (RHAF1123.COD_OCORRENCIA = 901))
   AND GER.TIPO = 'LOJA'
   AND GER.IND_RESP_UNI = 'S'
 ORDER BY RHFP0401.EDICAO_ORG ASC, RHAF1123.COD_CONTRATO ASC;