--==SQL PARA ATERAR DATA FIM DO TIPO DE CONTRATO DE EXPERIÊNCIA

SELECT * FROM RHFP0304
WHERE COD_CONTRATO = 395183

UPDATE RHFP0304
SET DATA_FIM = '14/06/2024'
WHERE DATA_FIM = '06/06/2024'
AND COD_CONTRATO = 395183


--====================================--

--==SQL PARA ALTERAR DATA DA AVALIAÇÃO DO CONTRATO CONTRATO
   /*SE NECESSÁRIO, SE NÃO, 
      POR DENTRO DO SISTEMA JÁ PERMITE, DESDE QUE A DATA_FIM DO SQL ANTERIOR ESTEJA ENTRE A DATA DA AVALIAÇÃO*/
      
SELECT * FROM RHFP0305
WHERE COD_CONTRATO = 395183

UPDATE RHFP0305
SET DATA_AVALIACAO = ''
WHERE COD_CONTRATO = 395183

--===================================--

--==TIPO DE CONTRATO PARA AVALIAÇÃO DE EXPERIÊNCIA

SELECT * FROM RHFP0314
WHERE COD_CONTRATO = 395183

--===================================---

--==SQL PARA MUDAR O GERTOR QUE IRÁ AVALIAR O COLABORADOR NA AVALIAÇÃO

SELECT *
FROM RHFP0643
WHERE COD_CONTRATO = 395183;


--UPDATE MAIS EFICAZ
SELECT A.*, A.ROWID
FROM RHFP0643 A
WHERE COD_CONTRATO = 395183;


