SELECT DISTINCT D.COD_CONTRATO
               ,C.DES_PESSOA AS NOME_FUNCIONARIO
               ,C.COD_UNIDADE
               ,C.NOME_ORGANOGRAMA
               ,E.COD_PERFIL
               ,PER.NOME_PERFIL
FROM RHFP0300 A, RHCS0310 B, V_DADOS_PESSOA C, RHCS0320 D, RHFP0100 EF, RHCS0290 E, RHCS0230 PER
WHERE B.DATA_AVALIACAO =  D.DATA_AVALIACAO 
AND B.COD_CONTRATO = C.COD_CONTRATO
AND B.COD_CONTRATO = D.COD_CONTRATO
AND C.DTA_ADMISSAO = A.DATA_INICIO
AND C.COD_CONTRATO = D.COD_CONTRATO
AND E.COD_CLH = C.COD_FUNCAO
AND PER.COD_PERFIL = E.COD_PERFIL
--AND D.DATA_AVALIACAO = '15/02/2022'
--AND C.DTA_ADMISSAO > '01/07/2021'
GROUP BY D.COD_CONTRATO
        ,C.DES_PESSOA
        ,C.COD_UNIDADE
        ,C.NOME_ORGANOGRAMA
        ,E.COD_PERFIL
        ,PER.NOME_PERFIL
ORDER BY 1, 5 ASC