SELECT AFAS.COD_CONTRATO,
       AFAS.DATA_INICIO,
       AFAS.DATA_FIM,
       AFAS.COD_CAUSA_AFAST,
       CAU.NOME_CAUSA_AFAST
  FROM RHFP0306 AFAS, RHFP0100 CAU
 WHERE AFAS.COD_CAUSA_AFAST = CAU.COD_CAUSA_AFAST
   AND AFAS.DATA_FIM = '31/12/2999'