SELECT DISTINCT AF.COD_CONTRATO
              , PSF.DES_PESSOA AS NOME_FUNCIONARIO
              , PSF.COD_UNIDADE AS FILIAL_ATUAL
              , PSF.COD_FUNCAO AS COD_CARGO
              , PSF.DES_FUNCAO AS NOME_CARGO
              , CH.COD_HORAS_BASE AS COD_CARGA_HORARIA
              , CH.QTD_HORBAS_MES AS CH_NO_MES
              , AF.COD_CAUSA_AFAST
              , AF.DATA_FIM, AF.DATA_INICIO, AF.DATA_FIM - AF.DATA_INICIO DIAS
              , TRUNC(24 * (AF.DATA_FIM - AF.DATA_INICIO)) HORAS
              , AF.COD_CID_10
              , PG.COD_VD
              , PG.VALOR_VD
              , PG.DATA_REFERENCIA
FROM RHFP0306 AF , V_DADOS_PESSOA PSF, RHFP1005 PG, RHFP0321 CH, RHFP0307 CDH
WHERE AF.COD_CID_10 IN ('B34.2', 'B34.9', 'B97.2', 'J0.19', 'J0.6', 'J0.69', 'J00'
                      , 'J01', 'J02', 'J02.0', 'J11.0', 'J118', 'J45.9', 'J98'
                      , 'J0.3', 'J11', 'R05', 'U07.2', 'U07.1', 'Z0.3', 'Z03.9'
                      , 'Z20', 'Z20.9', 'Z29.8')
AND AF.DATA_INICIO BETWEEN '01/11/2018' AND '09/11/2022'
AND PSF.COD_CONTRATO = AF.COD_CONTRATO
AND PG.COD_CONTRATO = AF.COD_CONTRATO
AND AF.COD_CONTRATO = CDH.COD_CONTRATO
AND CDH.COD_HORAS_BASE = CH.COD_HORAS_BASE
AND AF.COD_CAUSA_AFAST = 6
AND PG.COD_VD = 910
GROUP BY AF.COD_CONTRATO
       , PSF.DES_PESSOA
       , PSF.COD_UNIDADE
       , PSF.COD_FUNCAO
       , PSF.DES_FUNCAO
       , CH.COD_HORAS_BASE
       , CH.QTD_HORBAS_MES
       , AF.COD_CAUSA_AFAST
       , AF.DATA_INICIO
       , AF.DATA_FIM
       , AF.COD_CID_10
       , PG.COD_VD
       , PG.VALOR_VD
       , PG.DATA_REFERENCIA
ORDER BY PSF.COD_UNIDADE ASC


SELECT DISTINCT AF.COD_CONTRATO
              , PSF.DES_PESSOA AS NOME_FUNCIONARIO
              , PSF.COD_UNIDADE AS FILIAL_ATUAL
              , PSF.COD_FUNCAO AS COD_CARGO
              , PSF.DES_FUNCAO AS NOME_CARGO
              , CH.COD_HORAS_BASE AS COD_CARGA_HORARIA
              , CH.QTD_HORBAS_MES AS CH_NO_MES
              , AF.COD_CAUSA_AFAST
              , AF.DATA_FIM, AF.DATA_INICIO, AF.DATA_FIM - AF.DATA_INICIO DIAS
              , TRUNC(24 * (AF.DATA_FIM - AF.DATA_INICIO)) HORAS
              , AF.COD_CID_10
              , PG.COD_VD
              , PG.VALOR_VD
              --, PG.DATA_REFERENCIA
FROM RHFP0306 AF , V_DADOS_PESSOA PSF, RHFP1006 PG, RHFP0321 CH, RHFP0307 CDH
WHERE AF.COD_CID_10 IN ('B34.2', 'B34.9', 'B97.2', 'J0.19', 'J0.6', 'J0.69', 'J00'
                      , 'J01', 'J02', 'J02.0', 'J11.0', 'J118', 'J45.9', 'J98'
                      , 'J0.3', 'J11', 'R05', 'U07.2', 'U07.1', 'Z0.3', 'Z03.9'
                      , 'Z20', 'Z20.9', 'Z29.8')
--AND AF.DATA_INICIO BETWEEN '01/11/2018' AND '09/11/2022'
AND PSF.COD_CONTRATO = AF.COD_CONTRATO
AND PG.COD_CONTRATO = AF.COD_CONTRATO
AND AF.COD_CONTRATO = CDH.COD_CONTRATO
AND CDH.COD_HORAS_BASE = CH.COD_HORAS_BASE
AND AF.COD_CAUSA_AFAST = 6
AND PG.COD_VD = 910
GROUP BY AF.COD_CONTRATO
       , PSF.DES_PESSOA
       , PSF.COD_UNIDADE
       , PSF.COD_FUNCAO
       , PSF.DES_FUNCAO
       , CH.COD_HORAS_BASE
       , CH.QTD_HORBAS_MES
       , AF.COD_CAUSA_AFAST
       , AF.DATA_INICIO
       , AF.DATA_FIM
       , AF.COD_CID_10
       , PG.COD_VD
       , PG.VALOR_VD
       --, PG.DATA_REFERENCIA
ORDER BY PSF.COD_UNIDADE ASC