SELECT  EDICAO_NIVEL3,  EMAIL, COD_NIVEL3
         FROM RHFP0401 A
             ,RHFP0400 B
             ,JURIDICA C
WHERE A.COD_ORGANOGRAMA = B.COD_ORGANOGRAMA
AND C.EMAIL IS NOT NULL
AND A.COD_ORGANOGRAMA_SUB = 8
AND A.EDICAO_NIVEL3  NOT IN ('013', '001')
AND C.COD_PESSOA = B.COD_PESSOA
AND A.DATA_FIM = '31/12/2999'
 --AND A.EDICAO_NIVEL3 BETWEEN '002' AND '363'
ORDER BY A.EDICAO_NIVEL3;