/*SQL AUDITORIA, DESCOBRIR INCONSCISTÊNCIAS E PROCESSOS INDEVIDOS NO SISTEMA*/

SELECT 
    A.COD_AUDITORIA,
    A.NOME_FISICO_TABELA,
    A.NOME_USUARIO,
    A.NOME_TERMINAL,
    A.TIMESTAMP,
    MAX(CASE WHEN B.NOME_COLUNA = 'COD_CONTRATO' THEN B.VALOR_ANTIGO END) AS CONTRATO,
    MAX(CASE WHEN B.NOME_COLUNA = 'DATA_MOV' THEN B.VALOR_ANTIGO END) AS DATA_MOV,
    MAX(CASE WHEN B.NOME_COLUNA = 'COD_VD' THEN B.VALOR_ANTIGO END) AS COD_VD,
    MAX(CASE WHEN B.NOME_COLUNA = 'QTDE_VD' THEN B.VALOR_ANTIGO END) AS QTDE_VD,
    
    MAX(CASE WHEN B.NOME_COLUNA = 'DATA_DIGITACAO' THEN B.VALOR_ANTIGO END) AS DATA_DIGITACAO
FROM 
    RHAD0001 A
    JOIN RHAD0002 B ON A.COD_AUDITORIA = B.COD_AUDITORIA
WHERE 
    A.NOME_FISICO_TABELA = 'RHFP1004'
    AND TRUNC(A.TIMESTAMP) = TO_DATE('27/06/2025', 'DD/MM/YYYY')
    AND A.NOME_TERMINAL = '786-5481'
    AND A.TIPO_AUDITORIA = 'D'
    AND B.NOME_COLUNA IN ('COD_CONTRATO', 'COD_VD', 'DATA_DIGITACAO', 'DATA_MOV', 'QTDE_VD')
GROUP BY 
    A.COD_AUDITORIA,
    A.NOME_FISICO_TABELA,
    A.NOME_USUARIO,
    A.NOME_TERMINAL,
    A.TIMESTAMP
ORDER BY A.COD_AUDITORIA

  
SELECT A.COD_AUDITORIA, 
       A.NOME_FISICO_TABELA, 
       A.NOME_USUARIO, 
       A.NOME_TERMINAL, 
       A.TIMESTAMP,
       CASE
           WHEN B.NOME_COLUNA = 'COD_CONTRATO' THEN
            B.VALOR_ANTIGO
           ELSE 
            NULL
       END AS CONTRATO,
       CASE
           WHEN B.NOME_COLUNA = 'COD_VD' THEN
            B.VALOR_ANTIGO
           ELSE 
            NULL
       END AS VD
       --B.NOME_COLUNA,
       --B.VALOR_ANTIGO,
       --B.VALOR_NOVO       
FROM RHAD0001 A, RHAD0002 B
WHERE A.COD_AUDITORIA = B.COD_AUDITORIA
  AND A.NOME_FISICO_TABELA = 'RHFP1004'
  AND TRUNC(A.TIMESTAMP) = TO_DATE('27/06/2025', 'DD/MM/YYYY')
  AND A.NOME_TERMINAL = '786-5481'
  AND A.TIPO_AUDITORIA = 'D'
  AND B.NOME_COLUNA IN ('COD_CONTRATO', 'COD_VD', 'DATA_DIGITACAO', 'DATA_MOV', 'QTDE_VD')  
ORDER BY A.COD_AUDITORIA  

  
  

SELECT *
FROM RHAD0002
WHERE COD_AUDITORIA = 34429213
AND NOME_COLUNA IN ('COD_CONTRATO', 'COD_VD', 'DATA_DIGITACAO', 'DATA_MOV', 'QTDE_VD')