--MAPEAR TODAS AS LOJAS PARA ATUALIZAR E-MAILS   

SELECT J.COD_PESSOA, UNI.COD_UNIDADE, B.EDICAO_ORG, UNI.DES_FANTASIA, J.EMAIL, J.FANTASIA
FROM SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI, JURIDICA J, RHFP0400 A, RHFP0401 B
WHERE UNI.NUM_CGC = J.CGC
AND A.COD_PESSOA = J.COD_PESSOA
AND B.COD_ORGANOGRAMA = A.COD_ORGANOGRAMA
--AND UNI.DES_FANTASIA LIKE '%GZT %'
AND J.FANTASIA IN ('GRAZZIOTIN', 'PORMENOS', 'FRANCO GIORGI', 'TOTTAL', 'GZT')
ORDER BY UNI.COD_UNIDADE ASC 

--=======================--

--UPDATE PARA ATUALIZAR OS EMAIS DAS LOJAS

--EX: REDE GZT

UPDATE PESSOA_JURIDICA
SET EMAIL = CONCAT(SUBSTR(EMAIL, 1, INSTR(EMAIL, '@')), 'gztstore.com.br')
WHERE COD_PESSOA IN (
    SELECT J.COD_PESSOA
    FROM SISLOGWEB.V_UNIDADES_ATIVAS@NLGRZ UNI, JURIDICA J
    WHERE UNI.NUM_CGC = J.CGC
    AND J.FANTASIA = 'GZT'
)
AND SUBSTR(EMAIL, INSTR(EMAIL, '@') + 1) <> 'gztstore.com.br';
