--SQL AVALIAÇÕES DE DESEMPENHO SUPERIOR IMEDIATO ATUALIZADO PRA TRAZER QUEM ESTAVA AFASTADO NO PERÍODO DAS AVALIAÇÕES


--NOTAS SUPERIOR IMEDIATO

SELECT AVA.COD_CONTRATO,
       PE.NOME_PESSOA,
       CLH.COD_CLH,
       CLH.NOME_CLH,
       AVAD.DATA_INICIO_AVAL,
       AVAD.DATA_FIM_AVAL,
       AVA.NUM_PONTOS,
       AVA.COD_RELAC,
       EDI.EDICAO_ORG,
       NORG.NOME_ORGANOGRAMA,
       MAX(CASE
         WHEN AFAST.DATA_INICIO IS NOT NULL AND
              ((AFAST.DATA_INICIO >= '23/01/2023' AND AFAST.DATA_INICIO <= '21/04/2023') OR
               (AFAST.DATA_FIM >= '23/01/2023' AND AFAST.DATA_FIM <= '21/04/2023')) THEN 'SIM'
         ELSE 'NÃO'
       END) AS AFASTADO,
       CASE
         WHEN AVA.NUM_PONTOS IS NOT NULL THEN
          'REALIZADA'
         ELSE
          'NÃO REALIZADA'
       END AS SITUACAO
  FROM RHCS0320 AVA
  JOIN RHCS0310 AVAD ON AVA.COD_CONTRATO = AVAD.COD_CONTRATO
  JOIN RHFP0310 ORG ON AVA.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN RHFP0401 EDI ON EDI.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
  JOIN RHFP0400 NORG ON NORG.COD_ORGANOGRAMA = EDI.COD_ORGANOGRAMA
  JOIN RHFP0300 CONT ON CONT.COD_CONTRATO = AVA.COD_CONTRATO
  JOIN PESSOA PE ON PE.COD_PESSOA = CONT.COD_FUNC
  JOIN RHFP0340 CARG ON CARG.COD_CONTRATO = AVA.COD_CONTRATO
  JOIN RHFP0500 CLH ON CLH.COD_CLH = CARG.COD_CLH
  LEFT JOIN RHFP0306 AFAST ON AFAST.COD_CONTRATO = AVA.COD_CONTRATO
 WHERE ORG.DATA_FIM = '31/12/2999'
   AND AVAD.DATA_INICIO_AVAL = :DATA_INICIO
   AND AVAD.DATA_FIM_AVAL = :DATA_FIM
   AND CARG.DATA_FIM = '31/12/2999'
   AND AVA.DATA_AVALIACAO >= '23/01/2023'
   AND CONT.DATA_FIM IS NULL
   AND AVA.COD_RELAC = 1 --INDICADOR QUE SIGNIFICA QUE É A AVALIAÇÃO DO SUPERIOR IMEDIATO
   AND EDI.COD_NIVEL2 = :ORGANOGRAMA
   AND AVA.COD_CONTRATO = 389884
 GROUP BY AVA.COD_CONTRATO,
          PE.NOME_PESSOA,
          CLH.COD_CLH,
          CLH.NOME_CLH,
          AVA.NUM_PONTOS,
          AVAD.DATA_INICIO_AVAL,
          AVAD.DATA_FIM_AVAL,
          AVA.COD_RELAC,
          EDI.EDICAO_ORG,
          NORG.NOME_ORGANOGRAMA
 ORDER BY EDI.EDICAO_ORG ASC

--============

--NOTAS AUTO-AVALIAÇÃO

SELECT AVA.COD_CONTRATO,
       PE.NOME_PESSOA,
       CLH.COD_CLH,
       CLH.NOME_CLH,
       AVAD.DATA_INICIO_AVAL,
       AVAD.DATA_FIM_AVAL,
       AVA.NUM_PONTOS,
       AVA.COD_RELAC,
       EDI.EDICAO_ORG,
       NORG.NOME_ORGANOGRAMA,
       MAX(CASE
         WHEN AFAST.DATA_INICIO IS NOT NULL AND
              ((AFAST.DATA_INICIO >= '23/01/2023' AND AFAST.DATA_INICIO <= '21/04/2023') OR
               (AFAST.DATA_FIM >= '23/01/2023' AND AFAST.DATA_FIM <= '21/04/2023')) THEN 'SIM'
         ELSE 'NÃO'
       END) AS AFASTADO,
       CASE
         WHEN AVA.NUM_PONTOS IS NOT NULL THEN
          'REALIZADA'
         ELSE
          'NÃO REALIZADA'
       END AS SITUACAO
  FROM RHCS0320 AVA
  JOIN RHCS0310 AVAD ON AVA.COD_CONTRATO = AVAD.COD_CONTRATO
  JOIN RHFP0310 ORG ON AVA.COD_CONTRATO = ORG.COD_CONTRATO
  JOIN RHFP0401 EDI ON EDI.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
  JOIN RHFP0400 NORG ON NORG.COD_ORGANOGRAMA = EDI.COD_ORGANOGRAMA
  JOIN RHFP0300 CONT ON CONT.COD_CONTRATO = AVA.COD_CONTRATO
  JOIN PESSOA PE ON PE.COD_PESSOA = CONT.COD_FUNC
  JOIN RHFP0340 CARG ON CARG.COD_CONTRATO = AVA.COD_CONTRATO
  JOIN RHFP0500 CLH ON CLH.COD_CLH = CARG.COD_CLH
  LEFT JOIN RHFP0306 AFAST ON AFAST.COD_CONTRATO = AVA.COD_CONTRATO
 WHERE ORG.DATA_FIM = '31/12/2999'
   AND AVAD.DATA_INICIO_AVAL = :DATA_INICIO
   AND AVAD.DATA_FIM_AVAL = :DATA_FIM
   AND CARG.DATA_FIM = '31/12/2999'
   AND AVA.DATA_AVALIACAO >= '23/01/2023'
   AND CONT.DATA_FIM IS NULL
   AND AVA.COD_RELAC = 2 --INDICADOR QUE SIGNIFICA QUE É A AUTO--AVALIAÇÃO DO COLABORADOR
   AND EDI.COD_NIVEL2 = :ORGANOGRAMA
   AND AVA.COD_CONTRATO = 389884
 GROUP BY AVA.COD_CONTRATO,
          PE.NOME_PESSOA,
          CLH.COD_CLH,
          CLH.NOME_CLH,
          AVA.NUM_PONTOS,
          AVAD.DATA_INICIO_AVAL,
          AVAD.DATA_FIM_AVAL,
          AVA.COD_RELAC,
          EDI.EDICAO_ORG,
          NORG.NOME_ORGANOGRAMA
 ORDER BY EDI.EDICAO_ORG ASC






--====================================================--

----SQL ALTERNATIVO

SELECT AVA.COD_CONTRATO,
       PE.NOME_PESSOA,
       CLH.COD_CLH,
       CLH.NOME_CLH,
       AVAD.DATA_INICIO_AVAL,
       AVAD.DATA_FIM_AVAL,
       AVA.NUM_PONTOS,
       AVA.COD_RELAC,
       EDI.EDICAO_ORG,
       NORG.NOME_ORGANOGRAMA,
       MAX(CASE
         WHEN AFAST.DATA_INICIO IS NOT NULL AND 
              ((AFAST.DATA_INICIO >= '23/01/2023' AND AFAST.DATA_INICIO <= '21/04/2023') OR 
               (AFAST.DATA_FIM >= '23/01/2023' AND AFAST.DATA_FIM <= '21/04/2023')) THEN 'SIM'
         ELSE 'NÃO'
       END) AS AFASTADO,
       CASE
         WHEN AVA.NUM_PONTOS IS NOT NULL THEN 'REALIZADA'
         ELSE 'NÃO REALIZADA'
       END AS SITUACAO
  FROM RHCS0320 AVA, RHCS0310 AVAD, RHFP0310 ORG, RHFP0401 EDI,
       RHFP0400 NORG, RHFP0300 CONT, PESSOA PE, RHFP0340 CARG,
       RHFP0500 CLH, RHFP0306 AFAST
 WHERE AVA.COD_CONTRATO = ORG.COD_CONTRATO
   AND EDI.COD_ORGANOGRAMA = ORG.COD_ORGANOGRAMA
   AND CONT.COD_CONTRATO = AVA.COD_CONTRATO
   AND PE.COD_PESSOA = CONT.COD_FUNC
   AND NORG.COD_ORGANOGRAMA = EDI.COD_ORGANOGRAMA
   AND CARG.COD_CONTRATO = AVA.COD_CONTRATO
   AND CLH.COD_CLH = CARG.COD_CLH
   AND AVA.COD_CONTRATO = AFAST.COD_CONTRATO(+)
   AND ORG.DATA_FIM = '31/12/2999'
   AND AVAD.DATA_INICIO_AVAL = :DATA_INICIO
   AND AVAD.DATA_FIM_AVAL = :DATA_FIM
   AND CARG.DATA_FIM = '31/12/2999'
   AND AVA.DATA_AVALIACAO >= '23/01/2023'
   AND CONT.DATA_FIM IS NULL
   AND AVA.COD_RELAC = 1 --INDICADOR QUE SIGNIFICA QUE É A AVALIAÇÃO DO SUPERIOR IMEDIATO
   AND EDI.COD_NIVEL2 = :ORGANOGRAMA
 GROUP BY AVA.COD_CONTRATO,
          PE.NOME_PESSOA,
          CLH.COD_CLH,
          CLH.NOME_CLH,
          AVA.NUM_PONTOS,
          AVAD.DATA_INICIO_AVAL,
          AVAD.DATA_FIM_AVAL,
          AVA.COD_RELAC,
          EDI.EDICAO_ORG,
          NORG.NOME_ORGANOGRAMA
 ORDER BY EDI.EDICAO_ORG ASC
