
WITH OPERADORES AS (
    SELECT DISTINCT
           C.COD_CONTRATO,
           C.DES_PESSOA,
           C.DES_FUNCAO,
           C.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_COLAB,
           C.DES_UNIDADE,
           A.COD_OPERADOR,
           A.COD_PERFIL,
           D.NOME_PERFIL,
           B.COD_ORGANOGRAMA AS COD_ORGANOGRAMA_OPERADOR,
           'OPERADOR NÃO CADASTRADO NA OPERORG' AS STATUS_OP

    FROM OPERADOR A

    LEFT JOIN OPERORG B
      ON B.COD_OPERADOR = A.COD_OPERADOR

    JOIN V_DADOS_COLAB_AVT C
      ON C.COD_PESSOA = A.COD_PESSOA
      
    JOIN RHUS0010 D 
      ON A.COD_PERFIL = D.COD_PERFIL

    WHERE C.STATUS = 0
      AND (
             C.DES_FUNCAO LIKE '%GERENTE%'
          OR C.DES_FUNCAO LIKE '%SUPERVISOR%'
          OR C.DES_FUNCAO LIKE '%COMPRADOR%'
      )
      /*AND C.COD_UNIDADE NOT IN (
          768, 740, 769, 786, 780, 781, 900
      )*/
      AND C.COD_TIPO = 2

      -- Não encontrou o operador na OPERORG
      AND B.COD_OPERADOR IS NULL
      --AND A.COD_PERFIL IS NULL
)

SELECT *
FROM OPERADORES
ORDER BY COD_CONTRATO;