/*SQLs para mapear esquemas que usam DBLinks*/

SELECT DB_LINK, OWNER, USERNAME, HOST
FROM DBA_DB_LINKS;


SELECT OWNER, VIEW_NAME, TEXT_CLOB
FROM TEMP_VIEWS
WHERE UPPER(TEXT_CLOB) LIKE '%@GRZFOLHA%'
   OR UPPER(TEXT_CLOB) LIKE '%DBLINK%';

   
SELECT * FROM USER_REPSCHEMA 
   
SELECT DISTINCT OWNER, NAME, TYPE, TEXT
FROM ALL_SOURCE
WHERE UPPER(TEXT) LIKE '%@GRZFOLHA%'
   OR UPPER(TEXT) LIKE '%DBLINK%'; 


SELECT OWNER, VIEW_NAME
FROM ALL_VIEWS
WHERE UPPER(TEXT_VC) LIKE '%@NLGRZ%'
   OR UPPER(TEXT_VC) LIKE '%DBLINK%';