---SQLs PARA RETORNAR A QUANTIDADE DE LOJAS POR ANO


WITH LojasPorAno AS (
    SELECT COD_UNIDADE, DES_UNIDADE, DATA_INICIO, '2021' AS ANO
    FROM V_DADOS_LOJAS_AVT
    WHERE DATA_INICIO <= TO_DATE('2021-12-31', 'YYYY-MM-DD')
    UNION ALL
    SELECT COD_UNIDADE, DES_UNIDADE, DATA_INICIO, '2022' AS ANO
    FROM V_DADOS_LOJAS_AVT
    WHERE DATA_INICIO <= TO_DATE('2022-12-31', 'YYYY-MM-DD')
    UNION ALL
    SELECT COD_UNIDADE, DES_UNIDADE, DATA_INICIO, '2023' AS ANO
    FROM V_DADOS_LOJAS_AVT
    WHERE DATA_INICIO <= TO_DATE('2023-12-31', 'YYYY-MM-DD')
),
ContagemPorAno AS (
    SELECT ANO, COUNT(*) AS TOTAL_UNIDADES
    FROM LojasPorAno
    GROUP BY ANO
)
SELECT COD_UNIDADE, DES_UNIDADE, ANO
FROM LojasPorAno
UNION ALL
SELECT NULL AS COD_UNIDADE, NULL AS DES_UNIDADE, ANO || ' - Total de Unidades: ' || TO_CHAR(TOTAL_UNIDADES)
FROM ContagemPorAno
ORDER BY ANO, COD_UNIDADE;


--====================================---


--VERSÃO COM TOTAL DE LOJAS POR ANO

SELECT
    '2021' AS ANO,
    COUNT(COD_UNIDADE) AS TOTAL_UNIDADES
FROM
    V_DADOS_LOJAS_AVT
WHERE
    DATA_INICIO <= TO_DATE('2021-12-31', 'YYYY-MM-DD')
UNION ALL
SELECT
    '2022' AS ANO,
    COUNT(COD_UNIDADE) AS TOTAL_UNIDADES
FROM
    V_DADOS_LOJAS_AVT
WHERE
    DATA_INICIO <= TO_DATE('2022-12-31', 'YYYY-MM-DD')
UNION ALL
SELECT
    '2023' AS ANO,
    COUNT(COD_UNIDADE) AS TOTAL_UNIDADES
FROM
    V_DADOS_LOJAS_AVT
WHERE
    DATA_INICIO <= TO_DATE('2023-12-31', 'YYYY-MM-DD');