/*SQLs PARA ATUALIZAR PROCESSOS AUTOMÁTICOS*/

SELECT * FROM RHWF0405
WHERE COD_RELAT_GR = 'DE0001'


/*UPDATE PARA ATUALIZAR PERIODICIDADE DE UM PROCESSO*/
UPDATE RHWF0405
SET PERIODICIDADE = 'M'
WHERE COD_RELAT_GR = 'DE0001';

/*UPDATE PARA ATUALIZAR RELATÓRIO DE UM PROCESSO*/
UPDATE RHWF0405
SET COD_RELAT_GR = 'DE0001'
WHERE COD_RELAT_GR = 'DECLRACA';

/*VERSÃO PARA REMOVER PARTE DO NOME DO PROCESSO A ESQUERDA*/
UPDATE RHWF0405
SET NOME_PROCESSO = REPLACE(NOME_PROCESSO, 'DECLRACA - ', '')
WHERE COD_RELAT_GR = 'DE0001';

/*VERSÃO PARA INSERIR ALGO A MAIS NO NOME DO PROCESSO A ESQUERDA*/
UPDATE RHWF0405
SET NOME_PROCESSO = CONCAT('NOVO_', NOME_PROCESSO)
WHERE COD_RELAT_GR = 'DE0001';


/*VERSÃO PARA INSERIR ALGO A MAIS A DIREITA DO NOME DO PROCESSO*/
UPDATE RHWF0405
SET NOME_PROCESSO = CONCAT(NOME_PROCESSO, '_NOVO')
WHERE COD_RELAT_GR = 'DE0001';

