 CREATE TABLE BKP_GRZ_DADOS_CALCULO_APR_2025 AS
SELECT *
  FROM GRZ_DADOS_CALCULO_APR_ANUAL
 WHERE ANO = '2025';

CREATE TABLE BKP_GRZ_VLR_REGIOES_APR_2025 AS
SELECT *
  FROM GRZ_VALORES_REGIOES_APR_ANUAL
 WHERE ANO = '2025';


