/*TABELAS UMENTOR*/
SELECT * FROM GRZ_INT_UMENTOR_GESTORES_TEMP;
SELECT * FROM GRZ_INT_UMENTOR_COLABORADORES;
SELECT * FROM GRZ_INT_UMENTOR_CARGOS;
SELECT * FROM GRZ_INT_UMENTOR_FILIAIS;
SELECT * FROM GRZ_INT_UMENTOR_CONFIG;
SELECT * FROM GRZ_INT_UMENTOR_AREAS;
SELECT * FROM V_UMENTOR_FILIAIS;
SELECT * FROM GRZ_INT_UMENTOR_GESTORES_FIXOS;
SELECT * FROM GRZ_INT_UMENTOR_COLAB_EXP;
SELECT * FROM V_UMENTOR_COLABORADORES;
SELECT * FROM MIG_UMENTOR_REQUISICOES;
SELECT * FROM GRZ_INT_UMENTOR_COLAB_EXP_ENZO;
SELECT * FROM GRZ_INT_UMENTOR_AREAS_BKP;
SELECT * FROM V_UMENTOR_CARGOS;
SELECT * FROM V_UMENTOR_COLABORADORES_DESL;



/*INSERSÃO DE DADOS NA TABELA TEMPORÁRIA DOS GESTORES = MODELO*/

INSERT INTO GRZ_INT_UMENTOR_GESTORES_TEMP 
(COD_FUNCIONARIO, DES_COLABORADOR, CPF, DTA_INICIO, DTA_FIM, CPF_GESTOR, DTA_SISTEMA, IND_STATUS) 
VALUES 
(395279, 'Lais Martins Fracasso', '02092837001', TO_DATE('11/03/2032', 'DD/MM/YYYY'), TO_DATE('08/12/2034', 'DD/MM/YYYY'), '89179510078', TO_DATE('18/03/2025 09:04', 'DD/MM/YYYY HH24:MI'), 1);

