SCRIPT PARA ATUALIZAR FÉRIAS NA PROGRAMAÇÃO DE FÉRIAS INDIVIDUAIS COM DATAS DE RETORNO ERRADAS

--UPDATE PARA ALTERAR A DATA_RETORNO NA TABELA 'EXIBE AS INFORMAÇÕES DAS FÉRIAS DE TODOS OS COLABORADORES'

SELECT * FROM RHFP0327
WHERE COD_CONTRATO = 386162
AND DATA_RETORNO = '23/03/2022'

UPDATE RHFP0327
SET DATA_RETORNO = '06/03/2022'
WHERE DATA_RETORNO = '05/03/2022'
AND COD_CONTRATO = 386162


--UPDATE PARA ALTERAR A DATA_FIM E DATA_FIM_FRE DA TABELA 'HISTÓRICO DE AFASTAMENTOS DO CONTRATO'

SELECT * FROM RHFP0306
WHERE COD_CONTRATO = 386162

UPDATE RHFP0306
SET DATA_FIM_FRE = '06/03/2022', DATA_FIM = '06/03/2022'
WHERE DATA_FIM_FRE = '07/03/2022'
AND COD_CONTRATO = 386162


--SCRIPT PARA FAZER CONTAGEM DE DATAS

SELECT TO_DATE('14/02/2022', 'DD/MM/YYYY') + 20 FROM DUAL

SELECT TO_DATE('14/02/2022', 'DD/MM/YYYY') - TO_DATE('05/03/2022', 'DD/MM/YYYY') FROM DUAL


--SELECT PARA PUXAR OS DIAS DAS FÉRIAS E DO AFASTAMENTOS DO CONTRATO

SELECT PF.COD_CONTRATO, PF.DIAS_FERIAS_CONCED, PF.DIAS_ABONO_CONCED, PF.DIAS_FERIAS_GOZADOS, PF.DATA_FERIAS, PF.DATA_RETORNO, PF.DATA_FIM_ABONO,

       AF.DATA_INICIO AS DATA_INCIO_AFAST, AF.DATA_FIM AS DATA_FIM_AFAST, AF.DATA_FIM - AF.DATA_INICIO + 1 AS DIAS

FROM RHFP0327 PF, RHFP0306 AF

WHERE PF.DIAS_ABONO_CONCED > 0

  AND PF.COD_CONTRATO = AF.COD_CONTRATO

  AND TRUNC(PF.DATA_PREVISTA_FERIAS,'DD') = TRUNC(AF.DATA_INICIO,'DD')

  AND AF.COD_CAUSA_AFAST = 7

  AND AF.DATA_FIM - AF.DATA_INICIO + 1 > PF.DIAS_FERIAS_GOZADOS



