-VERSÃO ALTERNATIVA DE DADOS DOS GERENTES

--CREATE OR REPLACE VIEW V_DADOS_GERENTE AS
SELECT "COD_ORGANOGRAMA","DATA_INICIO","DATA_FIM","COD_CONTRATO" FROM RHFP0396 A
WHERE A.DATA_INICIO <= SYSDATE
AND A.DATA_FIM >= SYSDATE

