CREATE OR REPLACE VIEW V_STATUS_COLAB AS 
SELECT COD_CONTRATO, PF.NOME_PESSOA, 0 AS STATUS
FROM RHFP0300 RHFP0300, PESSOA_FISICA PF
WHERE RHFP0300.COD_FUNC = PF.COD_PESSOA
AND (RHFP0300.DATA_FIM IS NULL OR RHFP0300.DATA_FIM >= trunc(sysdate))
AND (RHFP0300.DATA_INICIO <= trunc(sysdate))
UNION ALL
SELECT COD_CONTRATO, PF.NOME_PESSOA, 1 AS STATUS
FROM RHFP0300 RHFP0300, PESSOA_FISICA PF
WHERE RHFP0300.COD_FUNC = PF.COD_PESSOA
AND (RHFP0300.DATA_FIM IS NOT NULL AND RHFP0300.DATA_FIM < trunc(sysdate))
AND (RHFP0300.DATA_INICIO <= trunc(sysdate))
UNION ALL
SELECT COD_CONTRATO, PF.NOME_PESSOA, 1 AS STATUS
FROM RHFP0300 RHFP0300, PESSOA_FISICA PF
WHERE RHFP0300.COD_FUNC = PF.COD_PESSOA
AND (RHFP0300.DATA_INICIO > trunc(sysdate));