VIEW V_RESP_ORGANOGRAMA

SELECT DISTINCT RESP.COD_CONTRATO_RESP,
       PE.NOME_PESSOA,
       RESP.COD_ORGANOGRAMA_RESP,
       OP.COD_ORGANOGRAMA,
       ORG2.EDICAO_ORG,
       ORG1.NOME_ORGANOGRAMA
  FROM RHFP0397 RESP,
       RHFP0400 ORG1,
       RHFP0401 ORG2,
       RHFP0310 CTORG,
       RHFP0300 CT,
       PESSOA   PE,
       OPERORG OP
 WHERE RESP.COD_ORGANOGRAMA = ORG1.COD_ORGANOGRAMA
   AND ORG1.COD_ORGANOGRAMA = ORG2.COD_ORGANOGRAMA
   AND ORG2.COD_ORGANOGRAMA = CTORG.COD_ORGANOGRAMA
   AND CT.COD_CONTRATO = RESP.COD_CONTRATO_RESP
   AND PE.COD_PESSOA = CT.COD_FUNC
   AND OP.COD_ORGANOGRAMA = RESP.COD_ORGANOGRAMA
   AND RESP.DATA_FIM = '31/12/2999'
   AND ORG2.DATA_FIM = '31/12/2999'
   AND ORG2.EDICAO_NIVEL2 = '008'
;