SELECT CO.COD_CONTRATO
FROM RHFP0401 EST, RHFP0310 CO, RHFP1026 VL, RHFP0300 CT
WHERE EST.COD_ORGANOGRAMA = CO.COD_ORGANOGRAMA
  AND CT.COD_CONTRATO = CO.COD_CONTRATO
  AND (CT.DATA_FIM IS NULL OR CT.DATA_FIM >= TRUNC(SYSDATE))
  AND :DATA_REFERENCIA BETWEEN CO.DATA_INICIO AND CO.DATA_FIM
  AND :DATA_REFERENCIA BETWEEN EST.DATA_INICIO AND EST.DATA_FIM
  AND EST.COD_NIVEL3 = VL.ARGUMENTO_1
  AND (EST.COD_NIVEL2 IN (4, 276) OR
       VL.COD_VL = 46)
       and co.cod_contrato between 390390 and 390410;




/*TENHO QUE VERIFICAR ESSE SELECT PARA DESCOBRIR NAS VARIAVEIS LIVRES DO PQ NÃO ESTÁ PUXANDO OS CONTRATOS
NAS GERAÇÕES DE OCORRENCIAS*/